<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/goods/goods.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('goods'); ?></div>
                    <div class="list-group">
                        <a href="/user/goods" class="list-group-item"><?php echo $this->translate('goodsME'); ?></a>
                        <a href="/user/purchase" class="list-group-item"><?php echo $this->translate('goodsBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 goods-main">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if (!empty($this->errMsg)): ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Warning!</strong> <?php echo $this->errMsg; ?>
                        </div>
                        <?php endif; ?>

                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('edit').$this->translate('goodsME');?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <form class="form-horizontal goods-main-edit" action="#" method="post" id="goods_edit_form" name="goods_edit_form">
                                        <div class="form-group">
                                            <label for="productName" class="col-sm-2 control-label"><?php echo $this->translate('productNAME'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="productName" id="productName" placeholder="" value="<?php echo $this->goods['productName']; ?>"  required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="productEnName" class="col-sm-2 control-label"><?php echo $this->translate('productENNAME'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="productEnName" id="productEnName" placeholder="" value="<?php echo $this->goods['productEnName']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="productBrand" class="col-sm-2 control-label"><?php echo $this->translate('brand'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="productBrand" id="productBrand" placeholder="" value="<?php echo $this->goods['productBrand']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="productModel" class="col-sm-2 control-label"><?php echo $this->translate('model'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="productModel" id="productModel" placeholder="" value="<?php echo $this->goods['productModel']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="crnCode" class="col-sm-2 control-label"><?php echo $this->translate('unitPrice'); ?></label>
                                            <div class="col-sm-2">
                                                <select class="form-control" name="crnCode" id="crnCode">
                                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY'], $this->goods['crnCode']); ?>
                                                </select>
                                            </div>
                                            <div class="col-sm-3">
                                                <input type="text" class="form-control" name="unitPrice" id="unitPrice" placeholder="" value="<?php echo $this->goods['unitPrice']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="pricingUnit" class="col-sm-2 control-label"><?php echo $this->translate('pricingUnit'); ?></label>
                                            <div class="col-sm-2">
                                                <select class="form-control" name="pricingUnit" id="pricingUnit">
                                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->goods['pricingUnit']); ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="hscode" class="col-sm-2 control-label"><?php echo $this->translate('HSCODE'); ?></label>
                                            <div class="col-sm-9">
                                                <select name="hscode" id="hscode" class="selectpicker form-control" data-live-search="true">
                                                    <option value=""><?php echo $this->translate('et_select'); ?></option>
                                                </select>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="authModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content"></div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
            // if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        var hscodeSelect = $("#hscode");
        $(hscodeSelect).on('shown.bs.select', function (e) {
            $(hscodeSelect).prev().find("input").keyup(function () {
                $(hscodeSelect).prev().find("input").attr('id', "hscodeInput"); //为input增加id属性
                var hscodeInput = $("#hscodeInput");
                var keyword = $(hscodeInput).val();
                var hscodeQuery = '/user/common/hscode-ajax';
                $.ajax({
                    type: "POST",
                    url: hscodeQuery,
                    data: {
                        keyword: keyword
                    },
                    dataType: "json",
                    success: function (data) {
                        var optionString = "";
                        $.each(data, function (i, item) {
                            // console.log(item);
                            optionString += "<option value='" + item.hscode + "'>" + item.hscode + " (" + item.codeName + ")</option>";
                        });

                        $(hscodeSelect).html("");
                        $(hscodeSelect).append(optionString);
                        $(hscodeSelect).selectpicker('refresh');
                    }
                });
            })
        });
    });
</script>
</body>
</html>
