<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/goods/goods.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('goods'); ?></div>
                    <div class="list-group">
                        <a href="/user/goods" class="list-group-item"><?php echo $this->translate('goodsME'); ?></a>
                        <a href="/user/purchase" class="list-group-item"><?php echo $this->translate('goodsBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('goodsME'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->resultMsg)): ?>
                        <div class="alert alert-success alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                        </div>
                        <?php endif; ?>

                        <ul id="goodsTabs" class="nav nav-tabs nav-justified">
                            <li role="presentation" class="active">
                                <a href="#forActivate" data-productStatus="03" aria-controls="forActivate" role="tab" data-toggle="tab"><?php echo $this->translate('valid'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-productStatus="01" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('forReview'); ?>&nbsp;<span class="badge" data-productStatus="01"><?php echo $this->countSaleProduct['01']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-productStatus="02" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('forConfirm'); ?>&nbsp;<span class="badge" data-productStatus="02"><?php echo $this->countSaleProduct['02']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-productStatus="04" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('rejected'); ?>&nbsp;<span class="badge" data-productStatus="04"><?php echo $this->countSaleProduct['04']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-productStatus="00" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('draft'); ?>&nbsp;<span class="badge" data-productStatus="00"><?php echo $this->countSaleProduct['00']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-productStatus="05" aria-controls="forActivate" role="tab" data-toggle="tab"><?php echo $this->translate('disable'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="forActivate">
                                <form class="form-horizontal" action="javascript:void(0)" onsubmit="goodsSearch()" id="goods_search_form">
                                    <div class="form-group" style="margin-bottom: 0 !important;">
                                        <label for="keyword" class="sr-only">keyword</label>
                                        <div class="col-sm-6">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fas fa-search"></i></span>
                                                <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('INPkw_goods');?>">
                                                <input type="hidden" name="productStatus" id="productStatus" value="<?php echo $this->productStatus?>">
                                            </div>
                                        </div>
                                        <div class="col-sm-1">
                                            <button type="submit" class="btn btn-primary"> Go </button>
                                        </div>
                                        <?php if ($this->CompAdmin == true): ?>
                                        <div class="col-sm-1 col-sm-offset-4">
                                            <a title="<?php echo $this->translate('add');?>" href="/user/goods/add" class="btn btn-default">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                </form>

                                <!-- Table -->
                                <table id="goodsListTable"></table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
    var dataDict = {};

    $().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $("#goodsTabs a").click(function () {
            $("#productStatus").val($(this).attr("data-productStatus"));
            goodsSearch();
        });

        $('#goodsTabs a[data-productStatus="<?php echo $this->productStatus; ?>"]').tab('show');

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = new Array("ECOMM_STATUS");
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#goodsListTable').bootstrapTable({
                    url: '/user/goods/goods-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search,
                            productStatus: $("#productStatus").val()
                        };
                    },
                    columns: [{
                        field: 'attachmentList',
                        title: '',
                        formatter: function (value, row) {
                            var imgUrl = '<?php echo $this->attachUrl; ?>';
                            imgUrl += '/doc/download.action?sid=' + '<?php echo session_id(); ?>' ;
                            var altStr = '';
                            if (value === undefined || value === '' || value === null) {
                                imgUrl = '/ky/images/goods_tx.png';
                            } else {
                                $.each(value, function (i, item) {
                                    imgUrl += '&nid=' + item.attachID + '&vid=' + item.verifyID + '&size=MIDDLE';
                                    altStr = item.name;
                                });
                            }

                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;

                            return '<a href="' + href + '">' + '<img src="' + imgUrl + '" alt="' + altStr + '" class="img-rounded" style="width: 64px; height: 64px;">' + '</a>';
                        }
                    },{
                        field: 'productName',
                        title: '<?php echo $this->translate("productNAME"); ?>',
                        formatter: function (value, row) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'productBrand',
                        title: '<?php echo $this->translate("brand"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'productModel',
                        title: '<?php echo $this->translate("model"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'hscode',
                        title: '<?php echo $this->translate("HSCODE"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'rebateRate',
                        title: '<?php echo $this->translate("rebateRate"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        formatter: function (value, row, index) {
                            var editTitle = "<?php echo $this->translate("edit");?>";
                            var copyTitle = "<?php echo $this->translate("copy");?>";
                            var disableTitle = "<?php echo $this->translate('disable');?>";
                            var validTitle = "<?php echo $this->translate('enable');?>";
                            var delTitle = "<?php echo $this->translate('delete');?>";
                            var confirmedTitle = "<?php echo $this->translate('confirmed');?>";
                            var submitForReviewTitle = "<?php echo $this->translate('submitForReview');?>";
                            var base = new Base64();
                            var resultEnCode = base.encode(row.productID);
                            var href = "/user/goods/edit?"+resultEnCode;
                            var copyHref = "/user/goods/copy?"+resultEnCode;

                            var result = '';
                            <?php if ($this->CompProductAdmin == true || $this->CompOrderAdmin == true): ?>
                            if (row.productStatus !== '05') {
                                result += '<a title="' + editTitle+ '" href="' + href + '">'
                                    + '<i class="far fa-edit"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.productStatus === '00' || row.productStatus === '01' || row.productStatus === '03') {
                                result += '<a title="' + copyTitle+ '" href="' + copyHref + '">'
                                    + '<i class="far fa-copy"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.allowInvalid === true) {
                                result += '<a href="javascript:void(0)" title="' + disableTitle + '" id="' + row.productID + '" data-url="/user/goods/invalid" '
                                    + 'data-msg1="<?php echo $this->translate("is_invalid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_invalid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_invalid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="fas fa-ban"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.allowDelete === true) {
                                result += '<a href="javascript:void(0)" title="' + delTitle + '" id="' + row.productID + '" data-url="/user/goods/del" '
                                    + 'data-msg1="<?php echo $this->translate("is_delete");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_del_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_del_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-trash-alt"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.allowValid === true) {
                                result += '<a href="javascript:void(0)" title="' + validTitle + '" id="' + row.productID + '" data-url="/user/goods/valid" '
                                    + 'data-msg1="<?php echo $this->translate("is_valid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_valid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_valid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.allowConfirm === true) {
                                result += '<a href="javascript:void(0)" title="' + confirmedTitle + '" id="' + row.productID + '" data-url="/user/goods/confirm" '
                                    + 'data-msg1="<?php echo $this->translate("is_confirm_goods");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_confirm_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_confirm_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.allowForReview === true) {
                                result += '<a href="javascript:void(0)" title="' + submitForReviewTitle + '" id="' + row.productID + '" data-url="/user/goods/for-review" '
                                    + 'data-msg1="<?php echo $this->translate("is_forReview");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_forReview_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_forReview_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>';
                            }
                            <?php endif; ?>

                            return result;
                        }
                    }]
                });
            }
        });

        $("#searchContactBtn").click(function () {
            goodsSearch();
        });
	});

	function goodsSearch() {
        var goodsListTable = $('#goodsListTable');
        var options = {
            query:{
                keyword: $("#keyword").val(),
                productStatus: $("#productStatus").val()
            }
        };
        $(goodsListTable).bootstrapTable('refresh', options);
    }

    function doOption(obj) {
        var url = $(obj).attr('data-url');
        var id = $(obj).attr('id');
        var msg1 = $(obj).attr('data-msg1');
        var msg2 = $(obj).attr('data-msg2');
        var msg3 = $(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title: false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
        }, function () {
            $.post(url,
                {'delID': id},
                function (data) {
                    var listTable = $('#goodsListTable');

                    if (data.status === 1) {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg2 + '</span>', {
                            skin: 'del-class',
                            icon: 1
                        });
                        goodsSearch();
                        refreshBadge();
                    } else {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg3 + '</span><br>' + data.error, {
                            skin: 'del-class',
                            icon: 0
                        });
                        goodsSearch();
                    }
                }, "json");
        }, function () {
            layer.closeAll();
        });
    }

    function refreshBadge() {
        var countSaleProductQuery = '/user/goods/count-sale-product-ajax';
        $.ajax({
            type: "POST",
            url: countSaleProductQuery,
            dataType: "json",
            success: function (data) {
                var forReview = "", forConfirm = "", rejected = "", draft = "";
                $.each(data, function (i, item) {
                    if (i === '01') {
                        forReview = item;
                    } else if (i === '02') {
                        forConfirm = item;
                    } else if (i === '04') {
                        rejected = item;
                    } else if (i === '00') {
                        draft = item;
                    }
                });

                $('.badge[data-productStatus="01"]').html(forReview);
                $('.badge[data-productStatus="02"]').html(forConfirm);
                $('.badge[data-productStatus="04"]').html(rejected);
                $('.badge[data-productStatus="00"]').html(draft);
            }
        });
    }
</script>
</body>
</html>
