<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/goods/goods.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('goods'); ?></div>
                    <div class="list-group">
                        <a href="/user/goods" class="list-group-item"><?php echo $this->translate('goodsME'); ?></a>
                        <a href="/user/purchase" class="list-group-item"><?php echo $this->translate('goodsBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('goodsME'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->errMsg)): ?>
                        <div class="alert alert-success alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <p><?php echo $this->errMsg; ?>!</p>
                        </div>
                        <?php endif; ?>

                        <ul class="nav nav-pills">
                            <li role="presentation" class="active"><a href="#goods_search_form"><?php echo $this->translate('valid'); ?></a></li>
                            <li role="presentation"><a href="#goods_search_form"><?php echo $this->translate('forReview'); ?></a></li>
                            <li role="presentation"><a href="#goods_search_form"><?php echo $this->translate('forConfirm'); ?></a></li>
                            <li role="presentation"><a href="#goods_search_form"><?php echo $this->translate('rejected'); ?></a></li>
                            <li role="presentation"><a href="#goods_search_form"><?php echo $this->translate('draft'); ?></a></li>
                            <li role="presentation"><a href="#goods_search_form"><?php echo $this->translate('disable'); ?></a></li>
                        </ul>

                        <form class="form-horizontal" action="javascript:void(0)" onsubmit="contactSearch()" id="goods_search_form">
                            <div class="form-group" style="margin-bottom: 0 !important;">
                                <label for="keyword" class="sr-only">keyword</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fas fa-search"></i></span>
                                        <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('INPkw_goods');?>">
                                    </div>
                                </div>
                                <div class="col-sm-1">
                                    <button type="submit" class="btn btn-primary"> Go </button>
                                </div>
                                <?php if ($this->CompAdmin == true): ?>
                                <div class="col-sm-1 col-sm-pull-4">
                                    <a title="<?php echo $this->translate('add');?>" href="/user/goods/add" class="btn btn-default">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>
                                <?php endif; ?>
                            </div>
                        </form>
                    </div>

                    <!-- Table -->
                    <table id="goodsListTable"></table>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
    var dataDict = {};

    $().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        var dataDictQuery = '/user/account/dict-ajax';
        var dictCode = new Array("ECOMM_STATUS");
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#contactListTable').bootstrapTable({
                    url: '/user/account/contactlistajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search
                        };
                    },
                    columns: [{
                        field: 'name',
                        title: '<?php echo $this->translate("name"); ?>',
                        formatter: function (value, row) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.contactID);
                            var href = "/user/account/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'ecommloginname',
                        title: '<?php echo $this->translate("username"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '') {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.contactID);
                            var href = "/user/account/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'ecommstatus',
                        title: '<?php echo $this->translate("userP"); ?>',
                        formatter: function (value) {
                            var result = "-";
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'ECOMM_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                        //}, {
                        //    field: 'ecommrole',
                        //    title: '<?php //echo $this->translate("userROLE"); ?>//'
                    }, {
                        field: 'contactStatus',
                        title: '<?php echo $this->translate("userPT"); ?>',
                        formatter: function (value) {
                            return (value === '01') ? '<?php echo $this->translate('normal') ?>' : '<?php echo $this->translate('disable'); ?>';
                        }
                    }, {
                        field: 'isDefaultPublic',
                        title: '<?php echo $this->translate("accountDF"); ?>',
                        formatter: function (value, row) {
                            var result = (value === true) ? '<?php echo $this->translate('yes') ?>' : '<?php echo $this->translate('no'); ?>';
                            <?php if ($this->CompAdmin == true): ?>
                            result = '<a href="javascript:void(0)" id="' + row.contactID + '" data-url="/user/account/default" data-msg1="<?php echo $this->translate("is_default");?>" '
                                + 'data-msg2="<?php echo $this->translate("tip_default_success");?>" '
                                + 'data-msg3="<?php echo $this->translate("tip_default_fail");?>" '
                                + 'onclick="doOption(this);" '
                                + '>'
                                + result
                                + '</a>';
                            <?php endif; ?>
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        formatter: function (value, row, index) {
                            var editTitle = "<?php echo $this->translate("edit");?>";
                            var disableTitle = "<?php echo $this->translate('disable');?>";
                            var validTitle = "<?php echo $this->translate('enable');?>";
                            var base = new Base64();
                            var resultEnCode = base.encode(row.contactID);
                            var href = "/user/account/edit?"+resultEnCode;

                            var result = '<a title="' + editTitle+ '" href="' + href + '">'
                                + '<i class="far fa-edit"></i>'
                                + '</a>&nbsp;';
                            <?php if ($this->CompAdmin == true): ?>
                            if (row.contactStatus === '01') {
                                result += '<a href="javascript:void(0)" title="' + disableTitle + '" id="' + row.contactID + '" data-url="/user/account/invalid" data-msg1="<?php echo $this->translate("is_invalid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_invalid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_invalid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="fas fa-ban"></i>'
                                    + '</a>';
                            }

                            if (row.contactStatus === '02') {
                                result += '<a href="javascript:void(0)" title="' + validTitle + '" id="' + row.contactID + '" data-url="/user/account/valid" data-msg1="<?php echo $this->translate("is_valid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_valid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_valid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>';
                            }
                            <?php endif; ?>

                            return result;
                        }
                    }]
                });
            }
        });

        $("#searchContactBtn").click(function () {
            goodsSearch();
        });

        $("#shoAllContact").click(function () {
            var goodsListTable = $('#goodsListTable');
            var options = {};
            if ($(this).is(':checked')) {
                options = {
                    query:{
                        contactStatus: "all"
                    }
                };
            }
            $(goodsListTable).bootstrapTable('refresh', options);
        });
	});

	function goodsSearch() {
        var goodsListTable = $('#goodsListTable');
        var options = {
            query:{
                keyword: $("#keyword").val()
            }
        };
        $(goodsListTable).bootstrapTable('refresh', options);
    }

    function doOption(obj) {
        var url = $(obj).attr('data-url');
        var id = $(obj).attr('id');
        var msg1 = $(obj).attr('data-msg1');
        var msg2 = $(obj).attr('data-msg2');
        var msg3 = $(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title: false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
        }, function () {
            $.post(url,
                {'delID': id},
                function (data) {
                    var contactListTable = $('#contactListTable');

                    if (data.status === 1) {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg2 + '</span>', {
                            skin: 'del-class',
                            icon: 1
                        });
                        $(contactListTable).bootstrapTable('refresh');
                    } else {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg3 + '</span><br>' + data.error, {
                            skin: 'del-class',
                            icon: 0
                        });
                        $(contactListTable).bootstrapTable('refresh');
                    }
                }, "json");

        }, function () {
            layer.closeAll();
        });
    }
</script>
</body>
</html>
