<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/goods/goods.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <!-- Viewer -->
    <link href="/ky/viewer-1.0.0-dist/viewer.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('goods'); ?></div>
                    <div class="list-group">
                        <a href="/user/goods" class="list-group-item"><?php echo $this->translate('goodsME'); ?></a>
                        <a href="/user/purchase" class="list-group-item"><?php echo $this->translate('purProduct'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 goods-view">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('goodsINF'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('goodsAttachment'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <h3>
                                        <?php if (($this->CompProductAdmin == true || $this->CompOrderAdmin == true) && $this->goods['productStatus'] != 05): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/goods/edit?' . base64_encode($this->goods['productID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->goods['productName']; ?>
                                    </h3>

                                    <dl class="dl-horizontal">
                                        <dt><?php echo $this->translate('productNAME'); ?></dt>
                                        <dd><?php echo $this->goods['productName']; ?></dd>

                                        <dt><?php echo $this->translate('productENNAME'); ?></dt>
                                        <dd><?php echo $this->goods['productEnName']; ?></dd>

                                        <dt><?php echo $this->translate('brand'); ?></dt>
                                        <dd><?php echo $this->goods['productBrand']; ?></dd>

                                        <dt><?php echo $this->translate('model'); ?></dt>
                                        <dd><?php echo $this->goods['productModel']; ?></dd>

                                        <dt><?php echo $this->translate('unitPrice'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY'], $this->goods['crnCode']); ?>&nbsp;
                                            <?php echo $this->goods["unitPrice"];?>
                                        </dd>

                                        <dt><?php echo $this->translate('pricingUnit'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->goods['pricingUnit']); ?>
                                        </dd>

                                        <dt><?php echo $this->translate('HSCODE'); ?></dt>
                                        <dd>
                                            <?php if (!empty($this->goods["hscode"])):?>
                                            <?php echo $this->goods["hscode"] . "&nbsp;(" . $this->goods["productHSCode"]["codeName"] . ")"; ?>
                                            <?php endif; ?>
                                        </dd>

                                        <dt><?php echo $this->translate('legalPricingUnit'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $this->goods['legalPricingUnit']); ?>
                                        </dd>

                                        <dt><?php echo $this->translate('rebateRate'); ?></dt>
                                        <dd>
                                            <?php echo $this->goods["rebateRate"] * 100; ?>&nbsp;%
                                        </dd>

                                        <dt><?php echo $this->translate('taxRate'); ?></dt>
                                        <dd>
                                            <?php echo $this->goods["taxRate"] * 100; ?>&nbsp;%
                                        </dd>

                                        <dt><?php echo $this->translate('declareElements'); ?></dt>
                                        <dd><?php echo $this->goods['declareElements']; ?></dd>

                                        <dt><?php echo $this->translate('productSize'); ?></dt>
                                        <dd><?php echo $this->goods['productSize']; ?></dd>

                                        <dt><?php echo $this->translate('functionUsage'); ?></dt>
                                        <dd><?php echo $this->goods["functionUsage"]; ?></dd>

                                        <dt><?php echo $this->translate('productMaterial'); ?></dt>
                                        <dd><?php echo $this->goods["productMaterial"]; ?></dd>

                                        <dt><?php echo $this->translate('productionMode'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['PRODUCT_PRODUCTION_MODE'], $this->userLangCode, $this->dic_Setting['PRODUCT_PRODUCTION_MODE'], $this->goods['productionMode']); ?>
                                        </dd>

                                        <?php if ($this->goods["productionMode"] == 02): ?>
                                        <dt><?php echo $this->translate('supplierName'); ?></dt>
                                        <dd><?php echo $this->goods["supplierName"]; ?></dd>

                                        <dt><?php echo $this->translate('purchaseUnitPrice'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY'], $this->goods["purchaseCrnCode"]); ?>&nbsp;
                                            <?php echo $this->goods["purchaseUnitPrice"]; ?>
                                        </dd>
                                        <?php endif; ?>

                                        <dt><?php echo $this->translate('packageTYPE'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['PRODUCT_PACKING_TYPE'], $this->userLangCode, $this->dic_Setting['PRODUCT_PACKING_TYPE'], $this->goods["packingType"]); ?>
                                        </dd>

                                        <dt><?php echo $this->translate('packingVolume'); ?></dt>
                                        <dd><?php echo $this->goods["packingVolume"]; ?>&nbsp;CBM</dd>

                                        <dt><?php echo $this->translate('grossWeight'); ?></dt>
                                        <dd><?php echo $this->goods["grossWeight"]; ?>&nbsp;KGS</dd>

                                        <dt><?php echo $this->translate('netWeight'); ?></dt>
                                        <dd><?php echo $this->goods["netWeight"]; ?>&nbsp;KGS</dd>

                                        <dt><?php echo $this->translate('needInspection'); ?></dt>
                                        <dd>
                                            <?php if ($this->goods["needInspection"]) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            } ?>
                                        </dd>
                                    </dl>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="profile">
                                <div class="col-md-12">
                                    <?php echo $this->ShowWebuploader($this->goods['attachmentList'], $this->biz_Setting['PRODUCT'], $this->attach_Setting['PDPD'], "1", $this->goods['productID']); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- viewer -->
<script type="text/javascript" src="/ky/viewer-1.0.0-dist/viewer.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        // viewer
        // 先判断是否有图片, 再初始化viewer
        if ($(".img-view > li").length > 0) {
            $(".img-view").viewer({
                url: "data-original"
            });
        }
	});
</script>
</body>
</html>
