<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/module/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1>删除系统模块</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
    <table class="admin_list">
      <tr>
        <th>编号</th>
        <th>名称</th>
        <th>类型</th>
        <th>说明</th>
      </tr>
      <?php if(is_array($this->modules)):?>
      <?php foreach($this->modules as $module):?>
      <tr>
        <td><input type="checkbox" id="mod_id<?php echo ($module['priv_id'])?>" name="mod_id[]" checked value="<?php echo ($module['mod_id'])?>">
          <?php echo ($module['mod_id'])?></td>
        <td><?php echo ($module['mod_name'])?></td>
        <td><?php echo ($module['mod_type'])?></td>
        <td><?php echo ($module['mod_desc'])?></td>
      </tr>
      <?php endforeach; ?>
      <?php endif;?>
    </table>
    <div class="batch">
      <input type="submit" name="" value="确认删除" class="admin_bnt2">
    </div>
</form>
<?php echo $this->render("footer.phtml") ?>
