<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$('input[@type=checkbox][@name=checkAll]').each(function(){
		$(this).checkbox().toggle($(this).val());
	});
});
//删除
function deleteAll(){
	var ids="";
	$("[name='chose[]'][checked]").each(function(){
		ids+=$(this).val()+",";
	});
	ids=ids.substring(0,(ids.length-1));
	document.location = "<?php echo $this->BaseUrl();?>/module/delete/mod_ids/"+ids;
}
function doadd(){
	$("#post_form").validate({
		event: "keyup",
		rules: {
			mod_name: "required",
			mod_desc: "required"
		},
		messages: {
			mod_name: "名称不能为空！",
			mod_desc: "说明不能为空！"
		},
		submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
				target:     '#SeedMsgTxt',
				url:        '<?php echo $this->BaseUrl();?>/module/add',
				success: function() {
				}
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
function doupdate(){
	$("#post_form").validate({
		event: "keyup",
		rules: {
			mod_id: "required",
			mod_name: "required",
			mod_desc: "required"
		},
		messages: {
			mod_id: "关键数据不能为空！",
			mod_name: "名称不能为空！",
			mod_desc: "说明不能为空！"
		},
		submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
				target:     '#SeedMsgTxt',
				url:        '<?php echo $this->BaseUrl();?>/module/update',
				success: function() {
				}
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
</script>
<h1>系统模块</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/module/'"/>
  </p>
</div>
<div class="admin_search">
<form name="post_form" method="post" action="" id="post_form" >
  <fieldset>
    <legend>编辑模块</legend>
    &nbsp;
    名称：
    <input type="text" name="mod_name" id="mod_name" value="<?php echo ($this->module['mod_name']);?>" style="width:100px;"/>
    类型：
    <select name="mod_type" id="mod_type" style="width:100px;">
      <option value="admin" <?php echo ($this->module['mod_type']=="admin")?"selected":"";?>>admin</option>
      <option value="front" <?php echo ($this->module['mod_type']=="front")?"selected":"";?>>front</option>
    </select>
    说明：
    <input type="text" name="mod_desc" id="mod_desc" value="<?php echo ($this->module['mod_desc']);?>" style="width:100px;"/>
    <?php if($this->module['mod_id']>0):?>
    <input type="hidden" name="mod_id" id="mod_id" value="<?php echo ($this->module['mod_id']);?>">
    <input name="updateConfirm" type="submit"  class="admin_bnt2"  value="修改" onclick="doupdate();"/>
    &nbsp;
    <?php else:?>
    <input type="submit" value="添加"  class="admin_bnt2"  onclick="doadd();"/>
    &nbsp;
    <?php endif;?>
    <input name="reset" type="reset"  class="admin_bnt2"  value="重置"/>
  </fieldset>
</form>
</div>
<table class="admin_list">
  <tr>
    <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
      <label for="checkAll">全选</label></th>
    <th>名称</th>
    <th>类型</th>
    <th>说明</th>
    <th>操作</th>
  </tr>
  <?php if(is_array($this->modules)):?>
  <?php foreach($this->modules as $module):?>
  <tr>
    <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($module['mod_id'])?>" class="ids_all"></td>
    <td><?php echo ($module['mod_name']);?></td>
    <td><?php echo ($module['mod_type']);?></td>
    <td><?php echo ($module['mod_desc']);?></td>
    <td><a href="<?php echo $this->BaseUrl();?>/module/index/mod_id/<?php echo ($module['mod_id']);?>"><img src="/images/center/edit.gif" title="编辑" alt="编辑"></a> <a href="<?php echo $this->BaseUrl();?>/moduleapi/index/mod_name/<?php echo ($module['mod_name']);?>_<?php echo ($module['mod_type']);?>"><img src="/images/center/set.gif" title="接口" alt="接口"></a> <a href="<?php echo $this->BaseUrl();?>/module/delete/mod_ids/<?php echo ($module['mod_id']);?>"><img src="/images/center/del.gif" title="删除" alt="删除"></a></td>
  </tr>
  <?php endforeach; ?>
  <?php endif;?>
</table>
<div class="batch">
  <input type="submit"  class="admin_bnt2"  name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
  &nbsp; </div>
<?php echo $this->render("footer.phtml") ?>
