<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/file/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>

<h1>删除文件</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
      <th>编号</th>
      <th>名称</th>
      <th>路径</th>
    </tr>
    <?php if(is_array($this->files)):?>
    <?php foreach($this->files as $file):?>
    <tr>
      <td><input type="checkbox" id="file_id[]" name="file_id[]" checked value="<?php echo ($file['file_id'])?>">
        <?php echo ($file['file_id'])?></td>
      <td><?php echo ($file['file_name']);?></td>
      <td><?php echo ($file['cate_path'])?></td>
    </tr>
    <?php endforeach; ?>
    <?php endif;?>
  </table>
  <div class="batch">
    <input type="submit" name="" value="确认删除" onclick="return confirm('确认删除选择记录？')">
  </div>
</form>
<?php echo $this->render("footer.phtml") ?> 