<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/czlui/favicon.ico" />
  <title>信天邮双十一钜惠</title>
<style type="text/css">
*{word-wrap:break-word;font-family:"Microsoft YaHei","宋体";}
html{color:#343434;font-size:12px;}
body,div,ol,ul,li,p,input,textarea,form,center,h1,h2,h3,h4,h5,h6,dl,dt,dd,img,select,table,tr,td,fieldset,legend,table,tr,td,th{margin:0; padding:0;}
body{_background-attachment:fixed; background-color: #ffffff;}
select,input,textarea{font-size:12px;vertical-align:middle;}  
select{font:12px Tahoma,Arial,Verdana;border:1px solid #ebebeb;height:24px;}
li{list-style:none;}
label input{width:14px;height:14px;vertical-align:middle;margin-right:5px;}
img{border:0;}
a{color:#f7f7f7;cursor:pointer;text-decoration:none;}
    #head{width:100%;display:block;text-align:center;background:#d00000 url(/static/sendyou/images/eleven/headbg.jpg) repeat-x;}
  .head_top{width:100%;display:block;height:40px;background-color: #e2e2e2;}
    .head_top p{width:970px;background:#e2e2e2;border:solid #eee;border-width:1px 0;display:inline-block;height:38px;line-height:38px;text-align:left;overflow:hidden;color:#666;}
      .head_top p a{color:#666;margin:0 10px;}
      .head_top p em{font-style:normal;color:#7cbe28;}
      .head_top p small{float:right;font-size:12px;}
  .header{width:970px;display:inline-block;text-align:left;padding:34px 0;height:72px;overflow:hidden;}
    .logo{float:left;height:72px;overflow:hidden;}
      .logo span{margin-right:40px; display:inline-block;}
    .header_r{float:right;height:72px;overflow:hidden;}
    .header_r img{margin-right: 30px;}
      .head_cart{height:32px;line-height:32px;}
        .head_cart a{padding:0 10px 0 50px;background:#7cbe28 url(/static/sendyou/images/czlui/head_cart.gif) no-repeat left;color:#fff;display:inline-block;vertical-align:middle;}
        .head_cart em{width:32px;height:32px;overflow:hidden;background:#A7A7A7;color:#fff;text-align:center;display:inline-block;font-style:normal;font-size:16px;vertical-align:middle;margin-left:1px;}

        .nav{width:100%;height:50px;background-color: #e2e2e2;display:block;text-align: center;}
    .navdiv{width:970px;height:50px;background-color: #e2e2e2;display:inline-block;z-index:2;float: auto;}
      .navdiv ul li{float:left;height:50px;font:16px/50px "Microsoft YaHei";padding:0 6px;}
          .navdiv ul li a{color:#E2E2E2;padding:0 18px;height:50px;display:block;}
          .navdiv ul li.crumb a{color:#D00000;}
          .navdiv ul li.crumb a:hover{color:#FDC740;}
        .navdiv ul li.nav_sort{width:170px;font-size:16px;padding:0;margin-right:15px;}
          .navdiv ul li.nav_sort a{background:#D00000 url(/static/sendyou/images/czlui/nav_sort.png) no-repeat 30px center;padding:0 0 0 25px;}
      .navdiv p{width:258px;height:28px;padding:11px 0;float:right;}

#content{width:100%;display:block;text-align:center;background-color: #fdc740;}
  .bigdiv{width:970px;display:inline-block;text-align:left;padding-top:10px;}
    .layout{width:100%;display:block;overflow:hidden;padding-bottom:10px;}
    .banner{width:100%;display:block;padding:10px 0;}
      .banner img{width:100%; display:block;}


.main{width:100%;height:520px;float:left;position:relative;}
  .item_show{width:100%;height:520px;overflow:hidden;float:left;position:relative;}

.yybjbig{width:100%;display:block;overflow:hidden;background-color: #d9c12d;}
    .yybjbig ul{width:970px;overflow:hidden;position:relative;background-color: #d9c12d;}
      .yybjbig ul li{float:left;padding:0 5px;overflow:hidden;}
      .yybjbig ul li img{width: 475px;}
      .yybjbig .title{width: 970px;height: 50px; background-color: #00791c;}
        .yybjbig .title b{width: 100px; font:20px/50px "Microsoft YaHei";color: #ffffff;float: left;margin-left: 5px;}
        .yybjbig .title p{font:16px/55px "Microsoft YaHei";color: #ffffff;float: left;}
        .yybjsmall ul{width:970px;overflow:hidden;position:relative;background-color: #d9c12d;}
        .yybjsmall ul li{float:left;padding:0 5px;overflow:hidden;}
        .yybjsmall ul li img{width: 313px;}

        .myyp .title{width: 970px;height: 50px; background-color: #00791c;}
        .myyp .title b{width: 100px; font:20px/50px "Microsoft YaHei";color: #ffffff;float: left;margin-left: 5px;}
        .myyp .title p{font:16px/55px "Microsoft YaHei";color: #ffffff;float: left;}
        .myyp ul{width:970px;overflow:hidden;position:relative;background-color: #d9c12d;}
        .myyp ul li{float:left;padding:0 5px;overflow:hidden;}
        .myyp ul li img{width: 313px;}
        
        .mzhf .title{width: 970px;height: 50px; background-color: #00791c;}
        .mzhf .title b{width: 100px; font:20px/50px "Microsoft YaHei";color: #ffffff;float: left;margin-left: 5px;}
        .mzhf .title p{font:16px/55px "Microsoft YaHei";color: #ffffff;float: left;}
        .mzhf ul{width:970px;overflow:hidden;position:relative;background-color: #d9c12d;}
        .mzhf ul li{float:left;padding:0 5px;overflow:hidden;}
        .mzhf ul li img{width: 313px;}

        .grhl .title{width: 970px;height: 50px; background-color: #00791c;}
        .grhl .title b{width: 100px; font:20px/50px "Microsoft YaHei";color: #ffffff;float: left;margin-left: 5px;}
        .grhl .title p{font:16px/55px "Microsoft YaHei";color: #ffffff;float: left;}
        .grhl ul{width:970px;overflow:hidden;position:relative;background-color: #d9c12d;}
        .grhl ul li{float:left;padding:0 5px;overflow:hidden;}
        .grhl ul li img{width: 313px;}

#footer{width:100%;display:block;text-align:center;background-color: #ffffff;}
  .guidediv{width:100%;background:#7cbe28 url(/static/sendyou/images/czlui/guidediv.png) repeat-x top;display:block;}
    .guide{width:970px; display:inline-block;background:#7cbe28;}
      .guide_top{padding:15px 0;border-top:2px solid #42bb48;}
      .guide_logo{float: left;}
      .guide_code{float: left;margin:12px;}
          .guide_cont dl{padding:5px 0 0 55px;width:100px;float:left;text-align:left;color:#f7f7f7;}
            .guide_cont dl dt{font:18px/24px "Microsoft YaHei";height:24px;overflow:hidden;padding-bottom:10px;color:#ffffff;}
            .guide_cont dl dd{width:100%;height:26px;line-height:26px;overflow:hidden;}
  .copyrightdiv{width:100%; display:block;background:#008028;padding: 15px 0;color: #f7f7f7;}
    .copyright{width:970px;display:inline-block;background:#008028;}
      .copyright a{margin:0 15px;} 
</style>
    </head>
    <body>
        <div id="head">
        	<div class="head_top">
            	<p>
                	<small>
                        <a href="/user/register">订单查询</a>
                        <a href="/user/register">帮助中心</a>
                        <a href="/user/register">我的信天邮</a>
                    </small>
                    <span>
                    <a>欢迎来到信天邮</a> | <a href="/user/login">登录</a> | <a href="/user/register">注册</a> 
                    </span>
                </p>
            </div>
            <div class="header">
            	<div class="logo">
                	<span><a href="/"><img src="/static/sendyou/images/eleven/logo.png" /></a></span>
              </div>
                <div class="header_r">
                    <img src="/static/sendyou/images/eleven/state.png">
                </div>   
            </div>
        </div>
    <div class="nav">
        <div class="navdiv">
            <ul>
                <li class="nav_sort"><a>所有商品分类</a></li>
                <li class="crumb"><a href="/" target="_blank">首页</a></li>
                <li class="crumb"><a href="/merchants" target="_blank">进驻商家</a></li>
                <li class="crumb"><a href="/help" target="_blank">服务指南</a></li>
                <li class="crumb"><a href="/about/contact.html" target="_blank">联系我们</a></li>
                <li class="crumb"><a href="/groups" target="_blank">真划算</a></li>
                <li class="crumb"><a href="<?php echo $this->seed_Setting['website'];?>">香港信天邮</a></li>
                <li class="crumb"><a href="/czl" target="_blank"> 采芝林</a></li>
            </ul>
             <form id="good_search" name="good_search" method="get" action='/search'>
            <p>
                <input class="s_txt" name="keyword" type="text" value="请输入关键词" onfocus="if(value==defaultValue){value='';this.style.color='#000'}" onblur="if(!value){value=defaultValue;this.style.color='#999'}" style="color: rgb(153, 153, 153);"/>
                <input class="s_bnt" name="" type="button" value="" onclick="javascript:a();"/>
            </p>
            </form>
        </div>
    </div>
<!--content内容-->
<div id="content">
    <div class="main">
        <div class="item_show">
                <a title="双十一线上活动">
                <div class="item" style="background:url(/static/sendyou/images/eleven/1920520.jpg) center  0 no-repeat ;width:100%;height:100%"></div>
                </a>
        </div>
    </div>
    <div class="bigdiv">
        <div class="layout">
            <div class="yybjbig">
                <div class="title">
                <b>营养保健：</b><p>您可以不知道，但健康必须拥有</p>
                </div>
                <ul>
                    <li><a href="http://www.sendtou.com/products/494.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj01.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/490.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj02.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/501.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj03.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/499.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj04.jpg"></a></li>
                </ul>
            </div>
            <div class="yybjsmall">
                <ul>
                    <li><a href="http://www.sendtou.com/products/1185.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj05.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/519.html#stock-546" target="_blank"><img src="/static/sendyou/images/eleven/yybj06.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1176.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj07.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1718.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj08.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1720.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj09.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1725.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj10.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1235.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj11.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1232.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj12.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1230.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj13.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/1208.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj14.jpg"></a></li>
                    <li><a href="http://www.sendtou.hk/products/630.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj15.jpg"></a></li>
                    <li><a href="http://www.sendtou.hk/products/1937.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj16.jpg"></a></li>
                    <li><a href="http://www.sendtou.hk/products/1944.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj17.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/503.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj18.jpg"></a></li>
                    <li><a href="http://www.sendtou.hk/products/633.html" target="_blank"><img src="/static/sendyou/images/eleven/yybj19.jpg"></a></li>
                </ul>
            </div>
        </div>
    <div class="layout">
        <div class="myyp">
                <div class="title">
                <b>母婴用品：</b><p>海外直邮，放心奶源</p>
                </div>
                <ul>
                    <li><a href="http://www.sendtou.com/products/162.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp01.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/163.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp02.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/165.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp03.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/166.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp04.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/167.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp05.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/169.html" target="_blank" target="_blank"><img src="/static/sendyou/images/eleven/myyp06.jpg"></a></li>
                </ul>
            </div>
    </div>
    <div class="layout">
        <div class="mzhf">
                <div class="title">
                <b>美妆护肤：</b><p>美丽永远不停止</p>
                </div>
                <ul>
                    <li><a href="http://www.sendtou.com/products/406.html" target="_blank"><img src="/static/sendyou/images/eleven/mzhf01.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/404.html" target="_blank"><img src="/static/sendyou/images/eleven/mzhf02.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/473.html" target="_blank"><img src="/static/sendyou/images/eleven/mzhf03.jpg"></a></li>
                </ul>
            </div>
    </div>
    <div class="layout">
        <div class="grhl">
            <div class="title">
            <b>个人护理：</b><p>细心的呵护</p>
            </div>
                <ul>
                    <li><a href="http://www.sendtou.com/products/464.html" target="_blank"><img src="/static/sendyou/images/eleven/grhl01.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/465.html" target="_blank"><img src="/static/sendyou/images/eleven/grhl02.jpg"></a></li>
                    <li><a href="http://www.sendtou.com/products/395.html" target="_blank"><img src="/static/sendyou/images/eleven/grhl03.jpg"></a></li>
                </ul>
        </div>
    </div>
</div>

<div id="footer">
        <div class="guide_top">
            <?php $charts = $this->fetchCharts('www_index_guide');?>
            <?php if(is_array($charts) && count($charts)>0):?>
            <?php foreach ($charts as $k=>$chart):?>
            <img src="/static/sendyou/images/czlui/guide_brand.png" />
            <?php endforeach;?>
            <?php endif;?>
        </div>
     <div class="guidediv">
      <div class="guide">
              <?php
                  $helpM = new Home_Model_Help('home');
                  $helps = $helpM->fetchRows(array(0,5),array('parent'=>'0'),array('order_by ASC'));
                  if(is_array($helps) && count($helps) > 0){
                    foreach ($helps as $k=>$help){
                      $sub_helps = $helpM->fetchRows(null,array('parent'=>$help['help_id']),array('order_by ASC'));
                      $helps[$k]['sub_helps'] = $sub_helps;
                    }
                  }
              ?>
            <div class="guide_cont">
                <div class="guide_code"><img src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/eleven/guide_code.jpg" />
                </div>
                <div class="guide_tip">
                <?php if(is_array($helps)):?>
                <?php foreach ($helps as $help):?>
                    <dl>
                        <dt><?php echo $this->escape($help['help_title']);?></dt>
                        <?php if(is_array($help['sub_helps']) && count($help['sub_helps'])):?>
                        <?php foreach ($help['sub_helps'] as $sub_help):?>
                        <dd><a href="/help/<?php echo $sub_help['help_mark']?>.html"><?php echo $this->escape($sub_help['help_title']);?></a></dd>
                        <?php endforeach;?>
                        <?php endif;?>
                    </dl>
                 <?php endforeach;?>
                 <?php endif;?>
                 </div>
            </div>
      </div>
    </div>
    <div class="copyrightdiv">
      <div class="copyright">
          <?php echo $this->seed_Setting['footer'];?>
        </div>
    </div>
</div>
</body>
</html>