<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$('input[@type=checkbox][@name=checkAll]').each(function(){
		$(this).checkbox().toggle($(this).val());
	});
});
//删除
function deleteAll(){
	var ids="";
	$("[name='chose[]'][checked]").each(function(){
		ids+=$(this).val()+",";
	});
	ids=ids.substring(0,(ids.length-1));
	document.location = "<?php echo $this->BaseUrl();?>/moduleapi/delete?mod_name=<?php echo ($this->module['mod_name']);?>_<?php echo ($this->module['mod_type']);?>&api_ids="+ids;
}
function doadd(){
	$("#post_form").validate({
		event: "keyup",
		rules: {
			mod_name: "required",
			api_name: "required",
			api_desc: "required",
			api_url: "required"
		},
		messages: {
			mod_name: "模块没有选择！",
			api_name: "名称不能为空！",
			api_desc: "说明不能为空！",
			api_url: "路径不能为空！"
		},
		submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
				target:     '#SeedMsgTxt',
				url:        '<?php echo $this->BaseUrl();?>/moduleapi/add',
				success: function() {
				}
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
function doupdate(){
	$("#post_form").validate({
		event: "keyup",
		rules: {
			mod_name: "required",
			api_name: "required",
			api_desc: "required",
			api_url: "required"
		},
		messages: {
			mod_name: "模块没有选择！",
			api_name: "名称不能为空！",
			api_desc: "说明不能为空！",
			api_url: "路径不能为空！"
		},
		submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
				target:     '#SeedMsgTxt',
				url:        '<?php echo $this->BaseUrl();?>/moduleapi/update',
				success: function() {
				}
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
</script>

<h1>模块接口 - <?php echo ($this->module['mod_desc']);?></h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/moduleapi/index?mod_name=<?php echo ($this->module['mod_name']);?>_<?php echo ($this->module['mod_type']);?>'"/>
  </p>
</div>
<div class="admin_search">
  <form name="post_form" method="post" action="" id="post_form" >
    <fieldset>
      <legend>编辑接口</legend>
      &nbsp;
      名称：
      <input type="text" name="api_name" id="api_name" value="<?php echo ($this->api['api_name']);?>" style="width:100px;"/>
      说明：
      <input type="text" name="api_desc" id="api_desc" value="<?php echo ($this->api['api_desc']);?>" style="width:100px;"/>
      路径：
      <input type="text" name="api_url" id="api_url" value="<?php echo ($this->api['api_url']);?>" style="width:200px;"/>
      <input type="hidden" name="mod_name" id="mod_name" value="<?php echo ($this->module['mod_name']);?>_<?php echo ($this->module['mod_type']);?>">
      <?php if($this->api['api_id']>0):?>
      <input type="hidden" name="api_id" id="api_id" value="<?php echo ($this->api['api_id']);?>">
      <input name="updateConfirm" type="submit"   class="admin_bnt2"  value="修改" onclick="doupdate();"/>
      &nbsp;
      <?php else:?>
      <input type="submit" value="添加"  class="admin_bnt2"   onclick="doadd();"/>
      &nbsp;
      <?php endif;?>
      <input name="reset" type="reset"  class="admin_bnt2"   value="重置"/>
    </fieldset>
  </form>
</div>
<table class="admin_list">
  <tr>
    <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
      <label for="checkAll">全选</label></th>
    <th>名称</th>
    <th>说明</th>
    <th>路径</th>
    <th>操作</th>
  </tr>
  <?php if(is_array($this->apis)):?>
  <?php foreach($this->apis as $api):?>
  <tr>
    <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($api['api_id'])?>" class="ids_all"></td>
    <td><?php echo ($api['api_name']);?></td>
    <td><?php echo ($api['api_desc']);?></td>
    <td><?php echo ($api['api_url']);?></td>
    <td><a href="<?php echo $this->BaseUrl();?>/moduleapi/index?mod_name=<?php echo ($this->module['mod_name']);?>_<?php echo ($this->module['mod_type']);?>&api_id=<?php echo ($api['api_id']);?>"><img src="/images/center/edit.gif" title="编辑" alt="编辑"></a> <a href="<?php echo $this->BaseUrl();?>/moduleapi/delete?mod_name=<?php echo ($this->module['mod_name']);?>_<?php echo ($this->module['mod_type']);?>&api_ids=<?php echo ($api['api_id']);?>"><img src="/images/center/del.gif" title="删除" alt="删除"></a></td>
  </tr>
  <?php endforeach; ?>
  <?php endif;?>
</table>
</div>
<div class="batch">
  <input type="submit"  class="admin_bnt2"  name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
  &nbsp; </div>
<?php echo $this->render("footer.phtml") ?> 