<footer class="footer-body">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-7 col-md-offset-1">
				<p>Copyright © 2015-<?php echo date('Y')?> 深圳市快移网络科技控股有限公司 版权所有</p>
				<p><a href="http://www.beian.miit.gov.cn/">粤ICP备17023256号-1</a></p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3">
				<div class="pull-right">
                    <a href="javascript:void(0)" id="changeLanguage" data-code="<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>"><img src="/ky/images/language/<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>.png" style="margin-top: -5px; float: none; margin-right: 0; width: 16px;" /> <?php if ($this->userLangCode == "en_US") echo $this->translate('chinese'); else echo $this->translate('english'); ?></a>
				</div>
			</div>
		</div>
	</div>
</footer>
