<!-- Optional JavaScript -->
<script src="/ky/jquery-3.3.1/jquery-3.3.1.min.js"></script>
<!--<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>-->
<script src="/ky/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
<!--<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="/ky/jquery-validation-1.17.0-dist/jquery.validate.min.js"></script>
<script src="/ky/jquery-validation-1.17.0-dist/localization/messages_zh.js"></script>
<!-- layui -->
<script src="/ky/layer/layer.js"></script>
<script src="/ky/layui/layui.js"></script>
<script src="/ky/js/funLib.js"></script>

<script type="text/javascript">
    $(function () {
        $('.navbar-nav').find('a').each(function () {
            // if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
            if (this.href === document.location.href) {
                $('.navbar-nav').find('li').removeClass('active');
                $(this).parents("li").addClass('active'); // this.className = 'active';

                // console.log(this.href);
                // console.log(document.location.href);
                // console.log(this.href === document.location.href);
                // console.log(document.location.href.search(this.href) >= 0);
                // console.log($(this));
            } else {
                // $(this).parents("li").removeClass('active');
            }
        });
    });
</script>
