<footer class="footer-body">
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 hidden-xs">
				<h4>关于我们</h4>
				<p>提供营运资本咨询服务和更灵活的解决方案，改进营运资金成本和更好管理贸易风险。</p>
				<p>创新供应链金融服务模式：快移金融创始者及践行者。</p>
				<p>IFG的成员，充分利用全球经验，助中国的贸易合作伙伴，以加快国际化。</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<h4>联系我们</h4>
				<p>深圳市骏海威科技网络控股有限公司</p>
				<p><i class="fas fa-map-marker-alt" style="color: #f0ad4e;"></i> 深圳市罗湖区嘉宾路深化商业大厦1502</p>
				<p><i class="fas fa-phone-square" style="color: #f0ad4e;"></i> +86-755-82383762</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<img src="/ky/images/Email-index.png" class="img-responsive" alt="E-Mail">
				<img src="/ky/images/wechat.png" class="img-responsive" alt="WeChat">
				<img src="/ky/images/linkedIn.png" class="img-responsive" alt="LinkedIn">
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
				<p>Copyright © 2015-2017 快移交易 eTradeFast 版权所有</p>
				<p>粤ICP备17023256号-1</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="pull-right">
                    <a href="javascript:void(0)" id="changeLanguage" data-code="<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>"><img src="/ky/images/language/<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>.png" style="margin-top: -5px;" /> <?php if ($this->userLangCode == "en_US") echo $this->translate('chinese'); else echo $this->translate('english'); ?></a>
				</div>
			</div>
		</div>
	</div>
</footer>
