<footer class="footer-body">
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 hidden-xs">
				<h4><?php echo $this->translate('nav_about'); ?></h4>
				<p><?php echo $this->translate('aboutInfo_1'); ?></p>
				<p><?php echo $this->translate('aboutInfo_2'); ?></p>
				<p><?php echo $this->translate('aboutInfo_3'); ?></p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<h4><?php echo $this->translate('contactUS'); ?></h4>
				<p>深圳市快移科技网络控股有限公司</p>
				<p><i class="fas fa-map-marker-alt" style="color: #f0ad4e;"></i> 深圳市前海深港合作区前湾一路1号A栋201室</p>
				<p><i class="fas fa-phone-square" style="color: #f0ad4e;"></i> +86-755-82383763</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<img src="/ky/images/Email-index.png" class="img-responsive" alt="E-Mail">
				<img src="/ky/images/wechat.png" class="img-responsive" alt="WeChat">
                <img src="/qrcode/app" style="width: 64px; height: 64px;" class="img-responsive img-thumbnail" alt="App">
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
				<p>Copyright © 2015-2017 快移交易 eTradeFast 版权所有</p>
				<p>粤ICP备17023256号-1</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="pull-right">
                    <a href="javascript:void(0)" id="changeLanguage" data-code="<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>"><img src="/ky/images/language/<?php if ($this->userLangCode == "en_US") echo "zh_CN"; else echo "en_US"; ?>.png" style="margin-top: -5px;" /> <?php if ($this->userLangCode == "en_US") echo $this->translate('chinese'); else echo $this->translate('english'); ?></a>
				</div>
			</div>
		</div>
	</div>
</footer>
