<!-- Optional JavaScript -->
<script src="/ky/jquery-3.3.1/jquery-3.3.1.min.js"></script>
<!--<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>-->
<script src="/ky/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
<!--<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="/ky/jquery-validation-1.17.0-dist/jquery.validate.min.js"></script>
<script src="/ky/jquery-validation-1.17.0-dist/localization/messages_zh.js"></script>
<!-- layui -->
<script src="/ky/layer-v3.1.1/layer.js"></script>
<script src="/ky/layui-v2.3.0/layui.js"></script>
<script src="/ky/js/funLib.js"></script>
<script src="/ky/js/arithUtil.js"></script>
<script src="/ky/js/jquery.form.js"></script>

<script type="text/javascript">
    $(function () {
        $('.navbar-nav').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
            // if (this.href === document.location.href) {
                if (!$(this).parents("li").hasClass('active')) {
                    $('.navbar-nav').find('li').removeClass('active');
                    $(this).parents("li").addClass('active'); // this.className = 'active';
                }

                // console.log(this.href);
                // console.log(document.location.href);
                // console.log(this.href === document.location.href);
                // console.log(document.location.href.search(this.href) >= 0);
                // console.log($(this));
            }
        });

        setInterval(function(){
            updateRedisExpire();
        }, 3500000);

        $("#changeLanguage").click(function () {
            var langCodeChange = '/user/system/lang-code',
                langCode = $(this).attr("data-code");
            $.ajax({
                type: "POST",
                url: langCodeChange,
                data: {
                    langCode: langCode
                },
                dataType: "json",
                success: function (data) {
                    if (data) {
                        location.reload();
                    } else {
                        return false;
                    }
                }
            });
        });
    });

    // app qr
    var prodStr = 'https://www.etradefast.com';
    if (document.location.href.search(prodStr) >= 0) {
        $("#etradeApp").attr("href", "/app/etradefast.apk");
    } else {
        $("#etradeApp").attr("href", "/app/app-debug.apk");
    }

    var updateExpireUrl = '/user/common/update-redis-expire-ajax';
    function updateRedisExpire() {
        $.ajax({
            type: "GET",
            url: updateExpireUrl,
            data: {

            },
            dataType: "json",
            success: function (data) {

            }
        });
    }
</script>
