<!-- Optional JavaScript -->
<script src="/ky/jquery-3.3.1/jquery-3.3.1.min.js"></script>
<!--<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>-->
<script src="/ky/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
<!--<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->
<script src="/ky/js/jquery.validate.min.js"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/localization/messages_zh.js"></script>
<!-- layui -->
<script src="/ky/layer/layer.js"></script>
<script src="/ky/layui/layui.js"></script>
