	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
    <link href="/ky/bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet" media="all">
	<!--<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">-->
	<!-- font-awesome CSS -->
    <link href="/ky/css/fontawesome-free-5.5.0-web/css/fontawesome.min.css" rel="stylesheet" media="all">
    <!--<link href="/ky/css/fontawesome-free-5.0.10/web-fonts-with-css/css/fontawesome-all.min.css" rel="stylesheet" media="all">-->
	<!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">-->
	<!-- layui CSS -->
	<link href="/ky/layui-v2.3.0/css/layui.css" rel="stylesheet" media="all">

	<meta name="description" content="">
	<meta name="keywords" content="">

    <link rel="shortcut icon" href="/ky/images/favicon.ico" type="image/x-icon" />
