<nav class="navbar navbar-inverse navbar-static-top shadow">
    <div class="container">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/">
                <img alt="eTradeFast" title="eTradeFast" src="/ky/images/index/Logo_loginH75.png" style="height: 32px;">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">首页 <span class="sr-only">(current)</span></a></li>
                <!--<li><a href="#">Link</a></li>-->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">订单中心 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">销售订单</a></li>
                        <li><a href="#">采购订单</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">合作伙伴 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">我的买家</a></li>
                        <li><a href="#">我的卖家</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">端口管理 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">我的商品</a></li>
                        <li><a href="#">采购的商品</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
