<div class="container-fluid index-person-top">
    <div class="container">
        <div class="row pull-right">
            <ul class="list-inline">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->userLoginName; ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/index/edit">修改个人资料</a></li>
                        <li><a href="/user/logout"><?php echo $this->translate('nav_exit'); ?></a></li>
                    </ul>
                </li>
                <li><a href="/user/index/edit"><?php echo $this->translate('userINF'); ?></a></li>
                <li><a href="#">快移金融</a></li>
                <li><a href="#">手机快移</a></li>
            </ul>
        </div>
    </div>
</div>
<nav class="navbar navbar-inverse navbar-static-top index-header shadow">
    <div class="container">
        <div class="navbar-header">

            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand" href="/">
                <img alt="eTradeFast" title="eTradeFast" src="/ky/images/index/Logo_loginH75.png" style="height: 32px;">
            </a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#"><?php echo $this->translate('nav_index'); ?> <span class="sr-only">(current)</span></a></li>
                <!--<li><a href="#">Link</a></li>-->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate('orderIN'); ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/orderxs"><?php echo $this->translate('orderSALLE'); ?></a></li>
                        <li><a href="/user/ordercg"><?php echo $this->translate('orderBUY'); ?></a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate('partners'); ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/buyer"><?php echo $this->translate('buyers'); ?></a></li>
                        <li><a href="/user/vendor"><?php echo $this->translate('vendors'); ?></a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate('goods'); ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/goods"><?php echo $this->translate('goodsME'); ?></a></li>
                        <li><a href="/user/purchase"><?php echo $this->translate('goodsBUY'); ?></a></li>
                    </ul>
                </li>

                <?php if ($this->isPersonAccount != 1): ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo $this->translate('companyMNG'); ?> <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="/user/company"><?php echo $this->translate('companyINF'); ?></a></li>
                        <li><a href="/user/account"><?php echo $this->translate('personNO'); ?></a></li>
                        <li><a href="/user/bank"><?php echo $this->translate('bankNO'); ?></a></li>
                    </ul>
                </li>
                <?php endif;?>
            </ul>
        </div>
    </div>
</nav>
