	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
	<!-- font-awesome CSS -->
	<link href="/ky/css/fontawesome-free-5.0.10/fontawesome-all.css" rel="stylesheet">
	<!-- layui CSS -->
	<link href="/ky/layui/css/layui.css" rel="stylesheet" media="all">

	<meta name="description" content="">
	<meta name="keywords" content="">
