<?php echo $this->render("header.phtml") ?>
<h1>Excel导入过滤用户名</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" enctype="multipart/form-data" method="post" action="" id="post_form">
  <table class="admin_form">
    <tr>
      <td><strong>注意：</strong>
        <p> 1.excel模板要按一定格式顺序录入数据.<br>
          2.excel模板所有数据都为必填.<br>
          3.excel模板<a href="/upload_files/excel/filterusername.xls">下载</a>. </p></td>
    </tr>
    <tr>
      <td><strong>选择EXCEL文件：</strong>
        <p>
          <input name="file" id="file" value="" type="file"/>
        </p></td>
    </tr>
    <?php if(isset($this->myresult) && !empty($this->myresult)):?>
    <tr>
      <td><strong>导入结果：</strong>
        <p><?php echo $this->myresult;?></p></td>
    </tr>
    <?php endif;?>
    <tr>
      <td><input name="" class="admin_bnt"  type="submit" value="提交" />
       </td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>