<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
		event: "keyup",
		rules: {},
		messages: {},
		submitHandler: function() {
			SeedMsgBox("正在保存中，请稍候...");
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/filterusername/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});


</script>

<h1>修改过滤用户名</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back(-1);"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <input type="hidden" name="filter_id" id="filter_id" value="<?php echo ($this->filter['filter_id']);?>">
  <table class="admin_form">
    <tr>
      <td><strong>关键词</strong>
        <p>
          <input name="keyword" id="keyword" type="text" class="admin_txt1"  value="<?php echo ($this->filter['keyword']);?>" />
        </p></td>
    </tr>
    <tr>
      <td><strong>过滤原因</strong>
        <p>
          <input name="filter_reason" id="filter_reason" type="text" class="admin_txt1"  value="<?php echo ($this->filter['filter_reason']);?>" />
        </p></td>
    </tr>
    <tr>
      <td><strong>是否启用：</strong>
        <p>
          <input type="radio" name="is_actived" id="is_actived0" value="0" style="width:15px;" <?php echo ($this->filter['is_actived']=='0')?"checked":""; ?>>
          否&nbsp;
          <input type="radio" name="is_actived" id="is_actived1" value="1" style="width:15px;" <?php echo ($this->filter['is_actived']=='1')?"checked":""; ?>>
          是 </p></td>
    </tr>
    <tr>
      <td><input name="" class="admin_bnt"  type="submit" value="提交" />
        <input name="" class="admin_bnt"  type="reset" value="重置" /></td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>