<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/goods/goods.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('partners'); ?></div>
                    <div class="list-group">
                        <a href="/user/buyer" class="list-group-item"><?php echo $this->translate('partners_buyers'); ?></a>
                        <a href="/user/vendor" class="list-group-item"><?php echo $this->translate('partners_vendors'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 partner-main">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if (!empty($this->errMsg)): ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Warning!</strong> <?php echo $this->errMsg; ?>
                        </div>
                        <?php endif; ?>

                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('edit').$this->translate('partners_buyers');?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <form class="form-horizontal partner-main-edit" action="#" method="post" id="partner_edit_form" name="partner_edit_form">
                                        <div class="form-group">
                                            <label for="companyName" class="col-sm-3 control-label"><?php echo $this->translate('companyName'); ?></label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control" name="accountName" id="accountName" placeholder="" value="<?php echo $this->partner['accountName']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="name" class="col-sm-3 control-label"><?php echo $this->translate('contacts'); ?></label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control" name="name" id="name" placeholder="" value="<?php echo $this->partner['contact']['name']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="mobilePhone" class="col-sm-3 control-label"><?php echo $this->translate('phone'); ?></label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control" name="mobilePhone" id="mobilePhone" placeholder="" value="<?php echo $this->partner['contact']['mobilePhone']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="email" class="col-sm-3 control-label"><?php echo $this->translate('email'); ?></label>
                                            <div class="col-sm-8">
                                                <input type="text" class="form-control" name="email" id="email" placeholder="" value="<?php echo $this->partner['contact']['email']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="regdCountryCode" class="col-sm-3 control-label"><?php echo $this->translate('address'); ?></label>
                                            <div class="col-sm-2">
                                                <select class="selectpicker form-control" name="regdCountryCode" id="regdCountryCode" data-live-search="true">
                                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['COUNTRY_ISO_CODE'], $this->userLangCode, $this->dic_Setting['COUNTRY_ISO_CODE'], $this->partner['regdCountryCode']); ?>
                                                </select>
                                            </div>
                                            <div class="col-sm-6">
                                                <input type="text" class="form-control" name="regdAddress" id="regdAddress" placeholder="" value="<?php echo $this->partner['regdAddress']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-8">
                                                <button type="submit" class="btn btn-warning"><?php echo $this->translate('save'); ?></button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="authModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content"></div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
            // if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $("#partner_edit_form").validate({
            rules: {

            },
            messages: {

            },
            errorPlacement: function(error, element) {
                // Append error within linked label
                $(element)
                    .closest( "form" )
                    .find( "label[for='" + element.attr( "id" ) + "']" )
                    .parent().addClass("has-error").removeClass("has-success")
                    .append( error );
                $(error).addClass("col-md-offset-3");
            },
            success: function(label) {
                var forName = $(label).attr("for");
                $("label[for='" + forName + "']").parent().addClass("has-success").removeClass("has-error");
                $(label).remove();
            },
            highlight: function (element) {
                $("label[for='" + element.id + "']").parent().addClass("has-error").removeClass("has-success");
            },
            submitHandler: function (form) {
                form.submit();
            }
        });
    });
</script>
</body>
</html>
