 <!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('etradefast'); ?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
</head>
<body>
<div class="order_goodslist">
    <div style="height: 40px;line-height:35px;margin: 10px;">
        <form action="#" method="post">
            <p>
                <input class="search_inp" name="keyword" <?php if(!empty($this->keyword)){echo "value=".$this->keyword;}?> placeholder="<?php echo $this->translate('INPkw_par_buyer');?>" type="text"><!--可输入公司名称、行业等关键字-->
                <input class="ss_btn" type="submit" value="">
                <a style="margin-top: 8px;" target="_blank" href="<?php echo WWW;?>user/buyer/add" class="addb_box fr"></a>
                <a style="margin-top: 10px;" target="_blank" href="<?php echo WWW;?>user/buyer/adds" class="p_n_sh fr"></a>
            </p>
        </form></div>
    <div style="width: 100%">
        <table class="qy_table_tc qy_table1">
            <thead>
            <tr>
                <th ><!--操作--><?php echo $this->translate('madeTT');?></th>
                <th ><!--公司名称--><?php echo $this->translate('companyName');?></th>
                <th><!--行业--><?php echo $this->translate('industry');?></th>
                <th><!--所在国家--><?php echo $this->translate('regdCountry');?></th>
                <th><!--状态--><?php echo $this->translate('state');?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(is_array($this->e) && count($this->e)>0):?>
                <?php foreach ($this->e as $k=>$v):?>
                    <tr>
                        <?php foreach($v['contactList'] as $k1=>$v1):?>
                        <?php if($v1['isDefaultPublic']==true):?>
                            <input id="contactName_<?php echo $v['toID'];?>" value="<?php echo $v1['name'];?>" type="hidden">
                            <input id="contactID_<?php echo $v['toID'];?>" value="<?php echo $v1['contactID'];?>" type="hidden">
                        <?php endif;?>
                        <?php endforeach;?>
                        <input id="crnCode_<?php echo $v['toID'];?>" value="<?php echo $v['crnCode'];?>" type="hidden">
                        <td> <input value="<?php echo $v['toName']."|".$v['regdCountryCode'];?>"  type="radio" name="checkbox" onclick="singleSelect(this)" id="<?php echo $v['toID'];?>"></td>
                        <td><?php echo $v['toName'];?></td>
                        <td><?php echo $this-> ShowDictionaryTo("datatest_setting",$this->userLangCode,$this->dic_Setting['ISIC_INDUSTRY_TYPE'], $v['industryCode']);?> </td>
                        <td><?php echo $this-> ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userLangCode,$this->dic_Setting['COUNTRY_ISO_CODE'], $v['regdCountryCode']);?></td>
                        <td><?php echo $this-> ShowDictionaryTo("datatest_setting",$this->userLangCode,$this->dic_Setting['PARTNER_STATUS'], $v['partnerStatus']);?> </td>
                    </tr>
                <?php endforeach; ?>
            <?php else:?>
                <tr><td colspan="5"> <?php echo $this->translate('noData');?></td></tr>
            <?php endif;?>
            </tbody>
        </table>
        <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
    </div>
</div>
<script>
    function doStatus(status){
        window.location.href='<?php echo $this->BaseUrl();?>/buyer/index/status/'+status

    }

    function canchild() {
        $(window.parent.document).find("#myDiv").css('display','none');
        $(window.parent.document).find("#popupDiv").children().remove();
    }
    var t = null;
    function singleSelect(obj) {

        var pname = $(obj).val();
        var arr = pname.split('|');
        var okname=arr[0];
        var okcity=arr[1];
        var thegoodid = obj.id;
        var dfcontactName=$('#contactName_'+thegoodid).val();
        var dfcontactID=$('#contactID_'+thegoodid).val();
        var buyercrnCode=$('#crnCode_'+thegoodid).val();

//        if(comcity==null||comcity==""){comcity="CN";}
//        var comcity="CN";
        if (obj.checked) {
            $(window.parent.document).find("#buyer").val(okname);
            $(window.parent.document).find("#buyerid").val(thegoodid);
            $(window.parent.document).find("#buyercity").val(okcity);
            $(window.parent.document).find("#selectgoods").children("li").remove();
            var ctName=$(window.parent.document).find("#buyerContactname").val();

            $(window.parent.document).find("#buyerContactname").val(dfcontactName);
            $(window.parent.document).find("#buyerContactid").val(dfcontactID);

            $(window.parent.document).find("#CURRENCY").val(buyercrnCode);
            $(window.parent.document).find("#CURRENCYoriginal").val(buyercrnCode);
            var comcity=$(window.parent.document).find("#comcity").val();
            if(comcity=='CN'&&okcity=='CN'&&okcity==comcity){
                $(window.parent.document).find("#chukou").hide();
                $(window.parent.document).find("#baoguanmk2").hide();
                $(window.parent.document).find("#baoguanmk2").children().find(".isbaoguanmk").eq(1).attr("checked",true);
                $(window.parent.document).find("#bgkan").hide();
                $(window.parent.document).find('#orderType').val('DT');
            }else {
                $(window.parent.document).find("#chukou").show();
                $(window.parent.document).find("#baoguanmk2").show();
                $(window.parent.document).find("#bgkan").show();
                $(window.parent.document).find("#baoguanmk2").children().find(".isbaoguanmk").eq(0).attr("checked",true);
                $(window.parent.document).find('#orderType').val('IT');
            }
        }
    }
    function delSelect(obj){
        $(obj).parent().remove();
    }

</script>
</body>
</html>
