<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body" style="padding-left: 0 !important;">
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="nav nav-tabs nav-justified">
                    <li role="presentation" class="active">
                        <a href="#usdContent" class="accumulativeTab" aria-controls="info" role="tab" data-toggle="tab" data-crn-code="CNY"><?php echo $this->translate('CNY'); ?></a>
                    </li>
                    <li role="presentation">
                        <a href="#usdContent" class="accumulativeTab" aria-controls="profile" role="tab" data-toggle="tab" data-crn-code="USD"><?php echo $this->translate('USD'); ?></a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active row" id="usdContent">
                        <div class="col-sm-12">
                            <div class="alert alert-info alert-dismissible" role="alert">
                                <div class="row">
                                    <div class="col-sm-12 col-md-8 border-right-solid-white">
                                        <div class="col-md-4">
                                            <div class="row span-margin">
                                                <div class="col-md-12">
                                                    <p class="text-center"><?php echo $this->translate('gains');?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="text-center span-font-size-30"><span id="gains"></span></p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-5">
                                            <div class="row span-margin">
                                                <div class="col-md-12">
                                                    <p class="text-center"><?php echo $this->translate('invested');?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="text-center span-font-size-30"><span id="invested"></span></p>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="row span-margin">
                                                <div class="col-md-12">
                                                    <p class="text-center"><?php echo $this->translate('arr');?></p>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="text-center span-font-size-30"><span id="arr"></span></p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-sm-12 col-md-4">
                                        <div class="row span-margin-10 margin-left-25">
                                            <span><?php echo $this->translate('Finance_operating'); ?></span>&nbsp;&nbsp;
                                            <b><span id="operatingAmount"></span></b>
                                        </div>

                                        <div class="row span-margin-10 margin-left-25">
                                            <span><?php echo $this->translate('Finance_available'); ?></span>&nbsp;&nbsp;
                                            <b><span id="availableAmount"></span></b>
                                        </div>

                                        <div class="row margin-left-25">
                                            <span><?php echo $this->translate('Finance_done'); ?></span>&nbsp;&nbsp;
                                            <b><span id="done"></span> <?php echo $this->translate('factoringChannelList'); ?></b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div id="ifc_zx" style="float: left; height: 400px; width: 1100px; padding-left: 10px"></div>
                    </div>

                    <div role="tabpanel" class="tab-pane row" id="cnyContent">

                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="row hidden">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('Finance_itermNo');?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringMode" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="RF">应收账款融资</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="PF">生产融资</button>
                                <input type="hidden" name="factoringMode" id="factoringMode" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('currency');?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="crnCode" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="USD">USD</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="CNY">CNY</button>
                                <input type="hidden" name="crnCode" id="crnCode" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static">金额</p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringAmount" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A1">5000以下</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A2">5000 至 2万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A3">2万 至 5万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A4">5万 至 10万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A5">10万 至 20万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A6">20万以上</button>
                                <input type="hidden" name="factoringAmount" id="factoringAmount" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static">进度</p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringStatus" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="all">进行中</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="all">历史</button>&nbsp;&nbsp;
                                <input type="hidden" name="factoringStatus" id="factoringStatus" value="all">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <ul class="list-unstyled resultList"></ul>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    var dataDict = {};
    var myChart = echarts.init(document.getElementById('ifc_zx'));

	$().ready(function() {

	});

	$(function () {
	    // 初始化收效数据
        initAccumulative('CNY');
        initGains('CNY', new Date().getFullYear());

        $(".accumulativeTab").click(function () {
            initAccumulative($(this).attr("data-crn-code"));
            initGains($(this).attr("data-crn-code"), new Date().getFullYear());
        });

        // 初始化ECharts
        option = {
            baseOption: {
                timeline: {
                    data: ['2017', '2018'],
                    // data: [],
                    currentIndex: 1,
                    bottom: '-5',
                    label: {
                        formatter: function (value, index) {
                            // 格式化，只显示年份
                            var date = new Date(value);
                            return date.getFullYear();
                        }
                    }
                },
                title: {
                    show: true,
                    text: '收益图表',
                    subtext: '收益(万元)'
                },
                tooltip: {
                    trigger: 'axis',
                    axisPointer: {
                        type: 'cross'
                    }
                },
                toolbox: {
                    show: true,
                    feature: {
                        saveAsImage: {}
                    }
                },
                legend: {
                    data:['实际收益', '应计收益']
                },
                xAxis: {
                    type: 'category',
                    data: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
                },
                yAxis: {
                    type: 'value'
                },
                series: [{
                    name: '实际收益',
                    type: 'bar',
                    data: [220, 182, 191, 234, 290]
                }, {
                    name: '应计收益',
                    data: [1, 2, 15, 20, 8, 20, 32, 7],
                    type: 'line',
                    itemStyle: {
                        normal: {
                            label: {show: true}
                        }
                    }
                }]
            },
            options: [
                {
                    title: {
                        text: '2017收益分析'
                    },
                    series: [
                        {data: [1, 2, 15, 20, 8, 20, 32, 7]},
                        {data: [220, 182, 191, 234, 290]}
                    ]
                }, {
                    title: {
                        text: '2018收益分析'
                    },
                    series: [
                        {data: [1, 2, 15, 20, 8, 20, 32, 7]},
                        {data: [220, 182, 191, 234, 290]}
                    ]
                }
            ]
        };

        myChart.setOption(option);


        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                var $titleOptions = $(".title-options");
                $titleOptions.find("button").click(function () {
                    var dataType = $(this).attr("data-type");
                    $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
                    $(this).addClass("btn-warning");

                    $("#" + dataType).val($(this).attr("data-value"));
                    refreshResultList();
                });

                refreshResultList();
            }
        });
	});

    function refreshResultList() {
        var factoringQuery = '/user/finance/list-factoring-item-channel-ajax';
        $.ajax({
            type: "POST",
            url: factoringQuery,
            data: {
                factoringMode: $("#factoringMode").val(),
                crnCode: $("#crnCode").val(),
                factoringAmount: $("#factoringAmount").val(),
                factoringStatus: $("#factoringStatus").val()
            },
            dataType: "json",
            success: function (data) {
                var contents = '',
                    $resultList = $(".resultList");

                if (data.rows.length === 0) {
                    contents += '<li>'
                        + ' <div class="panel panel-success">'
                        + '  <div class="panel-heading">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>&nbsp;</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'

                        + '  <div class="panel-body">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>没有找到匹配的记录</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'
                        + ' </div>'
                        + '</li>';
                } else {
                    $.each(data.rows, function (i, item) {
                        var base = new Base64();
                        var resultEnCode = base.encode(item.itemID);

                        var data = $.data(dataDict, 'dataDict');
                        var itemStatus = '-';
                        $.each(data, function (key, itemDict) {
                            if (key === 'FACTORING_STATUS') {
                                $.each(itemDict, function (i, dict) {
                                    if (dict.code === item.itemStatus) {
                                        itemStatus = dict.name;
                                    }
                                });
                            }
                        });
                        contents += '<li style="cursor: pointer;" data-resultEnCode="' + resultEnCode + '">'
                            + ' <div class="panel panel-success">'
                            + '  <div class="panel-heading">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-11">'
                            + '     <span>项目号</span>&nbsp;&nbsp;'
                            + '     <span>' + item.itemNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>订单编号</span>&nbsp;&nbsp;'
                            + '     <span>' + item.orderNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>项目金额</span>&nbsp;&nbsp;'
                            + '     <span>' + item.crnCode + ' ' + item.receivableAmount + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>状态</span>&nbsp;&nbsp;'
                            + '     <span>' + itemStatus + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-1">'
                            + '     <p class="text-right"><a href="/user/finance/channelview?' + resultEnCode + '">详情</a></p>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'

                            + '  <div class="panel-body">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-2">'
                            + '     <span>支付期限</span>&nbsp;&nbsp;'
                            + '     <span>' + item.period + ' Days' +'</span>'
                            + '    </div>'
                            + '    <div class="col-sm-4">'
                            + '     <span>投资金额</span>&nbsp;&nbsp;'
                            + '     <span>' + item.financingCrnCode + ' ' + item.financingAmount + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-3">'
                            + '     <span>预计收益</span>&nbsp;&nbsp;'
                            + '     <span>' + item.financingCrnCode + ' ' + item.interest + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-3">'
                            + '     <span>预计收益日</span>&nbsp;&nbsp;'
                            + '     <span>' + new Date(item.expiryDate).format("yyyy-MM-dd") + '</span>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'
                            + ' </div>'
                            + '</li>';
                    });
                }

                $resultList.html(contents);

                $(".resultList li").click(function () {
                    var resultEnCodeUrl = $(this).attr("data-resultEnCode");
                    if (resultEnCodeUrl !== undefined && resultEnCodeUrl !== '') {
                        window.location.href = '/user/finance/channelview?' + resultEnCodeUrl;
                    }
                });
            }
        });
    }
    
    function initAccumulative(crnCode) {
        var accumulativeUrl = '/user/finance/count-accumulative-ajax';
        $.ajax({
            type: "POST",
            url: accumulativeUrl,
            data: {
                crnCode: crnCode
            },
            dataType: "json",
            success: function (data) {
                $("#availableAmount").html(data.availableAmount);
                $("#operatingAmount").html(data.operatingAmount);
                $("#arr").html(data.arr);
                $("#done").html(data.done);
                $("#invested").html(data.invested);
                $("#gains").html(data.gains);
            }
        });
    }

    function initGains(crnCode, year) {
        var gainsUrl = '/user/finance/count-gains-ajax';
        $.ajax({
            type: "POST",
            url: gainsUrl,
            data: {
                crnCode: crnCode,
                year: year
            },
            dataType: "json",
            success: function (data) {
                // console.log(JSON.stringify(data.options));
                // console.log(data.options.length);

                // 填入数据
                myChart.setOption({
                    baseOption: {
                        timeline: {
                            data: data.totalYear,
                            currentIndex: data.options.length - 1
                        }
                    },
                    options: data.options
                });
            }
        });
    }
</script>
</body>
</html>
