<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-body bg-color">
                <div class="row text-white">
                    <div class="col-sm-12 col-md-8 border-right-solid-white">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <p class="text-center">计划<?php echo $this->translate('financingAmountview'); ?></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo $this->channelRow['financingCrnCode'] ?> <?php echo number_format($this->channelRow['tgtFinancingAmount'], 2) ?></p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <p class="text-center"><abbr title="预计利息收入 / 计划投入资金 = 计划收效率">计划<?php echo $this->translate('arr'); ?></abbr></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo number_format($this->channelRow['interest'] / $this->channelRow['tgtFinancingAmount'] * 100, 2); ?> %</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-3">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <?php
                                        $dateNow = strtotime(date("Y-m-d", time()));
                                        $expiryDate = strtotime($this->channelRow['expiryDate']);
                                        $graceDate = $expiryDate + $this->channelRow['factoring']['gracePeriod'] * 86400;
                                        ?>
                                        <?php if ($dateNow < $expiryDate): ?>
                                            <p class="text-center"><?php echo $this->translate('diffTimes'); ?></p>
                                        <?php elseif ($dateNow < $graceDate):?>
                                            <p class="text-center"><?php echo $this->translate('距宽限日'); ?></p>
                                        <?php else: ?>
                                            <p class="text-center"><?php echo $this->translate('逾期'); ?></p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo $this->channelRow['diffTime']; ?> DAYS</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-4">
                        <div class="row span-margin-10">
                            <div class="col-md-12">
                                <span><?php echo $this->translate('accountsReceivable'); ?></span>&nbsp;&nbsp;
                                <b><span><?php echo $this->channelRow['crnCode'].'&nbsp;&nbsp;'.$this->channelRow['receivableAmount'];?></span></b>
                            </div>
                        </div>
                        <div class="row span-margin-10">
                            <div class="col-md-5">
                                <span>项目<?php echo $this->translate('period'); ?></span>&nbsp;&nbsp;
                                <b><span><?php echo $this->channelRow['period'] ?>&nbsp;DAYS</span></b>
                            </div>
                            <div class="col-md-7">

                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <span><?php echo $this->translate('inputProportion'); ?></span>&nbsp;&nbsp;
                                <b>
                                    <span>
                                    <?php echo number_format($this->channelRow['financingAmount'] / $this->channelRow['receivableAmount'] * 100, 2); ?> %
                                    </span>
                                </b>
                            </div>
                            <div class="col-md-7">

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary"><?php echo $this->translate('Finance_info'); ?></p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('factoringNo'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['itemNo'] ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('companyName'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['factoring']['companyName'] ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('orderNon'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['orderNo'] ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Finance_project_date'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo date('Y/m/d', strtotime($this->channelRow['loanDate']));?> - <?php echo date("Y/m/d",strtotime($this->channelRow['expiryDate']));?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('当前投入'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['financingCrnCode'] . '&nbsp;' . $this->ShowToPrice($this->channelRow['actualTgtFinancingAmount']); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('当前收益'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['financingCrnCode'] . '&nbsp;' . $this->ShowToPrice($this->channelRow['actualInterest']); ?>
                        </p>
                    </div>
                </div>

                <div class="row hidden">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Finance_project_total'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->channelRow['financingCrnCode'] . '&nbsp;' . $this->ShowToPrice($this->channelRow['actualTgtFinancingAmount'] + $this->channelRow['actualInterest']); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">放款情况</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>放款编号</th>
                                <th>放款日期</th>
                                <th>货币</th>
                                <th class="text-right">放款金额</th>
                                <th class="text-right">利息</th>
                                <th class="text-right">宽限期利息</th>
                                <th class="text-right">逾期利息</th>
                                <th class="text-right">合计利息</th>
                                <th class="text-right">未还本息</th>
                                <th><?php echo $this->translate('settle_Status'); ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (empty($this->channelRow['factoringChannelLoanList'])):?>
                                <tr>
                                    <td colspan="10">暂无放款记录</td>
                                </tr>
                            <?php else:?>
                                <?php foreach ($this->channelRow['factoringChannelLoanList'] as $factoringLoan):?>
                                    <tr>
                                        <td><?php echo $factoringLoan['factoringLoan']['loanNo']; ?></td>
                                        <td><?php echo date('Y-m-d', strtotime($factoringLoan['loanDate'])); ?></td>
                                        <td><?php echo $factoringLoan['factoringLoan']['loanCrnCode']; ?></td>
                                        <td class="text-right"><?php echo number_format($factoringLoan['loanAmount'], 2); ?></td>
                                        <td class="text-right"><?php echo $factoringLoan['totalGeneralInterest'] != 0 ? number_format($factoringLoan['totalGeneralInterest'], 2) : '----'; ?></td>
                                        <td class="text-right"><?php echo $factoringLoan['totalGraceInterest'] != 0 ? number_format($factoringLoan['totalGraceInterest'], 2) : '----'; ?></td>
                                        <td class="text-right"><?php echo $factoringLoan['totalOverdueInterest'] != 0 ? number_format($factoringLoan['totalOverdueInterest'], 2) : '----'; ?></td>
                                        <td class="text-right">
                                            <?php echo $factoringLoan['totalInterest'] != 0 ? number_format($factoringLoan['totalInterest'], 2) : '----'; ?> <i class="layui-icon layui-icon-about" style="cursor: pointer;" data-toggle="modal" data-target="#interestModal" data-loan-id="<?php echo $factoringLoan['loanID']; ?>"></i>
                                        </td>
                                        <td class="text-right">
                                            <?php echo number_format($factoringLoan['writeoffBalAmount'] + $factoringLoan['writeoffBalInterest'], 2); ?>
                                        </td>
                                        <td class="loanStatus_<?php echo $factoringLoan['loanID']; ?>">
                                            <?php echo $this->ShowDictionaryTo("LOAN_STATUS", $this->userLangCode, $this->dic_Setting['LOAN_STATUS'], $factoringLoan['loanStatus']); ?>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row hidden">
                    <div class="col-md-3">
                        <span class="margin-left-5 text-999">实际利息</span>
                        <span class="margin-left-25 text-666"><?php echo $this->channelRow['financingCrnCode']; ?> <?php echo number_format($this->channelRow['actualInterest'], 2); ?></span>
                    </div>
                    <div class="col-md-3">
                        <span class="margin-left-5 text-999">宽限期利息</span>
                        <span class="margin-left-25 text-666"><?php echo $this->channelRow['financingCrnCode']; ?> <?php echo number_format($this->channelRow['graceInterest'], 2); ?></span>
                    </div>
                    <div class="col-md-3">
                        <span class="margin-left-5 text-999">逾期利息</span>
                        <span class="margin-left-25 text-666"><?php echo $this->channelRow['financingCrnCode']; ?> <?php echo number_format($this->channelRow['overdueInterest'], 2); ?></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">还款情况</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>还款编号</th>
                                <th>还款日期</th>
                                <th class="text-right">应还金额</th>
                                <th class="text-right">汇率</th>
                                <th class="text-right">已付金额</th>
                                <th class="text-right">支付利息</th>
                                <th class="text-right">支付本金</th>
                                <th class="text-right">支付尾款</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (empty($this->channelRow['factoringRepaymentList'])):?>
                                <tr>
                                    <td colspan="11">暂无还款记录</td>
                                </tr>
                            <?php else:?>
                                <?php foreach ($this->channelRow['factoringRepaymentList'] as $factoringRepayment):?>
                                    <tr>
                                        <td><?php echo $factoringRepayment['repaymentNo']; ?></td>
                                        <td><?php echo date('Y-m-d', strtotime($factoringRepayment['repaymentDate'])); ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo number_format($factoringRepayment['totalAmount'], 2); ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['exchangeRate']; ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo number_format($factoringRepayment['repaymentTotalAmount'], 2); ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo number_format($factoringRepayment['writeoffInterestAmount'], 2); ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo number_format($factoringRepayment['writeoffPrincipalAmount'], 2); ?></td>
                                        <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo number_format($factoringRepayment['writeoffFinalAmount'], 2); ?></td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<!-- Modal 利息明细 -->
<div class="modal fade" id="interestModal" tabindex="-1" role="dialog" aria-labelledby="interestLabel">
    <div class="modal-dialog modal-lg" role="document" style="width: 1080px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">利息明细</h4>
            </div>

            <div class="modal-body">
                <table class="table table-bordered" id="resultListTable">
                </table>
            </div>
        </div>
    </div>
</div>


<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>

<script type="text/javascript">
    var dataDict = {};

	$().ready(function() {

	});

	$(function () {
        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["LOAN_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);
            }
        });
	});

    $("#interestModal").on('show.bs.modal', function (e) {
        var triggered = $(e.relatedTarget),
            loanID = triggered.data("loan-id"),
            $resultListTable = $('#resultListTable');

        var options = {
            query:{
                loanID: loanID
            }
        };
        $resultListTable.bootstrapTable('refresh', options);

        $resultListTable.bootstrapTable({
            url: '/user/finance/factoring-interest-list-ajax',
            method: 'post',
            // showRefresh: true,
            // search: true,
            pagination: true,
            // onlyInfoPagination: true,
            classes: 'table table-hover table-no-bordered',
            sidePagination: 'server',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            queryParams: function(params) {
                return {
                    loanID: loanID
                };
            },
            columns: [{
                field: 'principalAmount',
                title: '<?php echo $this->translate("principalAmount"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    return formatCurrency(value, 2);
                }
            }, {
                field: 'valueDate',
                title: '<?php echo $this->translate("interestValueDate"); ?>',
                formatter: function (value) {
                    return new Date(value).format("yyyy-MM-dd");
                }
            }, {
                field: 'expiryDate',
                title: '<?php echo $this->translate("interestExpiryDate"); ?>',
                formatter: function (value) {
                    return new Date(value).format("yyyy-MM-dd");
                }
            }, {
                field: 'interestDays',
                title: '<?php echo $this->translate("interestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value;
                }
            }, {
                field: 'totalInterest',
                title: '<?php echo $this->translate("totalInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'graceInterestDays',
                title: '<?php echo $this->translate("graceInterestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value;
                }
            }, {
                field: 'graceInterest',
                title: '<?php echo $this->translate("graceInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'overdueInterestDays',
                title: '<?php echo $this->translate("overdueInterestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value;
                }
            }, {
                field: 'overdueInterest',
                title: '<?php echo $this->translate("overdueInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'writeoffBalInterest',
                title: '<?php echo $this->translate("writeoffBalInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }]
        });
    });
</script>
</body>
</html>
