<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/finance.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>



</head>
<body>

<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div class="finance_txt">
    	<p class="ifcp_tit"><!--项目详情--><?php echo $this->translate('Finance_info');?></p>
        <div class="ifc_cnv">
            <span class="line1"></span>
<!--            <span class="line2"></span>-->
            <table class="ifc_cnv_table f16" width="800">
                <tbody>
                    <tr>
                        <th><!--投入资金--><?php echo $this->translate('financingAmountview');?></th>
                        <th><!--收益率--><?php echo $this->translate('arr');?></th>
                        <th><!--距收益日--><?php echo $this->translate('diffTimes');?></th>
                    </tr>
                    <tr class="coloryel f20">
                        <td> <?php echo $this->channelRow['crnCode'].'&nbsp;&nbsp;'.$this->ShowToPrice($this->channelRow['financingAmount']);?></td>
                        <td><?php  echo $this->channelRow['disArr'].'%';?></td>
                        <td><?php  echo $this->channelRow['repaymentDaysDesc'];?></td>
                    </tr>
                </tbody>
            </table>
            <table class="ifc_cnv_table" width="280">
                <tbody>
                    <tr>
                        <th><!--项目总额--><?php echo $this->translate('accountsReceivable');?></th>
                        <td class="coloryel">&nbsp;<?php echo $this->channelRow['crnCode'].'&nbsp;&nbsp;'.$this->channelRow['factoringActualFinancingAmount'];?></td>
                    </tr>
                    <tr>
                        <th><!--周期--><?php echo $this->translate('period');?></th>
                        <td class="coloryel"><?php echo $this->channelRow['period'] ?>&nbsp;DAYS</td>
                    </tr>
                    <tr>
                        <th><!--投入比例--><?php echo $this->translate('inputProportion');?></th>
                        <td class="coloryel"><?php echo $this->channelRow['disInputProportion'].'%';?></td>
                    </tr>
                </tbody>
            </table>

        </div>
        <div class="txt_box">
            <label class="fc_lab"><!--项目号--><?php echo $this->translate('factoringNo');?></label>
            <p style="color: #428bca;"><?php echo $this->channelRow['factoringNo'] ?></p>
        </div>
        <div class="txt_box">
            <label class="fc_lab"><!--受理公司--><?php echo $this->translate('companyName');?></label>
            <p><?php echo $this->channelRow['companyName'] ?></p>
        </div>
        <div class="txt_box">
            <label class="fc_lab"><!--订单--><?php echo $this->translate('orderNon');?></label>
            <p><?php echo $this->channelRow['orderNo'] ?></p>
        </div>
        <p class="ifcp_tit"><!--项目计划--><?php echo $this->translate('Finance_project_plan');?>
            <span class="f12 colorred fn">  <!--（*计划只做参考，实际情况视订单进度而定）--><?php echo $this->translate('Finance_colorred_tip02');?></span></p>
        <table class="ifc_del">
            <tbody>
                <tr>
                    <th style="width: 100px;"></th>
                    <th style="width: 500px;"><!--起始日期--><?php echo $this->translate('Finance_project_date');?></th>
                    <th><!--投入资金--><?php echo $this->translate('financingAmountview');?></th>
                    <th></th>
                    <th><!--预计收益--><?php echo $this->translate('yjsy');?></th>

                    <th></th>
                    <th><!--本息合计--><?php echo $this->translate('Finance_project_total');?></th>
                </tr>
                <tr>
                    <td  align="center"><img src=/images/center/yes.gif></td>
                    <td><?php echo date('Y/m/d', strtotime($this->channelRow['loanDate']));?><br/>
                        <b style="color: #428bca;">-</b><br /><?php echo date("Y/m/d",strtotime($this->channelRow['expiryDate']));?></td>
                    <td><?php  echo $this->channelRow['crnCode'].'&nbsp;'. $this->ShowToPrice($this->channelRow['financingAmount']);?></td>
                    <td>+</td>
                    <td><?php  echo $this->channelRow['crnCode'].'&nbsp;'.  $this->ShowToPrice($this->channelRow['interest']);?></td>
                  <td>=</td>
                    <td class="colorred">
                        <?php  echo $this->channelRow['crnCode'].'&nbsp;'.
                            $this->ShowToPrice($this->channelRow['financingAmount']+$this->channelRow['interest']);?></td>
                </tr>
            </tbody>
        </table>

    </div>
</div>
</body>
</html>