<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body" style="padding-left: 0 !important;">
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <ul class="nav nav-tabs nav-justified">
                    <li role="presentation" class="active">
                        <a href="#cnyContent" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('CNY'); ?></a>
                    </li>
                    <li role="presentation">
                        <a href="#usdContent" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('USD'); ?></a>
                    </li>
                </ul>

                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane active row" id="cnyContent">
                        <div class="col-sm-12">
                            <div class="alert alert-info alert-dismissible" role="alert">
                                <h3><?php echo $this->translate('gains');?></h3>
                                <h3><?php echo $this->translate('invested');?></h3>
                                <h3><?php echo $this->translate('arr');?></h3>

                            </div>
                        </div>

                        <div id="ifc_zx" style="float: left; height: 400px; width: 1100px; margin-left: -30px;"></div>
                    </div>

                    <div role="tabpanel" class="tab-pane row" id="usdContent">

                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('Finance_itermNo');?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringMode" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="RF">应收账款融资</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="PF">生产融资</button>
                                <input type="hidden" name="factoringMode" id="factoringMode" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('currency');?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="crnCode" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="USD">USD</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="CNY">CNY</button>
                                <input type="hidden" name="crnCode" id="crnCode" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static">金额</p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringAmount" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A1">5000以下</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A2">5000 至 2万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A3">2万 至 5万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A4">5万 至 10万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A5">10万 至 20万</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A6">20万以上</button>
                                <input type="hidden" name="factoringAmount" id="factoringAmount" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static">进度</p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringStatus" data-value="all">全部</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="all">进行中</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="all">历史</button>&nbsp;&nbsp;
                                <input type="hidden" name="factoringStatus" id="factoringStatus" value="all">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <ul class="list-unstyled resultList"></ul>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/js/echarts.simple.min.js"></script>
<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        var myChart = echarts.init(document.getElementById('ifc_zx'));
        option = {
            title : {
                text: '',
                subtext: ''
            },
            tooltip : {
                trigger: 'item',
                formatter: "{a} <br/>{b} : {c} "
            },
            legend: {
                data:['收益曲线']
            },
            grid: {
                width: 'auto',
                borderWidth:'0'
            },
            calculable : true,
            xAxis : [
                {
                    type : 'category',
                    axisLabel:{
                        show: true,
                        formatter: null,
                        textStyle: {
                            color: '#ccc'
                        }
                    },
                    axisTick:{
                        show: false},
                    axisLine:{
                        show:true,
                        lineStyle: {
                            color:'#ccc',
                            width: 1
                        }},
                    splitLine:{show: false},//去除网格线
                    boundaryGap : false,
                    data : ['一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月']
                }
            ],
            yAxis : [
                {
                    type : 'value',
                    axisTick:{
                        show: false},
                    axisLabel:{show:false},
                    axisLine:{show:false},
                    splitLine:{show: false}//去除网格线

                }
            ],
            series : [
                {
                    name:'收益',
                    type:'line',
                    data:[1, 2, 15, 20, 8, 30,18, 7 ],
                    markPoint : {
                        data : []
                    },
                    symbolSize:5,
                    itemStyle : {
                        normal : {
                            // borderColor:'#5cb85c',
                            // lineStyle:{
                            //     color: "#ff6600"  //连线颜色
                            // },
                            label : {show: true}
                        }
                    },
                    markLine : {
                        data : []
                    }
                }
            ]
        };



        option3 = {
            title: {
                show: true,
                text: 'ECharts 入门示例'
            },
            tooltip: {},
            legend: {
                data:['销量']
            },
            xAxis: {
                type: 'category',
                data: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月']
            },
            yAxis: {
                type: 'value'
            },
            series: [{
                data: [1, 2, 15, 20, 8, 30, 18, 7],
                type: 'line',
                itemStyle: {
                    normal: {
                        label: {show: true}
                    }
                }
            }]
        };

        myChart.setOption(option3);


        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                var $titleOptions = $(".title-options");
                $titleOptions.find("button").click(function () {
                    var dataType = $(this).attr("data-type");
                    $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
                    $(this).addClass("btn-warning");

                    $("#" + dataType).val($(this).attr("data-value"));
                    refreshResultList();
                });

                refreshResultList();
            }
        });
	});

    function refreshResultList() {
        var factoringQuery = '/user/finance/factoring-list-ajax';
        $.ajax({
            type: "POST",
            url: factoringQuery,
            data: {
                factoringMode: $("#factoringMode").val(),
                crnCode: $("#crnCode").val(),
                factoringAmount: $("#factoringAmount").val(),
                factoringStatus: $("#factoringStatus").val()
            },
            dataType: "json",
            success: function (data) {
                var contents = '',
                    $resultList = $(".resultList");

                if (data.rows.length === 0) {
                    contents += '<li>'
                        + ' <div class="panel panel-success">'
                        + '  <div class="panel-heading">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>&nbsp;</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'

                        + '  <div class="panel-body">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>没有找到匹配的记录</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'
                        + ' </div>'
                        + '</li>';
                } else {
                    $.each(data.rows, function (i, item) {
                        var base = new Base64();
                        var resultEnCode = base.encode(item.factoringID);

                        var data = $.data(dataDict, 'dataDict');
                        var factoringStatus = '-';
                        $.each(data, function (key, itemDict) {
                            if (key === 'FACTORING_STATUS') {
                                $.each(itemDict, function (i, dict) {
                                    if (dict.code === item.factoringStatus) {
                                        factoringStatus = dict.name;
                                    }
                                });
                            }
                        });
                        contents += '<li style="cursor: pointer;" data-resultEnCode="' + resultEnCode + '">'
                            + ' <div class="panel panel-success">'
                            + '  <div class="panel-heading">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-11">'
                            + '     <span>项目编号</span>&nbsp;&nbsp;'
                            + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>订单编号</span>&nbsp;&nbsp;'
                            + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>债务方</span>&nbsp;&nbsp;'
                            + '     <span>' + item.debtorCustomerName + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>项目进度</span>&nbsp;&nbsp;'
                            + '     <span>' + factoringStatus + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-1">'
                            + '     <p class="text-right"><a href="/user/finance/view?' + resultEnCode + '">详情</a></p>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'

                            + '  <div class="panel-body">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-3">'
                            + '     <span>应收帐款</span>&nbsp;&nbsp;'
                            + '     <span>' + item.crnCode + ' ' + item.receivableTotalAmount  +'</span>'
                            + '    </div>'
                            + '    <div class="col-sm-4">'
                            + '     <span>计划融资</span>&nbsp;&nbsp;'
                            + '     <span>' + item.crnCode + ' ' + item.financingTotalAmount + ' ( ' + item.financingCrnCode + ' ' + item.tgtFinancingTotalAmount  + ')</span>'
                            + '    </div>'
                            + '    <div class="col-sm-2">'
                            + '     <span>保理期</span>&nbsp;&nbsp;'
                            + '     <span>' + item.period + ' 天</span>'
                            + '    </div>'
                            + '    <div class="col-sm-3">'
                            + '     <span>计划回款日</span>&nbsp;&nbsp;'
                            + '     <span>' + new Date(item.expiryDate).format("yyyy-MM-dd") + '</span>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'
                            + ' </div>'
                            + '</li>';
                    });
                }

                $resultList.html(contents);

                $(".resultList li").click(function () {
                    var resultEnCodeUrl = $(this).attr("data-resultEnCode");
                    if (resultEnCodeUrl !== undefined && resultEnCodeUrl !== '') {
                        window.location.href = '/user/finance/view?' + resultEnCodeUrl;
                    }
                });
            }
        });
    }
</script>
</body>
</html>
