<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="page-header">
                            <h1>
                                <?php echo $this->translate('Finance_index'); ?>
                                <ul class="list-inline pull-right">
                                    <li><button type="button" class="btn btn-warning">CNY</button></li>
                                    <li><button type="button" class="btn btn-default">USD</button></li>
                                </ul>
                            </h1>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-5">
                        <ul class="list-unstyled">
                            <li>
                                <dl class="dl-horizontal">
                                    <dt><?php echo $this->translate('Finance_mouth_amount'); ?></dt>
                                    <dd><?php echo $this->f_crnCode . '&nbsp;&nbsp;' . $this->ShowToPrice($this->MonthTotal); ?></dd>
                                </dl>
                            </li>
                            <li>
                                <dl class="dl-horizontal">
                                    <dt><?php echo $this->translate('Finance_re_amount'); ?></dt>
                                    <dd><?php echo $this->f_crnCode . '&nbsp;&nbsp;' . $this->ShowToPrice($this->TotalAmount); ?></dd>
                                </dl>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-7">
                        <div class="row">
                            <div class="col-md-10">
                                <?php echo $this->translate('Saltter_ETIFO'); ?>
                            </div>
                            <div class="col-md-2">
                                <a href="#" data-toggle="tooltip" title="" data-original-title="<?php echo $this->translate('Saltter_credit'); ?>">
                                    <?php echo $this->translate('Saltter_credit'); ?>
                                </a>&nbsp;&nbsp;
                                <span class="text-success"><?php echo $this->paymentData['creditRating']; ?></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="progress">
                                    <?php
                                    $percent = round($this->paymentData['creditBal'] / $this->paymentData['creditLimit'] * 100)."%";
                                    ?>
                                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: <?php echo $percent; ?>;">
                                        <span class=""><?php echo $percent; ?></span>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <?php echo $this->translate('Saltter_Available') . '&nbsp;&nbsp;' . $this->paymentData['creditBal'] . '/' . $this->paymentData['creditLimit']; ?>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#forActivate" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('forActivate'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('forLoan'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('waitPay'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('rejected'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('done'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="forActivate">
                                <form class="form-horizontal">
                                    <div class="form-group">
                                        <label for="factoringNo" class="col-sm-2 control-label"><?php echo $this->translate('finance') . $this->translate('Finance_itermNo'); ?></label>
                                        <div class="col-sm-3">
                                            <input type="text" class="form-control" name="factoringNo" id="factoringNo" placeholder="Jane Doe">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="startDate" class="col-sm-2 control-label"><?php echo $this->translate('Finance_reDate'); ?></label>
                                        <div class="col-sm-3">
                                            <input type="date" class="form-control" name="startDate" id="startDate">
                                        </div>
                                        <div class="layui-form-mid">-</div>
                                        <label for="endDate" class="sr-only">endDate</label>
                                        <div class="col-sm-3">
                                            <input type="date" class="form-control" name="endDate" id="endDate">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="orderNo" class="col-sm-2 control-label"><?php echo $this->translate('orderNO'); ?></label>
                                        <div class="col-sm-3">
                                            <input type="text" class="form-control" name="orderNo" id="orderNo">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="lowerAmount" class="col-sm-2 control-label"><?php echo $this->translate('ordertotal'); ?></label>
                                        <div class="col-sm-3">
                                            <input type="number" class="form-control" name="lowerAmount" id="lowerAmount">
                                        </div>
                                        <div class="layui-form-mid">-</div>
                                        <label for="upperAmount" class="sr-only">upperAmount</label>
                                        <div class="col-sm-3">
                                            <input type="number" class="form-control" name="upperAmount" id="upperAmount">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-offset-2 col-sm-4">
                                            <button type="submit" class="btn btn-default">Send invitation</button>
                                        </div>
                                    </div>
                                </form>
                            </div>

                            <div role="tabpanel" class="tab-pane fade" id="forLoan">
                                forLoan...
                            </div>

                            <div role="tabpanel" class="tab-pane fade" id="waitPay">
                                waitPay...
                            </div>

                            <div role="tabpanel" class="tab-pane fade" id="rejected">
                                rejected...
                            </div>

                            <div role="tabpanel" class="tab-pane fade" id="done">
                                done...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $("[data-toggle='tooltip']").tooltip();
	});
</script>
</body>
</html>
