<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <div class="panel panel-default hidden">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        Company Info
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <?php if (!empty($this->resultMsg)): ?>
                <div class="alert alert-success alert-dismissible fade in" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <p><?php echo base64_decode(str_replace(" ", "+", $this->resultMsg)); ?>!</p>
                </div>
                <?php endif; ?>

                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('factoring_mode'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringMode" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="RF"><?php echo $this->translate('factoring_mode_rf'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="PF"><?php echo $this->translate('factoring_mode_pf'); ?></button>
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="EF"><?php echo $this->translate('factoring_mode_ef'); ?></button>
                                <input type="hidden" name="factoringMode" id="factoringMode" value="all">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('factoring_crnCode'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="crnCode" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="USD">USD</button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="crnCode" data-value="CNY">CNY</button>
                                <input type="hidden" name="crnCode" id="crnCode" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('factoring_amount'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringAmount" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A1"><?php echo $this->translate('factoring_amount_a1'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A2"><?php echo $this->translate('factoring_amount_a2'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A3"><?php echo $this->translate('factoring_amount_a3'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A4"><?php echo $this->translate('factoring_amount_a4'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A5"><?php echo $this->translate('factoring_amount_a5'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A6"><?php echo $this->translate('factoring_amount_a6'); ?></button>
                                <input type="hidden" name="factoringAmount" id="factoringAmount" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static">进度</p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringStatus" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="01"><?php echo $this->translate('factoring_for_check'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="03"><?php echo $this->translate('factoring_activated'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringStatus" data-value="05"><?php echo $this->translate('factoring_done'); ?></button>
                                <input type="hidden" name="factoringStatus" id="factoringStatus" value="all">
                            </div>
                        </div>
                    </div>
                    <?php if ($this->regdCountryCode == 'CN'): ?>
                    <div class="col-sm-1 creditRating">
                        <p class="creditTitle"><?php echo $this->translate('factoring_credit'); ?></p>
                        <?php if (!empty($this->level)): ?>
                            <?php
                            $nowDate = strtotime(date("Y-m-d"));
                            $expiryDate = strtotime(date("Y-m-d", strtotime($this->expiryDate)));
                            ?>
                            <?php if ($nowDate > $expiryDate): ?>
                                <p class="text-center creditInfo"><?php echo $this->translate('factoring_credit_expiry'); ?></p>
                            <?php else: ?>
                                <p class="text-center creditInfo"><?php echo $this->level; ?></p>
                            <?php endif; ?>
                        <?php elseif (!empty($this->instance)): ?>
                            <?php if ($this->applyStatus == 0): ?>
                                <p class="text-center creditInfo-unApply" style="cursor: pointer;" data-type="instance">
                                    <?php echo $this->translate('factoring_credit_apply'); ?><br ><?php echo $this->translate('factoring_credit_evaluation'); ?>
                                </p>
                            <?php else: ?>
                                <p class="text-center creditInfo" style="font-size: 20px;"><?php echo $this->translate('factoring_credit_forCheck'); ?></p>
                            <?php endif; ?>
                        <?php else: ?>
                            <p class="text-center creditInfo-unApply" style="cursor: pointer;" data-type="init">
                                <?php echo $this->translate('factoring_credit_apply'); ?><br ><?php echo $this->translate('factoring_credit_evaluation'); ?>
                            </p>
                        <?php endif; ?>
                    </div>
                    <?php endif;?>
                </div>
            </div>
        </div>

        <ul class="list-unstyled resultList" id="flowResultList"></ul>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script type="text/javascript" src="/ky/upload/img.js"></script>

<script type="text/javascript">
    var dataDict = {};

	$().ready(function() {

	});

	$(function () {
        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                var $titleOptions = $(".title-options");
                $titleOptions.find("button").click(function () {
                    var dataType = $(this).attr("data-type");
                    $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
                    $(this).addClass("btn-warning");

                    $("#" + dataType).val($(this).attr("data-value"));

                    // 清空之前的结果
                    $("#flowResultList").html('');
                    $("#offset").val('0');
                    refreshFlowResultList();
                });

                // refreshResultList();
                refreshFlowResultList();
            }
        });

        $(".creditInfo-unApply").click(function () {
            var dataType = $(this).attr("data-type");
            var base = new Base64();
            var requestEnCode = base.encode(dataType);
            window.location.href = "/user/finance/init-evaluation-apply?" + requestEnCode;
        });

        $("#applyCreditModal").on('show.bs.modal', function (e) {
            var triggered = $(e.relatedTarget),
                dataType = triggered.data("type"),
                $evaluationBody = $("#applyCreditModal").find(".modal-body"),
                initUrl = '/user/finance/init-evaluation-apply';

            $evaluationBody.html("").load(initUrl, {"dataType": dataType});
        });
	});

	function refreshResultList() {
        var factoringQuery = '/user/finance/factoring-list-ajax';
        $.ajax({
            type: "POST",
            url: factoringQuery,
            data: {
                factoringMode: $("#factoringMode").val(),
                crnCode: $("#crnCode").val(),
                factoringAmount: $("#factoringAmount").val(),
                factoringStatus: $("#factoringStatus").val()
            },
            dataType: "json",
            success: function (data) {
                var contents = '',
                    $resultList = $(".resultList"),
                    noResult = '<?php echo $this->translate("noData"); ?>';

                if (data.rows.length === 0) {
                    contents += '<li>'
                        + ' <div class="panel panel-success">'
                        + '  <div class="panel-heading">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>&nbsp;</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'

                        + '  <div class="panel-body">'
                        + '   <div class="row">'
                        + '    <div class="col-sm-12">'
                        + '     <p>' + noResult + '</p>'
                        + '    </div>'
                        + '   </div>'
                        + '  </div>'
                        + ' </div>'
                        + '</li>';
                } else {
                    $.each(data.rows, function (i, item) {
                        var base = new Base64();
                        var resultEnCode = base.encode(item.factoringID);

                        var data = $.data(dataDict, 'dataDict');
                        var factoringStatus = '-';
                        $.each(data, function (key, itemDict) {
                            if (key === 'FACTORING_STATUS') {
                                $.each(itemDict, function (i, dict) {
                                    if (dict.code === item.factoringStatus) {
                                        factoringStatus = dict.name;
                                    }
                                });
                            }
                        });

                        var factoringNoStr = '<?php echo $this->translate("factoringListNo"); ?>',
                            orderNoStr = '<?php echo $this->translate("factoringListOrderNo"); ?>',
                            debtorCustomerNameStr = '<?php echo $this->translate("factoringDebtor"); ?>',
                            factoringStatusStr = '<?php echo $this->translate("factoringStatus"); ?>',
                            receivableTotalAmountStr = '<?php echo $this->translate("factoringReceivableTotalAmount"); ?>',
                            financingTotalAmountStr = '<?php echo $this->translate("factoringFinancingTotalAmount"); ?>',
                            periodStr = '<?php echo $this->translate("factoringPeriod"); ?>',
                            expiryDateStr = '<?php echo $this->translate("factoringExpiryDate"); ?>',
                            daysStr = '<?php echo $this->translate("factoringDays"); ?>',
                            infoStr = '<?php echo $this->translate("factoringInfo"); ?>';
                        contents += '<li style="cursor: pointer;" data-resultEnCode="' + resultEnCode + '">'
                            + ' <div class="panel panel-success">'
                            + '  <div class="panel-heading">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-11">'
                            + '     <span>' + factoringNoStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            // + '     <span>' + orderNoStr + '</span>&nbsp;&nbsp;'
                            // + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>' + debtorCustomerNameStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + item.debtorCustomerName + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                            + '     <span>' + factoringStatusStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + factoringStatus + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-1">'
                            + '     <p class="text-right"><a href="/user/finance/view?' + resultEnCode + '">' + infoStr + '</a></p>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'

                            + '  <div class="panel-body">'
                            + '   <div class="row">'
                            + '    <div class="col-sm-3">'
                            + '     <span>' + receivableTotalAmountStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + item.crnCode + ' ' + item.receivableTotalAmount  +'</span>'
                            + '    </div>'
                            + '    <div class="col-sm-4">'
                            + '     <span>' + financingTotalAmountStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + item.crnCode + ' ' + item.financingTotalAmount + ' ( ' + item.financingCrnCode + ' ' + item.tgtFinancingTotalAmount  + ')</span>'
                            + '    </div>'
                            + '    <div class="col-sm-2">'
                            + '     <span>' + periodStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + item.period + ' ' + daysStr + '</span>'
                            + '    </div>'
                            + '    <div class="col-sm-3">'
                            + '     <span>' + expiryDateStr + '</span>&nbsp;&nbsp;'
                            + '     <span>' + new Date(item.expiryDate).format("yyyy-MM-dd") + '</span>'
                            + '    </div>'
                            + '   </div>'
                            + '  </div>'
                            + ' </div>'
                            + '</li>';
                    });
                }

                $resultList.html(contents);

                $(".resultList li").click(function () {
                    var resultEnCodeUrl = $(this).attr("data-resultEnCode");
                    if (resultEnCodeUrl !== undefined && resultEnCodeUrl !== '') {
                        window.location.href = '/user/finance/view?' + resultEnCodeUrl;
                    }
                });
            }
        });
    }
    
    function refreshFlowResultList() {
	    var $limit = $("#limit"),
            $offset = $("#offset"),
            noMore = '<?php echo $this->translate("noMore"); ?>',
            loadMore = '<?php echo $this->translate("loadMore"); ?>';
        layui.use('flow', function(){
            var $ = layui.jquery; //不用额外加载jQuery，flow模块本身是有依赖jQuery的，直接用即可。
            var flow = layui.flow;
            flow.load({
                elem: '#flowResultList' //指定列表容器
                ,end: noMore    // 用于显示末页内容
                ,loadMore: '<cite>' + loadMore + '</cite>'  // 加载更多
                ,mb: 250    // 与底部的临界距离，即当滚动条与底部产生该距离时，触发加载。
                ,done: function(page, next){ //到达临界点（默认滚动触发），触发下一页
                    var lis = [];
                    var factoringQuery = '/user/finance/factoring-list-ajax';
                    $.ajax({
                        type: "POST",
                        url: factoringQuery,
                        data: {
                            limit: $limit.val(),
                            skip: $("#offset").val(),
                            factoringMode: $("#factoringMode").val(),
                            crnCode: $("#crnCode").val(),
                            factoringAmount: $("#factoringAmount").val(),
                            factoringStatus: $("#factoringStatus").val()
                        },
                        dataType: "json",
                        success: function (data) {
                            var contents = '',
                                noResult = '<?php echo $this->translate("noData"); ?>';

                            if (data.rows.length === 0) {
                                contents += '<li>'
                                    + ' <div class="panel panel-success">'
                                    + '  <div class="panel-heading">'
                                    + '   <div class="row">'
                                    + '    <div class="col-sm-12">'
                                    + '     <p>&nbsp;</p>'
                                    + '    </div>'
                                    + '   </div>'
                                    + '  </div>'

                                    + '  <div class="panel-body">'
                                    + '   <div class="row">'
                                    + '    <div class="col-sm-12">'
                                    + '     <p>' + noResult + '</p>'
                                    + '    </div>'
                                    + '   </div>'
                                    + '  </div>'
                                    + ' </div>'
                                    + '</li>';
                            } else {
                                $.each(data.rows, function (i, item) {
                                    var base = new Base64();
                                    var resultEnCode = base.encode(item.factoringID);

                                    var dataDictList = $.data(dataDict, 'dataDict');
                                    var factoringStatus = '-';
                                    $.each(dataDictList, function (key, itemDict) {
                                        if (key === 'FACTORING_STATUS') {
                                            $.each(itemDict, function (i, dict) {
                                                if (dict.code === item.factoringStatus) {
                                                    factoringStatus = dict.name;
                                                }
                                            });
                                        }
                                    });

                                    var factoringNoStr = '<?php echo $this->translate("factoringListNo"); ?>',
                                        orderNoStr = '<?php echo $this->translate("factoringListOrderNo"); ?>',
                                        debtorCustomerNameStr = '<?php echo $this->translate("factoringDebtor"); ?>',
                                        factoringStatusStr = '<?php echo $this->translate("factoringStatus"); ?>',
                                        receivableTotalAmountStr = '<?php echo $this->translate("factoringReceivableTotalAmount"); ?>',
                                        financingTotalAmountStr = '<?php echo $this->translate("factoringFinancingTotalAmount"); ?>',
                                        periodStr = '<?php echo $this->translate("factoringPeriod"); ?>',
                                        expiryDateStr = '<?php echo $this->translate("factoringExpiryDate"); ?>',
                                        daysStr = '<?php echo $this->translate("factoringDays"); ?>',
                                        infoStr = '<?php echo $this->translate("factoringInfo"); ?>';

                                    contents += '<li style="cursor: pointer;" data-resultEnCode="' + resultEnCode + '">'
                                        + ' <div class="panel panel-success">'
                                        + '  <div class="panel-heading">'
                                        + '   <div class="row">'
                                        + '    <div class="col-sm-11">'
                                        + '     <span>' + factoringNoStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                                        // + '     <span>' + orderNoStr + '</span>&nbsp;&nbsp;'
                                        // + '     <span>' + item.factoringNo + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                                        + '     <span>' + debtorCustomerNameStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + item.debtorCustomerName + '</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'
                                        + '     <span>' + factoringStatusStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + factoringStatus + '</span>'
                                        + '    </div>'
                                        + '    <div class="col-sm-1">'
                                        + '     <p class="text-right"><a href="/user/finance/view?' + resultEnCode + '">' + infoStr + '</a></p>'
                                        + '    </div>'
                                        + '   </div>'
                                        + '  </div>'

                                        + '  <div class="panel-body">'
                                        + '   <div class="row">'
                                        + '    <div class="col-sm-3">'
                                        + '     <span>' + receivableTotalAmountStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + item.crnCode + ' ' + item.receivableTotalAmount + '</span>'
                                        + '    </div>'
                                        + '    <div class="col-sm-4">'
                                        + '     <span>' + financingTotalAmountStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + item.crnCode + ' ' + item.financingTotalAmount + ' ( ' + item.financingCrnCode + ' ' + item.tgtFinancingTotalAmount + ')</span>'
                                        + '    </div>'
                                        + '    <div class="col-sm-2">'
                                        + '     <span>' + periodStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + item.period + ' ' + daysStr + '</span>'
                                        + '    </div>'
                                        + '    <div class="col-sm-3">'
                                        + '     <span>' + expiryDateStr + '</span>&nbsp;&nbsp;'
                                        + '     <span>' + new Date(item.expiryDate).format("yyyy-MM-dd") + '</span>'
                                        + '    </div>'
                                        + '   </div>'
                                        + '  </div>'
                                        + ' </div>'
                                        + '</li>';
                                });
                            }

                            lis.push(contents);

                            // 执行下一页渲染，第二参数为：满足“加载更多”的条件，即后面仍有分页
                            // pages为Ajax返回的总页数，只有当前页小于总页数的情况下，才会继续出现加载更多
                            next(lis.join(''), page < data.totalPage);
                            // 配置分页
                            $offset.val(parseInt($offset.val()) + parseInt($limit.val()));

                            $(".resultList li").click(function () {
                                var resultEnCodeUrl = $(this).attr("data-resultEnCode");
                                if (resultEnCodeUrl !== undefined && resultEnCodeUrl !== '') {
                                    window.location.href = '/user/finance/view?' + resultEnCodeUrl;
                                }
                            });
                        }
                    });
                }
            });
        });
    }
</script>
</body>
</html>
