<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <div class="panel panel-default">
            <div class="panel-body bg-color">
                <div class="row text-white">
                    <div class="col-sm-12 col-md-5">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <p class="text-center">融资(日)利率</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo $this->LoanView['interestPercent'] * 100; ?> %</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <p class="text-center">逾期(日)利率</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo $this->LoanView['overdueInterestPercent'] * 100; ?> %</p>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="row span-margin">
                                    <div class="col-md-12">
                                        <p class="text-center">宽限期(日)利率</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <p class="text-center span-font-size-30"><?php echo $this->LoanView['graceInterestPercent'] * 100; ?> %</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-7">
                        <div class="row span-margin-10">
                            <div class="col-md-5">
                                <span>方案编号</span>&nbsp;&nbsp;
                                <b><span><?php echo $this->LoanView['factoringNo']; ?></span></b>
                            </div>
                            <div class="col-md-7">
                                <span>债务方</span>&nbsp;&nbsp;
                                <b><span><?php echo $this->LoanView['debtorCustomerName']; ?></span></b>
                            </div>
                        </div>
                        <div class="row span-margin-10">
                            <div class="col-md-5">
                                <span>订单编号</span>&nbsp;&nbsp;
                                <b><span><?php echo $this->LoanView['orderNo']; ?></span></b>
                            </div>
                            <div class="col-md-7">
                                <span>应收账款金额</span>&nbsp;&nbsp;
                                <span><b><?php echo $this->LoanView['crnCode']; ?> <?php echo $this->LoanView['receivableTotalAmount'] != 0 ? number_format($this->LoanView['receivableTotalAmount'], 2) : '----'; ?></b></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-5">
                                <span>融资模式</span>&nbsp;&nbsp;
                                <b><span><?php echo $this->ShowDictionaryTo("FACTORING_MODE", $this->userLangCode, $this->dic_Setting['FACTORING_MODE'], $this->LoanView['factoringMode']); ?></span></b>
                            </div>
                            <div class="col-md-7">
                                <span>计划融资金额</span>&nbsp;&nbsp;
                                <span><b><?php echo $this->LoanView['crnCode']; ?> <?php echo $this->LoanView['financingTotalAmount'] != 0 ? number_format($this->LoanView['financingTotalAmount'], 2) : '----'; ?></b> 折合 <b><?php echo $this->LoanView['financingCrnCode']; ?> <?php echo $this->LoanView['tgtFinancingTotalAmount'] != 0 ? number_format($this->LoanView['tgtFinancingTotalAmount'], 2) : '----'; ?></b></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary">详细资料</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">保理公司</p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo $this->LoanView['companyName']; ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">计划放款日</p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo date('Y-m-d', strtotime($this->LoanView['loanDate'])); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">计划届满日</p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666">
                            <?php echo date('Y-m-d', strtotime($this->LoanView['expiryDate'])); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">预计总利息</p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static text-666">
                            <?php echo $this->LoanView['financingCrnCode']; ?> <?php echo $this->LoanView['interest'] != 0 ? number_format($this->LoanView['interest'], 2) : '----'; ?>
                        </p>
                    </div>
                    <div class="col-md-7">
                        <div class="well well-sm text-999" style="margin-bottom: 0 !important;">计划收取的利息总额，仅作参考。实收利息以实际发货情况及回款情况按日收取。</div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">文件</p>
                    </div>
                    <div class="col-md-10"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12 text-primary">
                        <?php
                        echo $this->ShowOrderContract4Factoring($this->contractList, $this->accountID, 'FTTA', $this->orders['client'], $this->hasIDCertificate);
                        ?>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">服务费用</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>费用项目</th>
                                <th>费用</th>
                                <th>服务费率</th>
                                <th>说明</th>
                                <th>付款情况</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>基础服务费</td>
                                <td><?php echo $this->LoanView['factoringItem']['financingCrnCode']; ?> <?php echo $this->LoanView['factoringItem']['serviceCharge'] != 0 ? number_format($this->LoanView['factoringItem']['serviceCharge'], 2) : '----'; ?></td>
                                <td><?php echo $this->LoanView['serviceChargePercent'] * 100; ?> %</td>
                                <td class="text-999">计算公式：应收账款金额 * 服务费率 * 汇率。发放融资前款前，一次性收取。</td>
                                <td>
                                    <?php if ($this->LoanView['factoringItem']['serviceChargeTradingID'] == ''):?>
                                    未开始
                                    <?php else:?>
                                    <?php echo $this->ShowDictionaryTo("PAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->LoanView['factoringItem']['serviceChargeTradingStatus']); ?>
                                    <?php endif;?>
                                </td>
                            </tr>
                            <tr>
                                <td>担保服务费</td>
                                <td><?php echo $this->LoanView['factoringItem']['financingCrnCode']; ?> <?php echo $this->LoanView['factoringItem']['guaranteeServiceFee'] != 0 ? number_format($this->LoanView['factoringItem']['guaranteeServiceFee'], 2) : '----'; ?></td>
                                <td><?php echo $this->LoanView['guaranteeServiceFeePercent'] * 100; ?> %</td>
                                <td class="text-999">计算公式：担保金额 * 服务费率 * 汇率。发放融资前款前，一次性收取。</td>
                                <td>
                                    <?php if ($this->LoanView['factoringItem']['serviceChargeTradingID'] == ''):?>
                                        未开始
                                    <?php else:?>
                                        <?php echo $this->ShowDictionaryTo("PAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->LoanView['factoringItem']['serviceChargeTradingStatus']); ?>
                                    <?php endif;?>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-1">
                        <p class="form-control-static margin-left-5 text-999">合计费用</p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static margin-left-25 text-666">
                            <?php echo $this->LoanView['factoringItem']['financingCrnCode']; ?> <?php echo $this->LoanView['factoringItem']['serviceCharge'] + $this->LoanView['factoringItem']['guaranteeServiceFee'] != 0 ? number_format($this->LoanView['factoringItem']['serviceCharge'] + $this->LoanView['factoringItem']['guaranteeServiceFee'], 2) : '----';; ?>
                        </p>
                    </div>
                    <?php if ($this->LoanView['factoringItem']['serviceChargeTradingStatus'] != '3' && $this->LoanView['factoringItem']['serviceChargeTradingID'] != ''):?>
                    <div class="col-md-2">
                        <a class="btn btn-warning" href="/user/settle/payment?<?php echo base64_encode($this->LoanView['factoringItem']['serviceChargeTradingID']);?>"><?php echo $this->translate('Saltter_payment');?></a>
                    </div>
                    <?php endif; ?>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">放款情况</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>放款编号</th>
                                <th>放款日期</th>
                                <th>货币</th>
                                <th class="text-right">放款金额</th>
                                <th class="text-right">利息</th>
                                <th class="text-right">宽限期利息</th>
                                <th class="text-right">逾期利息</th>
                                <th class="text-right">合计利息</th>
                                <th class="text-right">未核销本金</th>
                                <th class="text-right">未核销利息</th>
                                <th>状态</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (empty($this->LoanView['factoringItem']['factoringLoanList'])):?>
                            <tr>
                                <td colspan="11">暂无放款记录</td>
                            </tr>
                            <?php else:?>
                            <?php foreach ($this->LoanView['factoringItem']['factoringLoanList'] as $factoringLoan):?>
                            <tr>
                                <td><?php echo $factoringLoan['loanNo']; ?></td>
                                <td><?php echo date('Y-m-d', strtotime($factoringLoan['loanDate'])); ?></td>
                                <td><?php echo $factoringLoan['loanCrnCode']; ?></td>
                                <td class="text-right"><?php echo $factoringLoan['loanAmount'] != 0 ? number_format($factoringLoan['loanAmount'], 2) : '----'; ?></td>
                                <td class="text-right"><?php echo $factoringLoan['totalGeneralInterest'] != 0 ? number_format($factoringLoan['totalGeneralInterest'], 2) : '----'; ?></td>
                                <td class="text-right"><?php echo $factoringLoan['totalGraceInterest'] != 0 ? number_format($factoringLoan['totalGraceInterest'], 2) : '----'; ?></td>
                                <td class="text-right"><?php echo $factoringLoan['totalOverdueInterest'] != 0 ? number_format($factoringLoan['totalOverdueInterest'], 2) : '----'; ?></td>
                                <td class="text-right">
                                    <?php echo $factoringLoan['totalInterest'] != 0 ? number_format($factoringLoan['totalInterest'], 2) : '----'; ?> <i class="layui-icon layui-icon-about" style="cursor: pointer;" data-toggle="modal" data-target="#interestModal" data-loan-id="<?php echo $factoringLoan['loanID']; ?>"></i>
                                </td>
                                <td class="text-right"><?php echo $factoringLoan['writeoffBalAmount'] != 0 ? number_format($factoringLoan['writeoffBalAmount'], 2) : '----'; ?></td>
                                <td class="text-right"><?php echo $factoringLoan['writeoffBalInterest'] != 0 ? number_format($factoringLoan['writeoffBalInterest'], 2) : '----'; ?></td>
                                <td><?php echo $this->ShowDictionaryTo("LOAN_STATUS", $this->userLangCode, $this->dic_Setting['LOAN_STATUS'], $factoringLoan['loanStatus']); ?></td>
                            </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">还款情况</p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>还款编号</th>
                                <th>还款日期</th>
                                <th class="text-right">应还金额</th>
                                <th>结汇汇率</th>
                                <th class="text-right">已付金额</th>
                                <th class="text-right">还利息</th>
                                <th class="text-right">还本金</th>
                                <th class="text-right">剩余货款</th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (empty($this->LoanView['factoringItem']['factoringRepaymentList'])):?>
                                <tr>
                                    <td colspan="11">暂无还款记录</td>
                                </tr>
                            <?php else:?>
                            <?php foreach ($this->LoanView['factoringItem']['factoringRepaymentList'] as $factoringRepayment):?>
                                <tr>
                                    <td><?php echo $factoringRepayment['repaymentNo']; ?></td>
                                    <td><?php echo date('Y-m-d', strtotime($factoringRepayment['repaymentDate'])); ?></td>
                                    <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo $factoringRepayment['totalAmount'] != 0 ? number_format($factoringRepayment['totalAmount'], 2) : '----'; ?></td>
                                    <td><?php echo $factoringRepayment['exchangeRate']; ?></td>
                                    <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo $factoringRepayment['repaymentTotalAmount'] != 0 ? number_format($factoringRepayment['repaymentTotalAmount'], 2) : '----'; ?></td>
                                    <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo $factoringRepayment['writeoffInterestAmount'] != 0 ? number_format($factoringRepayment['writeoffInterestAmount'], 2) : '----'; ?></td>
                                    <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo $factoringRepayment['writeoffPrincipalAmount'] != 0 ? number_format($factoringRepayment['writeoffPrincipalAmount'], 2) : '----'; ?></td>
                                    <td class="text-right"><?php echo $factoringRepayment['crnCode']; ?> <?php echo $factoringRepayment['writeoffFinalAmount'] != 0 ? number_format($factoringRepayment['writeoffFinalAmount'], 2) : '----'; ?></td>
                                </tr>
                            <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15">核销记录</p>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<!-- Modal 利息明细 -->
<div class="modal fade" id="interestModal" tabindex="-1" role="dialog" aria-labelledby="interestLabel">
    <div class="modal-dialog modal-lg" role="document" style="width: 1080px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">利息明细</h4>
            </div>

            <div class="modal-body">
                <table class="table table-bordered" id="resultListTable">
                </table>
            </div>
        </div>
    </div>
</div>

<!--PDF预览-->
<div id="signViewDiv" style="display: none; background-color: #F6F6F6;">
    <div class="sign-button">企业签署</div>
    <div class="person-sign-button">个人签署</div>
    <div class="download-button">下载</div>
    <div class="pdfDoc" style="padding-left:50px;">
        <div id="pdfPageBox">
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<!-- pdf -->
<script type="text/javascript" src="/ky/pdf/pdf.js"></script>
<script type="text/javascript" src="/ky/pdf/pdf.worker.js"></script>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});

    $("#interestModal").on('show.bs.modal', function (e) {
        var triggered = $(e.relatedTarget),
            loanID = triggered.data("loan-id"),
            $resultListTable = $('#resultListTable');

        var options = {
            query:{
                loanID: loanID
            }
        };
        $resultListTable.bootstrapTable('refresh', options);

        $resultListTable.bootstrapTable({
            url: '/user/finance/factoring-interest-list-ajax',
            method: 'post',
            // showRefresh: true,
            // search: true,
            pagination: true,
            // onlyInfoPagination: true,
            classes: 'table table-hover table-no-bordered',
            sidePagination: 'server',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            queryParams: function(params) {
                return {
                    loanID: loanID
                };
            },
            columns: [{
                field: 'principalAmount',
                title: '<?php echo $this->translate("principalAmount"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    return formatCurrency(value, 2);
                }
            }, {
                field: 'valueDate',
                title: '<?php echo $this->translate("interestValueDate"); ?>',
                formatter: function (value) {
                    return new Date(value).format("yyyy-MM-dd");
                }
            }, {
                field: 'expiryDate',
                title: '<?php echo $this->translate("interestExpiryDate"); ?>',
                formatter: function (value) {
                    return new Date(value).format("yyyy-MM-dd");
                }
            }, {
                field: 'interestDays',
                title: '<?php echo $this->translate("interestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value + ' Days';
                }
            }, {
                field: 'totalInterest',
                title: '<?php echo $this->translate("totalInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'graceInterestDays',
                title: '<?php echo $this->translate("graceInterestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value + ' Days';
                }
            }, {
                field: 'graceInterest',
                title: '<?php echo $this->translate("graceInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'overdueInterestDays',
                title: '<?php echo $this->translate("overdueInterestDays"); ?>',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value + ' Days';
                }
            }, {
                field: 'overdueInterest',
                title: '<?php echo $this->translate("overdueInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }, {
                field: 'writeoffBalInterest',
                title: '<?php echo $this->translate("writeoffBalInterest"); ?>',
                halign: 'center',
                align: 'right',
                formatter: function (value) {
                    if (value === undefined || value === '' || value === null) {
                        return "----";
                    } else {
                        return formatCurrency(value, 2);
                    }
                }
            }]
        });
    });
</script>
</body>
</html>
