<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/lang/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1>删除语言</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
    <table class="admin_list">
      <tr>
        <th>编号</th>
        <th>名称</th>
        <th>说明</th>
      </tr>
      <?php if(is_array($this->langs)):?>
      <?php foreach($this->langs as $lang):?>
      <tr>
        <td><input type="checkbox" id="role_id<?php echo ($role['role_id'])?>" name="lang_id[]" checked value="<?php echo ($lang['lang_id'])?>">
          <?php echo ($lang['lang_id'])?></td>
        <td><?php echo ($lang['lang_name'])?></td>
        <td><?php echo ($lang['lang_content'])?></td>
      </tr>
      <?php endforeach; ?>
      <?php endif;?>
    </table>
    <div class="batch">
      <input type="submit" name="" class="admin_bnt2" value="确认删除" >
    </div>
</form>
<?php echo $this->render("footer.phtml") ?>
