<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/userattr/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1>删除会员属性</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
      <th>编号</th>
      <th>名称</th>
      <th>字段</th>
    </tr>
    <?php if(is_array($this->attributes)):?>
    <?php foreach($this->attributes as $attribute):?>
    <tr>
      <td><input type="checkbox" id="attr_id<?php echo ($attribute['attr_id'])?>" name="attr_id[]" checked value="<?php echo ($attribute['attr_id'])?>">
        <?php echo ($attribute['attr_id'])?></td>
      <td><?php echo ($attribute['attr_name'])?></td>
      <td><?php echo ($attribute['field_name'])?></td>
    </tr>
    <?php endforeach; ?>
    <?php endif;?>
  </table>
  <div class="batch">
    <input type="submit" name="" class="admin_bnt2" value="确认删除">
  </div>
</form>
<?php echo $this->render("footer.phtml") ?> 