<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
		event: "keyup",
		rules: {},
		messages: {},
		submitHandler: function() {
			SeedMsgBox("正在保存中，请稍候...");
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->baseUrl();?>/userattr/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
	
	//
	$("input[@name=attr_input_type]").click(function(){
		var a = $("input[@name=attr_input_type][@checked]").val();
		if (a == '0' || a == '1'){ 
			$('#attr_values').attr('disabled', true) ;
			$('#attr_displays').attr('disabled', true) ;
			$('#attr_values').val('');
		} else {
			$('#attr_values').attr('disabled', false) ;
			$('#attr_displays').attr('disabled', false) ;
		}		
	});
	
	var a = $("input[@name=attr_input_type][@checked]").val();
	if (a == '0' || a == '1'){ 
		$('#attr_values').attr('disabled', 'true') ;
		$('#attr_displays').attr('disabled', true) ;
	} else {
		$('#attr_values').attr('disabled', false) ;
		$('#attr_displays').attr('disabled', false) ;
	}
});


</script>

<h1>修改会员属性</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back(-1);"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_form">
    <input type="hidden" name="attr_id" id="attr_id" value="<?php echo ($this->attribute['attr_id']);?>">
    <tr>
      <td><strong>属性名称</strong>
        <p>
          <input name="attr_name" id="attr_name" type="text" class="admin_txt1"  value="<?php echo ($this->attribute['attr_name']);?>" />
        </p></td>
    </tr>
    <tr>
      <td><strong>该属性值的录入方式</strong>&nbsp;&nbsp;<font color="#ff0000">(* 只有'多选属性'和'复选属性'才提供‘可选值列表’操作)</font>
        <p>
          <input type="radio" name="attr_input_type" value="0" <?php if (($this->attribute['attr_input_type']) == 0) echo 'checked'?>/>
          单行录入
          <input type="radio" name="attr_input_type" value="1" <?php if (($this->attribute['attr_input_type']) == 1) echo 'checked'?>/>
          多行文本框
          <input type="radio" name="attr_input_type" value="2" <?php if (($this->attribute['attr_input_type']) == 2) echo 'checked'?>/>
          单选属性
          <input type="radio" name="attr_input_type" value="3" <?php if (($this->attribute['attr_input_type']) == 3) echo 'checked'?>/>
          复选属性 </p></td>
    </tr>
    <tr>
      <td><strong>可选值列表:</strong>
        <p>
          <textarea name="attr_values" id="attr_values" style="height: 100px;" class="textarea"><?php echo ($this->attribute['attr_values']);?></textarea>
        </p></td>
    </tr>
    <tr>
      <td><strong>可选值显示列表:</strong>
        <p>
          <textarea name="attr_displays" id="attr_displays" style="height: 100px;" class="textarea"><?php echo ($this->attribute['attr_displays']);?></textarea>
        </p></td>
    </tr>
  </table>
  <div class="batch">
    <input name="" type="submit" value="提交"  class="admin_bnt"/>
    &nbsp;&nbsp;&nbsp;
    <input name="" type="reset" value="重置"  class="admin_bnt"/>
    &nbsp;&nbsp;&nbsp; </div>
</form>
<?php echo $this->render("footer.phtml") ?>
