<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/login/login.css" rel="stylesheet">
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
	<link href="/ky/css/register/register.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu shadow">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<img alt="eTradeFast" src="/ky/images/index/Logo_loginH75.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎注册
			</p>

			<p class="navbar-text navbar-right">
                <?php echo $this->translate('alreadyRegistered'); ?> <a href="/" class="navbar-link"><?php echo $this->translate('login_s'); ?></a>
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid register-body">
	<div class="container">
		<div class="col-md-10 col-md-offset-1 col-xs-12 register-form-div">
			<form class="form-horizontal register-form-body" action="<?php echo $this->baseUrl();?>/register" method="post" id="register_form" name="register_form">

                <input type="hidden" name="isPersonAccount" id="isPersonAccount" value="false">

				<div class="register-type-info">
                    <div class="row">
						<div class="col-md-6 text-center">
							<a href="javascript:void(0)" id="changeCompanyRegister" ispersonaccount="false">企业注册</a>
						</div>
						<div class="col-md-6 text-center">
							<a href="javascript:void(0)" id="changePersonRegister" ispersonaccount="true">个人注册</a>
						</div>
					</div> 
				</div>

				<div class="form-group accountName">
					<label for="accountName" class="col-sm-3 control-label"><?php echo $this->translate('regd_company_name'); ?></label>
					<div class="col-sm-7">
						<input type="text" class="form-control" name="accountName" id="accountName" required placeholder="<?php echo $this->translate('is_comname'); ?>">
					</div>
				</div>

				<div class="form-group email">
					<label for="email" class="col-sm-3 control-label"><?php echo $this->translate('companyEM'); ?></label>
					<div class="col-sm-7">
						<input type="email" class="form-control" name="email" id="email" required placeholder="<?php echo $this->translate('ps_email'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="regdCountryCode" class="col-sm-3 col-xs-12 control-label"><?php echo $this->translate('address'); ?></label>
					<div class="col-sm-7">
						<select class="form-control" name="regdCountryCode" id="regdCountryCode" required>
                            <?php echo $this->ShowDictionaryList($this->dic_Setting['COUNTRY_ISO_CODE'], $this->userlangCode, $this->dic_Setting['COUNTRY_ISO_CODE']); ?>
						</select>
					</div>
				</div>

				<div class="form-group">
					<label for="regdAddress" class="col-sm-3 control-label"></label>
					<div class="col-sm-7">
						<input type="text" class="form-control" name="regdAddress" id="regdAddress" required placeholder="<?php echo $this->translate('is_regadress'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="name" class="col-sm-3 control-label"><?php echo $this->translate('name'); ?></label>
					<div class="col-sm-7">
						<input type="text" class="form-control" name="name" id="name" required placeholder="<?php echo $this->translate('name'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="mobilePhone" class="col-sm-3 control-label"><?php echo $this->translate('phone'); ?></label>
					<div class="col-sm-7">
						<input type="text" class="form-control" name="mobilePhone" id="mobilePhone" required placeholder="<?php echo $this->translate('is_phone'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="ecommloginname" class="col-sm-3 control-label"><?php echo $this->translate('elogname'); ?></label>
					<div class="col-sm-7">
						<input type="email" class="form-control" name="ecommloginname" id="ecommloginname" required placeholder="<?php echo $this->translate('is_emlog'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="ecommpasswsd" class="col-sm-3 control-label"><?php echo $this->translate('password'); ?></label>
					<div class="col-sm-7">
						<input type="password" class="form-control" name="ecommpasswsd" id="ecommpasswsd" required placeholder="<?php echo $this->translate('is_passwd'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="checkecommrpasswsd" class="col-sm-3 control-label"><?php echo $this->translate('confirmPSD'); ?></label>
					<div class="col-sm-7">
						<input type="password" class="form-control" name="checkecommrpasswsd" id="checkecommrpasswsd" required placeholder="<?php echo $this->translate('is_rpasswd'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="serviceContract" class="col-sm-3 control-label"></label>
					<div class="checkbox col-sm-7">
						<label>
							<input type="checkbox" value="" name="serviceContract" id="serviceContract" required>
							<input type="hidden" id="isReadServiceContract" value="false">
                            <?php echo $this->translate('check_service_contract'); ?>&nbsp;
						</label>
						<a href="javascript:void(0)" id="check_doc" style="color: #01AAED;"><?php echo $this->translate('service_contract'); ?></a>
					</div>
				</div>

				<div class="form-group">
                    <div class="col-sm-12 col-md-7 col-md-offset-3">
					    <button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('returnReg'); ?></button>
                    </div>
				</div>
			</form>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerSimple.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {
		$("#register_form").validate({
			rules: {
				ecommloginname: {
					checkLoginName: true
				},
				ecommpasswsd: {
					isValidPassword: true,
					minlength: 8,
					maxlength: 30
				},
				checkecommrpasswsd: {
					reCheckPassword: true
				}
			},
			messages: {
				ecommpasswsd : {
					required: "<?php echo $this->translate('de_null'); ?>",
					minlength: "<?php echo $this->translate('mat_psd');?>",
					maxlength: "<?php echo $this->translate('is_passwd');?>"
				},
				serviceContract: {
					required: "<?php echo $this->translate('check_service_contract'); ?>"
				}
			},
			errorPlacement: function(error, element) {
				// Append error within linked label
				$(element)
					.closest( "form" )
					.find( "label[for='" + element.attr( "id" ) + "']" )
					.parent().addClass("has-error").removeClass("has-success")
					.append( error );
			},
			success: function(label) {
				var forName = $(label).attr("for");
				$("label[for='" + forName + "']").parent().addClass("has-success").removeClass("has-error");
				$(label).remove();
			},
			highlight: function (element) {
				$("label[for='" + element.id + "']").parent().addClass("has-error").removeClass("has-success");
			},
			submitHandler: function (form) {
				form.submit();
			}
		});
	});

	$(function () {
		$("#serviceContract").click(function () {
			if ($("#isReadServiceContract").val() == 'false') {
				$("#serviceContract").prop('checked', false);
				toReadServiceContract();
			}
		});
		$("#check_doc").click(function () {
			if ($("#isReadServiceContract").val() == 'false') {
				$("#serviceContract").prop('checked', false);
			}
			toReadServiceContract();
		});

		$("#changeCompanyRegister).click(function () {
                $(this).addClass("active");
                $("#changePersonRegister").removeClass("active");
        });

		$("#changePersonRegister).click(function () {
                $(this).addClass("active");
                $("#changeCompanyRegister").removeClass("active");
        });
		
		$("#changeCompanyRegister,#changePersonRegister").click(function () {
            if ($(this).attr("isPersonAccount") === 'true') {
                $(".accountName,.email").hide();
                $("#isPersonAccount").val("true");
            } else {
                $(".accountName,.email").show();
                $("#isPersonAccount").val("false");
            }
        });
	});

	function toReadServiceContract() {
		$.post('/register/servicehtml', {}, function(service){
			layer.open({
				type: 1,
				title: "<?php echo $this->translate('service_contract'); ?>",
				area: ['1024px', '97%'],
				scrollbar: false,
				content: service,
				success: function(layero, index){
					$(".layui-layer-content").scroll(function () {
						// console.log(this.scrollHeight);
						if (this.scrollHeight - this.scrollTop === this.clientHeight) {
							console.log("in");
							$("#isReadServiceContract").val('true');
							$("#serviceContract").prop('checked', true);
						}
					});
				}
			});
		});
	}

	// 邮箱登录名验证
	jQuery.validator.addMethod("checkLoginName", function(value, element) {
		return $.post("<?php echo $this->BaseUrl();?>/register/check", {
				ecommloginname: value
			},
			function (data) {
				data = jQuery.parseJSON(data);
				return data.result == false;
			}
		);
	}, "<?php echo $this->translate('de_use');?>");

	// 密码规验证(8-30位  字母数字)
	jQuery.validator.addMethod("isValidPassword", function(value, element) {
		var regExp=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,30}$/;
		return this.optional(element) || (regExp.test(value));
	}, "<?php echo $this->translate('is_passwd');?>");

	// 验证确认密码
	jQuery.validator.addMethod("reCheckPassword", function(value, element) {
		var psw = $("#ecommpasswsd").val();
		return this.optional(element) || (value === psw);
	}, "<?php echo $this->translate('is_psd');?>");
</script>
</body>
