<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/index/index.css" rel="stylesheet">
	<link href="/ky/css/register/register.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="javascript:void(0)">
				<img alt="eTradeFast" src="/ky/images/logo.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎注册
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid index-body">
	<div class="container">
	
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

</body>