<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/index/index.css" rel="stylesheet">
	<link href="/ky/css/register/register.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="javascript:void(0)">
				<img alt="eTradeFast" src="/ky/images/logo.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎注册
			</p>

			<p class="navbar-text navbar-right">
				已经注册，现在就 <a href="<?php echo $this->seed_Setting['user_app_server'] ?>/" class="navbar-link">登录</a>
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid register-body">
	<div class="container">
		<div class="col-md-8 col-md-offset-2 register-form-body">
			<form class="form-horizontal login-body-form" action="<?php echo $this->baseUrl();?>/register" method="post" id="register_form">
				<div class="register-user-info">
					User Info
				</div>
				
				<div class="form-group">
					<label for="name" class="col-sm-2 control-label"><?php echo $this->translate('name'); ?></label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="name" id="name" required placeholder="<?php echo $this->translate('name'); ?>">
					</div>
				</div>
				
				<div class="form-group">
					<label for="ecommloginname" class="col-sm-2 control-label"><?php echo $this->translate('elogname'); ?></label>
					<div class="col-sm-10">
						<input type="email" class="form-control" name="ecommloginname" id="ecommloginname" required placeholder="<?php echo $this->translate('elogname'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="ecommpasswsd" class="col-sm-2 control-label"><?php echo $this->translate('password'); ?></label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="ecommpasswsd" id="ecommpasswsd" required placeholder="<?php echo $this->translate('password'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="checkecommrpasswsd" class="col-sm-2 control-label"><?php echo $this->translate('confirmPSD'); ?></label>
					<div class="col-sm-10">
						<input type="password" class="form-control" id="checkecommrpasswsd" required placeholder="<?php echo $this->translate('confirmPSD'); ?>">
					</div>
				</div>

				<div class="form-group">
					<label for="mobilePhone" class="col-sm-2 control-label"><?php echo $this->translate('phone'); ?></label>
					<div class="col-sm-10">
						<input type="text" class="form-control" name="mobilePhone" id="mobilePhone" required placeholder="<?php echo $this->translate('phone'); ?>">
					</div>
				</div>

				<div class="form-group">
					<button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('returnReg'); ?></button>
				</div>
			</form>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerSimple.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

</body>