<div style="background-color: #f4f4f4; position: absolute;">
	<div class=WordSection1 style="layout-grid:15.6pt; margin: 15px 20px; background-color: #fff; border: 1px solid #e2e2e2; padding: 15px 15px 50px 15px;">

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal align=center style='text-align:center'><span
                style='font-size:16.0pt;font-family:黑体'>《快移交易云平台服务协议》<span lang=EN-US><o:p></o:p></span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>1. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>特别提示</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>1.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>“快移交易云平台”</span><span lang=EN-US>(</span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>以下简称“快移平台”</span><span lang=EN-US>)</span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>是由深圳市<span class=GramE>快移网络</span>科技控股有限公司通过网站和手机应用程序“快移平台”向用户提供服务的客户服务端。用户在<span
                    class=GramE>使用快移平台</span>之前，应当认真阅读《快移交易云平台服务协议》（以下简称“本服务协议”）。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>1.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>在注册程序过程中，用户点击“同意”前应完整阅读本协议内容并确认已明确了解协议内容，一旦点击该按钮实际<span
                    class=GramE>使用快移平台</span>时，即表示用户完全理解并接受本协议项下的全部条款。用户在使用提供的各项服务之前，应仔细阅读<span
                    class=GramE>本服务</span>协议。如用户不同意<span class=GramE>本服务</span>协议，请停止使用，若因继续使用而产生的相关法律责任由用户自行承担。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>1.3</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>本协议内容中以黑体、加粗、下划线、斜体等方式显著标识的条款，请用户着重阅读。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>2. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户注册</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>2.1</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户确认，在通过完成注册程序或以其他深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司书面许可允许的其他方式<span class=GramE>使用快移平台</span>时，用户应当是具备完全民事行为能力和权利能力的自然人、法人或其他组织，否则，用户应在其法定监护人指导下方能<span
                    class=GramE>使用快移平台</span>，并由用户及其监护人对快移交易平台上的各项行为承担全部责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>2.2 </span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户在注册程序中，应当依照法律法规及深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司的要求，<span class=GramE>根据快移平台</span>相应页面的提示准确填写、上<span
                    class=GramE>传各项</span>用户资料，并在资料信息变更</span><span lang=EN-US>5</span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>日内及时进行用户信息更新，以确保用户提交的信息真实、准确、完整。若因用户未及时更新资料，导致有关流程和操作（包括后续资金流、信息流等作业）无法完成或发生错误，由此产生的一切后果和责任由用户承担，用户不得以此作为取消交易、拒绝付款或采取其他不当行为的理由。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>2.3</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户应通过注册设置的登录账号和密码<span class=GramE>登陆快移平台</span>，<span
                    class=GramE>遵守快移平台</span>及服务项目的相关服务协议及使用守则，且自行负责对登录账号及密码的保管及保密，用户对使用在该登录账号及密码下发生的所有行为承担责任。用户应以正确的步骤退出登录<span
                    class=GramE>离开快移平台</span>，一旦发现任何人未经用户授权使用其用户名和密码，应立即通知深圳市<span class=GramE>快移网络</span>科技控股有限公司并提供相应的证明。深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司将在合理时间内根据审查结果做出应对措施，在采取相应措施之前，用户应对已经产生的后果、损失自行承担责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>2.4</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户<span class=GramE>在快移平台</span>上的报价、缔约及线下履约行为，均视为<span
                    class=GramE>您用户</span>本人的行为，由用户您本人承担责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>服务内容</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.1</span></b><span
                lang=EN-US> </span><span class=GramE><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>快移平台</span></span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>的服务内容包括：订单跟踪管理、商品及物料管理、合作伙伴管理、交易合同及文档网络签署、文档及影像资料管理、报关及物流信息服务、交易结算服务和供应<span
                    class=GramE>链金融</span>服务等。深圳市<span class=GramE>快移网络</span>科技控股有限公司保留变更、中断、中止或终止部分或<span
                    class=GramE>全部快移平台</span>服务的权利。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户授权“快移平台”发布的交易信息包括但不限于订单、商品、合作伙伴等，同时用户同意发布方式包括但不限于网站及手机应用程序。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.3</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>您通过注册或者其他本公司允许的方式实际成为企业<span
                    class=GramE>在快移平台</span>的首位用户后，您被视为该企业授权该用户为企业有且仅有的公司信息管理员。您必须同时通过企业实名认证和个人实名认证后，方可以使用专属于您企业或本人的数字证书完成电子签章。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.4</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>您确认如您代表其他组织在本平台上签署文件的情况下，您向本公司提供其必要的签署信息（包括但不限于组织机构证明材料、印章等）已经获得该组织的合法授权，您应确保上述信息完整、真实、最新。您应对因您未能遵守本款约定而发生的任何损失、损毁及其他不利后果负责。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.5</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>您同意授权本公司向您的电子签署关联方定向提供您的签署信息，且同意<span
                    class=GramE>本服务</span>在未改变您所提供信息实质内容的情况下免于承担因该信息引起的任何法律责任。您同意在您征得签署关联方同意的情况下，向本公司提供其必要的签署信息（包括但不限于姓名、联系电话、电子邮箱、身份证号码等），您对此信息的真实性负责，因您提供的信息不真实、不完整而导致的任何纠纷或损失，本公司不负任何责任。</span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US><o:p>&nbsp;</o:p></span></b></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.6</span></b><span
                class=GramE><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>您实际</span></span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>使用本公司提供的电子签章服务即视为您同意与您的签署相对方就电子文件的签署已经达成合意且同意使用电子签名的方式完成该文件的签署，<span
                    class=GramE>并且您</span>认可签署过程中产生的电子数据。</span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US><o:p>&nbsp;</o:p></span></b></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.7</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户理解并确认：深圳市<span class=GramE>快移网络</span>科技控股有限公司仅提供相关的网络服务。除此之外与相关网络服务有关的设备</span><span
                lang=EN-US>(</span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>如电脑、调制解调器及其他与接入互联网有关的装置</span><span
                lang=EN-US>)</span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>及所需的费用</span><span
                lang=EN-US>(</span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>如为接入互联网而支付的电话费及上网费</span><span
                lang=EN-US>)</span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>均应由用户自行负担，用户应使用正版软件接受网络服务。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.8</span></b><span
                class=GramE><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>快移平台</span></span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>现阶段提供免费服务，后续如收取相关费用，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司将在平台上发布相关规定并予以公示。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>3.9</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户在使用快移平台的交易过程中发生纠纷，交易双方应友好协商解决。如任何一方将交易纠纷<span
                    class=GramE>提交快移平台</span>要求调解处理，则深圳市<span class=GramE>快移网络</span>科技控股有限公司作为<span
                    class=GramE>独立第三</span>方，有权根据交易规则、交易惯例单方判断做出调解处理决定，并向相关权利人提供相关的用户信息。用户了解并应同意并接受深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司的判断和决定，同意接受深圳市<span class=GramE>快移网络</span>科技控股有限公司因此采取的任何措施并不得因任何原因追究深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司的责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>使用规则</span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户在<span class=GramE>使用快移平台</span>过程中，应遵守中国有关的法律和法规以及《快移平台规则》，并且必须遵循以下规定：</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>1</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>遵守国家法律、法规等规范性文件<span class=GramE>及快移平台</span>各项规则的规定和要求，不违背社会公共利益或公共道德，不侵犯他人的合法权益，<span
                    class=GramE>不</span>偷逃应缴税费，不违反本协议及相关规则；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>2</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得传输或发表煽动抗拒、破坏宪法和法律、行政法规实施的言论，煽动颠覆国家政权，推翻社会主义制度的言论，煽动分裂国家、破坏国家统一的言论，煽动民族仇恨、民族歧视、破坏民族团结的言论；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>3</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得利用本平台站从事洗钱、窃取商业秘密、窃取个人信息等违法犯罪活动；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>4</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得冒用或盗用他人身份信息或者干扰他人使用本平台服务，不得为任何非法目的而使用本平台；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>5</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得<span class=GramE>利用快移平台</span>进行任何可能对互联网交易的正常运转造成不利影响的行为；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>6</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得利用“快移平台”发布虚假、失效、欺诈性交易信息或<span
                    class=GramE>利用快移平台</span>进行非法经营活动；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>7</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得<span class=GramE>利用快移平台</span>传输、发布任何骚扰性的、中伤他人的、辱骂性的、恐吓性的、庸俗淫秽的或其他任何非法的信息资料；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>8</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不以虚构或歪曲事实的方式不当评价其他会员，不采取不正当方式制造或提高自身的信用度；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>9</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得利用对“快移平台”上的任何数据进行作商业性活动利用，包括但不限于不得在未经深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司事先书面同意的情况下，以复制、转发等任何方式使用“快移平台”上展示的内容及形式展示的形式；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>10</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>不得利用任何非法手段获取其他用户个人信息，不得将其他用户信息用于任何营利或非营利目的，不得泄露其他用户或权利人的个人隐私；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>11</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>就深圳市<span class=GramE>快移网络</span>科技控股有限公司及合作商业伙伴的服务、产品、业务咨询应采取深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司书面允许的沟通渠道，不得在公众场合发布有关深圳市<span class=GramE>快移网络</span>科技控股有限公司及相关服务的负面宣传；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>12</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>如发现任何非法使用用户账号或账号出现安全漏洞的情况，应立即以书面形式通告深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>13</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>其他法律法规、本协议、“快移平台”各项规则和要求禁止从事的行为。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户违反上述规定，因此产生的任何法律后果，用户应独立承担所有相应的法律责任。如造成“快移平台”、深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司产生任何损失或增加费用，深圳市<span class=GramE>快移网络</span>科技控股有限公司将有权请求该用户赔偿进行追偿。同时，用户同意深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司将有权采取以下措施，维护交易秩序和交易安全：</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>1</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>关闭涉嫌恶意交易、欺诈交易、虚假交易的相应交易运单；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>2</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>删除涉嫌违反法律法规规定、本协议或“快移平台”其他规则的信息；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>3</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户信用降级、考核不合格；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>4</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>公示用户涉嫌违法、违约行为并公布“快移平台”采取的相应措施；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>5</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>中止、终止提供部分或全部服务；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>6</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>向司法机关、工商行政管理部门等国家机关举报并提供相关的用户信息；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>7</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>其他法律法规允许或“快移平台”交易规则规定的处理措施。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意采取以上措施深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司均无需就采取上述措施与用户确认核对或是征得用户的同意，且无需就采取以上措施向用户承担任何责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4.3</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司保留在中华人民共和国法律法规允许的范围内独自决定拒绝服务、关闭用户账户的权利，且无需事先通知用户。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4.4</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>对于用户因使用任何不正确或不合法的连线方式导致的任何损失、支出、费用、罚金，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司不承担任何责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>4.5</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>如用户涉嫌违反有关法律、本协议或“快移平台”其他规则之规定，使深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司遭受任何损失，或受到任何第三方的索赔，或受到任何行政管理部门的处罚，该用户应当赔偿深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司因此造成的损失和</span><span lang=EN-US>/</span><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>或发生的费用，包括但不限于合理的律师费用、诉讼费、差旅费、公证费、调查取证费用等。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.</span></b><span
                lang=EN-US> </span><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>信息披露与审核制度</span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.1</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意并确认，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权永久免费地使用用户于展示于“快移平台上提供、展示”的各类信息，包括但不限于用户提供的注册资料、数据信息、交易信息及道路货运公共监管与服务平台数据等，并有权基于以上信息和资料制作其他产品或将其作为其他产品的一部分予以使用。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.2</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意并确认，若用户选择向本站其他用户购买或提供服务、产品的，则视为用户同意向交易对方披露其用户信息、货源信息、定位信息、车辆信息等各类与交易相关的信息。如以上信息涉及到交易履行的第三方，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权将用户信息以必要的方式向第三方披露。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.3</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意并确认，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司通过“快移平台”，或以、邮件、短信、微信、网站通知或声明等形式向用户发送各类交易信息、宣传信息、促销活动、售后服务、客户服务等信息，如用户不希望接收上述信息，可选择退订。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.4 </span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户同意并确认，深圳市<span class=GramE>快移网络</span>科技控股有限公司<span
                    class=GramE>有权依应国家机关</span>的要求，向其提供用户信息及交易记录等信息。若如深圳市<span class=GramE>快移网络</span>科技控股有限公司初步判断，用户存在涉嫌侵犯他人合法权益，深深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司亦有权向权利人提供必要的用户信息。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.5</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户同意并确认，深圳市<span class=GramE>快移网络</span>科技控股有限公司有权在必要或紧急情况下登陆用户的注册账户查看相关信息进行证据保全，包括但不限于公证、见证、协助司法机关调查取证等。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>5.6</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司有权对用户提供的资料进行审查，如有合理理由怀疑用户提供的资料不准确、不完整，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权要求用户提供相关的证明资料、予以改正或直接做出删除相应资料的处理，并有权直至中止、终止对用户提供部分或全部服务。深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司对此不承担任何责任，用户自愿承担因此产生的任何直接或间接损失及不利后果。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>6. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>所有权及知识产权条款</span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>6.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>“快移平台”上所提供或展示中的文字、软件、声音、图片、视频、录像、图表、数据等全部所有信息、软件和素材的知识产权均属于深圳前海广大集团有限公司所有，受著作版权法、商标法和其它财产所有权相关法律的保护。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>6.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>除法律另有强制性规定外，未经深圳市<span class=GramE>快移网络</span>科技控股有限公司书面许可</span><span
                lang=EN-US>,</span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>任何单位或个人不得以任何方式非法地全部或部分复制、篡改、转发、盗用、链接或以其他方式使用“快移平台”的任何信息内容，否则，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权追究其法律责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>7. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>交易安全保障与数据安全保障</span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>7.1</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司将通过建立专业的安全团队，使用前沿的安全技术，建设严密的防护体系，保障交易过程及交易数据的安全。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>7.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司会采取不断更新的技术措施，努力保护用户的<span
                    class=GramE>帐号</span>及交易数据在服务器端的安全。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>7.3</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户需要采取特定措施保护自己的<span
                    class=GramE>帐号</span>安全，包括但不限于妥善保管<span class=GramE>帐号</span>与密码、安装防病毒木马软件、定期更改密码等措施。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>7.4</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司拥有同城和<span class=GramE>异地灾备机房</span>，保证业务连续性，配合实时及定期双备份保证用户数据的存储安全。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>8. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>责任限制</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>8.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>“快移平台”上的信息均由用户自行发布。“快移平台”仅提供用户信息交换达成交易的场所。用户对其在本平台发布的信息承担全部法律责任。用户应自行判断平台上信息的真实性、准确性、有效性及交易各方的履约能力、交易标的<span
                    class=GramE>的</span>合法性等交易达成的各项要素，并承担全部交易风险及损失。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>8.2</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户理解并同意，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司及其授权第三方对交易争议的调解处理并非司法机构的裁决、判决，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司及其授权第三方仅能根据交易规则、交易惯例以普通人的身份对证据进行辨别<span
                    class=GramE>作出</span>决定，用户自愿同意接受深圳市<span class=GramE>快移网络</span>科技控股有限公司的调处决定，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司不对调处调解处理结果承担任何责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>8.3</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>由于信息网络正常的设备维护，信息网络连接故障，电脑、通讯、黑客、病毒或其他系统的故障，电力故障，罢工，暴乱，火灾，洪水，战争，政府行为，司法行政机关的命令等不可抗力行为或第三方的不作为而造成的不能服务或延迟服务，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司不承担责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>8.4 </span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>因第三方未经批准使用用户的账户、用户个人信息被第三方窃取或用户自身终端遭受黑客攻击、病毒等原因造成的损失由用户自行承担。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>9. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>个人信息和商业秘密的收集与保护</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>9.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司将对用户隐私信息、“快移平台”中的各类商业信息采用技术手段进行合法保护。未经权利所有方同意任何第三方不得在平台上采用包括但不限于盗取、复制、披露、转发等手段进行违法活动，一经查实，将提交司法机关处理。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>9.2</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司可能会与第三方合作向用户提供相关的网络服务，在此情况下，如该第三方同意承担与深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司同等的保护用户隐私的责任，则用户同意授权深圳市<span class=GramE>快移网络</span>科技控股有限公司可将用户的注册资料等提供给该第三方。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>9.3</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>在不透露单个用户隐私资料的前提下，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权对整个用户数据库进行技术分析并对已进行分析、整理后的用户数据库进行商业上的利用。尽管深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司对用户的隐私权保护做了极大的努力，但是仍然不能保证现有的安全技术措施使用户的技术信息等不受任何形式的损失。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>10. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>协议终止</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>10.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>深圳市<span class=GramE>快移网络</span>科技控股有限公司保留提前通知用户并单方终止向用户提供部分或全部网络服务的权利，对于所有服务的终止而造成的任何损失，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司无需对用户或任何第三方承担任何责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>10.2</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>出现以下情形时，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司有权直接注销用户账户，并终止本协议：</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>1</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>用户提供信息存在虚假或欺诈内容；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>2</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>本协议内容或交易规则等变更时，用户明确通知深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司不愿接受新的服务协议；</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span
                    style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>（</span><span lang=EN-US>3</span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>）</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>其他本协议约定或深圳市<span class=GramE>快移网络</span>科技控股有限公司认为应当终止协议的情况。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>10.3</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意，本协议终止后，深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司仍有权继续保存并使用用户的各项信息。在服务终止之前已产生的交易行为，由用户自行处理并承担全部责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>11. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>违约赔偿</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>11.1</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>用户同意保障和维护深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司及其他用户的利益，如因用户违反有关法律、法规或本协议项下的任何条款而给深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司或任何<span class=GramE>其他第三</span>人造成损失，用户同意承担由此造成的损害赔偿责任。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>12. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>法律管辖</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>12.1</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>本协议的订立、执行和解释及争议的解决均应适用中国法律。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>12.2</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>如双方就本协议内容或其执行发生任何争议，双方应尽量友好协商解决；协商不成时，任何一方均应向深圳市<span
                    class=GramE>快移网络</span>科技控股有限公司所在地的人民法院提起诉讼。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><span lang=EN-US><span
                    style='mso-spacerun:yes'>&nbsp;</span></span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>13. </span></b><b
                style='mso-bidi-font-weight:normal'><span style='font-family:宋体;mso-ascii-font-family:
Calibri;mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>其他规定</span><span
                    lang=EN-US><o:p></o:p></span></b></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>13.1</span></b><span
                style='font-family:宋体;mso-ascii-font-family:Calibri;mso-ascii-theme-font:minor-latin;
mso-fareast-font-family:宋体;mso-fareast-theme-font:minor-fareast;mso-hansi-font-family:
Calibri;mso-hansi-theme-font:minor-latin'>本服务协议内容包括协议正文、法律声明、“快移平台”交易规则及所有服务平台已经发布或将来发布的各项规则、公告或通知。所有规则为本协议不可分割的一部分，与本协议具有同等法律效力。</span></p>

        <p class=MsoNormal><span lang=EN-US><o:p>&nbsp;</o:p></span></p>

        <p class=MsoNormal><b style='mso-bidi-font-weight:normal'><span lang=EN-US>13.2</span></b><span
                lang=EN-US> </span><span style='font-family:宋体;mso-ascii-font-family:Calibri;
mso-ascii-theme-font:minor-latin;mso-fareast-font-family:宋体;mso-fareast-theme-font:
minor-fareast;mso-hansi-font-family:Calibri;mso-hansi-theme-font:minor-latin'>如<span
                    class=GramE>本服务</span>协议中的任何条款因何种原因完全或部分无效或不具有执行力，本协议的其余条款仍应有<span class=GramE>效</span>并且有约束力。</span></p>

	</div>

    <div class="container-fluid" style="margin-bottom: 15px;">
        <div class="row">
            <div class="col-md-4 col-md-offset-5">
                <button type="button" class="btn btn-warning" id="checkServiceContractBtn"><?php echo $this->translate('check_service_contract'); ?></button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $("#checkServiceContractBtn").click(function () {
        $("#isReadServiceContract").val('true');
        $("#serviceContract").prop('checked', true);
        layer.close(layer.index);
    });
</script>
