<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
function deleteAll(){
	var ids="";
    $("[name='chose[]'][checked]").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->baseUrl();?>/wechatnotetpl/delete/nt_ids/"+ids;
}
</script>
<h1>微信通知模板管理</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加模板" onclick="document.location='<?php echo $this->baseUrl();?>/wechatnotetpl/add'"/>
  </p>
</div>
<table class="admin_list">
  <tr>
    <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
      <label for="checkAll">全选</label></th>
    <th>名称</th>
    <th>标题</th>
    <th>激活</th>
    <th>固定号码</th>
    <th>模板内容</th>
    <th>操作</th>
  </tr>
  <?php if (is_array($this->tpls)) :?>
  <?php foreach ($this->tpls as $tpl) :?>
  <tr>
    <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($tpl['nt_id'])?>" class="ids_all"></td>
    <td><?php echo ($tpl['nt_name']);?></td>
    <td><?php echo ($tpl['nt_desc']);?></td>
    <td><?php echo ($tpl['is_actived']=='1')?'<img src="/images/center/yes.gif">':'<img src=/images/center/no.gif>';?></td>
    <td><?php echo ($tpl['send_to']);?></td>
    <td><?php echo ($tpl['nt_data']);?></td>
    <td>
    <a href="<?php echo $this->baseUrl();?>/wechatnotetpl/update/nt_id/<?php echo ($tpl['nt_id']);?>"><img src="/images/center/edit.gif" title="编辑" alt="编辑"></a>
    <a href="<?php echo $this->baseUrl();?>/wechatnotetpl/delete/nt_ids/<?php echo ($tpl['nt_id']);?>"><img src="/images/center/del.gif" title="删除" alt="删除"/></a>
    </td>
  </tr>
  <?php endforeach;?>
  <?php endif;?>
</table>
<div class="batch">
  <input class="admin_bnt2"   type="button" name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
  &nbsp; </div>
<?php echo $this->render("footer.phtml") ?>
