<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/wechatnotetpl/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1>修改微信通知模板</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_form">
    <tr>
      <td><strong>官方模板id：</strong>
        <p>
          <input name="tpl_id" id="tpl_id" value="<?php echo ($this->tpl['tpl_id']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>模板英文名称：</strong>
        <p>
          <input name="nt_name" id="nt_name" value="<?php echo ($this->tpl['nt_name']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>模板标题：</strong>
        <p>
          <input name="nt_desc" id="nt_desc" value="<?php echo ($this->tpl['nt_desc']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
   <tr>
      <td><strong>微信发送至(固定号码填写 openId)：</strong>
        <p>
          <input name="send_to" id="send_to" value="<?php echo ($this->tpl['send_to']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>模板内容：</strong>
        <p>
          <textarea style="height:100px;" name="nt_data" id="nt_data" class="textarea"><?php echo ($this->tpl['nt_data']);?></textarea>
        </p></td>
    </tr>
    <tr>
      <td><strong>是否激活：</strong>
        <p>
          <input type="radio" name="is_actived" id="is_actived0" value="0" style="width:15px;" <?php echo ($this->tpl['is_actived']=='0')?"checked":""; ?>>
          否&nbsp;
          <input type="radio" name="is_actived" id="is_actived1" value="1" style="width:15px;" <?php echo ($this->tpl['is_actived']=='1')?"checked":""; ?>>
          是 </p></td>
    </tr>
  </table>
  <table class="admin_form">
    <tr>
      <td>
        <input name="nt_id" id="nt_id" type="hidden" value="<?php echo $this->tpl['nt_id']?>" />
        <input class="admin_bnt" name="" type="submit" value="提交"/></td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>
