<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="/user/transport"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoanApply'); ?></li>
        </ol>

        <?php if (!empty($this->resultMsg)): ?>
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <p><?php echo base64_decode($this->resultMsg); ?></p>
            </div>
        <?php endif; ?>

        <div id="financingLoanAlert" class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p>未选择运单或可用融资额度低于申请的融资金额，请重新选择运单！</p>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <form class="form-horizontal" action="javascript:void(0)">
                    <div class="form-group" style="margin-top: 10px;">
                        <label for="customerID" class="col-sm-1 control-label"><?php echo $this->translate('债务方'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="customerID" id="customerID">
                                <?php foreach ($this->dataDictList['TRANSPORT_ACCOUNT_LIST'] as $key => $dataDict): ?>
                                    <?php if ($key == 0): ?>
                                        <option value="<?php echo $dataDict['code']; ?>" selected="selected"><?php echo $dataDict['name']; ?></option>
                                    <?php else: ?>
                                        <option value="<?php echo $dataDict['code']; ?>"><?php echo $dataDict['name']; ?></option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group" style="margin-top: 10px;">
                        <label for="startSignDate" class="col-sm-1 control-label"><?php echo $this->translate('开始日期'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control layDateUI" name="startSignDate" id="startSignDate">
                        </div>

                        <label for="endSignDate" class="col-sm-1 control-label"><?php echo $this->translate('结束日期'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control layDateUI" name="endSignDate" id="endSignDate">
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="margin-bottom: 50px"></div>
        </div>
    </div>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <form class="form-horizontal" action="/user/financing/add-financing-loan" onsubmit="return addFinancing();" id="addFinancing_form" method="post">
            <input type="hidden" name="loanRatio" id="loanRatio" value="<?php echo $this->creditRating['instance']['evaluationLevel']['loanRatio']; ?>">
            <div class="form-group" style="margin-top: 10px;">
                <label for="creditBal" class="col-sm-3 control-label"><?php echo $this->translate('融资余额'); ?></label>
                <div class="col-sm-2">
                    <p class="form-control-static"><span id="creditBal_static">0</span> 元</p>
                </div>

                <label for="receivableAmount" class="col-sm-1 control-label"><?php echo $this->translate('运单金额'); ?></label>
                <div class="col-sm-2">
                    <p class="form-control-static"><span id="receivableAmount_static">0</span> 元</p>
                    <input type="hidden" name="receivableAmount" id="receivableAmount" value="0">
                </div>

                <label for="loanAmount" class="col-sm-1 control-label"><?php echo $this->translate('融资金额'); ?></label>
                <div class="col-sm-2">
                    <p class="form-control-static"><span id="loanAmount_static">0</span> 元</p>
                    <input type="hidden" name="loanAmount" id="loanAmount" value="0">
                </div>

                <button type="submit" class="btn btn-primary" id="addFinancingLoanBtn"><?php echo $this->translate('提交申请'); ?></button>
            </div>
        </form>
    </div>
</nav>


<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        listActivatedFinancing = {},
        userLangCode = '<?php echo $this->userLangCode; ?>',
        $resultListTable = $('#resultListTable'),
        signDateTime = $("#startSignDate").val(),
        endSignDate = $("#endSignDate").val(),
        layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>',
        creditBal = 0;

    if (!signDateTime || signDateTime === '') {
        signDateTime = new Date().format("yyyy-MM-dd")
    }
    if (!endSignDate || endSignDate === '') {
        endSignDate = new Date().format("yyyy-MM-dd")
    }

    $().ready(function() {

    });

    $(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // $("#financingLoanAlert").alert('close');

        // 初始化日期控件, 绑定多个
        layui.use('laydate', function() {
            let laydate = layui.laydate;
        });

        initListTable();

        $('#customerID').on('changed.bs.select', function () {
            let customerID = $("#customerID").val();
            $resultListTable.bootstrapTable('refresh', {
                query: {
                    customerID: customerID,
                    startSignDate: $("#startSignDate").val(),
                    endSignDate: $("#endSignDate").val()
                }
            });
        });
    });

    function initListTable() {
        $.ajax({
            type: "POST",
            url: '/user/transport/list-activated-financing-ajax',
            data: {
                debtor: $("#customerID").val()
            },
            dataType: "json",
            success: function (data) {
                listActivatedFinancing = data;

                let nowDate = new Date(),
                    earliestDate = new Date(),
                    lastDay = new Date();

                if (listActivatedFinancing && listActivatedFinancing.length > 0) {
                    let earliestBillDate = listActivatedFinancing[0].earliestBillDate;
                    earliestDate = new Date(earliestBillDate);
                    lastDay = new Date(earliestDate.year, earliestDate.month, 0);
                    // 可用额度
                    creditBal = listActivatedFinancing[0].creditBal;
                    if (creditBal) {
                        $("#creditBal_static").html(formatCurrency(creditBal, 2));
                    }
                }

                layui.use('laydate', function() {
                    let laydate = layui.laydate;
                    let startLaydate = laydate.render({
                        elem: '#startSignDate'
                        ,value: nowDate.format("yyyy-MM-dd")
                        ,min: earliestDate.format("yyyy-MM-dd")
                        ,max: nowDate.format("yyyy-MM-dd")
                        ,done: function(value, date, endDate){
                            let endDateValue = $("#endSignDate").val();
                            lastDay = new Date(date.year, date.month, 0);
                            if (lastDay.getTime() > nowDate.getTime()) {
                                lastDay = nowDate;
                            }

                            if (new Date(endDateValue).getTime() < new Date(value).getTime() || new Date(endDateValue).getTime() > lastDay.getTime()) {
                                endDateValue = lastDay.format("yyyy-MM-dd");
                            }

                            laydate.render({
                                elem: '#endSignDate'
                                ,value: endDateValue
                                ,min: value
                                ,max: lastDay.format("yyyy-MM-dd")
                                ,done: function(value, date, endDate){
                                    $resultListTable.bootstrapTable('refresh', {
                                        query: {
                                            customerID: $("#customerID").val(),
                                            startSignDate: $("#startSignDate").val(),
                                            endSignDate: value
                                        }
                                    });
                                }
                            });

                            $resultListTable.bootstrapTable('refresh', {
                                query: {
                                    customerID: $("#customerID").val(),
                                    startSignDate: value,
                                    endSignDate: endDateValue
                                }
                            });
                        }
                    });

                    let endLaydate = laydate.render({
                        elem: '#endSignDate'
                        ,value: nowDate.format("yyyy-MM-dd")
                        ,min: new Date($("#startSignDate").val()).format("yyyy-MM-dd")
                        ,max: nowDate.format("yyyy-MM-dd")
                        ,done: function(value, date, endDate){
                            $resultListTable.bootstrapTable('refresh', {
                                query: {
                                    customerID: $("#customerID").val(),
                                    startSignDate: $("#startSignDate").val(),
                                    endSignDate: value
                                }
                            });
                        }
                    });
                });

                $resultListTable.bootstrapTable({
                    classes: 'table table-no-bordered',
                    checkboxHeader: true,
                    method: 'POST',
                    clickToSelect: true,
                    // 对a和button标签忽略clickToSelect事件
                    ignoreClickToSelectOn: function (element) {
                        return $.inArray(element.tagName, ['A', 'BUTTON']);
                    },
                    url: '/user/transport/apply-list-ajax',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    queryParams: function(params) {
                        return {
                            customerID: $("#customerID").val(),
                            startSignDate: signDateTime,
                            endSignDate: endSignDate
                        };
                    },
                    onLoadSuccess: function() {
                        $resultListTable.bootstrapTable('checkAll');

                        refreshTotal($resultListTable);
                    },
                    onCheck: function() {
                        refreshTotal($resultListTable);
                    },
                    onUncheck:function(){
                        refreshTotal($resultListTable);
                    },
                    onCheckAll: function () {
                        refreshTotal($resultListTable);
                    },
                    onUncheckAll: function () {
                        refreshTotal($resultListTable);
                    },
                    onClickRow:function(row, $element, field) {
                        // alert(JSON.stringify(row));
                    },
                    columns: [{
                        halign: 'center',
                        checkbox: true
                    }, {
                        field: 'transOrderRefCode',
                        title: '<?php echo $this->translate("运单编号"); ?>',
                        width: 260,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            return value;
                        }
                    }, {
                        field: 'orderAmount',
                        title: '<?php echo $this->translate("运单金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        width: 160,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return ' ' + formatCurrency(value, 2);
                        }
                    }, {
                        field: 'carrierName',
                        title: '<?php echo $this->translate("承运方"); ?>',
                        valign: 'middle',
                        width: 300,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return value;
                        }
                    }, {
                        field: 'departureName',
                        title: '<?php echo $this->translate("始发地/目的地"); ?>',
                        valign: 'middle',
                        // width: 160,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return value;
                        }
                    }]
                });
            }
        });
    }

    function refreshTotal($resultListTable) {
        $("#financingLoanAlert").alert('close');
        let $allSelectionsData = $resultListTable.bootstrapTable('getAllSelections'),
            allSelectionsTotal = 0,
            $loanAmount = $("#loanAmount"),
            loanRatio = $("#loanRatio").val();

        $.each($allSelectionsData, function(i, val) { //两个参数，第一个参数表示遍历的数组的下标，第二个参数表示下标对应的值
            allSelectionsTotal += val.orderAmount;
        });

        $("#receivableAmount_static").html(formatCurrency(allSelectionsTotal, 2));
        $("#receivableAmount").val(allSelectionsTotal);

        $("#loanAmount_static").html(formatCurrency(allSelectionsTotal * loanRatio, 2));
        $loanAmount.val(allSelectionsTotal * loanRatio);
        if ($loanAmount.val() <= 0 || $loanAmount.val() > creditBal) {
            $("#addFinancingLoanBtn").attr("disabled","disabled");
        } else {
            $("#addFinancingLoanBtn").removeAttr("disabled");
        }
    }

    function addFinancing() {
        if (listActivatedFinancing && listActivatedFinancing.length > 0) {
            let loanAmount = $("#loanAmount").val();
            if (loanAmount <= 0 || loanAmount > creditBal) {
                $("#financingLoanAlert").alert();
                $("#addFinancingLoanBtn").attr("disabled","disabled");
                return false;
            } else {
                $("#addFinancingLoanBtn").removeAttr("disabled");
                let $addFinancing_form = $("#addFinancing_form"),
                    activatedFinancing = listActivatedFinancing[0],
                    receivableAmount = $("#receivableAmount").val(),
                    applyLoanDateStr = new Date(),
                    chooseDate = new Date($("#startSignDate").val()),
                    applyExpiryDate = new Date(chooseDate.getFullYear(), parseInt(chooseDate.getMonth() + parseInt(listActivatedFinancing[0].settlementPeriod / 30)), listActivatedFinancing[0].settlementDays);

                $addFinancing_form.append($("<input type='hidden' name='financingID' value='" + activatedFinancing.financingID + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='applyLoanDate' value='" + applyLoanDateStr.format("yyyy-MM-dd") + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='applyExpiryDate' value='" + applyExpiryDate.format("yyyy-MM-dd") + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='receivableAmount' value='" + receivableAmount + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='assignmentAmount' value='" + receivableAmount + "' />"));
                // $addFinancing_form.append($("<input type='hidden' name='loanAmount' value='" + receivableAmount * 0.63 + "' />"));

                let resultSelections = $resultListTable.bootstrapTable('getSelections');
                $.each(resultSelections, function(i, transportOrder) {
                    // console.log(i);
                    $addFinancing_form.append($("<input type='hidden' name='objBizType[]' value='TT' />"));
                    $addFinancing_form.append($("<input type='hidden' name='objBizID[]' value='" + transportOrder.transportOrderID + "' />"));
                    $addFinancing_form.append($("<input type='hidden' name='objBizNo[]' value='" + transportOrder.transOrderCode + "' />"));
                    let summary = transportOrder.agencyName + "|" + transportOrder.customerName + "|" + transportOrder.goodsDesc + "|" + transportOrder.carrierName + "|";
                    let transporterStr = '';
                    $.each(transportOrder.transporterList, function(i, transporter) {
                        if (i > 0) {
                            transporterStr += ";";
                        }
                        transporterStr += transporter.vehicleNo + " " + transporter.dirverName + " " + transporter.mobile;
                    });
                    $addFinancing_form.append($("<input type='hidden' name='summary[]' value='" + summary + transporterStr + "' />"));
                    $addFinancing_form.append($("<input type='hidden' name='crnCode[]' value='" + transportOrder.crnCode + "' />"));
                    $addFinancing_form.append($("<input type='hidden' name='totalAmount[]' value='" + transportOrder.orderAmount + "' />"));
                    $addFinancing_form.append($("<input type='hidden' name='billDate[]' value='" + transportOrder.takeDeliveryTime + "' />"));
                });
                return true;
            }
        } else {
            return false;
        }
    }
</script>
</body>
</html>
