<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoanApply'); ?></li>
        </ol>

        <?php if (!empty($this->resultMsg)): ?>
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <p><?php echo base64_decode($this->resultMsg); ?></p>
            </div>
        <?php endif; ?>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12" style="margin-bottom: 50px"></div>
        </div>
	</div>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <form class="form-horizontal" action="/user/financing/add-financing-item" onsubmit="return addFinancing();" id="addFinancing_form" method="post">
            <div class="form-group" style="margin-top: 10px;">
                <label for="customerID" class="col-sm-1 control-label"><?php echo $this->translate('订单类型'); ?></label>
                <div class="col-sm-4">
                    <select class="selectpicker form-control" name="customerID" id="customerID">
                        <?php echo $this->ShowDictionaryList($this->dic_Setting['TRANSPORT_ACCOUNT_LIST'], $this->userLangCode, $this->dic_Setting['TRANSPORT_ACCOUNT_LIST'], ''); ?>
                    </select>
                </div>

                <label class="sr-only" for="signDateTime">signDateTime</label>
                <div class="col-sm-2">
                    <select class="selectpicker form-control" name="signDateTime" id="signDateTime">
                        <?php for ($i = 0; $i <= 9; $i++): ?>
                        <option><?php echo date('Y-m-d', strtotime("-$i day")); ?></option>
                        <?php endfor; ?>
                    </select>
                </div>

                <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('合计'); ?></label>
                <div class="col-sm-3">
                    <p class="form-control-static"><span id="receivableAmount_static">0</span> 元</p>
                    <input type="hidden" name="receivableAmount" id="receivableAmount" value="0">
                </div>

                <button type="submit" class="btn btn-primary"><?php echo $this->translate('提交申请'); ?></button>
            </div>
        </form>
    </div>
</nav>


<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        listActivatedFinancing = {},
        userLangCode = '<?php echo $this->userLangCode; ?>',
        $resultListTable = $('#resultListTable');

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        let layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            let laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        $resultListTable.bootstrapTable({
            classes: 'table table-no-bordered',
            checkboxHeader: true,
            method: 'POST',
            clickToSelect: true,
            // 对a和button标签忽略clickToSelect事件
            ignoreClickToSelectOn: function (element) {
                return $.inArray(element.tagName, ['A', 'BUTTON']);
            },
            url: '/user/transport/apply-list-ajax',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            queryParams: function(params) {
                return {
                    customerID: $("#customerID").val(),
                    signDateTime: $("#signDateTime").val()
                };
            },
            onLoadSuccess: function() {
                $resultListTable.bootstrapTable('checkAll');
                $.ajax({
                    type: "POST",
                    url: '/user/transport/list-activated-financing-ajax',
                    data: {
                        debtor: $("#customerID").val()
                    },
                    dataType: "json",
                    success: function (data) {
                        listActivatedFinancing = data;
                    }
                });
                refreshTotal($resultListTable);
            },
            onCheck: function() {
                refreshTotal($resultListTable);
            },
            onUncheck:function(){
                refreshTotal($resultListTable);
            },
            onCheckAll: function () {
                refreshTotal($resultListTable);
            },
            onUncheckAll: function () {
                refreshTotal($resultListTable);
            },
            onClickRow:function(row, $element, field) {
                // alert(JSON.stringify(row));
            },
            columns: [{
                halign: 'center',
                checkbox: true
            }, {
                field: 'transOrderRefCode',
                title: '<?php echo $this->translate("运单编号"); ?>',
                width: 260,
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "";
                    }
                    return value;
                }
            }, {
                field: 'orderAmount',
                title: '<?php echo $this->translate("运单金额"); ?>',
                align: 'right',
                halign: 'center',
                valign: 'middle',
                width: 160,
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }
                    return ' ' + formatCurrency(value, 2);
                }
            }, {
                field: 'oppCustomerName',
                title: '<?php echo $this->translate("承运方"); ?>',
                valign: 'middle',
                width: 300,
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }

                    return value;
                }
            }, {
                field: 'departureName',
                title: '<?php echo $this->translate("始发地/目的地"); ?>',
                valign: 'middle',
                // width: 160,
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }
                    return value;
                }
            }]
        });

        $('#customerID').on('changed.bs.select', function () {
            let customerID = $("#customerID").val();
            $resultListTable.bootstrapTable('refresh', {
                query: {
                    customerID: customerID,
                    signDateTime: $("#signDateTime").val()
                }
            });

            $.ajax({
                type: "POST",
                url: '/user/transport/list-activated-financing-ajax',
                data: {
                    debtor: customerID
                },
                dataType: "json",
                success: function (data) {
                    listActivatedFinancing = data;
                }
            });

            refreshTotal($resultListTable);
        });

        $('#signDateTime').on('changed.bs.select', function () {
            $resultListTable.bootstrapTable('refresh', {
                query: {
                    customerID: $("#customerID").val(),
                    signDateTime: $("#signDateTime").val()
                }
            });

            refreshTotal($resultListTable);
        });
    });

	function refreshTotal($resultListTable) {
        let $allSelectionsData = $resultListTable.bootstrapTable('getAllSelections'),
            allSelectionsTotal = 0;

        $.each($allSelectionsData, function(i, val) { //两个参数，第一个参数表示遍历的数组的下标，第二个参数表示下标对应的值
            allSelectionsTotal += val.orderAmount;
        });

        $("#receivableAmount_static").html(formatCurrency(allSelectionsTotal, 2));
        $("#receivableAmount").val(allSelectionsTotal);
    }

    function addFinancing() {
        if (listActivatedFinancing && listActivatedFinancing.length > 0) {
            let $addFinancing_form = $("#addFinancing_form"),
                activatedFinancing = listActivatedFinancing[0],
                receivableAmount = $("#receivableAmount").val();

            $addFinancing_form.append($("<input type='hidden' name='financingID' value='" + activatedFinancing.financingID + "' />"));
            $addFinancing_form.append($("<input type='hidden' name='loanDate' value='2020-4-1' />"));
            $addFinancing_form.append($("<input type='hidden' name='expiryDate' value='2020-5-20' />"));
            $addFinancing_form.append($("<input type='hidden' name='assignmentAmount' value='" + receivableAmount + "' />"));
            $addFinancing_form.append($("<input type='hidden' name='financingAmount' value='" + receivableAmount * 0.63 + "' />"));

            let resultSelections = $resultListTable.bootstrapTable('getSelections');
            $.each(resultSelections, function(i, transportOrder) {
                console.log(i);
                $addFinancing_form.append($("<input type='hidden' name='objBizType[]' value='TT' />"));
                $addFinancing_form.append($("<input type='hidden' name='objBizID[]' value='" + transportOrder.transportOrderID + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='objBizNo[]' value='" + transportOrder.transportOrderCode + "' />"));
                let summary = transportOrder.agencyName + "|" + transportOrder.customerName + "|" + transportOrder.goodsDesc + "|" + transportOrder.carrierName + "|";
                let transporterStr = '';
                $.each(transportOrder.transporterList, function(i, transporter) {
                    if (i > 0) {
                        transporterStr += ";";
                    }
                    transporterStr += transporter.vehicleNo + " " + transporter.dirverName + " " + transporter.mobile;
                });
                $addFinancing_form.append($("<input type='hidden' name='summary[]' value='" + summary + transporterStr + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='crnCode[]' value='" + transportOrder.crnCode + "' />"));
                $addFinancing_form.append($("<input type='hidden' name='totalAmount[]' value='" + transportOrder.orderAmount + "' />"));
            });
            return true;
        } else {
            return false;
        }
    }
</script>
</body>
</html>
