<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightList'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="page-header">
                    <h3><?php echo $this->translate('订单列表'); ?><a href="/user/transport/apply" class="btn btn-success pull-right">生成金融方案</a></h3>
                </div>

                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <div class="form-group">
                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('订单编号'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('订单编号'); ?>" >
                        </div>

                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('商品名称'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="proName" id="proName" placeholder="<?php echo $this->translate('商品名称'); ?>" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="paymentStatus" class="col-sm-1 control-label"><?php echo $this->translate('订单类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="paymentStatus" id="paymentStatus" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_STATUS'], $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->paymentStatus); ?>
                            </select>
                        </div>

                        <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('时间'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control layDateUI" name="startDate" id="startDate">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="crnCode" class="col-sm-1 control-label"><?php echo $this->translate('配送方式'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="crnCode" id="crnCode" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>

                        <label for="proType" class="col-sm-1 control-label"><?php echo $this->translate('产品类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="proType" id="proType" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        let layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            let laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        let dataDictQuery = '/user/common/dict-ajax';
        let dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/transport/transport-order-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    // checkboxHeader: false,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            startDate: $("#startDate").val(),
                            endDate: $("#endDate").val(),
                            crnCode: $("#crnCode").val(),
                            lowerAmount: $("#lowerAmount").val(),
                            upperAmount: $("#upperAmount").val(),
                            tradingType: $("#tradingType").val(),
                            transNo: $("#transNo").val(),
                            paymentStatus: $("#paymentStatus").val()
                        };
                    },
                    columns: [{
                        field: 'transOrderRefCode',
                        title: '<?php echo $this->translate("订单编号/商品"); ?>',
                        valign: 'middle',
                        width: 280,
                        formatter: function (value, row) {
                            let base = new Base64(),
                                resultEnCode = base.encode(row.transportOrderID),
                                href = "/user/transport/view?"+resultEnCode;

                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            // return new Date(value).format("yyyy-MM-dd hh:mm:ss");
                            return '<a href="' + href + '">' + value + '<br>' + row.goodsDesc + '</a>';
                        }
                    }, {
                        field: 'tradingType',
                        title: '<?php echo $this->translate("type"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                return value = "-";
                            } else {
                                let result = '',
                                    data = $.data(dataDict, 'dataDict');
                                if (value !== 'D') {
                                    $.each(data, function (key, item) {
                                        if (key === 'PAYMENT_TRADING_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === value) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                } else {
                                    $.each(data, function (key, item) {
                                        if (key === 'AR_AP_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === row.rptype) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                }

                                let base = new Base64(),
                                    resultEnCode = base.encode(row.transportOrderID),
                                    href = "/user/transport/view?"+resultEnCode;

                                return '<a href="' + href + '">' + result + '</a>';
                            }
                        }
                    }, {
                        field: 'carrierName',
                        title: '<?php echo $this->translate("承运人"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            let base = new Base64(),
                                resultEnCode = base.encode(row.transportOrderID),
                                href = "/user/transport/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'arrivalsName',
                        title: '<?php echo $this->translate("始发地/目的地"); ?>',
                        halign: 'center',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            let base = new Base64(),
                                resultEnCode = base.encode(row.transportOrderID),
                                href = "/user/transport/view?"+resultEnCode;

                            return '<a href="' + href + '">' + row.departureName + '<br>' + value + '</a>';
                        }
                    }, {
                        field: 'takeDeliveryTime',
                        title: '<?php echo $this->translate("到货时间"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            let base = new Base64(),
                                resultEnCode = base.encode(row.transportOrderID),
                                href = "/user/transport/view?"+resultEnCode;

                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return '<a href="' + href + '">' + new Date(value).format("yyyy-MM-dd") + '</a>';
                        }
                    }, {
                        field: 'orderAmount',
                        title: '<?php echo $this->translate("应收运费"); ?>',
                        align: 'right',
                        valign: 'middle',
                        formatter: function (value, row) {
                            let result = row.crnCode + ' ' + formatCurrency(value, 2);

                            let base = new Base64();
                            let resultEnCode = base.encode(row.customerID);
                            let href = "/user/financing/financing-item-view?"+resultEnCode;

                            return '<a href="' + href + '">' + result + '</a>';
                        }
                    }, {
                        field: 'freightAmount',
                        title: '<?php echo $this->translate("应付运费"); ?>',
                        align: 'right',
                        valign: 'middle',
                        formatter: function (value, row) {
                            let result = row.crnCode + ' ' + formatCurrency(value, 2);

                            let base = new Base64(),
                                resultEnCode = base.encode(row.customerID),
                                href = "/user/financing/financing-item-view?"+resultEnCode;

                            return '<a href="' + href + '">' + result + '</a>';
                        }
                    }]
                });
            }
        });
	});
</script>
</body>
</html>
