<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/user/transport"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/transport"><?php echo $this->translate('运单列表'); ?></a></li>
            <li class="active"><?php echo $this->translate('运单详情'); ?></li>
        </ol>

        <div class="page-header">
            <h3><?php echo $this->translate('运单详情'); ?></h3>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-5">
                                <h3><?php echo $this->translate('运单编号'); ?>：<?php echo $this->transportOrder['transOrderCode']; ?> </h3>

                            </div>
                            <div class="col-md-1">
                                <span class="label label-success">状态：<?php echo $this->ShowDictionaryTo($this->dic_Setting['TRANSORDER_FACTORING_STATUS'], $this->userLangCode, $this->dic_Setting['TRANSORDER_FACTORING_STATUS'], $this->transportOrder["financeStatus"]); ?></span>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <p>&nbsp;</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('货物信息'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo $this->e['transNo']; ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('货源'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo $this->transportOrder['customerName']; ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('运输费用'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo number_format($this->transportOrder['freightAmount'], 2); ?> 元
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('完成时间'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo date("Y-m-d H:i:s", strtotime($this->transportOrder['takeDeliveryTime'])); ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('金融服务'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h3><?php echo $this->translate('运输信息'); ?></h3>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <p>&nbsp;</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('始发地'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo $this->transportOrder['departureName']; ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('目的地'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo $this->transportOrder['arrivalsName']; ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('距离'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo $this->transportOrder['distance']; ?> km
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('开始时间'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo date("Y-m-d H:i:s", strtotime($this->transportOrder['departureTime'])); ?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-2">
                                <p class="form-control-static text-999"><?php echo $this->translate('结束时间'); ?></p>
                            </div>
                            <div class="col-md-10">
                                <p class="form-control-static text-666">
                                    <?php echo date("Y-m-d H:i:s", strtotime($this->transportOrder['arrivalsTime'])); ?>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h3><?php echo $this->translate('承运人'); ?></h3>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <p>&nbsp;</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <table data-toggle="table" data-classes="table">
                                    <thead>
                                    <tr>
                                        <th data-width="130">司机</th>
                                        <th data-width="120">联系方式</th>
                                        <th data-width="180">车辆</th>
                                        <th data-width="180">身份证</th>
                                        <th data-width="180">备注</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <?php foreach ($this->transportOrder['transporterList'] as $transporter): ?>
                                        <tr>
                                            <td><?php echo $transporter['dirverName']; ?></td>
                                            <td><?php echo $transporter['mobile']; ?></td>
                                            <td><?php echo $transporter['vehicleNo']; ?>，<?php echo $transporter['vehicleLength']; ?>，<?php echo $transporter['vehicleModel']; ?></td>
                                            <td><?php echo $transporter['identityCardID']; ?></td>
                                            <td></td>
                                        </tr>
                                    <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="hidden">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h3>运输路线</h3>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <ul class="layui-timeline">
                                    <li class="layui-timeline-item">
                                        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                        <div class="layui-timeline-content layui-text">
                                            <h3 class="layui-timeline-title">2019-10-10 20:09:19</h3>
                                            <p>
                                                浙江省绍兴市上虞区苏宁,西南方向,105.2米
                                            </p>
                                        </div>
                                    </li>
                                    <li class="layui-timeline-item">
                                        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                        <div class="layui-timeline-content layui-text">
                                            <h3 class="layui-timeline-title">2019-10-10 20:09:19</h3>
                                            <p>
                                                浙江省绍兴市上虞区苏宁,西南方向,105.2米
                                            </p>
                                        </div>
                                    </li>
                                    <li class="layui-timeline-item">
                                        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                        <div class="layui-timeline-content layui-text">
                                            <h3 class="layui-timeline-title">2019-10-10 20:09:19</h3>
                                            <p>
                                                浙江省绍兴市上虞区苏宁,西南方向,105.2米
                                            </p>
                                        </div>
                                    </li>
                                    <li class="layui-timeline-item">
                                        <i class="layui-icon layui-timeline-axis">&#xe63f;</i>
                                        <div class="layui-timeline-content layui-text">
                                            <h3 class="layui-timeline-title">2019-10-10 20:09:19</h3>
                                            <p>
                                                浙江省绍兴市上虞区苏宁,西南方向,105.2米
                                            </p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-12">
                                <h3>路线地图</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>
<script src="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/locale/bootstrap-table-zh-CN.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('#resultListTable').bootstrapTable({

        });
	});
</script>
</body>
</html>
