<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/company/company.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">

    <!-- Web Uploader -->
    <!--<link href="/ky/webuploader-0.1.8-dist/webuploader.css" rel="stylesheet">-->
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container">
        <div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/company/authview" class="list-group-item"><?php if (!$this->hasIDCertificate): ?><i class="makerDot"></i><?php endif;?><?php echo $this->translate('companyAuth'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <div class="modal-header et-auth-bg-no">
                        <h4 class="modal-title" ><?php echo $this->translate('et_auth_verify'); ?></h4>
                        <div class="table-responsive" style="height: 90px;">
                            <form id="msForm">
                                <!-- progressbar -->
                                <ul id="progressbar">
                                    <li class="active">企业基本信息认证</li>
                                    <li class="active">银行信息认证、打款</li>
                                    <li class="activation">验证打款金额</li>
                                    <li>完成</li>
                                </ul>
                            </form>
                        </div>
                        <p><em>*</em> <?php echo $this->translate('et_auth_amount'); ?></p>
                    </div>

                    <div class="modal-body">
                        <div class="row">
                            <div class="et-auth-error" style="display: none;"></div>
                        </div>

                        <div class="row">
                            <form class="form-horizontal">
                                <div class="alert alert-danger col-sm-10 col-sm-offset-1 hidden confirmAlert" role="alert">Oh snap! 错误信息....</div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_name'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_code'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->businessLicenseNo; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_mg_name'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonName; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_mg_id'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonIdentityNo; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_acctNo'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->cardno; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_bankName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->bank; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_cityName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->provice; ?> / <?php echo json_decode($this->account->entRealAuthInfo)->city; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_subbranchName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->subbranch; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="authVerifyAmount" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_verify'); ?></label>
                                    <div class="col-sm-10 col-sm-8">
                                        <input type="text" class="form-control" id="authVerifyAmount" name="authVerifyAmount" placeholder="请输入<?php echo $this->translate('ordertotal'); ?>" >
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" id="doConfirmBtn"><?php echo $this->translate('confirm'); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<!-- Web Uploader -->
<!--<script type="text/javascript" src="/ky/webuploader-0.1.8-dist/webuploader.js"></script>-->
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script type="text/javascript">
    $().ready(function() {

    });

    $(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $("#doConfirmBtn").click(function () {
            var $authVerifyAmount = $("#authVerifyAmount"),
                $confirmAlert = $(".confirmAlert");
            if ($authVerifyAmount.val() === '') {
                $confirmAlert.removeClass("hidden");
                $confirmAlert.html("收款金额不能为空。");
                $authVerifyAmount.parent().addClass("has-error").focus();
                return false;
            }

            $("#doConfirmBtn").attr("disabled", true);
            var companyDoAuthPay = '/user/company/authconfirm';
            var loadLayer;

            $.ajax({
                type: "POST",
                url: companyDoAuthPay,
                data: {
                    authVerifyAmount: $authVerifyAmount.val()
                },
                dataType: "json",
                success: function (data) {
                    $("#doConfirmBtn").attr("disabled", false);
                    layer.close(loadLayer); // 关闭加载层

                    var contentStr = '',
                        contentErrCode = '';
                    if (data.status === 1) {
                        if (data.errCode === '0') {
                            // 验证成功, 刷新页面
                            setTimeout(function () {
                                document.location.reload();
                            }, 500);
                        } else {
                            // 验证失败, 弹出提示
                            contentErrCode = data.errCode;
                            contentStr = data.msg;
                            layerInfo(contentErrCode, contentStr);
                        }
                    } else {
                        contentStr = data.errorCode;
                        layerInfo(contentErrCode, contentStr);
                    }
                },
                beforeSend: function () {
                    loadLayer = layer.open({
                        type: 3
                        ,icon: 1
                    });
                },
                error: function () {
                    $("#doConfirmBtn").attr("disabled", false);
                }
            });
        });
    });

    function layerInfo(contentErrCode, contentStr) {
        layer.open({
            type: 1
            ,title: false //不显示标题栏
            ,closeBtn: false
            ,area: '400px;'
            ,shade: 0.8
            ,id: 'LAY_layuipro' //设定一个id，防止重复弹出
            ,btn: ['确认']
            ,btnAlign: 'c'
            ,moveType: 1 //拖拽模式，0或者1
            ,content: '<div style="padding: 50px; line-height: 22px; background-color: #393D49; color: #fff; font-weight: 300;">验证失败！<br><br>' + contentStr + '。</div>'
        });
    }
</script>
</body>
</html>
