<div id="authViewDiv_" class="layui-form">
	<div class="et-auth-top et-auth-bg-ok" style="height: 100px; text-align: left;">
		<h3><?php echo $this->translate('companySignh32'); ?></h3>
		<p><?php echo $this->translate('companySignp03'); ?></p>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="">
		<div style="margin-top: 20px;"></div>
		
		<?php
		// var_dump(json_decode($this->account->entRealAuthInfo)->accountName);exit;
		?>

		<!--营业执照名称-->
		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_name'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_code'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->businessLicenseNo; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_mg_name'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonName; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_mg_id'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonIdentityNo; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_acctNo'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->cardno; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_bankName'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->bank; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_cityName'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->provice; ?> / <?php echo json_decode($this->account->entRealAuthInfo)->city; ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><?php echo $this->translate('et_auth_subbranchName'); ?></label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo json_decode($this->account->entRealAuthInfo)->subbranch; ?></div>
			</div>
		</div>
	</div>
</div>