<div class="modal-header et-auth-bg-no">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" ><?php echo $this->translate('companySignh3'); ?></h4>
    <div class="table-responsive">
        <form id="msForm">
            <!-- progressbar -->
            <ul id="progressbar">
                <li class="active">企业基本信息认证</li>
                <li class="activation">银行信息认证、打款</li>
                <li>验证打款金额</li>
                <li>完成</li>
            </ul>
        </form>
    </div>
    <p><em>*</em> <?php echo $this->translate('companySignp01'); ?></p>
</div>

<div class="modal-body">
    <div class="alert alert-danger hidden" role="alert">
        <strong>Warning!</strong> <p></p>
    </div>
    <div class="row">
        <form class="form-horizontal">
            <div class="form-group">
                <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_name'); ?></label>
                <div class="col-sm-9">
                    <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?></p>
                    <input type="hidden" id="acctName" value="<?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="auth_acctNo" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_acctNo'); ?></label>
                <div class="col-sm-10 col-sm-8">
                    <input type="text" class="form-control" id="auth_acctNo" name="auth_acctNo" placeholder="请输入<?php echo $this->translate('et_auth_acctNo'); ?>">
                </div>
            </div>

            <div class="form-group">
                <label for="bankName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_bankName'); ?></label>
                <div class="col-sm-10 col-sm-8">
                    <select name="bankName" id="bankName" lay-verify="required" lay-search="" lay-filter="bankName">
                        <option value=""><?php echo $this->translate('et_select'); ?></option>
                        <?php echo $this-> ShowDictionaryList("datatest_setting",$this->userlangCode,$this->dic_Setting['ESIGN_BANK'], '');?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="provinceName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_cityName'); ?></label>
                <div class="col-sm-10 col-sm-4">
                    <select name="provinceName" id="provinceName" lay-filter="provinceName">
                        <option value=""></option>
                        <?php echo $this-> ShowDictionaryList("datatest_setting",$this->userlangCode,$this->dic_Setting['ESIGN_PROVINCE_CODE'], '');?>
                    </select>
                </div>
                <div class="col-sm-10 col-sm-4">
                    <select name="cityName" id="cityName" lay-filter="cityName">
                        <option value=""></option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="subbranchName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_subbranchName'); ?></label>
                <div class="col-sm-10 col-sm-8">
                    <select name="subbranchName" id="subbranchName" lay-verify="required" lay-search="" lay-filter="subbranchName">
                        <option value=""><?php echo $this->translate('et_select'); ?></option>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label for="auth_mg_id" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_mg_id'); ?></label>
                <div class="col-sm-10 col-sm-8">
                    <input type="text" class="form-control" id="auth_mg_id" name="auth_mg_id" value="<?php echo $this->account->legalPersonIdentityNo; ?>" placeholder="请输入<?php echo $this->translate('et_auth_mg_id'); ?>">
                </div>
            </div>
        </form>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('close'); ?></button>
    <button type="button" class="btn btn-primary" id="doConfirmBtn"><?php echo $this->translate('next'); ?></button>
</div>

<script type="text/javascript">
    $(function () {
        var form = layui.form;
        form.render('select');

        layui.use('element', function(){
            var element = layui.element;
            element.render();
        });

        $("#doConfirmBtn").click(function () {
            var acctName = $("#acctName").val();
            var auth_acctNo = $("#auth_acctNo").val();
            var bankName = $("#bankName").val();
            var provinceName = $("#provinceName").val();
            var cityName = $("#cityName").val();
            var subbranchName = $("#subbranchName").val();

            $("#doConfirmBtn").attr("disabled", true);
            var companyDoAuthPay = '/user/company/doauthpay';
            $.post(companyDoAuthPay, {
                acctName: acctName,
                auth_acctNo: auth_acctNo,
                bankName: bankName,
                provinceName: provinceName,
                cityName: cityName,
                subbranchName: subbranchName
            }, function (data) {
                if (data === '0' || data === '-4') {
                    $('#authModal').modal('hide');
                    setTimeout(function () {
                        $("#company-auth").trigger("click");
                    }, 500);
                } else {
                    $(".alert").removeClass('hidden').addClass('show').find('p').html(data);
                    console.log("err: " + data);
                }
                $("#doConfirmBtn").attr("disabled", false);
            });
        });
    });
</script>
