<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/company/company.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">

    <!-- Web Uploader -->
    <!--<link href="/ky/webuploader-0.1.8-dist/webuploader.css" rel="stylesheet">-->
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container">
        <div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/company/authview" class="list-group-item"><?php echo $this->translate('companyAuth'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <div class="modal-header et-auth-bg-no">
                        <h4 class="modal-title" ><?php echo $this->translate('et_auth_verify'); ?></h4>
                        <div class="table-responsive">
                            <form id="msForm">
                                <!-- progressbar -->
                                <ul id="progressbar">
                                    <li class="active">企业基本信息认证</li>
                                    <li class="active">银行信息认证、打款</li>
                                    <li class="activation">验证打款金额</li>
                                    <li>完成</li>
                                </ul>
                            </form>
                        </div>
                        <p><em>*</em> <?php echo $this->translate('et_auth_amount'); ?></p>
                    </div>

                    <div class="modal-body">
                        <div class="row">
                            <div class="et-auth-error" style="display: none;"></div>
                        </div>

                        <div class="row">
                            <form class="form-horizontal">
                                <div class="alert alert-danger col-sm-10 col-sm-offset-1 hidden confirmAlert" role="alert">Oh snap! 错误信息....</div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_name'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_code'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->businessLicenseNo; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_mg_name'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonName; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_mg_id'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->legalPersonIdentityNo; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_acctNo'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->cardno; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_bankName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->bank; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_cityName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->provice; ?> / <?php echo json_decode($this->account->entRealAuthInfo)->city; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_subbranchName'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->subbranch; ?></p>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="authVerifyAmount" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_verify'); ?></label>
                                    <div class="col-sm-10 col-sm-8">
                                        <input type="text" class="form-control" id="authVerifyAmount" name="authVerifyAmount" placeholder="请输入<?php echo $this->translate('ordertotal'); ?>">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" id="doConfirmBtn"><?php echo $this->translate('confirm'); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<!-- Web Uploader -->
<!--<script type="text/javascript" src="/ky/webuploader-0.1.8-dist/webuploader.js"></script>-->
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script type="text/javascript">
    $().ready(function() {

    });

    $(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $("#doConfirmBtn").click(function () {
            var authVerifyAmount = $("#authVerifyAmount").val();

            $("#doConfirmBtn").attr("disabled", true);
            var companyDoAuthPay = '/user/company/authconfirm';
            $.post(companyDoAuthPay, {
                authVerifyAmount: authVerifyAmount
            }, function (data) {
                if (data === '0') {
                    $('#authModal').modal('hide');
                    setTimeout(function () {
                        $("#company-auth").removeClass("et-ico-auth-cno et-ico-auth-cing").addClass("et-ico-auth-cok").trigger("click");
                    }, 500);
                } else if (data === '-4') {
                    $('#authModal').modal('hide');
                    setTimeout(function () {
                        $("#company-auth").removeClass("et-ico-auth-cing et-ico-auth-cok").addClass("et-ico-auth-cno").trigger("click");

                        var $confirmAlert = $(".confirmAlert");
                        $confirmAlert.removeClass("hidden");
                        $confirmAlert.html("超出3次认证失败功能冻结，请与客服联系。");
                    }, 500);
                } else {
                    console.log("err: " + data);
                }
                $("#doConfirmBtn").attr("disabled", false);
            });
        });
    });
</script>
</body>
</html>
