<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/company/company.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">

    <!-- Web Uploader -->
    <!--<link href="/ky/webuploader-0.1.8-dist/webuploader.css" rel="stylesheet">-->
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container">
        <div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/company/authview" class="list-group-item"><?php if (!$this->hasIDCertificate): ?><i class="makerDot"></i><?php endif;?><?php echo $this->translate('companyAuth'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <div class="modal-header et-auth-bg-no">
                        <h4 class="modal-title" ><?php echo $this->translate('companySignh3'); ?></h4>
                        <div class="table-responsive" style="height: 90px;">
                            <form id="msForm">
                                <!-- progressbar -->
                                <ul id="progressbar">
                                    <li class="active">企业基本信息认证</li>
                                    <li class="activation">银行信息认证、打款</li>
                                    <li>验证打款金额</li>
                                    <li>完成</li>
                                </ul>
                            </form>
                        </div>
                        <p><em>*</em> <?php echo $this->translate('companySignp01'); ?></p>
                    </div>

                    <div class="modal-body">
                        <div class="alert alert-danger hidden" role="alert">
                            <strong>Warning!</strong> <p></p>
                        </div>
                        <div class="row">
                            <form class="form-horizontal layui-form">
                                <div class="form-group">
                                    <label class="col-sm-3 control-label"><?php echo $this->translate('et_auth_name'); ?></label>
                                    <div class="col-sm-9">
                                        <p class="form-control-static"><?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?></p>
                                        <input type="hidden" id="acctName" value="<?php echo json_decode($this->account->entRealAuthInfo)->accountName; ?>">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="auth_acctNo" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_acctNo'); ?></label>
                                    <div class="col-sm-10 col-sm-8">
                                        <input type="text" class="form-control" id="auth_acctNo" name="auth_acctNo" placeholder="请输入<?php echo $this->translate('et_auth_acctNo'); ?>">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="bankName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_bankName'); ?></label>
                                    <div class="col-sm-10 col-sm-8">
                                        <select name="bankName" id="bankName" lay-verify="required" lay-search="" lay-filter="bankName">
                                            <option value=""><?php echo $this->translate('et_select'); ?></option>
                                            <?php echo $this-> ShowDictionaryList("datatest_setting",$this->userLangCode,$this->dic_Setting['ESIGN_BANK'], '');?>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="provinceName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_cityName'); ?></label>
                                    <div class="col-sm-10 col-sm-4">
                                        <select name="provinceName" id="provinceName" lay-filter="provinceName">
                                            <option value=""></option>
                                            <?php echo $this-> ShowDictionaryList("datatest_setting",$this->userLangCode,$this->dic_Setting['ESIGN_PROVINCE_CODE'], '');?>
                                        </select>
                                    </div>
                                    <div class="col-sm-10 col-sm-4">
                                        <select name="cityName" id="cityName" lay-filter="cityName">
                                            <option value=""></option>
                                        </select>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="subbranchName" class="col-sm-3 control-label"><?php echo $this->translate('et_auth_subbranchName'); ?></label>
                                    <div class="col-sm-10 col-sm-8">
                                        <select name="subbranchName" id="subbranchName" lay-verify="required" lay-search="" lay-filter="subbranchName">
                                            <option value=""><?php echo $this->translate('et_select'); ?></option>
                                        </select>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" id="doConfirmBtn"><?php echo $this->translate('next'); ?></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<!-- Web Uploader -->
<!--<script type="text/javascript" src="/ky/webuploader-0.1.8-dist/webuploader.js"></script>-->
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    $().ready(function() {

    });

    $(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        layui.use('form', function(){
            var form = layui.form;

            form.on('select(bankName)', function(data){
                var bankCode = data.value;
                var cityCode = $("#cityName").val();

                if (cityCode !== '' && bankCode !== '') {
                    var fuzzyQuery = '/user/company/fuzzy';
                    $.ajax({
                        type: "POST",
                        url: fuzzyQuery,
                        data: {
                            dataDictCode: 'ESIGN_SUBBRANCH_BANK',
                            keyword: '',
                            valuePCode: cityCode + ',' + bankCode
                        },
                        dataType: "json",
                        success: function (data) {
                            var optionString = "";
                            $.each(data, function (i, item) {
                                console.log(item);
                                optionString += "<option value=\"" + item.valueCode + "\" >" + item.valueCode + "</option>";
                            });
                            var str = '<?php echo $this->translate("et_select"); ?>';
                            $("#subbranchName").html('<option value="">' + str + '</option>' + optionString);
                            form.render('select'); //这个很重要
                        }
                    });
                } else {
                    var str = '<?php echo $this->translate("et_select"); ?>';
                    $("#subbranchName").empty().html('<option value="">' + str + '</option>');
                    form.render('select');
                }
            });

            form.on('select(provinceName)', function (data) {
                var provinceCode = data.value;
                if (provinceCode !== '') {
                    var fuzzyQuery = '/user/company/fuzzy';
                    $.ajax({
                        type: "POST",
                        url: fuzzyQuery,
                        data: {
                            dataDictCode: 'ESIGN_CITY_CODE',
                            keyword: '',
                            valuePCode: provinceCode
                        },
                        dataType: "json",
                        success: function (data) {
                            var optionString = '';
                            $.each(data, function (i, item) {
                                console.log(item);
                                optionString += '<option value="' + item.valueCode + '" >' + item.valueCode + '</option>';
                            });
                            $("#cityName").html('<option value=""></option>' + optionString);
                            form.render('select'); //这个很重要
                        }
                    });
                } else {
                    $("#cityName").empty().html('<option value=""></option>');
                    form.render('select');
                }
            });

            form.on('select(cityName)', function (data) {
                var bankCode = $("#bankName").val();
                var cityCode = data.value;

                if (cityCode !== '' && bankCode !== '') {
                    var fuzzyQuery = '/user/company/fuzzy';
                    $.ajax({
                        type: "POST",
                        url: fuzzyQuery,
                        data: {
                            dataDictCode: 'ESIGN_SUBBRANCH_BANK',
                            keyword: '',
                            valuePCode: cityCode + ',' + bankCode
                        },
                        dataType: "json",
                        success: function (data) {
                            var optionString = "";
                            $.each(data, function (i, item) {
                                console.log(item);
                                optionString += "<option value=\"" + item.valueCode + "\" >" + item.valueCode + "</option>";
                            });
                            var str = '<?php echo $this->translate("et_select"); ?>';
                            $("#subbranchName").html('<option value="">' + str + '</option>' + optionString);
                            form.render('select'); //这个很重要
                        }
                    });
                } else {
                    var str = '<?php echo $this->translate("et_select"); ?>';
                    $("#subbranchName").empty().html('<option value="">' + str + '</option>');
                    form.render('select');
                }
            });

            //但是，如果你的HTML是动态生成的，自动渲染就会失效
            //因此你需要在相应的地方，执行下述方法来手动渲染，跟这类似的还有 element.init();
            form.render();
        });

        layui.use('element', function () {
            var element = layui.element;
            element.render();
        });

        $("#doConfirmBtn").click(function () {
            var acctName = $("#acctName").val();
            var auth_acctNo = $("#auth_acctNo").val();
            var bankName = $("#bankName").val();
            var provinceName = $("#provinceName").val();
            var cityName = $("#cityName").val();
            var subbranchName = $("#subbranchName").val();

            $("#doConfirmBtn").attr("disabled", true);
            var companyDoAuthPay = '/user/company/doauthpay';
            $.post(companyDoAuthPay, {
                acctName: acctName,
                auth_acctNo: auth_acctNo,
                bankName: bankName,
                provinceName: provinceName,
                cityName: cityName,
                subbranchName: subbranchName
            }, function (data) {
                if (data === '0' || data === '-4') {
                    setTimeout(function () {
                        document.location.reload();
                    }, 500);
                } else {
                    $(".alert").removeClass('hidden').addClass('show').find('p').html(data);
                    console.log("err: " + data);
                }
                $("#doConfirmBtn").attr("disabled", false);
            });
        });
    });
</script>
</body>
</html>
