<div id="authViewDiv_" class="layui-form">
	<div class="et-auth-top et-auth-bg-no" style="height: 200px; text-align: left;">
		<h3><?php echo $this->translate('companySignh3'); ?></h3>
		<div class="time-line-x">
			<h3 class="time-line-title time-line-title-aft">
				<span><i class="layui-icon">&#xe63f;</i></span>
				<!--<label>基本信息认证</label>-->
			</h3>
			<h3 class="time-line-title time-line-title-bef time-line-title-aft">
				<span><i class="layui-icon">&#xe63f;</i></span>
				<!--<label>银行信息认证、获取验证码</label>-->
			</h3>
			<h3 class="time-line-title time-line-title-bef time-line-title-aft">
				<span><i class="layui-icon">&#xe63f;</i></span>
				<!--<label>打款验证</label>-->
			</h3>
			<h3 class="time-line-title time-line-title-bef">
				<span><i class="layui-icon">&#xe63f;</i></span>
				<!--<label>完成</label>-->
			</h3>
		</div>
		<p><?php echo $this->translate('companySignp01'); ?></p>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="">
		<div style="margin-top: 20px;"></div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><!--企业名称--><?php echo $this->translate('et_auth_name'); ?><em>*</em></label>
			<div class="layui-input-block" style="margin-left: 150px; width: 360px;">
				<input type="text" name="auth_name" value="<?php echo $this->account->accountName; ?>" lay-verify="et_auth_name" autocomplete="off" placeholder="请输入<?php echo $this->translate('et_auth_name'); ?>" class="layui-input">
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><!--统一社会信用代码--><?php echo $this->translate('et_auth_code'); ?><em>*</em></label>
			<div class="layui-input-block" style="margin-left: 150px; width: 360px;">
				<input type="text" name="auth_code" value="<?php echo $this->account->businessLicenseNo; ?>" lay-verify="auth_code" autocomplete="off" placeholder="请输入<?php echo $this->translate('et_auth_code'); ?>" class="layui-input">
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><!--负责人姓名--><?php echo $this->translate('et_auth_mg_name'); ?><em>*</em></label>
			<div class="layui-input-block" style="margin-left: 150px; width: 360px;">
				<input type="text" name="auth_mg_name" value="<?php echo $this->account->legalPersonName; ?>" lay-verify="auth_mg_name" autocomplete="off" placeholder="请输入<?php echo $this->translate('et_auth_mg_name'); ?>" class="layui-input">
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label" style="width: 120px"><!--负责人身份证号码--><?php echo $this->translate('et_auth_mg_id'); ?><em>*</em></label>
			<div class="layui-input-block" style="margin-left: 150px; width: 360px;">
				<input type="text" name="auth_mg_id" value="<?php echo $this->account->legalPersonIdentityNo; ?>" lay-verify="auth_mg_name" autocomplete="off" placeholder="请输入<?php echo $this->translate('et_auth_mg_id'); ?>" class="layui-input">
			</div>
		</div>

		<div class="et-auth-row" style="text-align: center;">
			<button class="layui-btn layui-btn-warm" id="doAuthBtn"><?php echo $this->translate('next'); ?></button>
		</div>
	</div>
</div>