<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/company/company.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">

    <!-- Web Uploader -->
    <!--<link href="/ky/webuploader-0.1.8-dist/webuploader.css" rel="stylesheet">-->
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container">
        <div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/company/authview" class="list-group-item"><?php if (!$this->hasIDCertificate): ?><i class="makerDot"></i><?php endif;?><?php echo $this->translate('companyAuth'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <div class="modal-header et-auth-bg-no">
                        <h4 class="modal-title" ><?php echo $this->translate('companySignh3'); ?></h4>
                        <div class="table-responsive" style="height: 90px;">
                            <form id="msForm">
                                <!-- progressbar -->
                                <ul id="progressbar">
                                    <li class="activation">企业基本信息认证</li>
                                    <li>银行信息认证、打款</li>
                                    <li>验证打款金额</li>
                                    <li>完成</li>
                                </ul>
                            </form>
                        </div>
                    </div>

                    <div class="modal-body" style="height: 265px;">
                        <div class="alert alert-danger" role="alert">
                            <strong>Warning!</strong>
                            <p>&nbsp;</p>
                            <p>企业实名认证申请失败超过三次，认证功能冻结，请与客服联系。</p>
                            <p>企业实名认证申请必须在72小时内完成，超过72小时认证功能冻结，请与客服联系。</p>
                        </div>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<!-- Web Uploader -->
<!--<script type="text/javascript" src="/ky/webuploader-0.1.8-dist/webuploader.js"></script>-->
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script type="text/javascript">
    $().ready(function() {

    });

    $(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });
    });
</script>
</body>
</html>
