<div class="modal-header et-auth-bg-no">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4 class="modal-title" ><?php echo $this->translate('companySignh3'); ?></h4>
    <div class="table-responsive">
        <form id="msForm">
            <!-- progressbar -->
            <ul id="progressbar">
                <li class="activation">企业基本信息认证</li>
                <li>银行信息认证、打款</li>
                <li>验证打款金额</li>
                <li>完成</li>
            </ul>
        </form>
    </div>
</div>

<div class="modal-body">
    <div class="alert alert-danger" role="alert">
        <strong>Warning!</strong> <p>企业实名认证申请必须在72小时内完成，超过72小时认证功能冻结，请与客服联系。</p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('close'); ?></button>
</div>

<script type="text/javascript">
    $(function () {
    });
</script>
