<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/img-upload.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/My97DatePicker/WdatePicker.js"></script>
<style type="text/css">
.dq_select{margin:0;}
.error{margin:0;}
#acEmail, #acLogin {
    width: 40px;
    height: 25px;
    line-height: 25px;
    color: #fff;
    text-align: center;
    margin: 0 10px;
    display: inline-block;
    background: #ff8c21;
    border-radius: 5px;
    border: 1px solid #de6e06;
}
</style>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL.'/company/r_top_menu.phtml');?>
        <form name="company_form" id="company_form" method="post" enctype="multipart/form-data" action="">
            <div class="info_cont clearfix">
                <div class="n_o_c_tit">
                    <h4><!--编辑公司信息--><?php echo $this->translate('edit').$this->translate('company_info');?></h4>
                </div>
                <div class="o_c_content">
                    <?php if($this->userrgCode):?>
                    <dl class="fl">
                        <dt class="fl"><!-- 公司名称 --><?php echo $this->translate('comNAME');?></dt>
                        <dd class="company"><input type="text" value="<?php echo $this->e['accountName'];?>" name="accountName" <?php if($this->e['accountStatus']==01){echo 'readonly="ture" style="background: #F5F5F5;border: none;"';} ?> /></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 英文名称 --><?php echo $this->translate('enNAME');?></dt>
                        <dd class="eng_name"><input type="text" value="<?php echo $this->e['accountEnName'];?>" name="accountEnName" class="di_style" <?php if($this->e['accountStatus']==01){echo 'readonly="ture" style="background: #F5F5F5;border: none;"';} ?> /></dd>
                    </dl>
                    <dl class="fl" style="width:100%">
                        <dt class="fl"><!-- 地址 --><?php echo $this->translate('address');?></dt>
                        <dd style="width:84%;" class="address">
                            <?php if($this->e['accountStatus']==01):?>
                            <a style="overflow: hidden; margin-right: 20px; display: block; float: left; color: rgb(0, 0, 0); font-size: 14px;" href="#" title=" <?php echo $this->ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>">
                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>
                            </a>
                            <?php else:?>
                            <select   class=" dq_select" name="regdCountryCode" id="regdCountryCode">
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>
                            </select>
                            <?php endif;?>
                            <input class="must" style="border: 1px solid #DF7E20;width:538px;" type="text" value="<?php echo $this->e['regdAddress'];?>" name="regdAddress" id="regdAddress" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('address');?>"/></dd>
                    </dl>
                        <dl class="fl" style="width:100%">
                            <dt class="fl" style="color: #f5f5f5;"><!-- 英文地址 --><?php echo $this->translate('enAdress');?></dt>
                            <dd style="width:84%;" class="address">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                <input class="must" style="border: 1px solid #DF7E20;width:538px;" type="text" value="<?php echo $this->e['regdEnAddress'];?>" name="regdEnAddress" id="regdEnAddress" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('enAdress');?>"/></dd>
                        </dl>
                    <?php else:?>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!-- 公司名称 --><?php echo $this->translate('comNAME');?></dt>
                            <dd class="company"><input type="text" value="<?php echo $this->e['accountName'];?>" name="accountName" <?php if($this->e['accountStatus']==01){echo 'readonly="ture" style="background: #F5F5F5;border: none;"';} ?> /></dd>
                        </dl>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!-- 地址 --><?php echo $this->translate('address');?></dt>
                            <dd style="width:84%;" class="address">
                                <?php if($this->e['accountStatus']==01):?>
                                    <a style="overflow: hidden; margin-right: 20px; display: block; float: left; color: rgb(0, 0, 0); font-size: 14px;" href="#" title=" <?php echo $this->ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>">
                                        <?php echo $this->ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>
                                    </a>
                                <?php else:?>
                                    <select   class=" dq_select" name="regdCountryCode" id="regdCountryCode">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['COUNTRY_ISO_CODE'],$this->userlangCode,$this->dic_Setting['COUNTRY_ISO_CODE'],$this->e['regdCountryCode']);?>
                                    </select>
                                <?php endif;?>
                                <input class="must" style="border: 1px solid #DF7E20;width:538px;" type="text" value="<?php echo $this->e['regdAddress'];?>" name="regdAddress" id="regdAddress" required data-msg-required="<?php echo $this->translate('de_null');?>" /></dd>
                        </dl>
                    <?php endif;?>
                    <dl class="fl">
                        <dt class="fl"><!-- 语言 --><?php echo $this->translate('dLANG');?></dt>
                        <dd class="language">
                            <select class="dq_select" name="langCode" id="langCode">
                                <?php echo $this->ShowDictionaryList('datatest_setting',$this->userlangCode,$this->dic_Setting['SYS_LANG'],$this->e['langCode']);?>
                            </select>
                        </dd>
                        </dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 货币 --><?php echo $this->translate('defaultCCY');?></dt>
                        <dd class="fl doller">
                            <?php if($this->e['accountStatus']==01){echo $this->e['crnCode'];}?>
                            <select   <?php if($this->e['accountStatus']==01){echo 'style="display:none;"  name="crnCode" ';} ?>  class="dq_select" id="crnCode" required data-msg-required="<?php echo $this->translate('de_null');?>">
                                <?php echo $this->ShowDictionaryList('datatest_setting',$this->userlangCode,$this->dic_Setting['CURRENCY'],$this->e['crnCode']);?>
                            </select>
                        </dd>
                    </dl>
                    <!-- 公司形式 -->
                    <dl class="fl">
                        <dt class="fl"><!-- 公司形式 --><?php echo $this->translate('company_legal_form');?></dt>
                        <dd class="fl dade">
                            <!--需要同时呈现code和Name-->
                            <select class="dq_select" name="legalForm" id="legalForm" required data-msg-required="<?php echo $this->translate('de_null');?>">
                                <?php echo $this->ShowDictionaryList('datatest_setting',$this->userlangCode,$this->dic_Setting['ACCOUNT_LEGALFORM'],$this->e['legalForm']);?>
                            </select>
                        </dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 成立日期 --><?php echo $this->translate('company_incorporation_date');?></dt><dd class="fl dade">
                            <??>
                            <?php if($this->e['accountStatus']==01):?>
                                <?php if($this->e['incorporationDate']){echo date('Y-m-d',strtotime($this->e['incorporationDate']));}else{echo null;}?>
                            <?php endif;?>
                            <?php if($this->e['accountStatus']!=01):?>
                                <input  class="must" style="border: 1px solid #DF7E20;"  type="text" value="<?php if($this->e['incorporationDate']){echo date('Y-m-d',strtotime($this->e['incorporationDate']));}?>" name="incorporationDate" id="incorporationDate"   onfocus="WdatePicker({minDate:'1600-01-01',maxDate:'%y-%M-%d'})" required data-msg-required="<?php echo $this->translate('de_null');?>" />
                            <?php endif;?>
                        </dd>
                    </dl>

                    <!-- 行业 -->
                    <dl class="fl"  style="width:100%">
                        <dt class="fl"><!-- 行业 --><?php echo $this->translate('industry');?></dt>
                        <dd class="fl dade">
                            <?php if($this->e['accountStatus']==01){echo $this->ShowDictionaryTo('datatest_setting',$this->userlangCode,$this->dic_Setting['ISIC_INDUSTRY_TYPE'],$this->e['industryCode']);}?>
                            <select name="industryCode"  <?php if($this->e['accountStatus']==01){echo 'style="display:none;"  name="industryCode"';}?> class="dq_select" id="industryCode" required data-msg-required="<?php echo $this->translate('de_null');?>">
                                <?php echo $this->ShowDictionaryList('datatest_setting',$this->userlangCode,$this->dic_Setting['ISIC_INDUSTRY_TYPE'],$this->e['industryCode']);?>
                            </select>
                        </dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 联系电话 --><?php echo $this->translate('comTEL');?></dt><dd class="fl tel"><input class="must" style="border: 1px solid #DF7E20;" type="text" value="<?php echo $this->e['phone'];?>" name="phone" id="phone" data-rule-phone="true" required data-msg-required="<?php echo $this->translate('de_null');?>" /></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 传真 --><?php echo $this->translate('comFOX');?></dt><dd class="fl fax"><input class="must" style="border: 1px solid #DF7E20;" type="text" value="<?php echo $this->e['fax'];?>" name="fax" id="fax" data-rule-fax="true" required data-msg-required="<?php echo $this->translate('de_null');?>" /></dd>
                    </dl>
                    <!-- E-mail -->
                    <dl class="fl">
                        <dt class="fl"><!-- E-mail --><?php echo $this->translate('company_email');?></dt><dd class="fl email"><input class="must" style="border: 1px solid #DF7E20;" type="text" value="<?php echo $this->e['email'];?>" name="email" id="email" data-rule-mail="email" required data-msg-required="<?php echo $this->translate('de_null');?>" /></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 网址 --><?php echo $this->translate('company_website');?></dt><dd class="fl net"><input type="text" value="<?php echo $this->e['website'];?>" name="website" /></dd>
                    </dl>

                    <div id="CNNO" <?php if($this->e['regdCountryCode']=='CN'){echo 'style="display:block;"';}else{echo 'style="display:none;"';}?>>

                    <dl class="fl">
                        <dt class="fl"><!-- 企业海关编码 --><?php echo $this->translate('ECC');?></dt><dd class="fl hgnum">
                            <input <?php if($this->e['accountStatus']==01){echo 'readonly="ture" style="background: #F5F5F5;border: none;"';} ?> type="text" value="<?php echo $this->e['customsCode'];?>" name="customsCode" /></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 统一社会信用代码 --><?php echo $this->translate('businessLicenseNo');?></dt><dd class="sb_num">
                            <input <?php if($this->e['accountStatus']==01){echo 'readonly="ture" style="background: #F5F5F5;border: none;"';} ?> type="text" value="<?php echo $this->e['businessLicenseNo'];?>" name="businessLicenseNo" /></dd>
                    </dl>
                    </div>
                </div>
            </div>
            <!-- 公司资料档案 -->
            <!-- 附件上传 -->
            <div class="yyzz_box info_cont pb20">
                <div class="zzname  n_o_c_tit"><h4><!-- 公司资料档案 --><?php echo $this->translate('company_profile');?></h4></div>
                <?php echo $this-> ShowWebuploader($this->attlist,$this->biz_Setting['CONTRACT'],$this->attach_Setting['000000'],"0");?>
            </div>
            <?php echo $this->render(SEED_WWW_TPL.'/btn_confirm.phtml');?>
        </form>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script src="/ky/js/jquery.validate.js"></script>
<script>
$(function(){
    $("#company_form").validate({
        submitHandler: function() {
            form.submit();
        }
    });
    $("#regdCountryCode").change(function () {
        var regd=$("#regdCountryCode").val();
        if(regd=="CN"){
           $("#CNNO").css("display","block");
        }else{
            $("#CNNO").css("display","none");
        }
    })
});
jQuery.validator.addMethod("mail", function (value, element) {
    var mail = /^[A-Za-z0-9._%-]+@([A-Za-z0-9-]+\.)+[A-Za-z]{2,4}$/;
    return this.optional(element) || (mail.test(value));
}, "<?php echo $this->translate('email').$this->translate('de_format');?>");
jQuery.validator.addMethod("phone", function (value, element) {
//    var phone = /^0\d{2,3}-\d{7,8}(-\d{1,6})?$/;
    var phone = /^[\d|\-|\+|\s]+$/;
    return this.optional(element) || (phone.test(value));
}, "<?php echo $this->translate('phone').$this->translate('de_format');?>");
jQuery.validator.addMethod("fax",function(value,element){
    var fax = /^[\d|\-|\+|\s]+$/;
    return this.optional(element) || (fax.test(value));
},"<?php echo $this->translate('fax').$this->translate('de_format');?>");
</script>
</body>
</html>
