<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>快移</title>

	<meta name="renderer" content="webkit">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <link href="/ky/css/authpage.css" rel="stylesheet">
	<link href="/ky/layui/css/layui.css" rel="stylesheet" media="all">

	<!-- company css -->
	<link href="/ky/css/company/company.css" rel="stylesheet">
	
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/layer/layer.js"></script>
	<script type="text/javascript" src="/ky/layui/layui.js"></script>
    <style type="text/css">
        #acEmail, #acLogin {
            width: 40px;
            height: 25px;
            line-height: 25px;
            color: #fff;
            text-align: center;
            margin: 0 10px;
            display: inline-block;
            background: #ff8c21;
            border-radius: 5px;
            border: 1px solid #de6e06;
        }
    </style>

</head>
<body>
<?php echo $this->render(SEED_WWW_TPL . '/header.phtml'); ?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL . '/left_menu.phtml'); ?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL . '/company/r_top_menu.phtml'); ?>
        <form id="imageform" method="post" enctype="multipart/form-data" action="../upload.php">

            <div class="info_cont clearfix">
                <div class="n_o_c_tit">
                    <h4><!--查看公司信息--><?php echo $this->translate('view') . $this->translate('companyINF'); ?><i
                                class="company_icon"></i><!--点击查看公司快移码--></h4>
                    <?php if ($this->CompAdmin == true): ?>
                        <a class="p_ed fr mt10 mr30" href="<?php echo WWW; ?>user/company/edit"></a>
                    <?php endif; ?>
                    <div class="company_box"><img
                                src="<?php echo WWWURL; ?>/qrcode?from=<?php echo base64_encode($this->e['accountName']); ?>"
                                style="width:100px;"></div>
                </div>
                <div class="o_c_content">
                    <?php if ($this->e['regdCountryCode'] == 'CN'): ?>
                        <dl class="fl">
                            <dt class="fl"><!-- 公司名称 --><?php echo $this->translate('comNAME'); ?></dt>
                            <dd class="company"><?php echo $this->e['accountName']; ?>
                                <a href="#">
                                    <?php if ($this->e['entRealAuthStatus'] == 0 || $this->e['entRealAuthStatus'] == -1): ?>
                                        <span id="company-auth" class="et-ico et-ico-auth-cno"></span>
                                    <?php elseif ($this->e['entRealAuthStatus'] == 1 || $this->e['entRealAuthStatus'] == 3 || $this->e['entRealAuthStatus'] == -2 || $this->e['entRealAuthStatus'] == -3): ?>
                                        <span id="company-auth" class="et-ico et-ico-auth-cing"></span>
                                    <?php elseif ($this->e['entRealAuthStatus'] == 2): ?>
                                        <span id="company-auth" class="et-ico et-ico-auth-cok"></span>
                                    <?php endif; ?>
                                </a>
                            </dd>
                        </dl>

                        <?php if ($this->e['accountEnName']): ?>
                            <dl class="fl">
                                <dt class="fl"><!-- 英文名称 --><?php echo $this->translate('enNAME'); ?></dt>
                                <dd class="eng_name"><?php echo $this->e['accountEnName']; ?></dd>
                            </dl>
                        <?php endif; ?>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!-- 地址 --><?php echo $this->translate('address'); ?></dt>
                            <dd class="address"><?php echo $this->ShowDictionaryTo($this->dic_Setting["COUNTRY_ISO_CODE"], $this->userlangCode, $this->dic_Setting["COUNTRY_ISO_CODE"], $this->e['regdCountryCode']) . "&nbsp;&nbsp;" . $this->regdCountryCode . $this->e['regdAddress']; ?></dd>
                        </dl>
                        <?php if ($this->e['regdEnAddress']): ?>
                            <dl class="fl" style="width:100%">
                            <dt class="fl" style="color: #f5f5f5;">
                                <!-- 地址 --><?php echo $this->translate('address'); ?></dt>
                            <dd class="address"><?php echo "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" . $this->e['regdEnAddress']; ?></dd>
                            </dl><?php endif; ?>
                    <?php else: ?>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!-- 公司名称 --><?php echo $this->translate('comNAME'); ?></dt>
                            <dd class="company"><?php echo $this->e['accountName']; ?></dd>
                        </dl>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!-- 地址 --><?php echo $this->translate('address'); ?></dt>
                            <dd class="address"><?php echo $this->ShowDictionaryTo($this->dic_Setting["COUNTRY_ISO_CODE"], $this->userlangCode, $this->dic_Setting["COUNTRY_ISO_CODE"], $this->e['regdCountryCode']) . "&nbsp;&nbsp;" . $this->regdCountryCode . $this->e['regdAddress']; ?></dd>
                        </dl>
                    <?php endif; ?>
                    <dl class="fl">
                        <dt class="fl"><!-- 语言 --><?php echo $this->translate('dLANG'); ?></dt>
                        <dd class="language"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['SYS_LANG'], $this->e['langCode']); ?></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 货币 --><?php echo $this->translate('defaultCCY'); ?></dt>
                        <dd class="fl doller"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['CURRENCY'], $this->e['crnCode']); ?></dd>
                    </dl>
                    <!-- 公司形式 -->
                    <dl class="fl">
                        <dt class="fl"><!-- 公司形式 --><?php echo $this->translate('comlegal'); ?></dt>
                        <dd class="fl dade"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['ACCOUNT_LEGALFORM'], $this->e['legalForm']); ?></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 成立日期 --><?php echo $this->translate('dateUP'); ?></dt>
                        <dd class="fl dade">
                            <?php if ($this->e['incorporationDate']) {
                                echo date('Y-m-d', strtotime($this->e['incorporationDate']));
                            } else {
                                echo null;
                            } ?>
                        </dd>
                    </dl>

                    <!-- 行业 -->
                    <dl class="fl" style="width:100%">
                        <dt class="fl"><!-- 行业 --><?php echo $this->translate('industry'); ?></dt>
                        <dd class="fl dade"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['ISIC_INDUSTRY_TYPE'], $this->e['industryCode']); ?></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 联系电话 --><?php echo $this->translate('comTEL'); ?></dt>
                        <dd class="fl tel"><?php echo $this->e['phone']; ?></dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 传真 --><?php echo $this->translate('comFOX'); ?></dt>
                        <dd class="fl fax"><?php echo $this->e['fax']; ?></dd>
                    </dl>
                    <!-- E-mail -->
                    <dl class="fl">
                        <dt class="fl"><!-- E-mail --><?php echo $this->translate('comEMAIL'); ?></dt>
                        <dd class="fl fax">
                            <?php echo $this->e['email']; ?>
                            <?php if ($this->CompAdmin == true): ?><a href="#"
                                                                      id="acEmail"><?php echo $this->translate('ACTcheck'); ?></a><?php endif; ?>
                        </dd>
                    </dl>
                    <dl class="fl">
                        <dt class="fl"><!-- 网址 --><?php echo $this->translate('comSITE'); ?></dt>
                        <dd class="fl net"><?php echo $this->e['website']; ?></dd>
                    </dl>
                    <?php if ($this->e['regdCountryCode'] == 'CN'): ?>

                        <dl class="fl">
                            <dt class="fl"><!-- 企业海关编码 --><?php echo $this->translate('ECC'); ?></dt>
                            <dd class="fl hgnum"><?php echo $this->e['customsCode']; ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!-- 统一社会信用代码 --><?php echo $this->translate('TINO'); ?></dt>
                            <dd class="sb_num"><?php echo $this->e['businessLicenseNo']; ?></dd>
                        </dl>

                    <?php endif; ?>
                </div>
            </div>
            <!-- 公司资料档案 -->
            <!-- 附件上传 -->
            <div class="yyzz_box info_cont pb20">
                <div class="zzname  n_o_c_tit"><h4><!-- 公司资料档案 --><?php echo $this->translate('MBLS'); ?></h4></div>
                <?php echo $this->ShowWebuploader($this->attlist, $this->biz_Setting['CONTRACT'], $this->attach_Setting['000000'], "1", $this->accountID); ?>
            </div>
        </form>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL . '/footer.phtml'); ?>

<div id="authViewDiv" class="layui-form" style="display: none;"></div>


<script type="application/javascript">
	layui.use('form', function(){
		var form = layui.form; //只有执行了这一步，部分表单元素才会自动修饰成功

		//……

		form.on('select(bankName)', function(data){
			var bankCode = data.value;
			var cityCode = $("#cityName").val();

			if (cityCode != '' && bankCode != '') {
				var fuzzyQuery = '/user/company/fuzzy';
				$.post(fuzzyQuery,
					{
						dataDictCode: 'ESIGN_SUBBRANCH_BANK',
						keyword: '',
						valuePCode: cityCode + ',' + bankCode
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						console.log(data);

						var optionstring = "";
						$.each(data, function (i, item) {
							optionstring += "<option value=\"" + item.valueCode + "\" >" + item.nameText + "</option>";
						});
						var str = '<?php echo $this->translate("et_select"); ?>';
						$("#subbranchName").html('<option value="">'+str+'</option>' + optionstring);
						form.render('select'); //这个很重要
					})
					.error(function () {
						console.log("network error");
					})
					.complete(function () {
						console.log("complete");
					});
			} else {
				var str = '<?php echo $this->translate("et_select"); ?>';
				$("#subbranchName").empty();
				$("#subbranchName").html('<option value="">'+str+'</option>');
				form.render('select');
			}
		});

		form.on('select(proviceName)', function(data){
			var proviceCode = data.value;
			if (proviceCode != '') {
				var fuzzyQuery = '/user/company/fuzzy';
				$.post(fuzzyQuery,
					{
						dataDictCode: 'ESIGN_CITY_CODE',
						keyword: '',
						valuePCode: proviceCode
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						console.log(data);

						var optionstring = "";
						$.each(data, function (i, item) {
							optionstring += "<option value=\"" + item.valueCode + "\" >" + item.nameText + "</option>";
						});
						$("#cityName").html('<option value=""></option>' + optionstring);
						form.render('select'); //这个很重要
					})
					.error(function () {
						console.log("network error");
					})
					.complete(function () {
						console.log("complete");
					});
			} else {
				$("#cityName").empty();
				$("#cityName").html('<option value=""></option>');
				form.render('select');
			}
		});

		form.on('select(cityName)', function(data){
			var bankCode = $("#bankName").val();
			var cityCode = data.value;
			
			if (cityCode != '' && bankCode != '') {
				var fuzzyQuery = '/user/company/fuzzy';
				$.post(fuzzyQuery,
					{
						dataDictCode: 'ESIGN_SUBBRANCH_BANK',
						keyword: '',
						valuePCode: cityCode + ',' + bankCode
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						console.log(data);

						var optionstring = "";
						$.each(data, function (i, item) {
							optionstring += "<option value=\"" + item.valueCode + "\" >" + item.nameText + "</option>";
						});
						var str = '<?php echo $this->translate("et_select"); ?>';
						$("#subbranchName").html('<option value="">'+str+'</option>' + optionstring);
						form.render('select'); //这个很重要
					})
					.error(function () {
						console.log("network error");
					})
					.complete(function () {
						console.log("complete");
					});
			} else {
				var str = '<?php echo $this->translate("et_select"); ?>';
				$("#subbranchName").empty();
				$("#subbranchName").html('<option value="">'+str+'</option>');
				form.render('select');
			}
		});

		//但是，如果你的HTML是动态生成的，自动渲染就会失效
		//因此你需要在相应的地方，执行下述方法来手动渲染，跟这类似的还有 element.init();
		form.render();
	});
	
	$(document).ready(function () {
        $('#acEmail').click(function () {
            //询问框
            layer.confirm('<?php echo $this->translate('is_email')?>', {
                title: false,
                btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
            }, function () {
                $.post('<?php echo $this->BaseUrl();?>/check/accountemailnotice',
                    function (data) {
                        layer.msg(data, {icon: 1});

                        location.href = '<?php echo $this->BaseUrl();?>/company/index';
                    }, "json");

            }, function () {
                layer.closeAll();
            });
        });

		$('#company-auth').click(function () {
			$("#authViewDiv").html("").load("<?php echo $this->BaseUrl();?>/company/authview", {
			
			}, function () {
				layer.closeAll();
				layer.open({
					type: 1,
					title: false,
					area: ['780px', '97%'],
					skin: 'layui-layer-rim',
					scrollbar: false,
					shade: 0.5,
					content: $("#authViewDiv")
				});

				var form = layui.form;
				form.render('select');
				
				// 认证基本信息
				$("#doAuthBtn").click(function () {
					var auth_name = $('input[name="auth_name"]').val();
					var auth_code = $('input[name="auth_code"]').val();
					var auth_mg_name = $('input[name="auth_mg_name"]').val();
					var auth_mg_id = $('input[name="auth_mg_id"]').val();

					var auth_error = $('#authViewDiv_').find('.et-auth-error');
					if (auth_name == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (auth_code == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (auth_mg_name == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (auth_mg_id == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					}

					$("#doAuthBtn").attr("disabled", true);
					var companyDO = '/user/company/doauth';
					$.post(companyDO,
					{
						auth_name: auth_name,
						auth_code: auth_code,
						auth_mg_name: auth_mg_name,
						auth_mg_id: auth_mg_id
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						if (data == '0') {
							auth_error.hide();
							layer.closeAll();

							setTimeout(function(){
								$("#company-auth").removeClass("et-ico-auth-cno").addClass("et-ico-auth-cing").trigger("click");
							}, 500);
						} else {
							auth_error.html("");
							auth_error.html(data);
							auth_error.show();
						}

						$("#doAuthBtn").attr("disabled", false);
					})
					.error(function () {
						console.log("network error");
						var tips = "<?php echo $this->translate('et_tips04');?>";
						auth_error.html("");
						auth_error.html(tips);
						auth_error.show();

						$("#doAuthBtn").attr("disabled", false);
					});
				});

				// 认证银行信息
				$('#doAuthPayBtn').click(function () {
					var acctName = $("#acctName").val();
					var auth_acctNo = $("#auth_acctNo").val();
					var bankName = $("#bankName").val();
					var proviceName = $("#proviceName").val();
					var cityName = $("#cityName").val();
					var subbranchName = $("#subbranchName").val();

					var auth_error = $('#authViewDiv_').find('.et-auth-error');
					if (auth_acctNo == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (bankName == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (proviceName == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (cityName == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					} else if (subbranchName == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					}

					$("#doAuthPayBtn").attr("disabled", true);
					var companyDoAuthPay = '/user/company/doauthpay';
					$.post(companyDoAuthPay,
					{
						acctName: acctName,
						auth_acctNo: auth_acctNo,
						bankName: bankName,
						proviceName: proviceName,
						cityName: cityName,
						subbranchName: subbranchName
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						if (data == '0') {
							auth_error.hide();
							layer.closeAll();

							setTimeout(function(){
								$("#company-auth").trigger("click");
							}, 500);
						} else {
							auth_error.html("");
							auth_error.html(data);
							auth_error.show();
						}
						$("#doAuthPayBtn").attr("disabled", false);
					})
					.error(function () {
						console.log("network error");
						var tips = "<?php echo $this->translate('et_tips04');?>";
						auth_error.html("");
						auth_error.html(tips);
						auth_error.show();

						$("#doAuthPayBtn").attr("disabled", false);
					});
				});

				// 验证码
				$('#doAuthConfirmBtn').click(function () {
					var authVerifyAmount = $("#authVerifyAmount").val();

					var auth_error = $('#authViewDiv_').find('.et-auth-error');
					if (authVerifyAmount == '') {
						auth_error.html("");
						auth_error.html('<?php echo $this->translate('et_tips03');?>');
						auth_error.show();
						return false;
					}

					$("#doAuthConfirmBtn").attr("disabled", true);
					var companyDoAuthPay = '/user/company/authconfirm';
					$.post(companyDoAuthPay,
					{
						authVerifyAmount: authVerifyAmount
					},
					function (data) {
					}, 'json')
					.success(function (data) {
						if (data == '0') {
							auth_error.hide();
							layer.closeAll();
							setTimeout(function(){
								$("#company-auth").removeClass("et-ico-auth-cno et-ico-auth-cing").addClass("et-ico-auth-cok").trigger("click");
							}, 500);
						} else {
							auth_error.html("");
							auth_error.html(data);
							auth_error.show();
						}
						$("#doAuthConfirmBtn").attr("disabled", false);
					})
					.error(function () {
						console.log("network error");
						var tips = "<?php echo $this->translate('et_tips04');?>";
						auth_error.html("");
						auth_error.html(tips);
						auth_error.show();
						$("#doAuthConfirmBtn").attr("disabled", form);
					});
				});
			});
		});
    });
</script>

</body>

</html>