<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <!--<ul class="nav nav-pills nav-stacked">
     p-                 <li role="presentation" class="active"><a href="#">Home</a></li>
                        <li role="presentation"><a href="#">Profile</a></li>
                        <li role="presentation"><a href="#">Messages</a></li>
                    </ul>-->
                    <div class="list-group">
                        <a href="#" class="list-group-item">
                            Cras justo odio
                        </a>
                        <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                        <a href="#" class="list-group-item">Morbi leo risus</a>
                        <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                        <a href="#" class="list-group-item">Vestibulum at eros</a>
                    </div>
                </div>

            </div>
            <div class="col-md-9 company-main">
                <div class="page-header">
                    <h1><?php echo $this->translate('companyINF'); ?> <small>Subtext for header</small></h1>
                </div>

                <div class="panel panel-default">
                    <div class="panel-heading">Panel heading without title</div>
                    <div class="panel-body">
                        Panel content
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});
</script>
</body>
</html>
