<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('etradefast'); ?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
       <div class="u_info_ed_box">
           <form action="#" method="post">
                <h3 class="clearfix">用户资料编辑<input class="sub_btn fr" type="submit" value="确定" /> <input class="info_edit fr" type="button" value="编辑" /></h3>
               <div class="infobox infobox1">
                    <h4>基本资料</h4>
                   <div>
                       <label class="labelbox">姓名:</label>
                       <input type="text" name="name" id="name" value="李杰" tabindex="1" />
                       <label class="help_info">{*必填，请填写详细姓名}</label>
                   </div>
                   <div>
                       <label class="labelbox">称谓:</label>
                       <label class="name_label">MayYung</label>
                   </div>
                   <div>
                       <label class="labelbox">公司职务:</label>
                       <input type="text" name="user_zw" id="user_zw" value="" tabindex="1" />
                       <label class="help_info">{*经理，主任等}</label>
                   </div>
                   <div>
                       <label class="labelbox">部门:</label>
                       <input type="text" name="user_bm" id="user_bm" value="" tabindex="1" />
                       <label class="help_info">{*业务部，项目部等}</label>
                   </div>
                   <div>
                       <label class="labelbox">平台用户:</label>
                       <input class="u_radio" type="radio" name="checked1" value="yes" checked>是
                       <input class="u_radio" type="radio" name="checked1" value="no">否
                   </div>
                   <div>
                       <label class="labelbox">用户角色:</label>
                       <input type="text" name="user_js" id="user_js" value="" tabindex="1" />
                       <label class="help_info">{*跟单员，业务员等}</label>
                   </div>
               </div>
               <div class="infobox infobox2">
                    <h4>通讯资料</h4>
                   <div>
                       <label class="labelbox">固定电话:</label>
                       <input type="text" name="phonenum" id="phonenum" value="" tabindex="1" />
                       <label class="help_info">{请填写单位联系电话}</label>
                   </div>
                   <div>
                       <label class="labelbox">移动电话:</label>
                       <input type="text" name="telphonenum" id="telphonenum" value="" tabindex="1" />
                       <label class="help_info">{请填写个人移动电话}</label>
                   </div>
                   <div>
                       <label class="labelbox">电子邮箱:</label>
                       <input type="text" name="email" id="email" value="" tabindex="1" />
                       <label class="help_info">{请填写游戏邮箱}</label>
                   </div>
                   <div>
                       <label class="labelbox">传真:</label>
                       <input type="text" name="user_cz" id="user_cz" value="" tabindex="1" />
                       <label class="help_info">{如无传真设备请留空}</label>
                   </div>
               </div>
               <div class="infobox infobox3">
                    <h4>邮寄地址</h4>
                   <div>
                       <label class="labelbox">国家/地区:</label>
                       <select class="dq_select">
                         <option>四川省</option>
                         <option>广东省</option>
                       </select>
                       <label class="help_info">{如中国、美国、内蒙古自治区}</label>
                   </div>
                   <div>
                       <label class="labelbox">省份:</label>
                       <select class="dq_select">
                         <option>四川省</option>
                         <option>广东省</option>
                       </select>
                       <label class="help_info">{所属省份，如广东省、福建省}</label>
                   </div>
                   <div>
                       <label class="labelbox">城市:</label>
                       <select class="dq_select">
                         <option>四川省</option>
                         <option>广东省</option>
                       </select>
                       <label class="help_info">{所属城市、区、镇}</label>
                   </div>
                   <div>
                       <label class="labelbox">街道:</label>
                       <input type="text" name="user_street" id="user_street" value="" tabindex="1" />
                   </div>
                   <div>
                       <label class="labelbox">邮政编码:</label>
                       <input type="text" name="user_postcode" id="user_postcode" value="" tabindex="1" />
                       <label class="help_info">{所属地区邮政编码，如2010100}</label>
                   </div>
               </div>
           </form>
       </div>           
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>
