<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('etradefast'); ?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
       <div class="peo_info_tit clearfix">
           <h4 class="fl">联系人详细信息</h4>
           <div class="man_info_btn_box fr">
               <a class="sure" href="javascript:;">确认</a>
               <a class="cancel" href="javascript:;">取消</a>
           </div>
       </div> 
        <div class="info_cont info_cont3 clearfix">
            <dl>
                <dt class="fl">姓名:</dt><dd class="fl gsreg_num">李四</dd>
            </dl>
            <dl>
                <dt class="fl">客户:</dt><dd class="fl hgnum">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">职务:</dt><dd class="sb_num">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">电子邮件:</dt><dd class="fl tel">浙江温州江南皮革厂</dd>
            </dl>
            <dl>
                <dt class="fl">电话:</dt><dd class="gsreg_num">李四</dd>
            </dl>
            <dl>
                <dt class="fl">手机:</dt><dd class="fl hgnum">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">所有人:</dt><dd class="sb_num">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">直属上司:</dt><dd class="fl tel">浙江温州江南皮革厂</dd>
            </dl>
            <dl>
                <dt class="fl">部门:</dt><dd class="gsreg_num">李四</dd>
            </dl>
            <dl>
                <dt class="fl">上次联系保存日期:</dt><dd class="fl hgnum">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">传真:</dt><dd class="sb_num">15245212165</dd>
            </dl>
            <dl>
                <dt class="fl">邮件地址:</dt><dd class="fl tel">浙江温州江南皮革厂</dd>
            </dl>
            <dl>
                <dt class="fl">其他地址:</dt><dd class="fl tel">浙江温州江南皮革厂</dd>
            </dl>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>
