<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
//删除
function deleteAll(){
	var ids="";
    $("[name='chose[]'][checked]").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->BaseUrl();?>/usertype/delete?type_ids="+ids;
}

function doOrder(){
    $("#post_form").validate({
       event: "keyup",
       rules: {},
       messages: {},
       submitHandler: function() {
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/usertype/order',
                success: function() {
                }
            };
            $('#post_form').ajaxSubmit(options);
        }
    });
}

</script>
<h1>会员等级管理</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="location.href='<?php echo $this->BaseUrl();?>/usertype/add/'"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
      <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
        <label for="checkAll">全选</label></th>
      <th>类型名</th>
      <th>消费金额</th>
      <th>折扣值</th>
      <th>折扣类型</th>
      <th>排序</th>
      <th>操作</th>
    </tr>
    <?php if(is_array($this->usertypes)):?>
    <?php foreach($this->usertypes as $usertype):?>
    <tr>
      <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($usertype['type_id'])?>" class="ids_all"></td>
      <td><?php echo ($usertype['type_name']);?></td>
      <td><?php echo ($usertype['user_integral']);?></td>
      <td><?php echo ($usertype['main_discount']);?></td>
      <td><?php echo ($usertype['main_discount_type']==1?'百分比':'直减');?></td>
      <td><input type="hidden" name="type_ids[]" value="<?php echo ($usertype['type_id'])?>">
        <input type="text" value="<?php echo ($usertype['order_by']);?>" name="order_bys[]" style="width:30px;"></td>
      <td><a href="<?php echo $this->BaseUrl();?>/usertype/update/type_id/<?php echo ($usertype['type_id']);?>"><img src="/images/center/edit.gif" title="编辑资料" alt="编辑资料"></a>
      <a href="<?php echo $this->BaseUrl();?>/usertype/delete/type_ids/<?php echo ($usertype['type_id']);?>"><img src="/images/center/del.gif" title="删除" alt="删除"/></a>
      </td>
    </tr>
    <?php endforeach; ?>
    <?php endif;?>
  </table>
  <div class="batch">
      <input class="admin_bnt2" type="submit" name="orderID" id="orderID" value="重新排序" onclick="doOrder()">
    &nbsp;
    <input class="admin_bnt2" type="button" name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
    &nbsp; 
 </div>
</form>
<?php echo $this->render("footer.phtml") ?>
