<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/swiper-3.3.1.min.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/swiper-3.3.1.jquery.min.js"></script>
<script type="text/javascript" src="/js/center/seed.form.js"></script>
<script type="text/javascript" src="/js/center/jquery.form.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<!--//<script type="text/javascript" src="/js/tips.js"></script>-->
<style type="text/css">
.error{margin:0;font-size: 14px;height: 30px;}
</style>

</head>
<body style="overflow-x:hidden;overflow-y:hidden">
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
    <div class="content">
        <div class="logindiv" style="">
    	<form action="<?php echo $this->baseUrl();?>/login" method="post" name="login_form" id="login_form">
            <div class="login_box fr tc">
                    <label class="lagin_lab1 mt50"><?php echo $this->translate('username');?></label>
                <p class="tl f20">
                    <i class="user_icon"></i><input value="<?php echo $this->rememberName;?>" class="login_txt1" name="ecommloginname" id="ecommloginname" type="text" data-rule-mail="true" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('tip_login_name');?>" /><!--请输入用户名-->
                </p>
                    <label class="lagin_lab1"><?php echo $this->translate('password');?></label>
                <p class="tl f20">
                    <i class="pw_icon"></i><input class="login_txt1" name="ecommpasswsd" id="ecommpasswsd" type="password" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('is_passwd');?>" /><!--请提供8-30位数字、大小写字母-->
                </p>
                <?php if($this->is_code=='1'):?>
                    <label class="lagin_lab1"><?php echo $this->translate('codes');?></label>
                    <p class="tl f20">
                        <input style=" width: 120px;float: left;" class="login_txt1" name="vcode" id="vcode" type="text" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('tip_code');?>" /><!--请输入验证码-->
                        <img style="width: 120px;float: left;margin-left: 5px;padding: 3px 0;" id="checkpic" onclick="changing();" src='/user/check/code' />
                    </p>
                <?php endif;?>
                <p class="tc f16">
                    <label>
						<input <?php if(!empty($this->rememberName)){echo 'checked="checked"';}?> type="checkbox" name="remember" value="1"><?php echo $this->translate('tip_remember');?>
					</label>
                    <a class="ml50" href="./forget"><?php echo $this->translate('forgetPSD');?>?</a>
                    <a class="ml20" href="./register"><?php echo $this->translate('userRegister');?></a>
                </p>
                <input class="login_bnt2" name="" type="submit" value="<?php echo $this->translate('login');?>" onclick="doLogin()"/><!--登录 LOGIN-->
            </div></form>
        </div>
    </div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?><script src="/ky/js/jquery.validate.js"></script>
<script type="text/javascript">
	function doLogin(){
		$("#login_form").validate({
			event: "keyup",
			rules: {},
			messages: {},
			submitHandler: function(form) {
				form.submit();
			}
		});
	}
	
	function changing() {
		document.getElementById('checkpic').src = "/user/check/code?" + Math.random();
	}

	$(function () {
	
	});
	jQuery.validator.addMethod("mail", function (value, element) {
		var mail = /^[a-zA-Z0-9._%-]+@([a-zA-Z0-9-]+\.)+[a-z]{2,4}$/;
		return this.optional(element) || (mail.test(value));
	}, "<?php echo $this->translate('email') . $this->translate('de_format');?>");
</script>
</body>
</html>
