<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移11</title>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="javascript:void(0)">
				<img alt="eTradeFast" src="/ky/images/logo.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎登录
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid index-body">
	<div class="container">
		
		<div class="row">

			<div class="col-md-8 hidden-xs">
				<div class="row body-font">
					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
						快移平台
					</div>
					<div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 col-md-offset-5">
						让交易更公平
					</div>
					<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-md-offset-7">
						更快捷
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-md-offset-8">
						更有保障
					</div>
				</div>
			</div>
			
			<div class="col-md-4 login-body">
				<ul class="nav nav-pills">
					<li><a href="javascript:void(0)">密码登录</a></li>
					<li><a href="javascript:void(0)">扫描登录</a></li>
				</ul>
				
				<hr>
				<form class="form-horizontal login-body-form" action="<?php echo $this->baseUrl();?>/login" method="post" id="login_form">
					<div class="form-group">
						<label class="sr-only" for="ecommloginname"></label>
						<div class="input-group">
							<div class="input-group-addon">
								<span class="glyphicon glyphicon-user" aria-hidden="true" style="color: #777"></span>
							</div>
							<input type="email" class="form-control" name="ecommloginname" id="ecommloginname" required placeholder="用户名/电子邮箱">
						</div>
					</div>

					<div class="form-group">
						<label class="sr-only" for="ecommpasswsd"></label>
						<div class="input-group">
							<div class="input-group-addon">
								<span class="glyphicon glyphicon-lock" aria-hidden="true" style="color: #777"></span>
							</div>
							<input type="password" class="form-control" name="ecommpasswsd" id="ecommpasswsd" required placeholder="登录密码">
						</div>
					</div>

					<div class="form-group">
						<div class="pull-right">
							<a href="./forget"><?php echo $this->translate('forgetPSD'); ?></a>
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('login'); ?></button>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-4 col-sm-4">
							<div class="text-center">
								<!--<div style="background-color: #f0ad4e; float: left;"><i class="far fa-user-circle"></i></div>-->
								<a href="./register"><i class="far fa-user-circle" style="color: #f0ad4e;"></i>&nbsp;<?php echo $this->translate('userRegister'); ?></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<footer class="footer-body">
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 hidden-xs">
				<h4>关于我们</h4>
				<p>提供营运资本咨询服务和更灵活的解决方案，改进营运资金成本和更好管理贸易风险。</p>
				<p>创新供应链金融服务模式：快移金融创始者及践行者。</p>
				<p>IFG的成员，充分利用全球经验，助中国的贸易合作伙伴，以加快国际化。</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<h4>联系我们</h4>
				<p>深圳市骏海威科技网络控股有限公司</p>
				<p><i class="fas fa-map-marker-alt" style="color: #f0ad4e;"></i> 深圳市罗湖区嘉宾路深化商业大厦1502</p>
				<p><i class="fas fa-phone-square" style="color: #f0ad4e;"></i> +86-755-82383762</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
				<img src="/ky/images/Email-index.png" class="img-responsive" alt="E-Mail">
				<img src="/ky/images/wechat.png" class="img-responsive" alt="WeChat">
				<img src="/ky/images/linkedIn.png" class="img-responsive" alt="LinkedIn">
			</div>
		</div>
		<hr>
		<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
				<p>Copyright © 2015-2017 快移交易 eTradeFast 版权所有</p>
				<p>粤ICP备17023256号-1</p>
			</div>
			<div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
				<div class="pull-right">
					language
				</div>
			</div>
			
		</div>
	</div>
</footer>

<!-- Optional JavaScript -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="/ky/js/jquery.validate.min.js"></script>
<script type="text/javascript">
	$().ready(function() {
		$("#login_form").validate({
			rules: {
				ecommpasswsd: {
					isValidPassword: true,
					minlength: 8,
					maxlength: 30
				}
			},
			messages: {
				ecommloginname: "<?php echo $this->translate('is_emails');?>",
				ecommpasswsd : {
					minlength: "<?php echo $this->translate('mat_psd');?>",
					maxlength: "<?php echo $this->translate('is_passwd');?>"
				}
			},
			errorPlacement: function(error, element) {
				// Append error within linked label
				$(element)
					.closest( "form" )
					.find( "label[for='" + element.attr( "id" ) + "']" )
					.parent().addClass("has-error").removeClass("has-success")
					.append( error );
			},
			success: function(label) {
				$(label)
					.parent().addClass("has-success").removeClass("has-error");
			},
			// rules: {},
			// messages: {},
			submitHandler: function (form) {
				form.submit();
			}
		});
	});

	function changing() {
		document.getElementById('checkpic').src = "/user/check/code?" + Math.random();
	}

	$(function () {

	});

	// 邮政编码验证
	jQuery.validator.addMethod("isValidPassword", function(value, element) {
		var regExp=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,30}$/;
		return this.optional(element) || (regExp.test(value));
	}, "<?php echo $this->translate('is_passwd');?>");
</script>
</body>
</html>
