<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/index/index.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="javascript:void(0)">
				<img alt="eTradeFast" src="/ky/images/logo.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎登录
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid index-body">
	<div class="container">
		
		<div class="row">

			<div class="col-md-8 hidden-xs">
				<div class="row body-font">
					<div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
						快移平台
					</div>
					<div class="col-xs-7 col-sm-7 col-md-7 col-lg-7 col-md-offset-5">
						让交易更公平
					</div>
					<div class="col-xs-5 col-sm-5 col-md-5 col-lg-5 col-md-offset-7">
						更快捷
					</div>
					<div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-md-offset-8">
						更有保障
					</div>
				</div>
			</div>
			
			<div class="col-md-4 login-body">
				<ul class="nav nav-pills">
					<li><a href="javascript:void(0)">密码登录</a></li>
					<li><a href="javascript:void(0)">扫描登录</a></li>
				</ul>
				
				<hr>
				<form class="form-horizontal login-body-form" action="<?php echo $this->baseUrl();?>/login" method="post" id="login_form">
					<div class="form-group">
						<label for="inputEmail3" class="col-sm-2 control-label">Email</label>
						<div class="col-sm-10">
							<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
						</div>
					</div>

					<div class="form-group">
						<label for="inputPassword3" class="col-sm-2 control-label">Password</label>
						<div class="col-sm-10">
							<input type="password" class="form-control" id="inputPassword3" placeholder="Password">
						</div>
					</div>

					<div class="form-group">
						<div class="pull-right">
							<a href="./forget"><?php echo $this->translate('forgetPSD'); ?></a>
						</div>
					</div>

					<div class="form-group">
						<button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('login'); ?></button>
					</div>

					<div class="form-group">
						<div class="col-sm-offset-4 col-sm-4">
							<div class="text-center">
								<!--<div style="background-color: #f0ad4e; float: left;"><i class="far fa-user-circle"></i></div>-->
								<a href="./register"><i class="far fa-user-circle" style="color: #f0ad4e;"></i>&nbsp;<?php echo $this->translate('userRegister'); ?></a>
							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>
<script type="text/javascript">
	$().ready(function() {
		$("#login_form").validate({
			rules: {
				ecommpasswsd: {
					isValidPassword: true,
					minlength: 8,
					maxlength: 30
				}
			},
			messages: {
				ecommloginname: "<?php echo $this->translate('is_emails');?>",
				ecommpasswsd : {
					required: "<?php echo $this->translate('de_null'); ?>",
					minlength: "<?php echo $this->translate('mat_psd');?>",
					maxlength: "<?php echo $this->translate('is_passwd');?>"
				}
			},
			errorPlacement: function(error, element) {
				// Append error within linked label
				$(element)
					.closest( "form" )
					.find( "label[for='" + element.attr( "id" ) + "']" )
					.parent().addClass("has-error").removeClass("has-success")
					.append( error );
			},
			success: function(label) {
				$(label)
					.parent().addClass("has-success").removeClass("has-error");
			},
			// rules: {},
			// messages: {},
			submitHandler: function (form) {
				form.submit();
			}
		});
	});

	function changing() {
		document.getElementById('checkpic').src = "/user/check/code?" + Math.random();
	}

	$(function () {

	});

	// 邮政编码验证
	jQuery.validator.addMethod("isValidPassword", function(value, element) {
		var regExp=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,30}$/;
		return this.optional(element) || (regExp.test(value));
	}, "<?php echo $this->translate('is_passwd');?>");
</script>
</body>
</html>
