<?php echo $this->render('header.phtml'); ?>
<script type="text/javascript">
$().ready(function() {
    $("#post_form").validate({
       event: "keyup",
       rules: {},
	   messages: {},
       submitHandler: function() {
	   		var oEditor = FCKeditorAPI.GetInstance('branch_m_content').GetXHTML(true);
			$('#branch_m_content').val(oEditor);
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/branch/add',
                success: function() {
                }
            };
            $('#post_form').ajaxSubmit(options);
        }
    });
});
</script>

<h1>添加网点</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_form">
    <tr>
      <td><strong>网点分区：</strong>
			<p>
			<select name="branch_region" id="branch_region">
				  <option value="0"></option>
				  <?php if(is_array($this->regionoptions)):?>
				  <?php foreach($this->regionoptions as $key => $region):?>
				  <option value="<?php echo $region['br_id'];?>"><?php echo $region['br_name'];?></option>
				  <?php endforeach;?>
				  <?php endif;?>
				</select>
			</p></td>
    </tr>
    <tr>
      <td><strong>网点名称：</strong>
				<p><input class="admin_txt1" name="branch_name" id="branch_name" type="text" /></p></td>
    </tr>
    <tr>
      <td><strong>保存文件名(留空则自动为添加时间)：</strong>
		        <p>
		        	<input name="branch_mark" id="branch_mark" value="" type="text" class="admin_txt1"/>
		        </p></td>
    </tr>
    <tr>
      <td><strong>网点图标：</strong>
				<p>
		        	<input name="branch_m_image" id="branch_m_image" readonly value="" type="text" class="admin_txt1"/>
		        	<input type="button" name="select" value="选择" class="admin_bnt2" onclick="selectCoverImage('branchthumb_vhome','branch_m_image')">		        	
		        	<input type="button" name="preview_branch_m_image" id="preview_branch_m_image" value="预览" class="admin_bnt2" onclick="previewCoverImage('branch_m_image')" style="display:none;">
		        </p></td>
    </tr>
    <tr>
      <td><strong>网点电话：</strong>
				<p><input class="admin_txt1" name="branch_telephone" id="branch_telephone" type="text" /></p></td>
    </tr>
    <tr>
      <td><strong>网点地址：</strong>
				<p><input class="admin_txt1" name="branch_address" id="branch_address" type="text" /></p></td>
    </tr>
      <tr>
          <td><strong>经度:</strong>
              <p><input type="text" class="admin_txt1" value="" name="location_y" id="location_y" /></p>
          </td>
      </tr>
      <tr>
          <td><strong>纬度:</strong>
              <p><input type="text" class="admin_txt1" value="" name="location_x" id="location_x" /></p>
          </td>
      </tr>
    <tr>
    	<td>
		<?php echo include("baidupoint.phtml");?>
    	</td>
    </tr>
    <tr>
      <td><strong>营业时间：</strong>
				<p><input class="admin_txt1" name="branch_time" id="branch_time" type="text" /></p></td>
    </tr>
    <tr>
      <td><strong>网点描述：</strong>
		        <p><textarea class="textarea" name="branch_m_desc" id="branch_m_desc"></textarea></p></td>
    </tr>
    <tr>
      <td><strong>网点介绍：</strong>
		        <p>
					<?php 
						$editor = new FCKeditor('branch_m_content') ;
						$editor->ToolbarSet = 'Default';
						$editor->ImageCate = 'branch';
						$editor->BasePath = '/js/FCKeditor/';
						$editor->Width = 950;
						$editor->Height = 700;
						$editor->Create();
					?>
		        </p></td>
    </tr>
    <tr>
      <td><strong>网点排序：</strong>
				<p><input class="admin_txt1" name="order_by" id="order_by" type="text" /></p></td>
    </tr>
    <tr>
      <td><strong>显示状态：</strong>（打勾表示前台显示，否则不显示）
			<p>
			<input name="is_m_actived" type="checkbox" id="is_m_actived" value="1" /><label for="is_m_actived">显示</label>
			</p></td>
    </tr>
  </table>
  <table class="admin_form">
    <tr>      <td><input class="admin_bnt"  type="submit" value="提交"/></td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>