<?php echo $this->render('header.phtml');?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/branch/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>

<h1>删除网点</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
      <th>编号</th>
      <th>网点名称</th>
    </tr>
    <?php if(is_array($this->branchs)):?>
	<?php foreach($this->branchs as $branch):?>
	<tr>
		<td><input type="checkbox" id="branch_id<?php echo $this->escape($branch['branch_id'])?>" name="branch_id[]" checked value="<?php echo $this->escape($branch['branch_id'])?>"></td>
		<td><?php echo $this->escape($branch['branch_name'])?></td>
	</tr>
	<?php endforeach; ?>
	<?php endif;?>
  </table>
  <div class="batch">
    <input class="admin_bnt2" type="submit" name="" value="确认删除">
  </div>
</form>
<?php echo $this->render("footer.phtml") ?>