<?php echo $this->render('header.phtml'); ?>
<script type="text/javascript">
$().ready(function() {
	$('input[@type=checkbox][@name=checkAll]').each(function(){
		$(this).checkbox().toggle($(this).val());
	});
});

//删除
function deleteAll(){
	var ids="";
    $("[name='chose[]'][checked]").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->BaseUrl();?>/branch/delete?branch_ids="+ids;
}
function doOrder(){
    $("#order_form").validate({
       event: "keyup",
       rules: {},
       messages: {},
       submitHandler: function() {
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/branch/order',
                success: function() {
                }
            };
            $('#order_form').ajaxSubmit(options);
        }
    });
}
</script>

<h1> 案例管理 </h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/branch/add/'"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
		<th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选"><label for="checkAll">全选</label></th>
		<th>分区</th>
		<th>名称</th>
      	<th>排序</th>
		<th>显示</th>
		<th>操作</th>
	</tr>
	<?php if(is_array($this->branchs)):?>
    <?php foreach($this->branchs as $branch):?>
	<tr>
		<td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo $this->escape($branch['branch_id'])?>" class="ids_all"></td>
		<td><?php echo $this->escape($branch['br_name']);?></td>
		<td><a href="<?php echo $this->seed_Setting['www_app_server'];?>/branch/<?php echo $this->escape($branch['branch_mark'])?>.html" target="_blank"><?php echo $this->escape($branch['branch_name']);?></a></td>
      	<td><input type="hidden" name="branch_ids[]" value="<?php echo $this->escape($branch['branch_id'])?>"><input type="text" value="<?php echo $this->escape($branch['order_by']);?>" name="order_bys[]" style="width:30px;"></td>
		<td><?php echo $this->escape($branch['is_m_actived']) == 0 ? "<img src='/images/center/no.gif'/>" : "<img src='/images/center/yes.gif'/>"?></td>
		<td>
			<a href="<?php echo $this->BaseUrl();?>/branch/update?branch_id=<?php echo $this->escape($branch['branch_id']);?>"><img src="/images/center/edit.gif" title="编辑" alt="编辑"></a>
		</td>
	</tr>
	<?php endforeach;?>
	<?php endif;?>
  </table>
  <div class="batch">
    <input class="admin_bnt2" type="submit" name="orderID" id="orderID" value="重新排序" onclick="doOrder()">
    &nbsp;
    <input class="admin_bnt2" type="button" name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
    &nbsp </div>
</form>
<!--分页结束-->
<?php echo $this->render("footer.phtml") ?>