<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>企业电商运营平台登录1</title>
<link rel="stylesheet" type="text/css" href="/css/center/login.css" />
<script type="text/javascript" src="/js/center/jquery.js"></script>
<script type="text/javascript" src="/js/center/admin.js"></script>
</head>
<body>
<?php
//增加版号的显示
$versionfile = SEED_CONF_ROOT."/version.php";
if(file_exists($versionfile)){
    require_once($versionfile);
}
?>
<div id="bodybg">
<div class="logo"><img src="/images/center/logo.png" /><?php if(defined('SEED_VERSION')):?><br>系统版本：<?php echo SEED_VERSION;?><?php endif;?></div>
  <div class="loginfrom">
    <form method="post" name="f" id="f">
      <p><strong>用户名:</strong><small><span class="add_icon1">
        <input class="text1" name="username" type="text" id="username" />
        </span></small></p>
      <p><strong>密&nbsp;&nbsp;码:</strong><small><span class="add_icon2">
        <input class="text1" name="password" type="password" id="password" />
      </span></small></p>
      <p><strong>验证码:</strong><small><span class="add_icon3">
      <input class="text2" name="vcode" onkeypress="dosubmit(event)" type="text" id="vcode" />
      </span><img src="<?php echo $this->BaseUrl();?>/vcode"  alt="点击刷新" onclick="this.src='<?php echo $this->BaseUrl();?>/vcode?&ref='+Math.random()" /></small></p>
      <p><small>
        <input class="login_bnt" name="" type="submit" value="登 录"/>
      </small>
      </p>
     <?php echo (!empty($this->message))?"<p><span style='color:#ff0000;'>&nbsp;".$this->escape($this->message)."</span></p>":"";?>
      
    </form>
  </div>
</div>
<script type="text/javascript">
function dosubmit(e){
  try{var keyCode = e.keyCode?e.keyCode:(e.which?e.which:e.charCode);if(keyCode == 13)document.getElementById('f').submit();}catch(e){}
}
</script>
</body>
</html>