<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>企业电商运营平台登录</title>
    <link rel="stylesheet" type="text/css" href="/css/center/login.css"/>
    <script type="text/javascript" src="/js/center/jquery.js"></script>
    <script type="text/javascript" src="/js/center/admin.js"></script>

    <style>
        video{
            position: fixed;
            right:0;
            bottom: 0;
            min-width: 100%;
            min-height: 100%;
            width: auto;
            height: auto;
            z-index: -9999;
            /*灰色调*/
            /*-webkit-filter:grayscale(100%)*/
        }
    </style>
</head>
<body>
<?php
//增加版号的显示
$versionfile = SEED_CONF_ROOT . "/version.php";
if (file_exists($versionfile)) {
    require_once($versionfile);
}
?>

<video id="v1" autoplay muted loop style="width: 100%">
    <source  src="/ky/video/Pexels_0621.mp4">
</video>

<div id="bodybg">
    <!--
    <div class="logo">
        <img src="/images/center/logo.png"/>
        <?php /*if (defined('SEED_VERSION')): */?>
            <br>系统版本：<?php /*echo SEED_VERSION; */?>
        <?php /*endif; */?>
    </div>
-->
    <div class="loginfrom">
        <form method="post" name="f" id="f" onsubmit="doSubmit(event)">
            <p>
                <strong>用户名:</strong>
                <small>
                    <span class="add_icon1">
                        <input class="text1" name="username" type="text" id="username"/>
                    </span>
                </small>
            </p>
            <p>
                <strong>密&nbsp;&nbsp;码:</strong>
                <small>
                    <span class="add_icon2">
                        <input class="text1" name="password" type="password" id="password"/>
                    </span>
                </small>
            </p>

            <p>
                <small>
                    <input class="login_bnt" name="" type="submit" value="登 录"/>
                </small>
            </p>
            <?php echo (!empty($this->message)) ? "<p><span style='color:#ff0000;'>&nbsp;" . $this->escape($this->message) . "</span></p>" : ""; ?>
        </form>
    </div>
</div>

<script type="text/javascript" src="/ky/js/jquery.cookie.js"></script>
<script type="text/javascript">
    $().ready(function () {
        if ($.cookie("adminAutoUser") === "true") {
            $("#username").val($.cookie("adminUsername"));
            $("#password").val($.cookie("adminPassword"));
        }
    });

    function doSubmit() {
        var str_username = $("#username").val();
        var str_password = $("#password").val();
        $.cookie("adminAutoUser", "true", {expires: 365}); //存储一个带7天期限的cookie
        $.cookie("adminUsername", str_username, {expires: 365});
        $.cookie("adminPassword", str_password, {expires: 365});
    }
</script>
</body>
</html>
