<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baidu-site-verification" content="7dGQolUeVh" />
<title>搜索结果</title>
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/favicon.ico" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/css/common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/css/www.css" />
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/www.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div id="content">
	<div class="bigdiv">
    	<div class="location"><a href="<?php echo WWW;?>">首页</a> &gt; 搜索结果</div>

        <div class="layout">
        	<div class="list">
        	    <?php if (is_array($this->goodses) && count($this->goodses)>0):?>
            	<ul>
            	<?php foreach ($this->goodses as $k => $goods):?>
                    <?php if($goods['goods_channel']=='BBC'):?>
                    <li>
                        <a href="<?php echo WWW;?>products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->showImage($goods['goods_list_image']);?>" alt="<?php echo $this->escape($goods['goods_name']);?>"/></a>
                        <p class="country"><?php echo $this->escape($goods['country_name']);?></p>
                        <h4><?php echo $this->escape($goods['goods_name']);?></h4>
                        <p class="shop_name"><?php echo $this->escape($goods['shop_name']);?></p>
                        <p><span class="star"><i style="width:<?php echo ($goods['score_avg']=='0.00'?'5':$goods['score_avg'])*20;?>%;"></i></span></p>
                        <p class="price"><?php echo $this->showPrice($goods['shop_price']);?></p>
                        <?php if($goods['sum_stock_value']<=0): ?>
                        <div class="product_tips">
                            <a href="<?php echo WWW;?>products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/soldout.png" alt="卖光啦"/></a>
                        </div>
                        <?php endif;?>
                    </li>
                    <?php else:?>
                    <li>
                        <a href="http://www.sendtou.hk/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->showImage($goods['goods_list_image']);?>" alt="<?php echo $this->escape($goods['goods_name']);?>"/></a>
                        <p class="country"><?php echo $this->escape($goods['country_name']);?></p>
                        <h4><?php echo $this->escape($goods['goods_name']);?></h4>
                        <p class="shop_name"><?php echo $this->escape($goods['shop_name']);?></p>
                        <p><span class="star"><i style="width:<?php echo ($goods['score_avg']=='0.00'?'5':$goods['score_avg'])*20;?>%;"></i></span></p>
                        <p class="price"><?php echo $this->showPrice($goods['shop_price']);?></p>
                        <div class="hk_product">
                            <a href="http://www.sendtou.hk/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/hkproduct.png" alt="香港直邮"/></a>
                        </div>
                        <?php if($goods['sum_stock_value']<=0): ?>
                        <div class="product_tips">
                            <a href="<?php echo WWW;?>products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/soldout.png" alt="卖光啦"/></a>
                        </div>
                        <?php endif;?>
                    </li> 
                    <?php endif;?> 
                 <?php endforeach;?>
                </ul>
                 <?php else :?>
                 没有商品！
                 <?php endif;?>
                 
            </div>
             <?php if ($this->page['totalpage']>1):?>
            <div class="page"><?php echo $this->ShowPage($this->page);?></div>
            <?php endif;?>
        </div>
        
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<?php echo $this->render(SEED_WWW_TPL.'/right_fix.phtml');?>
</body>
</html>