<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>下载App</title>
    <meta name="viewport" content="width=320.1, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta content="telephone=no" name="format-detection" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <script src="/ky/jquery-3.3.1/jquery-3.3.1.min.js"></script>
    <style type="text/css">
        *{margin:0; padding:0;}
        a{text-decoration: none;}
        img{max-width: 100%; height: auto;}
        .weixin-tip{display: none; position: fixed; left:0; top:0; bottom:0; background: rgba(0,0,0,0.8); filter:alpha(opacity=80);  height: 100%; width: 100%; z-index: 100;}
        .weixin-tip p{text-align: center; margin-top: 10%; padding:0 5%;}
    </style>
    <script>
        /*首先判断是否是pc，若是pc访问则跳转到http://app.ctrip.com/*/
        var u = navigator.userAgent || '';
        var isPC = !/(iphone|ios|android|mini|mobile|mobi|Nokia|Symbian|iPod|iPad|Windows\s+Phone|MQQBrowser|wp7|wp8|UCBrowser7|UCWEB|360\s+Aphone\s+Browser)/i.test(u);
        if (isPC) { location.href = "/app/etradefast-release.apk"; }
    </script>
    <script>
        var isPC = false;
        var e = navigator.userAgent ? navigator.userAgent.toLowerCase() : '';
        var iswx = /micromessenger/.test(e) ? !0 : !1;
        var wxurl = '';
        if (iswx) {
            wxurl = "http://mp.weixin.qq.com/mp/redirect?url=";
        }
        function hello() { //修复图片偶尔不能加载
            var appUrl = "/app/etradefast-release.apk";
            if (!isPC && !iswx) {
                if (appUrl) {
                    location.href = appUrl;
                } else if (sid) {
                    location.href = "/m/" + sid;
                }
            }
        }
    </script>

</head>
<body onload="hello()">
<div class="weixin-tip">
    <p>
        <img src="/app/live_weixin.png" alt="微信打开"/>
    </p>
</div>
<script type="text/javascript">
    $(window).on("load",function(){
        var winHeight = $(window).height();
        function is_weixin() {
            var ua = navigator.userAgent.toLowerCase();
            if (ua.match(/MicroMessenger/i) == "micromessenger") {
                return true;
            } else {
                return false;
            }
        }
        var isWeixin = is_weixin();

        var $weixinTip = $(".weixin-tip");
        if (isWeixin) {
            $weixinTip.css("height", winHeight);
            $weixinTip.show();
        }
    })
</script>

</body>
</html>
