<div id="deliveryEditDiv" class="layui-form">
	<div class="et-auth-top et-auth-bg-orange" style="height: 60px; text-align: left;">
		<h3><?php echo $this->translate('edit'); ?><label class="deliveryNo_"></label><?php echo $this->translate('deliveryItemQuantity'); ?></h3>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="">
		<div style="margin-top: 20px;"></div>

		<div class="layui-form-item">
			<table class="layui-table" lay-skin="line" id="deliveryEditTable">
				<colgroup>
					<col>
					<col width="140">
					<col width="100">
					<col width="100">
					<col width="160">
				</colgroup>
				<thead>
				<tr>
					<th>名称</th>
					<th>型号</th>
					<th>单价</th>
					<th>数量</th>
					<th>总价</th>
				</tr>
				</thead>
				<tbody>
                <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
					<tr>
						<td style="text-align: left"><?php echo $value->productName;?></td>
						<td style="text-align: left"><?php echo $value->productModel;?></td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode;?><label><?php echo $value->buyerUnitPrice;?></label></td>
						<td style="text-align: left">
							<input name="deliveryQuantity_edit" class="layui-input" value="<?php echo $value->deliveryQuantity;?>" />
							<input type="hidden" name="orderItemID_edit" value="<?php echo $value->itemID;?>" />
						</td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;<label id="itemID_<?php echo $value->itemID;?>"><?php echo $value->buyerTotalAmount;?></label></td>
					</tr>
                <?php endforeach; ?>
				</tbody>
			</table>
		</div>

		<div class="layui-form-item">
			<div class="layui-form-label" style="width: 420px;">
				<div class="yyzz_box clearfix" style="width: 600px;">
					<p class="zzname" id="deliveryEditAttachment" style="width: 600px; font-weight:bold;"><?php echo $this->translate('PREPARE_GOODS'); ?><!--合同相关附件上传--></p>
                    <?php
                        echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLPG'], "0", null);
                    ?>
				</div>
			</div>
		</div>

		<div style="height: 12px"></div>
		<div class="et-auth-row">
			<button class="layui-btn layui-btn-warm" id="deliveryEditConfirmBtn"><?php echo $this->translate('confirmed'); ?></button>&nbsp;&nbsp;
			<a id="deliveryEditViewDelBtn" style="color: #c2c2c2; cursor: pointer;"><?php echo $this->translate('deliveryDel'); ?></a>
		</div>
	</div>
</div>