<div id="deliveryBillInfoDiv" class="layui-form">
	<div class="et-auth-top et-auth-bg-orange billInfoTop" style="height: 120px; text-align: left;">
		<h3><?php echo $this->translate('deliveryBillTitle'); ?>&nbsp;<label><?php echo $this->delivery->deliveryNo; ?></label></h3>
		<h6 class="padding-left-15"><?php echo $this->translate('deliveryBillTipsBank'); ?></h6>
		<h6 class="padding-left-15"><?php echo $this->translate('deliveryBillTipsCheck'); ?></h6>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="layui-form">
		<div style="margin-top: 20px;"></div>

		<?php
		foreach ($this->deliverySupplierList as $deliverySupplier):
		?>
		<div class="layui-form-item">
			<label class="layui-form-label width-120">供应商名称</label>
			<div class="layui-input-block">
				<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->supplierName ?></div>
			</div>
		</div>

		<div class="layui-form-item">
			<label class="layui-form-label width-120">选择银行帐户</label>
			<div class="layui-input-block margin-left-150" style="width: 500px;">
				<select name="bankName" id="bankName" lay-verify="required" lay-search="" lay-filter="bankName">
					<option value=""><?php echo $this->translate('et_select'); ?></option>
                    <?php echo $this->ShowBankAccountList(); ?>
				</select>
			</div>
		</div>
		<?php
		endforeach;
		?>

		<div style="height: 12px"></div>
		<div class="et-auth-row">
			<button class="layui-btn layui-btn-warm" id="signingBtn"><?php echo $this->translate('signingNow'); ?></button>&nbsp;&nbsp;
			<a id="addBankAccountBtn" style="color: #01AAED; cursor: pointer;"><?php echo $this->translate('add').$this->translate('bankAccount'); ?></a>
		</div>
	</div>
</div>