<div id="deliveryBillInfoDiv" class="layui-form">
	<div class="et-auth-top et-auth-bg-orange billInfoTop" style="height: 190px; text-align: left;">
		<h3><label><?php echo $this->delivery->deliveryNo; ?></label>&nbsp;<?php echo $this->translate('deliveryBillTips'); ?></h3>
		<h6 class="padding-left-15">*&nbsp;<?php echo $this->translate('deliveryBillTips_A'); ?></h6>
		<h6 class="padding-left-15">*&nbsp;<?php echo $this->translate('deliveryBillTips_B'); ?></h6>
		<h6 class="padding-left-24"><?php echo $this->translate('deliveryBillTips_C'); ?></h6>
		<h6 class="padding-left-24"><?php echo $this->translate('deliveryBillTips_D'); ?></h6>
		<h6 class="padding-left-24"><?php echo $this->translate('deliveryBillTips_E'); ?></h6>
		<h6 class="padding-left-15">*&nbsp;<?php echo $this->translate('deliveryBillTips_F'); ?></h6>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="layui-form">
		<div class="layui-collapse" lay-accordion>
		<?php
		$isShow = true;
		foreach ($this->deliverySupplierList as $deliverySupplier):
		?>
			<div class="layui-colla-item" style="text-align: left">
				<h2 class="layui-colla-title"><?php echo $deliverySupplier->supplierName; ?></h2>
				<div class="layui-colla-content <?php if ($isShow) echo "layui-show" ?>">
					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">价税合计金额</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->supplierCrnCode. ' ' .$deliverySupplier->totalAmount; ?></div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100 text-align-left billingInfoFont font-orange">销售方信息</label>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">名称</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->supplierName ?></div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">纳税人识别号</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->supplier->businessLicenseNo ?></div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">地址、电话</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux">
								<?php echo $deliverySupplier->supplier->regdAddress ?>
								<a href="tel:<?php echo $deliverySupplier->supplier->phone ?>" class="text-white"><?php echo $deliverySupplier->supplier->phone ?></a>
							</div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">开户行及帐号</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->bankName. ' ' .$deliverySupplier->bankAcctNo ?></div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100 text-align-left billingInfoFont font-orange">邮寄信息</label>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100">快递单号</label>
						<div class="layui-input-block">
							<div class="layui-form-mid layui-word-aux"><?php echo $deliverySupplier->supplierName ?></div>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100 text-align-left billingInfoFont font-blue">供货合同</label>
						<div class="or_curs tl clearfix " style="width: 600px; padding: 10px 15px;">
							<dl class="fl download_doc">
								<?php
                                $contractList = array();
                                $contractList[] = $deliverySupplier->purContract;
                                echo $this->ShowTopContract($contractList, $this->accountID, 'CRSE', null, $this->hasIDCertificate);
								?>
							</dl>
						</div>
					</div>

					<div class="layui-form-item margin-bottom-1">
						<label class="layui-form-label width-100 text-align-left billingInfoFont font-blue">开票指引</label>
						<div class="or_curs tl clearfix " style="width: 600px; padding: 10px 15px;">
							<dl class="fl download_doc">
                                <?php
                                $supplierList = array();
                                $supplierList[] = $deliverySupplier->supplier;
                                echo $this->ShowTopContract($supplierList, $this->accountID, 'CRSE', null, $this->hasIDCertificate);
                                ?>
							</dl>
						</div>
					</div>
				</div>
			</div>
		<?php
            $isShow = false;
		endforeach;
		?>
		</div>
	</div>
</div>