<div class="header_wrap">
    <div class="header w1200 m0a ofh clearfix">
        <div class="logo fl">
            <a href="/"><img src="/ky/images/logo.png"></a>
        </div>

		
		
        <div class="nav fr">
            <ul class="nav_list">
				<?php
				if (!empty($this->userID)):
				?>
				<span style="width:200px;float:left;display:inline-block;line-height:76px;margin-left:-200px;text-align:center;color:#fff;">
                    <a style="color:#DCDCDD;" href="/user/index"><?php echo $this->userLoginName; ?></a>&nbsp;&nbsp;
                    <a style="color:#DCDCDD;" href="/user/Logout"><?php echo $this->translate('nav_exit'); ?></a>
                </span>
				<?php
				else:
				?>
				<li class="nav-item">
					<a href="/user/login"><?php echo $this->translate('register').$this->translate('nav_login'); ?></a>
				</li>
				<?php
				endif;
				?>
				
				<li class="nav-item  cur">
					<a href="/user/index"><?php echo $this->translate('nav_index');?></a>
				</li>
                <li class="nav-item">
                    <a href="/user/finance"><!-- 金融服务 --><?php echo $this->translate('nav_finservice');?></a>
                </li>
                <li class="nav-item">
                    <a href="/user/finance/channel"><!-- 金融项目 --><?php echo $this->translate('nav_channel');?></a>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 关于我们 --><?php echo $this->translate('nav_about');?></a>
                </li>
            </ul>
            <div class="move-bg"></div>
        </div>
    </div>
</div>
