<style>
	.dropdown {
		position: relative;
		display: inline-block;
	}

	.dropdown-content {
		display: none;
		position: absolute;
		background-color: #f9f9f9;
		min-width: 160px;
		box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
		padding: 12px 16px;
		z-index: 1;
	}

	.dropdown:hover .dropdown-content {
		display: block;
	}
</style>

<div class="header_wrap">
    <div class="header w1200 m0a ofh clearfix">
        <div class="logo fl">
            <a href="/"><img src="/ky/images/logo.png"></a>
        </div>

        <div class="nav">
            <ul class="nav_list">
				<li class="nav-item  cur">
					<a href="/user/index"><?php echo $this->translate('nav_index');?></a>
				</li>
                <li class="nav-item">
                    <a href="/user/finance"><!-- 金融服务 --><?php echo $this->translate('nav_finservice');?></a>
                </li>
                <li class="nav-item">
                    <a href="/user/finance/channel"><!-- 金融项目 --><?php echo $this->translate('nav_channel');?></a>
                </li>
                <!--<li class="nav-item">-->
                <!--    <a href="/"><!-- 关于我们 -->--><?php //echo $this->translate('nav_about');?><!--</a>-->
                <!--</li>-->

				<div class="dropdown">
					<span>Mouse over me</span>
					<div class="dropdown-content">
						<p>Hello World!</p>
					</div>
				</div>
    
                <?php if (!empty($this->userID)): ?>
				<span style="width:200px;float:left;display:inline-block;line-height:76px;margin-left:-200px;text-align:center;color:#fff;">
					<a style="color:#DCDCDD;" href="/user/index"><?php echo $this->userLoginName; ?></a>&nbsp;&nbsp;
					<a style="color:#DCDCDD;" href="/user/Logout"><?php echo $this->translate('nav_exit'); ?></a>
				</span>
				<?php else: ?>
				<li class="nav-item">
					<a href="/user/login"><?php echo $this->translate('register').$this->translate('nav_login'); ?></a>
				</li>
				<?php endif; ?>
            </ul>
            <div class="move-bg"></div>
        </div>
    </div>
</div>
