<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.min.js"></script>
<script type='text/javascript' src='/ky/js/jquery-ui.min.js'></script>
<script type="text/javascript" src="/ky/js/idrag.js"></script>

<!-- layui -->
<script type="text/javascript" src="/ky/layui/layui.js"></script>

<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>