<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.min.js"></script>
<script type='text/javascript' src='/ky/js/jquery-ui.min.js'></script>
<script type="text/javascript" src="/ky/js/idrag.js"></script>

<!-- layui -->
<link href="/ky/layui/css/layui.css" rel="stylesheet" media="all">
<script type="text/javascript" src="/ky/layui/layui.js"></script>