<div class="slides">
    <ul class="slideul">
        <li class="kefu">
            <div class="sidebox"><a class="slide1" onclick="openqq('http://wpa.b.qq.com/cgi/wpa.php?ln=1&key=XzkzODA2NTM2M18zNjI3MDhfNDAwMTAyMDMzM18yXw');"></a></div>
        </li>
        <li class="kefu">
            <div class="sidebox"><a class="slide2" onclick="openswt('http://dft.zoosnet.net/LR/Chatpre.aspx?id=DFT14714734&lng=cn');"></a></div>
        </li>
        <li class="kefu">
            <div class="sidebox"><a class="slide3"></a></div>
            <ul class="kefulist" style="top:-1px;">
                <li style="height: 38px;"><a style="line-height:38px;">400-1020-333</a></li>
                <li style="height: 42px;"><a style="line-height:18px;">020-83930306转8537</a></li>
            </ul>
        </li>
        <li class="kefu">
            <div class="sidebox"><a class="slide4" href="<?php echo WWW;?>user/cart"></a></div>
        </li>
        <li class="kefu">
            <div class="sidebox"><a class="slide5" href="<?php echo WWW;?>user/info"></a></div>
        </li>
        <li class="kefu">
            <div class="sidebox"><a class="slide6"></a></div>
            <ul class="kefulist" style="top:-70px;">
                <li><img src="<?php echo WWW;?>static/sendyou/images/ui/slide-code.png" alt=""></li>
            </ul>
        </li>
        <li class="kefu scroll_top"><div class="sidebox"><a class="slide7"></a></div></li>
    </ul>
</div>