<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('etradefast'); ?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/swiper-3.3.1.min.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/swiper-3.3.1.jquery.min.js"></script>
<script type="text/javascript" src="/js/center/seed.form.js"></script>
<script type="text/javascript" src="/js/center/jquery.form.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/js/tips.js"></script>
<style type="text/css">
.error{margin:0;font-size: 14px;height: 30px;}
</style>
<script type="text/javascript">
function doUpdate(){
    SeedMsgBox('<?php echo $this->translate('in_save');?>');/*正在保存中..*/
    var options = {
        target:     '#SeedMsgTxt',
        url:        '<?php echo $this->baseUrl();?>/forget',
        success: function() {
        }
    };
    $('#forget_form').ajaxSubmit(options);
}
</script>
</head>
<body style="overflow-x:hidden;overflow-y:hidden">
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="content">
    <div class="logindiv">
        <form action="" method="post" name="forget_form" id="forget_form">
        <div class="login_box fr tc">
            <label class="lagin_lab1 mt50"><!--用户名--><?php echo $this->translate('username');?></label>
            <p class="tl f20">
                <i class="user_icon"></i><input class="login_txt1" name="ecommloginname" id="ecommloginname" type="text" data-rule-mail="true" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('tip_login_name');?>" /><!--请输入登录用户名-->
            </p>
            <label class="lagin_lab1"><!--姓名--><?php echo $this->translate('name');?></label>
            <p class="tl f20">
                <i class="user_icon"></i><input class="login_txt1" name="contactname" id="name" type="text" required data-msg-required="<?php echo $this->translate('de_null');?>" placeholder="<?php echo $this->translate('name');?>" />
            </p>
            <input class="login_bnt2 mt50" name="" type="submit" value="<?php echo $this->translate('tip_find_pwd');?>" /><!--找回密码-->
            <p class="tc f16">
                <a class="fr" href="/user/login"><!--返回登录--><?php echo $this->translate('tip_login_back');?></a>
            </p>
        </div>
        </form>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script src="/ky/js/jquery.validate.js"></script>
<script>
$(function(){
    $("#forget_form").validate({
        submitHandler: function() {
            form.submit();
        }
    })
});
jQuery.validator.addMethod("mail", function (value, element) {
    var mail = /^[A-Za-z0-9._%-]+@([A-Za-z0-9-]+\.)+[A-Za-z]{2,4}$/;
    return this.optional(element) || (mail.test(value));
}, "<?php echo $this->translate('email').$this->translate('de_format');?>");
</script>
</body>
</html>
