<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/login/login.css" rel="stylesheet">
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
	<link href="/ky/css/forget/forget.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu shadow">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<img alt="eTradeFast" src="/ky/images/index/Logo_loginH75.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
                <?php echo $this->translate('findPSD'); ?>
			</p>

			<p class="navbar-text navbar-right">
                <?php echo $this->translate('alreadyRegistered'); ?> <a href="/" class="navbar-link"><?php echo $this->translate('login_s'); ?></a>
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid register-body">
	<div class="container">
		<div class="col-md-10 col-md-offset-1 col-xs-12 register-form-div">
			<form class="form-horizontal register-form-body" action="#" method="post" id="register_form" name="register_form">
				<div class="register-type-info">
                    <div class="row">
						<div class="col-md-6 text-center active">
							<a href="javascript:void(0)"><?php echo $this->translate('findPSD'); ?></a>
						</div>
					</div>
				</div>

                <?php if (!empty($this->resultMsg)): ?>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p><?php echo $this->resultMsg; ?>!</p>
                    </div>
                <?php endif; ?>

                <?php if (!empty($this->resultSuccessMsg)): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <p><?php echo $this->resultSuccessMsg; ?>!</p>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12 col-md-7 col-md-offset-5">
                            <a class="btn btn-warning btn-default" href="/" role="button"><?php echo $this->translate('tip_login_back'); ?></a>
                        </div>
                    </div>
                <?php else: ?>
                <div class="form-group phone">
                    <label for="ecommloginname" class="col-sm-3 control-label"><?php echo $this->translate('username'); ?></label>
                    <div class="col-sm-7">
                        <input type="text" class="form-control" name="ecommloginname" id="ecommloginname" required placeholder="<?php echo $this->translate('tip_login_name'); ?>" >
                    </div>
                </div>

				<div class="form-group">
					<label for="contactName" class="col-sm-3 control-label"><?php echo $this->translate('name'); ?></label>
					<div class="col-sm-7">
						<input type="text" class="form-control" name="contactName" id="contactName" required placeholder="<?php echo $this->translate('name'); ?>" >
					</div>
				</div>

				<div class="form-group">
                    <div class="col-sm-12 col-md-7 col-md-offset-3">
					    <button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('submit'); ?></button>
                    </div>
				</div>
                <?php endif; ?>
			</form>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerSimple.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
    var serviceContractData = '';

	$().ready(function() {
		$("#register_form").validate({
			rules: {
				ecommloginname: {
					checkLoginName: true
				},
				ecommpasswsd: {
					isValidPassword: true,
					minlength: 8,
					maxlength: 30
				},
				checkecommrpasswsd: {
					reCheckPassword: true
				}
			},
			messages: {
				ecommpasswsd : {
					required: "<?php echo $this->translate('de_null'); ?>",
					minlength: "<?php echo $this->translate('mat_psd');?>",
					maxlength: "<?php echo $this->translate('is_passwd');?>"
				},
				serviceContract: {
					required: "<?php echo $this->translate('check_service_contract'); ?>"
				}
			},
			errorPlacement: function(error, element) {
				// Append error within linked label
                $(error).addClass("col-md-offset-3");
				$(element)
					.closest( "form" )
					.find( "label[for='" + element.attr( "id" ) + "']" )
					.parent().addClass("has-error").removeClass("has-success")
					.append( error );
			},
			success: function(label) {
				var forName = $(label).attr("for");
				$("label[for='" + forName + "']").parent().addClass("has-success").removeClass("has-error");
				$(label).remove();
			},
			highlight: function (element) {
				$("label[for='" + element.id + "']").parent().addClass("has-error").removeClass("has-success");
			},
			submitHandler: function (form) {
				form.submit();
			}
		});
	});

	$(function () {
        var getServiceContractUrl = '/register/servicehtml';
        $.get(getServiceContractUrl, function (service) {
            serviceContractData = service;
        });

		$("#serviceContract").click(function () {
			if ($("#isReadServiceContract").val() == 'false') {
				$("#serviceContract").prop('checked', false);
				toReadServiceContract();
			}
		});
		$("#check_doc").click(function () {
			if ($("#isReadServiceContract").val() == 'false') {
				$("#serviceContract").prop('checked', false);
			}
			toReadServiceContract();
		});

		$("#changeCompanyRegister").click(function () {
                $(this).parent().addClass("active");
                $("#changePersonRegister").parent().removeClass("active");
        });

		$("#changePersonRegister").click(function () {
                $(this).parent().addClass("active");
                $("#changeCompanyRegister").parent().removeClass("active");
        });

		$("#changeCompanyRegister,#changePersonRegister").click(function () {
            if ($(this).attr("isPersonAccount") === 'true') {
                $(".accountName,.email").hide();
                $("#isPersonAccount").val("true");
                $(".phone").after($(".address"));
            } else {
                $(".accountName,.email").show();
                $("#isPersonAccount").val("false");
                $(".email").after($(".address"));
            }
        });
	});

	function toReadServiceContract() {
        layer.open({
            type: 1,
            title: "<?php echo $this->translate('service_contract'); ?>",
            area: ['1024px', '97%'],
            scrollbar: false,
            content: serviceContractData,
            success: function(layero, index){
                $(".layui-layer-content").scroll(function () {
                    // console.log(this.scrollHeight);
                    if (this.scrollHeight - this.scrollTop === this.clientHeight) {
                        console.log("in");
                        $("#isReadServiceContract").val('true');
                        $("#serviceContract").prop('checked', true);
                    }
                });
            }
        });
	}

	// 邮箱登录名验证
	jQuery.validator.addMethod("checkLoginName", function(value, element) {
		return $.post("<?php echo $this->BaseUrl();?>/register/check", {
				ecommloginname: value
			},
			function (data) {
				data = jQuery.parseJSON(data);
				return data.result == false;
			}
		);
	}, "<?php echo $this->translate('de_use');?>");

	// 密码规验证(8-30位  字母数字)
	jQuery.validator.addMethod("isValidPassword", function(value, element) {
		var regExp=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,30}$/;
		return this.optional(element) || (regExp.test(value));
	}, "<?php echo $this->translate('is_passwd');?>");

	// 验证确认密码
	jQuery.validator.addMethod("reCheckPassword", function(value, element) {
		var psw = $("#ecommpasswsd").val();
		return this.optional(element) || (value === psw);
	}, "<?php echo $this->translate('is_psd');?>");
</script>
</body>
