<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/swiper-3.3.1.min.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/swiper-3.3.1.jquery.min.js"></script>
<script type="text/javascript" src="/js/center/seed.form.js"></script>
<script type="text/javascript" src="/js/center/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/www.js"></script>
<script type="text/javascript" src="/js/tips.js"></script>
</script>
<script type="text/javascript">
    function checkphone(user_name){
        if(user_name.replace(/^\s+|\s+$/ig,'') === '' || !(/^1[3|4|5|8]\d{9}/.test(user_name))){
            showMsg(no_img+'请正确填写手机号',2000);
            return false;
        }
        return true;
    }

var _vtime = 0,_vid;
function sendvcode(){
    if(_vtime > 0)return false;
    _vtime = 30;
    countvtime();
    $.ajax({
        url:'<?php echo $this->seed_BaseUrl;?>/phonevcode/forget',
        data:'telephone='+$('#phone').val()+'&userid=<?php echo ($this->seed_User['user_id']>0)?$this->escape($this->seed_User['user_id']):"0";?>&t='+(new Date).getTime(),
        type:'GET',
        error:function(){
            unsetVcode();
            showMsg(no_img+'对不起，出错了',1000);
        },
        success:function(d){
            if(d && d !== 'ok'){
                unsetVcode();
                showMsg(no_img+d,1000);
            }else{
                showMsg(yes_img+"验证码发送成功！",1000);
            }
        }
    });
}

var vtstr = '秒后可再发送';
function countvtime(){
    if(_vtime <1){
        unsetVcode();
        return ;
    }
    $('#sendvcode').html(_vtime+vtstr);
    _vid = window.setTimeout(function(){countvtime()},1000);
    --_vtime;
}

function unsetVcode(){
    window.clearTimeout(_vid);
    _vtime = 0;
    $('#sendvcode').html('发送验证码');
}

function doUpdate(){
    SeedMsgBox('正在保存中，请稍候...');
    var options = {
        target:     '#SeedMsgTxt',
        url:        '<?php echo $this->baseUrl();?>/forget',
        success: function() {
        }
    };
    $('#forget_form').ajaxSubmit(options);
}
</script>
</head>
<body style="overflow-x:hidden;overflow-y:hidden">
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>

<!-- content star -->
<div class="content">
    <div class="logindiv">
        <div class="login_box fr tc">
            <label class="lagin_lab1">用户名</label>
            <p class="tl f20">
                <i class="user_icon"></i><input class="login_txt1" name="ecommloginname" id="ecommloginname" type="text" placeholder="请输入用户名" />
            </p>
            <label class="lagin_lab1">短信验证</label>
            <p class="tl f20">
                <i class="sms_icon"></i><input class="login_txt2 fl" name="vcode" id="vcode" type="text" placeholder="请输入验证码" />
                <a class="login_bnt1 fr tc" id="sendvcode" onclick="sendvcode();">点击获取</a>
            </p>
            <label class="lagin_lab1">密码</label>
            <p class="tl f20">
                <i class="pw_icon"></i><input class="login_txt1" name="ecommpasswsd" id="ecommpasswsd" type="password" placeholder="请输入密码" />
            </p>
            <label class="lagin_lab1">确认密码</label>
            <p class="tl f20">
                <i class="pw_icon"></i><input class="login_txt1" name="ecommpasswsd" id="ecommpasswsd" type="password" placeholder="请再次输入密码" />
            </p>
            <input class="login_bnt2 mt50" name="" type="submit" value="确认修改" onclick="doLogin()"/>
        </div>
    </div>
</div>
<!-- content end -->

<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>
