<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移1</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link rel="shortcut icon" type="image/x-icon" href="/ky/images/favicon.ico">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/swiper-3.3.1.min.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript" src="/ky/js/swiper-3.3.1.jquery.min.js"></script>
</head>
<style>
    .swiper-container {
        width: 100%;
        height: 100%;
    }
    .swiper-slide {
        min-width:1200px;
        text-align: center;
        font-size: 18px;
        background: #fff;
        display: -webkit-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        -webkit-box-pack: center;
        -ms-flex-pack: center;
        -webkit-justify-content: center;
        justify-content: center;
        -webkit-box-align: center;
        -ms-flex-align: center;
        -webkit-align-items: center;
        align-items: center;
        overflow:hidden;
    }
</style>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<!-- banner star -->
<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"><a><img src="./ky/images/banner.jpg"></a></div>
        <div class="swiper-slide"><a><img src="./ky/images/banner.jpg"></a></div>
        <div class="swiper-slide"><a><img src="./ky/images/banner.jpg"></a></div>
    </div>
    <div class="swiper-pagination"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
</div>
<!-- <div class="service w1200 m0a">
    <ul class="service_list clearfix">
        <li class="pr">
            <h3>基础服务</h3>
            <p>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
        <li class="pr">
            <h3>退税服务</h3>
            <p>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
        <li class="pr">
            <h3>金融服务</h3>
            <p class>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
        <li class="pr">
            <h3>基础服务</h3>
            <p>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
        <li class="pr">
            <h3>基础服务</h3>
            <p>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
        <li class="pr">
            <h3>基础服务</h3>
            <p>基础服务基础服务，基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务基础服务</p>
            <a class="more pa" href="javascript:;">服务详细>></a>
        </li>
    </ul>
</div> -->
<!-- <div class="about_us w1200 m0a">
    <h2 class="clearfix">
        <span class="fl">关于我们 </span><span class="fr">About us</span>
    </h2>
    <img src="./ky/images/add1.jpg">
    <div class="other_a w1200 mt20">
        <dl class="clearfix h30 mt20">
            <dt class="fl tc">其他链接 / LINK</dt>
            <dd class="fl">
                <a href="javascript:;">关于快移</a>
                <a href="javascript:;">合作伙伴</a>
                <a href="javascript:;">营销中心</a>
                <a href="javascript:;">联系我们</a>
                <a href="javascript:;">联系客服</a>
                <a href="javascript:;">诚征英才</a>
                <a href="javascript:;">网站地图</a>
            </dd>
        </dl>
        <dl class="clearfix h30">
            <dt class="fl tc">热门帮助 / HELP</dt>
            <dd class="fl">
                <a href="javascript:;">关于快移</a>
                <a href="javascript:;">合作伙伴</a>
                <a href="javascript:;">营销中心</a>
                <a href="javascript:;">联系我们</a>
                <a href="javascript:;">联系客服</a>
                <a href="javascript:;">诚征英才</a>
                <a href="javascript:;">网站地图</a>
                <a href="javascript:;">关于快移</a>
                <a href="javascript:;">合作伙伴</a>
                <a href="javascript:;">营销中心</a>
                <a href="javascript:;">联系我们</a>
                <a href="javascript:;">联系客服</a>
                <a href="javascript:;">诚征英才</a>
                <a href="javascript:;">网站地图</a>
            </dd>
        </dl>
    </div>
</div> -->
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script>
    var swiper = new Swiper('.swiper-container', {
        pagination: '.swiper-pagination',
        nextButton: '.swiper-button-next',
        prevButton: '.swiper-button-prev',
        slidesPerView: 1,
        paginationClickable: true,
        spaceBetween: 30,
        autoplay: 2500,
        loop: true
    });
    
</script>
</body>
</html>