<?php echo $this->render("header.phtml") ?>
<h1>操作记录 <button id="reloadBtn" class="layui-btn">reload</button></h1>

<table id="demo" lay-filter="test"></table>
<div id="logInfoDiv" style="display: none; white-space: nowrap;"></div>


<script>
	layui.use('table', function(){
		var table = layui.table;

		//第一个实例
		table.render({
			elem: '#demo'
			,height: 475
			,url: '/a/log/logfilelist' //数据接口
			,page: true //开启分页
			,limit: 10
			,cols: [[ //表头
				{field: 'id', title: 'ID', width:80, sort: true, fixed: 'left'}
				,{field: 'name', title: '文件名', width:280, templet: '#titleTpl'}
				,{field: 'fileTime', title: '修改时间', width:280, sort: true}
			]]
		});

		$("#reloadBtn").click(function () {
			var tableIns = table.render({
				elem: '#demo'
				,url: '/a/log/logfilelist' //设置异步接口
				,id: 'idTest'
			});

			tableIns.reload({
				page: {
					curr: 1 //重新从第 1 页开始
				}
			});
		});
	});

	function showLog(fileName) {
		$("#logInfoDiv").html("").load('/a/log/loginfo', {fileName:fileName}, function () {
			layer.open({
				type: 1,
				title: false,
				area: ['85%', '95%'],
				skin: 'layui-layer-rim',
				scrollbar: false,
				shade: 0.5,
				content: $("#logInfoDiv"),
				cancel: function(index, layero){
					// if(confirm('确定要关闭么')){ //只有当点击confirm框的确定时，该层才会关闭
					// 	layer.close(index)
					// }
					$("#logInfoDiv").html("").hide();
					// return false;
				}
			});
		});
	}
</script>

<script type="text/html" id="titleTpl">
	<a href="javascript:void(0)" onclick="showLog('{{d.name}}')" class="layui-table-link">{{d.name}}</a>
</script>
<?php
foreach ($this->fileList as $file):
?>
<!--<div>--><?php //echo $file. ' ' . date('Y-m-d H:i:s', filectime('/storage/html/eTradeFastWebhooksTest/eTradeFastPhp/log/'.$file)); ?><!-- </div>-->
<?php
endforeach;
?>
<?php //var_dump($this->fileList); ?>
