<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script>

    var t = null;
    function singleSelect(obj) {
        var pname = $(obj).val();
        var thegoodid = obj.id;
        if (obj.checked) {
            $(window.parent.document).find("#accountContactID").val(thegoodid);
            $(window.parent.document).find("#accountContactName").val(pname);
        }
    }
    function delSelect(obj){
        $(obj).parent().remove();
    }
</script>
</head>
<body>
<div class="order_goodslist">
    <div style="height: 40px;line-height:35px;margin: 10px;">
        <form action="#" method="post">
            <p>
                <input class="search_inp"  name="keyword"  <?php if(!empty($this->keyword)){echo "value=".$this->keyword;}?> placeholder="<?php echo $this->translate('INPkw_par');?>" type="text"><!--可输入公司名称、行业等关键字-->
                <input class="ss_btn" type="submit" value="">
                <?php if($this->CompAdmin==true):?>
                    <a style="margin-top: 8px;" href="<?php echo WWW;?>user/buyer/add" class="addb_box fr"></a>
                    <a style="margin-top: 10px;" href="<?php echo WWW;?>user/buyer/adds" class="p_n_sh fr"></a>
                <?php endif;?>

            </p>
        </form></div>
    <div style="width: 100%">
        <table class="qy_table_tc qy_table1">
            <thead>
            <tr>
                <th ><!--操作--><?php echo $this->translate('madeTT');?></th>
                <th ><!--姓名--><?php echo $this->translate('name');?></th>
                <th><!--个人电话--><?php echo $this->translate('myphone');?></th>
                <th><!--电子邮箱--><?php echo $this->translate('email');?></th>
                <th><!--职务--><?php echo $this->translate('myjob');?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(is_array($this->e) && count($this->e)>0):?>
                <?php foreach ($this->e as $k=>$v):?>
                    <tr>
                        <td> <input value="<?php echo $v['name'];?>"  type="radio" name="checkbox" onclick="singleSelect(this)" id="<?php echo $v['contactID'];?>"></td>
                        <td><?php echo $v['name'];?></td>
                        <td><?php if($v['phone']){echo $v['phone'];}else{echo $v['mobilePhone'];}?></td>
                        <td><?php echo $v['email'];?></td>
                        <td><?php echo $v['title'];?></td>
                    </tr>
                <?php endforeach; ?>
            <?php endif;?>
            </tbody>
        </table>
        <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
    </div>
</div>
</body>
</html>