<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/account/account.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('personNO'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->errMsg)): ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Warning!</strong> <?php echo $this->errMsg; ?>
                        </div>
                        <?php endif; ?>

                        <form class="form-horizontal" action="#" id="contact_edit_form" method="post">
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('name'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['realAuthStatus'] != 0 && $this->e['realAuthStatus'] != -1): ?>
                                    <p class="form-control-static"><?php echo $this->e['name']; ?></p>
                                    <?php else:?>
                                    <input type="text" class="form-control" name="name" id="name" placeholder="<?php echo $this->translate('is_name');?>" value="<?php echo $this->e['name']; ?>" required>
                                    <?php endif; ?>
                                    <input type="hidden" name="contactID" value="<?php echo $this->e['contactID']; ?>">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="salutation" class="col-sm-2 control-label"><?php echo $this->translate('title'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static"><?php echo $this->e['salutation']; ?></p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="salutation" id="salutation" placeholder="<?php echo $this->translate('title');?>" value="<?php echo $this->e['salutation']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sex" class="col-sm-2 control-label"><?php echo $this->translate('sex'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['SEX'], $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?>
                                        </p>
                                    <?php else: ?>
                                        <select class="form-control" name="sex" id="sex">
                                            <?php echo $this->ShowDictionaryList($this->dic_Setting['SEX'], $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?>
                                        </select>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="birthdate" class="col-sm-2 control-label"><?php echo $this->translate('birthday'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php if ($this->e['birthdate']) {
                                                echo date('Y-m-d', strtotime($this->e['birthdate']));
                                            } else {
                                                echo null;
                                            } ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="birthdate" id="birthdate" placeholder="yyyy-MM-dd" <?php if (!empty($this->e['birthdate'])) { echo "value='". date('Y-m-d', strtotime($this->e['birthdate']) )."'"; }; ?> >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <?php if ($this->account->regdCountryCode == 'CN'): ?>
                            <div class="form-group">
                                <label for="identityType" class="col-sm-2 control-label"><?php echo $this->translate('certificateType'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['ID_TYPE'], $this->userLangCode, $this->dic_Setting['ID_TYPE'], $this->e['identityType']); ?>
                                        </p>
                                    <?php else: ?>
                                        <select class="form-control" name="identityType" id="identityType">
                                            <?php echo $this->ShowDictionaryList($this->dic_Setting['ID_TYPE'], $this->userLangCode, $this->dic_Setting['ID_TYPE'], $this->e['identityType']); ?>
                                        </select>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="identityNo" class="col-sm-2 control-label"><?php echo $this->translate('certificateNo'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['identityNo']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="identityNo" id="identityNo" placeholder="<?php echo $this->translate('certificateNo');?>" value="<?php echo $this->e['identityNo'];?>" >
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif;?>

                            <div class="form-group">
                                <label for="department" class="col-sm-2 control-label"><?php echo $this->translate('division'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['department']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="department" id="department" placeholder="<?php echo $this->translate('division');?>" value="<?php echo $this->e['department']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title" class="col-sm-2 control-label"><?php echo $this->translate('job'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['title']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="title" id="title" placeholder="<?php echo $this->translate('job');?>" value="<?php echo $this->e['title']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="email" class="col-sm-2 control-label"><?php echo $this->translate('email'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['email']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="email" class="form-control" name="email" id="email" placeholder="<?php echo $this->translate('is_emails');?>" value="<?php echo $this->e['email']; ?>" required>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="mobilePhone" class="col-sm-2 control-label"><?php echo $this->translate('mobile'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['mobilePhone']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="mobilePhone" id="mobilePhone" placeholder="<?php echo $this->translate('is_phone');?>" value="<?php echo $this->e['mobilePhone']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="phone" class="col-sm-2 control-label"><?php echo $this->translate('telephone'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['phone']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="phone" id="phone" placeholder="<?php echo $this->translate('is_tel');?>" value="<?php echo $this->e['phone']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="fax" class="col-sm-2 control-label"><?php echo $this->translate('fax'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['ecommstatus'] == 'AT'): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['fax']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="fax" id="fax" placeholder="<?php echo $this->translate('fax');?>" value="<?php echo $this->e['fax']; ?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('elogname'); ?></label>
                                <div class="col-sm-9">
                                    <p class="form-control-static">
                                        <?php if (!empty($this->e['ecommloginname'])) {
                                            echo $this->e['ecommloginname'];
                                        } else {
                                            echo $this->translate('noRegister');
                                        } ?>
                                    </p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('userP'); ?></label>
                                <div class="col-sm-9">
                                    <p class="form-control-static">
                                        <?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_STATUS'], $this->e['ecommstatus']); ?>
                                    </p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="" class="col-sm-2 control-label"><?php echo $this->translate('userROLE'); ?></label>
                                <div class="col-sm-9">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompUser" <?php if (in_array("CompUser", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompUser');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompOrderAdmin" <?php if (in_array("CompOrderAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompOrderAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompClerk" <?php if (in_array("CompClerk", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompClerk');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompProductAdmin" <?php if (in_array("CompProductAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompProductAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompPartnerAdmin" <?php if (in_array("CompPartnerAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompPartnerAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="SOAdmin" <?php if (in_array("SOAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('SOAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="TOAdmin" <?php if (in_array("TOAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('TOAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompPublicInfoAdmin" <?php if (in_array("CompPublicInfoAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompPublicInfoAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompAdmin" <?php if (in_array("CompAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="DeclarationAdmin" <?php if (in_array("DeclarationAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('DeclarationAdmin');?>
                                        </label>
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="ecommrole[]" value="CompSettleAdmin" <?php if (in_array("CompSettleAdmin", $this->ecommrole)) { echo 'checked="checked"';} ?>>
                                            <?php echo $this->translate('CompSettleAdmin');?>
                                        </label>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="isPublicContact" class="col-sm-2 control-label"><?php echo $this->translate('orderContact'); ?></label>
                                <div class="col-sm-9">
                                    <label class="radio-inline">
                                        <input type="radio" name="isPublicContact" value="1" <?php if ($this->e['isPublicContact']) { echo "checked='checked'"; } ?>> <?php echo $this->translate('yes');?>
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="isPublicContact" value="0" <?php if (!($this->e['isPublicContact'])) { echo "checked='checked'"; } ?>> <?php echo $this->translate('no');?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-12 col-md-9 col-md-offset-2">
                                    <button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('save'); ?></button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        var layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            var laydate = layui.laydate;

            // 直接嵌套显示
            laydate.render({
                elem: '#birthdate'
                ,trigger: 'click'
                ,lang: layDateLang
            });
        });
	});
</script>
</body>
</html>
