<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/account/account.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('personNO'); ?></div>
                    <div class="panel-body">
                        <form class="form-inline" action="javascript:void(0)" onsubmit="contactSearch()" id="contact_search_form">
                            <div class="form-group" style="margin-bottom: 0 !important;">
                                <label for="keyword" class="sr-only">keyword</label>
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="fas fa-search"></i></span>
                                    <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('INPkw_ac');?>">
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary"> Go </button>
                        </form>
                    </div>

                    <!-- Table -->
                    <table id="contactListTable"></table>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $('#contactListTable').bootstrapTable({
            url: '/user/account/contactlistajax',
            method: 'post',
            // showRefresh: true,
            // search: true,
            pagination: true,
            classes: 'table table-no-bordered',
            sidePagination: 'server',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            pageNumber: 1,
            pageSize: 10,
            queryParams: function(params) {
                return {
                    limit: params.limit,
                    skip: params.offset,
                    keyword: params.search
                };
            },
            columns: [{
                field: 'name',
                title: '<?php echo $this->translate("name"); ?>'
            }, {
                field: 'ecommloginname',
                title: '<?php echo $this->translate("username"); ?>'
            }, {
                field: 'ecommstatus',
                title: '<?php echo $this->translate("userP"); ?>',
                formatter: function (value) {
                    console.log(value);
                    return '<?php echo $this->ShowDictionaryTo($this->dic_Setting["ECOMM_STATUS"], $this->userlangCode, $this->dic_Setting["ECOMM_STATUS"], ' + value + '); ?>';
                }
            }, {
                field: 'ecommrole',
                title: '<?php echo $this->translate("userROLE"); ?>'
            }, {
                field: 'contactStatus',
                title: '<?php echo $this->translate("userPT"); ?>',
                formatter: function (value) {
                    return (value === '01') ? '<?php echo $this->translate('normal') ?>' : '<?php echo $this->translate('disable'); ?>';
                }
            }, {
                field: 'isDefaultPublic',
                title: '<?php echo $this->translate("accountDF"); ?>',
                formatter: function (value) {
                    return (value === true) ? '<?php echo $this->translate('yes') ?>' : '<?php echo $this->translate('no'); ?>';
                }
            }, {
                title: '<?php echo $this->translate("madeTT"); ?>',
                formatter: function (value, row, index) {
                    var title = "<?php echo $this->translate("edit");?>";
                    var href = "<?php echo '/user/account/edit?'.base64_encode(" + row.contactID + ");?>";

                    return '<a title="' + title+ '" class="p_ed" href="' + href + '">'
                        + '<i class="far fa-edit"></i>'
                        + '</a>';
                }
            }]
        });

        $("#searchContactBtn").click(function () {
            contactSearch();
        });

	});

	function contactSearch() {
        var contactListTable = $('#contactListTable');
        var opt = {
            query:{
                keyword: $("#keyword").val()
            }
        };
        $(contactListTable).bootstrapTable('refresh', opt);
    }
</script>
</body>
</html>
