<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->escape($this->seed_Setting['www_html_title']);?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/seed.form.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.form.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript" src="/ky/layer-v3.1.1/layer.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL.'/account/r_top_menu.phtml');?>
        <div class="qysearch_box user_search">
            <form action="#" method="post">
                    <input class="search_inp" name="keyword" placeholder="<?php echo $this->translate('INPkw_ac');?>" type="text">
                    <input class="ss_btn" type="submit" value="">
                    <a href=<?php if($this->PStatus=='01'){ echo '/user/account/index-00-1.html';}else{echo '/user/account/index-01-1.html';}?>> <span class="ac_all_st"><em  <?php if($this->PStatus!='01'){ echo 'class="ac_all_bg"';}?>></em></span></a><span class="ac_all_t"><?php echo $this->translate('CHK_account');?></span>
                <?php if($this->CompAdmin==true && count($this->account_isAllowAdd)>0):?>
                <!--新增--><a title="<?php echo $this->translate('add');?>" href=<?php echo '/user/account/add';?> class="addb_box fr"></a>
               <?php endif;?>
            </form>
        </div>
        <table class="qy_table user_table1">
            <thead>
            <tr>
                <th width="150"><!-- 姓名 --><?php echo $this->translate('name');?></th>
                <th width="200"><!-- 用户名 --><?php echo $this->translate('username');?></th>
                <th width="70"><!-- 用户状态 --><?php echo $this->translate('userP');?></th>
                <th width="200"><!-- 角色 --><?php echo $this->translate('userROLE');?></th>
                <th width="70"><!-- 员工状态 --><?php echo $this->translate('userPT');?></th>
                <th width="70"><!-- 是否默认 --><?php echo $this->translate('accountDF');?></th>
                <th width="80"><!-- 操作 --><?php echo $this->translate('madeTT');?></th>
            </tr>
            </thead>
            <tbody>
            <?php if(is_array($this->userList) && count($this->userList)>0):?>
                <?php foreach ($this->userList as $k=>$ulist):?>
                    <tr style="height: 71px;">
                        <td><a href="<?php if(!empty($this->account_isAllowView)){echo '/user/account/view?'.base64_encode($ulist['contactID']);}?>"><?php echo $ulist['name'];?></a></td>
                        <td><a href="<?php if(!empty($this->account_isAllowView)){echo '/user/account/view?'.base64_encode($ulist['contactID']);}?>"><?php echo $ulist['ecommloginname'];?></a></td>
                        <td><a href="<?php if(!empty($this->account_isAllowView)){echo '/user/account/view?'.base64_encode($ulist['contactID']);}?>">
                                <?php echo $this->ShowDictionaryTo('datatest_setting',$this->userLangCode,$this->dic_Setting['ECOMM_STATUS'],$ulist['ecommstatus']);?>
                            </a></td><!--用户状态 字典代码 ECOMM_STATUS-->
                        <td><dl class="acct_role">
                                <?php $role_name="";if($ulist['ecommrole']):?>
                                    <?php foreach (explode(",",$ulist['ecommrole']) as $k2=>$roleDD):?>
                                        <?php $role_name.=$this->ShowDictionaryTo('datatest_setting',$this->userLangCode,$this->dic_Setting['ECOMM_ROLE'],$roleDD).',';?>
                                    <?php endforeach;?>
                                <?php endif;?>
                                <a title="<?php echo $role_name;?>"
                                   href="<?php if(!empty($this->account_isAllowView)){echo '/user/account/view?'.base64_encode($ulist['contactID']);}?>">
                                    <?php echo $role_name;?></a>
                               </dl></td>
                        <!--员工状态 字典代码 CONTACT_STATUS-->
                        <td>
                            <a href="#" >
                                <?php echo $ulist['contactStatus']=='01'?$this->translate('normal'):$this->translate('disable');?></a></td>
                        <!--是否默认联系人-->
                        <td>
                            <a href="#" href="javascript:;" id="<?php echo $ulist['contactID'];?>" data-url="/user/account/default"
                               data-msg1="<?php echo $this->translate('is_default');?>" data-msg2="<?php echo $this->translate('tip_default_success');?>"
                               data-msg3="<?php echo $this->translate('tip_default_fail');?>" <?php if($this->CompAdmin==true){echo'onclick="doOption(this);"';}?>>
                                <?php if($ulist['isDefaultPublic']==true){echo $this->translate('yes');}else{echo $this->translate('no');};?></a>
                        </td>

                        <td>
                            <div class="cc_box">
                                <a title="<?php echo $this->translate('edit');?>" class="p_ed" href="<?php echo '/user/account/edit?'.base64_encode($ulist['contactID']);?>"></a>
                                <?php  if($this->CompAdmin==true):?>
                                <!--禁用-->   <a title="<?php echo $this->translate('disable');?>"  <?php if ($ulist['contactStatus']=='01'){echo 'style="display:inline-block;"';}?>  class="t_edit p_jy"
                                               href="javascript:;" id="<?php echo $ulist['contactID'];?>" data-url="/user/account/invalid"
                                               data-msg1="<?php echo $this->translate('is_invalid');?>" data-msg2="<?php echo $this->translate('tip_invalid_success');?>"
                                               data-msg3="<?php echo $this->translate('tip_invalid_fail');?>" onclick="doOption(this);"></a>

                               <!--启用-->   <a title="<?php echo $this->translate('enable');?>" <?php if ($ulist['contactStatus']=='02'){  echo 'style="display:inline-block;"';}?>  class="t_edit p_qy"
                                              href="javascript:;" id="<?php echo $ulist['contactID'];?>" data-url="/user/account/valid"
                                              data-msg1="<?php echo $this->translate('is_valid');?>" data-msg2="<?php echo $this->translate('tip_valid_success');?>"
                                              data-msg3="<?php echo $this->translate('tip_valid_fail');?>" onclick="doOption(this);"></a>
                                <?php endif;?>

                            </div>
                        </td>
                    </tr>
                <?php endforeach; ?>
            <?php else:?>
                <tr><td colspan="7"> <?php echo $this->translate('noData');?></td></tr>
            <?php endif;?>
            </tbody>
        </table>
        <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
    </div>
</div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script>
    function doOption(obj){
        var url=$(obj).attr('data-url');
        var id=$(obj).attr('id');
        var msg1=$(obj).attr('data-msg1');
        var msg2=$(obj).attr('data-msg2');
        var msg3=$(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title:false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>','<?php echo $this->translate('no');?>'] //按钮
        }, function(){
            $.post( url,
                {'delID':id},
                function(data){
                    if( data.status == 1){
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">'+msg2+'</span>', {skin:'del-class',icon: 1});
                        parent.window.location.reload();
                    }
                    else{
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">'+msg3+'</span><br>'+data.error, {skin:'del-class',icon: 0});
                        parent.window.location.reload();
                    }
                },"json");

        }, function(){
            layer.closeAll();
        });
    }

</script>
</body>
</html>
