<div class="o_tab">
    <ul>
        <li><a href="<?php echo WWW;?>user/company/index"><!-- 公司信息 --><?php echo $this->translate('company_info');?></a></li>
        <li class="cur"><a href="<?php echo WWW;?>user/account/index"><!-- 员工信息 --><?php echo $this->translate('personNO');?></a></li>
        <li><a href="<?php echo WWW;?>user/bank/index"><!-- 银行账户 --><?php echo $this->translate('bankNO');?></a></li>
    </ul>
</div>
