<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->escape($this->seed_Setting['www_html_title']); ?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript" src="/ky/layer-v3.1.1/layer.js"></script>
    <style type="text/css">
        #acEmail, #acLogin {
            width: 40px;
            height: 25px;
            line-height: 25px;
            color: #fff;
            text-align: center;
            margin: 0 10px;
            display: inline-block;
            background: #ff8c21;
            border-radius: 5px;
            border: 1px solid #de6e06;
        }
    </style>
    <script>
        $(document).ready(function () {

            $('#acEmail').click(function () {
                //询问框
                layer.confirm('<?php echo $this->translate('tip_active_00')?>', {
                    title: false,
                    btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
                }, function () {
                    $.post('<?php echo $this->BaseUrl();?>/check/contactinviteemailnotice',
                        {'contactID':'<?php echo $this->e['contactID'];?>'},
                        function (data) {

                            layer.msg(data, {icon: 1});
                            location.href = '<?php echo $this->BaseUrl();?>/account/view?<?php echo base64_encode($this->e['contactID']);?>';

                        }, "json");

                }, function () {
                    layer.closeAll();
                });
            });
        });
    </script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL . '/header.phtml'); ?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL . '/left_menu.phtml'); ?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL . '/account/r_top_menu.phtml'); ?>
        <div class="n_o_c_tit">
            <h4><!--查看员工资料--><?php echo $this->translate('view') . $this->translate('baseINF'); ?></h4>
            <?php if ($this->CompAdmin == true): ?>
                <a class="p_ed fr mt10"
                   href="<?php echo WWW . 'user/account/edit?' . base64_encode($this->e['contactID']); ?>"></a>
            <?php endif; ?>
        </div>
        <div class="o_c_content">
            <form action="#" method="post">
                <table>
                    <tbody>
                    <tr>
                        <td><span><!-- 姓名： --><?php echo $this->translate('name'); ?></span></td>
                        <td><?php echo $this->e['name']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 称谓： --><?php echo $this->translate('title'); ?></span></td>
                        <td><?php echo $this->e['salutation']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 性别： --><?php echo $this->translate('sex'); ?></span></td>
                        <td><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 生日： --><?php echo $this->translate('birthday'); ?></span></td>
                        <td><?php echo date('Y-m-d', strtotime($this->e['birthdate'])); ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 部门： --><?php echo $this->translate('division'); ?></span></td>
                        <td><?php echo $this->e['department']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 公司职务 --><?php echo $this->translate('job'); ?></span></td>
                        <td><?php echo $this->e['title']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 电子邮箱： --><?php echo $this->translate('email'); ?></span></td>
                        <td><?php echo $this->e['email']; ?>
                        <?php if (!empty($this->e['email']) && $this->e['ecommstatus'] == "IN"&& $this->CompAdmin == true): ?>
                        <a href="#" id="acEmail"><?php echo $this->translate('invitation'); ?></a>
                        <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span><!-- 移动电话： --><?php echo $this->translate('mobile'); ?></span></td>
                        <td><?php echo $this->e['mobilePhone']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 固定电话： --><?php echo $this->translate('telephone'); ?></span></td>
                        <td><?php echo $this->e['phone']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 传真： --><?php echo $this->translate('fax'); ?></span></td>
                        <td><?php echo $this->e['fax']; ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 登录名 --><?php echo $this->translate('elogname'); ?></span></td>
                        <td>
                            <?php if(!empty($this->e['ecommloginname'])){echo $this->e['ecommloginname'];}else{echo $this->translate('noRegister');}?>
                        </td>
                    </tr>
                    <tr>
                        <td><span><!-- 用户状态 --><?php echo $this->translate('userP'); ?></span></td>
                        <td><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_STATUS'], $this->e['ecommstatus']); ?>
                        </td>
                    </tr>
                    <tr>
                        <td><span><!-- 默认联系人 --><?php echo $this->translate('Df_Contact'); ?></span></td>
                        <td>
                            <?php if ($this->e['isDefaultPublic'] == true) {
                                echo $this->translate('yes');
                            } else {
                                echo $this->translate('no');
                            } ?></td>
                    </tr>
                    <tr>
                        <td><span><!-- 订单联系人 --><?php echo $this->translate('orderContact'); ?></span></td>
                        <td>
                            <?php if ($this->e['isPublicContact'] == true) {
                                echo $this->translate('yes');
                            } else {
                                echo $this->translate('no');
                            } ?></td>
                    </tr>
                    <tr style="width:100%;">
                        <td><span><!-- 平台角色 --><?php echo $this->translate('userROLE'); ?></span></td>
                        <td>
                            <?php if ($this->e['ecommrole']): ?>
                                <?php foreach (explode(",", $this->e['ecommrole']) as $k2 => $roleDD): ?>
                                    <?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_ROLE'], $roleDD) . ','; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL . '/footer.phtml'); ?>
</body>
</html>
