<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/account/account.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 account-view">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('personNO'); ?></div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <h3>
                                        <?php if ($this->CompAdmin == true): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/account/edit?' . base64_encode($this->e['contactID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->e['name']; ?>
                                    </h3>

                                    <dl class="dl-horizontal">
                                        <dt><?php echo $this->translate('title'); ?></dt>
                                        <dd><?php echo $this->e['salutation']; ?></dd>

                                        <dt><?php echo $this->translate('sex'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo($this->dic_Setting['SEX'], $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?></dd>

                                        <dt><?php echo $this->translate('birthday'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['birthdate']) {
                                                echo date('Y-m-d', strtotime($this->e['birthdate']));
                                            } else {
                                                echo null;
                                            } ?>
                                        </dd>

                                        <dt><?php echo $this->translate('division'); ?></dt>
                                        <dd><?php echo $this->e['department']; ?></dd>

                                        <dt><?php echo $this->translate('job'); ?></dt>
                                        <dd><?php echo $this->e['title']; ?></dd>

                                        <dt><?php echo $this->translate('email'); ?></dt>
                                        <dd>
                                            <?php echo $this->e['email']; ?>
                                            <?php if (!empty($this->e['email']) && $this->e['ecommstatus'] == "IN" && $this->CompAdmin == true): ?>
                                                <a href="javascript:void(0)" id="acEmail"><?php echo $this->translate('invitation'); ?></a>
                                            <?php endif; ?>
                                        </dd>

                                        <dt><?php echo $this->translate('mobile'); ?></dt>
                                        <dd><?php echo $this->e['mobilePhone']; ?></dd>

                                        <dt><?php echo $this->translate('telephone'); ?></dt>
                                        <dd><?php echo $this->e['phone']; ?></dd>

                                        <dt><?php echo $this->translate('fax'); ?></dt>
                                        <dd><?php echo $this->e['fax']; ?></dd>

                                        <dt><?php echo $this->translate('elogname'); ?></dt>
                                        <dd><?php if(!empty($this->e['ecommloginname'])){echo $this->e['ecommloginname'];}else{echo $this->translate('NoRegister');}?></dd>

                                        <dt><?php echo $this->translate('userP'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_STATUS'], $this->e['ecommstatus']); ?></dd>

                                        <dt><?php echo $this->translate('Df_Contact'); ?></dt>
                                        <dd>
                                            <?php
                                            if ($this->e['isDefaultPublic'] == true) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            }
                                            ?>
                                        </dd>

                                        <dt><?php echo $this->translate('orderContact'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['isPublicContact'] == true) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            } ?>
                                        </dd>

                                        <dt><?php echo $this->translate('userROLE'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['ecommrole']): ?>
                                                <?php foreach (explode(",", $this->e['ecommrole']) as $k2 => $roleDD): ?>
                                                    <?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_ROLE'], $roleDD) . ','; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });
	});
</script>
</body>
</html>
