<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/company/company.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 company-main">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('personNO'); ?></div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-10">
                                    <h3>
                                        <?php if ($this->CompAdmin == true): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="/user/company/edit">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->e['accountName']; ?>
                                        <small>
                                            <a href="javascript:void(0)">
                                                <?php if ($this->e['entRealAuthStatus'] == 0 || $this->e['entRealAuthStatus'] == -1 || $this->e['entRealAuthStatus'] == -4): ?>
                                                    <span id="company-auth" class="et-ico et-ico-auth-cno" data-toggle="modal" data-target="#authModal"></span>
                                                <?php elseif ($this->e['entRealAuthStatus'] == 1 || $this->e['entRealAuthStatus'] == 3 || $this->e['entRealAuthStatus'] == -2 || $this->e['entRealAuthStatus'] == -3): ?>
                                                    <span id="company-auth" class="et-ico et-ico-auth-cing" data-toggle="modal" data-target="#authModal"></span>
                                                <?php elseif ($this->e['entRealAuthStatus'] == 2): ?>
                                                    <span id="company-auth" class="et-ico et-ico-auth-cok" data-toggle="modal" data-target="#authModal"></span>
                                                <?php endif; ?>
                                            </a>
                                        </small>
                                    </h3>
                                    <?php if ($this->e['accountEnName']): ?>
                                        <p>
                                            <?php echo $this->e['accountEnName']; ?>
                                        </p>
                                    <?php endif; ?>

                                    <dl class="dl-horizontal">
                                        <dt><?php echo $this->translate('address'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo($this->dic_Setting["COUNTRY_ISO_CODE"], $this->userlangCode, $this->dic_Setting["COUNTRY_ISO_CODE"], $this->e['regdCountryCode']); ?></dd>
                                        <dd><?php echo $this->regdCountryCode . $this->e['regdAddress']; ?></dd>
                                        <?php if ($this->e['regdEnAddress']): ?>
                                            <dd><?php echo $this->e['regdEnAddress']; ?></dd>
                                        <?php endif; ?>

                                        <dt><?php echo $this->translate('email'); ?></dt>
                                        <dd>
                                            <?php echo $this->e['email']; ?>
                                            <?php if ($this->CompAdmin == true): ?>
                                                <?php if (empty($this->e['emailVerifyTime'])): ?>
                                                    <button type="button" id="acEmail" class="btn btn-warning btn-xs"><?php echo $this->translate('verify'); ?></button>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </dd>

                                        <dt><?php echo $this->translate('company_phone'); ?></dt>
                                        <dd><?php echo $this->e['phone']; ?></dd>

                                        <dt><?php echo $this->translate('company_fax'); ?></dt>
                                        <dd><?php echo $this->e['fax']; ?></dd>

                                        <dt><?php echo $this->translate('company_website'); ?></dt>
                                        <dd><?php echo $this->e['website']; ?></dd>

                                        <dt><?php echo $this->translate('company_incorporation_date'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['incorporationDate']) {
                                                echo date('Y-m-d', strtotime($this->e['incorporationDate']));
                                            } else {
                                                echo null;
                                            } ?>
                                        </dd>

                                        <dt><?php echo $this->translate('industry'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['ISIC_INDUSTRY_TYPE'], $this->e['industryCode']); ?>
                                        </dd>

                                        <dt><?php echo $this->translate('company_legal_form'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['ACCOUNT_LEGALFORM'], $this->e['legalForm']); ?></dd>

                                        <dt><?php echo $this->translate('businessLicenseNo'); ?></dt>
                                        <dd><?php echo $this->e['businessLicenseNo']; ?></dd>

                                        <dt><?php echo $this->translate('ECC'); ?></dt>
                                        <dd><?php echo $this->e['customsCode']; ?></dd>

                                        <dt><?php echo $this->translate('crnCode'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['CURRENCY'], $this->e['crnCode']); ?></dd>

                                        <dt><?php echo $this->translate('langCode'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userlangCode, $this->dic_Setting['SYS_LANG'], $this->e['langCode']); ?></dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });
	});
</script>
</body>
</html>
