<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/account/account.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 account-view">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('personNO'); ?></div>
                    <div class="panel-body">
                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <h3>
                                        <?php if ($this->CompAdmin == true): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/account/edit?' . base64_encode($this->e['contactID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->e['name']; ?>
                                    </h3>

                                    <dl class="dl-horizontal">
                                        <dt><?php echo $this->translate('title'); ?></dt>
                                        <dd><?php echo $this->e['salutation']; ?></dd>

                                        <dt><?php echo $this->translate('sex'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo($this->dic_Setting['SEX'], $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?></dd>

                                        <dt><?php echo $this->translate('birthday'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['birthdate']) {
                                                echo date('Y-m-d', strtotime($this->e['birthdate']));
                                            } else {
                                                echo null;
                                            } ?>
                                        </dd>

                                        <dt><?php echo $this->translate('division'); ?></dt>
                                        <dd><?php echo $this->e['department']; ?></dd>

                                        <dt><?php echo $this->translate('job'); ?></dt>
                                        <dd><?php echo $this->e['title']; ?></dd>

                                        <dt><?php echo $this->translate('email'); ?></dt>
                                        <dd>
                                            <?php echo $this->e['email']; ?>
                                            <?php if (!empty($this->e['email']) && $this->e['ecommstatus'] == "IN" && $this->CompAdmin == true): ?>
                                                <button type="button" id="acEmail" class="btn btn-warning btn-xs"><?php echo $this->translate('invitation'); ?></button>
                                            <?php endif; ?>
                                        </dd>

                                        <dt><?php echo $this->translate('mobile'); ?></dt>
                                        <dd><?php echo $this->e['mobilePhone']; ?></dd>

                                        <dt><?php echo $this->translate('telephone'); ?></dt>
                                        <dd><?php echo $this->e['phone']; ?></dd>

                                        <dt><?php echo $this->translate('fax'); ?></dt>
                                        <dd><?php echo $this->e['fax']; ?></dd>

                                        <dt><?php echo $this->translate('elogname'); ?></dt>
                                        <dd><?php if(!empty($this->e['ecommloginname'])){echo $this->e['ecommloginname'];}else{echo $this->translate('NoRegister');}?></dd>

                                        <dt><?php echo $this->translate('userP'); ?></dt>
                                        <dd><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_STATUS'], $this->e['ecommstatus']); ?></dd>

                                        <dt><?php echo $this->translate('企业签署人'); ?></dt>
                                        <dd>
                                            <?php
                                            if ($this->e['isDefaultPublic'] == true) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            }
                                            ?>
                                            &nbsp;&nbsp;
                                            <button type="button" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#changeSigningAgent">
                                                <i class="fas fa-signature"></i> 设为签署人
                                            </button>
                                        </dd>

                                        <dt><?php echo $this->translate('Df_Contact'); ?></dt>
                                        <dd>
                                            <?php
                                            if ($this->e['isDefaultPublic'] == true) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            }
                                            ?>
                                        </dd>

                                        <dt><?php echo $this->translate('orderContact'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['isPublicContact'] == true) {
                                                echo $this->translate('yes');
                                            } else {
                                                echo $this->translate('no');
                                            } ?>
                                        </dd>

                                        <dt><?php echo $this->translate('userROLE'); ?></dt>
                                        <dd>
                                            <?php if ($this->e['ecommrole']): ?>
                                                <?php foreach (explode(",", $this->e['ecommrole']) as $k2 => $roleDD): ?>
                                                    <?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ECOMM_ROLE'], $roleDD) . ','; ?>
                                                <?php endforeach; ?>
                                            <?php endif; ?>
                                        </dd>
                                    </dl>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<!-- 修改签署人 -->
<div class="modal fade" id="changeSigningAgent" tabindex="-1" role="dialog" aria-labelledby="changeSigningAgentLabel">
    <div class="modal-dialog modal-sm" role="document" style="width: 550px;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('变更企业签署人'); ?></h4>
            </div>

            <div class="modal-body">
                <div class="layui-form-item table-responsive">
                    <form>
                        <div class="form-group">
                            <label for="signMobileInput"><?php echo $this->translate('signAuthType'); ?></label>
                            <input type="text" class="form-control" id="signMobileInput" name="signMobileInput" value="<?php echo $this->translate('mobile_phone').' '. substr($this->mobilePhone, 0, 3) . '*****' . substr($this->mobilePhone, 8, strlen($this->mobilePhone));?>" readonly="readonly">
                        </div>

                        <div class="form-group">
                            <label class="control-label sr-only" for="authCode">authCode</label>
                            <div class="row" style="margin-right: 0;">
                                <div class="col-sm-7">
                                    <input type="text" class="form-control" id="authCode" name="authCode" placeholder="<?php echo $this->translate('signInputAuthCode'); ?>">
                                </div>
                                <div class="col-sm-5">
                                    <button type="button" id="signSendAuthCodeBtn" class="btn btn-primary"><?php echo $this->translate('signSendAuthCode'); ?></button>
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="row" style="margin-right: 0;">
                                <div class="col-sm-10">
                                    <button type="submit" id="singConfirmBtn" class="btn btn-primary btn-block" data-content-id="<?php echo $this->e['contactID']; ?>">
                                        <?php echo $this->translate('confirmed'); ?>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $('#acEmail').click(function () {
            //询问框
            layer.confirm('<?php echo $this->translate('tip_active_00')?>', {
                title: false,
                btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
            }, function () {
                $.post('<?php echo $this->BaseUrl();?>/check/contactinviteemailnotice',
                    {'contactID': '<?php echo $this->e['contactID'];?>'},
                    function (data) {

                        layer.msg(data, {icon: 1});
                        location.href = '<?php echo $this->BaseUrl();?>/account/view?<?php echo base64_encode($this->e['contactID']);?>';

                    }, "json");

            }, function () {
                layer.closeAll();
            });
        });

        // 修改企业签署人 获取短信验证码
        $("#signSendAuthCodeBtn").click(function () {
            var sendSignAuthCode = '/user/account/send-mobile-auth-code';

            $.ajax({
                type: "POST",
                url: sendSignAuthCode,
                data: {

                },
                dataType: "json",
                success: function () {
                    var sendingStr = "<?php echo $this->translate('signAuthCodeSending');?>";
                    $("#signSendAuthCodeBtn").text(sendingStr);
                    sendSignAuthCodeCountDown();
                }
            });
        });

        // 修改企业签署人
        $("#singConfirmBtn").click(function () {
            var doSignPDF = '/user/account/change-signing-agent';
            var contractID = $(this).attr("data-contact-id");

            $.ajax({
                type: "POST",
                url: doSignPDF,
                data: {
                    contractID: contractID,
                    authCode: $("#authCode").val()
                },
                dataType: "json",
                success: function (data) {
                    var signMsg = "<?php echo $this->translate('signFail');?>";
                    if (data !== null && data !== '') {
                        signMsg = "<?php echo $this->translate('signSuccess');?>";
                        // layer.msg(signMsg);
                        // window.location.reload();
                    } else {
                        $("#signAuthCode").val('');
                        // layer.msg(signMsg);
                    }
                }
            });
        });
	});

    var countdown=120;
    function sendSignAuthCodeCountDown() {
        var obj = $("#signSendAuthCodeBtn");
        setTimeTxt(obj);
    }

    function setTimeTxt(obj) { //发送验证码倒计时
        if (countdown === 0) {
            obj.attr('disabled',false);
            var authCodeStr = "<?php echo $this->translate('signSendAuthCode'); ?>";
            obj.text(authCodeStr);
            countdown = 120;
            return;
        } else {
            console.log(countdown);
            obj.attr('disabled',true);
            var btnStr = "<?php echo $this->translate('signAuthCodeSending'); ?>";
            obj.text(btnStr + "(" + countdown + ")");
            countdown--;
        }
        setTimeout(function() {
                setTimeTxt(obj) }
            ,1000);
    }
</script>
</body>
</html>
