<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>选择图片</title>
<style type="text/css">
html{font-size:12px; font-family:"宋体";color:#666;}
body,div,ul,li,p,dl,dt,dd,input,form{margin:0; padding:0;}
ul{list-style:none;}
img{border:0;}
.file_show{width:100%;float:left;}
.file_show div{padding-left:20px;padding-top:10px;text-align:left;font-weight:bold;}
	    .file_show ul{float:left;width:100%;padding-bottom:10px;}
	    .file_show li{width:100%;height:30px;float:left;line-height:25px;padding:10px 10px 0;}
		  .file_show li p{width:100%;float:left;text-align:center;}
		    .file_show li p strong{width:100px;float:left;height:25px;overflow:hidden;}
			.file_show li p small{width:65px;float:right;height:25px; text-align:right;}
			  .file_show li p small a{color:#fc9b4d;}
.page {
color:#686868;
line-height:25px;
text-align:right;
}
.page strong {
font-weight:normal;
padding-right:10px;
}
.page a {
color:#008DBA;
margin:0 10px;
}
</style>
</head>
<body>
<div class="file_show">
    <div class="page"> 【<a href="<?php echo $this->BaseUrl();?>/testfile/upload?name=<?php echo ($this->name);?>">上传文件</a>】 <?php echo $this->showPage($this->page);?></div>
	<ul>
		<?php if(is_array($this->files)):?>
		<?php foreach($this->files as $file):?>
		<li>
			<p>
				<?php echo ($file['file_name']);?> &nbsp;
			</p>
		</li>
	  	<?php endforeach; ?>
		<?php endif;?>
	</ul>
</div>
</body>
</html>