<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$('input[@type=checkbox][@name=checkAll]').each(function(){
		$(this).checkbox().toggle($(this).val());
	});
    <?php if(isset($this->conditions['is_actived'])):?>
    $("#is_actived").val('<?php echo $this->conditions['is_actived'];?>');
    <?php endif;?>
});

//删除
function deleteAll(){
	var ids="";
    $("[name='chose[]'][checked]").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->BaseUrl();?>/messagetemplate/delete?temp_ids="+ids;
}
</script>

<h1>短信息模板</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/messagetemplate/add'"/>
  </p>
</div>
<div class="main">
  <table class="admin_list">
    <tr>
      <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
        <label for="checkAll">全选</label></th>
      <th>模板名称</th>
      <th>模板标题</th>
      <th>是否激活</th>
      <th>操作</th>
    </tr>
    <?php if(is_array($this->temps)):?>
    <?php foreach($this->temps as $temp):?>
    <tr>
      <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($temp['temp_id'])?>" class="ids_all"></td>
      <td><?php echo ($temp['temp_name']);?></td>
      <td><?php echo ($temp['temp_title']);?></td>
      <td><?php echo ($temp['is_actived']=='1')?'<img src="/images/center/yes.gif">':'<img src=/images/center/no.gif>';?></td>
      <td><a href="<?php echo $this->BaseUrl();?>/messagetemplate/update?temp_id=<?php echo ($temp['temp_id']);?>"><img src="/images/center/edit.gif" title="编辑资料" alt="编辑资料"></a></td>
    </tr>
    <?php endforeach; ?>
    <?php endif;?>
  </table>
</div>
<div class="batch">
  <input type="submit" class="admin_bnt2" name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">
  &nbsp; </div>
<?php echo $this->render("footer.phtml") ?> 