<h1>快移交易平台企业实名指引</h1>
<h2>简介</h2>
<p>通过成功注册，登录快移交易平台（简称：平台）。平台明确定义企业注册用户的主体为企业，所有注册用户均基于企业主体下，以职员身份存在平台上。
    首先为企业注册的用户，平台将定义该用户为其企业管理员身份。该用户有权限修改企业信息、员工信息、银行账户信息、企业实名、等操作。同时，该用户为其企业在平台上进行电子合同签署的验证码接收人。
    目前，可参考一下说明进行操作。</p>
<h2>注册</h2>
<ol>
    <li>打开浏览器(推荐使用最新版本的Chrome 或 Firefox )，网址栏输入：www.eTradeFast.com。</li>
    <li>进入首页后，点击免费注册进入注册页面。</li>
    <li>
        <p>填写好企业相关信息后，点击“请阅读并同意相关服务条款  《快移交易云平台服务协议》”
        </p>
        <ul>
            <li>企业邮箱：请填写企业日常业务通讯用的邮箱地址</li>
            <li>地址：请与企业营业执照住所地址保存一致</li>
            <li>姓名：请填写当前注册人（首次注册为其企业管理员）姓名</li>
            <li>登录名：请填写登录平台用的登录名，可与企业邮箱一致</li>
            <li>密码：请输入8-12位包含数字、字母的密码</li>
        </ul>
        <img src="/ky/images/help/image001.png" />
    </li>
    <li>
        <p>页面弹出《协议内容》，请认证阅读待右侧滚动条滚动至底部后，方可点击右上角关闭按钮。
            <img src="/ky/images/help/image003.png" /></p>
    </li>
    <li>
        <p>自动返回至注册信息填写页面，点击底部“立即注册”。成功注册后，系统将会跳转至企业首页。</p>
    </li>
</ol>
<h2>企业管理</h2>
<p><img src="/ky/images/help/image005.png" /></p>
<ol>
    <li>
        <p>点击上方功能菜单“公司信息”</p>
    </li>
    <li>
        <p>进入企业信息页后，可对刚注册后的企业信息进行修改后点击保存按钮。</p>
        <ul>
            <li>建议补全企业英文地址、企业联系电话、企业传真、统一社会信用代码、行业等信息，便于提高审核速度
                <img src="/ky/images/help/image007.png" />
                <img src="/ky/images/help/image009.png" /></li>
        </ul>
    </li>
    <li>
        <p>点击左侧银行账户，进入企业银行账户列表后，点击右上角添加按钮。
            <img src="/ky/images/help/image011.png" />
        </p>
    </li>
    <li>
        <p>填写企业银行账户基础信息，并将开户许可证上传至平台。
            <img src="/ky/images/help/image013.png" /></p>
    </li>
    <li>
        <p>添加银行账户成功。
            <img src="/ky/images/help/image015.png" /></p>
    </li>
</ol>
<h2>企业实名</h2>
<ol>
    <li>
        <p>点击左侧公司信息，点击企业名称后的实名图标，进入企业实名流程。
            <img src="/ky/images/help/image017.png" /></p>
    </li>
    <li>
        <p>第一步，填写企业法人代表信息。
            <img src="/ky/images/help/image019.png" /></p>
    </li>
    <li>
        <p>第二步，填写企业银行基本户信息。
            <img src="/ky/images/help/image021.png" /></p>
    </li>
    <li>
        <p>第三步，前一步验证成功后，系统将往基本户打入一笔款项，将收到的金额填写入底部金额输入框后点击确定按钮。如在收到款项前关闭了验证页面或验证过程出现资料有误的情况，请重复企业实名步骤第一点。
            <img src="/ky/images/help/image023.png" /></p>
    </li>
    <li>
        <p>企业实名成功后，实名图标变为绿色。
            <img src="/ky/images/help/image025.png" /></p>
    </li>
</ol>
<h2>个人实名</h2>
<ol>
    <li>
        <p>点击页面上方个人中心。
            <img src="/ky/images/help/image027.png" /></p>
    </li>
    <li>
        <p>在该页面填写好个人基本资料后，点击底部保存按钮。</p>
        <ul>
            <li>移动电话：请填写与本人姓名一致，已通过营运商实名的号码</li>
            <li>身份证号码：请填写本人身份证号码
                <img src="/ky/images/help/image029.png" /></li>
        </ul>
    </li>
    <li>
        <p>再次进入个人中心，点击姓名后的个人实名图标，在弹出页面点击确认即可。如认证不通过，重复个人实名第一点，确认信息无误。
            <img src="/ky/images/help/image031.png" /></p>
    </li>
</ol>



<!--
<h1>快移交易平台企业实名指引</h1>
<h2>简介</h2>
<p>通过成功注册，登录快移交易平台（简称：平台）。平台明确定义企业注册用户的主体为企业，所有注册用户均基于企业主体下，以职员身份存在平台上。
    首先为企业注册的用户，平台将定义该用户为其企业管理员身份。该用户有权限修改企业信息、员工信息、银行账户信息、企业实名、等操作。同时，该用户为其企业在平台上进行电子合同签署的验证码接收人。
    目前，可参考一下说明进行操作。</p>
<h2>注册</h2>
<ol>
    <li>打开浏览器(推荐使用最新版本的Chrome 或 Firefox )，网址栏输入：www.eTradeFast.com。</li>
    <li>进入首页后，点击免费注册进入注册页面。</li>
    <li>
        <p>填写好企业相关信息后，点击“请阅读并同意相关服务条款  《快移交易云平台服务协议》”
        </p>
        <ul>
            <li>企业邮箱：请填写企业日常业务通讯用的邮箱地址</li>
            <li>地址：请与企业营业执照住所地址保存一致</li>
            <li>姓名：请填写当前注册人（首次注册为其企业管理员）姓名</li>
            <li>登录名：请填写登录平台用的登录名，可与企业邮箱一致</li>
            <li>密码：请输入8-12位包含数字、字母的密码
                <img src="https://i.imgur.com/Yhu1KIC.png" /></li>
        </ul>
    </li>
    <li>
        <p>页面弹出《协议内容》，请认证阅读待右侧滚动条滚动至底部后，方可点击右上角关闭按钮。
            <img src="https://i.imgur.com/0BSrza9.png" /></p>
    </li>
    <li>
        <p>自动返回至注册信息填写页面，点击底部“立即注册”。成功注册后，系统将会跳转至企业首页。</p>
    </li>
</ol>
<h2>企业管理</h2>
<p><img src="https://i.imgur.com/f6S2Ub5.png" /></p>
<ol>
    <li>
        <p>点击上方功能菜单“公司信息”</p>
    </li>
    <li>
        <p>进入企业信息页后，可对刚注册后的企业信息进行修改后点击保存按钮。</p>
        <ul>
            <li>建议补全企业英文地址、企业联系电话、企业传真、统一社会信用代码、行业等信息，便于提高审核速度
                <img src="https://i.imgur.com/hcTHOOM.png" />
                <img src="https://i.imgur.com/zRzM3HB.png" /></li>
        </ul>
    </li>
    <li>
        <p>点击左侧银行账户，进入企业银行账户列表后，点击右上角添加按钮。
            <img src="https://i.imgur.com/EmryxpO.png" />
        </p>
    </li>
    <li>
        <p>填写企业银行账户基础信息，并将开户许可证上传至平台。
            <img src="https://i.imgur.com/W9f5uCo.png" /></p>
    </li>
    <li>
        <p>添加银行账户成功。
            <img src="https://i.imgur.com/XBLaSlT.png" /></p>
    </li>
</ol>
<h2>企业实名</h2>
<ol>
    <li>
        <p>点击左侧公司信息，点击企业名称后的实名图标，进入企业实名流程。
            <img src="https://i.imgur.com/d3TJZ0T.png" /></p>
    </li>
    <li>
        <p>第一步，填写企业法人代表信息。
            <img src="https://i.imgur.com/6515sJn.png" /></p>
    </li>
    <li>
        <p>第二步，填写企业银行基本户信息。
            <img src="https://i.imgur.com/iJFUFvF.png" /></p>
    </li>
    <li>
        <p>第三步，前一步验证成功后，系统将往基本户打入一笔款项，将收到的金额填写入底部金额输入框后点击确定按钮。如在收到款项前关闭了验证页面或验证过程出现资料有误的情况，请重复企业实名步骤第一点。
            <img src="https://i.imgur.com/2aReqkZ.png" /></p>
    </li>
    <li>
        <p>企业实名成功后，实名图标变为绿色。
            <img src="https://i.imgur.com/ox3p3Xc.png" /></p>
    </li>
</ol>
<h2>个人实名</h2>
<ol>
    <li>
        <p>点击页面上方个人中心。
            <img src="https://i.imgur.com/ILexrrL.png" /></p>
    </li>
    <li>
        <p>在该页面填写好个人基本资料后，点击底部保存按钮。</p>
        <ul>
            <li>移动电话：请填写与本人姓名一致，已通过营运商实名的号码</li>
            <li>身份证号码：请填写本人身份证号码
                <img src="https://i.imgur.com/aVmE0QS.png" /></li>
        </ul>
    </li>
    <li>
        <p>再次进入个人中心，点击姓名后的个人实名图标，在弹出页面点击确认即可。如认证不通过，重复个人实名第一点，确认信息无误。
            <img src="https://i.imgur.com/7S5sZQ7.png" /></p>
    </li>
</ol>
-->
