<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
    $("#post_form").validate({
       event: "keyup",
       rules: {
       },
       messages: {
       },
       submitHandler: function() {
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/mobileoutbox/import',
                success: function() {
                }
            };
            $('#post_form').ajaxSubmit(options);
        }
    });
});
</script>
<h1>批量发送手机短信</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_form">
    <tr>
      <td><strong>接收手机号：</strong>
        <p>
         <textarea class="textarea" name="send_mobiles" id="send_mobiles" style="height:500px;"></textarea>
        </p></td>
    </tr>
    <tr>
      <td><strong>短信内容：</strong>
        <p>
          <textarea class="textarea" name="send_content" id="send_content"></textarea>
        </p></td>
    </tr>
  </table>
  <table class="admin_form">
    <tr>      <td><input class="admin_bnt"  type="submit" value="提交"/></td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>