<div id="deliveryReceiptDiv" class="layui-form">
	<div class="et-auth-top et-auth-bg-orange" style="height: 60px; text-align: left;">
		<h3><?php echo $this->translate('reGOODS'); ?>&nbsp;<label><?php echo $this->delivery->deliveryNo; ?></label></h3>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="">
		<div style="margin-top: 20px;"></div>

		<div class="layui-form-item">
			<table class="layui-table" lay-skin="line" id="deliveryEditTable">
				<colgroup>
					<col>
					<col width="140">
					<col width="120">
					<col width="80">
					<col width="160">
				</colgroup>
				<thead>
				<tr>
					<th>名称</th>
					<th>型号</th>
					<th>单价</th>
					<th>数量</th>
					<th>总价</th>
				</tr>
				</thead>
				<tbody>
                <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
					<tr>
						<td style="text-align: left"><?php echo $value->productName;?></td>
						<td style="text-align: left"><?php echo $value->productModel;?></td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode;?>&nbsp;
							<label class="buyerUnitPrice_"></label>
							<script type="text/javascript">$(".buyerUnitPrice_").html(formatCurrency(<?php echo $value->buyerUnitPrice;?>, 2));</script>
						</td>
						<td style="text-align: left"><?php echo $value->deliveryQuantity;?></td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;
							<label class="buyerTotalAmount_"></label>
							<script type="text/javascript">$(".buyerTotalAmount_").html(formatCurrency(<?php echo $value->buyerTotalAmount;?>, 2));</script>
						</td>
					</tr>
                <?php endforeach; ?>
				</tbody>
			</table>
		</div>

		<div class="layui-form-item">
			<div id="at_up" class="clearfix" style="display:block; margin: 0 auto 20px;">
				<!--质量保证函模板-->
                <?php if(is_array($this->templAttachmentList) && count($this->templAttachmentList)>0):?>
					<h5 style="font-weight: bold; color: #56859D; font-size: 14px; padding: 9px 15px; text-align: left;"><?php echo $this->translate('RECEIPT_CONFIRMATION_TEMPL').$this->translate('download');?></h5>
                    <?php foreach ($this->templAttachmentList as $k=>$attach):?>
						<dl class="fl" style="width:90%; padding: 0 20px;height:30px;">
							<span class="fr"><?php echo $this->translate('creatdate')." ".date('Y-m-d H:i:s',strtotime($attach->createTime));?></span>
							<em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext);?>.png') no-repeat;background-size: 20px;"></em>
							<a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'].'/doc/download.action?sid='.session_id().'&nid='.$attach->attachID.'&vid='.$attach->verifyID;?>" download>
                                <?php echo $attach->name;?>
							</a>
						</dl>
                    <?php endforeach; ?>
                <?php endif;?>
			</div>
		</div>

		<div class="layui-form-item">
			<div class="layui-form-label" style="width: 420px;">
				<div class="yyzz_box clearfix" style="width: 600px;">
					<p class="zzname" style="width: 600px; font-weight:bold;"><?php echo $this->translate('RECEIPT_CONFIRMATION_FORMAL').$this->translate('upload'); ?></p>
                    <?php
                    	echo $this->ShowWebuploader(null, $this->biz_Setting['ORDER'], $this->attach_Setting['DLCF'], "0", null);
                    ?>
				</div>
			</div>
		</div>

		<div class="layui-form-item">
			<div class="layui-form-label" style="width: 420px;">
				<div class="yyzz_box clearfix" style="width: 600px;">
					<p class="zzname" style="width: 600px; font-weight:bold;"><?php echo $this->translate('RECEIPT_GOODS').$this->translate('upload'); ?></p>
                    <?php
                        echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLRG'], "0", null);
                    ?>
				</div>
			</div>
		</div>

		<div class="et-auth-row">
			<button class="layui-btn layui-btn-warm" id="deliveryReceiptGoodsBtn"><?php echo $this->translate('ckGOODS'); ?></button>
		</div>
	</div>
</div>