<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<link href="/ky/css/img-upload.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>

<style type="text/css">
    .order_progress{padding:0 20px;border-top:5px solid #df7e20;border-bottom: 20px solid #fff;}
    .progress{display:block;padding: 10px 0;margin: 0 -10px;overflow:hidden;}
    .progress p{float: left;margin:0 10px;font-size: 12px;}
    .icon_bg1,.icon_bg2,.icon_bg3{
        width:210px;
        height:40px;
        background-color:#A0A0A0;
        position:relative;
        color:#000;
        line-height: 40px;
    }
	/*
    .icon_bg1:before, .icon_bg1:after, .icon_bg2:before, .icon_bg2:after, .icon_bg3:before, .icon_bg3:after{
        width:0px;
        height:0px;
        border:transparent solid;
        position:absolute;
        left:100%;
        content:""
    }
    .icon_bg2:before, .icon_bg3:before{
        border-width:20px;
        border-left-color: #f5f5f5;
        left: 0;
    }
    .icon_bg1:after, .icon_bg2:after{
        border-width:20px;
        border-left-color: #A0A0A0;
    }
	*/
    .finish{background-color:#4CAF50;
        color:#fff;}
	/*
    .finish:after{
        border-width:20px;
        border-left-color: #4CAF50;
    }
	*/
    .go{background-color:#df7e20;
        color:#fff;}
    .go:after{border-left-color: #df7e20;}
	.gocursor {cursor: pointer;}
    .od_ht_dl{border-top:1px solid #ddd;border-bottom:1px solid #ddd;overflow:hidden;}
</style>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL.'/ordercg/newlist.phtml');?>
        <div class="order_table order_tableh">
            <ul class="order_state2 clearfix">
                <li <?php if ($this->status=='03'||$this->status=='04'):?>class="on"<?php endif;?> ><a href= "/user/ordercg/index-04-1.html"><!--有效--><?php echo $this->translate('valid');?><span class="ws_num"><?php if(!empty($this->clConut['03'])||!empty($this->clConut['04'])){ echo '('.($this->clConut['03']+$this->clConut['04']).')';}?></span></a></li>
               <li <?php if ($this->status=='01'||$this->status=='05'):?>class="on"<?php endif;?> ><a href= "/user/ordercg/index-01-1.html"><!--待审核--><?php echo $this->translate('checkP');?><span class="wh_num"><?php if(!empty($this->clConut['01'])||!empty($this->clConut['05'])){echo '('.($this->clConut['01']+$this->clConut['05']).')';}?></span></a></li>
                <li <?php if ($this->status=='02'):?>class="on"<?php endif;?> ><a href= "/user/ordercg/index-02-1.html"><!--待确认--><?php echo $this->translate('checkR');?><span class="ws_num"><?php if(!empty($this->clConut['02'])){ echo '('.$this->clConut['02'].')';}?></span></a></li>
                <li <?php if ($this->status=='00'):?>class="on"<?php endif;?> ><a href= "/user/ordercg/index-00-1.html"><!--草稿--><?php echo $this->translate('draft');?><span class="ha_num"><?php if(!empty($this->clConut['00'])){ echo '('.$this->clConut['00'].')';}?></span></a></li>
                <li <?php if ($this->status=='10'||$this->status=='CL'):?>class="on"<?php endif;?> ><a href="/user/ordercg/index-10-1.html"><!--历史--><?php echo $this->translate('history');?><span class="wh_num"><?php if(!empty($this->clConut['10'])||!empty($this->clConut['CL'])){ echo '('.($this->clConut['10']+$this->clConut['CL']).')';}?></span></a></li>
            </ul>
        </div>
        <div class="qy_list_wrap curr pr">
            <div class="qysearch_box">
               <form action="#" method="post">
                        <input class="search_inp"  name="keyword"  <?php if(!empty($this->keyword)){echo "value=".$this->keyword;}?> placeholder="<?php echo $this->translate('INPkw_order_cg');?>" type="text"><!--可输入订单号、卖家名称-->
                        <input class="ss_btn" type="submit" value="">
                <?php if($this->CompOrderAdmin==true&&count($this->ordercg_isAllowAdd)>0):?>
                    <a href="<?php echo '/user/ordercg/add';?>" class="addb_box fr"></a>
                <?php endif;?> </form>
            </div>
            <table class="qy_table qy_table1">
                <thead>
                <tr>
                    <th width="185"><!--订单号--><?php echo $this->translate('orderID');?></th>
                    <th width="185"><!--订单金额--><?php echo $this->translate('orderPrice');?></th>
                    <th><!--买家--><?php echo $this->translate('buyers');?></th>
                    <th width="160"><!--更新时间--><?php echo $this->translate('UPdate');?></th>
                    <?php if($this->CompOrderAdmin==true):?>
                    <th width="120" ><!--操作--><?php echo $this->translate('madeTT');?></th>
                    <?php endif;?>
                </tr>
                </thead>
                <tbody>
                <?php if(is_array($this->e) && count($this->e)>0):?>
                <?php foreach ($this->e as $k=>$orders):?>
                    <tr>
                        <td><a href="<?php  if(!empty($this->ordercg_isAllowView)){echo '/user/ordercg/'.$this->linked.'?'.base64_encode($orders['orderID']);}?>"><?php echo $orders['orderNo'];?></a></td>
                        <td><a href="<?php  if(!empty($this->ordercg_isAllowView)){echo '/user/ordercg/'.$this->linked.'?'.base64_encode($orders['orderID']);}?>"><?php echo $orders['vendorCrnCode'].'  '.$orders['totalAmount'];?></a></td>
                        <td><a href="<?php  if(!empty($this->ordercg_isAllowView)){echo '/user/ordercg/'.$this->linked.'?'.base64_encode($orders['orderID']);}?>"><?php echo $orders['vendorName'];?></a></td>
                        <td><a href="<?php  if(!empty($this->ordercg_isAllowView)){echo '/user/ordercg/'.$this->linked.'?'.base64_encode($orders['orderID']);}?>"><?php echo date('Y-m-d H:i:s',strtotime($orders['lastUpdate']));?></a></td>
                        <?php if($this->CompOrderAdmin==true):?>
                            <td>
                                <div class="cc_box">
                                    <!--提交订单--> <a title="<?php echo $this->translate('submit');?>"  class="t_edit p_qr" <?php if ($orders['orderStatus']==00){ echo 'style="display:inline-block;"';}?>
                                                   href="javascript:;" id="<?php echo $orders['orderID'];?>" data-url="/user/ordercg/submit"
                                                   data-msg1="<?php echo $this->translate('is_submit');?>" data-msg2="<?php echo $this->translate('tip_forReview_success');?>"
                                                   data-msg3="<?php echo $this->translate('tip_forReview_fail');?>" onclick="doOption(this);"></a>

                                    <!--编辑订单--> <a  title="<?php echo $this->translate('edit');?>"  class="t_edit p_ed" <?php if($this->accountID==$orders['client']){if ($orders['orderStatus']==05||$orders['orderStatus']==00||$orders['orderStatus']==02){ echo 'style="display:inline-block;"';}}?>
                                                    href=<?php echo '/user/ordercg/edit?'.base64_encode($orders['orderID']);?>></a>

                                    <!--取消订单--> <a title="<?php echo $this->translate('cancel');?>"  class="t_edit p_delx" <?php if ($orders['orderStatus']==01||$orders['orderStatus']==02||$orders['orderStatus']==05){ echo 'style="display:inline-block;"';}?>
                                                   href="javascript:;" id="<?php echo $orders['orderID'];?>" data-url="/user/ordercg/cancel"
                                                   data-msg1="<?php echo $this->translate('is_cancel');?>" data-msg2="<?php echo $this->translate('tip_cancel_success');?>"
                                                   data-msg3="<?php echo $this->translate('tip_cancel_fail');?>" onclick="doOption(this);"></a>

                                    <!--删除订单--> <a title="<?php echo $this->translate('delete');?>"  class="t_edit p_del" <?php if ($orders['orderStatus']==00){ echo 'style="display:inline-block;"';}?>
                                                   href="javascript:;" id="<?php echo $orders['orderID'];?>" data-url="/user/ordercg/del"
                                                   data-msg1="<?php echo $this->translate('is_delete');?>" data-msg2="<?php echo $this->translate('tip_delete_sucess');?>"
                                                   data-msg3="<?php echo $this->translate('tip_delete_fail');?>" onclick="doOption(this);"></a>


                                </div>
                        </td>
                            <?php endif;?>
                    </tr>
                    <?php endforeach; ?>
                <?php else:?>
                    <tr><td colspan="5"> <?php echo $this->translate('noData');?></td></tr>
                <?php endif;?>
                </tbody>
            </table>
            <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script type="text/javascript" src="/ky/layer-v3.1.1/layer.js"></script>
<script>
    function doOption(obj){
        var url=$(obj).attr('data-url');
        var id=$(obj).attr('id');
        var msg1=$(obj).attr('data-msg1');
        var msg2=$(obj).attr('data-msg2');
        var msg3=$(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title:false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>','<?php echo $this->translate('no');?>'] //按钮
        }, function(){
            $.post( url,
                {'delID':id},
                function(data){
                    if( data.status == 1){
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">'+msg2+'</span>', {skin:'del-class',icon: 1});
                        parent.window.location.reload();
                    }
                    else{
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">'+msg3+'</span><br>'+data.error, {skin:'del-class',icon: 0});
                        parent.window.location.reload();
                    }
                },"json");

        }, function(){
            layer.closeAll();
        });

    }


$(".signTopBtn").click(function () {
	var executionStatus = <?php echo $this->vestut;?>;
	$(".signTopDiv").show();
	$(".deliveryTopDiv").hide();
	$(".paymentTopDiv").hide();
});

$(".deliveryTopBtn").click(function () {
	var executionStatus = <?php echo $this->vestut;?>;
	if (executionStatus >= 7) {
		$(".signTopDiv").hide();
		$(".deliveryTopDiv").show();
		$(".paymentTopDiv").hide();
	}

});

$(".paymentTopBtn").click(function () {
	var executionStatus = <?php echo $this->vestut;?>;
	if (executionStatus >= 7) {
		$(".signTopDiv").hide();
		$(".deliveryTopDiv").hide();
		$(".paymentTopDiv").show().load('<?php echo $this->BaseUrl();?>/orderxs/trading', {'orderID': $("#orderID").val()});
	}
});
</script>
</body>
</html>
