<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('etradefast'); ?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript" src="/ky/layer-v3.1.1/layer.js"></script>
    <style type="text/css">
        .bg_box {
            width: 880px;
            margin: 0 auto;
            overflow: hidden;
        }

        .bg_box p {
            float: left;
        }

        .bg_box span {
            float: right;
            color: #a0a0a0;
        }

        .trackbg {
            position: absolute;
            width: 4px;
            height: 100%;
            top: 52px;
            left: 13px;
            background: #7BBC18;
        }

        .info_btn_box {
            padding: 20px;
        }

        #order_change {
            display: none;
        }

        .o_tab ul li {
            width: 190px;
        }

        .order_progress {
            padding: 0 20px;
            border-top: 5px solid #df7e20;
        }

        .progress {
            display: block;
            padding: 10px 0;
            margin: 0 -10px;
            overflow: hidden;
        }

        .progress p {
            float: left;
            margin: 0 10px;
        }

        .icon_bg1, .icon_bg2, .icon_bg3 {
            width: 123px;
            height: 40px;
            background-color: #A0A0A0;
            position: relative;
            color: #000;
            line-height: 40px;
            padding-left: 10px;
        }

        .icon_bg1:before, .icon_bg1:after, .icon_bg2:before, .icon_bg2:after, .icon_bg3:before, .icon_bg3:after {
            width: 0px;
            height: 0px;
            border: transparent solid;
            position: absolute;
            left: 100%;
            content: ""
        }

        .icon_bg2:before, .icon_bg3:before {
            border-width: 20px;
            border-left-color: #f5f5f5;
            left: 0;
        }

        .icon_bg1:after, .icon_bg2:after {
            border-width: 20px;
            border-left-color: #A0A0A0;
        }

        .finish {
            background-color: #4CAF50;
            color: #fff;
        }

        .finish:after {
            border-width: 20px;
            border-left-color: #4CAF50;
        }

        .go {
            background-color: #df7e20;
            color: #fff;
        }

        .go:after {
            border-left-color: #df7e20;
        }

        .od_ht_dl {
            border-top: 1px solid #ddd;
            border-bottom: 1px solid #ddd;
            overflow: hidden;
        }
    </style>
    <script type="text/javascript">
        $(function () {
            function itemApp($id,$crn) {
                $app="view";
//        $prcetyp 1 表示采购价格 2 表示开票价格 金额

                layer.open({
                    type: 2,
                    title: false,
                    shadeClose: true,
                    shade: 0.8,
                    area: ['700px', '600px'],
                    content: '/user/orderauth/item?ID=' + $id+'&app='+$app+'&crn='+$crn
                });
            }
            /*  编辑订单 必备：orderType DT为内贸  IT为外贸*/
            orderType='<?php echo $this->orders['orderType'];?>';
            if(orderType=='DT'){
                $("#chukou").hide();
                $("#baoguanmk2").hide();
                $("#bgkan").hide();
            }else {
                $("#chukou").show();
                $("#baoguanmk2").show();
                $("#bgkan").show();
            }
            jinrong='<?php echo $this->orders['paymentTerm'];?>';
            if(jinrong=="T/T"){
                $("#jinrong2").hide();
            }else {
                $("#jinrong2").show();
            }

            //获取汇率view 汇率 统一走 listchange 接口 不能同 新增 一样
            isRate('<?php echo  $this->veorderID;?>');

            var orderID = '<?php echo $this->orders['orderID'];?>';
            $('#bgwl').click(function () {
                $('#declaration').load('<?php echo $this->BaseUrl();?>/orderauth/declaration', {'orderID': orderID});
                $('#shipping').load('<?php echo $this->BaseUrl();?>/orderauth/shipping', {'orderID': orderID});
                $('#trucking').load('<?php echo $this->BaseUrl();?>/orderauth/trucking', {'orderID': orderID});
                var declaration = $('#declaration').html();
                var shipping = $('#shipping').html();
                var trucking = $('#trucking').html();
                var bgwl = declaration + shipping + trucking;
                if (bgwl == null || bgwl == "") {
                    $('#declaration').html('<?php $this->translate('noData');?>');
                }
            });
            $('#gzrz').click(function () {
                $('#track').load('<?php echo $this->BaseUrl();?>/orderauth/track', {
                    'orderID': orderID,
                    'view': 'event'
                });
                $('#BYdate').removeClass('on');
                $('#BYevent').addClass('on');
            });
            $('#BYdate').click(function () {

                $('#track').load('<?php echo $this->BaseUrl();?>/orderauth/track', {
                    'orderID': orderID,
                    'view': 'date'
                });
                $('#BYdate').addClass('on');
                $('#BYevent').removeClass('on');
            });
            $('#BYevent').click(function () {
                $('#track').load('<?php echo $this->BaseUrl();?>/orderauth/track', {
                    'orderID': orderID,
                    'view': 'event'
                });
                $('#BYdate').removeClass('on');
                $('#BYevent').addClass('on');
            });
            $('#jiesuan').click(function () {
                $('#trading').load('<?php echo $this->BaseUrl();?>/orderauth/trading', {'orderID': orderID});
            });
            $('#wendang').click(function () {
                $('#attachment').load('<?php echo $this->BaseUrl();?>/orderauth/attachment', {'orderID': orderID});
            });
        });
    </script>
</head>
<body>
<!--头部开始-->
<div class="header_wrap">
    <div class="header w1200 m0a ofh clearfix">
        <div class="logo fl">
            <a href="/"><img src="/ky/images/logo.png"></a>
        </div>
        <div class="nav fr">
            <ul class="nav_list">
                <li class="nav-item  cur">
                    <a href="/"><!-- 基础服务 --><?php echo $this->translate('nav_baseService'); ?></a>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 金融服务 --><?php echo $this->translate('nav_financeService'); ?></a>
                </li>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 帮助中心 --><?php echo $this->translate('nav_help'); ?></a>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 关于我们 --><?php echo $this->translate('nav_about'); ?></a>
                </li>
            </ul>
            <div class="move-bg"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $(".nav").movebg({
            width: 115/*滑块的大小*/,
            extra: 40/*额外反弹的距离*/,
            speed: 300/*滑块移动的速度*/,
            rebound_speed: 400/*滑块反弹的速度*/
        });

        $('#langcode').change(function () {
            var lang = $('#langcode').val();
            $.post('/user/system/langcode',
                {'langcode': lang},
                function (data) {
                    if (data) {
                        location.reload();
                    }
                    else {
                        return false;
                    }
                }, "json");
        });

    });

</script>
<!--头部结束-->
<div class="o_content_wrap w1200 m0a clearfix">
    <div style="margin: 0 auto;" class="o_content w940">
        <?php if ($this->acctID == $this->orders['vendor']) {
            echo $this->render(SEED_WWW_TPL . '/orderauth/topvendor.phtml');
        } else {
            echo $this->render(SEED_WWW_TPL . '/orderauth/topbuyer.phtml');
        }; ?>
        <div class="order_table">
            <div class="o_tab" id="o_tab">
                <ul>
                    <li><a href="#"><!--订单信息--><?php echo $this->translate('orderVINF'); ?></a></li>
                    <li id="bgwl"><a href="#"><!--报关物流--><?php echo $this->translate('logistics'); ?></a></li>
                    <li id="gzrz"><a href="#"><!--跟踪日志--><?php echo $this->translate('DERIL_log'); ?></a></li>
                    <li id="jiesuan"><a href="#"><!--结算--><?php echo $this->translate('settle'); ?></a></li>
                    <li id="wendang"><a href="#"><!--文档--><?php echo $this->translate('file'); ?></a></li>
                </ul>
            </div>
            <div class="order_info" id="order_info">
                <div class="info_cont" id="order_change">
                    <div class="n_o_c_tit">
                        <h4><!--订单信息预览--><?php echo $this->translate('view') . $this->translate('orderINF'); ?></h4>
                    </div>
                    <div class="info_cont clearfix">
                        <?php if ($this->acctID == $this->orders['vendor']): ?>
                            <dl class="fl">
                                <dt class="fl"><!--买家-->
                                    <?php echo $this->translate('buyers'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['buyerName']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--买家联系人--><?php echo $this->translate('buyerATTN'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['buyerContactName']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--订单货币(取对方货币)--><?php echo $this->translate('payCNY'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['buyerCrnCode']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--本单联系人--><?php echo $this->translate('thisATTN'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['vendorContactName']; ?></dd>
                            </dl>
                        <?php else: ?>
                            <dl class="fl">
                                <dt class="fl"><!--卖家-->
                                    <?php echo $this->translate('seller'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['vendorName']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--卖家联系人--><?php echo $this->translate('sellerATTN'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['vendorContactName']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--订单货币(取对方货币)--><?php echo $this->translate('payCNY'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['buyerCrnCode']; ?></dd>
                            </dl>
                            <dl class="fl">
                                <dt class="fl"><!--本单联系人--><?php echo $this->translate('thisATTN'); ?></dt>
                                <dd class="buyer_contacts"><?php echo $this->orders['buyerContactName']; ?></dd>
                            </dl>
                        <?php endif; ?>

                        <dl class="fl">
                            <dt class="fl"><!--结算方式--><?php echo $this->translate('remitMD'); ?></dt>
                            <dd class="fl price_rules"> <?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['PAYMENT_TERM'], $this->orders['paymentTerm']); ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--支付期限--><?php echo $this->translate('payDD'); ?></dt>
                            <dd class="fl price_rules"><?php echo  $this->orders['paymentPeriod']; ?>
                                &nbsp;&nbsp;DAYS</dd>
                        </dl>
                        <dl class="fl" id="chukou">
                            <dt class="fl"><!--出口方式--><?php echo $this->translate('exportMD'); ?></dt>
                            <dd class="fl price_rules"><?php if ($this->orders['isSelfSupport'] == true) {
                                    echo $this->translate('sellersEX');
                                } else {
                                    echo $this->translate('siteEX');
                                } ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"></dt>
                            <dd class="fl price_rules"></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--计价方式--><?php echo $this->translate('payJJ'); ?></dt>
                            <dd class="buyer_contacts"><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ORDER_QUOTATION_MODE'], $this->orders['quotationMode']); ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--价格条款--><?php echo $this->translate('payPrice'); ?></dt>
                            <dd class="fl price_rules"><?php echo $this->orders['priceTerm']; ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--包装方式--><?php echo $this->translate('payCasing'); ?></dt>
                            <dd class="fl price_rules"><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['ORDER_PACKING_MODE'], $this->orders['packingMode']); ?></dd>
                        </dl>
                        <dl class="fl" style="width:100%">
                            <dt class="fl"><!--包装说明--><?php echo $this->translate('packINF'); ?></dt>
                            <dd class="fl price_rules"><?php echo $this->orders['packingDesc']; ?></dd>
                        </dl>
                    </div>
                    <div class="info_tit">
                        <h4><!--商品清单--><?php echo $this->translate('payGoods'); ?></h4>
                    </div>
                    <div class="info_table_box" id="selectgoods_view">
                        <?php if (is_array($this->orders['orderItemList']) && count($this->orders['orderItemList']) > 0): ?>
                            <?php foreach ($this->orders['orderItemList'] as $k => $goods): ?>
                                <li id=<?php echo $goods['productID']; ?>>
                                    <div class="pro_view">
                                        <a href="javascript:itemApp('<?php echo $goods['itemID'];?>','<?php echo $this->orders['buyerCrnCode'];?>');" >
                                            <em><?php echo $k+1;?></em></a>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--商品名称--><?php echo $this->translate('productNAME'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['productName']);?> </p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--英文名称--><?php echo $this->translate('productNAME'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['productEnName']);?> </p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--包装类型--><?php echo $this->translate('packageTYPE'); ?></label>
                                            <span class="view_span"
                                                  title="<?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['PRODUCT_PACKING_TYPE'], $goods['packingType']); ?>"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['PRODUCT_PACKING_TYPE'], $goods['packingType']); ?></span>
                                        </p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--HSCode--><?php echo $this->translate('HSCODE'); ?></label>
                                            <span class="view_span"
                                                  title="<?php echo $goods['hscode']; ?>"><?php echo $goods['hscode']; ?></span>
                                        </p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--品牌--><?php echo $this->translate('brand'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['productBrand']);?> </p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--型号--><?php echo $this->translate('model'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['productModel']);?></p>
                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--材质--><?php echo $this->translate('productMaterial'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['productMaterial']);?></p>

                                        <p>
                                            <label class="public_lab  mr10">
                                                <!--功能用途--><?php echo $this->translate('functionUsage'); ?></label>
                                            <?php echo $this->showOrderViewGoods($goods['functionUsage']);?> </p>
                                    </div>
                                    <table class="n_sp_tab tc" id=<?php echo $goods['productID']; ?>>
                                        <tr>
                                            <th><!--价格--><?php echo $this->translate('orderprice'); ?></th>
                                            <th><!--数量--><?php echo $this->translate('number'); ?></th>
                                            <th><!--金额--><?php echo $this->translate('ordertotal'); ?></th>
                                            <?php if ($this->orders['quotationMode'] == 'IV'): ?>
                                                <th class="uije">
                                                    <!--开票价格--><?php echo $this->translate('uiprice'); ?></th>
                                                <th class="uije">
                                                    <!--开票金额--><?php echo $this->translate('uitotal'); ?></th>
                                            <?php else: ?>
                                                <!--采购价格 采购金额-->
                                                <?php if ($goods['productionMode'] == '02'): ?>
                                                    <th class="poje"><?php echo $this->translate('purchaseUnitPrice'); ?></th>
                                                    <th class="poje"><?php echo $this->translate('purtotal'); ?></th>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                            <th><!--件数--><?php echo $this->translate('quantity'); ?></th>
                                            <th><!--净重--><?php echo $this->translate('netWeight'); ?></th>
                                            <th><!--毛重--><?php echo $this->translate('grossWeight'); ?></th>
                                        </tr>
                                        <tr>
                                            <td><span class="w50b"><?php echo $this->orders['buyerCrnCode']; ?>
                                                    &nbsp;</span><?php echo round($goods['unitPrice'], 4); ?></td>
                                            <td><?php echo $goods['quantity']; ?>
                                                <span id="num_dw"
                                                      class="w30b">&nbsp;<?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $goods['pricingUnit']); ?></span>
                                            </td>
                                            <td><span class="w50b"><?php echo $this->orders['buyerCrnCode']; ?>
                                                    &nbsp;</span><?php echo $goods['totalPrice']; ?></td>
                                            <?php if ($this->orders['quotationMode'] == 'IV' || $goods['productionMode'] == '02'): ?>
                                                <td class="uije"><span class="w50b"><?php echo $goods['purCrnCode']; ?>
                                                        &nbsp;</span><?php echo $goods['purUnitPrice']; ?></td>
                                                <td class="uije"><span class="w50b"><?php echo $goods['purCrnCode']; ?>
                                                        &nbsp;</span><?php echo $goods['totalPurPrice']; ?></td>
                                            <?php endif; ?>
                                            <td>
                                                <!---总数量除以每件数量=件数--><?php echo $goods['totalPackage'];?></td>
                                            <td><?php echo $goods['totalNetWeight']; ?><span class="w50b">&nbsp;KGS</span>
                                            </td>
                                            <td><?php echo $goods['totalGrossWeight']; ?><span class="w50b">&nbsp;KGS</span>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </div>
                    <div class="n_sp_total tl">
                        <p class="p_total"><!--总净重：--><?php echo $this->translate('shopNet'); ?>&nbsp;<span
                                    id="zjinzhong"><?php echo $this->orders['totalNetWeight']; ?></span>&nbsp;<b>KGS</b>
                        </p>
                        <p class="p_total"><!--总毛重：--><?php echo $this->translate('shopGross'); ?>&nbsp;<span
                                    id="zmaozhong"><?php echo $this->orders['totalGrossWeight']; ?></span>&nbsp;<b>KGS</b>
                        </p>
                        <p class="p_total" style="width:22%"><!--订单总金额：--><?php echo $this->translate('shopTotal'); ?>
                            &nbsp;<b><?php echo $this->orders['buyerCrnCode']; ?>&nbsp;</b><span id="zjine"><?php echo $this->orders['totalAmount']; ?></span>
                        </p>
                        <p class="p_total" style="width:44%"><!--订单汇率：--><?php echo $this->translate('shopPrities'); ?>
                            <span id="huilv2" class="huilv"></span></p>

                    </div>
                    <div class="info_cont clearfix">
                        <dl class="fl">
                            <dt class="fl"><!--运输方式--><?php echo $this->translate('moveMD'); ?></dt>
                            <dd class="place_contacts"><?php echo $this->ShowDictionaryTo('datatest_setting', $this->userLangCode, $this->dic_Setting['SHIPPING_METHOD'], $this->orders['shippingMethod']); ?></dd>
                        </dl>
                        <dl class="fl" id="bgkan">
                            <dt class="fl"><!--报关口岸--><?php echo $this->translate('POCRC'); ?></dt>
                            <dd class="fl packing_method"> <?php echo $this->ShowDictionaryTo($this->dic_Setting['EXPORT_POINTS'], $this->userLangCode, $this->dic_Setting['EXPORT_POINTS'], $this->orders['clearancePlace']); ?></dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--起运港--><?php echo $this->translate('portSHIP'); ?></dt>
                            <dd>
                                <?php echo $this->ShowDictionaryTo($this->port, $this->userLangCode, $this->port, $this->orders['loadingPort']); ?>
                            </dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--卸货港--><?php echo $this->translate('portDSCG'); ?></dt>
                            <dd>
                                <?php echo $this->ShowDictionaryTo($this->port, $this->userLangCode, $this->port, $this->orders['dischargePort']); ?>
                            </dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--交货港--><?php echo $this->translate('portDLVY'); ?></dt>
                            <dd>
                                <?php echo $this->ShowDictionaryTo($this->port, $this->userLangCode, $this->port, $this->orders['deliveryPort']); ?>
                            </dd>
                        </dl>
                        <dl class="fl">
                            <dt class="fl"><!--预计交货日期--><?php echo $this->translate('mabyDATE'); ?></dt>
                            <dd class="destination"><?php echo date('Y-m-d H:i:s', strtotime($this->orders['deliveryDate'])); ?></dd>
                        </dl>
                        <dl class="fl" <?php if ($this->orders['needShipping'] == true) {
                            echo 'style="width:100%";';
                        } else {
                            echo 'style="display:none;"';
                        } ?>>
                            <dt class="fl"><!--装柜类型--><?php echo $this->translate('isFCL'); ?></dt>
                            <dd class="cabinet"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['SHIPPING_SERVICE_TYPE'], $this->orders['shippingServiceType']); ?></dd>
                        </dl>

                        <?php if($this->orders['sizeQuantityMap']):?>
                            <dl class="fl" <?php if($this->orders['needShipping']==true){if($this->orders['shippingServiceType']=='FCL'){echo 'style="width:100%;"';}else{echo 'style="display:none;"';}}else{echo 'style="display:none;"';}?>>
                                <dt class="fl"><!--装柜数量--><?php echo $this->translate('infoFCL'); ?></dt>
                                <dd class="fl settlement">
                                    <?php if(!empty($this->orders['sizeQuantityMap']['20GP'])):?>
                                        <em class="num1"><a>20GP*</a><?php echo $this->orders['sizeQuantityMap']['20GP'];?></em>
                                    <?php endif;?>

                                    <?php if(!empty($this->orders['sizeQuantityMap']['40GP'])):?>
                                        <em class="num1"><a>40GP*&nbsp;</a><?php echo $this->orders['sizeQuantityMap']['40GP'];?></em>
                                    <?php endif;?>

                                    <?php if(!empty($this->orders['sizeQuantityMap']['40HP'])):?>
                                        <em class="num1"><a>40HQ*&nbsp;</a><?php echo $this->orders['sizeQuantityMap']['40HP'];?></em>
                                    <?php endif;?>

                                    <?php if(!empty($this->orders['sizeQuantityMap']['45HP'])):?>
                                        <em class="num1"><a>45HQ*&nbsp;</a><?php echo $this->orders['sizeQuantityMap']['45HP'];?></em>
                                    <?php endif;?>

                                    <?php if(!empty($this->orders['sizeQuantityMap']['20OT'])):?>
                                        <em class="num1"><a>20OT*&nbsp;</a><?php echo $this->orders['sizeQuantityMap']['20OT'];?></em>
                                    <?php endif;?>

                                    <?php if(!empty($this->orders['sizeQuantityMap']['40OT'])):?>
                                        <em class="num1"><a>40OT*&nbsp;</a><?php echo $this->orders['sizeQuantityMap']['40OT'];?></em>
                                    <?php endif;?>
                                </dd>
                            </dl>
                        <?php endif;?>

                        <?php if(($this->orders['needShipping'] == true && $this->accountID=$this->orders['shippingClient'])||($this->orders['needTrucking'] == true &&$this->accountID=$this->orders['truckingClient'])):?>
                            <dl class="fl">
                                <dt class="fl"><!--物流要求--><?php echo $this->translate('logisticND'); ?></dt>
                                <dd class="fl log_service"><?php echo $this->orders['shippingRequest']; ?></dd>
                            </dl>
                        <?php endif;?>
                        <div  id="baoguanmk2">
                        <dl class="fl" <?php if ($this->orders['isAssignCustomsAgency'] == false) {
                            echo 'style="display:none;"';
                        } ?>>
                            <dt class="fl"><!--报关行名称--><?php echo $this->translate('nameCHB'); ?></dt>
                            <dd class="cabinet"><?php echo $this->orders['customsAgencyName']; ?></dd>
                        </dl>
                        <dl class="fl" <?php if ($this->orders['isAssignCustomsAgency'] == false) {
                            echo 'style="display:none;"';
                        } ?>>
                            <dt class="fl"><!--报关要求--><?php echo $this->translate('needCHB'); ?></dt>
                            <dd class="cabinet"><?php echo $this->orders['customClearanceRequest']; ?></dd>
                        </dl>
                        </div>
                    </div>
                    <?php if($this->orders['paymentTerm']!="T/T"):?>
                    <?php if(($this->orders['needFinancing'] == true)&&($this->accountID=$this->orders['financingClient'])):?>
                    <div  id="jinrong2" class="info_cont clearfix">
                        <dl class="fl" style="width: 100%;height: 100px;">
                            <dt class="fl"><!--金融要求--><?php echo $this->translate('needOTH'); ?></dt>
                            <dd class="cabinet"><?php echo $this->orders['financingRequest']; ?></dd>
                        </dl>
                    </div>
                    <?php endif;?>
                    <?php endif;?>

                </div>
                <div class="info_cont" id="order_change">
                    <div id="declaration"></div>
                    <div id="shipping"></div>
                    <div id="trucking"></div>
                </div>
                <div class="info_cont" id="order_change">
                    <div class="info_h3 clearfix">
                        <h3 class="fl"></h3>
                        <div class="info_btn_box fr">
                            <a class="by_time" id="BYdate" href="#">
                                <!--按时间分类--><?php echo $this->translate('timeCLASS'); ?></a>
                            <a class="by_event" id="BYevent" href="#">
                                <!--按事件分类--><?php echo $this->translate('eventCLASS'); ?></a>
                        </div>
                    </div>
                    <div id="track">
                    </div>
                </div>
                <div class="info_cont" id="order_change">
                    <div id="trading"></div>
                </div>
                <div class="info_cont" id="order_change">
                    <div id="attachment"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL . '/footer.phtml'); ?>
</body>
</html>
