<?php if(is_array($this->dcd) && count($this->dcd)>0):?>
    <div class="info_tit">
        <h4><!--订舱单--><?php echo $this->translate('shipping');?></h4>
    </div>
    <?php foreach ($this->dcd as $k=>$orders):?>
        <div class="clearfix">
            <dl class="fl">
                <dt class="fl"><!--运输公司--><?php echo $this->translate('companySPP');?></dt><dd class="buyer_contacts"><?php echo $orders['carrierName'];?></dd>
            </dl>
            <dl class="fl">
                <dt class="fl"><!--货运代理--><?php echo $this->translate('poxySPP');?></dt><dd class="fl price_rules"><?php echo $orders['forwarderName'];?></dd>
            </dl>
            <dl class="fl">
                <dt class="fl"><!--运输方式--><?php echo $this->translate('moveMD');?></dt>
                <dd class="buyer_contacts"><?php echo $this->ShowDictionaryTo("datatest_setting",$this->userlangCode,$this->dic_Setting['SHIPPING_METHOD'],$orders['shippingMethod']);?>
               </dd>
            </dl>
            <dl class="fl">
                <dt class="fl"><!--放货方式--><?php echo $this->translate('saveSPP');?></dt>
                <dd class="fl price_rules"><?php echo $this->ShowDictionaryTo("datatest_setting",$this->userlangCode,$this->dic_Setting['SO_RELEASE_WAY'],$orders['releaseWay']);?>
                </dd>
            </dl>
            <dl class="fl">
                <dt class="fl"><!--是否分批--><?php echo $this->translate('isbatchSPP');?></dt>
                <dd class="buyer_contacts"><?php echo $this->ShowDictionaryTo("datatest_setting",$this->userlangCode,$this->dic_Setting['TRUE_OR_FALSE'],$orders['canPartialShipment']);?>
                   </dd>
            </dl>
            <dl class="fl">
                <dt class="fl"><!--状态--><?php echo $this->translate('state');?></dt>
                <dd class="fl price_rules"><?php echo $this->ShowDictionaryTo("datatest_setting",$this->userlangCode,$this->dic_Setting['SHIPPING_ORDER_STATUS '],$orders['shippingStatus']);?>
                    </dd>
            </dl>
        </div>

    <?php endforeach; ?>
<?php else:?>
    <div class="info_tit">
        <h4><!--订仓单--><?php echo $this->translate('shipping');?></h4>
    </div>
    <div class="clearfix">
        <?php echo $this->translate('Nodata');?>
    </div>
<?php endif;?>