<div class="header_wrap">
    <div class="header w1200 m0a ofh clearfix">
        <div class="logo fl">
            <a href="/"><img src="/ky/images/logo.png"></a>
        </div>
        <div class="nav fr">
            <ul class="nav_list">
                <?php  if(!empty($this->userID)):?>
                <span style="width:200px;float:left;display:inline-block;line-height:76px;margin-left:-200px;text-align:center;color:#fff;">
                    <a style="color:#DCDCDD;" href="/user/index"><?php echo $this->userLoginName;?></a>&nbsp;|
                    <a style="color:#DCDCDD;" href="/user/Logout"><!--退出--><?php echo $this->translate('nav_exit');?></a>
                </span>
                <?php else:?>
                <li class="nav-item">
                    <a href="/user/login"><!-- 注册登录 --><?php echo $this->translate('register').$this->translate('nav_login');?></a>
                </li>
                <?php endif;?>
                <li class="nav-item  cur">
                    <a href="/"><!-- 基础服务 --><?php echo $this->translate('nav_baseservice');?></a>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 金融服务 --><?php echo $this->translate('nav_finservice');?></a>
                </li>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 帮助中心 --><?php echo $this->translate('nav_help');?></a>
                </li>
                <li class="nav-item">
                    <a href="/"><!-- 关于我们 --><?php echo $this->translate('nav_about');?></a>
                </li>
            </ul>
            <div class="move-bg"></div>
        </div>
    </div>
</div>
