<div class="o_nav fl">
    <dt>基础服务</dt>
    <dd>
        <a  href="#">
            服务项目一</a>
    </dd>
    <dd>
        <a  href="#">
            服务项目二</a>
    </dd>
    <dd>
        <a  href="#">
            服务项目三</a>
    </dd>

    <dt>金融服务</dt>
    <dd>
        <a  href="#">
            企业代收</a>
    </dd>
    <dd>
        <a  href="#">
            企业代付</a>
    </dd>

    <dt>关于我们</dt>
    <dd>
        <a  href="#">
            企业介绍</a>
    </dd>
    <dd>
        <a  href="#">
            查找职位</a>
    </dd>
    <dd>
        <a  href="#">
            隐身声明</a>
    </dd>
    <dd>
        <a  href="#">
            法律条款</a>
    </dd>
    <dt>帮助中心</dt>
    <dd>
        <a  href="#">
            平台规则</a>
    </dd>
    <dd>
        <a  href="#">
            新手注册</a>
    </dd>
    <dd>
        <a  href="#">
            使用说明</a>
    </dd>

    <dt>快移资讯</dt>
</div>