<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<!--<script type="text/javascript" src="/ky/js/prompt.js"></script>-->
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL.'/bank/r_top_menu.phtml');?>
        <div class="n_o_c_tit">
            <h4><!--编辑银行账户--><?php echo $this->translate('edit').$this->translate('bankAcctNo');?></h4>
        </div>
        <div class="acc_add_box">
           <form action="#" method="post" id="bank_edit_form" onsubmit="return toVaild()">
               <div  class="bank_box">
                   <label><!--账号--><?php echo $this->translate('bankAcctName');?></label>
                   <input class="must" style="border: 1px solid #DF7E20;" type="text" name="bankAcctName" id="bankAcctName" value="<?php echo $this->bank['bankAcctName'];?>" required data-msg-required="<?php echo $this->translate('de_null');?>"/>
               </div>
               <div  class="bank_box">
                   <label><!--账户名称--><?php echo $this->translate('bankAcctNo');?></label>
                   <input class="must" style="border: 1px solid #DF7E20;" type="text" name="bankAcctNo" id="bankAcctNo" value="<?php echo $this->bank['bankAcctNo'];?>" required data-msg-required="<?php echo $this->translate('de_null');?>" />
               </div>
               <div  class="bank_box">
                   <label><!--账户类型--><?php echo $this->translate('bankAcctType');?></label>
                   <select style="width: 265px;padding: 0 5px;" name="bankAcctType">
                       <?php echo $this-> ShowDictionaryList("datatest_setting",$this->userLangCode,$this->dic_Setting['BANK_ACCOUNT_TYPE'],$this->bank['bankAcctType']);?>
                   </select>
               </div>
               <div  class="bank_box">
                   <label><!--银行名称--><?php echo $this->translate('accountBKname');?></label>
                   <input class="must" style="border: 1px solid #DF7E20;" type="text" name="bankName" id="bankName" value="<?php echo $this->bank['bankName'];?>" required data-msg-required="<?php echo $this->translate('de_null');?>" />
               </div>
               <div  class="bank_box">
                   <label><!--SWIFT CODE--><?php echo $this->translate('SWIFTCode');?></label>
                   <input class="must" type="text" name="swiftcode"  value="<?php echo $this->bank['swiftcode'];?>"/>
               </div>

               <div  class="bank_box" style="width:100%">
                   <label><!--开户行地址--><?php echo $this->translate('accountADR');?></label>
                   <input  type="text" name="bankAddress" value="<?php echo $this->bank['bankAddress'];?>" />
               </div>
               <div  class="bank_box clearfix" style="width:100%;height: auto;">
                   <label><!--备注--><?php echo $this->translate('remarks');?></label>
                   <textarea class="spl_full" style="width:688px" name="remarks" cols="200" rows="5"><?php echo $this->bank['remarks'];?></textarea>
               </div>
               <div class="yyzz_box info_cont">
                   <div class="zzname  n_o_c_tit"><h4><!-- 银行资料 --><?php echo $this->translate('UPBank');?></h4></div>
                   <?php echo $this-> ShowWebuploader($this->bank['attachmentList'],$this->biz_Setting['BANK_ACCOUNT'],$this->attach_Setting['0000'],"0");?>
               </div>
               <?php echo $this->render(SEED_WWW_TPL.'/btn_confirm.phtml');?>
           </form>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script src="/ky/js/jquery.validate.js"></script>
<script type="text/javascript" src="/ky/layer-v3.1.1/layer.js"></script>
<script>
    function toVaild(){
        var isT=$('input[name="attachSize[]"]').val();
        if(isT==null||isT==""){
            layer.msg("<?php echo $this->translate('tip_bank_no');?>",{skin:'del-class',icon: 0});
            return false;
           }
            else{
            return true;
                  }
     }

    $(function(){
        $("#bank_edit_form").validate({
            submitHandler: function() {
                form.submit();
            }
        })
    });
</script>
</body>
</html>
