<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/bank/bank.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <!-- Viewer -->
    <link href="/ky/viewer-1.0.0-dist/viewer.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 bank-main">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if (!empty($this->errMsg)): ?>
                        <div class="alert alert-danger alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <strong>Warning!</strong> <?php echo $this->errMsg; ?>
                        </div>
                        <?php endif; ?>

                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('bankNO'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <form class="form-horizontal bank-main-edit" action="#" method="post" id="bank_edit_form" name="bank_edit_form">
                                        <div class="form-group">
                                            <label for="bankAcctName" class="col-sm-2 control-label"><?php echo $this->translate('bankAcctName'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="bankAcctName" id="bankAcctName" placeholder="" value="<?php echo $this->bank['bankAcctName']; ?>"  required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="bankAcctNo" class="col-sm-2 control-label"><?php echo $this->translate('bankAcctNo'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="bankAcctNo" id="bankAcctNo" placeholder="" value="<?php echo $this->bank['bankAcctNo']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="bankAcctType" class="col-sm-2 control-label"><?php echo $this->translate('bankAcctType'); ?></label>
                                            <div class="col-sm-9">
                                                <select class="form-control" name="bankAcctType" id="bankAcctType">
                                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['BANK_ACCOUNT_TYPE'], $this->userLangCode, $this->dic_Setting['BANK_ACCOUNT_TYPE'], $this->bank['bankAcctType']); ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="bankName" class="col-sm-2 control-label"><?php echo $this->translate('accountBKname'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="bankName" id="bankName" placeholder="" value="<?php echo $this->bank['bankName']; ?>" required >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="swiftcode" class="col-sm-2 control-label"><?php echo $this->translate('SWIFTCode'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="swiftcode" id="swiftcode" placeholder="" value="<?php echo $this->bank['swiftcode']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="bankAddress" class="col-sm-2 control-label"><?php echo $this->translate('accountADR'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="bankAddress" id="bankAddress" placeholder="" value="<?php echo $this->bank['bankAddress']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="remarks" class="col-sm-2 control-label"><?php echo $this->translate('remarks'); ?></label>
                                            <div class="col-sm-9">
                                                <input type="text" class="form-control" name="remarks" id="remarks" placeholder="" value="<?php echo $this->bank['remarks']; ?>" >
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <label for="" class="col-sm-2 control-label"><?php echo $this->translate('UPBank'); ?></label>
                                            <div class="col-sm-9">
                                                <?php echo $this->ShowWebuploader($this->bank['attachmentList'], $this->biz_Setting['BANK_ACCOUNT'], $this->attach_Setting['0000'], "0"); ?>
                                            </div>
                                        </div>

                                        <?php if ($this->CompAdmin == true): ?>
                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-9">
                                                <button type="submit" class="btn btn-warning"><?php echo $this->translate('save'); ?></button>
                                            </div>
                                        </div>
                                        <?php endif; ?>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Modal -->
                <div class="modal fade" id="authModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content"></div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- viewer -->
<script type="text/javascript" src="/ky/viewer-1.0.0-dist/viewer.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
            // if (this.href === document.location.href) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        // viewer
        // 先判断是否有图片, 再初始化viewer
        if ($(".img-view > li").length > 0) {
            $(".img-view").viewer({
                url: "data-original"
            });
        }
	});
</script>
</body>
</html>
