<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/bank/bank.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <?php if ($this->isPersonAccount != 1): ?>
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                    <?php else: ?>
                        <div class="panel-heading"><?php echo $this->translate('bankNO'); ?></div>
                        <div class="list-group">
                            <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>

            <div class="col-md-9 bank-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('bankNO'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->resultMsg)): ?>
                        <div class="alert alert-success alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                        </div>
                        <?php endif; ?>

                        <form class="form-horizontal" action="javascript:void(0)" onsubmit="bankSearch()" id="bank_search_form">
                            <div class="form-group" style="margin-bottom: 0 !important;">
                                <label for="keyword" class="sr-only">keyword</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <span class="input-group-addon"><i class="fas fa-search"></i></span>
                                        <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('INPkw_bk');?>">
                                    </div>
                                </div>
                                <div class="col-sm-1">
                                    <button type="submit" class="btn btn-primary"> Go </button>
                                </div>
                                <?php if ($this->CompAdmin == true): ?>
                                <div class="col-sm-1 col-sm-offset-4">
                                    <a title="<?php echo $this->translate('add');?>" href="/user/bank/add" class="btn btn-default">
                                        <i class="fas fa-plus"></i>
                                    </a>
                                </div>
                                <?php endif; ?>
                            </div>
                        </form>

                        <!-- Table -->
                        <table id="bankListTable"></table>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
    var dataDict = {};

	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["BANK_ACCOUNT_STATUS", "BANK_ACCOUNT_TYPE"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#bankListTable').bootstrapTable({
                    url: '/user/bank/bank-list-ajax',
                    method: 'post',
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    height: 489,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search
                        };
                    },
                    columns: [{
                        field: 'bankAcctNo',
                        title: '<?php echo $this->translate("bankAcctNo"); ?>',
                        formatter: function (value, row) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.bankAcctID);
                            var href = "/user/bank/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'bankAcctName',
                        title: '<?php echo $this->translate("bankAcctName"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.bankAcctID);
                            var href = "/user/bank/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'bankAcctType',
                        title: '<?php echo $this->translate("bankAcctType"); ?>',
                        formatter: function (value) {
                            var result ="";
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'BANK_ACCOUNT_TYPE') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'bankName',
                        title: '<?php echo $this->translate("bankName"); ?>'
                    }, {
                        field: 'swiftcode',
                        title: '<?php echo $this->translate("SWIFTCode"); ?>'
                    }, {
                        field: 'isDefault',
                        title: '<?php echo $this->translate("accountDF"); ?>',
                        formatter: function (value) {
                            return (value === true) ? '<?php echo $this->translate('yes') ?>' : '<?php echo $this->translate('no'); ?>';
                        }
                    }, {
                        field: 'bankAcctStatus',
                        title: '<?php echo $this->translate("state"); ?>',
                        formatter: function (value) {
                            var result = "-";
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'BANK_ACCOUNT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        formatter: function (value, row, index) {
                            var editTitle = "<?php echo $this->translate("edit");?>";
                            var delTitle = "<?php echo $this->translate('delete');?>";
                            var disableTitle = "<?php echo $this->translate('disable');?>";
                            var validTitle = "<?php echo $this->translate('valid');?>";
                            var base = new Base64();
                            var resultEnCode = base.encode(row.bankAcctID);
                            var href = "/user/bank/edit?"+resultEnCode;

                            var result = '';
                            <?php if ($this->CompAdmin == true): ?>
                            if (row.bankAcctStatus === '03' || row.bankAcctStatus === '04') {
                                result += '<a title="' + editTitle+ '" href="' + href + '">'
                                    + '<i class="far fa-edit"></i>'
                                    + '</a>&nbsp;';

                                result += '<a href="javascript:void(0)" title="' + delTitle + '" id="' + row.bankAcctID + '" data-url="/user/bank/delete" data-msg1="<?php echo $this->translate("is_delete");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_del_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_del_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-trash-alt"></i>'
                                    + '</a>';
                            }
                            if (row.bankAcctStatus === '01') {
                                result += '<a href="javascript:void(0)" title="' + disableTitle + '" id="' + row.bankAcctID + '" data-url="/user/bank/invalid" data-msg1="<?php echo $this->translate("is_invalid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_invalid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_invalid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="fas fa-ban"></i>'
                                    + '</a>';
                            }

                            if (row.bankAcctStatus === '02') {
                                result += '<a href="javascript:void(0)" title="' + validTitle + '" id="' + row.bankAcctID + '" data-url="/user/bank/valid" data-msg1="<?php echo $this->translate("is_valid");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_valid_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_valid_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>';
                            }
                            <?php endif; ?>

                            return result;
                        }
                    }]
                });
            }
        });

        $("#searchBankBtn").click(function () {
            bankSearch();
        });

        $("#shoAllContact").click(function () {
            var contactListTable = $('#contactListTable');
            var options = {};
            if ($(this).is(':checked')) {
                options = {
                    query:{
                        contactStatus: "all"
                    }
                };
            }
            $(contactListTable).bootstrapTable('refresh', options);
        });
	});

	function bankSearch() {
        var contactListTable = $('#bankListTable');
        var options = {
            query:{
                keyword: $("#keyword").val()
            }
        };
        $(contactListTable).bootstrapTable('refresh', options);
    }

    function doOption(obj) {
        var url = $(obj).attr('data-url');
        var id = $(obj).attr('id');
        var msg1 = $(obj).attr('data-msg1');
        var msg2 = $(obj).attr('data-msg2');
        var msg3 = $(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title: false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
        }, function () {
            $.post(url,
                {'delID': id},
                function (data) {
                    var contactListTable = $('#bankListTable');

                    if (data.status === 1) {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg2 + '</span>', {
                            skin: 'del-class',
                            icon: 1
                        });
                        $(contactListTable).bootstrapTable('refresh');
                    } else {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg3 + '</span><br>' + data.error, {
                            skin: 'del-class',
                            icon: 0
                        });
                        $(contactListTable).bootstrapTable('refresh');
                    }
                }, "json");

        }, function () {
            layer.closeAll();
        });
    }
</script>
</body>
</html>
