<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/bank/bank.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <!-- Viewer -->
    <link href="/ky/viewer-1.0.0-dist/viewer.min.css" rel="stylesheet">

</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('companyMNG'); ?></div>
                    <div class="list-group">
                        <a href="/user/company" class="list-group-item"><?php echo $this->translate('company_info'); ?></a>
                        <a href="/user/account" class="list-group-item"><?php echo $this->translate('personNO'); ?></a>
                        <a href="/user/bank" class="list-group-item"><?php echo $this->translate('bankNO'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 bank-view">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('bankNO'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('UPBank'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12">
                                    <h3>
                                        <?php if ($this->CompAdmin == true && ($this->bank['bankAcctStatus'] == '04' || $this->bank['bankAcctStatus'] == '03')): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/bank/edit?' . base64_encode($this->bank['bankAcctID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->bank['bankAcctName']; ?>
                                    </h3>

                                    <dl class="dl-horizontal">
                                        <dt><?php echo $this->translate('bankAcctName'); ?></dt>
                                        <dd><?php echo $this->bank['bankAcctNo']; ?></dd>

                                        <dt><?php echo $this->translate('bankAcctNo'); ?></dt>
                                        <dd><?php echo $this->bank['bankAcctName']; ?></dd>

                                        <dt><?php echo $this->translate('bankAcctType'); ?></dt>
                                        <dd>
                                            <?php echo $this->ShowDictionaryTo($this->dic_Setting['BANK_ACCOUNT_TYPE'], $this->userLangCode, $this->dic_Setting['BANK_ACCOUNT_TYPE'], $this->bank['bankAcctType']); ?>
                                        </dd>

                                        <dt><?php echo $this->translate('accountBKname'); ?></dt>
                                        <dd><?php echo $this->bank['bankName']; ?></dd>

                                        <dt><?php echo $this->translate('SWIFTCode'); ?></dt>
                                        <dd><?php echo $this->bank['swiftcode']; ?></dd>

                                        <dt><?php echo $this->translate('accountDF'); ?></dt>
                                        <dd>
                                            <?php if($this->bank['isDefault']){echo $this->translate('yes');}else{echo $this->translate('no');}?>
                                        </dd>

                                        <dt><?php echo $this->translate('accountADR'); ?></dt>
                                        <dd><?php echo $this->bank['bankAddress']; ?></dd>

                                        <dt><?php echo $this->translate('remarks'); ?></dt>
                                        <dd><?php echo $this->bank['remarks']; ?></dd>
                                    </dl>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="profile">
                                <div class="col-md-12">
                                    <?php echo $this->ShowWebuploader($this->bank['attachmentList'], $this->biz_Setting['BANK_ACCOUNT'], '0000', "1", $this->bank['bankAcctID']); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- viewer -->
<script type="text/javascript" src="/ky/viewer-1.0.0-dist/viewer.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        // viewer
        // 先判断是否有图片, 再初始化viewer
        if ($(".img-view > li").length > 0) {
            $(".img-view").viewer({
                url: "data-original"
            });
        }
	});
</script>
</body>
</html>
