<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title>快移</title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>

</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <?php echo $this->render(SEED_WWW_TPL.'/bank/r_top_menu.phtml');?>
        <div class="n_o_c_tit">
            <h4><!--银行账户详细--><?php echo $this->translate('accountNO').$this->translate('info');?></h4>
            <?php if($this->CompAdmin==true):?>
            <?php if($bank['bankAcctStatus']=='04'||$bank['bankAcctStatus']=='03'):?>
            <a class="p_ed fr mt10" href=<?php echo WWW.'user/bank/edit?'.base64_encode($this->bank['bankAcctID']);?> ></a>
            <?php endif;?>
            <?php endif;?>
        </div>
        <div class="o_c_content">
                <table>
                    <tbody>
                        <tr><td><span><!--账号--><?php echo $this->translate('accountNAME');?></span></td><td><?php echo $this->bank['bankAcctNo'];?></td></tr>
                        <tr><td><span><!--账号名称--><?php echo $this->translate('accountNO');?></span></td><td><?php echo $this->bank['bankAcctName'];?></td></tr>
                        <tr><td><span><!--账户类型--><?php echo $this->translate('accountTP');?></span></td>
                            <td> <?php echo $this-> ShowDictionaryTo("datatest_setting",$this->userlangCode,$this->dic_Setting['BANK_ACCOUNT_TYPE'],$this->bank['bankAcctType']);?></td></tr>
                        <tr><td><span><!--银行名称--><?php echo $this->translate('accountBKname');?></span></td><td><?php echo $this->bank['bankName'];?></td></tr>
                        <tr><td><span><!--SWITFCODE--><?php echo $this->translate('accountSCD');?></span></td><td><?php echo $this->bank['swiftcode'];?></td></tr>
                        <tr><td><span><!--是否默认--><?php echo $this->translate('accountDF');?></span></td>
                            <td><?php if($this->bank['isDefault']){echo $this->translate('yes');}else{echo $this->translate('no');}?></td></tr>
                        <tr style="width: 100%;"><td><span><!--开户行地址--><?php echo $this->translate('accountADR');?></span></td><td><?php echo $this->bank['bankAddress'];?></td></tr>
                        <tr style="width: 100%;"><td><span><!--备注--><?php echo $this->translate('accountBZ');?></span></td><td><?php echo $this->bank['remarks'];?></td></tr>
                    </tbody>
                 </table>
        </div>
        <div class="yyzz_box info_cont">
            <div class="zzname  n_o_c_tit"><h4><!-- 银行资料 --><?php echo $this->translate('UPBank');?></h4></div>
            <?php echo $this-> ShowWebuploader($this->bank['attachmentList'],$this->biz_Setting['BANK_ACCOUNT'],$this->attach_Setting['000000'],"1", $this->bank['bankAcctID']);?>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>