<?php echo $this->render("header.phtml") ?>

<h1>配送地区 - <?php echo $this->shipping['shipping_desc'];?></h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="列表" onclick="document.location='<?php echo $this->baseUrl();?>/shippingregion?shipping_name=<?php echo $this->shipping['shipping_name'];?>'"/>
    <input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->baseUrl();?>/shippingregion/add?shipping_name=<?php echo $this->shipping['shipping_name'];?>'"/>
  </p>
</div>
    注意：当前配置的是：<?php if(defined('CURRENT_MODULE_NAME') && CURRENT_MODULE_NAME=='center_hk'):?>HK站的配送管理，若需设置大陆的，则用大陆域名打开后台并进行管理。<?php endif;?>
<?php if(defined('CURRENT_MODULE_NAME') && CURRENT_MODULE_NAME=='center'):?>大陆站的配送管理，若需设置HK的，则用HK域名打开后台并进行管理。<?php endif;?>
<table class="admin_list">
  <tr>
    <th>名称</th>
    <th>说明</th>
    <th>操作</th>
  </tr>
  <?php if (is_array($this->shippingregions)) :?>
  <?php foreach ($this->shippingregions as $region) :?>
  <tr>
    <td style="width:30%;"><?php echo ($region['sr_name']);?></td>
    <td style="width:50%;"><?php echo ($region['sr_desc']);?></td>
    <td style="width:19%;"><a href="<?php echo $this->baseUrl();?>/shippingregion/update?shipping_name=<?php echo $this->shipping['shipping_name'];?>&sr_id=<?php echo ($region['sr_id']);?>"><img src="/images/center/edit.gif" title="编辑" alt="编辑"></a> <a href="<?php echo $this->baseUrl();?>/shippingregion/delete?shipping_name=<?php echo $this->shipping['shipping_name'];?>&sr_id=<?php echo ($region['sr_id']);?>"><img src="/images/center/del.gif" title="删除" alt="删除"></a></td>
  </tr>
  <?php endforeach;?>
  <?php endif;?>
</table>
<?php echo $this->render("footer.phtml") ?>