<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/chart/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1>删除信息</h1>
<div class="textnav">
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_list">
    <tr>
      <th>编号</th>
      <th>信息标题</th>
    </tr>
    <?php if(is_array($this->chartall)):?>
    <?php foreach($this->chartall as $key => $chart):?>
    <tr>
      <td><input type="checkbox" id="chart_id<?php echo ($chart['chart_id'])?>" name="chart_id[]" checked value="<?php echo ($chart['chart_id'])?>">
        <?php echo ($chart['chart_id'])?>
        <?php if(0 == $key):?>
        <input type="hidden" name="channel_id" value="<?php echo $chart['channel_id'];?>" />
        <input type="hidden" name="cate_id" value="<?php echo $chart['cate_id'];?>" />
        <?php endif;?></td>
      <td><?php echo ($chart['chart_name'])?></td>
    </tr>
    <?php endforeach; ?>
    <?php endif;?>
  </table>
  <div class="batch">
    <input type="submit" class="admin_bnt2" name="" value="确认删除" >
  </div>
</form>
<?php echo $this->render("footer.phtml") ?> 