<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>快移</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript">
        function doPasswd(){
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->baseUrl();?>/passwd',
                success: function() {
                }
            };
            $('#register_form').ajaxSubmit(options);
        }
    </script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div style="margin: 0 auto;" class="o_content w940">

        <div class="n_o_c_tit2">
            <h3>修改密码</h3>
        </div>
            <div class="u_info_ed_box">
            <form action="#" method="post" id="register_form">
                <div class="infobox">
                <dl class="infobox_pd">
                    <label>旧密码：</label>
                    <input type="text" name="ecommpasswsd" value=""/>
                </dl>
                 <dl class="infobox_pd">
                    <label>新密码：</label>
                    <input type="text" name="newpwd" value=""/>
                </dl>
                <dl class="infobox_pd">
                    <label>确认密码</label>
                    <input type="text" name="newpwd" value=""/>
                </dl>
                    </div>
                <p class="tc">
                    <input class="acc_rbtn" type="button" value="返回首页">
                    <input class="acc_sbtn" onclick="doPasswd()" type="submit" value="确认">
                </p>
            </form>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>