<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/order/order.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('partners'); ?></div>
                    <div class="list-group">
                        <a href="/user/sale" class="list-group-item"><?php echo $this->translate('orderSALLE'); ?></a>
                        <a href="/user/pur" class="list-group-item"><?php echo $this->translate('orderBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 order-main">
                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('orderINF01'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->resultMsg)): ?>
                        <div class="alert alert-success alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                        </div>
                        <?php endif; ?>

                        <ul id="optionTabs" class="nav nav-tabs nav-justified">
                            <li role="presentation" class="active">
                                <a href="#orderINF01" data-orderStatus="04" aria-controls="forActivate" role="tab" data-toggle="tab"><?php echo $this->translate('orderINF01'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#orderINF02" data-orderStatus="01" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('orderINF02'); ?>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#orderINF03" data-orderStatus="02" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('orderINF03'); ?>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#orderINF04" data-orderStatus="00" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('orderINF04'); ?>
                                </a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                                <input type="hidden" name="accountName" id="accountName">
                                <input type="hidden" name="crncode" id="crncode">
                                <input type="hidden" name="comcity" id="comcity">


                                <div role="tabpanel" class="tab-pane fade in active" id="orderINF01">
                                    <div class="form-group">
                                        <label for="buyerName" class="col-sm-3 control-label"><?php echo $this->translate('buyers'); ?></label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="buyerName" id="buyerName" placeholder="" value="<?php echo $this->orders['buyerName']; ?>" required >
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="buyerContactName" class="col-sm-3 control-label"><?php echo $this->translate('buyerATTN'); ?></label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="buyerContactName" id="buyerContactName" placeholder="" value="<?php echo $this->orders['buyerContactName']; ?>" required >
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="buyerCrnCode" class="col-sm-3 control-label"><?php echo $this->translate('payCNY'); ?></label>
                                        <div class="col-sm-8">
                                            <select class="selectpicker form-control" name="buyerCrnCode" id="buyerCrnCode" data-live-search="true">
                                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY'], $this->orders['buyerCrnCode']); ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="buyerContactName" class="col-sm-3 control-label"><?php echo $this->translate('thisATTN'); ?></label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="vendorContactName" id="vendorContactName" placeholder="" value="<?php echo $this->orders['vendorContactName']; ?>" required >
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="paymentTerm" class="col-sm-3 control-label"><?php echo $this->translate('remitMD'); ?></label>
                                        <div class="col-sm-8">
                                            <select class="selectpicker form-control" name="paymentTerm" id="paymentTerm" data-live-search="true">
                                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_TERM'], $this->userLangCode, $this->dic_Setting['PAYMENT_TERM'], $this->orders['paymentTerm']); ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="paymentPeriod" class="col-sm-3 control-label"><?php echo $this->translate('payDD'); ?></label>
                                        <div class="col-sm-8">
                                            <input type="number" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" min="1" step="1" >
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="isSelfSupport" class="col-sm-3 control-label"><?php echo $this->translate('exportMD'); ?></label>
                                        <div class="col-sm-8">
                                            <label class="radio-inline">
                                                <input type="radio" name="isSelfSupport" value="0"> <?php echo $this->translate('siteEX');?>
                                            </label>
                                            <label class="radio-inline">
                                                <input type="radio" name="isSelfSupport" value="1"> <?php echo $this->translate('sellersEX');?>
                                            </label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label for="buyerOrderRequest" class="col-sm-3 control-label"><?php echo $this->translate('payNeed'); ?></label>
                                        <div class="col-sm-8">
                                            <textarea class="form-control" name="buyerOrderRequest" id="buyerOrderRequest" rows="3"><?php echo $this->orders['paymentPeriod']; ?></textarea>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-8">
                                        <a class="btn btn-warning" href="#<?php echo $this->translate('save'); ?>" aria-controls="forActivate" role="tab" data-toggle="tab"><?php echo $this->translate('next'); ?></a>
                                    </div>
                                </div>
                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="orderINF02">
                                    <?php echo $this->translate('orderINF02'); ?>
                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="orderINF03">

                                </div>

                                <div role="tabpanel" class="tab-pane fade" id="orderINF04">

                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
    var dataDict = {};

    $().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $("#optionTabs a").click(function () {
            $("#orderStatus").val($(this).attr("data-orderStatus"));
            search();
        });

        $('#optionTabs a[data-orderStatus="<?php echo $this->orderStatus; ?>"]').tab('show');

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["ISIC_INDUSTRY_TYPE", "COUNTRY_ISO_CODE"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/sale/sale-order-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search,
                            orderStatus: $("#orderStatus").val()
                        };
                    },
                    columns: [{
                        field: 'orderNo',
                        title: '<?php echo $this->translate("orderNo"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("orderPrice"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + row.buyerCrnCode + " " + value + '</a>';
                        }
                    }, {
                        field: 'buyerName',
                        title: '<?php echo $this->translate("buyers"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'lastUpdate',
                        title: '<?php echo $this->translate("lastUpdate"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + new Date(value).format("yyyy-MM-dd hh:mm:ss") + '</a>';
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        formatter: function (value, row, index) {
                            var editTitle = "<?php echo $this->translate("edit");?>";
                            var rejectTitle = "<?php echo $this->translate('reject');?>";
                            var acceptTitle = "<?php echo $this->translate('accept');?>";
                            var delTitle = "<?php echo $this->translate('delete');?>";
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/edit?"+resultEnCode;

                            var result = '';
                            <?php if ($this->CompPartnerAdmin == true || $this->CompOrderAdmin == true): ?>
                            if (row.partnerStatus === '00') {
                                result += '<a title="' + editTitle+ '" href="' + href + '">'
                                    + '<i class="far fa-edit"></i>'
                                    + '</a>&nbsp;';

                            }

                            if (row.partnerStatus === '00' || row.partnerStatus === '01') {
                                result += '<a href="javascript:void(0)" title="' + delTitle + '" id="' + row.toID + '" data-url="/user/sale/delete" '
                                    + 'data-msg1="<?php echo $this->translate("is_delete");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_del_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_del_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-trash-alt"></i>'
                                    + '</a>&nbsp;';
                            }

                            if (row.partnerStatus === '02') {
                                result += '<a href="javascript:void(0)" title="' + acceptTitle + '" id="' + row.toID + '" data-url="/user/sale/accept" '
                                    + 'data-msg1="<?php echo $this->translate("is_accept");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_accept_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_accept_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="far fa-check-circle"></i>'
                                    + '</a>&nbsp;';

                                result += '<a href="javascript:void(0)" title="' + rejectTitle + '" id="' + row.toID + '" data-url="/user/sale/reject" '
                                    + 'data-msg1="<?php echo $this->translate("is_reject");?>" '
                                    + 'data-msg2="<?php echo $this->translate("tip_reject_success");?>" '
                                    + 'data-msg3="<?php echo $this->translate("tip_reject_fail");?>" '
                                    + 'onclick="doOption(this);" '
                                    + '>'
                                    + '<i class="fas fa-ban"></i>'
                                    + '</a>&nbsp;';
                            }
                            <?php endif; ?>

                            return result;
                        }
                    }]
                });
            }
        });
	});

	function search() {
        var listTable = $('#resultListTable');
        var options = {
            query:{
                keyword: $("#keyword").val(),
                orderStatus: $("#orderStatus").val()
            }
        };
        $(listTable).bootstrapTable('refresh', options);
    }

    function doOption(obj) {
        var url = $(obj).attr('data-url');
        var id = $(obj).attr('id');
        var msg1 = $(obj).attr('data-msg1');
        var msg2 = $(obj).attr('data-msg2');
        var msg3 = $(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title: false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
        }, function () {
            $.post(url,
                {'delID': id},
                function (data) {
                    if (data.status === 1) {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg2 + '</span>', {
                            skin: 'del-class',
                            icon: 1
                        });
                        search();
                        refreshBadge();
                    } else {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg3 + '</span><br>' + data.error, {
                            skin: 'del-class',
                            icon: 0
                        });
                        search();
                    }
                }, "json");
        }, function () {
            layer.closeAll();
        });
    }

    function refreshBadge() {
        var countQuery = '/user/sale/count-sale-order-ajax';
        $.ajax({
            type: "POST",
            url: countQuery,
            dataType: "json",
            success: function (data) {
                var waiting = "", forReview = "";
                $.each(data, function (i, item) {
                    if (i === '02') {
                        waiting = item;
                    } else if (i === '00') {
                        forReview = item;
                    }
                });

                $('.badge[data-orderStatus="02"]').html(waiting);
                $('.badge[data-orderStatus="00"]').html(forReview);
            }
        });
    }

    Date.prototype.format = function(fmt) {
        var o = {
            "M+" : this.getMonth()+1,                 //月份
            "d+" : this.getDate(),                    //日
            "h+" : this.getHours(),                   //小时
            "m+" : this.getMinutes(),                 //分
            "s+" : this.getSeconds(),                 //秒
            "q+" : Math.floor((this.getMonth()+3)/3), //季度
            "S"  : this.getMilliseconds()             //毫秒
        };
        if(/(y+)/.test(fmt)) {
            fmt=fmt.replace(RegExp.$1, (this.getFullYear()+"").substr(4 - RegExp.$1.length));
        }
        for(var k in o) {
            if(new RegExp("("+ k +")").test(fmt)){
                fmt = fmt.replace(RegExp.$1, (RegExp.$1.length==1) ? (o[k]) : (("00"+ o[k]).substr((""+ o[k]).length)));
            }
        }
        return fmt;
    }
</script>
</body>
</html>
