<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/order/order.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('partners'); ?></div>
                    <div class="list-group">
                        <a href="/user/sale" class="list-group-item"><?php echo $this->translate('orderSALLE'); ?></a>
                        <a href="/user/pur" class="list-group-item"><?php echo $this->translate('orderBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 order-main">
                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <input type="hidden" name="accountName" id="accountName">
                    <input type="hidden" name="crncode" id="crncode">
                    <input type="hidden" name="comcity" id="comcity">

                    <div class="panel panel-default">
                        <!-- Default panel contents -->
                        <div class="panel-heading"><?php echo $this->translate('orderINF01');?></div>
                        <div class="panel-body">
                            <?php if (!empty($this->resultMsg)): ?>
                            <div class="alert alert-success alert-dismissible fade in" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                            </div>
                            <?php endif; ?>

                            <div class="form-group">
                                <label for="buyerName" class="col-sm-2 control-label"><?php echo $this->translate('buyers'); ?></label>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="buyerName" id="buyerName" placeholder="" value="<?php echo $this->orders['buyerName']; ?>" required >
                                        <input type="hidden" name="buyer" id="buyer">
                                        <div class="input-group-addon">
                                            <a href="javascript:void(0)" data-toggle="modal" data-target="#myModal"><i class="fas fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>

                                <label for="buyerContactName" class="col-sm-2 control-label"><?php echo $this->translate('buyerATTN'); ?></label>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="buyerContactName" id="buyerContactName" placeholder="" value="<?php echo $this->orders['buyerContactName']; ?>" required >
                                        <input type="hidden" name="buyerContactID" id="buyerContactID">
                                        <div class="input-group-addon">
                                            <a href="javascript:void(0)" data-toggle="modal" data-target="#buyerContactModal"><i class="fas fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="buyerCrnCode" class="col-sm-2 control-label"><?php echo $this->translate('payCNY'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="buyerCrnCode" id="buyerCrnCode" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY'], $this->orders['buyerCrnCode']); ?>
                                    </select>
                                </div>

                                <label for="buyerContactName" class="col-sm-2 control-label"><?php echo $this->translate('thisATTN'); ?></label>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <input type="text" class="form-control" name="vendorContactName" id="vendorContactName" placeholder="" value="<?php echo $this->dfContactName; ?>" required >
                                        <input type="hidden" name="vendorContactID" id="vendorContactID" value="<?php echo $this->dfContactID;?>">
                                        <div class="input-group-addon">
                                            <a href="javascript:void(0)" data-toggle="modal" data-target="#contactModal"><i class="fas fa-plus"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('remitMD'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="paymentTerm" id="paymentTerm" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_TERM'], $this->userLangCode, $this->dic_Setting['PAYMENT_TERM'], $this->orders['paymentTerm']); ?>
                                    </select>
                                </div>

                                <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('payDD'); ?></label>
                                <div class="col-sm-3">
                                    <input type="number" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" min="0" step="1" >
                                </div>
                                <div class="col-sm-1">
                                    <p class="form-control-static">DAYS</p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="isSelfSupport" class="col-sm-2 control-label"><?php echo $this->translate('exportMD'); ?></label>
                                <div class="col-sm-8">
                                    <label class="radio-inline">
                                        <input type="radio" name="isSelfSupport" value="0" checked> <?php echo $this->translate('siteEX');?>
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="isSelfSupport" value="1"> <?php echo $this->translate('sellersEX');?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="buyerOrderRequest" class="col-sm-2 control-label"><?php echo $this->translate('payNeed'); ?></label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" name="buyerOrderRequest" id="buyerOrderRequest" rows="3"><?php echo $this->orders['paymentPeriod']; ?></textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <!-- Default panel contents -->
                        <div class="panel-heading"><?php echo $this->translate('orderINF02');?></div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="quotationMode" class="col-sm-2 control-label"><?php echo $this->translate('payJJ'); ?></label>
                                <div class="col-sm-8">
                                    <select class="selectpicker form-control" name="quotationMode" id="quotationMode" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['ORDER_QUOTATION_MODE'], $this->userLangCode, $this->dic_Setting['ORDER_QUOTATION_MODE'], $this->orders['quotationMode']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="priceTerm" class="col-sm-2 control-label"><?php echo $this->translate('payPrice'); ?></label>
                                <div class="col-sm-8">
                                    <select class="selectpicker form-control" name="priceTerm" id="priceTerm" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['PRICE_TERM'], $this->userLangCode, $this->dic_Setting['PRICE_TERM'], $this->orders['priceTerm']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="packingMode" class="col-sm-2 control-label"><?php echo $this->translate('payCasing'); ?></label>
                                <div class="col-sm-8">
                                    <select class="selectpicker form-control" name="packingMode" id="packingMode" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['ORDER_PACKING_MODE'], $this->userLangCode, $this->dic_Setting['ORDER_PACKING_MODE'], $this->orders['packingMode']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="packingDesc" class="col-sm-2 control-label"><?php echo $this->translate('packINF'); ?></label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" name="packingDesc" id="packingDesc" rows="3"><?php echo $this->orders['packingDesc']; ?></textarea>
                                </div>
                            </div>

                            <div class="page-header">
                                <h3><?php echo $this->translate('payGoods'); ?></h3>
                            </div>

                            <div class="alert alert-info alert-dismissible" role="alert">
                                <p class="text-center" style="cursor: pointer">

                                </p>
                            </div>

                            <button type="button" class="btn btn-default btn-lg btn-block">
                                <i class="fas fa-plus"></i> 点击选择商品
                            </button>

                            <div class="alert alert-info alert-dismissible" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('productNAME'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('productENNAME'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('packageTYPE'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('HSCODE'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('brand'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('model'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('productMaterial'); ?></label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('functionUsage'); ?></label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('orderprice'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('number'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('ordertotal'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('uiprice'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('uitotal'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('purchaseUnitPrice'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('quantity'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>

                                    <label for="paymentPeriod" class="col-sm-2 control-label"><?php echo $this->translate('netWeight'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="paymentTerm" class="col-sm-2 control-label"><?php echo $this->translate('grossWeight'); ?></label>
                                    <div class="col-sm-3">
                                        <input type="text" class="form-control" name="paymentPeriod" id="paymentPeriod" placeholder="" value="<?php echo $this->orders['paymentPeriod']; ?>" >
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <!-- Default panel contents -->
                        <div class="panel-heading"><?php echo $this->translate('orderINF03');?></div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="shippingMethod" class="col-sm-2 control-label"><?php echo $this->translate('moveMD'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="shippingMethod" id="shippingMethod" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SHIPPING_METHOD'], $this->userLangCode, $this->dic_Setting['SHIPPING_METHOD'], $this->orders['shippingMethod']); ?>
                                    </select>
                                </div>

                                <label for="clearancePlace" class="col-sm-2 control-label"><?php echo $this->translate('POCRC'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="clearancePlace" id="clearancePlace" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['EXPORT_POINTS'], $this->userLangCode, $this->dic_Setting['EXPORT_POINTS'], $this->orders['clearancePlace']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="loadingPort" class="col-sm-2 control-label"><?php echo $this->translate('portSHIP'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="loadingPort" id="loadingPort" data-live-search="true">
                                        <option value=""><?php echo $this->translate('et_select'); ?></option>
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SEA_PORT'], $this->userLangCode, $this->dic_Setting['SEA_PORT'], $this->orders['loadingPort']); ?>
                                    </select>
                                </div>

                                <label for="dischargePort" class="col-sm-2 control-label"><?php echo $this->translate('portDSCG'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="dischargePort" id="dischargePort" data-live-search="true">
                                        <option value=""><?php echo $this->translate('et_select'); ?></option>
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SEA_PORT'], $this->userLangCode, $this->dic_Setting['SEA_PORT'], $this->orders['dischargePort']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="deliveryPort" class="col-sm-2 control-label"><?php echo $this->translate('portDLVY'); ?></label>
                                <div class="col-sm-4">
                                    <select class="selectpicker form-control" name="deliveryPort" id="deliveryPort" data-live-search="true">
                                        <option value=""><?php echo $this->translate('et_select'); ?></option>
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SEA_PORT'], $this->userLangCode, $this->dic_Setting['SEA_PORT'], $this->orders['deliveryPort']); ?>
                                    </select>
                                </div>

                                <label for="deliveryPort" class="col-sm-2 control-label"><?php echo $this->translate('mabyDATE'); ?></label>
                                <div class="col-sm-4">
                                    <input type="date" class="form-control" name="deliveryDate" id="deliveryDate" placeholder="" value="<?php echo $this->orders['deliveryDate']; ?>" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="shippingServiceType" class="col-sm-2 control-label"><?php echo $this->translate('isFCL'); ?></label>
                                <div class="col-sm-6">
                                    <select class="selectpicker form-control" name="shippingServiceType" id="shippingServiceType" data-live-search="true">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SHIPPING_SERVICE_TYPE'], $this->userLangCode, $this->dic_Setting['SHIPPING_SERVICE_TYPE'], $this->orders['shippingServiceType']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sizeQuantityMap_20GP" class="col-sm-2 control-label"><?php echo $this->translate('infoFCL'); ?></label>
                                <div class="col-sm-1">
                                    <p class="form-control-static">20GP</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_20GP" id="sizeQuantityMap_20GP" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_20GP']; ?>" min="0" step="1" >
                                </div>
                                <div class="col-sm-1">
                                    <p class="form-control-static">40GP</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_40GP" id="sizeQuantityMap_40GP" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_40GP']; ?>" min="0" step="1" >
                                </div>
                                <div class="col-sm-1">
                                    <p class="form-control-static">40HQ</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_40HP" id="sizeQuantityMap_40HP" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_40HP']; ?>" min="0" step="1" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sizeQuantityMap_45HP" class="col-sm-2 control-label"></label>
                                <div class="col-sm-1">
                                    <p class="form-control-static">45HQ</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_45HP" id="sizeQuantityMap_45HP" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_45HP']; ?>" min="0" step="1" >
                                </div>
                                <div class="col-sm-1">
                                    <p class="form-control-static">20OT</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_20OT" id="sizeQuantityMap_20OT" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_20OT']; ?>" min="0" step="1" >
                                </div>
                                <div class="col-sm-1">
                                    <p class="form-control-static">40OT</p>
                                </div>
                                <div class="col-sm-1">
                                    <input type="number" class="form-control" name="sizeQuantityMap_40OT" id="sizeQuantityMap_40OT" placeholder="" value="<?php echo $this->orders['sizeQuantityMap_40OT']; ?>" min="0" step="1" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="needShipping" class="col-sm-2 control-label"><?php echo $this->translate('logisticSS'); ?></label>
                                <div class="col-sm-8">
                                    <label class="radio-inline">
                                        <input type="radio" name="needShipping" value="1" checked> <?php echo $this->translate('yes');?>
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="needShipping" value="0"> <?php echo $this->translate('no');?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="shippingRequest" class="col-sm-2 control-label"><?php echo $this->translate('logisticND'); ?></label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" name="shippingRequest" id="shippingRequest" rows="3"><?php echo $this->orders['shippingRequest']; ?></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="isAssignCustomsAgency" class="col-sm-2 control-label"><?php echo $this->translate('selectCHB'); ?></label>
                                <div class="col-sm-8">
                                    <label class="radio-inline">
                                        <input type="radio" name="isAssignCustomsAgency" value="1" checked> <?php echo $this->translate('yes');?>
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="isAssignCustomsAgency" value="0"> <?php echo $this->translate('no');?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="customsAgencyName" class="col-sm-2 control-label"><?php echo $this->translate('nameCHB'); ?></label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" name="customsAgencyName" id="customsAgencyName" rows="3"><?php echo $this->orders['customsAgencyName']; ?></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="needFinancing" class="col-sm-2 control-label"><?php echo $this->translate('nameSRV'); ?></label>
                                <div class="col-sm-8">
                                    <label class="radio-inline">
                                        <input type="radio" name="needFinancing" value="1" checked> <?php echo $this->translate('yes');?>
                                    </label>
                                    <label class="radio-inline">
                                        <input type="radio" name="needFinancing" value="0"> <?php echo $this->translate('no');?>
                                    </label>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="financingRequest" class="col-sm-2 control-label"><?php echo $this->translate('needOTH'); ?></label>
                                <div class="col-sm-8">
                                    <textarea class="form-control" name="financingRequest" id="financingRequest" rows="3"><?php echo $this->orders['financingRequest']; ?></textarea>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-8">
                                    <button type="submit" class="btn btn-warning btn-block"><?php echo $this->translate('save'); ?></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('buyers'); ?></h4>
            </div>

            <div class="modal-body">
                <table id="buyerListTable"></table>
            </div>

            <div class="modal-footer">
<!--                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>-->
                <button type="button" class="btn btn-primary" id="selectBuyerBtn"><?php echo $this->translate('submit'); ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="buyerContactModal" tabindex="-1" role="dialog" aria-labelledby="buyerContactModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('buyerATTN'); ?></h4>
            </div>

            <div class="modal-body">
                <table id="buyerContactListTable"></table>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="selectBuyerContactBtn"><?php echo $this->translate('submit'); ?></button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="contactModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('thisATTN'); ?></h4>
            </div>

            <div class="modal-body">
                <table id="contactListTable"></table>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="selectContactBtn"><?php echo $this->translate('submit'); ?></button>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    var dataDict = {};

    $().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        var $buyerTable = $("#buyerListTable"),
            $selectBuyerBtn = $("#selectBuyerBtn"),
            $buyerModal = $("#myModal"),
            $buyer = $("#buyer"),
            $buyerContactModal = $("#buyerContactModal"),
            $selectBuyerContactBtn = $("#selectBuyerContactBtn"),
            $buyerContactListTable = $('#buyerContactListTable'),
            $contactModal = $("#contactModal"),
            $selectContactBtn = $("#selectContactBtn"),
            $contactListTable = $('#contactListTable');

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["ISIC_INDUSTRY_TYPE", "COUNTRY_ISO_CODE", "PARTNER_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#buyerListTable').bootstrapTable({
                    url: '/user/buyer/buyer-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    clickToSelect: true,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search,
                            partnerStatus: $("#partnerStatus").val()
                        };
                    },
                    columns: [{
                        radio: true
                    },{
                        field: 'toName',
                        title: '<?php echo $this->translate("companyName"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            <?php if ($this->userrgCode == 'CN'): ?>

                            <?php else: ?>
                            if (row.toEnName !== null && row.toEnName !== '') {
                                value = row.toEnName;
                            }
                            <?php endif; ?>
                            return value;
                        }
                    }, {
                        field: 'industryCode',
                        title: '<?php echo $this->translate("industry"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            var result = value;
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'ISIC_INDUSTRY_TYPE') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'regdCountryCode',
                        title: '<?php echo $this->translate("regdCountry"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            var result = value;
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'COUNTRY_ISO_CODE') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'partnerStatus',
                        title: '<?php echo $this->translate("state"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            var result = value;
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PARTNER_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }]
                });

                $('#contactListTable').bootstrapTable({
                    url: '/user/account/contactlistajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    clickToSelect: true,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search
                        };
                    },
                    columns: [{
                        radio: true
                    },{
                        field: 'name',
                        title: '<?php echo $this->translate("name"); ?>'
                    }, {
                        field: 'ecommloginname',
                        title: '<?php echo $this->translate("username"); ?>'
                    }, {
                        field: 'ecommstatus',
                        title: '<?php echo $this->translate("userP"); ?>',
                        formatter: function (value) {
                            var result = "-";
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'ECOMM_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'contactStatus',
                        title: '<?php echo $this->translate("userPT"); ?>',
                        formatter: function (value) {
                            return (value === '01') ? '<?php echo $this->translate('normal') ?>' : '<?php echo $this->translate('disable'); ?>';
                        }
                    }, {
                        field: 'isDefaultPublic',
                        title: '<?php echo $this->translate("accountDF"); ?>',
                        formatter: function (value, row) {
                            return (value === true) ? '<?php echo $this->translate('yes') ?>' : '<?php echo $this->translate('no'); ?>';
                        }
                    }]
                });
            }
        });

        $buyerContactListTable.bootstrapTable({
            url: '/user/buyer/contact-list-ajax',
            method: 'post',
            // showRefresh: true,
            // search: true,
            pagination: true,
            classes: 'table table-no-bordered',
            sidePagination: 'server',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            pageNumber: 1,
            pageSize: 10,
            clickToSelect: true,
            queryParams: function(params) {
                return {
                    limit: params.limit,
                    skip: params.offset,
                    keyword: params.search,
                    toID: $("#buyer").val()
                };
            },
            columns: [{
                radio: true
            },{
                field: 'name',
                title: '<?php echo $this->translate("name"); ?>',
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }
                    return value;
                }
            }, {
                field: 'phone',
                title: '<?php echo $this->translate("personPhone"); ?>',
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = row.mobilePhone;
                    }
                    return value;
                }
            }, {
                field: 'email',
                title: '<?php echo $this->translate("email"); ?>',
                formatter: function (value, row) {
                    if (value === undefined || value === '' || value === null) {
                        value = "-";
                    }
                    return value;
                }
            }, {
                field: 'title',
                title: '<?php echo $this->translate("position"); ?>',
                formatter: function (value, row, index) {
                    return value;
                }
            }]
        });

        $selectBuyerBtn.click(function () {
            // alert('getSelections: ' + JSON.stringify($buyerTable.bootstrapTable('getSelections')));
            var selections = $buyerTable.bootstrapTable('getSelections');
            if (selections.length > 0) {
                $buyer.val(selections[0].toID);
                $("#buyerName").val(selections[0].toName);
                $('#buyerCrnCode').selectpicker('val', selections[0].crnCode);

                $.each(selections[0].contactList, function(i, contact) {
                    if (contact.isDefaultPublic === true) {
                        $("#buyerContactID").val(contact.contactID);
                        $("#buyerContactName").val(contact.name);
                        return false;
                    }
                });

                var options = {
                    query:{
                        toID: $buyer.val()
                    }
                };
                $buyerContactListTable.bootstrapTable('refresh', options);
                $buyerModal.modal('hide');
            }
        });

        $selectBuyerContactBtn.click(function () {
            // alert('getSelections: ' + JSON.stringify($buyerTable.bootstrapTable('getSelections')));
            console.log(JSON.stringify($buyerContactListTable.bootstrapTable('getSelections')));
            var selections = $buyerContactListTable.bootstrapTable('getSelections');
            if (selections.length > 0) {
                $("#buyerContactID").val(selections[0].contactID);
                $('#buyerContactName').val(selections[0].name);
                $buyerContactModal.modal('hide');
            }
        });

        $selectContactBtn.click(function () {
            // alert('getSelections: ' + JSON.stringify($buyerTable.bootstrapTable('getSelections')));
            console.log(JSON.stringify($contactListTable.bootstrapTable('getSelections')));
            var selections = $contactListTable.bootstrapTable('getSelections');
            if (selections.length > 0) {
                $("#vendorContactID").val(selections[0].contactID);
                $('#vendorContactName').val(selections[0].name);
                $contactModal.modal('hide');
            }
        });
	});
</script>
</body>
</html>
