<div id="deliveryEditDiv" class="layui-form">
	<div class="et-auth-error" style="display: none;"></div>
	<div class="">
		<div class="layui-form-item">
			<table class="layui-table" lay-skin="line" id="deliveryEditTable">
				<colgroup>
					<col>
					<col width="140">
					<col width="100">
					<col width="100">
					<col width="160">
				</colgroup>
				<thead>
				<tr>
					<th>名称</th>
					<th>型号</th>
					<th>单价</th>
					<th>数量</th>
					<th>总价</th>
				</tr>
				</thead>
				<tbody>
                <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
					<tr>
						<td style="text-align: left"><?php echo $value->productName;?></td>
						<td style="text-align: left"><?php echo $value->productModel;?></td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode;?><label><?php echo $value->vendorUnitPrice;?></label></td>
						<td style="text-align: left">
							<input name="deliveryQuantity_edit" class="layui-input" value="<?php echo $value->deliveryQuantity;?>" />
							<input type="hidden" name="orderItemID_edit" value="<?php echo $value->itemID;?>" />
						</td>
						<td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;<label id="itemID_<?php echo $value->itemID;?>"><?php echo $value->vendorTotalAmount;?></label></td>
					</tr>
                <?php endforeach; ?>
				</tbody>
			</table>
		</div>

        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLPG'], '0', null); ?>
            </div>
        </div>
	</div>
</div>
