<div id="deliveryAddDiv" class="layui-form">
	<div class="et-auth-top et-auth-bg-orange" style="height: 60px; text-align: left;">
		<h3><?php echo $this->translate('deliveryAdd'); ?></h3>
	</div>
	<div class="et-auth-error" style="display: none;"></div>

	<div class="">
		<div style="margin-top: 20px;"></div>

		<div class="layui-form-item">
			<table class="layui-table" lay-skin="line">
				<colgroup>
					<col>
					<col width="140">
					<col width="100">
					<col width="100">
					<col width="160">
				</colgroup>
				<thead>
				<tr>
                    <th><?php echo $this->translate('productNAME'); ?></th>
                    <th><?php echo $this->translate('model'); ?></th>
                    <th><?php echo $this->translate('uprice'); ?></th>
                    <th><?php echo $this->translate('number'); ?></th>
                    <th><?php echo $this->translate('ordertotal'); ?></th>
				</tr>
				</thead>
				<tbody>
                <?php foreach ($this->orderItemList as $index => $value):?>
					<tr>
						<td style="text-align: left; vertical-align: middle;"><?php echo $value->productName;?></td>
						<td style="text-align: left"><?php echo $value->productModel;?></td>
						<td style="text-align: left"><?php echo $this->deliveryCrnCode;?><label><?php echo $value->contractUnitPrice;?></label></td>
						<td style="text-align: left">
							<?php
							$quantity = $value->quantity - $value->deliveryQuantity <= 0  ? 0 : $value->quantity - $value->deliveryQuantity;
							?>
							<input name="deliveryQuantity_add" class="layui-input" value="<?php echo $quantity;?>" />
							<input type="hidden" name="orderItemID_add" value="<?php echo $value->itemID;?>" />
						</td>
						<td style="text-align: left"><?php echo $this->deliveryCrnCode?>&nbsp;<label id="itemID_<?php echo $value->itemID;?>"></label></td>
					</tr>
                <?php endforeach; ?>
				</tbody>
			</table>
		</div>

		<div class="layui-form-item">
			<div class="layui-form-label" style="width: 420px;">
				<div class="yyzz_box clearfix" style="width: 600px;">
					<p class="zzname" id="deliveryEditAttachment" style="width: 600px; font-weight:bold;"><?php echo $this->translate('PREPARE_GOODS'); ?><!--合同相关附件上传--></p>
                    <?php
                        echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLPG'], "0", null);
                    ?>
				</div>
			</div>
		</div>

		<div style="height: 12px"></div>
		<div class="et-auth-row">
			<button class="layui-btn layui-btn-warm" id="deliveryAddConfirmBtn"><?php echo $this->translate('confirmed'); ?></button>&nbsp;&nbsp;
		</div>
	</div>
</div>
