<div id="deliveryDeliverDiv" class="layui-form">
    <div class="col-sm-12">
        <table class="layui-table" lay-skin="line">
            <colgroup>
                <col>
                <col width="140">
                <col width="120">
                <col width="80">
                <col width="160">
            </colgroup>
            <thead>
            <tr>
                <th>名称</th>
                <th>型号</th>
                <th>单价</th>
                <th>数量</th>
                <th>总价</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
                <tr>
                    <td style="text-align: left"><?php echo $value->productName;?></td>
                    <td style="text-align: left"><?php echo $value->productModel;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode;?>&nbsp;
                        <label class="buyerUnitPrice_"></label>
                        <script type="text/javascript">$(".buyerUnitPrice_").html(formatCurrency(<?php echo $value->buyerUnitPrice;?>, 2));</script>
                    </td>
                    <td style="text-align: left"><?php echo $value->deliveryQuantity;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;
                        <label class="buyerTotalAmount_"></label>
                        <script type="text/javascript">$(".buyerTotalAmount_").html(formatCurrency(<?php echo $value->buyerTotalAmount;?>, 2));</script>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
