<div id="deliveryViewDiv" class="layui-form">
    <div class="col-sm-12">
        <table class="layui-table" lay-skin="line" id="deliveryEditTable">
            <colgroup>
                <col width="140">
                <col width="180">
                <col width="130">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="160">
            </colgroup>
            <thead>
            <tr>
                <th><?php echo $this->translate('productNAME'); ?></th>
                <th><?php echo $this->translate('model'); ?></th>
                <th><?php echo $this->translate('uprice'); ?></th>
                <th><?php echo $this->translate('number'); ?></th>
                <th><?php echo $this->translate('quantity'); ?></th>
                <th><?php echo $this->translate('totalNetWeight'); ?>(KGS)</th>
                <th><?php echo $this->translate('totalGrossWeight'); ?>(KGS)</th>
                <th><?php echo $this->translate('totalVolume'); ?>(CBM)</th>
                <th><?php echo $this->translate('ordertotal'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->delivery->deliveryItemList as $index => $value): ?>
                <tr>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->productName; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->productModel; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $this->delivery->crnCode; ?>&nbsp;
                        <label class="buyerUnitPrice_"></label>
                        <script type="text/javascript">$(".buyerUnitPrice_").html(formatCurrency(<?php echo $value->buyerUnitPrice;?>, 2));</script>
                    </td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->deliveryQuantity; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalPackages; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalNetWeight; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalGrossWeight; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalVolume; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $this->delivery->crnCode ?>&nbsp;
                        <label class="buyerTotalAmount_"></label>
                        <script type="text/javascript">$(".buyerTotalAmount_").html(formatCurrency(<?php echo $value->buyerTotalAmount;?>, 2));</script>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12 deliveryContract">
        <?php foreach ($this->deliveryContractList as $deliveryContract): ?>
            <?php if (!empty($deliveryContract['contractList'])): ?>
                <div class="row">
                    <div class="col-xs-1">
                        <p class="form-control-static text-999"><?php echo $this->translate('supplierName'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666"><?php echo $deliveryContract['supplierName']; ?></p>
                    </div>
                </div>

                <?php echo $this->ShowOrderContract4Factoring($deliveryContract['contractList'], $this->accountID); ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>

    <!-- 备货相关附件 -->
    <?php if (is_array($this->prepareAttachmentList) && count($this->prepareAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('PREPARE_GOODS') . $this->translate('download'); ?></h4>
            </div>
        </div>
        <?php foreach ($this->prepareAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- 验货相关附件 -->
    <?php if (is_array($this->examineAttachmentList) && count($this->examineAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('EXAMINE_GOODS') . $this->translate('download'); ?></h4>
            </div>
        </div>

        <?php foreach ($this->examineAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- 质量保证函正本 -->
    <?php if (is_array($this->qualityAttachmentList) && count($this->qualityAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('QUALITY_AGREE_FORMAL') . $this->translate('download'); ?></h4>
            </div>
        </div>

        <?php foreach ($this->qualityAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- 发货相关附件 -->
    <?php if (is_array($this->deliverAttachmentList) && count($this->deliverAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('DELIVER_GOODS') . $this->translate('download'); ?></h4>
            </div>
        </div>

        <?php foreach ($this->deliverAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- 收货相关附件 -->
    <?php if (is_array($this->receiptAttachmentList) && count($this->receiptAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('RECEIPT_GOODS') . $this->translate('download'); ?></h4>
            </div>
        </div>

        <?php foreach ($this->receiptAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>

    <!-- 收货确认函正本 -->
    <?php if (is_array($this->receiptConfirmationAttachmentList) && count($this->receiptConfirmationAttachmentList) > 0): ?>
        <div class="col-xs-12">
            <div class="page-header">
                <h4><?php echo $this->translate('RECEIPT_CONFIRMATION_FORMAL') . $this->translate('download'); ?></h4>
            </div>
        </div>

        <?php foreach ($this->receiptConfirmationAttachmentList as $k => $attach): ?>
            <div class="col-xs-8">
                <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext); ?>.png') no-repeat;background-size: 20px;"></em>
                <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'] . '/doc/download.action?sid=' . session_id() . '&nid=' . $attach->attachID . '&vid=' . $attach->verifyID; ?>" download>
                    <p class="new_uptitle"><?php echo $attach->name; ?></p>
                </a>
            </div>
            <div class="col-xs-4">
                <?php echo $this->translate('creatdate') . " " . date('Y-m-d H:i:s', strtotime($attach->createTime)); ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>
