<div id="deliveryDeliverDiv" class="layui-form">
    <div class="col-sm-12">
        <table class="layui-table" lay-skin="line">
            <colgroup>
                <col>
                <col width="140">
                <col width="120">
                <col width="80">
                <col width="160">
            </colgroup>
            <thead>
            <tr>
                <th><?php echo $this->translate('productNAME'); ?></th>
                <th><?php echo $this->translate('model'); ?></th>
                <th><?php echo $this->translate('uprice'); ?></th>
                <th><?php echo $this->translate('number'); ?></th>
                <th><?php echo $this->translate('ordertotal'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
                <tr>
                    <td style="text-align: left"><?php echo $value->productName;?></td>
                    <td style="text-align: left"><?php echo $value->productModel;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode;?>&nbsp;
                        <label class="buyerUnitPrice_">
                            <?php echo $value->buyerUnitPrice != 0 ? number_format($value->buyerUnitPrice, 2) : '----'; ?>
                        </label>
                    </td>
                    <td style="text-align: left"><?php echo $value->deliveryQuantity;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;
                        <label class="buyerTotalAmount_">
                            <?php echo $value->buyerTotalAmount != 0 ? number_format($value->buyerTotalAmount, 2) : '----'; ?>
                        </label>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12 deliveryContract">
        <?php foreach ($this->deliveryContractList as $deliveryContract): ?>
            <?php if (!empty($deliveryContract['contractList'])): ?>
                <div class="row">
                    <div class="col-xs-1">
                        <p class="form-control-static text-999"><?php echo $this->translate('supplierName'); ?></p>
                    </div>
                    <div class="col-md-10">
                        <p class="form-control-static text-666"><?php echo $deliveryContract['supplierName']; ?></p>
                    </div>
                </div>

                <?php echo $this->ShowOrderContract4Factoring($deliveryContract['contractList'], $this->accountID); ?>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>
</div>
