<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/order/order.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('orderIN'); ?></div>
                    <div class="list-group">
                        <a href="/user/sale" class="list-group-item"><?php echo $this->translate('orderSALLE'); ?></a>
                        <a href="/user/pur" class="list-group-item"><?php echo $this->translate('orderBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-12 order-main">
                <ol class="breadcrumb hidden">
                    <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
                    <li><a href="/user/settle"><?php echo $this->translate('settle_IN'); ?></a></li>
                    <li class="active"><?php echo $this->translate('settle_List'); ?></li>
                </ol>

                <div class="panel panel-default">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->translate('orderSALLE'); ?></div>
                    <div class="panel-body">
                        <?php if (!empty($this->resultMsg)): ?>
                        <div class="alert alert-success alert-dismissible fade in" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <p><?php echo base64_decode($this->resultMsg); ?></p>
                        </div>
                        <?php endif; ?>

                        <ul id="optionTabs" class="nav nav-tabs nav-justified">
                            <li role="presentation" class="active">
                                <a href="#forActivate" data-orderStatus="04" aria-controls="forActivate" role="tab" data-toggle="tab"><?php echo $this->translate('valid'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-orderStatus="01" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('forReview'); ?>&nbsp;<span class="badge" data-orderStatus="01"><?php echo $this->countOrder['01']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-orderStatus="02" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('forConfirm'); ?>&nbsp;<span class="badge" data-orderStatus="02"><?php echo $this->countOrder['02']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-orderStatus="00" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('draft'); ?>&nbsp;<span class="badge" data-orderStatus="00"><?php echo $this->countOrder['00']; ?></span>
                                </a>
                            </li>
                            <li role="presentation">
                                <a href="#forActivate" data-orderStatus="10" aria-controls="forActivate" role="tab" data-toggle="tab">
                                    <?php echo $this->translate('history'); ?>&nbsp;<span class="badge" data-orderStatus="10"><?php echo $this->countOrder['10']; ?></span>
                                </a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="forActivate">
                                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                                    <div class="form-group" style="margin-bottom: 0 !important;">
                                        <label for="keyword" class="sr-only">keyword</label>
                                        <div class="col-sm-6 col-xs-7">
                                            <div class="input-group">
                                                <span class="input-group-addon"><i class="fas fa-search"></i></span>
                                                <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('INPkw_order_xs');?>">
                                                <input type="hidden" name="orderStatus" id="orderStatus" value="<?php echo $this->orderStatus; ?>" >
                                            </div>
                                        </div>
                                        <div class="col-sm-1 col-xs-2">
                                            <button type="submit" class="btn btn-primary"> Go </button>
                                        </div>
                                        <?php if ($this->CompPartnerAdmin == true): ?>
                                        <div class="col-sm-1 col-xs-2 col-sm-offset-4">
                                            <a title="<?php echo $this->translate('add');?>" href="/user/sale/add" class="btn btn-default">
                                                <i class="fas fa-plus"></i>
                                            </a>
                                        </div>
                                        <?php endif; ?>
                                    </div>
                                </form>

                                <!-- Table -->
                                <table id="resultListTable"></table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script src="/ky/js/base64.js"></script>

<script type="text/javascript">
    var dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>' === ''?'zh_CN':'<?php echo $this->userLangCode?>';

    $().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        $("#optionTabs a").click(function () {
            $("#orderStatus").val($(this).attr("data-orderStatus"));
            search();
        });

        //$('#optionTabs a[data-orderStatus="<?php //echo $this->orderStatus; ?>//"]').tab('sPDFJShow');

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["ISIC_INDUSTRY_TYPE", "COUNTRY_ISO_CODE"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/sale/sale-order-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-hover table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    height: 489,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            orderStatus: $("#orderStatus").val()
                        };
                    },
                    onClickRow: function(row) {
                        console.log(row.orderID);

                        var resultEnCode = new Base64().encode(row.orderID);
                        window.location.href = "/user/sale/view?"+resultEnCode;
                    },
                    columns: [{
                        field: 'orderNo',
                        title: '<?php echo $this->translate("orderNo"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;
                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("orderPrice"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + row.buyerCrnCode + " " + value + '</a>';
                        }
                    }, {
                        field: 'buyerName',
                        title: '<?php echo $this->translate("buyers"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            if (userLangCode === 'en_US') {
                                if (row.buyerEnName !== '') {
                                    value = row.buyerEnName;
                                }
                            }

                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + value + '</a>';
                        }
                    }, {
                        field: 'lastUpdate',
                        title: '<?php echo $this->translate("lastUpdate"); ?>',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/view?"+resultEnCode;

                            return '<a href="' + href + '">' + new Date(value).format("yyyy-MM-dd hh:mm:ss") + '</a>';
                        }
                    }, {
                        title: '<?php echo $this->translate("operation"); ?>',
                        formatter: function (value, row, index) {
                            var editTitle = "<?php echo $this->translate("edit");?>";
                            var delTitle = "<?php echo $this->translate('delete');?>";
                            var cancelTitle = "<?php echo $this->translate('cancel');?>";
                            var submitForReviewTitle = "<?php echo $this->translate('submit');?>";
                            var base = new Base64();
                            var resultEnCode = base.encode(row.orderID);
                            var href = "/user/sale/edit?"+resultEnCode;

                            var result = '';
                            <?php if ($this->CompOrderAdmin == true): ?>
                            if (row.agent !== undefined && row.agent !== '') {
                                if ('<?php echo $this->accountID; ?>' === row.agent) {
                                    if (row.orderStatus === '00' || row.orderStatus === '01' || row.orderStatus === '02' || row.orderStatus === '05') {
                                        result += '<a title="' + editTitle+ '" href="' + href + '">'
                                            + '<i class="far fa-edit"></i>'
                                            + '</a>&nbsp;';
                                    }

                                    if (row.orderStatus === '01' || row.orderStatus === '02' || row.orderStatus === '05') {
                                        result += '<a href="javascript:void(0)" title="' + cancelTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/cancel" '
                                            + 'data-msg1="<?php echo $this->translate("is_cancel");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_cancel_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_cancel_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="fas fa-ban"></i>'
                                            + '</a>&nbsp;';
                                    }

                                    if (row.orderStatus === '00') {
                                        result += '<a href="javascript:void(0)" title="' + delTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/del" '
                                            + 'data-msg1="<?php echo $this->translate("is_delete");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_del_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_del_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="far fa-trash-alt"></i>'
                                            + '</a>&nbsp;';

                                        result += '<a href="javascript:void(0)" title="' + submitForReviewTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/submit" '
                                            + 'data-msg1="<?php echo $this->translate("is_submit");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_forReview_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_forReview_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="far fa-check-circle"></i>'
                                            + '</a>&nbsp;';
                                    }
                                }
                            } else {
                                if ('<?php echo $this->accountID; ?>' === row.client) {
                                    if (row.orderStatus === '00' || row.orderStatus === '01' || row.orderStatus === '02' || row.orderStatus === '05') {
                                        result += '<a title="' + editTitle+ '" href="' + href + '">'
                                            + '<i class="far fa-edit"></i>'
                                            + '</a>&nbsp;';
                                    }

                                    if (row.orderStatus === '01' || row.orderStatus === '02' || row.orderStatus === '05') {
                                        result += '<a href="javascript:void(0)" title="' + cancelTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/cancel" '
                                            + 'data-msg1="<?php echo $this->translate("is_cancel");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_cancel_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_cancel_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="fas fa-ban"></i>'
                                            + '</a>&nbsp;';
                                    }

                                    if (row.orderStatus === '00') {
                                        result += '<a href="javascript:void(0)" title="' + delTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/del" '
                                            + 'data-msg1="<?php echo $this->translate("is_delete");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_del_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_del_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="far fa-trash-alt"></i>'
                                            + '</a>&nbsp;';

                                        result += '<a href="javascript:void(0)" title="' + submitForReviewTitle + '" data-id="' + row.orderID + '" data-url="/user/sale/submit" '
                                            + 'data-msg1="<?php echo $this->translate("is_submit");?>" '
                                            + 'data-msg2="<?php echo $this->translate("tip_forReview_success");?>" '
                                            + 'data-msg3="<?php echo $this->translate("tip_forReview_fail");?>" '
                                            + 'onclick="doOption(this);" '
                                            + '>'
                                            + '<i class="far fa-check-circle"></i>'
                                            + '</a>&nbsp;';
                                    }
                                }
                            }
                            <?php endif; ?>

                            return result;
                        }
                    }]
                });
            }
        });
	});

	function search() {
        var listTable = $('#resultListTable');
        var options = {
            query:{
                skip: 0,
                keyword: $("#keyword").val(),
                orderStatus: $("#orderStatus").val()
            },
            pageNumber: 1
        };
        $(listTable).bootstrapTable('refresh', options);
    }

    function doOption(obj) {
        var url = $(obj).attr('data-url');
        var id = $(obj).attr('data-id');
        var msg1 = $(obj).attr('data-msg1');
        var msg2 = $(obj).attr('data-msg2');
        var msg3 = $(obj).attr('data-msg3');
        //询问框
        layer.confirm(msg1, {
            title: false,
            closeBtn: 0,
            btn: ['<?php echo $this->translate('yes');?>', '<?php echo $this->translate('no');?>'] //按钮
        }, function () {
            $.post(url,
                {'delID': id},
                function (data) {
                    if (data.status === 1) {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg2 + '</span>', {
                            skin: 'del-class',
                            icon: 1
                        });
                        search();
                        refreshBadge();
                    } else {
                        layer.msg('<span style="color: #EF8200;font-size: 16px;">' + msg3 + '</span><br>' + data.error, {
                            skin: 'del-class',
                            icon: 0
                        });
                        search();
                    }
                }, "json");
        }, function () {
            layer.closeAll();
        });
    }

    function refreshBadge() {
        var countQuery = '/user/sale/count-sale-order-ajax';
        $.ajax({
            type: "POST",
            url: countQuery,
            dataType: "json",
            success: function (data) {
                var waiting = "", forReview = "";
                $.each(data, function (i, item) {
                    if (i === '02') {
                        waiting = item;
                    } else if (i === '00') {
                        forReview = item;
                    }
                });

                $('.badge[data-orderStatus="02"]').html(waiting);
                $('.badge[data-orderStatus="00"]').html(forReview);
            }
        });
    }
</script>
</body>
</html>
