<div class="row">
    <div class="col-md-2">
        <p class="form-control-static text-999"><?php echo $this->translate("taskContents"); ?></p>
    </div>
    <div class="col-md-10">
        <p class="form-control-static text-666">
            <?php echo $this->orderTask->contents; ?>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p class="form-control-static text-999"><?php echo $this->translate("taskBeginTime"); ?></p>
    </div>
    <div class="col-md-4">
        <p class="form-control-static text-666">
            <?php echo empty($this->orderTask->beginTime) ? null : date('Y-m-d H:i:s', strtotime($this->orderTask->planBeginTime)); ?>
        </p>
    </div>
    <div class="col-md-2">
        <p class="form-control-static text-999"><?php echo $this->translate("taskEndTime"); ?></p>
    </div>
    <div class="col-md-4">
        <p class="form-control-static text-666">
            <?php echo empty($this->orderTask->endTime) ? null : date('Y-m-d H:i:s', strtotime($this->orderTask->planEndTime)); ?>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p class="form-control-static text-999"><?php echo $this->translate("taskProgress"); ?></p>
    </div>
    <div class="col-md-8">
        <div class="progress">
            <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?php echo $this->orderTask->progress; ?>" aria-valuemin="0" aria-valuemax="100" style="width: <?php echo $this->orderTask->progress; ?>%;">
                <?php echo $this->orderTask->progress; ?>%
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-2">
        <p class="form-control-static text-999"><?php echo $this->translate("taskPrincipal"); ?></p>
    </div>
    <div class="col-md-10">
        <p class="form-control-static text-666">
            <?php foreach ($this->orderTask->taskPrincipalList as $index => $principal):?>
                <?php echo $principal->displayName; ?>,
            <?php endforeach; ?>
        </p>
    </div>
</div>

<?php foreach ($this->orderTask->taskDeliveryList as $index => $taskDelivery):?>
    <div class="alert alert-info alert-dismissible taskDeliveryAlert" role="alert">
        <div class="row">
            <div class="col-xs-2"><?php echo $this->translate("taskDelivery"); ?></div>
            <div class="col-sm-4"><?php echo $taskDelivery->subject; ?></div>
            <div class="col-xs-2"><?php echo $this->translate("deliveryCreateTime"); ?></div>
            <div class="col-sm-4">
                <?php echo empty($taskDelivery->createTime) ? null : date('Y-m-d H:i:s', strtotime($taskDelivery->createTime)); ?>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-8"><?php echo $taskDelivery->contents; ?></div>
        </div>

        <?php if (!empty($taskDelivery->location)): ?>
        <div class="row">
            <div class="col-sm-8 mapMarked" style="cursor: pointer;" data-delivery-id="<?php echo $taskDelivery->taskDeliveryID; ?>" data-longitude="<?php echo json_decode($taskDelivery->location)->longitude; ?>" data-latitude="<?php echo json_decode($taskDelivery->location)->latitude; ?>">
                <i class="fas fa-map-marked-alt"></i> <?php echo json_decode($taskDelivery->location)->address; ?>
            </div>
        </div>

        <div class="row map-<?php echo $taskDelivery->taskDeliveryID; ?>">
            <div class="col-sm-10 text-999 mapContainer-<?php echo $taskDelivery->taskDeliveryID; ?>" id="mapContainer_<?php echo $index; ?>" style="height:500px; margin: 0; padding: 0;">11</div>
        </div>
        <?php endif; ?>

        <div class="row">
            <div class="col-sm-12">
                <?php echo $this->ShowUPimg($taskDelivery->attachmentList); ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>

<div class="row" id="mapTestDiv" style="height:500px; margin: 0; padding: 0;">11</div>

<script type="text/javascript">
    $(".mapMarked").click(function () {
        console.log($("#mapTestDiv").html());
        var deliveryID = $(this).attr("data-delivery-id"),
            longitude = $(this).attr("data-longitude"),
            latitude = $(this).attr("data-latitude"),
            $map = $(".map-" + deliveryID),
            $mapContainer = $(".mapContainer-" + deliveryID),
            mapContainerID = $mapContainer.attr("id");

        console.log($mapContainer.html());
        $(".text-999").append("<b>Hello world!</b>");
        $mapContainer.append("<b>Hello world1111!</b>");
        document.getElementById("mapContainer_0").innerHTML="your str";
        console.log($mapContainer.html());


        var script = document.createElement("script");
        script.src = "http://api.map.baidu.com/api?v=2.0&ak=8P5e0fcLzr2U3MfSB282xuaK8TcHh46g&callback=initialize(4.9E-324, 4.9E-324)";
        document.body.appendChild(script);

        // if ($map.hasClass("hidden")) {
        //     $map.removeClass("hidden");
        // } else {
        //     $map.addClass("hidden");
        // }
    });

    function initialize(pointx, pinty) {
        // console.log("in");
        var map = new BMap.Map("mapContainer_0");         // 创建地图实例
        var point = new BMap.Point(pointx, pinty);      // 创建点坐标
        map.centerAndZoom(point, 15);                   // 初始化地图，设置中心点坐标和地图级别
        map.enableScrollWheelZoom(true);                // 开启鼠标滚轮缩放
        var marker = new BMap.Marker(point);            // 创建点
        map.addOverlay(marker);
    }
</script>
