<table class="table">
    <thead>
    <tr>
        <th><?php echo $this->translate('settle_Time'); ?></th>
        <th><?php echo $this->translate('type'); ?></th>
        <th><?php echo $this->translate('settle_TradeID'); ?></th>
        <th><?php echo $this->translate('settle_For'); ?></th>
        <th class="text-center"><?php echo $this->translate('ordertotal'); ?></th>
        <th class="text-center"><?php echo $this->translate('settle_Status'); ?></th>
        <th><?php echo $this->translate('operation'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if (is_array($this->jsd) && count($this->jsd) > 0): ?>
        <?php foreach ($this->jsd as $k => $paymentTrading): ?>
            <tr>
                <td style="vertical-align: middle;"><?php echo date('Y-m-d H:i:s', strtotime($paymentTrading['recordDate'])); ?></td>
                <td style="vertical-align: middle;">
                    <?php if ($paymentTrading['tradingType'] == 'D'): ?>
                        <?php echo $this->ShowDictionaryTo("AR_AP_TYPE", $this->userLangCode, $this->dic_Setting['AR_AP_TYPE'], $paymentTrading['rptype']); ?>
                    <?php else: ?>
                        <?php echo $this->ShowDictionaryTo("PAYMENT_TRADING_TYPE", $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'], $paymentTrading['tradingType']); ?>
                    <?php endif;?>
                </td>
                <td>
                    <?php echo $paymentTrading['transNo']; ?><br>
                    <span style="color: #ccc;">
                    <?php echo $paymentTrading['subject']; ?><br>
                    <?php echo $paymentTrading['remarks']; ?>
                    </span>
                </td>
                <td style="vertical-align: middle;"><?php echo $paymentTrading['customerName']; ?></td>
                <td class="text-right" style="vertical-align: middle;">
                    <?php if ($paymentTrading['rptype'] == 'P'):?>
                        <p class="text-danger">
                            <?php echo $paymentTrading['crnCode']; ?>&nbsp;<?php echo number_format($paymentTrading['totalAmount'], 2); ?>
                        </p>
                    <?php else: ?>
                        <?php echo $paymentTrading['crnCode']; ?>&nbsp;<?php echo number_format($paymentTrading['totalAmount'], 2); ?>
                    <?php endif; ?>
                </td>
                <td style="vertical-align: middle;">
                    <?php if ($paymentTrading['paymentStatus'] == 0):?>
                        <?php if ($paymentTrading['rptype'] == 'P'): ?>
                            <?php echo $this->translate('settle_status_payment'); ?>
                        <?php elseif ($paymentTrading['rptype'] == 'R'):?>
                            <?php echo $this->translate('settle_status_receivable'); ?>
                        <?php elseif ($paymentTrading['rptype'] == 'O'):?>
                            <?php echo $this->translate('settle_status_forCheck'); ?>
                        <?php endif;?>
                    <?php else: ?>
                        <?php echo $this->ShowDictionaryTo("PAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $paymentTrading['paymentStatus']); ?>
                    <?php endif; ?>
                </td>
                <td style="vertical-align: middle;">
                    <?php if ($paymentTrading['allowPayment']): ?>
                        <a href="/user/settle/payment?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('settle_payment'); ?></a>|
                    <?php endif; ?>
                    <?php if ($paymentTrading['allowTransfer']): ?>
                        <a href="/user/settle/transfer?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('settle_transfer'); ?></a>|
                    <?php endif; ?>
                    <a href="/user/settle/listview?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('settle_INF'); ?></a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="7"><?php echo $this->translate('noData'); ?></td>
        </tr>
    <?php endif; ?>
    </tbody>
</table>
