<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/order/order.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('orderIN'); ?></div>
                    <div class="list-group">
                        <a href="/user/sale" class="list-group-item"><?php echo $this->translate('orderSALLE'); ?></a>
                        <a href="/user/pur" class="list-group-item"><?php echo $this->translate('orderBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 order-view">
                <div class="panel panel-default">
                    <div class="panel-body order-news">
                        <div class="row responsive-utilities-test hidden-on">
                            <div class="col-xs-6 col-sm-3">
                                <span class="<?php if ($this->vestut == 0) { echo 'order-activated'; } elseif ($this->vestut > 0) { echo 'order-finished'; } ?>"><?php echo $this->translate('confirming'); ?></span>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <span class="<?php if ($this->vestut == 1 || $this->vestut == 3) { echo 'order-activated'; } elseif ($this->vestut > 1) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('sign'); ?></span>
                            </div>
                            <div class="clearfix visible-xs-block"></div>
                            <div class="col-xs-6 col-sm-3">
                                <span class="<?php if ($this->vestut > 3) { echo 'order-activated'; } elseif ($this->vestut > 7) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('delivery'); ?></span>
                            </div>
                            <div class="col-xs-6 col-sm-3">
                                <span class="<?php if ($this->vestut > 3) { echo 'order-activated'; } elseif ($this->vestut > 7) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('calculate'); ?></span>
                            </div>
                        </div>

                        <div class="tab-content ">
                            <div role="tabpanel" class="tab-pane fade in active" id="confirming">
                                <div class="row">
                                    <div class="col-xs-2">
                                        <p class="text-right news-title"><?php echo $this->translate('orderNo');?></p>
                                    </div>
                                    <div class="col-xs-4">
                                        <p><?php echo $this->newE["orderNo"];?></p>
                                    </div>
                                    <div class="col-xs-2 news-title"><?php echo $this->translate('Prities');?></div>
                                    <div class="col-xs-4"></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('progressING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->plan['plan'];?></p>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('stateING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->ShowDictionaryTo($this->dic_Setting['ORDER_STATUS'], $this->userLangCode, $this->dic_Setting['ORDER_STATUS'], $this->newE["orderStatus"]); ?></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('orderVINF'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#logistics" aria-controls="logistics" role="tab" data-toggle="tab"><?php echo $this->translate('logistics'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#log" aria-controls="log" role="tab" data-toggle="tab"><?php echo $this->translate('DERIL_log'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('file'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12 orderInfo">
                                    <h3>
                                        <?php if (($this->CompProductAdmin == true || $this->CompOrderAdmin == true) && $this->orders['productStatus'] != 05): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/sale/edit?' . base64_encode($this->orders['orderID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->orders['orderNo']; ?>
                                    </h3>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('buyers'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerName'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('buyerATTN'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerContactName'];?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payCNY'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerCrnCode'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('thisATTN'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['vendorContactName'];?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('remitMD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['PAYMENT_TERM'], $this->orders['paymentTerm']); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payDD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['paymentPeriod'];?> DAYS</div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('exportMD'); ?></div>
                                        <div class="col-xs-4"><?php if($this->orders['isSelfSupport']==true){echo $this->translate('sellersEX'); }else{ echo $this->translate('siteEX');}?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payJJ'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['ORDER_QUOTATION_MODE'], $this->orders['quotationMode']); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payPrice'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['priceTerm'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payCasing'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['ORDER_PACKING_MODE'], $this->orders['packingMode']); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('packINF'); ?></div>
                                        <div class="col-xs-8"><?php echo $this->orders['packingDesc'];?></div>
                                    </div>

                                    <div class="page-header">
                                        <h3><?php echo $this->translate('payGoods'); ?></h3>
                                    </div>

                                    <div class="orderItemDiv">
                                        <?php if (is_array($this->orders['orderItemList']) && count($this->orders['orderItemList']) > 0): ?>
                                        <?php foreach ($this->orders['orderItemList'] as $k=>$goods):?>
                                        <div class="alert alert-info alert-dismissible" role="alert">
                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("productNAME"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['productName'];?></div>
                                                <div class="col-xs-2"><?php echo $this->translate("productENNAME"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['productEnName'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("packageTYPE"); ?></div>
                                                <div class="col-sm-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['PRODUCT_PACKING_TYPE'], $goods['packingType']); ?></div>
                                                <div class="col-xs-2"><?php echo $this->translate("HSCODE"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['hscode'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("brand"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['productBrand'];?></div>
                                                <div class="col-xs-2"><?php echo $this->translate("model"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['productModel'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("productMaterial"); ?></div>
                                                <div class="col-sm-8"><?php echo $goods['productMaterial'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("functionUsage"); ?></div>
                                                <div class="col-sm-8"><?php echo $goods['functionUsage'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("number"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['quantity'];?>&nbsp;&nbsp;<?php echo $this->ShowDictionaryTo("", $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $goods['pricingUnit']); ?></div>
                                                <div class="col-xs-2"><?php echo $this->translate("quantity"); ?></div>
                                                <div class="col-sm-4"><?php echo $goods['totalPackage'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("orderprice"); ?></div>
                                                <div class="col-sm-1"><?php echo $goods['unitPrice'];?></div>
                                                <div class="col-xs-1">x</div>
                                                <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                <div class="col-xs-1">=</div>
                                                <div class="col-sm-1"><?php echo $this->orders['buyerCrnCode'];?></div>
                                                <div class="col-sm-1"><?php echo $goods['totalPrice'];?></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("netWeight"); ?></div>
                                                <div class="col-sm-1"><?php echo $goods['netWeight'];?></div>
                                                <div class="col-xs-1">x</div>
                                                <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                <div class="col-xs-1">=</div>
                                                <div class="col-sm-1"><?php echo $goods['totalNetWeight'];?></div>
                                                <div class="col-sm-1">KGS</div>
                                            </div>

                                            <div class="row">
                                                <div class="col-xs-2"><?php echo $this->translate("grossWeight"); ?></div>
                                                <div class="col-sm-1"><?php echo $goods['grossWeight'];?></div>
                                                <div class="col-xs-1">x</div>
                                                <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                <div class="col-xs-1">=</div>
                                                <div class="col-sm-1"><?php echo $goods['totalGrossWeight'];?></div>
                                                <div class="col-sm-1">KGS</div>
                                            </div>

                                            <?php if ($this->orders['quotationMode'] === 'IV'): ?>
                                                <div class="row">
                                                    <div class="col-xs-2"><?php echo $this->translate("uiprice"); ?></div>
                                                    <div class="col-sm-1"><?php echo $goods['purUnitPrice'];?></div>
                                                    <div class="col-xs-1">x</div>
                                                    <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                    <div class="col-xs-1">=</div>
                                                    <div class="col-sm-1"><?php echo $goods['purCrnCode'];?></div>
                                                    <div class="col-sm-1"><?php echo $goods['totalPurPrice'];?></div>
                                                </div>
                                            <?php else: ?>
                                                <?php if ($goods['productionMode'] != '01'): ?>
                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("purchaseUnitPrice"); ?></div>
                                                        <div class="col-sm-1"><?php echo $goods['purUnitPrice'];?></div>
                                                        <div class="col-xs-1">x</div>
                                                        <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                        <div class="col-xs-1">=</div>
                                                        <div class="col-sm-1"><?php echo $goods['purCrnCode'];?></div>
                                                        <div class="col-sm-1"><?php echo $goods['totalPurPrice'];?></div>
                                                    </div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <?php endforeach; ?>
                                        <?php endif; ?>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title">
                                            <p>运输方式</p>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('moveMD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['SHIPPING_METHOD'], $this->orders['shippingMethod']); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('POCRC'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['EXPORT_POINTS'], $this->orders['clearancePlace']); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portSHIP'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->loadingPort); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portDSCG'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->loadingPort); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portDLVY'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->deliveryPort); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('mabyDATE'); ?></div>
                                        <div class="col-xs-4"><?php echo date('Y-m-d', strtotime($this->orders['deliveryDate'])); ?></div>
                                    </div>

                                    <?php if ($this->orders['needShipping'] == true || $this->orders['needTrucking'] == true): ?>
                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('isFCL'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['SHIPPING_SERVICE_TYPE'], $this->orders['shippingServiceType']); ?></div>
                                    </div>

                                        <?php if ($this->orders['shippingServiceType'] == 'FCL'): ?>
                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('infoFCL'); ?></div>
                                            <div class="col-xs-10">
                                                <div class="row" style="margin-top: 0 !important;">
                                                <?php if(!empty($this->orders['sizeQuantityMap']['20GP'])):?>
                                                    <div class="col-xs-2">
                                                        20GP*<?php echo $this->orders['sizeQuantityMap']['20GP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40GP'])):?>
                                                    <div class="col-xs-2">
                                                        40GP*<?php echo $this->orders['sizeQuantityMap']['40GP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40HP'])):?>
                                                    <div class="col-xs-2">
                                                        40HP*<?php echo $this->orders['sizeQuantityMap']['40HP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['45HP'])):?>
                                                    <div class="col-xs-2">
                                                        45HP*<?php echo $this->orders['sizeQuantityMap']['45HP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['20OT'])):?>
                                                    <div class="col-xs-2">
                                                        20OT*<?php echo $this->orders['sizeQuantityMap']['20OT'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40OT'])):?>
                                                    <div class="col-xs-2">
                                                        40OT*<?php echo $this->orders['sizeQuantityMap']['40OT'];?>
                                                    </div>
                                                <?php endif;?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif;?>

                                        <?php if (($this->orders['needShipping'] == true && $this->accountID = $this->orders['shippingClient']) || ($this->orders['needTrucking'] == true && $this->accountID = $this->orders['truckingClient'])): ?>
                                            <div class="row">
                                                <div class="col-xs-2 view-title"><?php echo $this->translate('logisticND'); ?></div>
                                                <div class="col-xs-4"><?php echo $this->orders['shippingRequest']; ?></div>
                                            </div>
                                        <?php endif;?>
                                    <?php endif;?>

                                    <?php if ($this->orders['isAssignCustomsAgency'] == true): ?>
                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('nameCHB'); ?></div>
                                            <div class="col-xs-8"><?php echo $this->orders['customsAgencyName'];?></div>
                                        </div>

                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('needCHB'); ?></div>
                                            <div class="col-xs-8"><?php echo $this->orders['customClearanceRequest']; ?></div>
                                        </div>
                                    <?php endif;?>

                                    <?php if ($this->orders['paymentTerm'] != "T/T"): ?>
                                        <?php if ($this->orders['needFinancing'] == true && $this->accountID == $this->orders['financingClient']): ?>
                                            <div class="row">
                                                <div class="col-xs-2 view-title"><?php echo $this->translate('needOTH'); ?></div>
                                                <div class="col-xs-8"><?php echo $this->orders['financingRequest']; ?></div>
                                            </div>
                                        <?php endif;?>
                                    <?php endif;?>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="logistics">
                                <div class="col-md-12">
                                    <p>物流</p>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="log">
                                <div class="col-md-12">
                                    <p>日志</p>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="profile">
                                <div class="col-md-12">
                                    <?php echo $this-> ShowWebuploader($this->orders['attachmentList'],$this->biz_Setting['PRODUCT'],$this->attach_Setting['PDPD'],"1", $this->orders['bankAcctID']);?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });
	});
</script>
</body>
</html>
