<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->translate('etradefast'); ?></title>
<meta name="description" content="">
<meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>
<body>
   <?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
    <!-- content star -->
    <div class="o_content_wrap w1200 m0a clearfix">
        <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
        <div class="o_content fr w940">
            <div class="order_table">
                <div class="o_tab">
                <ul class="order_state2 order_state3 clearfix">
                    <li><a href=<?php echo '/user/pur/view?'.base64_encode($this->orderid);?>>订单信息</a></li>
                    <li class="cur"><a href=<?php echo '/user/pur/contract?'.base64_encode($this->orderid);?>>报关物流</a></li>
                    <li><a href=<?php echo '/user/pur/track?'.base64_encode($this->orderid);?>>跟踪日志</a></li>
                    <li><a href="order_settlement.html">结算</a></li>
                    <li><a href="order_document.html">文档</a></li>
                </ul></div>
                <div class="order_info">
                    <h3>报关</h3>
                    <div class="qysearch_box qysearch_box2">
                        <ul class="bg_list">
                            <li>
                                    <label class="fl tc">
                                        委托人：<span class="bunum">121214</span>
                                    </label>
                                    <label class="fl tc">
                                        经营单位：<span class="bunum">121214</span>
                                    </label>
                                    <label class="fl tc">
                                        申报单位：<span class="bunum">121214</span>
                                    </label>
                                    <label class="fl tc">
                                        申报现场：<span class="bunum">121214</span>
                                    </label>
                                    <label class="fl tc">
                                        指运港/城市：<span class="bunum">121214</span>
                                    </label>
                                <label class="fl tc">
                                    状态：<span class="bunum">121214</span>
                                </label>
                                <label class="fl tc">
                                    <span class="bunum">PP2016102300121.PDF</span>
                                </label>
                                <label class="fl tc">
                                    生成时间：<span class="bunum">15:34 2016/08/15</span>
                                </label>

                            </li>
                        </ul>
                    </div>
                </div>
            </div>

        </div>
    </div>
    <!-- content end -->

    <!-- footer star -->
    <div class="footer_warp">
        <div class="footer ta w1200 m0a">
            <div class="f_a tc">
                <a href="javascript:;">查找兼职</a>  |
                <a href="javascript:;">查找兼职</a>  |
                <a href="javascript:;">查找兼职</a>  |
                <a href="javascript:;">查找兼职</a>  |
                <a href="javascript:;">查找兼职</a>
            </div>
            <p class="tc">©2016ENRADEFAST.INC</p>
        </div>
    </div>
    <!-- footer end -->
</body>
<script>
$(function(){
    $(".nav").movebg({width:115/*滑块的大小*/,extra:40/*额外反弹的距离*/,speed:300/*滑块移动的速度*/,rebound_speed:400/*滑块反弹的速度*/});
})
</script>
</html>
