<div id="deliveryReceiptDiv" class="layui-form">
    <div class="col-sm-12">
        <div class="alert alert-warning deliveryReceiptAlert hidden">
            <strong></strong>
        </div>
    </div>

    <div class="col-sm-12">
        <table class="layui-table" lay-skin="line">
            <colgroup>
                <col width="140">
                <col width="180">
                <col width="130">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="100">
                <col width="160">
            </colgroup>
            <thead>
            <tr>
                <th><?php echo $this->translate('productNAME'); ?></th>
                <th><?php echo $this->translate('model'); ?></th>
                <th><?php echo $this->translate('uprice'); ?></th>
                <th><?php echo $this->translate('number'); ?></th>
                <th><?php echo $this->translate('quantity'); ?></th>
                <th><?php echo $this->translate('totalNetWeight'); ?>(KGS)</th>
                <th><?php echo $this->translate('totalGrossWeight'); ?>(KGS)</th>
                <th><?php echo $this->translate('totalVolume'); ?>(CBM)</th>
                <th><?php echo $this->translate('ordertotal'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
                <tr>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->productName; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->productModel; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $this->delivery->crnCode; ?>&nbsp;
                        <label class="buyerUnitPrice_">
                            <?php echo $value->buyerUnitPrice != 0 ? number_format($value->buyerUnitPrice, 2) : '----'; ?>
                        </label>
                    </td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->deliveryQuantity; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalPackages; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalNetWeight; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalGrossWeight; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $value->totalVolume; ?></td>
                    <td style="text-align: left; vertical-align: middle;"><?php echo $this->delivery->crnCode ?>&nbsp;
                        <label class="buyerTotalAmount_">
                            <?php echo number_format($value->buyerTotalAmount, 2);?>
                        </label>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12" style="margin-top: 15px;">
        <!--质量保证函模板-->
        <?php if(is_array($this->templAttachmentList) && count($this->templAttachmentList)>0):?>
            <h4 style="color: #56859D; font-weight: bold;"><?php echo $this->translate('RECEIPT_CONFIRMATION_TEMPL').$this->translate('download');?></h4>
            <?php foreach ($this->templAttachmentList as $k=>$attach):?>
                <div class="col-sm-8">
                    <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext);?>.png') no-repeat;background-size: 20px;"></em>
                    <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'].'/doc/download.action?sid='.session_id().'&nid='.$attach->attachID.'&vid='.$attach->verifyID;?>" download>
                        <?php echo $attach->name;?>
                    </a>
                </div>
                <div class="col-sm-4">
                    <?php echo $this->translate('creatdate')." ".date('Y-m-d H:i:s',strtotime($attach->createTime));?>
                </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
</div>
