<div id="deliveryExamineDiv" class="layui-form">
    <div class="col-sm-12">
        <div class="alert alert-warning deliveryExamineAlert hidden">
            <strong></strong>
        </div>
    </div>

    <div class="col-sm-12">
        <table class="layui-table" lay-skin="line" id="deliveryEditTable">
            <colgroup>
                <col>
                <col width="140">
                <col width="120">
                <col width="80">
                <col width="160">
            </colgroup>
            <thead>
            <tr>
                <th>名称</th>
                <th>型号</th>
                <th>单价</th>
                <th>数量</th>
                <th>总价</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->delivery->deliveryItemList as $index => $value):?>
                <tr>
                    <td style="text-align: left"><?php echo $value->productName;?></td>
                    <td style="text-align: left"><?php echo $value->productModel;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode;?>&nbsp;
                        <label class="buyerUnitPrice_">
                            <?php echo $value->buyerUnitPrice != 0 ? number_format($value->buyerUnitPrice, 2) : '----'; ?>
                        </label>
                    </td>
                    <td style="text-align: left"><?php echo $value->deliveryQuantity;?></td>
                    <td style="text-align: left"><?php echo $this->delivery->crnCode?>&nbsp;
                        <label class="buyerTotalAmount_">
                            <?php echo $value->buyerTotalAmount != 0 ? number_format($value->buyerTotalAmount, 2) : '----'; ?>
                        </label>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>

    <div class="col-sm-12" style="margin-top: 15px;">
        <!--质量保证函模板-->
        <?php if(is_array($this->templAttachmentList) && count($this->templAttachmentList)>0):?>
            <h4 style="color: #56859D; font-weight: bold;"><?php echo $this->translate('quality_tmp').$this->translate('download');?></h4>
            <?php foreach ($this->templAttachmentList as $k=>$attach):?>
                <div class="col-sm-8">
                    <em class="new_upicon" style="background:url('/ky/ico/<?php echo strtolower($attach->ext);?>.png') no-repeat;background-size: 20px;"></em>
                    <a class="new_uptitle" href="<?php echo $this->seed_Setting['KyUrlex'].'/doc/download.action?sid='.session_id().'&nid='.$attach->attachID.'&vid='.$attach->verifyID;?>" download>
                        <?php echo $attach->name;?>
                    </a>
                </div>
                <div class="col-sm-4">
                    <?php echo $this->translate('creatdate')."&nbsp;&nbsp;".date('Y-m-d H:i:s',strtotime($attach->createTime));?>
                </div>
            <?php endforeach; ?>
        <?php endif;?>
    </div>
</div>
