<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/order/order.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-3 company-navigation hidden-xs">
                <div class="panel panel-default">
                    <div class="panel-heading"><?php echo $this->translate('orderIN'); ?></div>
                    <div class="list-group">
                        <a href="/user/sale" class="list-group-item"><?php echo $this->translate('orderSALLE'); ?></a>
                        <a href="/user/pur" class="list-group-item"><?php echo $this->translate('orderBUY'); ?></a>
                    </div>
                </div>
            </div>

            <div class="col-md-9 order-view">
                <?php if ($this->vestut >= 0): ?>
                <div class="panel panel-default">
                    <div class="panel-body order-news">
                        <div class="row responsive-utilities-test hidden-on">
                            <div class="col-xs-6 col-sm-3">
                                <span class="<?php if ($this->vestut == 0) { echo 'order-activated'; } elseif ($this->vestut > 0) { echo 'order-finished'; } ?>"><?php echo $this->translate('confirming'); ?></span>
                            </div>

                            <a href="#sign" aria-controls="info" role="tab" data-toggle="tab">
                                <div class="col-xs-6 col-sm-3">
                                    <span class="<?php if ($this->vestut == 1 || $this->vestut == 3) { echo 'order-activated'; } elseif ($this->vestut > 1) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('sign'); ?></span>
                                </div>
                            </a>

                            <div class="clearfix visible-xs-block"></div>

                            <a href="#delivery" aria-controls="info" role="tab" data-toggle="tab">
                                <div class="col-xs-6 col-sm-3">
                                    <span class="<?php if ($this->vestut > 3) { echo 'order-activated'; } elseif ($this->vestut > 7) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('delivery'); ?></span>
                                </div>
                            </a>

                            <a href="#calculate" aria-controls="info" role="tab" data-toggle="tab">
                                <div class="col-xs-6 col-sm-3">
                                    <span class="<?php if ($this->vestut > 3) { echo 'order-activated'; } elseif ($this->vestut > 7) { echo 'order-finished'; } else { echo 'order-no-start';} ?>"><?php echo $this->translate('calculate'); ?></span>
                                </div>
                            </a>
                        </div>

                        <div class="tab-content ">
                            <div role="tabpanel" class="tab-pane fade <?php if ($this->vestut == 0) { echo 'in active'; } ?>" id="confirming">
                                <div class="row">
                                    <div class="col-xs-2">
                                        <p class="text-right news-title"><?php echo $this->translate('orderNo');?></p>
                                    </div>
                                    <div class="col-xs-4">
                                        <p><?php echo $this->orders["orderNo"];?></p>
                                    </div>
                                    <div class="col-xs-2 news-title"><?php echo $this->translate('Prities');?></div>
                                    <div class="col-xs-4"></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('progressING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->plan['plan'];?></p>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('stateING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->ShowDictionaryTo($this->dic_Setting['ORDER_STATUS'], $this->userLangCode, $this->dic_Setting['ORDER_STATUS'], $this->orders["orderStatus"]); ?></p>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row <?php if ($this->vestut == 1 || $this->vestut == 3) { echo 'in active'; } ?>" id="sign">
                                <div class="row">
                                    <div class="col-xs-2">
                                        <p class="text-right news-title"><?php echo $this->translate('orderNo');?></p>
                                    </div>
                                    <div class="col-xs-4">
                                        <p><?php echo $this->orders["orderNo"];?></p>
                                    </div>
                                    <div class="col-xs-2 news-title"><?php echo $this->translate('Prities');?></div>
                                    <div class="col-xs-4"></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('progressING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->plan['plan'];?></p>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('files');?></p>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-12">
                                        <?php
                                        echo $this->ShowOrderContract($this->contractList, $this->accountID, 'ODTA', $this->orders['client'], $this->hasIDCertificate);
                                        ?>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 news-title">
                                        <p class="text-right"><?php echo $this->translate('stateING');?></p>
                                    </div>
                                    <div class="col-xs-8">
                                        <p><?php echo $this->ShowDictionaryTo($this->dic_Setting['ORDER_STATUS'], $this->userLangCode, $this->dic_Setting['ORDER_STATUS'], $this->orders["orderStatus"]); ?></p>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row <?php if ($this->vestut > 3) { echo 'in active'; } ?>" id="delivery">
                                <div class="col-md-12">
                                    <table class="layui-table" lay-skin="line" id="deliveryTable" lay-filter="demoEvent">
                                        <colgroup>
                                            <col width="60">
                                            <col width="140">
                                            <col width="100">
                                            <col width="160">
                                            <col>
                                            <col width="130">
                                        </colgroup>
                                        <thead>
                                        <tr style="background-color: #01AAED; color: white;">
                                            <th>批次</th>
                                            <th>收发货单编号</th>
                                            <th>批次状态</th>
                                            <th style="text-align: center">日期</th>
                                            <th style="text-align: center">摘要</th>
                                            <th style="text-align: center">操作</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php if (count($this->deliveryList) > 0): ?>
                                            <?php foreach ($this->deliveryList as $k => $v):?>
                                                <tr>
                                                    <td data-toggle="modal" data-target="#viewDelivery" data-delivery-id="<?php echo $v->deliveryID; ?>" data-delivery-status="<?php echo $v->deliveryStatus; ?>" data-delivery-no="<?php echo $v->deliveryNo; ?>">
                                                        <span class="layui-badge" style="background-color: #4CAF50;"><?php echo $k + 1; ?></span>
                                                    </td>
                                                    <td style="cursor: pointer;" data-toggle="modal" data-target="#viewDelivery" data-delivery-id="<?php echo $v->deliveryID; ?>" data-delivery-status="<?php echo $v->deliveryStatus; ?>" data-delivery-no="<?php echo $v->deliveryNo; ?>"><?php echo $v->deliveryNo; ?></td>
                                                    <td style="cursor: pointer;" data-toggle="modal" data-target="#viewDelivery" data-delivery-id="<?php echo $v->deliveryID; ?>" data-delivery-status="<?php echo $v->deliveryStatus; ?>" data-delivery-no="<?php echo $v->deliveryNo; ?>"><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['DELIVERY_STATUE'], $v->deliveryStatus); ?></td>
                                                    <td style="cursor: pointer;" data-toggle="modal" data-target="#viewDelivery" data-delivery-id="<?php echo $v->deliveryID; ?>" data-delivery-status="<?php echo $v->deliveryStatus; ?>" data-delivery-no="<?php echo $v->deliveryNo; ?>"><?php $date = date_create($v->readyDate); echo date_format($date,"Y年m月d日"); ?></td>
                                                    <td style="cursor: pointer;" data-toggle="modal" data-target="#viewDelivery" data-delivery-id="<?php echo $v->deliveryID; ?>" data-delivery-status="<?php echo $v->deliveryStatus; ?>" data-delivery-no="<?php echo $v->deliveryNo; ?>"><?php $summary = $v->summary; $replaceStr = "<br />"; echo str_replace('\n', $replaceStr, $summary); ?></td>
                                                    <td style="text-align: center">
                                                        <?php if ($v->deliveryStatus == 1 && $v->needExamine == False):?>
                                                            <a class="layui-btn layui-btn-warm deliveryDeliverViewBtn" deliveryID_="<?php echo $v->deliveryID; ?>">发货</a>
                                                        <?php elseif ($v->deliveryStatus == 2): ?>
                                                            <a class="layui-btn layui-btn-warm deliveryDeliverViewBtn" deliveryID_="<?php echo $v->deliveryID; ?>">发货</a>
                                                        <?php elseif (!$this->orders->isSelfSupport && $v->deliveryStatus == 3 && $v->vendorPaymentStatus == 3): ?>
                                                            <a href='javascript:void(0)' data-toggle="modal" data-target="#billingInfo" data-delivery-id="<?php echo $v->deliveryID; ?>" >开票资料</a>
                                                        <?php elseif (!$this->orders->isSelfSupport && $v->deliveryStatus == 4 && $v->vendorPaymentStatus == 3): ?>
                                                            <a href='javascript:void(0)' data-toggle="modal" data-target="#billingInfo" data-delivery-id="<?php echo $v->deliveryID; ?>" >开票资料</a>
                                                        <?php endif; ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr>
                                                <td colspan="6" style="height: 100px; text-align: center;">
                                                    <label><?php echo $this->translate('deliveryItemListNull'); ?></label>
                                                </td>
                                            </tr>
                                        <?php endif; ?>
                                        </tbody>
                                    </table>

                                    <div style="height: 12px"></div>
                                    <div>
                                        <button type="button" class="btn btn-default btn-block" data-toggle="modal" data-target="#addDelivery"><b><?php echo $this->translate('deliveryAdd'); ?></b></button>
                                    </div>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="calculate">
                                <div class="col-md-12">
                                    calculate
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li role="presentation" class="active">
                                <a href="#info" aria-controls="info" role="tab" data-toggle="tab"><?php echo $this->translate('orderVINF'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#logistics" aria-controls="logistics" role="tab" data-toggle="tab"><?php echo $this->translate('logistics'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#log" aria-controls="log" role="tab" data-toggle="tab"><?php echo $this->translate('DERIL_log'); ?></a>
                            </li>
                            <li role="presentation">
                                <a href="#profile" aria-controls="profile" role="tab" data-toggle="tab"><?php echo $this->translate('file'); ?></a>
                            </li>
                        </ul>

                        <div class="tab-content">
                            <div role="tabpanel" class="tab-pane active row" id="info">
                                <div class="col-md-12 orderInfo">
                                    <h3>
                                        <?php if (($this->CompProductAdmin == true || $this->CompOrderAdmin == true) && $this->orders['productStatus'] != 05): ?>
                                            <a class="profile-heading-edit pull-right btn btn-xs" data-type="base" href="<?php echo '/user/sale/edit?' . base64_encode($this->orders['orderID']); ?>">
                                                <i class="fas fa-pencil-alt" aria-hidden="true"></i><?php echo $this->translate('edit'); ?>
                                            </a>
                                        <?php endif; ?>
                                        <?php echo $this->orders['orderNo']; ?>
                                    </h3>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('buyers'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerName'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('buyerATTN'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerContactName'];?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payCNY'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['buyerCrnCode'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('thisATTN'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['vendorContactName'];?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('remitMD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['PAYMENT_TERM'], $this->orders['paymentTerm']); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payDD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['paymentPeriod'];?> DAYS</div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payJJ'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['ORDER_QUOTATION_MODE'], $this->orders['quotationMode']); ?></div>
                                        <?php if ($this->orders['orderType'] != 'DT'): ?>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('exportMD'); ?></div>
                                        <div class="col-xs-4"><?php if($this->orders['isSelfSupport']==true){echo $this->translate('sellersEX'); }else{ echo $this->translate('siteEX');}?></div>
                                        <?php endif; ?>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payPrice'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->orders['priceTerm'];?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('payCasing'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['ORDER_PACKING_MODE'], $this->orders['packingMode']); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('packINF'); ?></div>
                                        <div class="col-xs-8"><?php echo $this->orders['packingDesc'];?></div>
                                    </div>

                                    <div class="page-header">
                                        <h3><?php echo $this->translate('payGoods'); ?></h3>
                                    </div>

                                    <div class="orderItemDiv">
                                        <?php if (is_array($this->orders['orderItemList']) && count($this->orders['orderItemList']) > 0): ?>
                                            <?php foreach ($this->orders['orderItemList'] as $k=>$goods):?>
                                                <div class="alert alert-info alert-dismissible" role="alert">
                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("productNAME"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['productName'];?></div>
                                                        <div class="col-xs-2"><?php echo $this->translate("productENNAME"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['productEnName'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("packageTYPE"); ?></div>
                                                        <div class="col-sm-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['PRODUCT_PACKING_TYPE'], $goods['packingType']); ?></div>
                                                        <div class="col-xs-2"><?php echo $this->translate("HSCODE"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['hscode'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("brand"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['productBrand'];?></div>
                                                        <div class="col-xs-2"><?php echo $this->translate("model"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['productModel'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("productMaterial"); ?></div>
                                                        <div class="col-sm-8"><?php echo $goods['productMaterial'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("functionUsage"); ?></div>
                                                        <div class="col-sm-8"><?php echo $goods['functionUsage'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("number"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['quantity'];?>&nbsp;&nbsp;<?php echo $this->ShowDictionaryTo("", $this->userLangCode, $this->dic_Setting['PRODUCT_PRICING_UNIT'], $goods['pricingUnit']); ?></div>
                                                        <div class="col-xs-2"><?php echo $this->translate("quantity"); ?></div>
                                                        <div class="col-sm-4"><?php echo $goods['totalPackage'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("orderprice"); ?></div>
                                                        <div class="col-sm-1"><?php echo $goods['unitPrice'];?></div>
                                                        <div class="col-xs-1">x</div>
                                                        <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                        <div class="col-xs-1">=</div>
                                                        <div class="col-sm-1"><?php echo $this->orders['buyerCrnCode'];?></div>
                                                        <div class="col-sm-1"><?php echo $goods['totalPrice'];?></div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("netWeight"); ?></div>
                                                        <div class="col-sm-1"><?php echo $goods['netWeight'];?></div>
                                                        <div class="col-xs-1">x</div>
                                                        <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                        <div class="col-xs-1">=</div>
                                                        <div class="col-sm-1"><?php echo $goods['totalNetWeight'];?></div>
                                                        <div class="col-sm-1">KGS</div>
                                                    </div>

                                                    <div class="row">
                                                        <div class="col-xs-2"><?php echo $this->translate("grossWeight"); ?></div>
                                                        <div class="col-sm-1"><?php echo $goods['grossWeight'];?></div>
                                                        <div class="col-xs-1">x</div>
                                                        <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                        <div class="col-xs-1">=</div>
                                                        <div class="col-sm-1"><?php echo $goods['totalGrossWeight'];?></div>
                                                        <div class="col-sm-1">KGS</div>
                                                    </div>

                                                    <?php if ($this->orders['quotationMode'] === 'IV'): ?>
                                                        <div class="row">
                                                            <div class="col-xs-2"><?php echo $this->translate("uiprice"); ?></div>
                                                            <div class="col-sm-1"><?php echo $goods['purUnitPrice'];?></div>
                                                            <div class="col-xs-1">x</div>
                                                            <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                            <div class="col-xs-1">=</div>
                                                            <div class="col-sm-1"><?php echo $goods['purCrnCode'];?></div>
                                                            <div class="col-sm-1"><?php echo $goods['totalPurPrice'];?></div>
                                                        </div>
                                                    <?php else: ?>
                                                        <?php if ($goods['productionMode'] != '01'): ?>
                                                            <div class="row">
                                                                <div class="col-xs-2"><?php echo $this->translate("purchaseUnitPrice"); ?></div>
                                                                <div class="col-sm-1"><?php echo $goods['purUnitPrice'];?></div>
                                                                <div class="col-xs-1">x</div>
                                                                <div class="col-sm-1"><?php echo $goods['quantity'];?></div>
                                                                <div class="col-xs-1">=</div>
                                                                <div class="col-sm-1"><?php echo $goods['purCrnCode'];?></div>
                                                                <div class="col-sm-1"><?php echo $goods['totalPurPrice'];?></div>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                            <?php endforeach; ?>

                                            <div class="alert alert-success alert-dismissible" role="alert">
                                                <div class="row">
                                                    <div class="col-xs-2"><?php echo $this->translate("shopNet"); ?></div>
                                                    <div class="col-sm-3"><?php echo $this->orders['totalNetWeight'];?>&nbsp;<b>KGS</b></div>
                                                    <div class="col-xs-2"><?php echo $this->translate("shopGross"); ?></div>
                                                    <div class="col-sm-3"><?php echo $this->orders['totalGrossWeight'];?>&nbsp;<b>KGS</b></div>
                                                </div>

                                                <div class="row">
                                                    <div class="col-xs-2"><?php echo $this->translate("shopTotal"); ?></div>
                                                    <div class="col-sm-3"><b><?php echo $this->orders['buyerCrnCode']; ?></b>&nbsp;<?php echo $this->orders['totalAmount'];?></div>
                                                    <div class="col-xs-2"><?php echo $this->translate("shopPrities"); ?></div>
                                                    <div class="col-sm-4"></div>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>

                                    <div class="page-header">
                                        <h3><?php echo $this->translate('moveMD'); ?></h3>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('moveMD'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['SHIPPING_METHOD'], $this->orders['shippingMethod']); ?></div>
                                        <?php if ($this->orders['orderType'] != 'DT'): ?>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('POCRC'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['EXPORT_POINTS'], $this->orders['clearancePlace']); ?></div>
                                        <?php endif; ?>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portSHIP'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->loadingPort); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portDSCG'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->dischargePort); ?></div>
                                    </div>

                                    <div class="row">
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('portDLVY'); ?></div>
                                        <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->port, $this->deliveryPort); ?></div>
                                        <div class="col-xs-2 view-title"><?php echo $this->translate('mabyDATE'); ?></div>
                                        <div class="col-xs-4"><?php echo date('Y-m-d', strtotime($this->orders['deliveryDate'])); ?></div>
                                    </div>

                                    <?php if ($this->orders['needShipping'] == true || $this->orders['needTrucking'] == true): ?>
                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('isFCL'); ?></div>
                                            <div class="col-xs-4"><?php echo $this->ShowDictionaryTo(null, $this->userLangCode, $this->dic_Setting['SHIPPING_SERVICE_TYPE'], $this->orders['shippingServiceType']); ?></div>
                                        </div>

                                        <?php if ($this->orders['shippingServiceType'] == 'FCL'): ?>
                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('infoFCL'); ?></div>
                                            <div class="col-xs-10">
                                                <div class="row" style="margin-top: 0 !important;">
                                                <?php if(!empty($this->orders['sizeQuantityMap']['20GP'])):?>
                                                    <div class="col-xs-2">
                                                        20GP*<?php echo $this->orders['sizeQuantityMap']['20GP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40GP'])):?>
                                                    <div class="col-xs-2">
                                                        40GP*<?php echo $this->orders['sizeQuantityMap']['40GP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40HP'])):?>
                                                    <div class="col-xs-2">
                                                        40HP*<?php echo $this->orders['sizeQuantityMap']['40HP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['45HP'])):?>
                                                    <div class="col-xs-2">
                                                        45HP*<?php echo $this->orders['sizeQuantityMap']['45HP'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['20OT'])):?>
                                                    <div class="col-xs-2">
                                                        20OT*<?php echo $this->orders['sizeQuantityMap']['20OT'];?>
                                                    </div>
                                                <?php endif;?>

                                                <?php if(!empty($this->orders['sizeQuantityMap']['40OT'])):?>
                                                    <div class="col-xs-2">
                                                        40OT*<?php echo $this->orders['sizeQuantityMap']['40OT'];?>
                                                    </div>
                                                <?php endif;?>
                                                </div>
                                            </div>
                                        </div>
                                        <?php endif;?>

                                        <?php if (($this->orders['needShipping'] == true && $this->accountID = $this->orders['shippingClient']) || ($this->orders['needTrucking'] == true && $this->accountID = $this->orders['truckingClient'])): ?>
                                            <div class="row">
                                                <div class="col-xs-2 view-title"><?php echo $this->translate('logisticND'); ?></div>
                                                <div class="col-xs-4"><?php echo $this->orders['shippingRequest']; ?></div>
                                            </div>
                                        <?php endif;?>
                                    <?php endif;?>

                                    <?php if ($this->orders['orderType'] != 'DT'): ?>
                                        <?php if ($this->orders['isAssignCustomsAgency'] == true): ?>
                                            <div class="row">
                                                <div class="col-xs-2 view-title"><?php echo $this->translate('nameCHB'); ?></div>
                                                <div class="col-xs-8"><?php echo $this->orders['customsAgencyName'];?></div>
                                            </div>
                                        <?php endif;?>

                                        <div class="row">
                                            <div class="col-xs-2 view-title"><?php echo $this->translate('needCHB'); ?></div>
                                            <div class="col-xs-8"><?php echo $this->orders['customClearanceRequest']; ?></div>
                                        </div>
                                    <?php endif;?>

                                    <?php if ($this->orders['paymentTerm'] != "T/T"): ?>
                                        <?php if ($this->orders['needFinancing'] == true && $this->accountID == $this->orders['financingClient']): ?>
                                            <div class="row">
                                                <div class="col-xs-2 view-title"><?php echo $this->translate('needOTH'); ?></div>
                                                <div class="col-xs-8"><?php echo $this->orders['financingRequest']; ?></div>
                                            </div>
                                        <?php endif;?>
                                    <?php endif;?>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="logistics">
                                <div class="col-md-12">
                                    <p>物流</p>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="log">
                                <div class="col-md-12">
                                    <p>日志</p>
                                </div>
                            </div>

                            <div role="tabpanel" class="tab-pane row" id="profile">
                                <div class="col-md-12">
                                    <?php echo $this-> ShowWebuploader($this->orders['attachmentList'],$this->biz_Setting['PRODUCT'],$this->attach_Setting['PDPD'],"1", $this->orders['bankAcctID']);?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
		</div>
	</div>
</div>

<!--PDF预览-->
<div id="signViewDiv" style="display: none; background-color: #F6F6F6;">
    <div class="sign-button">企业签署</div>
    <div class="person-sign-button">个人签署</div>
    <div class="download-button">下载</div>
    <div class="pdfDoc" style="padding-left:50px;">
        <div id="pdfPageBox">
        </div>
    </div>
</div>

<!--非网签-->
<div id="signViewNoEContractDiv" class="layui-form" style="display: none;">
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div style="margin-top: 20px;"></div>

        <div class="layui-form-item" style="margin-left: 28px;">
            <div style="text-align: left;">
                <label class="layui-form-label" style="width: 400px;text-align: left;"><?php echo $this->translate('contractUPInfo'); ?></label>
            </div>
        </div>

        <div class="layui-form-item" style="margin-bottom: -5px;margin-top: -15px;margin-left: 28px;margin-right: 28px;">
            <div style="text-align: left;">
                <table class="layui-table" id="demo" lay-filter="test">
                    <colgroup>
                        <col width="470">
                        <col width="150">
                        <col>
                    </colgroup>
                    <thead>
                    <tr>
                        <th>合同列表</th>
                        <th>类型</th>
                        <th style="text-align:center">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="layui-form-item" style="margin-left: 28px; margin-top: 50px; width: 600px;">
            <div class="layui-form-label" style="width: 420px;">
                <div class="yyzz_box clearfix" style="width: 600px;">
                    <p class="zzname" style="width: 600px; font-weight:bold;"><?php echo $this->translate('contractUP'); ?><!--合同相关附件上传--></p>
                    <?php if ($this->vestut == 1) {
                        echo $this->ShowWebuploader($this->goods['attachmentList'], $this->biz_Setting['ORDER'], $this->attach_Setting['CRIM'], "0", null);
                    } ?>
                </div>
            </div>
        </div>


        <div style="height: 12px"></div>
        <div class="et-auth-row">
            <button class="layui-btn" id="signNoEContractConfirmBtn"><?php echo $this->translate('signing'); ?></button>
        </div>
    </div>
</div>

<!--签署-->
<div id="doSignPDFLayDiv" class="layui-form" style="display: none;">
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div style="margin-top: 20px;"></div>

        <div class="layui-form-item" style="margin-left: 28px;">
            <div style="text-align: left;">
                <label class="layui-form-label" style="width: 180px;text-align: left;"><?php echo $this->translate('signInfo'); ?></label>
            </div>
        </div>

        <div class="layui-form-item" style="margin-bottom: -5px;margin-top: 25px;margin-left: 28px;">
            <div style="text-align: left;">
                <label class="layui-form-label" style="width: 180px;text-align: left;"><b><?php echo $this->translate('signAuthType'); ?></b></label>
            </div>
        </div>

        <div class="layui-form-item" style="margin-left: 28px;">
            <div class="layui-form-label" style="width: 420px;">
                <input type="text" id="signMobileInput" name="signMobileInput" lay-verify="signMobileInput" autocomplete="off" class="layui-input" readonly="readonly">
            </div>
        </div>

        <div class="layui-form-item" style="margin-left: 28px;">
            <div class="layui-form-label" style="width: 250px;">
                <input type="text" id="signAuthCode" name="signAuthCode" lay-verify="signAuthCode" autocomplete="off" placeholder="<?php echo $this->translate('signInputAuthCode'); ?>" class="layui-input">
            </div>

            <div class="layui-form-label" style="width: 140px;">
                <button class="layui-btn layui-btn-fluid" id="signSendAuthCodeBtn"><?php echo $this->translate('signSendAuthCode'); ?></button>
            </div>
        </div>

        <div style="height: 12px"></div>
        <div class="et-auth-row">
            <button class="layui-btn layui-btn-fluid" id="singConfirmBtn" style="width: 85%;"><?php echo $this->translate('confirmed'); ?></button>
        </div>
    </div>
</div>

<!-- Modal 查看发货记录 -->
<div class="modal fade" id="viewDelivery" tabindex="-1" role="dialog" aria-labelledby="viewDeliveryLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('deliveryView'); ?> <span class="deliveryNo"></span></h4>
            </div>

            <div class="modal-body">
                <div class="layui-form-item table-responsive viewDeliveryTable">
                </div>

                <div class="row">
                    <div class="col-sm-12 deliveryItemAttachment"></div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deliveryEditBtn"><?php echo $this->translate('edit'); ?></button>
                <a id="deliveryDelBtn" style="color: #c2c2c2; cursor: pointer;"><?php echo $this->translate('deliveryDel'); ?></a>
            </div>
        </div>
    </div>
</div>

<!-- Modal 添加发货记录 -->
<div class="modal fade" id="addDelivery" tabindex="-1" role="dialog" aria-labelledby="addDeliveryLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('deliveryAdd'); ?></h4>
            </div>

            <div class="modal-body">
                <div class="layui-form-item table-responsive">
                    <table class="table layui-table" lay-skin="line">
                        <colgroup>
                            <col>
                            <col width="140">
                            <col width="100">
                            <col width="100">
                            <col width="160">
                        </colgroup>
                        <thead>
                        <tr>
                            <th>名称</th>
                            <th>型号</th>
                            <th>单价</th>
                            <th>数量</th>
                            <th>总价</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php foreach ($this->orderItemList as $index => $value):?>
                            <tr>
                                <td style="text-align: left"><?php echo $value->productName;?></td>
                                <td style="text-align: left"><?php echo $value->productModel;?></td>
                                <td style="text-align: left"><?php echo $this->deliveryCrnCode;?><label><?php echo $value->unitPrice;?></label></td>
                                <td style="text-align: left">
                                    <?php
                                    $quantity = $value->quantity - $value->deliveryQuantity <= 0  ? 0 : $value->quantity - $value->deliveryQuantity;
                                    ?>
                                    <input name="deliveryQuantity_add" class="layui-input" value="<?php echo $quantity;?>" />
                                    <input type="hidden" name="orderItemID_add" value="<?php echo $value->itemID;?>" />
                                </td>
                                <td style="text-align: left"><?php echo $this->orders['buyerCrnCode']?>&nbsp;<label id="itemID_<?php echo $value->itemID;?>"></label></td>
                            </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                </div>

                <div class="row">
                    <div class="col-sm-12">
                        <?php echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLPG'], null); ?>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deliveryAddConfirmBtn"><?php echo $this->translate('submit'); ?></button>
            </div>
        </div>
    </div>
</div>

<!-- Modal 编辑发货记录 -->
<div class="modal fade" id="editDelivery" tabindex="-1" role="dialog" aria-labelledby="editDeliveryLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"><?php echo $this->translate('edit'); ?> <span class="editDeliveryNo"></span> <?php echo $this->translate('deliveryItemQuantity'); ?></h4>
            </div>

            <div class="modal-body">
                <div class="layui-form-item table-responsive editDeliveryTable">
                </div>

                <div class="row">
                    <div class="col-sm-12 editDeliveryItemAttachment">
                        <?php echo $this->ShowWebuploader($this->attachmentList, $this->biz_Setting['ORDER'], $this->attach_Setting['DLPG'], null); ?>
                    </div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="deliveryEditConfirmBtn"><?php echo $this->translate('confirmed'); ?></button>
                <a id="editDeliveryDelBtn" style="color: #c2c2c2; cursor: pointer;"><?php echo $this->translate('deliveryDel'); ?></a>
            </div>
        </div>
    </div>
</div>

<!-- Modal 开票资料 -->
<div class="modal fade" id="billingInfo" tabindex="-1" role="dialog" aria-labelledby="billingInfoLabel">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="layui-form-item table-responsive billingInfoContent">
                </div>
            </div>
        </div>
    </div>
</div>

<!-- 物流编辑 -->
<div id="deliveryViewDiv" style="display: none;"></div>

<div id="deliveryEditViewDiv" style="display: none;"></div>

<div id="billingInfoDiv" style="display: none;"></div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- pdf -->
<script type="text/javascript" src="/ky/pdf/pdf.js"></script>
<script type="text/javascript" src="/ky/pdf/pdf.worker.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });
	});

    // *************************** PDF Sign View ********************************
    PDFJS.workerSrc = '/ky/pdf/pdf.worker.js';

    var pdfDoc = null;
    var pageNum = 1;
    var pageRendering = false;
    var pageNumPending = null;
    var scale = 1.5;

    function renderPage(num, id) {
        var canvas = document.getElementById(id);
        var ctx = canvas.getContext('2d');
        pageRendering = true;
        pdfDoc.getPage(num).then(function(page) {
            var viewport = page.getViewport(scale);
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            var renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };
            var renderTask = page.render(renderContext);

            renderTask.promise.then(function() {
                pageRendering = false;
                if (pageNumPending !== null) {
                    // New page rendering is pending
                    renderPage(pageNumPending);
                    pageNumPending = null;
                }
            });
        });

        //document.getElementById('page_num').textContent = pageNum;
    }

    function queueRenderPage(num) {
        if (pageRendering) {
            pageNumPending = num;
        } else {
            renderPage(num);
        }
    }

    function onPrevPage() {
        if (pageNum <= 1) {
            return;
        }
        pageNum--;
        queueRenderPage(pageNum);
    }
    //document.getElementById('prev').addEventListener('click', onPrevPage);

    function onNextPage() {
        if (pageNum >= pdfDoc.numPages) {
            return;
        }
        pageNum++;
        queueRenderPage(pageNum);
    }
    //document.getElementById('next').addEventListener('click', onNextPage);

    function initPdfView(pdfUrl, obj) {
        $("#pdfPageBox").html("");
        PDFJS.getDocument(pdfUrl).then(function(pdfDoc_) {
            pdfDoc = pdfDoc_;
            //document.getElementById('page_count').textContent = pdfDoc.numPages;
            for (var i=1;i<=pdfDoc.numPages;i++){
                var canvasDiv = $("<div style=\"padding-top:10px;padding-bottom:10px;\"></div>");
                var pageNum = $("<div style=\"background-color: #999999;position:absolute;float: left;height:30px;width:60px;text-align: center;line-height: 30px;color:#ffffff;opacity: 0.6;\">"+i+"/"+pdfDoc.numPages+"</div>");
                var canvas = $("<canvas></canvas>").attr("id", "the-canvas_"+i);
                canvasDiv.append(pageNum);
                canvasDiv.append(canvas);
                $("#pdfPageBox").append(canvasDiv);
                renderPage(i, "the-canvas_"+i);
            }
        });

        var signTitle = "<?php echo $this->translate('signTitle');?>";
        layer.open({
            type: 1,	//Page层类型
            area: ['1150px', '100%'],
            title: signTitle,
            shadeClose: true,
            shade: 0.6,	//遮罩透明度
            // anim: 1,	//0-6的动画形式，-1不开启
            scrollbar: false,
            content: $("#signViewDiv")
        });

        $(".download-button").attr("contractID_", obj.id);

        if ($("#isESigned_" + obj.id).val() == 1) {
            $(".sign-button").hide();
        } else {
            $(".sign-button").show().attr("contractID_", obj.id);
        }

        if ($("#isPSigned_" + obj.id).val() == 1) {
            $(".person-sign-button").hide();
        } else {
            $(".person-sign-button").show().attr("contractID_", obj.id);
        }
    }

    //document.getElementById('prev').addEventListener('click', onPrevPage);

    $(".download-button").bind("click",function(){
        var contractID_ = $(this).attr("contractID_");
        window.location.href = $("#contractAttachUrl_" + contractID_).val();
    });

    // ********************   获取验证手机号码 Start  *************************************
    $(".sign-button").bind("click",function(){
        var getSignMobile = '/user/pur/getsignmobile';
        $.ajax({
            type: "POST",
            url: getSignMobile,
            data: {

            },
            dataType: "json",
            success: function (data) {
                var mobileStr = "<?php echo $this->translate('mobile_phone');?>";
                $("#signMobileInput").val(mobileStr + " " +data);
            }
        });

        var signTitle = "<?php echo $this->translate('signTitle');?>";
        layer.open({
            type: 1,
            title: signTitle,
            shadeClose: true,
            shade: 0.2,
            area: ['500px', '420px'],
            content: $('#doSignPDFLayDiv')
        });
    });

    $(".person-sign-button").bind("click",function(){
        var getSignMobile = '/user/pur/getpersonsignmobile';
        $.ajax({
            type: "POST",
            url: getSignMobile,
            data: {

            },
            dataType: "json",
            success: function (data) {
                var mobileStr = "<?php echo $this->translate('mobile_phone');?>";
                $("#signMobileInput").val(mobileStr + " " +data);
            }
        });

        var signTitle = "<?php echo $this->translate('signTitle');?>";
        layer.open({
            type: 1,
            title: signTitle,
            shadeClose: true,
            shade: 0.2,
            area: ['500px', '420px'],
            content: $('#doSignPDFLayDiv')
        });
        $("#signSendAuthCodeBtn").attr("personSend", "true");
        $("#singConfirmBtn").attr("personSend", "true");
    });
    // ********************   End  *************************************

    // ********************   获取短信验证码 Start  *************************************
    $("#signSendAuthCodeBtn").click(function () {
        var sendSignAuthCode = '/user/pur/sendsignauthcode';
        if ($(this).attr("personSend") == "true") {
            sendSignAuthCode = '/user/pur/sendpersonsignauthcode';
        }

        $.ajax({
            type: "POST",
            url: sendSignAuthCode,
            data: {

            },
            dataType: "json",
            success: function (data) {
                var sendingStr = "<?php echo $this->translate('signAuthCodeSending');?>";
                $("#signSendAuthCodeBtn").text(sendingStr);
                sendSignAuthCodeCountDown();
            }
        });
    });

    var countdown=120;
    function sendSignAuthCodeCountDown() {
        var obj = $("#signSendAuthCodeBtn");
        settime(obj);
    }

    function settime(obj) { //发送验证码倒计时
        if (countdown == 0) {
            obj.attr('disabled',false);
            //obj.removeattr("disabled");
            obj.removeClass('layui-btn-disabled');
            var btnStr = "<?php echo $this->translate('signSendAuthCode'); ?>";
            obj.text(btnStr);
            countdown = 120;
            return;
        } else {
            console.log(countdown);
            obj.attr('disabled',true);
            obj.addClass('layui-btn-disabled');
            var btnStr = "<?php echo $this->translate('signAuthCodeSending'); ?>";
            obj.text(btnStr + "(" + countdown + ")");
            countdown--;
        }
        setTimeout(function() {
                settime(obj) }
            ,1000)
    }
    // ********************   获取短信验证码 End  *************************************



    // ********************   获取短信验证码 Start  *************************************
    $("#singConfirmBtn").click(function () {
        var doSignPDF = '/user/pur/dosignpdf';
        var contractID = $(".sign-button").attr("contractID_");
        if ($(this).attr("personSend") == "true") {
            doSignPDF = '/user/pur/dopersonsignpdf';
            contractID = $(".person-sign-button").attr("contractID_");
        }

        $.ajax({
            type: "POST",
            url: doSignPDF,
            data: {
                contractID: contractID,
                signAuthCode: $("#signAuthCode").val()
            },
            dataType: "json",
            success: function (data) {
                var signMsg = "<?php echo $this->translate('signFail');?>";
                if (data != null && data != '') {
                    signMsg = "<?php echo $this->translate('signSuccess');?>";
                    layer.msg(signMsg);
                    window.location.reload();
                } else {
                    $("#signAuthCode").val('');
                    layer.msg(signMsg);
                }
            }
        });
    });
    // ********************   获取短信验证码 End  *************************************


    // ********************   显示非网签上传合同层 Start  *************************************
    function initSignViewNoEContract(obj) {

        var signTitle = "<?php echo $this->translate('signTitle');?>";
        layer.open({
            type: 1,	//Page层类型
            area: ['800px', '550px'],
            title: signTitle,
            // shadeClose: true,
            shade: 0.6,	//遮罩透明度
            // anim: 1,	//0-6的动画形式，-1不开启
            scrollbar: false,
            content: $("#signViewNoEContractDiv")
        });


        $("#signViewNoEContractDiv tr:not(:first)").empty();
        //获取最后一行的data-id(标识行)
        var rowIndex = $("#signViewNoEContractDiv tr:last").attr("data-row");
        if (rowIndex == "" || rowIndex == null) {
            rowIndex = parseInt(1);
        } else {
            rowIndex = parseInt(rowIndex) + 1;
        }

        var htmlList = '<tr data-row=' + rowIndex + '>';

        htmlList += '<td><a href="#" id="" onclick="doDownload(\''+obj.id+'\')">' + $("#contractName_" + obj.id).val() + '</a></td>';

        htmlList += '<td>' + $("#ext_" + obj.id).val() + '</td>';

        htmlList += '<td><a href="#" id="" onclick="doDownload(\''+obj.id+'\')" class="order_contract_sign fr">下载</a></td>';

        htmlList += '</td></tr>';
        //在行最后添加数据
        $("#signViewNoEContractDiv tr:last").after(htmlList);

        $("#signNoEContractConfirmBtn").attr("contractID_", obj.id);
        // alert(obj.id);
        // alert($("#contractName_" + obj.id).val());
    }

    function doDownload(objID) {
        window.location.href = $("#contractAttachUrl_" + objID).val();
    }
    // ********************   显示非网签上传合同层 End  *************************************


    // ********************   非网签签署合同提交按钮 Start  *************************************
    $("#signNoEContractConfirmBtn").click(function () {
        var contractID = $(this).attr("contractID_");

        var nidArr = "";
        var nid = document.getElementsByName("attachNid[]");
        for (var i = 0, j = nid.length; i < j; i++) {
            nidArr += nid[i].value + "|";
        }
        var nameArr = "";
        var name = document.getElementsByName("attachName[]");
        for (var i = 0, j = name.length; i < j; i++) {
            nameArr += name[i].value + "|";
        }
        var sizeArr = "";
        var size = document.getElementsByName("attachSize[]");
        for (var i = 0, j = size.length; i < j; i++) {
            sizeArr += size[i].value + "|";
        }
        var attachTypeArr = "";
        var attachType = document.getElementsByName("attachType[]");
        for (var i = 0, j = attachType.length; i < j; i++) {
            attachTypeArr += attachType[i].value + "|";
        }

        $.ajax({
            type: "POST",
            url: '<?php echo $this->BaseUrl();?>/sale/agree',
            data: {
                contractID: contractID,
                name: nameArr,
                nid: nidArr,
                size: sizeArr,
                attachType: attachTypeArr
            },
            dataType: "json",
            success: function (data) {
                if (data === '1') {
                    document.location.reload();
                } else {
                    alert(data + 'failed,please try again!');
                }
            }
        });
    });
    // ********************   非网签签署合同提交按钮 End  *************************************


    // ********************   物流详情 Start  *************************************
    var $deliveryEditBtn = $("#deliveryEditBtn"),
        $deliveryDelBtn = $("#deliveryDelBtn"),
        $viewDelivery = $("#viewDelivery"),
        $editDelivery = $("#editDelivery");
    $viewDelivery.on('show.bs.modal', function (e) {
        var triggered = $(e.relatedTarget),
            deliveryID = triggered.data("delivery-id"),
            deliveryStatus = triggered.data("delivery-status"),
            deliveryNo = triggered.data("delivery-no"),
            $viewDeliveryTable = $(".viewDeliveryTable"),
            $deliveryItemAttachment = $(".deliveryItemAttachment");

        if (deliveryStatus === 1) {
            $deliveryDelBtn.show();
            $deliveryDelBtn.attr("data-delivery-id", deliveryID);

            $deliveryEditBtn.show();
            $deliveryEditBtn.attr("data-delivery-id", deliveryID);
            $deliveryEditBtn.attr("data-delivery-no", deliveryNo);
        } else {
            $deliveryDelBtn.hide();
            $deliveryEditBtn.hide();
        }

        $(".deliveryNo").html(deliveryNo);
        var deliveryUrl = "/user/sale/delivery-ajax";
        $.ajax({
            type: "POST",
            url: deliveryUrl,
            data: {
                deliveryID: deliveryID
            },
            dataType: "json",
            success: function (data) {
                var attachUrl = '<?php echo $this->seed_Setting['KyUrlex'] ?>';
                $viewDeliveryTable.html("");
                var content = '';
                content += '<table class="layui-table" lay-skin="line" id="deliveryEditTable">'
                    + '<colgroup>'
                    + ' <col>'
                    + ' <col width="140">'
                    + ' <col width="120">'
                    + ' <col width="80">'
                    + ' <col width="160">'
                    + '</colgroup>'
                    + '<thead>'
                    + '<tr>'
                    + ' <th>名称</th>'
                    + ' <th>型号</th>'
                    + ' <th>单价</th>'
                    + ' <th>数量</th>'
                    + ' <th>总价</th>'
                    + '</thead>'
                    + '<tbody>';

                $.each(data.delivery.deliveryItemList, function (index, deliveryItem) {
                    content += '<tr>'
                        + '<td style="text-align: left">' + deliveryItem.productName + '</td>'
                        + '<td style="text-align: left">' + deliveryItem.productModel + '</td>'
                        + '<td style="text-align: left">' + data.delivery.crnCode + '&nbsp;' + formatCurrency(deliveryItem.buyerUnitPrice, 2) + '</td>'
                        + '<td style="text-align: left">' + deliveryItem.deliveryQuantity + '</td>'
                        + '<td style="text-align: left">' + data.delivery.crnCode + '&nbsp;' + formatCurrency(deliveryItem.buyerTotalAmount, 2) + '</td>'
                        + '</tr>';
                });

                content += '</tbody>'
                    + '</table>';

                $viewDeliveryTable.html(content);

                // 附件
                $deliveryItemAttachment.html("");
                var attachmentContent = '';

                // 备货
                if (data.prepareAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.prepareAttachmentList, '<?php echo $this->translate('PREPARE_GOODS').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                // 验货
                if (data.examineAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.examineAttachmentList, '<?php echo $this->translate('EXAMINE_GOODS').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                // 质量保证函正本
                if (data.qualityAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.qualityAttachmentList, '<?php echo $this->translate('QUALITY_AGREE_FORMAL').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                // 发货
                if (data.deliverAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.deliverAttachmentList, '<?php echo $this->translate('DELIVER_GOODS').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                // 收货
                if (data.receiptAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.receiptAttachmentList, '<?php echo $this->translate('RECEIPT_GOODS').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                // 收货确认函正本
                if (data.receiptConfirmationAttachmentList.length > 0) {
                    attachmentContent += genAttachContent(data.receiptConfirmationAttachmentList, '<?php echo $this->translate('RECEIPT_CONFIRMATION_FORMAL').$this->translate('download'); ?>', attachmentContent, attachUrl);
                }

                $deliveryItemAttachment.html(attachmentContent);
            }
        });
    });

    function genAttachContent(data, title, attachmentContent, attachUrl) {
        attachmentContent += '<div class="page-header">'
            + '<h4>' + title + '</h4>'
            + '</div>';
        $.each(data, function (index, attach) {
            var ext = attach.ext !== undefined ? attach.ext.toLowerCase(): '';
            attachmentContent += '<div class="col-xs-8">'
                + '<em class="new_upicon" style="background:url(\'/ky/ico/' + ext + '.png\') no-repeat;background-size: 20px;"></em>'
                + '<a href="' + attachUrl + '/doc/download.action?sid=<?php echo session_id(); ?>&nid=' + attach.attachID + '&vid=' + attach.verifyID + '" download>'
                + '<p class="new_uptitle">' + attach.name + '</p>'
                + '</a>'
                + '</div>'
                + '<div class="col-xs-4">'
                + '<?php echo $this->translate("creatdate") ?>&nbsp;' + new Date(attach.createTime).format("yyyy-MM-dd hh:mm:ss")
                + '</div>';
        });
        return attachmentContent;
    }

    $deliveryDelBtn.click(function () {
        var deliveryID = $(this).attr("data-delivery-id"),
            delDelivery = '/user/sale/del-delivery-ajax';
        layer.msg('确定删除发货单？', {
            time: 0 //不自动关闭
            ,btn: ['确定', '取消']
            ,yes: function(index){
                $.ajax({
                    type: "POST",
                    url: delDelivery,
                    data: {
                        deliveryID: deliveryID
                    },
                    dataType: "json",
                    success: function (data) {
                        if (data === 1) {
                            document.location.reload();
                        } else {
                            alert(data + ' failed, please try again!');
                        }
                    }
                });
            }
        });
    });

    // 查看备货单页面点击编辑按钮
    $deliveryEditBtn.click(function () {
        $editDelivery.attr('data-delivery-id', $(this).attr("data-delivery-id"));
        $editDelivery.attr('data-delivery-no', $(this).attr("data-delivery-no"));

        $viewDelivery.modal('hide');
        setTimeout(function () {
            $editDelivery.modal('show')
        }, 400);
    });

    // 呈现备货单编辑页面
    $editDelivery.on('show.bs.modal', function (e) {
        var deliveryID = $editDelivery.attr("data-delivery-id"),
            deliveryNo = $editDelivery.attr("data-delivery-no"),
            $editDeliveryTable = $(".editDeliveryTable"),
            $attachView = $(".editDeliveryItemAttachment").find(".img-view");

        $(".editDeliveryNo").html(deliveryNo);
        $attachView.html("");

        var deliveryUrl = "/user/sale/edit-delivery-ajax";
        $.ajax({
            type: "POST",
            url: deliveryUrl,
            data: {
                deliveryID: deliveryID
            },
            dataType: "json",
            success: function (data) {
                var content = '',
                    attachmentContent = '',
                    attachUrl = '<?php echo $this->seed_Setting['KyUrlex'] ?>';
                if (data.delivery === null) {

                    content += '暂无数据';
                } else {
                    content += '<table class="layui-table" lay-skin="line" id="deliveryEditTable">'
                        + '<colgroup>'
                        + ' <col>'
                        + ' <col width="140">'
                        + ' <col width="120">'
                        + ' <col width="80">'
                        + ' <col width="160">'
                        + '</colgroup>'
                        + '<thead>'
                        + '<tr>'
                        + ' <th>名称</th>'
                        + ' <th>型号</th>'
                        + ' <th>单价</th>'
                        + ' <th>数量</th>'
                        + ' <th>总价</th>'
                        + '</thead>'
                        + '<tbody>';

                    $.each(data.delivery.deliveryItemList, function (index, deliveryItem) {
                        content += '<tr>'
                            + '<td style="text-align: left">' + deliveryItem.productName + '</td>'
                            + '<td style="text-align: left">' + deliveryItem.productModel + '</td>'
                            + '<td style="text-align: left">' + data.delivery.crnCode + '&nbsp;<label>' + formatCurrency(deliveryItem.buyerUnitPrice, 2) + '</label></td>'
                            + '<td style="text-align: left">'
                            + '<input name="deliveryQuantity_edit" class="layui-input" value="' + deliveryItem.deliveryQuantity + '" />'
                            + '<input type="hidden" name="orderItemID_edit" value="' + deliveryItem.itemID + '" />'
                            + '</td>'
                            + '<td style="text-align: left">' + data.delivery.crnCode + '&nbsp;<label id="itemID_' + deliveryItem.itemID + '">' + formatCurrency(deliveryItem.buyerTotalAmount, 2) + '</label></td>'
                            + '</tr>';
                    });

                    content += '</tbody>'
                        + '</table>';

                    $.each(data.prepareAttachmentList, function (index, attach) {
                        var ext = attach.ext !== undefined ? attach.ext.toLowerCase(): '';
                        if (ext === "DOCX" || ext === "WPS") {
                            ext = "doc";
                        }
                        if (ext === "XLSX") {
                            ext = "xls";
                        }
                        if (ext === "PPTX") {
                            ext = "ppt";
                        }
                        attachmentContent += '<li>';
                        if (ext === "jpeg" || ext === "png" || ext === "jpg" || ext === "gif" || ext === "GIF" || ext === "JPG" || ext === "PNG" || ext === "JPEG") {
                            attachmentContent += '<img width="125px" height="125px"  layer-src="' + attachUrl + '/doc/download.action?sid=<?php echo session_id(); ?>&nid=' + attach.attachID + '&vid=' + attach.verifyID + '" src="' + attachUrl + '/doc/download.action?sid=<?php echo session_id(); ?>&nid=' + attach.attachID + '&vid=' + attach.verifyID + '&size=MIDDLE" name="' + attach.name + '">'
                                + '<span class="del_to">' + attach.name + '<br><a onclick="view_pic(this)">查看</a>|<a onclick="delete_pic(this)">删除</a></span>';
                        } else {
                            attachmentContent += '<img width="125px" height="125px" src="/ky/ico/' + ext + '.png" alt=' + attach.attachType + ' />'
                                + '<span class="del_to">' + attach.name + '<br>'
                                + '<a href="' + attachUrl + '/doc/download.action?sid=<?php echo session_id(); ?>&nid=' + attach.attachID + '&vid=' + attach.verifyID + '" download>下载</a>'
                                + '<a onclick="delete_pic(this)">删除</a>'
                                + '</span>';
                        }

                        attachmentContent += '<input type="hidden" name="attachNid[]" value="' + attach.attachID + '" />'
                            + '<input type="hidden" name="attachType[]" value="' + attach.attachType + '" />'
                            + '<input type="hidden" name="attachName[]" value="' + attach.name + '" />'
                            + '<input type="hidden" name="attachSize[]" value="' + attach.size + '" />';
                        attachmentContent += '</li>';
                    });
                }

                $editDeliveryTable.html(content);
                $attachView.html(attachmentContent);

                $("input[name='deliveryQuantity_edit']").keyup(function () {
                    var unitPrice = $(this).parent().prev().find("label").html();
                    var quantity = $(this).val();
                    if (isNaN(quantity)) {
                        quantity = 0;
                    }
                    var totalAmount = arithMul(unitPrice, quantity);

                    totalAmount = formatCurrency(totalAmount, 2);
                    $(this).parent().next().find("label").html(totalAmount);
                });

                $("#deliveryEditConfirmBtn").click(function () {
                    var nidArr = "";
                    var nid = $("#editDelivery input[name='attachNid[]']");
                    for (var i = 0, j = nid.length; i < j; i++) {
                        nidArr += nid[i].value + "|";
                    }
                    var nameArr = "";
                    var name = $("#editDelivery input[name='attachName[]']");
                    for (var i = 0, j = name.length; i < j; i++) {
                        nameArr += name[i].value + "|";
                    }
                    var sizeArr = "";
                    var size = $("#editDelivery input[name='attachSize[]']");
                    for (var i = 0, j = size.length; i < j; i++) {
                        sizeArr += size[i].value + "|";
                    }
                    var attachTypeArr = "";
                    var attachType = $("#editDelivery input[name='attachType[]']");
                    for (var i = 0, j = attachType.length; i < j; i++) {
                        attachTypeArr += attachType[i].value + "|";
                    }
                    // var orderItemID_add = "";
                    var orderItemIDArr = "";
                    var orderItemID_add = $("#editDelivery input[name='orderItemID_edit']");
                    for (var i = 0, j = orderItemID_add.length; i < j; i++) {
                        orderItemIDArr += orderItemID_add[i].value + "|";
                    }

                    var deliveryQuantityArr = "";
                    var deliveryQuantity_add = $("#editDelivery input[name='deliveryQuantity_edit']");
                    for (var i = 0, j = deliveryQuantity_add.length; i < j; i++) {
                        deliveryQuantityArr += deliveryQuantity_add[i].value + "|";
                    }

                    var editDelivery = '/user/sale/editdeliverysave';
                    $.ajax({
                        type: "POST",
                        url: editDelivery,
                        data: {
                            deliveryID: deliveryID,
                            name: nameArr,
                            nid: nidArr,
                            size: sizeArr,
                            attachType: attachTypeArr,
                            orderItemID: orderItemIDArr,
                            deliveryQuantity: deliveryQuantityArr
                        },
                        dataType: "json",
                        success: function (data) {
                            if (data === 1) {
                                document.location.reload();
                            } else {
                                alert(data + 'failed,please try again!');
                            }
                        }
                    });
                });

                $("#editDeliveryDelBtn").click(function () {
                    var delDelivery = '/user/sale/del-delivery-ajax';
                    layer.msg('确定删除发货单？', {
                        time: 0, //不自动关闭
                        btn: ['确定', '取消'],
                        zIndex: 99991014,
                        yes: function(index){
                            $.ajax({
                                type: "POST",
                                url: delDelivery,
                                data: {
                                    deliveryID: deliveryID
                                },
                                dataType: "json",
                                success: function (data) {
                                    if (data === 1) {
                                        document.location.reload();
                                    } else {
                                        alert(data + 'failed,please try again!');
                                    }
                                }
                            });
                        }
                    });
                });
            }
        });
    });

    /* 添加发货记录 */
    $("#deliveryAddConfirmBtn").click(function () {
        var auth_error = $('#deliveryAddDiv').find('.et-auth-error');

        var nidArr = "";
        var nid = $("#addDelivery input[name='attachNid[]']");
        for (var i = 0, j = nid.length; i < j; i++) {
            nidArr += nid[i].value + "|";
        }
        var nameArr = "";
        var name = $("#addDelivery input[name='attachName[]']");
        for (var i = 0, j = name.length; i < j; i++) {
            nameArr += name[i].value + "|";
        }
        var sizeArr = "";
        var size = $("#addDelivery input[name='attachSize[]']");
        for (var i = 0, j = size.length; i < j; i++) {
            sizeArr += size[i].value + "|";
        }
        var attachTypeArr = "";
        var attachType = $("#addDelivery input[name='attachType[]']");
        for (var i = 0, j = attachType.length; i < j; i++) {
            attachTypeArr += attachType[i].value + "|";
        }
        // var orderItemID_add = "";
        var orderItemIDArr = "";
        var orderItemID_add = $("#addDelivery input[name='orderItemID_add']");
        console.log(orderItemID_add.length);
        for (var i = 0, j = orderItemID_add.length; i < j; i++) {
            orderItemIDArr += orderItemID_add[i].value + "|";
        }

        var deliveryQuantityArr = "";
        var deliveryQuantity_add = $("#addDelivery input[name='deliveryQuantity_add']");
        for (var i = 0, j = deliveryQuantity_add.length; i < j; i++) {
            deliveryQuantityArr += deliveryQuantity_add[i].value + "|";
        }

        var doPrepareGoods = '/user/sale/preparesave';
        $.ajax({
            type: "POST",
            url: doPrepareGoods,
            data: {
                orderID: '<?php echo $this->orders['orderID'];?>',
                name: nameArr,
                nid: nidArr,
                size: sizeArr,
                attachType: attachTypeArr,
                orderItemID: orderItemIDArr,
                deliveryQuantity: deliveryQuantityArr
            },
            dataType: "json",
            success: function (data) {
                if (data === 1) {
                    document.location.reload();
                } else {
                    alert(data + 'failed,please try again!');
                }
            }
        });
    });

    /* 添加发货记录 */
    $("input[name='deliveryQuantity_add']").keyup(function () {
        var unitPrice = $(this).parent().prev().find("label").html();
        var quantity = $(this).val();
        if (isNaN(quantity)) {
            quantity = 0;
        }
        var totalAmount = arithMul(unitPrice, quantity);

        totalAmount = formatCurrency(totalAmount, 2);
        $(this).parent().next().find("label").html(totalAmount);
    });

    /* 发货详情页 */
    $(".deliveryDeliverViewBtn").click(function () {
        var deliveryID = $(this).attr("deliveryID_");
        $("#deliveryViewDiv").html("").load("<?php echo $this->BaseUrl();?>/sale/deliver", {
            deliveryID: deliveryID
        }, function () {
            layer.closeAll();
            layer.open({
                type: 1,
                title: false,
                area: ['750px', '97%'],
                skin: 'layui-layer-rim',
                scrollbar: false,
                shade: 0.5,
                content: $("#deliveryViewDiv")
            });

            /* 发货 */
            $("#deliveryDeliverGoodsBtn").click(function () {
                var auth_error = $('#deliveryDeliverDiv').find('.et-auth-error');

                var nidArr = "";
                var nid = document.getElementsByName("attachNid[]");
                for (var i = 0, j = nid.length; i < j; i++) {
                    nidArr += nid[i].value + "|";
                }
                var nameArr = "";
                var name = document.getElementsByName("attachName[]");
                for (var i = 0, j = name.length; i < j; i++) {
                    nameArr += name[i].value + "|";
                }
                var sizeArr = "";
                var size = document.getElementsByName("attachSize[]");
                for (var i = 0, j = size.length; i < j; i++) {
                    sizeArr += size[i].value + "|";
                }
                var attachTypeArr = "";
                var attachType = document.getElementsByName("attachType[]");
                for (var i = 0, j = attachType.length; i < j; i++) {
                    attachTypeArr += attachType[i].value + "|";
                }

                var deliverGoods = '/user/sale/deliversave';
                $.ajax({
                    type: "POST",
                    url: deliverGoods,
                    data: {
                        deliveryID: deliveryID,
                        name: nameArr,
                        nid: nidArr,
                        size: sizeArr,
                        attachType: attachTypeArr
                    },
                    dataType: "json",
                    success: function (data) {
                        if (data === '1') {
                            document.location.reload();
                        } else {
                            alert(data + 'failed,please try again!');
                        }
                    }
                });
            });
        });
    });


    // ********************   物流详情 End  *************************************

    $(".signTopBtn").click(function () {
        var executionStatus = <?php echo $this->vestut;?>;
        $(".signTopDiv").show();
        $(".deliveryTopDiv").hide();
        $(".paymentTopDiv").hide();
    });

    $(".deliveryTopBtn").click(function () {
        var executionStatus = <?php echo $this->vestut;?>;
        if (executionStatus >= 7) {
            $(".signTopDiv").hide();
            $(".deliveryTopDiv").show();
            $(".paymentTopDiv").hide();
        }

    });

    $(".paymentTopBtn").click(function () {
        var executionStatus = <?php echo $this->vestut;?>;
        if (executionStatus >= 7) {
            $(".signTopDiv").hide();
            $(".deliveryTopDiv").hide();
            $(".paymentTopDiv").show().load('<?php echo $this->BaseUrl();?>/sale/trading', {'orderID': $("#orderID").val()});
        }
    });

    // ********************   开票资料 Start  *************************************
    $("#billingInfo").on('show.bs.modal', function (e) {
        console.log("in");
        var triggered = $(e.relatedTarget),
            deliveryID = triggered.data("delivery-id");

        $(".billingInfoContent").html("").load("/user/sale/deliverbillinginfo", {
            deliveryID: deliveryID
        }, function () {
            layui.use('form', function() {
                var form = layui.form;
                form.render();
            });

            layui.use('element', function(){
                var element = layui.element;
                element.render();
            });

            $(".billingExpressEdit").click(function () {
                $(".expressShow").hide();
                $(".expressEdit").show();
            });
            $(".billingExpressEditSave").click(function () {
                console.log("in");
                var deliveryID = $(this).attr("deliveryID_");
                var supplierID = $(this).attr("supplierID_");
                var expressType = $("#expressType").val();
                var expressName = $("#expressType").find("option:selected").text();
                var expressNo = $("#expressNo").val();

                var editExpressNo = '/user/sale/editexpresssave';
                $.ajax({
                    type: "POST",
                    url: editExpressNo,
                    data: {
                        deliveryID: deliveryID,
                        supplierID: supplierID,
                        expressType: expressType,
                        expressNo: expressNo
                    },
                    dataType: "json",
                    success: function (data) {
                        $(".expressName_").html(expressName);
                        $(".expressNo_").html(expressNo);

                        $("#expressType").val(expressType);
                        $("#expressNo").val(expressNo);

                        $(".expressShow").show();
                        $(".expressEdit").hide();
                    }
                });
            });

            $(".genBillInfoBtn").click(function () {
                var deliveryID = $(this).attr("deliveryID_");

                var supplierIDArray = "";
                var supplierID = document.getElementsByName("supplierID");
                for (var i = 0, j = supplierID.length; i < j; i++) {
                    supplierIDArray += supplierID[i].value + "|";
                }

                var bankAcctIDArray = "";
                var bankAcctID = document.getElementsByName("bankAcctID");
                for (var i = 0, j = bankAcctID.length; i < j; i++) {
                    bankAcctIDArray += bankAcctID[i].value + "|";
                }

                $(".genBillInfoBtn").attr("disabled", true);
                var genBillingInfo = '/user/sale/genbillinginfo';
                $.ajax({
                    type: "POST",
                    url: genBillingInfo,
                    data: {
                        deliveryID: deliveryID,
                        supplierID: supplierIDArray,
                        bankAcctID: bankAcctIDArray
                    },
                    dataType: "json",
                    success: function (data) {
                        layer.closeAll();

                        setTimeout(function () {
                            $("#company-auth").trigger("click");
                        }, 500);

                        $(".genBillInfoBtn").attr("disabled", false);
                    }
                });
            });
        });
    });
    // ********************   开票资料 End  *************************************
</script>
</body>
</html>
