<table class="table table-hovers">
    <thead>
    <tr>
        <th><?php echo $this->translate('productNAME'); ?></th>
        <th><?php echo $this->translate('brand'); ?></th>
        <th><?php echo $this->translate('model'); ?></th>
        <th><?php echo $this->translate('supplierName'); ?></th>
        <th><?php echo $this->translate('state'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->productList) > 0): ?>
        <?php foreach ($this->productList as $product): ?>
            <tr style="cursor: pointer;" data-type="<?php echo $this->dataType; ?>" data-id="<?php echo $product->productID; ?>">
                <td><?php echo $product->productName; ?></td>
                <td><?php echo $product->productBrand; ?></td>
                <td>
                    <?php echo $product->productModel ?>
                </td>
                <td>
                    <?php echo $product->supplierName ?>
                </td>
                <td>
                    <?php echo $this->ShowDictionaryTo($this->dic_Setting["PRODUCT_STATUS"], $this->userLangCode, $this->dic_Setting["PRODUCT_STATUS"], $product->productStatus); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
    <tr>
        <td colspan="5"><?php echo $this->translate('noData'); ?></td>
    </tr>
    <?php endif;?>
    <tr>
        <td colspan="5" class="text-right"><a href="<?php echo $this->listUrl; ?>">更 多 >></a></td>
    </tr>
    </tbody>
</table>
<script src="/ky/js/base64.js"></script>
<script>
    // 行点击
    $("tr").slice(1, -1).click(function () {
        var dataID = $(this).attr("data-id");
        if (dataID !== undefined && dataID !== '') {
            var base = new Base64();
            var resultEnCode = base.encode($(this).attr("data-id"));
            if ($(this).attr("data-type") === 'goods') {
                window.location.href = "/user/goods/view?" + resultEnCode;
            } else if ($(this).attr("data-type") === 'purchase') {
                window.location.href = "/user/purchase/view?" + resultEnCode;
            }
        }
    });
</script>
