<table class="table table-bordered listSaleOrder">
    <thead>
    <tr>
        <th><?php echo $this->translate('orderNo'); ?></th>
        <th><?php echo $this->translate('buyers'); ?></th>
        <th><?php echo $this->translate('orderItem'); ?></th>
        <th><?php echo $this->translate('orderTotal'); ?></th>
        <th><?php echo $this->translate('orderStatue.01'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->saleOrderList as $saleOrder): ?>
        <tr>
            <td><?php echo $saleOrder->orderNo; ?></td>
            <td><?php echo $saleOrder->buyerName; ?></td>
            <td>

            </td>
            <td>
                <?php echo $saleOrder->buyerCrnCode. ' '; ?>
                <label class="saleOrderTotalAmount_"></label>
                <script type="text/javascript">$(".saleOrderTotalAmount_").html(formatCurrency(<?php echo $saleOrder->totalAmount;?>, 2));</script>
            </td>
            <td><?php echo date('Y-m-d H:i:s', strtotime($saleOrder->lastUpdate)); ?></td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
