<table class="table table-bordered listSaleOrder">
    <thead>
    <tr>
        <th><?php echo $this->translate('orderNo'); ?></th>
        <th><?php echo $this->translate('buyers'); ?></th>
        <th><?php echo $this->translate('orderItem'); ?></th>
        <th><?php echo $this->translate('orderTotal'); ?></th>
        <th><?php echo $this->translate('state'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->orderList as $order): ?>
        <tr>
            <td><?php echo $order->orderNo; ?></td>
            <td><?php echo $order->buyerName; ?></td>
            <td>
                <?php echo date('Y-m-d H:i:s', strtotime($order->lastUpdate)); ?>
            </td>
            <td>
                <?php echo $order->buyerCrnCode. ' '; ?>
                <label class="saleOrderTotalAmount_"></label>
                <script type="text/javascript">$(".saleOrderTotalAmount_").html(formatCurrency(<?php echo $order->totalAmount;?>, 2));</script>
            </td>
            <td class="text-center">
                <?php echo $this->ShowDictionaryTo($this->dic_Setting["ORDER_STATUS"], $this->userlangCode, $this->dic_Setting["ORDER_STATUS"], $order->orderStatus); ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
