<table class="table table-bordered listSaleOrder">
    <thead>
    <tr>
        <th><?php echo $this->translate('productNAME'); ?></th>
        <th><?php echo $this->translate('brand'); ?></th>
        <th><?php echo $this->translate('model'); ?></th>
        <th><?php echo $this->translate('supplierName'); ?></th>
        <th><?php echo $this->translate('state'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->productList as $product): ?>
        <tr>
            <td><?php echo $product->productName; ?></td>
            <td><?php echo $product->productBrand; ?></td>
            <td>
                <?php echo $product->productModel ?>
            </td>
            <td class="text-right">
                <?php echo $product->supplierName ?>
            </td>
            <td>
                <?php echo $this->ShowDictionaryTo($this->dic_Setting["PRODUCT_STATUS"], $this->userlangCode, $this->dic_Setting["PRODUCT_STATUS"], $product->productStatus); ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
