<table class="table table-bordered">
    <thead>
    <tr>
        <th><?php echo $this->translate('orderNo'); ?></th>
        <th><?php echo $this->translate('buyers'); ?></th>
        <th><?php echo $this->translate('lastUpdate'); ?></th>
        <th><?php echo $this->translate('orderTotal'); ?></th>
        <th><?php echo $this->translate('state'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->orderList) > 0): ?>
        <?php foreach ($this->orderList as $order): ?>
            <tr style="cursor: pointer;" data-type="<?php echo $this->dataType; ?>" data-id="<?php echo $order->orderID; ?>">
                <td><?php echo $order->orderNo; ?></td>
                <td><?php echo $order->buyerName; ?></td>
                <td>
                    <?php echo date('Y-m-d H:i:s', strtotime($order->lastUpdate)); ?>
                </td>
                <td class="text-right">
                    <?php echo $order->buyerCrnCode. ' '; ?>
                    <?php echo number_format($order->totalAmount,2); ?>
                </td>
                <td>
                    <?php echo $this->ShowDictionaryTo($this->dic_Setting["ORDER_STATUS"], $this->userLangCode, $this->dic_Setting["ORDER_STATUS"], $order->orderStatus); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="5"><?php echo $this->translate('noData'); ?></td>
        </tr>
    <?php endif;?>
    <tr>
        <td colspan="5" class="text-right"><a href="<?php echo $this->listUrl; ?>">更 多 >></a></td>
    </tr>
    </tbody>
</table>
<script src="/ky/js/base64.js"></script>
<script>
    // 行点击
    $("tr").slice(1, -1).click(function () {
        var dataID = $(this).attr("data-id");
        if (dataID !== undefined && dataID !== '') {
            var base = new Base64();
            var resultEnCode = base.encode($(this).attr("data-id"));
            if ($(this).attr("data-type") === 'pur') {
                window.location.href = "/user/pur/view?" + resultEnCode;
            } else if ($(this).attr("data-type") === 'sale') {
                window.location.href = "/user/sale/view?" + resultEnCode;
            }
        }
    });
</script>
