<table class="table table-hover">
    <thead>
    <tr>
        <th><?php echo $this->translate('companyName'); ?></th>
        <th><?php echo $this->translate('industry'); ?></th>
        <th><?php echo $this->translate('partner_regdCountryCode'); ?></th>
        <th><?php echo $this->translate('state'); ?></th>
    </tr>
    </thead>
    <tbody>
    <?php if (count($this->partnerList) > 0): ?>
        <?php foreach ($this->partnerList as $partner): ?>
            <tr>
                <td>
                    <?php if ($this->userrgCode == 'CN') {
                        echo $partner->toName;
                    } elseif (!empty($partner->toEnName)) {
                        echo $partner->toEnName;
                    } else {
                        echo $partner->toName;
                    } ?>
                </td>
                <td>
                    <?php echo $this->ShowDictionaryTo($this->dic_Setting['ISIC_INDUSTRY_TYPE'], $this->userLangCode, $this->dic_Setting['ISIC_INDUSTRY_TYPE'], $partner->industryCode); ?>
                </td>
                <td>
                    <?php echo $this->ShowDictionaryTo($this->dic_Setting['COUNTRY_ISO_CODE'], $this->userLangCode, $this->dic_Setting['COUNTRY_ISO_CODE'], $partner->regdCountryCode); ?>
                </td>
                <td>
                    <?php echo $this->ShowDictionaryTo($this->dic_Setting["PARTNER_STATUS"], $this->userLangCode, $this->dic_Setting["PARTNER_STATUS"], $partner->partnerStatus); ?>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <tr>
            <td colspan="5"><?php echo $this->translate('noData'); ?></td>
        </tr>
    <?php endif;?>
    </tbody>
</table>
