<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/index/index.css" rel="stylesheet">
    <link href="/ky/css/authpage.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">
            <div class="col-md-10 col-md-offset-1">
                <ol class="breadcrumb">
                    <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
                    <li><a href="/user/index/profile"><?php echo $this->translate('userINF'); ?></a></li>
                    <li class="active"><?php echo $this->translate('editProfile'); ?></li>
                </ol>

                <?php if (!empty($this->resultMsg)): ?>
                    <div class="alert alert-danger alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                    </div>
                <?php endif; ?>

                <form class="form-horizontal" action="#" id="contact_edit_form" method="post">
                    <div class="panel panel-default">
                        <div class="panel-heading"><?php echo $this->translate('myINF'); ?></div>
                        <div class="panel-body">
                            <div class="form-group">
                                <label for="name" class="col-sm-2 control-label"><?php echo $this->translate('name'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['realAuthStatus']!=0&&$this->e['realAuthStatus']!=-1):?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['name']; ?>
                                        </p>
                                    <?php else:?>
                                        <input type="text" class="form-control" name="name" id="name" placeholder="<?php echo $this->translate('is_name');?>" value="<?php echo $this->e['name']; ?>" required>
                                    <?php endif; ?>
                                    <input type="hidden" name="contactID" value="<?php echo $this->e['contactID']; ?>">
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="salutation" class="col-sm-2 control-label"><?php echo $this->translate('title'); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="salutation" id="salutation" placeholder="<?php echo $this->translate('title');?>" value="<?php echo $this->e['salutation']; ?>" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="sex" class="col-sm-2 control-label"><?php echo $this->translate('sex'); ?></label>
                                <div class="col-sm-9">
                                    <select class="form-control" name="sex" id="sex">
                                        <?php echo $this->ShowDictionaryList($this->dic_Setting['SEX'], $this->userLangCode, $this->dic_Setting['SEX'], $this->e['sex']); ?>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="birthdate" class="col-sm-2 control-label"><?php echo $this->translate('birthday'); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="birthdate" id="birthdate" placeholder="<?php echo $this->translate('title');?>" value="<?php echo date('Y-m-d', strtotime($this->e['birthdate']));?>" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="identityType" class="col-sm-2 control-label"><?php echo $this->translate('certificateType'); ?></label>
                                <div class="col-sm-9">
                                    <p class="form-control-static">
                                        <?php echo $this->ShowDictionaryTo("ID_TYPE", $this->userLangCode, $this->dic_Setting['ID_TYPE'], $this->e['identityType']); ?>
                                    </p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="identityNo" class="col-sm-2 control-label"><?php echo $this->translate('certificateNo'); ?></label>
                                <div class="col-sm-9">
                                    <?php if ($this->e['realAuthStatus'] != 0 && $this->e['realAuthStatus'] != -1): ?>
                                        <p class="form-control-static">
                                            <?php echo $this->e['identityNo']; ?>
                                        </p>
                                    <?php else: ?>
                                        <input type="text" class="form-control" name="identityNo" id="identityNo" placeholder="<?php echo $this->translate('certificateNo');?>" value="<?php echo $this->e['identityNo'];?>" >
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="department" class="col-sm-2 control-label"><?php echo $this->translate('division'); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="department" id="department" placeholder="<?php echo $this->translate('division');?>" value="<?php echo $this->e['department']; ?>" >
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="title" class="col-sm-2 control-label"><?php echo $this->translate('job'); ?></label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" name="title" id="title" placeholder="<?php echo $this->translate('job');?>" value="<?php echo $this->e['title']; ?>" >
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-default">
                        <div class="panel-heading"><?php echo $this->translate('contactInfo'); ?></div>
                        <div class="panel-body">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="email" class="col-sm-2 control-label"><?php echo $this->translate('email'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="email" class="form-control" name="email" id="email" placeholder="<?php echo $this->translate('is_emails');?>" value="<?php echo $this->e['email']; ?>" >
                                    </div>

                                    <label for="mobilePhone" class="col-sm-2 control-label"><?php echo $this->translate('mobile'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="mobilePhone" id="mobilePhone" placeholder="<?php echo $this->translate('is_phone');?>" value="<?php echo $this->e['mobilePhone']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="phone" class="col-sm-2 control-label"><?php echo $this->translate('telephone'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="phone" id="phone" placeholder="<?php echo $this->translate('is_tel');?>" value="<?php echo $this->e['phone']; ?>" >
                                    </div>

                                    <label for="fax" class="col-sm-2 control-label"><?php echo $this->translate('fax'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="fax" id="fax" placeholder="<?php echo $this->translate('fax');?>" value="<?php echo $this->e['fax']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="assistantName" class="col-sm-2 control-label"><?php echo $this->translate('HPname'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="assistantName" id="assistantName" placeholder="<?php echo $this->translate('HPname');?>" value="<?php echo $this->e['assistantName']; ?>" >
                                    </div>

                                    <label for="assistantPhone" class="col-sm-2 control-label"><?php echo $this->translate('HPphone'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="assistantPhone" id="assistantPhone" placeholder="<?php echo $this->translate('HPphone');?>" value="<?php echo $this->e['assistantPhone']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="mailingAddress" class="col-sm-2 control-label"><?php echo $this->translate('maillADD'); ?></label>
                                    <div class="col-sm-10">
                                        <input type="text" class="form-control" name="mailingAddress" id="mailingAddress" placeholder="<?php echo $this->translate('maillADD');?>" value="<?php echo $this->e['mailingAddress']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="mailingZipCode" class="col-sm-2 control-label"><?php echo $this->translate('postcode'); ?></label>
                                    <div class="col-sm-4">
                                        <input type="text" class="form-control" name="mailingZipCode" id="mailingZipCode" placeholder="<?php echo $this->translate('postcode');?>" value="<?php echo $this->e['mailingZipCode']; ?>" >
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="timeZone" class="col-sm-2 control-label"><?php echo $this->translate('timezone'); ?></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" name="timeZone" id="timeZone">
                                            <?php echo $this->ShowDictionaryList($this->dic_Setting['TIME_ZONE'], $this->userLangCode, $this->dic_Setting['TIME_ZONE'], $this->e['contactPreference']['timeZone']); ?>
                                        </select>
                                    </div>

                                    <label for="langCode" class="col-sm-2 control-label"><?php echo $this->translate('langCode'); ?></label>
                                    <div class="col-sm-4">
                                        <select class="form-control" name="langCode" id="langCode">
                                            <?php echo $this->ShowDictionaryList($this->dic_Setting['SYS_LANG'], $this->userLangCode, $this->dic_Setting['SYS_LANG'], $this->e['contactPreference']['langCode']); ?>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-12 col-md-4 col-md-offset-3">
                            <button type="submit" class="btn btn-warning btn-default btn-block"><?php echo $this->translate('save'); ?></button>
                        </div>
                    </div>
                </form>
            </div>
		</div>
	</div>
</div>

<div id="et-layer-userauth" style="display: none;">
    <div class="et-auth-top et-auth-bg-no">
        <h3><!--个人实名认证--><?php echo $this->translate('userSignh3');?></h3>
        <p><!--*仅支持由中华人民共和国居民身份证的用户进行认证，请准确填写并核对无误后，点击确认按钮提交认证-->
            <?php echo $this->translate('userSignp01');?>
        </p>
    </div>
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div class="et-auth-row">
            <label for="name"><!--姓名--><?php echo $this->translate('name');?></label>
            <p class="et_auth_name" id="et_auth_name"><?php echo $this->e['name']; ?></p>
        </div>
        <div class="et-auth-row">
            <label for="name"><!--身份证--><?php echo $this->translate('ID_card');?></label>
            <p class="et_auth_identityNo" id="et_auth_identityNo"><?php echo $this->e['identityNo'];?></p>
        </div>
        <div class="et-auth-row">
            <label for="name"><!--移动电话--><?php echo $this->translate('mobile');?></label>
            <p class="et_auth_mobilePhone" id="et_auth_mobilePhone"><?php echo $this->e['mobilePhone']; ?></p>
        </div>
        <div class="et-auth-row">
            <button type="button"  class="et-btn"><!--确认--><?php echo $this->translate('confirmed'); ?></button></div>
    </div>
</div>

<div id="et-layer-userauth2" style="display: none;">
    <div class="et-auth-top et-auth-bg-ok">
        <h3><!--个人实名认证--><?php echo $this->translate('userSignh31');?></h3>
        <p><!--*仅支持由中华人民共和国居民身份证的用户进行认证，请准确填写并核对无误后，点击确认按钮提交认证-->
            <?php echo $this->translate('userSignp02');?></p>
    </div>
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div class="et-auth-row">
            <label for="name"><!--姓名--><?php echo $this->translate('name');?></label>
            <p class="et_auth_name"><?php echo $this->e['name']; ?></p>
        </div>
        <div class="et-auth-row">
            <label for="name"><!--身份证--><?php echo $this->translate('ID_card');?></label>
            <p class="et_auth_code"><?php echo $this->e['identityNo'];?></p>
        </div>
        <div class="et-auth-row">
            <label for="name"><!--移动电话--><?php echo $this->translate('mobile');?></label>
            <p class="et_auth_bankaccount"><?php echo $this->e['mobilePhone']; ?></p>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $('.company-navigation').find('a').each(function () {
            if (this.href === document.location.href || document.location.href.search(this.href) >= 0) {
                $(this).addClass('nav-selected');
            } else {
                $(this).removeClass('nav-selected');
            }
        });

        $('#user-authNo').click(function () {
            var name = $("#name").val();
            var identityNo = $("#identityNo").val();
            var mobilePhone = $("#mobilePhone").val();

            $("#et_auth_name").html(name);
            $("#et_auth_identityNo").html(identityNo);
            $("#et_auth_mobilePhone").html(mobilePhone);

            var auth_error = $('#et-layer-userauth').find('.et-auth-error');
            if (name == '' || identityNo == '' || mobilePhone == '') {
                var tips2 = "<?php echo $this->translate('userTips01');?><a href='#' id='reEditUserInfo' style='color: #6298cd;'><?php echo $this->translate('edit');?></a><?php echo $this->translate('userTips02');?>";
                auth_error.html("");
                auth_error.html(tips2);
                auth_error.show();

                $("#reEditUserInfo").bind("click", function () {
                    layer.closeAll();
                    auth_error.html("");
                    auth_error.hide();
                });
            }

            layer.open({
                type: 1,
                title: false,
                shadeClose: true,
                shade: 0.2,
                area: ['500px', '300px'],
                content: $('#et-layer-userauth')
            })
        });

        $('#user-authOk').click(function () {
            var id_card = '<?php echo $this->e['certificateNo']; ?>';
            if (id_card = "") {
                layer.msg('IDcard is NULL', {
                    icon: 2,
                    time: 20000 //20s后自动关闭
                });
                return false;
            }
            layer.open({
                type: 1,
                title: false,
                shadeClose: true,
                shade: 0.2,
                area: ['500px', '300px'],
                content: $('#et-layer-userauth2')
            })
        });

        var layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            var laydate = layui.laydate;

            // 直接嵌套显示
            laydate.render({
                elem: '#birthdate'
                ,trigger: 'click'
                ,lang: layDateLang
            });
        });
	});
</script>
</body>
</html>
