<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
	<link href="/ky/css/index/index.css" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-default navbar-static-top top-memu shadow">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="javascript:void(0)">
				<img alt="eTradeFast" title="eTradeFast" src="/ky/images/index/Logo_loginH75.png" style="width: 32px;">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
				欢迎登录
			</p>
		</div>
	</div>
</nav>

<div class="container-fluid index-body">
	<div class="container">

		<div class="row">

		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});
</script>
</body>
</html>
