<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<title><?php echo $this->escape($this->seed_Setting['www_html_title']);?></title>
<meta name="description" content="">
<meta name="keywords" content="">
<link href="/ky/css/base.css" rel="stylesheet">
<link href="/ky/css/style.css" rel="stylesheet">
<script type="text/javascript" src="/ky/js/jquery.js"></script>
<script type="text/javascript" src="/ky/js/www.js"></script>
<script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
<script type="text/javascript">
    function selectAA() {
        $.ajax(
            {
                type: "post",
                url: "<?php echo WWW;?>user/data/country",
                data: { "type": "COUNTRY_ISO_CODE" },
                success: function (msg) {
                    var json;
                    if(typeof msg === 'object'){
                        json = msg;
                    }
                    else{
                        json = eval('(' + msg + ')');
                    }
                    $.each(json, function (n, value) {
                        $("#COUNTRY_ISO_CODE").append("<option value=" + value.code + ">" + value.name + "</option>");
                    });
                    $("#COUNTRY_ISO_CODE").val("CN");
                    //  $("#COUNTRY_ISO_CODE  option[value="+Coun+"] ").attr("selected",true)
                    selectBB();
                }
            });
    };


    function selectBB() {
        $("#PROVINCE_CODE").html("");
        $.ajax(
            {
                type: "post",
                url: "<?php echo WWW;?>user/data/province",
                data: { "provinceID":$('#COUNTRY_ISO_CODE').attr("value")},
                success: function (msg2) {

                    var json2;
                    if(typeof msg2 === 'object'){
                        json2 = msg2;
                    }
                    else{
                        json2 = eval('(' + msg2 + ')');
                    }
                    $.each(json2, function (n, value) {
                        $("#PROVINCE_CODE").append("<option value=" + value.code + ">" + value.name + "</option>");
                    });
                    $("#PROVINCE_CODE").val("44");
                    selectCC();
                }
            });
    };
    function selectCC() {
        $("#CITY_CODE").html("");
        $.ajax(
            {
                type: "post",
                url: "<?php echo WWW;?>user/data/city",
                data: {"cityID":$('#PROVINCE_CODE').attr("value") },
                success: function (msg3) {
                    var json3;
                    if(typeof msg3 === 'object'){
                        json3 = msg3;
                    }
                    else{
                        json3 = eval('(' + msg3 + ')');
                    }
                    $.each(json3, function (n, value) {
                        $("#CITY_CODE").append("<option value=" + value.code + ">" + value.name + "</option>");
                    });
                    $("#CITY_CODE").val("4401");
                }
            })
    };
    $(function () {
        selectAA();
        $('#COUNTRY_ISO_CODE').bind("change", selectBB);
        $('#PROVINCE_CODE').bind("change", selectCC);
    });
</script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div style="margin: 0 auto;" class="o_content w940">
        <div class="o_tab">
            <ul>
                <li><a href="<?php echo WWW;?>user/index/edit"><!-- 个人信息 --><?php echo $this->translate('myINF');?></a></li>
                <li class="cur"><a href="<?php echo WWW;?>user/index/photo"><!-- 头像 --><?php echo $this->translate('myPHOTO');?></a></li>
                <li><a href="<?php echo WWW;?>user/index/passwd"><!-- 账户安全 --><?php echo $this->translate('myNO');?></a></li>
            </ul>
        </div>
        <div class="n_o_c_tit">
            <h4><!--编辑头像--><?php echo $this->translate('edit').$this->translate('myPHOTO');?></h4>
        </div>
        <div class="u_info_ed_box">
            <?php echo $this-> ShowWebuploader($this->attlist);?>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script src="/ky/js/jquery.validate.js"></script>
<script>
$(function(){
    $("#account_edit_form").validate({
        submitHandler: function() {
            form.submit();
        }
    })
});
jQuery.validator.addMethod("mail", function (value, element) {
    var mail = /^[a-z0-9._%-]+@([a-z0-9-]+\.)+[a-z]{2,4}$/;
    return this.optional(element) || (mail.test(value));
}, "<?php echo $this->translate('email').$this->translate('de_format');?>");
jQuery.validator.addMethod("phone", function (value, element) {
    var phone = /^[\d|\-|\+|\s]+$/;
    return this.optional(element) || (phone.test(value));
}, "<?php echo $this->translate('phone').$this->translate('de_format');?>");
jQuery.validator.addMethod("mobile", function (value, element) {
    var mobile = /^[\d|\-|\+|\s]+$/;
    return this.optional(element) || (mobile.test(value));
}, "<?php echo $this->translate('mobile_phone').$this->translate('de_format');?>");
jQuery.validator.addMethod("fax",function(value,element){
    var fax = /^[\d|\-|\+|\s]+$/;
    return this.optional(element) || (fax.test(value));
},"<?php echo $this->translate('fax').$this->translate('de_format');?>");
</script>
</body>
</html>
