<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->escape($this->seed_Setting['www_html_title']);?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <?php echo $this->render(SEED_WWW_TPL.'/left_menu.phtml');?>
    <div class="o_content fr w940">
        <div class="con_div">
            <h1><?php echo $this->escape($this->news['news_title']);?></h1>
            <div class="time"><?php echo date('Y-m-d',$this->news['add_time']);?> <a href="<?php echo $this->BaseUrl();?>/news/?cate_mark=<?php echo $this->news['cate_mark'];?>"><?php echo $this->escape($this->news['cate_name']);?></a></div>
            <div class="con_txt">
                <?php echo $this->ShowContent($this->news['news_m_content']);?>
            </div>
        </div>
        <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
    </div>
</div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>