<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
function doadd(){
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/articlecate/add',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
function doupdate(){
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/articlecate/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
function dodelete(){
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/articlecate/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
}
</script>
<h1>资讯分类</h1>
<div class="textnav">
  <p>
    <input class="btn btn-primary" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/articlecate/index/'"/>
  </p>
</div>
<table width="100%" border="0">
  <form name="post_form" method="post" action="" id="post_form" >
    <tr>
      <td valign="top" style="width:200px;">
        <script language="javascript" type="text/javascript">
		d = new dTree("d","/images/center/");
		d.add(0,-1,"资讯分类");
		<?php if(is_array($this->cates)):?>
		<?php foreach($this->cates as $key => $cate):?>
		d.add("<?php echo $cate['cate_id'];?>","<?php echo $cate['parent'];?>","<?php echo ($cate['cate_name']);?>","<?php echo $this->BaseUrl();?>/articlecate/index/cate_id/<?php echo ($cate['cate_id']);?>");
		<?php endforeach;?>
		<?php endif;?>
		document.write(d);
		</script></td>
      <td valign="top"><table class="admin_form">
          <tr>
            <td><strong>所属：</strong>
              <p>
                <select name="parent" id="parent">
                  <option value="0"></option>
                  <?php if(is_array($this->cateoptions)):?>
                  <?php foreach($this->cateoptions as $key => $cate):?>
                  <option value="<?php echo $cate['cate_id'];?>" <?php if($cate['cate_id']==$this->cate['parent']):?>selected<?php endif;?>><?php echo $cate['cate_name'];?></option>
                  <?php endforeach;?>
                  <?php endif;?>
                </select>
              </p></td>
          </tr>
          <tr>
            <td><strong>名称：</strong>
              <p>
                <input  name="cate_name" id="cate_name" value="<?php echo $this->cate['cate_name'];?>" type="text" class="admin_txt1"/>
              </p></td>
          </tr>
          <tr>
            <td><strong>保存名称(英文和数字*)：</strong>
              <p>
                <input name="cate_mark" id="cate_mark" value="<?php echo ($this->cate['cate_mark']);?>" type="text" class="admin_txt1"/>
              </p></td>
          </tr>
          <tr>
            <td><strong>排序：</strong>
              <p>
                <input  name="order_by" id="order_by" value="<?php echo $this->cate['order_by'];?>" type="text" class="admin_txt1"/>
              </p></td>
          </tr>
    	<?php if(isset($this->seed_Setting['pc_open']) && $this->seed_Setting['pc_open']=='1'):?>
 		 <tr>
		      <td><strong>图标(PC版)：</strong>
						<p>
				        	<input name="cate_image" id="cate_image" readonly value="<?php echo $this->escape($this->cate['cate_image']);?>" type="text" class="admin_txt1"/>
				        	<input type="button" name="select" value="选择" class="btn btn-primary" onclick="selectCoverImage('newscate','cate_image')">		        	
				        	<input type="button" name="preview_cate_image" id="preview_cate_image" value="预览" class="btn btn-primary" onclick="previewCoverImage('cate_image')" style="display:none;">
				        </p></td>
		 </tr>   	
    	<?php endif;?>
		 <tr>
		      <td><strong>图标(移动版)：</strong>
						<p>
				        	<input name="cate_m_image" id="cate_m_image" readonly value="<?php echo $this->escape($this->cate['cate_m_image']);?>" type="text" class="admin_txt1"/>
				        	<input type="button" name="select" value="选择" class="btn btn-primary" onclick="selectCoverImage('newscate_m','cate_m_image')">		        	
				        	<input type="button" name="preview_cate_m_image" id="preview_cate_m_image" value="预览" class="btn btn-primary" onclick="previewCoverImage('cate_m_image')" style="display:none;">
				        </p></td>
		 </tr>
         <tr>
            <td><?php if($this->cate['cate_id']>0):?>
            <input type="hidden" name="cate_id" id="cate_id" value="<?php echo $this->cate['cate_id'];?>">
              <input class="btn btn-primary" name="updateConfirm" type="submit" value="修改" onclick="doupdate();"/>
              &nbsp;
              <input class="btn btn-primary" name="deleteConfirm" type="submit" value="删除" onclick="dodelete();"/>
              &nbsp;
              <?php else:?>
              <input class="btn btn-primary" name="addConfirm" type="submit" value="添加" onclick="doadd();"/>
              &nbsp;
              <?php endif;?>
              <input class="btn btn-primary" name="reset" type="reset" value="重置"/></td>
          </tr>
        </table>
  </form>
    </td>
  
    </tr>
  
</table>
<?php echo $this->render("footer.phtml") ?> 