<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
    $("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/article/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});

	$("#idtab ul").idTabs();
});

function selectMaterial(){
	tb_show('', '<?php echo $this->BaseUrl();?>/material/select/?TB_iframe=true&width=800&height=450');
}

function setMaterial(id){
	loadMaterial(id);
}

function loadMaterial(id){
	$.getJSON( "<?php echo $this->BaseUrl();?>/material/getjson?material_id="+id, function( data ) {
		if(data.material_id>0){
			$("#news_material_id").val(data.material_id);
			$("#material_select").html(data.material_title);
			$("#news_title").val(data.material_title);
			$("#news_m_image").val(data.material_m_image);
			$("#news_m_desc").val(data.material_m_desc);
		}
	});
}

</script>
<script type="text/javascript" src="<?php echo $this->seed_Setting['static_app_server'] ?>/commerce/editor/xheditor.min.js"></script>
<script type="text/javascript" src="<?php echo $this->seed_Setting['static_app_server'] ?>/commerce/editor/xheditor_lang/zh-cn.js"></script>
<h1>修改文章</h1>
<div class="textnav"  id="idtab" >
  <ul>
    <li><a class="selected" href="#basic">基本数据</a></li>
    <li><a href="#status">状态设置</a></li>
  </ul>
  <p>
    <input class="btn btn-primary" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
  <table class="admin_form" id="basic">
    <tr>
      <td><strong>文章分类：</strong>
        <p>
          <select name="cate_id" id="cate_id" class="admin_txt1">
            <option value="0"></option>
            <?php if(is_array($this->cateoptions)):?>
            <?php foreach ($this->cateoptions as $cate):?>
            <option value="<?php echo $cate['cate_id'];?>" <?php echo ($cate['cate_id']==$this->news['cate_id'])?"selected":"";?>><?php echo $cate['cate_name'];?></option>
            <?php endforeach;?>
            <?php endif;?>
          </select>
        </p></td>
    </tr>
    <tr>
      <td><strong>内容来源：</strong>
        <p>
          <input type="radio" name="news_source" id="news_source0" value="0" style="width:15px;" <?php echo ($this->news['news_source']==0)?"checked":"";?> onclick="$('#tr_source1').show();$('#tr_source0').hide();" disabled>
          <label for="news_source0">单独添加</label>
          &nbsp;
          <input type="radio" name="news_source" id="news_source1" value="1" style="width:15px;" <?php echo ($this->news['news_source']==1)?"checked":"";?> onclick="$('#tr_source0').show();$('#tr_source1').hide();" disabled>
          <label for="news_source1">素材库</label>
        </p></td>
    </tr>
    <tr id="tr_source0" <?php echo ($this->news['news_source']==0)?"style=\"display:none;\"":"";?>>
    	<td><strong>选择素材：</strong>
    	<p>
    		<input type="button" name="select" value="点击选择"  class="btn btn-primary"  onclick="selectMaterial()"><input type="hidden" name="news_material_id" id="news_material_id" value="<?php echo ($this->news['news_material_id']);?>">
    		当前选择:<span id="material_select"><?php echo ($this->news['news_material_title']);?></span>
    	</p>
    	</td>
    </tr>
    <tr>
      <td><strong>文章标题：</strong>
        <p>
          <input name="news_title" id="news_title" value="<?php echo ($this->news['news_title']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>文章封面：</strong>
        <p>
          <input name="news_m_image" id="news_m_image" readonly value="<?php echo ($this->news['news_m_image']);?>" type="text" class="admin_txt1"/>
          <input type="button" name="select" value="选择"  class="btn btn-primary" onclick="selectCoverImage('newsthumb_m','news_m_image')">
          <input type="button" name="preview_news_m_image" id="preview_news_m_image" value="预览"  class="btn btn-primary" onclick="previewCoverImage('news_m_image')" <?php echo (($this->news['news_m_image'])=="")?"style=\"display:none;\"":"";?>>
        </p></td>
    </tr>
    <tr>
      <td><strong>文章概要：</strong>
        <p>
          <textarea class="textarea" name="news_m_desc" id="news_m_desc"><?php echo ($this->news['news_m_desc']);?></textarea>
        </p></td>
    </tr>
    <tbody  id="tr_source1" <?php echo ($this->news['news_source']==1)?"style=\"display:none;\"":"";?>>
    <tr>
      <td><strong>表现类型：</strong>
        <p>
          <input type="radio" name="news_type" id="news_type0" value="0" style="width:15px;" <?php echo ($this->news['news_type']==0)?"checked":"";?> onclick="$('#li_type0').show();$('#li_type1').hide();" disabled>
          <label for="news_type0">文字类</label>
          &nbsp;
          <input type="radio" name="news_type" id="news_type1" value="1" style="width:15px;" <?php echo ($this->news['news_type']==1)?"checked":"";?> onclick="$('#li_type1').show();$('#li_type0').hide();" disabled>
          <label for="news_type1">图册类</label>
        </p></td>
    </tr>
    <tr id="li_type0" <?php echo ($this->news['news_type']==1)?"style=\"display:none;\"":"";?>>
      <td><strong>文章内容：</strong>
            <div class="txt_lft">
                <textarea  id="container" name="news_m_content" rows="20" cols="80" style="width: 100%; height:400px">
                    <?php echo $this->ShowContent($this->news['news_m_content']);?>
                </textarea>
                <!-- 配置文件 -->
                <script type="text/javascript" src="/ueditor/ueditor.config.js"></script>
                <!-- 编辑器源码文件 -->
                <script type="text/javascript" src="/ueditor/ueditor.all.js"></script>
                <!-- 实例化编辑器 -->
                <script type="text/javascript">
                    var ue = UE.getEditor('container');
                </script>
            </div>
            <input id="imgZoneUrl1" type="hidden" value="/b/upload/imagexhr/initimagepage?type=2&img_cate=news_m">
      </td>
    </tr>
    <tr>
        <td id="imgZoneContent1" style="margin-top:10px;"></td>
    </tr>
    <tr id="li_type1" <?php echo ($this->news['news_type']==0)?"style=\"display:none;\"":"";?>>
      <td><strong>文章图册：</strong>
        <p>
          <input type="button" name="select" value="批量上传"  class="btn btn-primary"  onclick="selectAlbumImage('newsalbum_m','album_show')">
	        <div class="image_show">
	          <ul id="album_show">
	            <?php if(is_array($this->news['news_m_images'])):?>
	            <?php foreach ($this->news['news_m_images'] as $image):?>

	              <li style="padding-bottom:5px;"><img src='<?php echo $this->seed_Setting['upload_view_server'].$image['thumb_image'];?>' style="width:150px;padding-bottom:5px;"><br>
	                  <input type='checkbox' name='album_image_ids[<?php echo $image['image_id'];?>]' value='<?php echo $image['image_id'];?>' checked>
	                  <input type='hidden' name='album_thumb_images[<?php echo $image['image_id'];?>]' value='<?php echo $image['thumb_image'];?>'>
	                  <input type='hidden' name='album_normal_images[<?php echo $image['image_id'];?>]' value='<?php echo $image['normal_image'];?>'>
	                  <input type='hidden' name='album_original_images[<?php echo $image['image_id'];?>]' value='<?php echo $image['original_image'];?>'>
	                  说明：
	                  <input type='text' name='album_image_descs[<?php echo $image['image_id'];?>]' value='<?php echo $image['image_desc'];?>' style='width:70px;'>
	                  排序：
	                  <input type='text' name='album_order_bys[<?php echo $image['image_id'];?>]' value='<?php echo $image['order_by'];?>' style='width:15px;'></li>
	              <?php endforeach;?>
	              <?php endif;?>
	          </ul>
	        </div>
        </p>
      </td>
    </tr>
    </tbody>
  </table>
  <table class="admin_form" id="status">
    <tr>
      <td><strong>添加时间：</strong>
        <p>

        <p>
          <input name="add_time" id="add_time" value="<?php echo date("Y-m-d H:i:s",$this->news['add_time']);?>" type="text" class="admin_txt1"/>
        </p>
        </p></td>
    </tr>
    <tr>
      <td><strong>是否开放：</strong>
        <p>
          <input type="radio" name="is_m_actived" id="is_m_actived0" value="0" style="width:15px;" <?php echo ($this->news['is_m_actived']==0)?"checked":"";?>>
          否&nbsp;
          <input type="radio" name="is_m_actived" id="is_m_actived1" value="1" style="width:15px;" <?php echo ($this->news['is_m_actived']==1)?"checked":"";?>>
          是 </p></td>
    </tr>
    <tr>
      <td><strong>访问次数：</strong>
        <p>
          <input name="view_cnt" id="view_cnt" value="<?php echo ($this->news['view_cnt']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
  </table>
  <div class="batch">
    <input type="hidden" name="news_id" id="news_id" value="<?php echo ($this->news['news_id']);?>">
    <input class="btn btn-primary"  name="" type="submit" value="提交" />
  </div>
</form>
<?php echo $this->render("footer.phtml") ?>