<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoanList'); ?></li>
        </ol>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body" style="height: 200px; padding: 0;">
                        <div class="row">
                            <div class="col-xm-12" style="padding-top: 30px;"></div>
                        </div>

                        <div class="col-md-5" style="height: 130px;">
                            <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                            <div id="pie_" style="width: 350px;height: 250px;"></div>
                        </div>

                        <div class="col-md-7" style="padding-top: 35px;">
                            <div class="row">
                                <div class="col-md-5">
                                    <p class="form-control-static text-999"><?php echo $this->translate('可融资额度'); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <p class="form-control-static text-666" style="font-weight: bold;">46,500,000.00 元</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-5">
                                    <p class="form-control-static text-999"><?php echo $this->translate('总额度'); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <p class="form-control-static text-666" style="font-weight: bold;">150,000,000.00 元</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body" style="padding: 0;">
                        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                        <div id="line_" style="height: 200px;" ></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('项目进度'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringMode" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="RF"><?php echo $this->translate('factoring_mode_rf'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="PF"><?php echo $this->translate('factoring_mode_pf'); ?></button>
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="EF"><?php echo $this->translate('factoring_mode_ef'); ?></button>
                                <input type="hidden" name="factoringMode" id="factoringMode" value="all">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        let layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            let laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        let dataDictQuery = '/user/common/dict-ajax';
        let dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/settle/payment-trading-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    checkboxHeader: true,
                    clickToSelect: true,
                    // 对a和button标签忽略clickToSelect事件
                    ignoreClickToSelectOn: function (element) {
                        return $.inArray(element.tagName, ['A', 'BUTTON']);
                    },
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            startDate: $("#startDate").val(),
                            endDate: $("#endDate").val(),
                            crnCode: $("#crnCode").val(),
                            lowerAmount: $("#lowerAmount").val(),
                            upperAmount: $("#upperAmount").val(),
                            tradingType: $("#tradingType").val(),
                            transNo: $("#transNo").val(),
                            paymentStatus: $("#paymentStatus").val()
                        };
                    },
                    onClickRow:function(row, $element, field) {
                        // alert(JSON.stringify(row));
                    },
                    columns: [{
                        halign: 'center',
                        checkbox: true
                    }, {
                        field: 'transNo',
                        title: '<?php echo $this->translate("项目编号"); ?>',
                        width: 150,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            value += '<br>';

                            let subject = row.subject;
                            if (subject === undefined || subject === '' || subject === null) {
                                subject = "";
                            }
                            subject += '<br>';

                            let remarks = row.remarks;
                            if (remarks === undefined || remarks === '' || remarks === null) {
                                remarks = "";
                            }

                            return '<a href="/user/freight/freight-loan-view" target="_blank">' + value + '</a>';
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("应收账款金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        width: 140,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            let result = row.crnCode + ' ' + formatCurrency(value, 2);

                            return '<a href="/user/freight/freight-loan-view" target="_blank">' + result + '</a>';
                        }
                    }, {
                        field: 'oppCustomerName',
                        title: '<?php echo $this->translate("债务方"); ?>',
                        valign: 'middle',
                        width: 300,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return '<a href="/user/freight/freight-loan-view" target="_blank">' + value + '</a>';
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("目标融资金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        width: 140,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            let result = '<p>' + row.crnCode + ' ' + formatCurrency(value, 2) + '</p>';
                            if (row.rptype === 'P') {
                                result = '<p class="text-danger">' + row.crnCode + ' ' + formatCurrency(value, 2) + '</p>';
                            }

                            return '<a href="/user/freight/freight-loan-view" target="_blank">' + result + '</a>';
                        }
                    }, {
                        field: 'recordDate',
                        title: '<?php echo $this->translate("届满日"); ?>',
                        valign: 'middle',
                        width: 120,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return new Date(value).format("yyyy-MM-dd");
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("项目状态"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            let result = '';
                            let data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("operation"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            let base = new Base64();
                            let resultEnCode = base.encode(row.tradingID);
                            let result = '';
                            if (row.allowPayment) {
                                let href = "/user/freight/freight-loan-payment?"+resultEnCode;
                                let str = "<?php echo $this->translate('settle_payment');?>";
                                result += '<a href="' + href + '" style="color: #337ab7">' + str + '</a>';
                            }

                            return result;
                        }
                    }]
                });
            }
        });
	});

    // 基于准备好的dom，初始化echarts实例
    let pie_Chart = echarts.init(document.getElementById('pie_'));
    let line_Chart = echarts.init(document.getElementById('line_'));

    let pie_data = {
        value: 45,
        name: '完成率'
    };

    // 指定图表的配置项和数据
    let pie_option = {
        title: [{
            id: 'ti',
            text: pie_data.value + '%',
            x: '29%',
            y: '38%',
            textAlign: 'center',
            textStyle: {
                // fontWeight: 'bold',
                fontSize: 22,
                color: '#1A3B4C'
            }
        }, {
            id: 'ti2',
            text: '占用额度',
            x: '29%',
            y: '30%',
            textAlign: 'center',
            textStyle: {
                // fontWeight: 'bold',
                fontSize: 12,
                color: '#1A3B4C'
            }
        }],
        data: [{
            name: pie_data.name,
        }],


        series: [{ // 主圆环
            name: pie_data.name,
            type: 'pie',
            radius: ['40%', '70%'], // 饼图的半径，数组的第一项是内半径，第二项是外半径。
            startAngle: 180,    // 起始角度，支持范围[0, 360]。
            center: ['30%', '42%'],
            top: 0,
            color: [{
                type: 'linear',
                x: 1,
                y: 0,
                x2: 0,
                y2: 0,
                colorStops: [{
                    offset: 0,
                    color: 'rgba(47,172,234,1)' // 0% 处的颜色
                }, {
                    offset: 1,
                    color: 'rgba(47,172,234,.1)' // 100% 处的颜色
                }]
            }, 'transparent'],
            hoverAnimation: true,
            legendHoverLink: false,
            z: 10,
            labelLine: {
                normal: {
                    show: false
                }
            },
            data: [{
                value: 50 * pie_data.value / 100
            }, {
                value: 100 - (50 * pie_data.value / 100)
            }]
        }, { // 背景圆环
            name: '',
            type: 'pie',
            radius: ['40%', '60%'],
            center: ['30%', '42%'],
            silent: true,
            startAngle: 180,
            labelLine: {
                normal: {
                    show: false
                }
            },
            z: 5,
            data: [{
                value: 50,
                itemStyle: {
                    color: '#1A3B4C'
                }
            }, {
                value: 50,
                itemStyle: {
                    color: 'transparent'
                }
            }]
        }]
    };

    // 使用刚指定的配置项和数据显示图表。
    pie_Chart.setOption(pie_option);

    let line_option = {
        tooltip: {
            trigger: 'axis'
        },
        xAxis: [{
            type: 'category',
            data: ['01','02','03','04','05','06', '07', '08', '09', '10', '11', '12'],
            axisLine: {
                lineStyle: {
                    color: "#999"
                }
            }
        }],
        yAxis: [{
            name: '万元',
            type: 'value',
            splitNumber: 4,
            splitLine: {
                lineStyle: {
                    type: 'solid',
                    color: '#DDD'
                }
            },
            axisLine: {
                show: false,
                lineStyle: {
                    color: "#333"
                },
            },
            nameTextStyle: {
                color: '#999',
                align: 'left',
                width: '100%'
            },
            splitArea: {
                show: false
            }
        }],
        series: [{
            name: '本月',
            type: 'line',
            data: [23,60,20,36,23,75],
            lineStyle: {
                normal: {
                    width: 6,
                    color: {
                        type: 'linear',

                        colorStops: [{
                            offset: 0,
                            color: '#A9F387' // 0% 处的颜色
                        }, {
                            offset: 1,
                            color: '#48D8BF' // 100% 处的颜色
                        }],
                        globalCoord: false // 缺省为 false
                    },
                    shadowColor: 'rgba(72,216,191, 0.3)',
                    shadowBlur: 10,
                    shadowOffsetY: 20
                }
            },
            itemStyle: {
                normal: {
                    color: '#fff',
                    borderWidth: 10,
                    /*shadowColor: 'rgba(72,216,191, 0.3)',
                    shadowBlur: 100,*/
                    borderColor: "#A9F387"
                }
            },
            smooth: true
        }, {
            name: '上月',
            type: 'line',
            data: [75,60,30,80,120,95, 100, 80, 50, 40],
            lineStyle: {
                normal: {
                    width: 6,
                    color: {
                        type: 'linear',

                        colorStops: [{
                            offset: 0,
                            color: '#F6D06F' // 0% 处的颜色
                        }, {
                            offset: 1,
                            color: '#F9A589' // 100% 处的颜色
                        }],
                        globalCoord: false // 缺省为 false
                    },
                    shadowColor: 'rgba(72,216,191, 0.3)',
                    shadowBlur: 10,
                    shadowOffsetY: 20
                }
            },
            itemStyle: {
                normal: {
                    color: '#fff',
                    borderWidth: 10,
                    /*shadowColor: 'rgba(72,216,191, 0.3)',
                    shadowBlur: 100,*/
                    borderColor: "#F6D06F"
                }
            },
            smooth: true
        }]
    };

    // 使用刚指定的配置项和数据显示图表。
    line_Chart.setOption(line_option);
</script>
</body>
</html>
