<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
    <div class="container" style="min-height: 620px;">
        <ol class="breadcrumb">
            <li><a href="/user/transport"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/financing"><?php echo $this->translate('financing'); ?></a></li>
            <li class="active"><?php echo $this->translate('financingItem'). '：'.$this->financingItem['debtorCustomerName']; ?></li>
        </ol>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body" style="height: 200px; padding: 0;">
                        <div class="row">
                            <div class="col-xm-12" style="padding-top: 30px;"></div>
                        </div>

                        <div class="col-md-5" style="height: 130px;">
                            <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                            <div id="pie_" style="width: 350px;height: 250px;"></div>
                        </div>

                        <div class="col-md-7" style="padding-top: 35px;">
                            <div class="row">
                                <div class="col-md-5">
                                    <p class="form-control-static text-999"><?php echo $this->translate('可融资额度'); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <p class="form-control-static text-666" style="font-weight: bold;"><?php echo number_format($this->financingItem['creditBal'], 2); ?> 元</p>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-5">
                                    <p class="form-control-static text-999"><?php echo $this->translate('总额度'); ?></p>
                                </div>
                                <div class="col-md-6">
                                    <p class="form-control-static text-666" style="font-weight: bold;"><?php echo number_format($this->financingItem['creditLimit'], 2); ?> 元</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body" style="padding: 0;">
                        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                        <div id="line_" style="height: 200px;" ></div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('项目进度'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="loanStatus" data-value="all"><?php echo $this->translate('financingAll'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="loanStatus" data-value="12"><?php echo $this->translate('financingRepayment'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="loanStatus" data-value="11"><?php echo $this->translate('financingPendingLoan'); ?></button>
                                <button type="button" class="btn btn-default" data-type="loanStatus" data-value="05"><?php echo $this->translate('financingDone'); ?></button>
                                <button type="button" class="btn btn-default" data-type="loanStatus" data-value="01"><?php echo $this->translate('financingPending'); ?></button>
                                <input type="hidden" name="loanStatus" id="loanStatus" value="all">
                                <input type="hidden" name="financingID" id="financingID" value="<?php echo $this->financingItem['financingID']; ?>">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default" style="margin-bottom: 70px">
            <div class="panel-body" >
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-default navbar-fixed-bottom">
    <div class="container">
        <form class="form-horizontal" action="/user/financing/financing-repayments" id="repayment_form" onsubmit="return checkSelections();" method="post">
            <div class="form-group" style="margin-top: 10px;">
                <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('应还金额'); ?></label>
                <div class="col-sm-3">
                    <p class="form-control-static"><span id="paymentAmount_static">0</span> 元</p>
                    <input type="hidden" name="financingID" value="<?php echo $this->financingItem['financingID']; ?>">
                    <input type="hidden" name="paymentAmount" id="paymentAmount" value="0">
                    <input type="hidden" name="actualFinancingAmount" id="actualFinancingAmount" value="0">
                    <input type="hidden" name="actualInterest" id="actualInterest" value="0">
                    <input type="hidden" name="actualServiceCharge" id="actualServiceCharge" value="0">
                    <input type="hidden" name="explanationStr" id="explanationStr" value="">
                </div>

                <div class="col-sm-7"></div>

                <button type="submit" class="btn btn-primary"><?php echo $this->translate('批量还款'); ?></button>
            </div>
        </form>
    </div>
</nav>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>',
        $resultListTable = $('#resultListTable');

    $().ready(function() {

    });

    $(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        let layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            let laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        let dataDictQuery = '/user/common/dict-ajax';
        let dictCode = ["LOAN_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $resultListTable.bootstrapTable({
                    classes: 'table table-no-bordered',
                    checkboxHeader: true,
                    method: 'post',
                    clickToSelect: true,
                    // 对a和button标签忽略clickToSelect事件
                    ignoreClickToSelectOn: function (element) {
                        return $.inArray(element.tagName, ['A', 'BUTTON']);
                    },
                    url: '/user/financing/financing-loan-list-ajax',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    queryParams: function(params) {
                        return {
                            limit: 120,
                            skip: 0,
                            financingID: $("#financingID").val(),
                            loanStatus: $("#loanStatus").val()
                        };
                    },
                    onLoadSuccess: function() {
                        let $resultList = $resultListTable.bootstrapTable('getData');
                        $.each($resultList, function (i, loan) {
                            if (loan['loanStatus'] === '02') {
                                $resultListTable.bootstrapTable('check', i);
                            }
                        });

                        refreshPaymentAmount($resultListTable);
                    },
                    onCheck: function() {
                        refreshPaymentAmount($resultListTable);
                    },
                    onUncheck:function(){
                        refreshPaymentAmount($resultListTable);
                    },
                    onCheckAll: function () {
                        refreshPaymentAmount($resultListTable);
                    },
                    onUncheckAll: function () {
                        refreshPaymentAmount($resultListTable);
                    },
                    onClickRow:function(row, $element, field) {
                        // alert(JSON.stringify(row));
                    },
                    columns: [{
                        halign: 'center',
                        checkbox: true,
                        formatter: function (value, row, index) {
                            if (row.loanStatus !== '02') {
                                return {
                                    disabled: true
                                }
                            }
                            return value
                        }
                    }, {
                        field: 'loanNo',
                        title: '<?php echo $this->translate("项目编号"); ?>',
                        width: 220,
                        sortable: true,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }

                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            return '<a href="' + href + '" target="_blank">' + value + '</a>';
                        }
                    }, {
                        field: 'receivableAmount',
                        title: '<?php echo $this->translate("应收账款金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        width: 180,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            let result = row.loanCrnCode + ' ' + formatCurrency(value, 2);

                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            return '<a href="' + href + '" target="_blank">' + result + '</a>';
                        }
                    }, {
                        field: 'loanAmount',
                        title: '<?php echo $this->translate("目标融资金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        sortable: true,
                        width: 180,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            let result = row.loanCrnCode + ' ' + formatCurrency(value, 2);

                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            return '<a href="' + href + '" target="_blank">' + result + '</a>';
                        }
                    }, {
                        field: 'loanAmount',
                        title: '<?php echo $this->translate("应还金额"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        sortable: true,
                        width: 180,
                        formatter: function (value, row) {
                            let result = row.loanCrnCode + ' ' + formatCurrency(value + row.totalInterest + row.totalServiceCharge, 2);

                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            return '<a href="' + href + '" target="_blank">' + result + '</a>';
                        }
                    }, {
                        field: 'expiryDate',
                        title: '<?php echo $this->translate("届满日"); ?>',
                        valign: 'middle',
                        width: 180,
                        formatter: function (value, row) {
                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            if (value === undefined || value === '' || value === null) {
                                if (row.applyExpiryDate === undefined || row.applyExpiryDate === '' || row.applyExpiryDate === null) {
                                    return "";
                                } else {
                                    return '<a href="' + href + '" target="_blank">' + new Date(row.applyExpiryDate).format("yyyy-MM-dd") + '</a>';
                                }
                            } else {
                                return '<a href="' + href + '" target="_blank">' + new Date(value).format("yyyy-MM-dd") + '</a>';
                            }
                        }
                    }, {
                        field: 'loanStatus',
                        title: '<?php echo $this->translate("项目状态"); ?>',
                        valign: 'middle',
                        width: 120,
                        formatter: function (value, row) {
                            let loanStatus = row.loanStatus;
                            if (loanStatus === undefined || loanStatus === '' || loanStatus === null) {
                                loanStatus = "-";
                            }
                            let result = '';
                            let data = $.data(dataDict, 'dataDict');

                            $.each(data, function (key, item) {
                                if (key === 'LOAN_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === loanStatus) {
                                            result = dict.name;
                                        }
                                    });
                                }
                            });

                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let href = "/user/financing/financing-loan-view?"+resultEnCode;

                            return '<a href="' + href + '" target="_blank">' + result + '</a>';
                        }
                    }, {
                        title: '<?php echo $this->translate("operation"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            let base = new Base64();
                            let resultEnCode = base.encode(row.loanID);
                            let result = '';
                            if (row.loanStatus && row.loanStatus === '02') {
                                let href = "/user/financing/financing-repayment?"+resultEnCode;
                                let str = "<?php echo $this->translate('还款');?>";
                                result += '<a href="' + href + '" style="color: #337ab7">' + str + '</a>';
                            }

                            return result;
                        }
                    }]
                });

                let $titleOptions = $(".title-options");
                $titleOptions.find("button").click(function () {
                    let dataType = $(this).attr("data-type");
                    $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
                    $(this).addClass("btn-warning");

                    $("#" + dataType).val($(this).attr("data-value"));

                    // 刷新 bootstrapTable
                    let refreshOptions = {
                        query:{
                            loanStatus: $("#loanStatus").val()
                        }
                    };
                    $resultListTable.bootstrapTable('refresh', refreshOptions);
                });
            }
        });

        let loanStatisticQuery = '/user/financing/list-loan-statistic-data-ajax';
        $.ajax({
            type: "POST",
            url: loanStatisticQuery,
            data: {
                financingID: $("#financingID").val()
            },
            dataType: "json",
            success: function (data) {
                console.log(data);
                let nowDate = new Date,
                    year_ = [],
                    month_ = [1,2,3,4,5,6,7,8,9,10,11,12],
                    seriesData = [];

                year_.push(nowDate.getFullYear());
                year_.push(nowDate.getFullYear() - 1);

                $.each(year_, function (yearKey, yearItem) {
                    seriesData[yearKey] = [];
                    $.each(month_, function (monthKey, monthItem) {
                        seriesData[yearKey][monthKey] = 0;
                        $.each(data, function (dataKey, dataItem) {
                            if (dataItem.resultMap.year_.value == yearItem && dataItem.resultMap.month_.value == monthItem) {
                                seriesData[yearKey][monthKey] = dataItem.resultMap.totalAmount.value
                            }
                        });
                    });
                });

                let line_option = {
                    tooltip: {
                        trigger: 'axis'
                    },
                    xAxis: [{
                        type: 'category',
                        data: ['1','2','3','4','5','6', '7', '8', '9', '10', '11', '12'],
                        axisLine: {
                            lineStyle: {
                                color: "#999"
                            }
                        }
                    }],
                    yAxis: [{
                        name: '元',
                        type: 'value',
                        splitNumber: 4,
                        splitLine: {
                            lineStyle: {
                                type: 'solid',
                                color: '#DDD'
                            }
                        },
                        axisLine: {
                            show: false,
                            lineStyle: {
                                color: "#333"
                            },
                        },
                        nameTextStyle: {
                            color: '#999',
                            align: 'left',
                            width: '100%'
                        },
                        splitArea: {
                            show: false
                        }
                    }],
                    series: [{
                        name: '今年',
                        type: 'line',
                        data: seriesData[0],
                        lineStyle: {
                            normal: {
                                width: 6,
                                color: {
                                    type: 'linear',

                                    colorStops: [{
                                        offset: 0,
                                        color: '#A9F387' // 0% 处的颜色
                                    }, {
                                        offset: 1,
                                        color: '#48D8BF' // 100% 处的颜色
                                    }],
                                    globalCoord: false // 缺省为 false
                                },
                                shadowColor: 'rgba(72,216,191, 0.3)',
                                shadowBlur: 10,
                                shadowOffsetY: 20
                            }
                        },
                        itemStyle: {
                            normal: {
                                color: '#fff',
                                borderWidth: 10,
                                /*shadowColor: 'rgba(72,216,191, 0.3)',
                                shadowBlur: 100,*/
                                borderColor: "#A9F387"
                            }
                        },
                        smooth: true
                    }, {
                        name: '去年',
                        type: 'line',
                        data: seriesData[1],
                        lineStyle: {
                            normal: {
                                width: 6,
                                color: {
                                    type: 'linear',

                                    colorStops: [{
                                        offset: 0,
                                        color: '#F6D06F' // 0% 处的颜色
                                    }, {
                                        offset: 1,
                                        color: '#F9A589' // 100% 处的颜色
                                    }],
                                    globalCoord: false // 缺省为 false
                                },
                                shadowColor: 'rgba(246,208,111, 0.3)',
                                shadowBlur: 10,
                                shadowOffsetY: 20
                            }
                        },
                        itemStyle: {
                            normal: {
                                color: '#fff',
                                borderWidth: 10,
                                /*shadowColor: 'rgba(72,216,191, 0.3)',
                                shadowBlur: 100,*/
                                borderColor: "#F6D06F"
                            }
                        },
                        smooth: true
                    }]
                };

                // 使用刚指定的配置项和数据显示图表。
                line_Chart.setOption(line_option);
            }
        });
    });

    function refreshPaymentAmount($resultListTable) {
        let $allSelectionsData = $resultListTable.bootstrapTable('getAllSelections'),
            allSelectionsPaymentAmount = 0,
            allSelectionsActualFinancingAmount = 0,
            allSelectionsActualInterest = 0,
            allSelectionsActualServiceCharge = 0,
            $repayment_form = $("#repayment_form");

        // 删除所有itemID元素
        $(".paymentLoanIDs").remove();
        $.each($allSelectionsData, function(i, val) { //两个参数，第一个参数表示遍历的数组的下标，第二个参数表示下标对应的值
            allSelectionsPaymentAmount += val.writeoffBalAmount + val.writeoffBalInterest + val.writeoffServiceBalCharge;
            allSelectionsActualFinancingAmount += val.writeoffBalAmount;
            allSelectionsActualInterest += val.writeoffBalInterest;
            allSelectionsActualServiceCharge += val.writeoffServiceBalCharge;
            $repayment_form.append($("<input type='hidden' name='paymentLoanIDs[]' value='" + val.loanID + "' class='paymentLoanIDs' />"));
        });

        $("#paymentAmount_static").html(formatCurrency(allSelectionsPaymentAmount, 2));
        $("#paymentAmount").val(allSelectionsPaymentAmount);
        $("#actualFinancingAmount").val(allSelectionsActualFinancingAmount);
        $("#actualInterest").val(allSelectionsActualInterest);
        $("#actualServiceCharge").val(allSelectionsActualServiceCharge);
        if ($resultListTable && $allSelectionsData && $resultListTable.length > 0 && $allSelectionsData.length > 0) {
            // console.log($allSelectionsData)
            // console.log($allSelectionsData[0].loanNo);
            $("#explanationStr").val($allSelectionsData[0].loanNo);
        }
    }

    function checkSelections() {
        let $allSelectionsData = $resultListTable.bootstrapTable('getAllSelections');
        if ($allSelectionsData.length === 0) {
            return false;
        } else {
            return true;
        }
    }

    // 基于准备好的dom，初始化echarts实例
    let pie_Chart = echarts.init(document.getElementById('pie_'));
    let line_Chart = echarts.init(document.getElementById('line_'));

    let pie_data = {
        value: <?php echo intval($this->financingItem['creditBal'] / $this->financingItem['creditLimit'] * 100); ?>,
        name: '完成率'
    };

    // 指定图表的配置项和数据
    let pie_option = {
        title: [{
            id: 'ti',
            text: pie_data.value + '%',
            x: '29%',
            y: '38%',
            textAlign: 'center',
            textStyle: {
                // fontWeight: 'bold',
                fontSize: 22,
                color: '#1A3B4C'
            }
        }, {
            id: 'ti2',
            text: '可用额度',
            x: '29%',
            y: '30%',
            textAlign: 'center',
            textStyle: {
                // fontWeight: 'bold',
                fontSize: 12,
                color: '#1A3B4C'
            }
        }],
        data: [{
            name: pie_data.name,
        }],


        series: [{ // 主圆环
            name: pie_data.name,
            type: 'pie',
            radius: ['40%', '70%'], // 饼图的半径，数组的第一项是内半径，第二项是外半径。
            startAngle: 180,    // 起始角度，支持范围[0, 360]。
            center: ['30%', '42%'],
            top: 0,
            color: [{
                type: 'linear',
                x: 1,
                y: 0,
                x2: 0,
                y2: 0,
                colorStops: [{
                    offset: 0,
                    color: 'rgba(47,172,234,1)' // 0% 处的颜色
                }, {
                    offset: 1,
                    color: 'rgba(47,172,234,.1)' // 100% 处的颜色
                }]
            }, 'transparent'],
            hoverAnimation: true,
            legendHoverLink: false,
            z: 10,
            labelLine: {
                normal: {
                    show: false
                }
            },
            data: [{
                value: 50 * pie_data.value / 100
            }, {
                value: 100 - (50 * pie_data.value / 100)
            }]
        }, { // 背景圆环
            name: '',
            type: 'pie',
            radius: ['40%', '60%'],
            center: ['30%', '42%'],
            silent: true,
            startAngle: 180,
            labelLine: {
                normal: {
                    show: false
                }
            },
            z: 5,
            data: [{
                value: 50,
                itemStyle: {
                    color: '#1A3B4C'
                }
            }, {
                value: 50,
                itemStyle: {
                    color: 'transparent'
                }
            }]
        }]
    };
    // 使用刚指定的配置项和数据显示图表。
    pie_Chart.setOption(pie_option);
</script>
</body>
</html>
