<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.16.0-dist/extensions/group-by-v2/bootstrap-table-group-by.css" rel="stylesheet">
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>


<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/freight/freight-loan-index"><?php echo $this->translate('freightLoanFinanceItem'); ?></a></li>
            <li><a href="/user/freight/freight-loan-item-index"><?php echo $this->translate('freightLoanApplyList'); ?>：德邦快递</a></li>
            <li class="active"><?php echo $this->translate('freightLoanItemView'); ?></li>
        </ol>

        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-primary">
                    <!-- Default panel contents -->
                    <div class="panel-heading">FL042019112900001<span class="pull-right">共400运单 <i class="layui-icon layui-icon-about" style="cursor: pointer;" data-toggle="modal" data-target="#freightModal" data-loan-id=""></i></span></div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('债务方'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666">XXXXXXX有限公司</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('应收账款金额'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666">3,487,688.19  元</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('可融资金额'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666">3,487,688.19  元</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('计划放款日'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666">2020年2月6日</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('届满日'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666">2020年2月6日</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-primary">
                    <!-- Default panel contents -->
                    <div class="panel-heading">项目利率<span class="pull-right"><i class="layui-icon layui-icon-about"></i></span></div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('融资（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666">0.03 %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('逾期（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666">0.08 %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('宽限期（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666">0.03 %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('服务费（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666">0.0002 %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('预期总费用'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666">10,288.31 元</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="panel panel-primary" style="height: 242px;">
                    <!-- Default panel contents -->
                    <div class="panel-heading">待还金额<span class="pull-right">2020年1月12日</i></span></div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999" style="margin-top: 47px;"><?php echo $this->translate('距还款'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666"><span class="text-danger span-font-size-68">24</span> 天</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('预期应还'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-danger">3,488,926.7 元</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-warning">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('项目文件'); ?></div>

            <div class="panel-body">

            </div>
        </div>

        <div class="panel panel-danger">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('放款情况'); ?></div>

            <!-- Table -->
            <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                <thead>
                <tr>
                    <th data-field="id"><?php echo $this->translate('放款编号'); ?></th>
                    <th data-field="name"><?php echo $this->translate('放款日期'); ?></th>
                    <th data-field="name"><?php echo $this->translate('放款金额'); ?></th>
                    <th data-field="name"><?php echo $this->translate('利息'); ?></th>
                    <th data-field="name"><?php echo $this->translate('宽限期利息'); ?></th>
                    <th data-field="name"><?php echo $this->translate('逾期利息'); ?></th>
                    <th data-field="name"><?php echo $this->translate('利息合计'); ?></th>
                    <th data-field="name"><?php echo $this->translate('服务费'); ?></th>
                    <th data-field="name"><?php echo $this->translate('未还金额'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>LR01201912290001</td>
                    <td>2020年</td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="panel panel-success">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('还款情况'); ?></div>

            <!-- Table -->
            <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                <thead>
                <tr>
                    <th data-field="id"><?php echo $this->translate('还款编号'); ?></th>
                    <th data-field="name"><?php echo $this->translate('还款日期'); ?></th>
                    <th data-field="name"><?php echo $this->translate('应还金额'); ?></th>
                    <th data-field="name"><?php echo $this->translate('还款金额'); ?></th>
                    <th data-field="name"><?php echo $this->translate('已还本金'); ?></th>
                    <th data-field="name"><?php echo $this->translate('已还利息'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>LR01201912290001</td>
                    <td>2020年</td>
                </tr>
                </tbody>
            </table>
        </div>
	</div>
</div>

<!-- Modal 运单明细 -->
<div class="modal fade" id="freightModal" tabindex="-1" role="dialog" aria-labelledby="freightLabel">
    <div class="modal-dialog modal-lg" role="document" style="width: 1080px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
<!--                <h4 class="modal-title">--><?php //echo $this->translate('factoringInterestDetail'); ?><!--</h4>-->
            </div>

            <div class="modal-body">
                <table id="freightResultListTable"></table>
            </div>
        </div>
    </div>
</div>

<!-- PDF预览 -->
<div id="signViewDiv" style="display: none; background-color: #F6F6F6;">
    <div class="download-button">下载</div>
    <div class="pdfDoc" style="padding-left:50px;">
        <div id="pdfPageBox">
        </div>
    </div>
</div>


<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- pdf -->
<script type="text/javascript" src="/ky/pdf/pdf.js"></script>
<script type="text/javascript" src="/ky/pdf/pdf.worker.js"></script>
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script src="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/extensions/group-by-v2/bootstrap-table-group-by.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/locale/bootstrap-table-zh-CN.min.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $("#freightModal").on('show.bs.modal', function (e) {
            let triggered = $(e.relatedTarget),
                loanID = triggered.data("loan-id"),
                $resultListTable = $('#freightResultListTable');

            let options = {
                query:{
                    loanID: loanID
                }
            };
            $resultListTable.bootstrapTable('refresh', options);

            $resultListTable.bootstrapTable({
                url: '/user/settle/payment-trading-list-ajax',
                method: 'post',
                // showRefresh: true,
                // search: true,
                pagination: true,
                // onlyInfoPagination: true,
                classes: 'table table-hover',
                sidePagination: 'server',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                queryParams: function(params) {
                    return {
                        loanID: loanID
                    };
                },
                columns: [{
                    field: 'transNo',
                    title: '<?php echo $this->translate("运单编号"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'subject',
                    title: '<?php echo $this->translate("运单名称"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'transNo',
                    title: '<?php echo $this->translate("保险单号"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'totalAmount',
                    title: '<?php echo $this->translate("运单总额"); ?>',
                    align: 'right',
                    halign: 'center',
                    valign: 'middle',
                    width: 140,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "-";
                        }
                        return row.crnCode + ' ' + formatCurrency(value, 2);
                    }
                }, {
                    field: 'oppCustomerName',
                    title: '<?php echo $this->translate("承运人"); ?>',
                    valign: 'middle',
                    width: 300,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "-";
                        }

                        return value;
                    }
                }]
            });
        });
	});

    // *************************** PDF Sign View ********************************
    PDFJS.workerSrc = '/ky/pdf/pdf.worker.js';

    let pdfDoc = null,
        pageNum = 1,
        pageRendering = false,
        pageNumPending = null,
        scale = 1.5,
        $downLoadBtn = $(".download-button");

    function renderPage(num, id) {
        let canvas = document.getElementById(id);
        let ctx = canvas.getContext('2d');
        pageRendering = true;
        pdfDoc.getPage(num).then(function(page) {
            let viewport = page.getViewport(scale);
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            let renderContext = {
                canvasContext: ctx,
                viewport: viewport
            };
            let renderTask = page.render(renderContext);

            renderTask.promise.then(function() {
                pageRendering = false;
                if (pageNumPending !== null) {
                    renderPage(pageNumPending);
                    pageNumPending = null;
                }
            });
        });
    }

    function queueRenderPage(num) {
        if (pageRendering) {
            pageNumPending = num;
        } else {
            renderPage(num);
        }
    }

    function onPrevPage() {
        if (pageNum <= 1) {
            return;
        }
        pageNum--;
        queueRenderPage(pageNum);
    }

    function onNextPage() {
        if (pageNum >= pdfDoc.numPages) {
            return;
        }
        pageNum++;
        queueRenderPage(pageNum);
    }

    function initPdfView(pdfUrl, obj) {
        $("#pdfPageBox").html("");
        PDFJS.getDocument(pdfUrl).then(function(pdfDoc_) {
            pdfDoc = pdfDoc_;
            //document.getElementById('page_count').textContent = pdfDoc.numPages;
            for (let i=1;i<=pdfDoc.numPages;i++){
                let canvasDiv = $("<div style=\"padding-top:10px;padding-bottom:10px;\"></div>");
                let pageNum = $("<div style=\"background-color: #999999;position:absolute;float: left;height:30px;width:60px;text-align: center;line-height: 30px;color:#ffffff;opacity: 0.6;\">"+i+"/"+pdfDoc.numPages+"</div>");
                let canvas = $("<canvas></canvas>").attr("id", "the-canvas_"+i);
                canvasDiv.append(pageNum);
                canvasDiv.append(canvas);
                $("#pdfPageBox").append(canvasDiv);
                renderPage(i, "the-canvas_"+i);
            }
        });

        let signTitle = "<?php echo $this->translate('pdfView');?>";
        layer.open({
            type: 1,	//Page层类型
            area: ['1150px', '100%'],
            title: signTitle,
            shadeClose: true,
            shade: 0.6,	//遮罩透明度
            // anim: 1,	//0-6的动画形式，-1不开启
            scrollbar: false,
            content: $("#signViewDiv")
        });

        $downLoadBtn.attr("contractID_", obj.id);
    }

    $downLoadBtn.bind("click",function(){
        let contractID_ = $(this).attr("contractID_");
        window.location.href = $("#contractAttachUrl_" + contractID_).val();
    });
</script>
</body>
</html>
