<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
    <title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/finance/finance.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-table-1.16.0-dist/extensions/group-by-v2/bootstrap-table-group-by.css" rel="stylesheet">
    <!-- fancybox -->
    <link href="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>


<div class="container-fluid index-body">
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="/user/transport"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/financing"><?php echo $this->translate('financing'); ?></a></li>
            <li><a href="/user/financing/financing-item?<?php echo base64_encode($this->financingLoan['financing']['financingID'])?>"><?php echo $this->translate('financingItem'); ?>：<?php echo $this->financingLoan['financing']['debtorCustomerName']; ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoanItemView'); ?></li>
        </ol>

        <div class="row">
            <div class="col-md-5">
                <div class="panel panel-primary" style="height: 242px;">
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $this->financingLoan['loanNo']; ?><span class="pull-right">共400运单 <i class="layui-icon layui-icon-about" style="cursor: pointer;" data-toggle="modal" data-target="#freightModal" data-loan-id=""></i></span></div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('债务方'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666"><?php echo $this->financingLoan['financing']['debtorCustomerName']; ?></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('应收账款金额'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666"><?php echo number_format($this->financingLoan['receivableAmount'], 2); ?>  元</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('可融资金额'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666"><?php echo number_format($this->financingLoan['maxLoanAmount'], 2); ?>  元</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('计划放款日'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666"><?php echo date("Y-m-d", strtotime($this->financingLoan['applyLoanDate'])); ?></p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('计划届满日'); ?></p>
                            </div>
                            <div class="col-md-8">
                                <p class="form-control-static text-666"><?php echo date("Y-m-d", strtotime($this->financingLoan['applyExpiryDate'])); ?></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-primary" style="height: 242px;">
                    <!-- Default panel contents -->
                    <div class="panel-heading">方案利率/费率<span class="pull-right"><i class="layui-icon layui-icon-about"></i></span></div>

                    <div class="panel-body">
                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('融资（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666"><?php echo $this->financingLoan['financing']['minInterestPercent'] * 100; ?> %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('宽限期（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666"><?php echo $this->financingLoan['financing']['graceInterestPercent'] * 100; ?> %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('逾期（日）利率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666"><?php echo $this->financingLoan['financing']['overdueInterestPercent'] * 100; ?> %</p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <p class="form-control-static text-999"><?php echo $this->translate('服务（日）费率'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-666"><?php echo $this->financingLoan['financing']['serviceChargePercent'] * 100; ?> %</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-3">
                <div class="panel panel-primary" style="height: 242px;">
                    <!-- Default panel contents -->
                    <div class="panel-heading">还款日期
                        <span class="pull-right">
                            <i class="layui-icon layui-icon-about"></i>
                        </span>
                    </div>

                    <div class="panel-body">
                        <?php if ($this->financingLoan['loanStatus'] == '03'): ?>
                            <div class="row">
                                <div class="col-md-4">
                                    <p class="form-control-static text-999" style="margin-top: 27px;"></p>
                                </div>
                                <div class="col-md-6">
                                    <p class="form-control-static text-666"><span class="text-danger span-font-size-28"><?php echo $this->translate('已完成'); ?></span></p>
                                </div>
                            </div>
                        <?php else: ?>
                            <?php if (round((strtotime($this->financingLoan['expiryDate']) - strtotime(date("Y-m-d"))) / 86400) > 0): ?>
                                <div class="row">
                                    <div class="col-md-4">
                                        <p class="form-control-static text-999" style="margin-top: 47px;"><?php echo $this->translate('距还款'); ?></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="form-control-static text-666"><span class="text-danger span-font-size-68"><?php echo round((strtotime($this->financingLoan['expiryDate']) - strtotime(date("Y-m-d"))) / 86400); ?></span> 天</p>
                                    </div>
                                </div>
                            <?php elseif (round((strtotime($this->financingLoan['expiryDate'] .' +'. $this->financingLoan['financing']['gracePeriod'] .' day') - strtotime(date("Y-m-d"))) / 86400) > 0): ?>
                                <div class="row">
                                    <div class="col-md-4">
                                        <p class="form-control-static text-999" style="margin-top: 47px;"><?php echo $this->translate('宽限期内'); ?></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="form-control-static text-666"><span class="text-danger span-font-size-68"><?php echo round((strtotime($this->financingLoan['expiryDate'] .' +'. $this->financingLoan['financing']['gracePeriod'] .' day') - strtotime(date("Y-m-d"))) / 86400); ?></span> 天</p>
                                    </div>
                                </div>
                            <?php else: ?>
                                <div class="row">
                                    <div class="col-md-4">
                                        <p class="form-control-static text-999" style="margin-top: 47px;"><?php echo $this->translate('逾期'); ?></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p class="form-control-static text-666"><span class="text-danger span-font-size-68"><?php echo round((strtotime(date("Y-m-d")) - strtotime($this->financingLoan['expiryDate'] .' +'. $this->financingLoan['financing']['gracePeriod'] .' day')) / 86400); ?></span> 天</p>
                                    </div>
                                </div>
                            <?php endif; ?>
                        <?php endif; ?>

                        <div class="row">
                            <div class="col-md-4">
                                <p class="form-control-static text-999"><?php echo $this->translate('还款日'); ?></p>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-danger">
                                    <?php if ($this->financingLoan['expiryDate']): ?>
                                        <?php if (round((strtotime($this->financingLoan['expiryDate']) - strtotime(date("Y-m-d"))) / 86400) > 0): ?>
                                            <?php echo date("Y-m-d", strtotime($this->financingLoan['expiryDate'])); ?>
                                        <?php else: ?>
                                            <?php echo date("Y-m-d", strtotime($this->financingLoan['expiryDate'] .' +'. $this->financingLoan['financing']['gracePeriod'] .' day')); ?>
                                        <?php endif;?>
                                    <?php else: ?>
                                        <?php echo date("Y-m-d", strtotime($this->financingLoan['applyExpiryDate'])); ?>
                                    <?php endif;?>
                                </p>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-4">
                                <?php if ($this->financingLoan['loanStatus'] == '03'): ?>
                                    <p class="form-control-static text-999"><?php echo $this->translate('还款'); ?></p>
                                <?php else: ?>
                                    <p class="form-control-static text-999"><?php echo $this->translate('预期应还'); ?></p>
                                <?php endif; ?>
                            </div>
                            <div class="col-md-6">
                                <p class="form-control-static text-danger"><?php echo number_format($this->financingLoan['loanAmount'] + $this->financingLoan['totalInterest'] + $this->financingLoan['totalServiceCharge'], 2); ?> 元</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-warning">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('项目文件'); ?></div>

            <div class="panel-body">
                <div class="col-xs-12 text-muted">
                    <?php if (!empty($this->contractList)):?>
                        <?php echo $this->ShowOrderContract4Factoring($this->contractList, $this->accountID); ?>
                    <?php else: ?>
                        <label>暂无数据！</label>
                    <?php endif; ?>
                </div>
            </div>
        </div>

        <div class="panel panel-danger">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('放款情况'); ?></div>

            <!-- Table -->
            <table data-classes="table" class="table">
                <thead>
                <tr>
                    <th><?php echo $this->translate('放款编号'); ?></th>
                    <th><?php echo $this->translate('放款日期'); ?></th>
                    <th><?php echo $this->translate('放款金额'); ?></th>
                    <th><?php echo $this->translate('利息'); ?></th>
                    <th><?php echo $this->translate('宽限期利息'); ?></th>
                    <th><?php echo $this->translate('逾期利息'); ?></th>
                    <th><?php echo $this->translate('利息合计'); ?></th>
                    <th><?php echo $this->translate('服务费'); ?></th>
                    <th><?php echo $this->translate('未还金额'); ?></th>
                    <th><?php echo $this->translate('状态'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><?php echo $this->financingLoan['loanNo']; ?></td>
                    <td><?php if ($this->financingLoan['loanDate']) { echo date("Y-m-d", strtotime($this->financingLoan['loanDate'])); } ?></td>
                    <td><?php echo number_format($this->financingLoan['loanAmount'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['totalGeneralInterest'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['totalGraceInterest'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['totalOverdueInterest'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['totalInterest'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['totalServiceCharge'], 2); ?> 元</td>
                    <td><?php echo number_format($this->financingLoan['writeoffBalInterest'] + $this->financingLoan['writeoffBalAmount'] + $this->financingLoan['writeoffServiceBalCharge'], 2); ?> 元</td>
                    <td><?php echo $this->ShowDictionaryTo("LOAN_STATUS", $this->userLangCode, $this->dic_Setting['LOAN_STATUS'], $this->financingLoan['loanStatus']); ?></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="panel panel-success">
            <!-- Default panel contents -->
            <div class="panel-heading">
                <div class="row">
                    <div class="col-sm-8">
                        <?php echo $this->translate('还款情况'); ?>
                    </div>
                    <div class="col-sm-4">
                        <p class="text-right">
                            <?php if (!empty($this->financingLoan) && $this->financingLoan['loanStatus'] == '02' && $this->isRepayment == true): ?>
                                <a class="btn btn-warning btn-xs"  href="/user/financing/financing-repayment?<?php echo base64_encode($this->financingLoan['loanID']);?>">去还款</a>
                            <?php endif; ?>
                        </p>
                    </div>
                </div>
            </div>

            <!-- Table -->
            <table data-classes="table" class="table">
                <thead>
                <tr>
                    <th><?php echo $this->translate('还款编号'); ?></th>
                    <th><?php echo $this->translate('还款日期'); ?></th>
                    <th><?php echo $this->translate('还款金额'); ?></th>
                    <th><?php echo $this->translate('已还本金'); ?></th>
                    <th><?php echo $this->translate('已还利息'); ?></th>
                    <th><?php echo $this->translate('支付服务费'); ?></th>
                    <th><?php echo $this->translate('状态'); ?></th>
                </tr>
                </thead>
                <tbody>
                <?php if (empty($this->financingLoan['financingRepaymentList'])): ?>
                    <tr>
                        <td colspan="9" class="text-center">暂无还款记录</td>
                    </tr>
                <?php else: ?>
                    <?php foreach ($this->financingLoan['financingRepaymentList'] as $financingRepayment): ?>
                        <tr>
                            <td><?php echo $financingRepayment['repaymentNo']; ?></td>
                            <td><?php echo date("Y-m-d", strtotime($financingRepayment['repaymentDate'])); ?></td>
                            <td><?php echo number_format($financingRepayment['repaymentTotalAmount'], 2); ?> 元</td>
                            <td><?php echo number_format($financingRepayment['writeoffPrincipalAmount'], 2); ?> 元</td>
                            <td><?php echo number_format($financingRepayment['writeoffInterestAmount'], 2); ?> 元</td>
                            <td><?php echo number_format($financingRepayment['writeoffServiceCharge'], 2); ?> 元</td>
                            <td><?php echo $this->ShowDictionaryTo("REPAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['REPAYMENT_STATUS'], $financingRepayment['repaymentStatus']); ?></td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Modal 运单明细 -->
<div class="modal fade" id="freightModal" tabindex="-1" role="dialog" aria-labelledby="freightLabel">
    <div class="modal-dialog modal-lg" role="document" style="width: 1080px !important;">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <!--                <h4 class="modal-title">--><?php //echo $this->translate('factoringInterestDetail'); ?><!--</h4>-->
            </div>

            <div class="modal-body">
                <table id="freightResultListTable"></table>
            </div>
        </div>
    </div>
</div>

<!--PDF预览-->
<div id="signViewDiv" style="display: none; background-color: #F6F6F6;">
    <div class="sign-button">企业签署</div>
    <div class="person-sign-button">个人签署</div>
    <div class="download-button">下载</div>
    <div class="pdfDoc" style="padding-left:50px;">
        <div id="pdfPageBox">
        </div>
    </div>
</div>
<!--非网签-->
<div id="signViewNoEContractDiv" class="layui-form" style="display: none;">
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div style="margin-top: 20px;"></div>

        <div class="layui-form-item" style="margin-left: 28px;">
            <div style="text-align: left;">
                <label class="layui-form-label" style="width: 400px;text-align: left;"><?php echo $this->translate('contractUPInfo'); ?></label>
            </div>
        </div>

        <div class="layui-form-item" style="margin-bottom: -5px;margin-top: -15px;margin-left: 28px;margin-right: 28px;">
            <div style="text-align: left;">
                <table class="layui-table" id="demo" lay-filter="test">
                    <colgroup>
                        <col width="470">
                        <col width="150">
                        <col>
                    </colgroup>
                    <thead>
                    <tr>
                        <th>合同列表</th>
                        <th><?php echo $this->translate('type'); ?></th>
                        <th style="text-align:center"><?php echo $this->translate('operation'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="layui-form-item" style="margin-left: 28px; margin-top: 50px; width: 600px;">
            <div class="layui-form-label" style="width: 420px;">
                <div class="yyzz_box clearfix" style="width: 600px;">
                    <p class="zzname" style="width: 600px; font-weight:bold;"><?php echo $this->translate('contractUP'); ?><!--合同相关附件上传--></p>
                    <?php if ($this->vestut == 1) {
                        echo $this->ShowWebuploader($this->goods['attachmentList'], $this->biz_Setting['ORDER'], $this->attach_Setting['CRIM'], "0", null);
                    } ?>
                </div>
            </div>
        </div>


        <div style="height: 12px"></div>
        <div class="et-auth-row">
            <button class="layui-btn" id="signNoEContractConfirmBtn"><?php echo $this->translate('signing'); ?></button>
        </div>
    </div>
</div>

<!--签署-->
<div id="doSignPDFLayDiv" class="layui-form" style="display: none;">
    <div class="et-auth-error" style="display: none;"></div>
    <div class="et-auth-content">
        <div style="margin-top: 20px;"></div>

        <div class="signContent">
            <div class="layui-form-item" style="margin-left: 28px;">
                <div style="text-align: left;">
                    <label class="layui-form-label" style="width: 180px;text-align: left;"><?php echo $this->translate('signInfo'); ?></label>
                </div>
            </div>

            <div class="layui-form-item" style="margin-bottom: -5px;margin-top: 25px;margin-left: 28px;">
                <div style="text-align: left;">
                    <label class="layui-form-label" style="width: 180px;text-align: left;"><b><?php echo $this->translate('signAuthType'); ?></b></label>
                </div>
            </div>

            <div class="layui-form-item" style="margin-left: 28px;">
                <div class="layui-form-label" style="width: 420px;">
                    <input type="text" id="signMobileInput" name="signMobileInput" lay-verify="signMobileInput" autocomplete="off" class="layui-input" readonly="readonly">
                </div>
            </div>

            <div class="layui-form-item" style="margin-left: 28px;">
                <div class="layui-form-label" style="width: 250px;">
                    <input type="text" id="signAuthCode" name="signAuthCode" lay-verify="signAuthCode" autocomplete="off" placeholder="<?php echo $this->translate('signInputAuthCode'); ?>" class="layui-input">
                </div>

                <div class="layui-form-label" style="width: 140px;">
                    <button class="layui-btn layui-btn-fluid" id="signSendAuthCodeBtn"><?php echo $this->translate('signSendAuthCode'); ?></button>
                </div>
            </div>

            <div style="height: 12px"></div>
            <div class="et-auth-row">
                <button class="layui-btn layui-btn-fluid" id="singConfirmBtn" style="width: 85%;"><?php echo $this->translate('confirmed'); ?></button>
            </div>
        </div>

        <div class="jumpInfoContent hidden">
            <div class="layui-form-item" style="margin-bottom: -5px;margin-top: 25px;margin-left: 28px;">
                <div style="text-align: left;">
                    <label class="layui-form-label text-danger" style="width: 450px;text-align: left;"><i class="fas fa-exclamation-triangle"></i> <?php echo $this->translate('未生成有效的企业签署证书，请先完成企业及管理员实名认证。'); ?></label>
                </div>
            </div>
        </div>

        <div class="jumpPersonInfoContent hidden">
            <div class="layui-form-item" style="margin-bottom: -5px;margin-top: 25px;margin-left: 28px;">
                <div style="text-align: left;">
                    <label class="layui-form-label text-danger" style="width: 320px;text-align: left;"><i class="fas fa-exclamation-triangle"></i> <?php echo $this->translate('个人实名认证未完成前不可签署合同。'); ?></label>
                </div>
            </div>
            <div class="layui-form-item" style="margin-bottom: -5px; margin-left: 28px;">
                <div style="text-align: left;">
                    <label class="layui-form-label" style="width: 280px;text-align: left;">
                        <a href="/user/index/profile"><u><strong><?php echo $this->translate('点击此处'); ?></strong></u></a> <?php echo $this->translate('完成个人实名认证。'); ?>
                    </label>
                </div>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<!-- pdf -->
<script type="text/javascript" src="/ky/pdf/pdf.js"></script>
<script type="text/javascript" src="/ky/pdf/pdf.worker.js"></script>
<script type="text/javascript" src="/ky/pdf/signature.js"></script>
<!-- fancybox -->
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/jquery.fancybox.min.js"></script>
<script type="text/javascript" src="/ky/fancybox-3.5.6-dist/fancyboxInit.js"></script>

<script src="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/extensions/group-by-v2/bootstrap-table-group-by.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/locale/bootstrap-table-zh-CN.min.js"></script>

<script type="text/javascript">
    // signatureJS用到的变量
    let signViewTitle = "<?php echo $this->translate('签署合同');?>",
        mobileStr = "<?php echo $this->translate('mobile_phone');?>",
        sendingStr = "<?php echo $this->translate('signAuthCodeSending');?>",
        signSendAuthCodeStr = "<?php echo $this->translate('signSendAuthCode'); ?>",
        signAuthCodeSendingStr = "<?php echo $this->translate('signAuthCodeSending'); ?>",
        signFailStr = "<?php echo $this->translate('signFail');?>",
        signSuccessStr = "<?php echo $this->translate('signSuccess');?>",
        hasIDCertificate = '<?php echo $this->hasIDCertificate;?>',
        contactHasIDCertificate = '<?php echo $this->contactHasIDCertificate;?>';


    $().ready(function() {

    });

    $(function () {
        $("#freightModal").on('show.bs.modal', function (e) {
            let triggered = $(e.relatedTarget),
                loanID = triggered.data("loan-id"),
                $resultListTable = $('#freightResultListTable');

            let options = {
                query:{
                    loanID: loanID
                }
            };
            $resultListTable.bootstrapTable('refresh', options);

            $resultListTable.bootstrapTable({
                url: '/user/settle/payment-trading-list-ajax',
                method: 'post',
                // showRefresh: true,
                // search: true,
                pagination: true,
                // onlyInfoPagination: true,
                classes: 'table table-hover',
                sidePagination: 'server',
                contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                queryParams: function(params) {
                    return {
                        loanID: loanID
                    };
                },
                columns: [{
                    field: 'transNo',
                    title: '<?php echo $this->translate("运单编号"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'subject',
                    title: '<?php echo $this->translate("运单名称"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'transNo',
                    title: '<?php echo $this->translate("保险单号"); ?>',
                    width: 150,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "";
                        }

                        return value;
                    }
                }, {
                    field: 'totalAmount',
                    title: '<?php echo $this->translate("运单总额"); ?>',
                    align: 'right',
                    halign: 'center',
                    valign: 'middle',
                    width: 140,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "-";
                        }
                        return row.crnCode + ' ' + formatCurrency(value, 2);
                    }
                }, {
                    field: 'oppCustomerName',
                    title: '<?php echo $this->translate("承运人"); ?>',
                    valign: 'middle',
                    width: 300,
                    formatter: function (value, row) {
                        if (value === undefined || value === '' || value === null) {
                            value = "-";
                        }

                        return value;
                    }
                }]
            });
        });
    });

</script>
</body>
</html>
