<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoan'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <?php if (!empty($this->resultMsg)): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p><?php echo base64_decode(str_replace(" ", "+", $this->resultMsg)); ?>!</p>
                    </div>
                <?php endif; ?>

                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('freightFinanceStat'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="freightFinanceStat" data-value="all"><?php echo $this->translate('freightFinanceStat_All'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="01"><?php echo $this->translate('freightFinanceStat_Valid'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="02"><?php echo $this->translate('freightFinanceStat_ForCheck'); ?></button>
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="03"><?php echo $this->translate('freightFinanceStat_Invalid'); ?></button>
                                <input type="hidden" name="freightFinanceStat" id="freightFinanceStat" value="all">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-danger">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('德邦快递'); ?></div>

            <!-- Table -->
            <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                <thead>
                <tr>
                    <th data-field="id"><?php echo $this->translate('方案编号'); ?></th>
                    <th data-field="name"><?php echo $this->translate('年份'); ?></th>
                    <th data-field="price"><?php echo $this->translate('总额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                    <th><?php echo $this->translate('已用额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                    <th><?php echo $this->translate('锁定额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已申请未放款的金额"></i></th>
                    <th><?php echo $this->translate('可用额度'); ?></th>
                    <th><?php echo $this->translate('融资日利率'); ?></th>
                    <th><?php echo $this->translate('服务费日费率'); ?></th>
                    <th><?php echo $this->translate('合同'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td><a href="/user/freight/freight-loan-item-index">LR01201912290001</a></td>
                    <td>2020年</td>
                    <td>5,000,000.00 元</td>
                    <td>--  元</td>
                    <td>--  元</td>
                    <td>5,000,000.00 元</td>
                    <td>0.0003 %</td>
                    <td>0.0002 %</td>
                    <td><button type="button" class="btn btn-warning">签署</button></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="panel panel-default">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('德邦快递'); ?></div>

            <!-- Table -->
            <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                <thead>
                <tr>
                    <th data-field="id"><?php echo $this->translate('方案编号'); ?></th>
                    <th data-field="name"><?php echo $this->translate('年份'); ?></th>
                    <th data-field="price"><?php echo $this->translate('总额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                    <th><?php echo $this->translate('已用额度'); ?></th>
                    <th><?php echo $this->translate('锁定额度'); ?></th>
                    <th><?php echo $this->translate('可用额度'); ?></th>
                    <th><?php echo $this->translate('融资日利率'); ?></th>
                    <th><?php echo $this->translate('服务费日费率'); ?></th>
                    <th><?php echo $this->translate('合同'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>LR01201912290001</td>
                    <td>2020年</td>
                    <td>5,000,000.00 元</td>
                    <td>--  元</td>
                    <td>--  元</td>
                    <td>5,000,000.00 元</td>
                    <td>0.0003 %</td>
                    <td>0.0002 %</td>
                    <td><button type="button" class="btn btn-warning">签署</button></td>
                </tr>
                </tbody>
            </table>
        </div>

        <div class="panel panel-danger">
            <!-- Default panel contents -->
            <div class="panel-heading"><?php echo $this->translate('德邦快递'); ?></div>

            <!-- Table -->
            <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                <thead>
                <tr>
                    <th data-field="id"><?php echo $this->translate('方案编号'); ?></th>
                    <th data-field="name"><?php echo $this->translate('年份'); ?></th>
                    <th data-field="price"><?php echo $this->translate('总额度'); ?></th>
                    <th><?php echo $this->translate('已用额度'); ?></th>
                    <th><?php echo $this->translate('锁定额度'); ?></th>
                    <th><?php echo $this->translate('可用额度'); ?></th>
                    <th><?php echo $this->translate('融资日利率'); ?></th>
                    <th><?php echo $this->translate('服务费日费率'); ?></th>
                    <th><?php echo $this->translate('合同'); ?></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>LR01201912290001</td>
                    <td>2020年</td>
                    <td>5,000,000.00 元</td>
                    <td>--  元</td>
                    <td>--  元</td>
                    <td>5,000,000.00 元</td>
                    <td>0.0003 %</td>
                    <td>0.0002 %</td>
                    <td><button type="button" class="btn btn-warning">签署</button></td>
                </tr>
                </tbody>
            </table>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    var dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

            }
        });

        $('[data-toggle="tooltip"]').tooltip();
	});
</script>
</body>
</html>
