<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body" style="min-height: 550px;">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('financing'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <?php if (!empty($this->resultMsg)): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p><?php echo base64_decode(str_replace(" ", "+", $this->resultMsg)); ?>!</p>
                    </div>
                <?php endif; ?>

                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('freightFinanceStat'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn <?php if (empty($this->resultStatus) || $this->resultStatus == 'all') { echo ' btn-warning';} else {echo ' btn-default';}?>" data-type="financingStatus" data-value="all"><?php echo $this->translate('freightFinanceStat_All'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn <?php if ($this->resultStatus == '03') { echo ' btn-warning';} else {echo ' btn-default';}?>" data-type="financingStatus" data-value="03"><?php echo $this->translate('freightFinanceStat_Valid'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn <?php if ($this->resultStatus == '01') { echo ' btn-warning';} else {echo ' btn-default';}?>" data-type="financingStatus" data-value="01"><?php echo $this->translate('freightFinanceStat_ForCheck'); ?></button>
                                <button type="button" class="btn <?php if ($this->resultStatus == '05') { echo ' btn-warning';} else {echo ' btn-default';}?>" data-type="financingStatus" data-value="05"><?php echo $this->translate('freightFinanceStat_Invalid'); ?></button>
                                <form action="/user/financing/index" name="refreshFinancingList" id="refreshFinancingList" method="post">
                                <input type="hidden" name="financingStatus" id="financingStatus" value="all">
                                </form>
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <?php if (empty($this->financingList)):?>
            <div class="panel panel-default">
                <!-- Default panel contents -->
                <div class="panel-heading"></div>

                <!-- Table -->
                <table id="resultListTable" data-toggle="table" data-classes="table" class="table">
                    <thead>
                    <tr>
                        <th data-field="id"><?php echo $this->translate('方案编号'); ?></th>
                        <th data-field="name"><?php echo $this->translate('年份'); ?></th>
                        <th data-field="price"><?php echo $this->translate('总额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                        <th><?php echo $this->translate('已用额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                        <th><?php echo $this->translate('锁定额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已申请未放款的金额"></i></th>
                        <th><?php echo $this->translate('可用额度'); ?></th>
                        <th><?php echo $this->translate('融资日利率'); ?></th>
                        <th><?php echo $this->translate('服务费日费率'); ?></th>
                        <th><?php echo $this->translate('合同'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td colspan="9"><?php echo $this->translate("noData"); ?></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <?php foreach ($this->financingList as $financing): ?>
                <?php if (strtotime($financing['expiryDate']) < strtotime(date('Y-m-d'))): ?>
                <div class="panel panel-default">
                <?php else: ?>
                <div class="panel panel-danger">
                <?php endif; ?>
                    <!-- Default panel contents -->
                    <div class="panel-heading"><?php echo $financing['debtorCustomerName']; ?></div>

                    <!-- Table -->
                    <table data-toggle="table" data-classes="table" class="table">
                        <thead>
                        <tr>
                            <th><?php echo $this->translate('方案编号'); ?></th>
                            <th><?php echo $this->translate('有效期'); ?></th>
                            <th><?php echo $this->translate('总额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                            <th><?php echo $this->translate('已用额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已放款且未还款的金额"></i></th>
                            <th><?php echo $this->translate('锁定额度'); ?> <i class="layui-icon layui-icon-about" data-toggle="tooltip" data-placement="top" title="已申请未放款的金额"></i></th>
                            <th><?php echo $this->translate('可用额度'); ?></th>
                            <th><?php echo $this->translate('融资日利率'); ?></th>
                            <th><?php echo $this->translate('服务费日费率'); ?></th>
                            <th><?php echo $this->translate('合同'); ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><a href="<?php echo '/user/financing/financing-item?'. base64_encode($financing['financingID'])?>"><?php echo $financing['financingNo']; ?></a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo date("Y-m", strtotime($financing['applyDate'])). ' 至 '. date("Y-m", strtotime($financing['expiryDate'])); ?></a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo number_format($financing['debtorPayAcct']['creditLimit'], 2); ?> 元</a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo number_format($financing['debtorPayAcct']['creditLimit'] - $financing['debtorPayAcct']['creditBal'], 2); ?> 元</a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>">--  元</a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo number_format($financing['debtorPayAcct']['creditBal'], 2); ?> 元</a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo $financing['minInterestPercent'] * 100; ?> %</a></td>
                            <td><a href="/user/financing/financing-item?<?php echo base64_encode($financing['financingID'])?>"><?php echo $financing['serviceChargePercent'] * 100; ?> %</a></td>
                            <td><button type="button" class="btn btn-warning">签署</button></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.16.0-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    let dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        let dataDictQuery = '/user/financing/financing-item-list-ajax';
        let dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

            }
        });

        let $titleOptions = $(".title-options");
        $titleOptions.find("button").click(function () {
            let dataType = $(this).attr("data-type");
            $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
            $(this).addClass("btn-warning");

            $("#" + dataType).val($(this).attr("data-value"));

            // 清空之前的结果
            $("#refreshFinancingList").submit();
        });

        $('[data-toggle="tooltip"]').tooltip();
	});
</script>
</body>
</html>
