<!-- tabbar 底部导航 -->
<div class="weui-tabbar">
    <a href="/user/mp/index" class="weui-tabbar__item weui-bar__item_on" data-target="tab_home">
        <img src="/ky/images/mp/tabbar_home.png" alt="" class="weui-tabbar__icon">
        <p class="weui-tabbar__label">首页</p>
    </a>
    <a href="/user/mp/get-loan-list" class="weui-tabbar__item" data-target="tab_loan">
        <img src="/ky/images/mp/tabbar_loan.png" alt="" class="weui-tabbar__icon">
        <p class="weui-tabbar__label">可投标</p>
    </a>
    <a href="javascript:void(0);" class="weui-tabbar__item" data-target="tab_me">
        <img src="/ky/images/mp/tabbar_me.png" alt="" class="weui-tabbar__icon">
        <p class="weui-tabbar__label">我的</p>
    </a>
</div>
