<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
<!-- base layout -->
<link rel="stylesheet" href="/ky/css/mp/base.css">
<!-- 引入 WeUI -->
<!--    <link rel="stylesheet" href="//res.wx.qq.com/open/libs/weui/1.1.3/weui.min.css"/>-->
<link rel="stylesheet" href="//res.wx.qq.com/open/libs/weui/2.0.0/weui.min.css"/>
<!-- 引入 jQuery WeUI -->
<link rel="stylesheet" href="/ky/jquery-weui-1.2.1-dist/css/jquery-weui.css">
<!-- minirefresh -->
<link rel="stylesheet" href="/ky/minirefresh-2.0.2-dist/minirefresh.min.css">
