<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,user-scalable=0">
    <title>WeUI</title>
    <!-- 引入 WeUI -->
    <link rel="stylesheet" href="//res.wx.qq.com/open/libs/weui/2.0.0/weui.min.css"/>
</head>
<body>
<!-- 使用 -->

<div class="weui-form-preview">
    <div class="weui-cell__hd" style="position: relative;margin-right: 10px;">
        <img src="<?php echo $this->wechatHeadimgurl; ?>" style="width: 50px;display: block">
    </div>
    <div class="weui-form-preview__hd">
        <label class="weui-form-preview__label">用户名</label>
        <em class="weui-form-preview__value"><?php echo $this->userLoginName; ?></em>
    </div>
</div>
</body>
</html>
