<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/mp/headerLink.phtml'); ?>
    <title>快移资金 - 操作成功</title>

    <link rel="stylesheet" href="/ky/css/mp/loan-view.css">
</head>
<body ontouchstart>
<div class="weui-tab">
    <!-- 主体 -->
    <div class="weui-msg">
        <div class="weui-msg__icon-area"><i class="weui-icon-success weui-icon_msg"></i></div>
        <div class="weui-msg__text-area">
            <h2 class="weui-msg__title">操作成功</h2>
            <p class="weui-msg__desc">请在项目认筹时间内，保证您的快移账户有足够的余额。</p>
        </div>
        <div class="weui-msg__opr-area">
            <p class="weui-btn-area">
                <a href="/mp/get-loan-view" class="weui-btn weui-btn_primary">返回详情</a>
            </p>
        </div>
        <div class="weui-msg__extra-area">
            <div class="weui-footer">
                <p class="weui-footer__links">
                    <a href="javascript:void(0);" class="weui-footer__link">底部链接文本</a>
                </p>
                <p class="weui-footer__text">Copyright &copy; 2015-<?php echo date('Y')?> 快移交易 eTradeFast 版权所有</p>
            </div>
        </div>
    </div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/mp/footerLink.phtml'); ?>

<script type="text/javascript">
    $(function () {
        $('.weui-tabbar').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass("weui-bar__item_on");
            } else {
                $(this).removeClass('weui-bar__item_on');
            }
        });
    });

</script>
</body>
</html>
