<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/mp/headerLink.phtml'); ?>
    <title>快移资金 - 我的</title>

    <link rel="stylesheet" href="/ky/css/mp/my.css">
</head>
<body ontouchstart>
<div class="weui-tab">
    <!-- 主体 -->
    <div class="weui-tab__bd">
        <!-- 推荐项目 -->
        <div class="weui-flex">
            <div class="weui-flex__item flex_item mp-margin-5_bd my-head-bg">
                <div class="weui-flex weui-btn_bootstrap-primary mp-text-white my-head-bg mp-padding-LR-16">
                    <div class="weui-flex__item mp-text-margin-5">
                        <span> 周盛 </span>
                    </div>
                    <div class="weui-flex__item mp-text-margin-5 mp-my-right_arrow">
                        <span style="float: right; padding-right: 9px">未认证</span>
                    </div>
                </div>

                <div class="weui-flex weui-btn_bootstrap-primary mp-text-white my-head-bg mp-padding-LR-16">
                    <div class="weui-flex__item mp-text-margin-5 mp-text-size-18">
                        <b><span> 400,000 元 </span></b>
                    </div>
                    <div class="weui-flex__item mp-text-margin-5">
                        <span style="float: right;">申请提现</span>
                    </div>
                </div>

                <div class="weui-flex weui-btn_bootstrap-primary mp-text-white my-head-bg mp-padding-LR-16">
                    <div class="weui-flex__item mp-text-margin-5">
                        <span> 累计收入 </span>
                    </div>
                    <div class="weui-flex__item mp-text-margin-5">
                        <span>20,000元</span>
                    </div>

                    <div class="weui-flex__item mp-text-margin-5">
                        <span> 可用额度 </span>
                    </div>
                    <div class="weui-flex__item mp-text-margin-5">
                        <span>500,000元</span>
                    </div>
                </div>
            </div>
        </div>

        <div class="weui-cells">
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1261.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>已投项目</p>
                </div>
                <div class="weui-cell__ft">
                    详细信息
                </div>
            </a>
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1245.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>资金筹备计划</p>
                </div>
                <div class="weui-cell__ft">
                    <span>详细信息</span>
                </div>
            </a>
        </div>

        <div class="weui-cells">
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1277.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>交易记录</p>
                </div>
                <div class="weui-cell__ft">
                </div>
            </a>
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1289.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>充值</p>
                </div>
                <div class="weui-cell__ft">
                </div>
            </a>
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1303.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>银行帐户</p>
                </div>
                <div class="weui-cell__ft">
                </div>
            </a>
        </div>

        <div class="weui-cells">
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1333.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>合作协议</p>
                </div>
                <div class="weui-cell__ft">
                </div>
            </a>
        </div>

        <div class="weui-cells">
            <a class="weui-cell weui-cell_access" href="javascript:;">
                <div class="weui-cell__hd"><img src="/ky/images/mp/u1317.png" alt="" style="width:20px;margin-right:5px;display:block"></div>
                <div class="weui-cell__bd">
                    <p>消息</p>
                </div>
                <div class="weui-cell__ft">
                </div>
            </a>
        </div>
    </div>

    <?php echo $this->render(SEED_WWW_TPL . '/mp/footer.phtml'); ?>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/mp/footerLink.phtml'); ?>

<script type="text/javascript">
    $(function () {
        $('.weui-tabbar').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass("weui-bar__item_on");
            } else {
                $(this).removeClass('weui-bar__item_on');
            }
        });
    });

</script>
</body>
</html>
