<!DOCTYPE html>
<html lang="en">
<head>
    <?php echo $this->render(SEED_WWW_TPL . '/mp/headerLink.phtml'); ?>
    <title>快移资金 - 充值</title>

    <link rel="stylesheet" href="/ky/css/mp/loan-view.css">
</head>
<body ontouchstart>
<div class="weui-tab">
    <!-- 主体 -->
    <div class="weui-tab__bd">
        <form action="/mp/add-loan" method="post">
            <div class="weui-flex flex_item mp-margin-8_bd">
                <div class="weui-flex__item mp-padding-16 loan-view-info">
                    <div>
                        <div class="mp-text-info"><span class="mp-text-danger" style="line-height: 30px;">温馨提示</span></div>
                    </div>
                    <div>
                        <div class="mp-text-info">• 目前仅支持线下汇款。</div>
                        <div class="mp-text-info">• 线下转账直接向快移资金的专属账户汇款，系统会将汇款匹配到你的快移账户</div>
                    </div>
                </div>
            </div>

            <div class="weui-flex flex_item mp-margin-8_bd">
                <div class="weui-flex__item mp-padding-16 loan-view-info">
                    <div class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label mp-text-size-18"><span style="font-weight: bold;">充值金额</span></div>
                    </div>
                    <div  class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label"><span class="mp-text-size-18">￥</span></div>
                        <div class="mp-text-info loan-view-info__item_span">
                            <input class="weui-input" style="border-bottom: 1px solid; border-radius: 0; font-size: 18px" type="number" pattern="[1-9]\d*\.\d*|0\.\d*[1-9]\d*$" placeholder="请输入投标金额"/>
                        </div>
                    </div>
                    <div class="loan-view-info__item mp-text-margin-top-5">
                        <div class="mp-text-info loan-view-info__item_label"><span class="mp-text-danger">当前额度 300,000 元</span></div>
                    </div>
                </div>
            </div>

            <div class="weui-flex flex_item mp-margin-8_bd">
                <div class="weui-flex__item mp-padding-16 loan-view-info">
                    <div class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label"><span class="mp-text-size-18" style="font-weight: bold;">转账信息</span></div>
                    </div>
                    <div  class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label">账户名称</div>
                        <div class="mp-text-info loan-view-info__item_span">骏海威商业保理（深圳）有限公司</div>
                    </div>
                    <div class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label">开户银行</div>
                        <div class="mp-text-info loan-view-info__item_span">中国农业银行前海分行</div>
                    </div>
                    <div class="loan-view-info__item">
                        <div class="mp-text-info loan-view-info__item_label">银行账号</div>
                        <div class="mp-text-info loan-view-info__item_span">41013700040058794</div>
                    </div>
                </div>
            </div>

            <div class="weui-flex">
                <div class="weui-flex__item mp-margin-10_bd">
                    <button type="submit" class="weui-btn mp-btn_bootstrap_default" style="width: 98%;">确 定</button>
                </div>
            </div>
        </form>
    </div>

    <?php echo $this->render(SEED_WWW_TPL . '/mp/footer.phtml'); ?>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/mp/footerLink.phtml'); ?>

<script type="text/javascript">
    $(function () {
        $('.weui-tabbar').find('a').each(function () {
            if (this.href === document.location.href) {
                $(this).addClass("weui-bar__item_on");
            } else {
                $(this).removeClass('weui-bar__item_on');
            }
        });
    });

</script>
</body>
</html>
