<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoanList'); ?></li>
        </ol>

        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
                        <div id="main_1" style="width: 600px;height:400px;"></div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-default">
                    <div class="panel-body">

                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="page-header">
                    <h3><?php echo $this->translate('订单列表'); ?></h3>
                </div>

                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <div class="form-group">
                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('订单编号'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('订单编号'); ?>" >
                        </div>

                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('商品名称'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="proName" id="proName" placeholder="<?php echo $this->translate('商品名称'); ?>" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="paymentStatus" class="col-sm-1 control-label"><?php echo $this->translate('订单类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="paymentStatus" id="paymentStatus" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_STATUS'], $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->paymentStatus); ?>
                            </select>
                        </div>

                        <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('时间'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control layDateUI" name="startDate" id="startDate">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="crnCode" class="col-sm-1 control-label"><?php echo $this->translate('配送方式'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="crnCode" id="crnCode" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>

                        <label for="proType" class="col-sm-1 control-label"><?php echo $this->translate('产品类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="proType" id="proType" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('债项金额'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringAmount" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A1"><?php echo $this->translate('factoring_amount_a1'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A2"><?php echo $this->translate('factoring_amount_a2'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A3"><?php echo $this->translate('factoring_amount_a3'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A4"><?php echo $this->translate('factoring_amount_a4'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A5"><?php echo $this->translate('factoring_amount_a5'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringAmount" data-value="A6"><?php echo $this->translate('factoring_amount_a6'); ?></button>
                                <input type="hidden" name="factoringAmount" id="factoringAmount" value="all">
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('项目进度'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="factoringMode" data-value="all"><?php echo $this->translate('factoring_all'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="RF"><?php echo $this->translate('factoring_mode_rf'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="PF"><?php echo $this->translate('factoring_mode_pf'); ?></button>
                                <button type="button" class="btn btn-default" data-type="factoringMode" data-value="EF"><?php echo $this->translate('factoring_mode_ef'); ?></button>
                                <input type="hidden" name="factoringMode" id="factoringMode" value="all">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    var dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        var layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            var laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/settle/payment-trading-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    checkboxHeader: false,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            startDate: $("#startDate").val(),
                            endDate: $("#endDate").val(),
                            crnCode: $("#crnCode").val(),
                            lowerAmount: $("#lowerAmount").val(),
                            upperAmount: $("#upperAmount").val(),
                            tradingType: $("#tradingType").val(),
                            transNo: $("#transNo").val(),
                            paymentStatus: $("#paymentStatus").val()
                        };
                    },
                    columns: [{
                        halign: 'center',
                        checkbox: true
                    }, {
                        field: 'recordDate',
                        title: '<?php echo $this->translate("订单编号/商品"); ?>',
                        valign: 'middle',
                        width: 170,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return new Date(value).format("yyyy-MM-dd hh:mm:ss");
                        }
                    }, {
                        field: 'tradingType',
                        title: '<?php echo $this->translate("type"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                return value = "-";
                            } else {
                                var result = '';
                                var data = $.data(dataDict, 'dataDict');
                                if (value !== 'D') {
                                    $.each(data, function (key, item) {
                                        if (key === 'PAYMENT_TRADING_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === value) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                } else {
                                    $.each(data, function (key, item) {
                                        if (key === 'AR_AP_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === row.rptype) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                }
                                return result;
                            }
                        }
                    }, {
                        field: 'transNo',
                        title: '<?php echo $this->translate("货物数量/体积/重量"); ?>',
                        width: 350,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            value += '<br>';

                            var subject = row.subject;
                            if (subject === undefined || subject === '' || subject === null) {
                                subject = "";
                            }
                            subject += '<br>';

                            var remarks = row.remarks;
                            if (remarks === undefined || remarks === '' || remarks === null) {
                                remarks = "";
                            }

                            return value + '<span style="color: #ccc;">' + subject + remarks + '</span>';
                        }
                    }, {
                        field: 'oppCustomerName',
                        title: '<?php echo $this->translate("承运人"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return value;
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("始发地/目的地"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '<p>' + row.crnCode + ' ' + value + '</p>';
                            if (row.rptype === 'P') {
                                result = '<p class="text-danger">' + row.crnCode + ' ' + value + '</p>';
                            }


                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("到货时间"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("路线距离"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("运费总价"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("operation"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.tradingID);
                            var result = '';
                            if (row.allowPayment) {
                                var href = "/user/settle/payment?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_payment');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }
                            if (row.allowTransfer) {
                                var href = "/user/settle/transfer?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_transfer');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }

                            var infoHref = "/user/settle/listview?"+resultEnCode;
                            var infoStr = "<?php echo $this->translate('settle_INF');?>";
                            result += '<a href="' + infoHref + '">' + infoStr + '</a>';

                            return result;
                        }
                    }]
                });
            }
        });
	});

    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main_1'));

    // 指定图表的配置项和数据
    var option = {
        title: {

        },
        tooltip: {},
        legend: {
            data:['销量']
        },
        series: [
            {
                type: "gauge",
                center: ["50%", "45%"], // 仪表位置
                radius: "40%",          //仪表大小
                startAngle: 180,
                endAngle: 0,
                axisLine: {
                    show: false,
                    lineStyle: { // 属性lineStyle控制线条样式
                        color: [
                            [ 0.5,  new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
                                offset: 1,
                                color: "#E75F25" // 50% 处的颜色
                            }, {
                                offset: 0.8,
                                color: "#D9452C" // 40% 处的颜色
                            }], false) ], // 100% 处的颜色
                            [ 0.7,  new echarts.graphic.LinearGradient(0, 0, 1, 0, [{
                                offset: 1,
                                color: "#FFC539" // 70% 处的颜色
                            }, {
                                offset: 0.8,
                                color: "#FE951E" // 66% 处的颜色
                            }, {
                                offset: 0,
                                color: "#E75F25" // 50% 处的颜色
                            }], false) ],
                            [ 0.9,  new echarts.graphic.LinearGradient(0, 0, 0, 1, [{
                                offset: 1,
                                color: "#C7DD6B" // 90% 处的颜色
                            }, {
                                offset: 0.8,
                                color: "#FEEC49" // 86% 处的颜色
                            }, {
                                offset: 0,
                                color: "#FFC539" // 70% 处的颜色
                            }], false) ],
                            [1,  new echarts.graphic.LinearGradient(0, 0, 0, 1, [ {
                                offset: 0.2,
                                color: "#1CAD52" // 92% 处的颜色
                            }, {
                                offset: 0,
                                color: "#C7DD6B" // 90% 处的颜色
                            }], false) ]
                        ],
                        width: 10
                    }
                },
                splitLine: {
                    show: false
                },
                axisTick: {
                    show: false
                },
                axisLabel: {
                    show: false
                },
                pointer : { //指针样式
                    length: '45%'
                },
                detail: {
                    show: false
                }
            },
            {
                type : "gauge",
                center: ["50%", "45%"], // 默认全局居中
                radius : "70%",
                startAngle: 180,
                endAngle: 0,
                axisLine : {
                    show : true,
                    lineStyle : { // 属性lineStyle控制线条样式
                        color : [ //表盘颜色
                            [ 0.5, "#DA462C" ],//0-50%处的颜色
                            [ 0.7, "#FF9618" ],//51%-70%处的颜色
                            [ 0.9, "#FFED44" ],//70%-90%处的颜色
                            [ 1,"#20AE51" ]//90%-100%处的颜色
                        ],
                        width : 30//表盘宽度
                    }
                },
                splitLine : { //分割线样式（及10、20等长线样式）
                    length : 30,
                    lineStyle : { // 属性lineStyle控制线条样式
                        width : 2
                    }
                },
                axisTick : { //刻度线样式（及短线样式）
                    length : 20
                },
                axisLabel : { //文字样式（及“10”、“20”等文字样式）
                    color : "black",
                    distance : 5 //文字离表盘的距离
                },
                detail: {
                    formatter : "{score|{value}%}",
                    offsetCenter: [0, "40%"],
                    // backgroundColor: '#FFEC45',
                    // height: 30,
                    rich : {
                        score : {
                            color : "red",
                            fontFamily : "微软雅黑",
                            fontSize : 32
                        }
                    }
                },
                data: [{
                    value: 56,
                    label: {
                        textStyle: {
                            fontSize: 12
                        }
                    }
                }]
            }
        ]
    };

    // 使用刚指定的配置项和数据显示图表。
    myChart.setOption(option);
</script>
</body>
</html>
