<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('freightLoan'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body title-options">
                <?php if (!empty($this->resultMsg)): ?>
                    <div class="alert alert-success alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <p><?php echo base64_decode(str_replace(" ", "+", $this->resultMsg)); ?>!</p>
                    </div>
                <?php endif; ?>

                <div class="row">
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-1">
                                <p class="form-control-static"><?php echo $this->translate('freightFinanceStat'); ?></p>
                            </div>
                            <div class="col-sm-9">
                                <button type="button" class="btn btn-warning" data-type="freightFinanceStat" data-value="all"><?php echo $this->translate('freightFinanceStat_All'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="01"><?php echo $this->translate('freightFinanceStat_Valid'); ?></button>&nbsp;&nbsp;
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="02"><?php echo $this->translate('freightFinanceStat_ForCheck'); ?></button>
                                <button type="button" class="btn btn-default" data-type="freightFinanceStat" data-value="03"><?php echo $this->translate('freightFinanceStat_Invalid'); ?></button>
                                <input type="hidden" name="freightFinanceStat" id="freightFinanceStat" value="all">
                                <input type="hidden" name="limit" id="limit" value="<?php echo $this->limit; ?>">
                                <input type="hidden" name="offset" id="offset" value="<?php echo $this->offset; ?>">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <ul class="list-unstyled resultList" id="flowResultList">
            <li style="cursor: pointer;">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        德邦快递
                    </div>
                </div>

                <div class="panel panel-default">
                    <div class="panel-body">
                        <!-- Table -->
                        <table id="resultListTable" data-toggle="table" data-classes="table" style="border: 0 solid transparent !important">
                            <thead>
                            <tr>
                                <th data-field="id">Item ID</th>
                                <th data-field="name">Item Name</th>
                                <th data-field="price">Item Price</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>1</td>
                                <td>Item 1</td>
                                <td>$1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>Item 2</td>
                                <td>$2</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </li>
        </ul>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script type="text/javascript" src="/ky/echarts-4.2.0/echarts.min.js"></script>

<script type="text/javascript">
    var dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

            }
        });
	});
</script>
</body>
</html>
