<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/freight/freight.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li class="active"><?php echo $this->translate('订单列表'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body">

                <div class="page-header">
                    <h3><?php echo $this->translate('订单列表'); ?></h3>
                </div>

                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <div class="form-group">
                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('订单编号'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="keyword" id="keyword" placeholder="<?php echo $this->translate('订单编号'); ?>" >
                        </div>

                        <label for="keyword" class="col-sm-1 control-label"><?php echo $this->translate('商品名称'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="proName" id="proName" placeholder="<?php echo $this->translate('商品名称'); ?>" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="paymentStatus" class="col-sm-1 control-label"><?php echo $this->translate('订单类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="paymentStatus" id="paymentStatus" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_STATUS'], $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->paymentStatus); ?>
                            </select>
                        </div>

                        <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('时间'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control layDateUI" name="startDate" id="startDate">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="crnCode" class="col-sm-1 control-label"><?php echo $this->translate('配送方式'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="crnCode" id="crnCode" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>

                        <label for="proType" class="col-sm-1 control-label"><?php echo $this->translate('产品类型'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="proType" id="proType" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['CURRENCY'], $this->userLangCode, $this->dic_Setting['CURRENCY']); ?>
                            </select>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/js/base64.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>

<script type="text/javascript">
    var dataDict = {},
        userLangCode = '<?php echo $this->userLangCode; ?>';

	$().ready(function() {

	});

	$(function () {
        if (userLangCode === 'en_US') {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['en-US']);
        } else {
            $.extend($.fn.bootstrapTable.defaults, $.fn.bootstrapTable.locales['zh-CN']);
        }

        // 初始化日期控件, 绑定多个
        var layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            var laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });

        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["FACTORING_STATUS"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/settle/payment-trading-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    checkboxHeader: false,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            startDate: $("#startDate").val(),
                            endDate: $("#endDate").val(),
                            crnCode: $("#crnCode").val(),
                            lowerAmount: $("#lowerAmount").val(),
                            upperAmount: $("#upperAmount").val(),
                            tradingType: $("#tradingType").val(),
                            transNo: $("#transNo").val(),
                            paymentStatus: $("#paymentStatus").val()
                        };
                    },
                    columns: [{
                        halign: 'center',
                        checkbox: true
                    }, {
                        field: 'recordDate',
                        title: '<?php echo $this->translate("订单编号/商品"); ?>',
                        valign: 'middle',
                        width: 170,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return new Date(value).format("yyyy-MM-dd hh:mm:ss");
                        }
                    }, {
                        field: 'tradingType',
                        title: '<?php echo $this->translate("type"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                return value = "-";
                            } else {
                                var result = '';
                                var data = $.data(dataDict, 'dataDict');
                                if (value !== 'D') {
                                    $.each(data, function (key, item) {
                                        if (key === 'PAYMENT_TRADING_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === value) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                } else {
                                    $.each(data, function (key, item) {
                                        if (key === 'AR_AP_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === row.rptype) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                }
                                return result;
                            }
                        }
                    }, {
                        field: 'transNo',
                        title: '<?php echo $this->translate("货物数量/体积/重量"); ?>',
                        width: 350,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            value += '<br>';

                            var subject = row.subject;
                            if (subject === undefined || subject === '' || subject === null) {
                                subject = "";
                            }
                            subject += '<br>';

                            var remarks = row.remarks;
                            if (remarks === undefined || remarks === '' || remarks === null) {
                                remarks = "";
                            }

                            return value + '<span style="color: #ccc;">' + subject + remarks + '</span>';
                        }
                    }, {
                        field: 'oppCustomerName',
                        title: '<?php echo $this->translate("承运人"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return value;
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("始发地/目的地"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '<p>' + row.crnCode + ' ' + value + '</p>';
                            if (row.rptype === 'P') {
                                result = '<p class="text-danger">' + row.crnCode + ' ' + value + '</p>';
                            }


                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("到货时间"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("路线距离"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("运费总价"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                } else if (row.rptype === 'O') {
                                                    result = '申请中';
                                                }
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("operation"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.tradingID);
                            var result = '';
                            if (row.allowPayment) {
                                var href = "/user/settle/payment?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_payment');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }
                            if (row.allowTransfer) {
                                var href = "/user/settle/transfer?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_transfer');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }

                            var infoHref = "/user/settle/listview?"+resultEnCode;
                            var infoStr = "<?php echo $this->translate('settle_INF');?>";
                            result += '<a href="' + infoHref + '">' + infoStr + '</a>';

                            return result;
                        }
                    }]
                });
            }
        });
	});
</script>
</body>
</html>
