<?php echo $this->render("header.phtml") ?>
<script type="text/javascript" src="/js/center/jquery.checkbox.js"></script>
<script type="text/javascript">
if(parent.$_('admincpnav'))
    parent.$_('admincpnav').innerHTML='上传系统&nbsp;&raquo;&nbsp;前台角色';
</script>
<script type="text/javascript">
$().ready(function() {
	$('input[@type=checkbox][@name=checkAll]').each(function(){
		$(this).checkbox().toggle($(this).val());
	});
});
//删除
function deleteAll(){
	var ids="";
    $("[name='chose[]'][checked]").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->BaseUrl();?>/role/delete/role_ids/"+ids;
}

function doadd(){
    $("#post_form").validate({
       event: "keyup",
       rules: {
         role_name: "required",
         mod_desc: "required",
         order_by: "required"
       },
       messages: {
         role_name: "角色名称不能为空！",
         mod_desc: "角色说明不能为空！",
         order_by: "排序不能为空！"
       },
       submitHandler: function() {
            SeedMsgBox('<img src="正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/role/add',
                success: function() {
                }
            };
            $('#post_form').ajaxSubmit(options);
        }
    });
}
function doupdate(){
    $("#post_form").validate({
       event: "keyup",
       rules: {
         role_id: "required",
         role_name: "required",
         role_desc: "required",
         order_by: "required"
       },
       messages: {
         role_id: "关键数据不能为空！",
         role_name: "名称不能为空！",
         role_desc: "说明不能为空！",
         order_by: "角色等级不能为空！"
       },
       submitHandler: function() {
            SeedMsgBox('<img src="正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->BaseUrl();?>/role/update',
                success: function() {
                }
            };
            $('#post_form').ajaxSubmit(options);
        }
    });
}
</script>

<h1>前台角色 - <?php echo $this->module['mod_desc'];?></h1>
<div class="textnav">
  <p>
    		<input class="admin_bnt2" name="" type="button" value="添加" onclick="document.location='<?php echo $this->BaseUrl();?>/role/index'"/>
    	</p>
</div>
    
    <div class="main">
    	<div class="control">
    	<form name="post_form" method="post" action="" id="post_form" >
        <fieldset>
            <legend>编辑角色</legend>
            &nbsp;
            名称：<input type="text" name="role_name" id="role_name" value="<?php echo ($this->role['role_name']);?>" style="width:100px;"/>
            &nbsp;
            说明：<input type="text" name="role_desc" id="role_desc" value="<?php echo ($this->role['role_desc']);?>" style="width:100px;"/>
            &nbsp;
            排序：<input type="text" name="order_by" id="order_by" value="<?php echo ($this->role['order_by']);?>" style="width:20px;"/>
            &nbsp;
            <input type="checkbox" name="is_default" id="is_default" value="1" <?php echo ($this->role['is_default']=='1')?"checked":"";?>/>默认
            <?php if($this->role['role_id']>0):?>
            <input type="hidden" name="role_id" id="role_id" value="<?php echo ($this->role['role_id']);?>">
            <input name="updateConfirm" type="submit"  value="修改" onclick="doupdate();"/>&nbsp;
            <?php else:?>
            <input type="submit" value="添加"  onclick="doadd();"/>&nbsp;
            <?php endif;?>
            <input name="reset" type="reset"  value="重置"/>
        </fieldset>
        </form>
        </div>
        
        <div class="list_title">
	      <ul>
		     <li style="width:10%;"><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选"><label for="checkAll">全选</label></li>
	         <li style="width:20%;">名称</li>
	         <li style="width:20%;">说明</li>
	         <li style="width:15%;">排序</li>
	         <li style="width:15%;">默认</li>
	         <li style="width:18%;">操作</li>
	      </ul>
	    </div>
	    
	    <div class="list_content">
		<?php if(is_array($this->roles)):?>
		<?php foreach($this->roles as $role):?>
		<ul>
			<li style="width:10%;">
				<input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($role['role_id'])?>" class="ids_all">
			</li >
			<li style="width:20%;"><?php echo ($role['role_name']);?></li>
			<li style="width:20%;"><?php echo ($role['role_desc']);?></li>
			<li style="width:15%;"><?php echo ($role['order_by']);?></li>
			<li style="width:15%;"><?php echo ($role['is_default']=='1')?'<img src="'.$this->imageUrl.'/static/images/admin/yes.gif">':'<img src="'.$this->imageUrl.'/static/images/admin/no.gif">';?></li>
			<li style="width:18%;">
				<a href="<?php echo $this->BaseUrl();?>/role/index/role_id/<?php echo ($role['role_id']);?>"><img src="<?php echo $this->imageUrl?>/static/images/admin/edit.gif" title="编辑" alt="编辑"></a>
				<a href="<?php echo $this->BaseUrl();?>/acl/index/role_id/<?php echo ($role['role_id']);?>"><img src="/images/shouquan.gif" title="授权" alt="授权"></a>
				<a href="<?php echo $this->BaseUrl();?>/role/delete/role_ids/<?php echo ($role['role_id']);?>"><img src="/images/trash.gif" title="删除" alt="删除"></a>
			</li>
		</ul>
		<?php endforeach; ?>
		<?php endif;?>
    	</div>
    	</div>
    	<div class="batch">
			<input type="submit" name="deleteID" id="deleteID" value="删除选择" onclick="deleteAll()">&nbsp;
		</div>
    <div class="bg1">&nbsp;</div>
  </div>
</div>
<?php echo $this->render("footer.phtml") ?>

