<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
  <base target="_blank">
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/czlui/favicon.ico" />
  <title>信天邮感恩节钜惠</title>
  <script type="text/javascript">
function a(){
  if(good_search.keyword.value == '请输入关键词'){
    alert('请输入关键词');
    return true;
  } 
  good_search.submit();
}
</script>
<style type="text/css">
*{word-wrap:break-word;font-family:"Microsoft YaHei","宋体";}
html{color:#343434;font-size:12px;}
body,div,ol,ul,li,p,input,textarea,form,center,h1,h2,h3,h4,h5,h6,dl,dt,dd,img,select,table,tr,td,fieldset,legend,table,tr,td,th{margin:0; padding:0;}
body{_background-attachment:fixed; background:#FDFBEC url(/static/sendyou/ganen/ganenbg.jpg)}
select,input,textarea{font-size:12px;vertical-align:middle;}  
select{font:12px Tahoma,Arial,Verdana;border:1px solid #ebebeb;height:24px;}
li{list-style:none;}
label input{width:14px;height:14px;vertical-align:middle;margin-right:5px;}
img{border:0;}
a{color:#666;cursor:pointer;text-decoration:none;}
    #head{width:100%;display:block;text-align:center;background:#ffffff;}
  .head_top{width:100%;display:block;height:40px;background-color: #e2e2e2;}
    .head_top p{width:970px;background:#e2e2e2;border:solid #eee;border-width:1px 0;display:inline-block;height:38px;line-height:38px;text-align:left;overflow:hidden;color:#666;}
      .head_top p a{color:#666;margin:0 10px;}
      .head_top p em{font-style:normal;color:#7cbe28;}
      .head_top p small{float:right;font-size:12px;}
  .header{width:970px;display:inline-block;text-align:left;padding:34px 0;height:72px;overflow:hidden;}
    .logo{float:left;height:72px;overflow:hidden;}
      .logo span{margin-right:40px; display:inline-block;}
    .header_r{float:right;height:72px;overflow:hidden;}
    .header_r img{margin-right: 30px;}

        .nav{width:100%;height:50px;background-color: #008028;display:block;text-align: center;}
    .navdiv{width:970px;height:50px;background-color: #008028;display:inline-block;z-index:2;float: auto;}
      .navdiv ul li{float:left;height:50px;font:16px/50px "Microsoft YaHei";padding:0 6px;}
          .navdiv ul li a{color:#E2E2E2;padding:0 6px;height:47px;display:block;}
          .navdiv ul li.crumb a{color:#ffffff;}
          .navdiv ul li.crumb a:hover{font-weight:bold;border-bottom: 3px solid #fcff00;color:#fcff00; }
        .navdiv ul li.nav_sort{width:170px;font-size:16px;padding:0;margin-right:15px;background-color: #7cbe28;}
          .navdiv ul li.nav_sort a{background:#7cbe28 url(/static/sendyou/ganen/nav_sort.png) no-repeat 30px center;padding:0 0 0 25px;}
        .navdiv p{width:200px;height:28px;padding:8px 0;float:right;}
        .good_search{float: left; width:200px;}
        .s_txt{width:150px;height:26px;float:left;padding:2px;color:#333;border:2px solid #7CBE28;background:#fff;}
        .s_bnt{width:40px;height:34px;border:none;float:left;background:#7CBE28 url(/static/sendyou/ganen/search.png) no-repeat center;cursor:pointer;}
.main1{width:100%;min-width: 1000px;height:550px;float:left;position:relative;}
  .item_show{width:100%;min-width: 1000px;height: 550px;overflow:hidden;float:left;position:relative;}
  .mainhead{width:100%;min-width: 1000px; float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/cententhead.jpg) no-repeat top center;}
  .mainhead .head{height: 76px;}
  .maintop{width:100%;min-width: 1000px;float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/content1.jpg) no-repeat top center;}
  .maintop .top{height: 241px;}
  .main2{width:100%;min-width: 1000px;float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/content2.jpg) no-repeat top center;}
  .main3{width:100%;min-width: 1000px;float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/content3.jpg) no-repeat top center;}
  .main4{width:100%;min-width: 1000px;float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/content4.jpg) no-repeat top center;}
  .main5{width:100%;min-width: 1000px;height: 351px;float:left;position:relative;background:#FDFBEC url(/static/sendyou/ganen/cont_footer.jpg) no-repeat top center;}
  .main5 .footerpro{width:1000px;display:inline-block;text-align:left;padding-left: 30px;}
  .main5 .footerpro img{width: 488px;border: 1px solid #E7C489;}
  .content{width:100%;min-width: 1000px;display:block;text-align:center;}
  .contenthead{width:100%;display:block;}
      .contenthead img{width:100%; display:block;}

  .bigdiv{width:1000px;display:inline-block;text-align:left;padding-top:10px;}
    .layout{width:100%;display:block;overflow:hidden;padding:150px 0 0 10px;}
    
        .grhl ul{width:1000px;overflow:hidden;position:relative;}
        .grhl ul li{float:left;overflow:hidden;border:1px solid #E7C489;margin: 5px;}
        .grhl ul li img{width: 488px;}

.footer{width:100%;display:block;text-align:center;background-color: #ffffff;}
  .guidediv{width:100%;background:#ffffff;display:block;}
    .guide{width:1000px; display:inline-block;background:#ffffff;}
      .guide_top{padding:15px 0;border-top:2px solid #42bb48;}
      .guide_logo{float: left;}
      .guide_code{float: left;margin:12px;}
          .guide_cont dl{padding:5px 0 0 55px;width:100px;float:left;text-align:left;color:#f7f7f7;}
            .guide_cont dl dt{font:18px/24px "Microsoft YaHei";height:24px;overflow:hidden;padding-bottom:10px;color: #666666;}
            .guide_cont dl dd{width:100%;height:26px;line-height:26px;overflow:hidden;}
  .copyrightdiv{width:100%; display:block;background:#A9A9A9;padding: 15px 0;color: #f7f7f7;}
    .copyright{width:970px;display:inline-block;background:#A9A9A9;}
      .copyright a{margin:0 15px;color: #ffffff;} 
</style>
    </head>
    <body>
        <div id="head">
          <div class="head_top">
              <p>
                  <small>
                        <a href="/user/register">订单查询</a>
                        <a href="/user/register">帮助中心</a>
                        <a href="/user/register">我的信天邮</a>
                    </small>
                    <span>
                    <a>欢迎来到信天邮</a> | <a href="/user/login">登录</a> | <a href="/user/register">注册</a> 
                    </span>
                </p>
            </div>
            <div class="header">
              <div class="logo">
                  <span><a href="/"><img src="/static/sendyou/ganen/logo.png" /></a></span>
              </div>
                <div class="header_r">
                    <img src="/static/sendyou/ganen/state.png">
                </div>   
            </div>
        </div>
    <div class="nav">
        <div class="navdiv">
            <ul>
                <li class="nav_sort"><a href="http://www.sendtou.com/search?keyword=">搜索其他商品</a></li>
                <li class="crumb"><a href="/">首页</a></li>
                <li class="crumb"><a href="/merchants">进驻商家</a></li>
                <li class="crumb"><a href="/help">服务指南</a></li>
                <li class="crumb"><a href="/about/contact.html">联系我们</a></li>
                <li class="crumb"><a href="/groups">真划算</a></li>
<!--                 <li class="crumb"><a href="<?php echo $this->seed_Setting['website'];?>">香港信天邮</a></li> -->
                <li class="crumb"><a href="/czl">采芝林</a></li>
            </ul>
             <form class="good_search" id="good_search" name="good_search" method="get" action='/search'>
            <p>
                <input class="s_txt" name="keyword" type="text" value="请输入关键词" onfocus="if(value==defaultValue){value='';this.style.color='#000'}" onblur="if(!value){value=defaultValue;this.style.color='#999'}" style="color: rgb(153, 153, 153); outline:none;"/>
                <input class="s_bnt" name="" type="button" value="" onclick="javascript:a();"style="outline:none;"/>
            </p>
            </form>
        </div>
    </div>
<!--content内容-->
<div class="content">
    <div class="main1">
        <div class="item_show">
            <a title="信天邮感恩节钜惠" alt="信天邮感恩节钜惠" href="http://www.sendtou.hk/products/268.html">
            <div class="item" style="background:url(/static/sendyou/ganen/1920550.jpg) center  0 no-repeat ;width:100%;height:100%"></div>
            </a>
        </div>
    </div>
    <div class="mainhead">
        <div class="head">
        </div>
    </div>
    <div class="maintop">
        <div class="top">
        </div>
    </div>
    <div class="main2">
        <div class="bigdiv">
            <div class="layout">
                <ul>
                    <li><a title="余仁生冰糖燕窝" alt="余仁生冰糖燕窝" href="http://www.sendtou.hk/products/276.html"><img src="/static/sendyou/ganen/cont_pro1.jpg"></a></li>
                    <li><a title="余仁生珍珠粉胶原蛋白燕窝" alt="余仁生珍珠粉胶原蛋白燕窝" href="http://www.sendtou.hk/products/277.html"><img src="/static/sendyou/ganen/cont_pro2.jpg"></a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="main3">
        <div class="bigdiv">
            <div class="layout">
                <div class="grhl">
                  <ul>
                    <li><a title="消炎止痛片" alt="消炎止痛片" href="http://www.sendtou.hk/products/289.html"><img src="/static/sendyou/ganen/cont_pro3.jpg"></a></li>
                    <li><a title="记忆力片" alt="记忆力片" href="http://www.sendtou.hk/products/290.html"><img src="/static/sendyou/ganen/cont_pro4.jpg"></a></li>
                    <li><a title="记忆力片" alt="记忆力片" href="http://www.sendtou.hk/products/290.html"><img src="/static/sendyou/ganen/cont_pro5.jpg"></a></li>
                    <li><a title="消化酶胶囊" alt="消化酶胶囊" href="http://www.sendtou.hk/products/293.html"><img src="/static/sendyou/ganen/cont_pro6.jpg"></a></li>
                  </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="main4">
        <div class="bigdiv">
            <div class="layout">
                <div class="grhl">
                  <ul>
                    <li><a title="余仁生虫草菌丝体胶囊" alt="余仁生虫草菌丝体胶囊" href="http://www.sendtou.com/products/274.html"><img src="/static/sendyou/ganen/cont_pro7.jpg"></a></li>
                    <li><a title="金牌白凤丸" alt="金牌白凤丸" href="http://www.sendtou.hk/products/270.html"><img src="/static/sendyou/ganen/cont_pro8.jpg"></a></li>
                    <li><a title="金牌白凤丸" alt="金牌白凤丸" href="http://www.sendtou.hk/products/271.html"><img src="/static/sendyou/ganen/cont_pro9.jpg"></a></li>
                    <li><a title="延采白凤丸" alt="延采白凤丸" href="http://www.sendtou.hk/products/272.html"><img src="/static/sendyou/ganen/cont_pro10.jpg"></a></li>
                  </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="main5">
        <div class="footerpro">
             <ul>
                <li><a title="鹿尾羓丸" alt="鹿尾羓丸" href="http://www.sendtou.hk/products/273.html"><img src="/static/sendyou/ganen/cont_pro11.jpg"></a></li>
             </ul>
        </div>
    </div>
</div>

  <div class="footer">
          <div class="guide_top">
              <?php $charts = $this->fetchCharts('www_index_guide');?>
              <?php if(is_array($charts) && count($charts)>0):?>
              <?php foreach ($charts as $k=>$chart):?>
              <img src="/static/sendyou/ganen/guide_brand.png" />
              <?php endforeach;?>
              <?php endif;?>
          </div>
          <div class="guidediv">
                <div class="guide">
                        <?php
                            $helpM = new Home_Model_Help('home');
                            $helps = $helpM->fetchRows(array(0,5),array('parent'=>'0'),array('order_by ASC'));
                            if(is_array($helps) && count($helps) > 0){
                              foreach ($helps as $k=>$help){
                                $sub_helps = $helpM->fetchRows(null,array('parent'=>$help['help_id']),array('order_by ASC'));
                                $helps[$k]['sub_helps'] = $sub_helps;
                              }
                            }
                        ?>
                      <div class="guide_cont">
                          <div class="guide_code"><img src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/ganen/guide_code.jpg" />
                          </div>
                          <div class="guide_tip">
                          <?php if(is_array($helps)):?>
                          <?php foreach ($helps as $help):?>
                              <dl>
                                  <dt><?php echo $this->escape($help['help_title']);?></dt>
                                  <?php if(is_array($help['sub_helps']) && count($help['sub_helps'])):?>
                                  <?php foreach ($help['sub_helps'] as $sub_help):?>
                                  <dd><a href="/help/<?php echo $sub_help['help_mark']?>.html"><?php echo $this->escape($sub_help['help_title']);?></a></dd>
                                  <?php endforeach;?>
                                  <?php endif;?>
                              </dl>
                           <?php endforeach;?>
                           <?php endif;?>
                           </div>
                      </div>
                </div>
          </div>
          <div class="copyrightdiv">
            <div class="copyright">
                <?php echo $this->seed_Setting['footer'];?>
            </div>
          </div>
  </div>
</body>
</html>