<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/article/delete',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});
});
</script>
<h1> 删除资讯 </h1>
<div class="textnav">
  <p>
    <input class="btn btn-primary" name="" type="button" value="返回" onclick="history.back();"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
    <table class="admin_list">
      <tr>
        <th>编号</th>
        <th>文章标题</th>
      </tr>
      <?php if(is_array($this->newsall)):?>
      <?php foreach($this->newsall as $news):?>
      <tr>
        <td><input type="checkbox" id="news_id<?php echo ($news['news_id'])?>" name="news_id[]" checked value="<?php echo ($news['news_id'])?>">
          <?php echo ($news['news_id'])?></td>
        <td><?php echo ($news['news_title'])?></td>
      </tr>
      <?php endforeach; ?>
      <?php endif;?>
    </table>
    <div class="batch">
     <input type="submit" name="" class="btn btn-primary" value="确认删除" >
    </div>
</form>
<?php echo $this->render("footer.phtml") ?>
