<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
    <?php if(isset($this->conditions['cate_id'])):?>
    $("#cate_id").val('<?php echo $this->conditions['cate_id'];?>');
    <?php endif;?>
    <?php if(isset($this->conditions['news_type'])):?>
    $("#news_type").val('<?php echo $this->conditions['news_type'];?>');
    <?php endif;?>
    <?php if(isset($this->conditions['is_actived'])):?>
    $("#is_actived").val('<?php echo $this->conditions['is_actived'];?>');
    <?php endif;?>
});

//删除
function deleteAll(){
	var ids="";
    $("input[name='chose\[\]']:checked").each(function(){
    	ids+=$(this).val()+",";
    });
    ids=ids.substring(0,(ids.length-1));
    document.location = "<?php echo $this->BaseUrl();?>/article/delete/news_ids/"+ids;
}

</script>
<h1>资讯管理</h1>
<div class="textnav">
  <p>
    <input class="btn btn-primary" name="" type="button" value="添加" onclick="location.href='<?php echo $this->BaseUrl();?>/article/add/'"/>
  </p>
</div>
<div class="admin_search">
<form name="search" action="" method="get">
  <fieldset>
    <legend>资讯搜索</legend>
    &nbsp;
    <select name="cate_id" id="cate_id">
      <option value="-1">-资讯分类-</option>
      <?php if(is_array($this->cateoptions)):?>
      <?php foreach ($this->cateoptions as $cate):?>
      <option value="<?php echo $cate['cate_id'];?>" ><?php echo $cate['cate_name'];?></option>
      <?php endforeach;?>
      <?php endif;?>
    </select>
    &nbsp;
    <select name="news_type" id="news_type">
      <option value="-1">-表现类型-</option>
      <option value="0" >文章类</option>
      <option value="1" >图册类</option>
    </select>
    &nbsp;
    <select name="is_actived" id="is_actived">
      <option value="-1">-是否开放-</option>
      <option value="0" >否</option>
      <option value="1" >是</option>
    </select>
   <input name="提交" type="submit"  class="btn btn-primary" value="搜索" />
  </fieldset>
</form>
</div>
<table class="admin_list">
  <tr>
    <th><input type="checkbox" name="checkAll" id="checkAll"  value="input.ids_all" title="全选/反选">
      <label for="checkAll">全选</label></th>
    <th>文章标题</th>
    <th>文章分类</th>
    <th>表现类型</th>
    <th>添加时间</th>
    <th>访问点击</th>
    <?php if(isset($this->seed_Setting['pc_open']) && $this->seed_Setting['pc_open']=='1'):?>
    <th>PC版</th>
    <?php endif;?>
    <th>移动版</th>
    <th>操作</th>
  </tr>
  <?php if(is_array($this->newsall)):?>
  <?php foreach($this->newsall as $news):?>
  <tr>
    <td><input type="checkbox" id="chose[]" name="chose[]" value="<?php echo ($news['news_id'])?>" class="ids_all"></td>
    <td><a href="<?php echo $this->seed_Setting['vhome_app_server'];?>/news/detail?id=<?php echo $news['news_id'];?>" target="_blank"><?php echo ($news['news_title']);?></a></td>
    <td><?php echo ($news['cate_name']);?></td>
    <td><?php echo ($news['news_type']=='1')?"图册类":"文章类";?></td>
    <td><?php echo  date('Y-m-d',$news['add_time']);?></td>
    <td><?php echo ($news['view_cnt']);?></td>
    <?php if(isset($this->seed_Setting['pc_open']) && $this->seed_Setting['pc_open']=='1'):?>
    <td>
    	<?php echo ($news['is_actived']=='1')?'<img src="/images/center/yes.gif">':'<img src=/images/center/no.gif>';?><br />
    	<a href="<?php echo $this->BaseUrl();?>/article/updatepc/news_id/<?php echo $news["news_id"]?>">[编辑]</a>
        <a href="javascript:;" class="js-copy-link" url="<?php echo $this->seed_Setting['www_app_server']?>/news/detail?id=<?php echo $this->escape($news['news_id'])?>">[链接]</a>
    </td>
    <?php endif;?>
    <td>
    	<?php echo ($news['is_m_actived']=='1')?'<img src="/images/center/yes.gif">':'<img src=/images/center/no.gif>';?><br />
	    <a href="<?php echo $this->BaseUrl();?>/article/update/news_id/<?php echo $news["news_id"]?>">[编辑]</a>
        <a href="javascript:;" class="js-copy-link" url="<?php echo $this->seed_Setting['vhome_app_server']?>/news/detail?id=<?php echo $this->escape($news['news_id'])?>">[链接]</a>
    </td>
    <td>
	    <a href="<?php echo $this->BaseUrl();?>/article/delete/news_ids/<?php echo $news["news_id"];?>">[删除]</a>
    </td>
  </tr>
  <?php endforeach; ?>
  <?php endif;?>
</table>
<div class="batch">
  <input type="button" class="btn btn-primary" name="deleteButton" id="deleteButton" value="删除选择" onclick="deleteAll()">
</div>
<!--分页开始-->
<div class="page">
  <?php echo $this->showPage($this->page);?>
</div>
<!--分页结束-->
<?php echo $this->render("footer.phtml") ?>
