<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/account/add',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});

    $("#idtab ul").idTabs();

    var options	= {	data: data}
	var loc = new LinkageSelect(options);
	loc.bind('#province_id','0');
	loc.bind('#city_id','0');
	loc.bind('#district_id','0');

	$("#user_birthday").jSelectDate({
		css:'mydate',
		yearEnd:<?php echo date('Y');?>,
		yearBegin: <?php echo (date('Y')-80);?>,
		disabled : false,
		showLabel : false
	});
});
</script>

<h1> 添加帐号 </h1>
<div class="textnav" id="idtab">
  <ul>
    <li><a class="crumb" href="#account">帐号账户</a></li>
    <li><a href="#basic">基本资料</a></li>
    <li><a href="#detail">详细资料</a></li>
  </ul>
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.go(-1);"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form">
  <table class="admin_form" id="account">
    <tr>
      <td><strong>用户名：</strong>
        <p>
          <input name="user_name" id="user_name" value="" type="text" class="admin_txt1 {required:true,messages:{required:'用户名不能为空'}}"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>登录密码/支付密码：</strong>
        <p>
          <input name="user_password" id="user_password" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>昵称：</strong>
        <p>
          <input name="nick_name" id="nick_name" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>帐号状态：</strong>
        <p>
          <input type="radio" name="is_actived" id="is_actived0" value="0" >
          禁用&nbsp;
          <input type="radio" name="is_actived" id="is_actived1" value="1" checked>
          正常 </p></td>
    </tr>
    <tr>
      <td><strong>后台登陆：</strong>
        <p>
          <input type="radio" name="is_admin" id="is_admin0" value="0" checked>
          不允许&nbsp;
          <input type="radio" name="is_admin" id="is_admin1" value="1">
          允许 </p></td>
    </tr>
    <tr>
      <td><strong>邮箱：</strong>
        <p>
          <input name="user_email" id="user_email" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>邮箱激活：</strong>
        <p>
          <input type="radio" name="email_valid" id="email_valid0" value="0" checked>
          未验证&nbsp;
          <input type="radio" name="email_valid" id="email_valid1" value="1">
          验证通过 </p></td>
    </tr>
    <tr>
      <td><strong>手机：</strong>
        <p>
          <input name="user_mobile" id="user_mobile" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>手机激活：</strong>
        <p>
          <input type="radio" name="mobile_valid" id="mobile_valid0" value="0" checked>
          未验证&nbsp;
          <input type="radio" name="mobile_valid" id="mobile_valid1" value="1">
          验证通过 </p></td>
    </tr>
    <tr>
      <td><strong>真实姓名：</strong>
        <p>
          <input name="real_name" id="real_name" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证号码：</strong>
        <p>
          <input name="idcard_no" id="idcard_no" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证正面图：</strong>
        <p>
          <input name="idcard_cover1" id="idcard_cover1" readonly value="" type="text" class="admin_txt1"/>
          <input type="button" name="select" value="选择" class="admin_bnt2" onclick="selectCoverImage('idcard','idcard_cover1')">
          <input type="button" name="preview_idcard_cover1" id="preview_idcard_cover1" value="预览" class="admin_bnt2" onclick="previewCoverImage('idcard_cover1')" style="display:none;">
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证背面图：</strong>
        <p>
          <input name="idcard_cover2" id="idcard_cover2" readonly value="" type="text" class="admin_txt1"/>
          <input type="button" name="select" value="选择" class="admin_bnt2" onclick="selectCoverImage('idcard','idcard_cover2')">
          <input type="button" name="preview_idcard_cover2" id="preview_idcard_cover2" value="预览" class="admin_bnt2" onclick="previewCoverImage('idcard_cover2')" style="display:none;">
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证验证：</strong>
        <p>
          <input type="radio" name="idcard_valid" id="idcard_valid0" value="0" checked>
          未验证&nbsp;
          <input type="radio" name="idcard_valid" id="idcard_valid1" value="1" >
          验证通过 </p></td>
    </tr>
  </table>
  <table class="admin_form" id="basic">
    <tr>
      <td><strong>性别：</strong>
        <p>
          <input type="radio" name="user_gender" id="user_gender0" value="1" checked>
          男&nbsp;
          <input type="radio" name="user_gender" id="user_gender1" value="2">
          女 </p></td>
    </tr>
    <tr>
      <td><strong>生日：</strong>
        <p>
          <input name="user_birthday" id="user_birthday" value="1980-01-01" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>城市：</strong>
        <p>
          <select name="province_id" id="province_id" style="width:72px;">
          </select>
          <select name="city_id" id="city_id" style="width:72px;">
          </select>
          <select name="district_id" id="district_id" style="width:72px;">
          </select>
        </p></td>
    </tr>
    <tr>
      <td><strong>地址：</strong>
        <p>
          <input name="user_address" id="user_address" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>邮编：</strong>
        <p>
          <input name="zip_code" id="zip_code" value="" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
  </table>
    <table class="admin_form" id="detail">
    <?php if(is_array($this->attrs)):?>
    <?php foreach($this->attrs as $attr):?>
    <tr>
      <td><strong><?php echo $attr['attr_name'];?>：</strong>
        <p><?php echo $this->attrInput($attr,'');?></p></td>
    </tr>
    <?php endforeach;?>
    <?php endif;?>
  </table>
  <table class="admin_form">
    <tr>
      <td><input class="admin_bnt"  type="submit" value="提交"/>
        <input class="admin_bnt" name="reset" type="reset" value="重置"/></td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>