<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
$().ready(function() {
	$("#post_form").validate({
	   event: "keyup",
	   rules: {},
	   messages: {},
	   submitHandler: function() {
			SeedMsgBox('正在保存中，请稍候...');
			var options = {
			    target:     '#SeedMsgTxt',
			    url:        '<?php echo $this->BaseUrl();?>/account/update',
			    success: function() {
			    }
			};
			$('#post_form').ajaxSubmit(options);
		}
	});

	$("#idTabs ul").idTabs();

	// 加载地区
	var options	= {	data: data}
	var loc = new LinkageSelect(options);
	loc.bind('#province_id','0');
	loc.bind('#city_id','0');
	loc.bind('#district_id','0');
});
</script>

<h1>修改帐号</h1>
<div class="textnav" id="idTabs">
  <ul>
    <li><a class="crumb" href="#account">帐号账户</a></li>
    <li><a href="#basic">基本资料</a></li>
    <li><a href="#detail">详细资料</a></li>
  </ul>
  <p>
    <input class="admin_bnt2" name="" type="button" value="返回" onclick="history.back()"/>
  </p>
</div>
<form name="post_form" method="post" action="" id="post_form" >
<input name="user_id" id="user_id" type="hidden" value="<?php echo $this->user_id?>" />
  <table class="admin_form" id="account" style="display:none">
    <tr>
      <td><strong>用户名：</strong>
        <p><?php echo $this->user['user_name'];?></p></td>
    </tr>
    <tr>
      <td><strong>帐号状态：</strong>
        <p>
          <input type="radio" name="is_actived" id="is_actived0" value="0" <?php echo ($this->user['is_actived']=='0')?"checked":""; ?>>
          禁用&nbsp;
          <input type="radio" name="is_actived" id="is_actived1" value="1" <?php echo ($this->user['is_actived']=='1')?"checked":""; ?>>
          正常 </p></td>
    </tr>
    <tr>
      <td><strong>后台登陆：</strong>
        <p>
          <input type="radio" name="is_admin" id="is_admin0" value="0" <?php echo ($this->user['is_admin']=='0')?"checked":""; ?>>
          不允许&nbsp;
          <input type="radio" name="is_admin" id="is_admin1" value="1" <?php echo ($this->user['is_admin']=='1')?"checked":""; ?>>
          允许 </p></td>
    </tr>
    <tr>
      <td><strong>邮箱：</strong>
        <p>
          <input name="user_email" id="user_email" value="<?php echo ($this->user['user_email']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>邮箱激活：</strong>
        <p>
          <input type="radio" name="email_valid" id="email_valid0" value="0" <?php echo ($this->user['email_valid']=='0')?"checked":""; ?>>
          未验证&nbsp;
          <input type="radio" name="email_valid" id="email_valid1" value="1" <?php echo ($this->user['email_valid']=='1')?"checked":""; ?>>
          验证通过 </p></td>
    </tr>
    <tr>
      <td><strong>手机：</strong>
        <p>
          <input name="user_mobile" id="user_mobile" value="<?php echo ($this->user['user_mobile']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>手机激活：</strong>
        <p>
          <input type="radio" name="mobile_valid" id="mobile_valid0" value="0" <?php echo ($this->user['mobile_valid']=='0')?"checked":""; ?>>
          未验证&nbsp;
          <input type="radio" name="mobile_valid" id="mobile_valid1" value="1" <?php echo ($this->user['mobile_valid']=='1')?"checked":""; ?>>
          验证通过 </p></td>
    </tr>
    <tr>
      <td><strong>真实姓名：</strong>
        <p>
          <input name="real_name" id="real_name" value="<?php echo ($this->user['real_name']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证号码：</strong>
        <p>
          <input name="idcard_no" id="idcard_no" value="<?php echo ($this->user['idcard_no']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证正面图：</strong>
        <p>
          <input name="idcard_cover1" id="idcard_cover1" readonly value="<?php echo ($this->user['idcard_cover1']);?>" type="text" class="admin_txt1"/>
          <input type="button" name="select" value="选择" class="admin_bnt2" onclick="selectCoverImage('idcard','idcard_cover1')">
          <input type="button" name="preview_idcard_cover1" id="preview_idcard_cover1" value="预览" class="admin_bnt2" onclick="previewCoverImage('idcard_cover1')" <?php echo (($this->user['idcard_cover1'])=="")?"style=\"display:none;\"":"";?>>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证背面图：</strong>
        <p>
          <input name="idcard_cover2" id="idcard_cover2" readonly value="<?php echo ($this->user['idcard_cover2']);?>" type="text" class="admin_txt1"/>
          <input type="button" name="select" value="选择" class="admin_bnt2" onclick="selectCoverImage('idcard','idcard_cover2')">
          <input type="button" name="preview_idcard_cover2" id="preview_idcard_cover2" value="预览" class="admin_bnt2" onclick="previewCoverImage('idcard_cover2')" <?php echo (($this->user['idcard_cover2'])=="")?"style=\"display:none;\"":"";?>>
        </p></td>
    </tr>
    <tr>
      <td><strong>身份证验证：</strong>
        <p>
          <input type="radio" name="idcard_valid" id="idcard_valid0" value="0" <?php echo ($this->user['idcard_valid']=='0')?"checked":""; ?>>
          未验证&nbsp;
          <input type="radio" name="idcard_valid" id="idcard_valid1" value="1" <?php echo ($this->user['idcard_valid']=='1')?"checked":""; ?>>
          验证通过 </p></td>
    </tr>
    <tr>
      <td><strong>是否设置为供应商：</strong>
        <p>
          <input type="radio" name="is_supplier" id="is_supplier0" value="0" <?php echo ($this->user['is_supplier']=='0')?"checked":""; ?>>
          否&nbsp;
          <input type="radio" name="is_supplier" id="is_supplier0" value="1" <?php echo ($this->user['is_supplier']=='1')?"checked":""; ?>>
          是 </p></td>
    </tr>
    <tr>
      <td><strong>是否特殊用户：</strong>
        <p>
          <input type="radio" name="is_open" id="is_open" value="0" <?php echo ($this->user['is_open']=='0')?"checked":""; ?>>
          否&nbsp;
          <input type="radio" name="is_open" id="is_open" value="1" <?php echo ($this->user['is_open']=='1')?"checked":""; ?>>
          是 </p></td>
    </tr>
    <tr>
     <td><strong>门店名称：</strong>
        <p>
          <select name="store_id" id="store_id" style="width:300px;">
          <?php if (is_array($this->stores) && count($this->stores)):?>
          <option value="0">请选择</option>
          <?php foreach ($this->stores as $sto):?>
          <option value="<?php echo $sto['store_id']?>" <?php if ($sto['store_id']==$this->user['store_id']):?>selected<?php endif;?>><?php echo $sto['store_name']?></option>
          <?php endforeach;?>
          <?php endif;?> 
          </select>
        </p>
      </td>
    </tr>
  </table>
  <table class="admin_form" id="basic" style="display:none">
    <tr>
      <td><strong>昵称：</strong>
        <p>
          <input name="nick_name" id="nick_name" value="<?php echo ($this->user['nick_name']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>性别：</strong>
        <p>
          <input type="radio" name="user_gender" id="user_gender0" value="1" <?php echo ($this->user['user_gender']=='1')?"checked":""; ?>>
          男&nbsp;
          <input type="radio" name="user_gender" id="user_gender1" value="2" <?php echo ($this->user['user_gender']=='2')?"checked":""; ?>>
          女 </p></td>
    </tr>
    <tr>
      <td><strong>生日：</strong>
        <p>
          <input name="user_birthday" id="user_birthday" value="<?php echo ($this->user['user_birthday']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>城市：</strong>
        <p>
          <select name="province_id" id="province_id" style="width:72px;">
          </select>
          <select name="city_id" id="city_id" style="width:72px;">
          </select>
          <select name="district_id" id="district_id" style="width:72px;">
          </select>
        </p></td>
    </tr>
    <tr>
      <td><strong>地址：</strong>
        <p>
          <input name="user_address" id="user_address" value="<?php echo ($this->user['user_address']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
    <tr>
      <td><strong>邮编：</strong>
        <p>
          <input name="zip_code" id="zip_code" value="<?php echo ($this->user['zip_code']);?>" type="text" class="admin_txt1"/>
        </p></td>
    </tr>
  </table>
<table class="admin_form" id="detail" style="display:none">
    <?php if(is_array($this->attrs)):?>
    <?php foreach($this->attrs as $attr):?>
    <tr>
      <td><strong><?php echo $attr['attr_name'];?>：</strong>
        <p><?php echo $this->attrInput($attr,$this->profile[$attr['field_name']]);?></p></td>
    </tr>
    <?php endforeach;?>
    <?php endif;?>
  </table>
  <table class="admin_form">
    <tr>
      <td>
      <input type="hidden" name="user_id" id="user_id" value="<?php echo $this->user['user_id'];?>">
        <input class="admin_bnt"  name="" type="submit" value="提交" />
        <input class="admin_bnt" name="reset" type="reset" value="重置"/>
      <td>
    </tr>
  </table>
</form>
<?php echo $this->render("footer.phtml") ?>
