<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
	<link href="/ky/css/welcome/login.css" rel="stylesheet">
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
</head>
<body onload="document.login_form.ecommloginname.focus()">

<nav class="navbar navbar-default navbar-static-top top-memu shadow">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="/">
				<img alt="eTradeFast" title="eTradeFast" src="/ky/images/index/Logo_loginH75.png">
			</a>
		</div>
		<div class="collapse navbar-collapse">
			<p class="navbar-text">
                &nbsp;
			</p>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="/user/login/login"><h3>登录</h3></a></li>
            </ul>
		</div>
	</div>
</nav>

<div style="height: 100px; width: 100%; background-color: red;" class="hidden">

</div>

<div class="container-fluid">
	<div class="container">

		<div class="row">
            <div class="col-md-12">
                <img src="/ky/images/welcome/20201113114615.png" alt="eTradeFast">
            </div>
		</div>


        <div class="page-header">
            <h2><img src="/ky/images/welcome/20201113114637.png" alt="" style="width: 32px; height: 32px">  基础服务</h2>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">快移供应链金融</div>
                    <div class="panel-body">
                        享受金融服务的同时还享受通关、物流、退税、外汇等，外贸全流程一站式服务，省心省力，操作简单。
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-primary">
                    <div class="panel-heading">快移信融保</div>
                    <div class="panel-body">
                        享受金融服务的同时还享受通关、物流、退税、外汇等，外贸全流程一站式服务，省心省力，操作简单。
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="panel panel-warning">
                    <div class="panel-heading">快移出口退税</div>
                    <div class="panel-body">
                        享受一站式快移出口退税服务，使你更省心省力，操作简单。
                    </div>
                </div>
            </div>
        </div>

        <div class="page-header">
            <h2><img src="/ky/images/welcome/20201113114637.png" alt="" style="width: 32px; height: 32px">  金融服务</h2>
        </div>

        <div class="row">
            <div class="col-md-11">
                <div style="padding-left: 40px;">
                    <img src="/ky/images/welcome/20201113114621.png" alt="eTradeFast">
                </div>
            </div>
        </div>

        <div class="page-header">
            <h2> -- </h2>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>
<script src="/ky/js/jquery.cookie.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});
</script>
</body>
</html>
