<?php echo $this->render("header.phtml") ?>
<script type="text/javascript">
if(parent.$_('admincpnav')) 
	parent.$_('admincpnav').innerHTML='上传系统&nbsp;&raquo;&nbsp;系统信息';
</script>
<div id="information">
  <div class="content">
    <div class="title">
    	<strong>系统信息</strong>
    </div>
    
    <div class="main">
      <p>欢迎使用萌芽工作室信息应用系统</p>
      <p>技术支持：广州萌芽工作室</p>
      <p>支持网站：http://www.gzseed.com</p>
    </div>
    <div class="bg1">&nbsp;</div>
  </div>
</div>
<?php echo $this->render("footer.phtml") ?>