 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="baidu-site-verification" content="7dGQolUeVh" />
<title><?php echo $this->escape($this->goods['goods_name']);?>(<?php echo $this->escape($this->goods['country_name']);?>)进口 价格 图片 评价-信天邮全球购</title>
<meta name="keywords" content="<?php echo $this->escape($this->goods['goods_name']);?>" 价格 图片 评价/>
<meta name="description" content="信天邮线上线下销售<?php echo $this->escape($this->goods['goods_name']);?>产品，您可以了解到<?php echo $this->escape($this->goods['goods_name']);?>的最新价格,促销，优惠，打折等相关产品信息。" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/css/common.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/css/www.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/css/preferetial.css" />
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/jquery.js"></script>
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/www.js"></script>
<script type="text/javascript" src="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/js/seed.form.js"></script>
<script type="text/javascript" src="<?php echo $this->seed_Setting['static_app_server']?>/default/vplatform/js/jquery.form.js"></script>
<script type="text/javascript" src="<?php echo $this->seed_Setting['static_app_server']?>/default/vplatform/js/jquery.validate.js"></script>
<script type="text/javascript" src="<?php echo $this->seed_Setting['static_app_server']?>/default/vplatform/js/jquery.ba-hashchange.js"></script>
<script type="text/javascript" src="<?php echo WWW;?>static/sendyou/js/jquery.lazyload.js"></script>
<style type="text/css">
    #content{background: #ebebeb;}
    .layout{margin-top: 30px;}
</style>
<script type="text/javascript">
function ajaxTToCart(goods_id, stock_id){
    $('#goods_id').val(goods_id);
    $('#stock_id').val(stock_id);
    SeedMsgBox('正在保存中，请稍候...');
    var options = {
            target:     '#SeedMsgTxt',
            url:        '<?php echo $this->seed_Setting['user_app_server']?>/cart/addgoods?ajax=1',
            success: function() {
            }
        };
        $('#goods_form').ajaxSubmit(options);
}

function comment_list(){
	var page_num = parseInt($("#pagenum").val());
	var pages = parseInt($("#pages").val());
	var cate = $("#cate").val();
	if(page_num > 0 && page_num < pages){
		page_num = parseInt(page_num)+parseInt(1);
		$('#pagenum').val(page_num);
		$.get("<?php echo $this->BaseUrl();?>/products/getcomments?<?php if(!empty($this->goods['goods_id'])):echo 'goods_id='.$this->goods['goods_id'].'&';endif;?>page="+page_num,function(data){
				$("#comment_list").append(data);
		 });
		return false;
	}else{
		$('#tips').html("已经是最后一条记录！");
		return false;
	}
}
</script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div id="content">
	<div class="bigdiv">
    	<div class="location"><a href="/">首页</a> &gt;
    	   <?php if (is_array($this->parent_cates)){
		    	   	foreach ($this->parent_cates as $k => $cate){
		    	   		echo '<a href="/products/top-'.$cate['cate_id'].'.html">'.$cate['cate_name'].'</a>'.'&gt; ';
		    	   	}
    	         }
    	   ?>
    	   <?php echo $this->escape($this->goods['goods_name']);?>
        </div>

        <div class="bigbor">
        	<div class="mainshow">
                <div class="image">
                    <dl>
                    <?php if (is_array($this->photos) && count($this->photos)>0):?>
                    <?php foreach ($this->photos as $k => $photo):?>
                        <dd><img class="lazy" data-original="<?php echo $this->showImage($photo['normal_image']);?>" alt="<?php echo $this->escape($photo['image_desc']);?>" alt="产品展示大图" width="1200px" height="396px" /></dd>
                    <?php endforeach;?>
                    <?php endif;?>
                        <dt>
                            <ul>
                             <?php if (is_array($this->photos) && count($this->photos)>0):?>
                             <?php foreach ($this->photos as $k => $photo):?>
                                <li><img class="lazy" data-original="<?php echo $this->showImage($photo['thumb_image']);?>" alt="产品展示小图" width="90px" height="90px"/></li>
                             <?php endforeach;?>
                             <?php endif;?>
                            </ul>
                        </dt>
                    </dl>
                </div>

                <?php echo $this->render('default/products/goods_main.phtml');?>
        	</div>
            <!--<?php if (is_array($this->recommend_goodses) && count($this->recommend_goodses)>0):?>
            <div class="list">
            	<ul>
            	   <?php foreach ($this->recommend_goodses as $k => $goods):?>
                    <li>
                        <a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img src="<?php echo $this->showImage($goods['goods_list_image']);?>" alt="<?php echo $this->escape($goods['goods_name']);?>"/></a>
                        <p class="country"><?php echo $this->escape($goods['country_name']);?></p>
                        <h4><a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><?php echo $this->escape($goods['goods_name']);?></a></h4>
                        <p class="shop_name"><?php echo $this->escape($this->goods['shop_name']);?></p>
                        <p class="price"><?php echo $this->showPrice($goods['shop_price']);?></p>
                    </li>
                    <?php endforeach;?>
                </ul>
        	</div>
              <?php endif;?> -->

            <?php if(count($this->goodses) > 0){?>
            <div class="preferetial" style="display:block">
            <?php }else{?>
            <div class="preferetial" style="display:none">
            <?php }?>
                <div class="preferetial_top">
                <p>优惠套装</p>
                </div>
                <div class="preferetial_content">
                    <div class="content_choose" id="content_choose">
                        <ul>
                            <?php foreach($this->goodses as $k => $v ): ?>
                            <li class="select">优惠套装<?php echo $k+1;?></li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                <form name="goods_form" method="post" action="" id="goods_form" >
                    <div class="goods" id="goods">
                    <?php foreach($this->goodses as $k => $v ): ?>
                        <?php if($k == 0){?>
                        <div class="goods_group" id="goods_group" style="display:block">
                        <?php }else{?>
                        <div class="goods_group" id="goods_group" style="display:none">
                        <?php }?>
                            <div id="group_goods1" class="group_goods1" >
                                <ul>
                                    <?php foreach($v['groups'] as $key => $vv ): ?>
                                    <?php if ($key!= count($vv['goods_name'])-1) echo '<span></span>';?>
                                    <li>
                                        <a href="/products/<?php echo $vv['goods_mark'];?>.html" target="_blank" title="<?php echo $this->escape($vv['goods_name']);?>">
                                        <img class="lazy" data-original="<?php echo $this->ShowImage($vv['goods_list_image']);?>" alt="<?php echo $this->escape($vv['goods_name']);?>" width="176px" width="176px" />
                                        <p><?php echo $this->escape($vv['goods_name']);?></p>
                                        <p style="font-size:16px;color:#008028;font-weight:bold;">￥<?php echo $this->escape($vv['cost_price']);?></p>
                                        <p>原价：<s>￥<?php echo $this->escape($vv['shop_price']);?></s></p>
                                        <p>数量：<b><?php echo $this->escape($vv['goods_number']);?></b></p>
                                        </a>
                                    </li>
                                    <?php endforeach;?>
                                </ul>
                            </div>

                            <div class="group_goods_account" >
                            <?php echo '<span></span>';?>
                                <ul>
                                <li style="color:#008028;font-weight:bold;">套装价：￥<?php echo $this->escape($v['all_cost_price']);?></li>
                                <li>信天邮价：<s>￥<?php echo $this->escape($v['all_shop_price']);?></s></li>
                                <li>立即节省：￥<?php echo $this->escape($v['discount_price']);?></li>
                                </ul>

                                <p><a href="javascript:void(0)" onclick="ajaxTToCart(<?php echo $v['group_id'];?>,<?php echo $v['groupstock_id']?>);"><b>添加到购物车</b>

                                </a>
                                </p>
                                <input type="hidden" id="goods_number" name="goods_number" value="1" />
                                <input type="hidden" id="goods_id" name="goods_id" value="" />
                                <input type="hidden" id="stock_id" name="stock_id" value="" />
                            </div>
                        </div>
                    <?php endforeach;?>
                    </div>
                </from>
                </div>
            </div>

            <div class="layout" id="goods_cont">
                <div class="goods_cont_left">
                    <div class="xgsp">
                        <p class="pro_title">配件商品/相关商品</p>
                        <ul>
                           <?php foreach ($this->same_goodses as $k => $goods):?>
                            <li>
                                <a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img class="lazy" data-original="<?php echo $this->showImage($goods['goods_list_image']);?>" alt="<?php echo $this->escape($goods['goods_name']);?>" width="72px" height="72px" /></a>
                                <h4><a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><?php echo $this->escape($goods['goods_name']);?></a></h4>
                                <p class="price"><?php echo $this->showPrice($goods['shop_price']);?></p>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                    <div class="xsph">
                        <p class="pro_title">大家都在买/销售排行</p>
                        <ul>
                           <?php foreach ($this->recommend_goodses as $k => $goods):?>
                            <li>
                                <a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><img class="lazy" data-original="<?php echo $this->showImage($goods['goods_list_image']);?>" alt="<?php echo $this->escape($goods['goods_name']);?>" width="72px" height="72px" /></a>
                                <h4><a href="/products/<?php echo $this->escape($goods['goods_mark']);?>.html"><?php echo $this->escape($goods['goods_name']);?></a></h4>
                                <p class="price"><?php echo $this->showPrice($goods['shop_price']);?></p>
                            </li>
                            <?php endforeach;?>
                        </ul>
                    </div>
                </div>
                <div class="goods_cont_right">
                    <div class="goods_cont_right_banner" id="goods_cont_right_banner">
                        <ul>
                            <li class="select"><p style="cursor:pointer;">商品详情</p></li>
                            <li class=""><p style="cursor:pointer;">信天邮介绍</p></li>
                            <li class=""><p style="cursor:pointer;">购买须知</p></li>
                            <li class=""><p style="cursor:pointer;">售后服务</p></li>
                            <li class=""><p style="cursor:pointer;">用户评价</p></li>
                        </ul>
                    </div>
                    <div class="goods_cont_right_change" id="goods_cont_right_change">
                        <div class="goods_cont_right_content" style="display:block">
                            <div class="content_spxq_banner"><img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/content_spxq_banner.jpg" alt="产品详情页banner" title="产品详情页banner" width="920px" height="160px" /></div>
                            <div id="tab_0" class="property tab" data-connect="tab">
                                <p class="bgcolor">商品名称：<?php echo $this->escape($this->goods['goods_name']);?></p>
                                <p >商品货号：<?php echo $this->escape($this->goods['goods_sn']);?></p>
                                <p class="bgcolor">品牌：<?php echo $this->escape($this->goods['brand_name']);?></p>
                                <p>原产地：<?php echo $this->escape($this->goods['country_name']);?></p>
                                <p>商品分类：<?php echo $this->escape($this->goods['cate_name']);?></p>
                                <p class="bgcolor">商品毛重：<?php echo $this->escape($this->goods['goods_weight']);?></p>
                                <p>商品单重：无</p>
                                <p class="bgcolor">计量单位：<?php echo $this->escape($this->goods['unit_name']);?></p>
                                <p class="bgcolor">规格：<?php echo $this->stock_str;?></p>
                                <p>税率：<?php echo $this->tax_str;?></p>
                                <p class="bgcolor">生产日期：见包装</p>
                                <p></p>
                                <?php if(!empty($this->goods['shop_name'])):?>
                                <!--<p>供应商：<?php echo $this->escape($this->goods['shop_name']);?></p>
                                --><?php endif;?>
                                <?php if (is_array($this->attrs) && count($this->attrs)>0):?>
                                <?php foreach ($this->attrs as $k=>$v):?>
                                <?php if (!empty($v['attr_value'])):?>
                                <p><?php echo $v['attr_name'];?>：<?php echo $v['attr_value'];?></p>
                                <?php endif;?>
                                <?php endforeach;?>
                                <?php endif;?>
                            </div>
                            <div class="goods_txt">
                            <?php echo $this->showContent($this->goods['goods_content']);?>
                            </div>
                        </div>
                        <div class="goods_cont_right_content">
                            <div class="xtyjs">
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/xtyjs01.jpg" alt="信天邮介绍01" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/xtyjs02.jpg" alt="信天邮介绍02" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/xtyjs03.jpg" alt="信天邮介绍03" />
                            </div>
                        </div>
                        <div class="goods_cont_right_content">
                            <div class="gmxz">
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz01.jpg" alt="购买须知01" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz02.jpg" alt="购买须知02" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz03.jpg" alt="购买须知03" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz04.jpg" alt="购买须知04" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz05.jpg" alt="购买须知05" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/gmxz06.jpg" alt="购买须知06" />
                            </div>
                        </div>
                        <div class="goods_cont_right_content">
                            <div class="shfw">
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/shfw01.jpg" alt="售后服务01" />
                                <img class="lazy" data-original="<?php echo $this->escape($this->seed_Setting['static_app_server']);?>/sendyou/images/ui/shfw02.jpg" alt="售后服务02" />
                            </div>
                        </div>
                        <div class="goods_cont_right_content">
                            <div class="goods_pl">
                                <ul name="comment_list" id="comment_list">
                                    <?php echo $this->render('default/products/commentlist.phtml');?>
                                </ul>
                            </div>
                            <center id="tips"></center>
                            <div class="tips_more">
                            <input type="hidden" name="pagenum" id="pagenum" value="1"/>
                            <input type="hidden" name="pages" id='pages' value="<?php echo $this->page['totalpage']?>"/>
                            <a href="javascript:void(0);" onclick="comment_list()">点击查看更多 <em>&gt;</em></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<?php echo $this->render(SEED_WWW_TPL.'/right_fix.phtml');?>
</body>
<script type="text/javascript" charset="utf-8">
      $(function() {
            // placeholder : "/static/sendyou/images/ui/load.png"
          $("img.lazy").lazyload({
              threshold : 200,
              effect : "fadeIn"
          });
      });
</script>
</html>
