<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('etradefast'); ?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div class="st_tit mt20 mb2 pb10" style="border-bottom: 2px solid #ccc;">
        <p class="f18"><!--修改支付密码--><?php echo $this->translate('settle_edit_pwd');?></p>
    </div>
    <div class="st_wrap p30 mb20">
        <div class="st_box"></div>
        <div class="st_box">
            <label class="st_lab"><!--新 密 码--><?php echo $this->translate('newPSD');?></label>
            <input class="st_input" type="text" name="password" id="" value="">
        </div>
        <div class="st_box"></div>
        <div class="st_box">
            <label class="st_lab"><!--确认密码--><?php echo $this->translate('confirmPSD');?></label>
            <input class="st_input" type="text" name="password2" id="" value="">
        </div>
        <div class="clearfix tc">
            <input class="st_btn" type="button" value="<?php echo $this->translate('settle_confirmed');?>"><!--确认-->
        </div>
    </div>

</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>
