<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">

    <link href="/ky/css/settle/base.css" rel="stylesheet">
    <link href="/ky/css/settle/style.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body" style="margin-bottom: 180px;">
	<div class="container">
		<div class="row">

            <div class="page-header">
                <h3><?php echo $this->translate('Saltter_edit_pwd'); ?></h3>
            </div>

            <form action="#" method="post" id="register_form" class="form-horizontal">
                <div class="form-group">
                    <label for="longPSD" class="col-sm-2 col-md-offset-2 control-label"><?php echo $this->translate('loginPSD'); ?></label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" name="longPSD" id="longPSD" placeholder="">
                    </div>
                </div>

                <div class="form-group">
                    <label for="newPSD" class="col-sm-2 col-md-offset-2 control-label"><?php echo $this->translate('newPSD'); ?></label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" name="newPSD" id="newPSD" onblur="checkpwd(this.value)" placeholder="">
                        <span id="e_pwd" class="f12"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="confirmPSD" class="col-sm-2 col-md-offset-2 control-label"><?php echo $this->translate('confirmPSD'); ?></label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" name="confirmPSD" id="confirmPSD" onblur="checkRpwd(this.value)" placeholder="">
                        <span id="e_pwd" class="f12"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-4">
                        <button type="submit" class="btn btn-warning btn-block"><?php echo $this->translate('confirmed'); ?></button>
                    </div>
                </div>
            </form>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});

    function doPasswd(){
        SeedMsgBox('正在保存中，请稍候...');
        var options = {
            target:     '#SeedMsgTxt',
            url:        '<?php echo $this->baseUrl();?>/passwd',
            success: function() {
            }
        };
        $('#register_form').ajaxSubmit(options);
    }
    function checkpwd(va) {
        var pwd = document.getElementById("ecommpasswsd").value;
        if (va == "") {
            $("#e_pwd").css('color', 'red');
            $("#ecommpasswsd").css('border-color', 'red');
            document.getElementById("e_pwd").innerHTML = "<?php echo $this->translate('password') . $this->translate('de_null');?>";
            /*密码不能为空*/
            document.register_form.sub.disabled = true;
        } else {
            $("#ecommpasswsd").css('border-color', '#DF7E20');
            document.getElementById("e_pwd").innerHTML = "";

        }

        var reg = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
        var pwdok = reg.test(pwd);
        if (!pwdok) {
            $("#e_pwd").css('color', 'red');
            $("#ecommpasswsd").css('border-color', 'red');
            document.getElementById("e_pwd").innerHTML = "<?php echo $this->translate('mat_psd');?>";
            /*密码最少8位，包含大小字母数字*/
            document.register_form.sub.disabled = true;
            return false;
        } else {
            $("#ecommpasswsd").css('border-color', '#DF7E20');
            document.getElementById("e_pwd").innerHTML = "";

        }
    }
    function checkRpwd(va) {
        var pwd = document.getElementById("ecommpasswsd").value;
        if (va == "") {
            $("#e_rpwd").css('color', 'red');
            $("#ecommpasswsd").css('border-color', 'red');
            document.getElementById("e_rpwd").innerHTML = "<?php echo $this->translate('password') . $this->translate('de_null');?>";
            /*密码不能为空*/
            document.register_form.sub.disabled = true;
            $("#e_rpwd").css('border-color', '#red');
        } else {
            $("#ecommpasswsd").css('border-color', '#DF7E20');
            document.getElementById("e_rpwd").innerHTML = "";

        }
        if (va != pwd) {
            $("#e_rpwd").css('color', 'red');
            $("#ecommrpasswsd").css('border-color', 'red');
            document.getElementById("e_rpwd").innerHTML = "<?php echo $this->translate('is_psd');?>";
            /*两次输入的密码不一致*/
            document.register_form.sub.disabled = true;
        } else {
            $("#ecommrpasswsd").css('border-color', '#DF7E20');
            document.getElementById("e_rpwd").innerHTML = "";

        }
    }
</script>
</body>
</html>
