<div class="pay">
<label><!--提取金额--><?php echo $this->translate('settle_draw_amount');?></label>
<em><?php echo $this->draw_crnCode;?></em>
<input onchange="multiply2()" id="pay_ind" class="pay_inpt" type="text" value="">
<span class="pay_transfer_sp">
   <!--剩余--><?php echo $this->translate('settle_surplus');?>
    <em><?php echo $this->draw_crnCode;?></em>
    <?php echo $this->draw_amount;?><!--可用-->
    <?php echo $this->translate('settle_usable');?>
</span>
</div>
<div class="pay">
    <label><!--当前汇率--><?php echo $this->translate('settle_huilv');?></label>
    <em><?php echo $this->draw_crnCode.'->'.$this->crnCode;?>  &nbsp;&nbsp;
        <span id="pay_huilv"></span></em>
</div>
<div class="pay">
    <label><!--结汇金额--><?php echo $this->translate('settle_exg_amt');?></label>
    <em><?php echo $this->crnCode;?></em>
    <span id="pay_huilvs" class="pay_transfer_sp"></span>
    <input type="hidden" name="paymentAmount" id="pay_huilvst" value="">
</div>
<script type="application/javascript">
    $(document).ready(function () {
        var  basecode ='<?php echo $this->draw_crnCode;?>';//商品基准货币
        var  contcode = '<?php echo $this->crnCode;?>';//对应目标货币
        if(basecode==null||basecode==""){basecode=contcode;}
        if(contcode==null||contcode==""){contcode=basecode;}
        $.post("/user/system/orderlist/", {
            'baseCrn': basecode,
            'contraCrn': contcode
        }, function (data) {
            var json;
            if (typeof data === 'object') {
                json = data.result;
            }
            else {
                json = eval('(' + data.result + ')');
            }
           
          
            $('#pay_huilv').html(json);
        }, "json");
        data=$('#pay_ind').val();
        if(data!=null||data!=""){
            $('#pay_ind').val();
        }

    });
    function multiply2(){

        data=$('#pay_ind').val();
        rate=$('#pay_huilv').html();
        paymount=Math.floor(parseFloat(data)*parseFloat(rate) * 100) / 100;

        $('#pay_huilvs').html(paymount);
        $('#pay_huilvst').val(paymount);
    }
</script>