<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><?php echo $this->translate('etradefast'); ?></title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div class="st_tit mt20 mb2 pb10" style="border-bottom: 2px solid #ccc;">
        <p class="f18"><!--修改支付密码-->忘记支付密码</p>
    </div>
    <div class="st_wrap p30 mb20">
        <div class="clearfix tc">
            <form action="" method="post">
            <p>我们将发送一封重置支付密码的邮件至您的个人邮箱,请注意查收</p>
            <input type="hidden" name="timeout" value="" id="timeout">
            <button id="btn" class="st_btn" type="button" value="299">发送</button>
            </form>
        <a>不了，谢谢！</a>
        </div>
    </div>

</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
<script>
    var wait = 300;
    document.getElementById("btn").onclick = function() {
        time(this);
        document.getElementById("timeout").val(wait);
    };
    function time(o) {
        if (wait == 0) {
            o.removeAttribute("disabled");
            o.innerHTML = "免费获取验证码";
            wait = 300;
        } else {
            o.setAttribute("disabled", true);
            o.innerHTML = parseInt(wait/60) + "分钟后可以重新发送";
            o.style.backgroundColor= "#ccc";
            wait--;
            setTimeout(function() {
                time(o)
            }, 1000)
        }
    }
</script>
</body>
</html>
