<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <div class="page-header">
            <h3><?php echo $this->translate('Saltter_IN'); ?>
                <small class="pull-right"><a href="/user/settle/changepwd"  target="_blank" class="btn btn-warning btn-xs"><?php echo $this->translate('Saltter_setting');?></a></small>
            </h3>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row info">
                    <div class="col-sm-12 col-md-6">
                        <div class="row">
                            <div class="col-md-7">
                                <h3><?php echo $this->e['accountName'];?></h3>
                            </div>
                            <div class="col-md-5">
                                <a href="/user/bank" class="btn btn-warning" target="_blank"><?php echo $this->translate('Saltter_Bank');?></a>
                                &nbsp;&nbsp;
                                <a href="/user/settle/pay" class="btn btn-warning"><?php echo $this->translate('Saltter_recharge');?></a>
                            </div>
                        </div>
                        <div class="row info-balAmount">
                            <div class="col-md-7 text-primary">
                                <h3><?php echo $this->translate('Saltter_Balance');?></h3>
                            </div>
                            <div class="col-md-5">
                                <?php foreach($this->paymentAccountBalList as $k =>$v): ?>
                                <div class="row">
                                    <div class="col-md-1 text-warning" style="line-height: 28px;">
                                        <i>
                                        <?php echo $k; ?>
                                        </i>
                                    </div>
                                    <div class="col-md-8">
                                        <p class="text-right span-font-size-22">
                                            <?php echo number_format($v['balAmount'], 2); ?>
                                        </p>
                                    </div>
                                </div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-6 info-company">
                        <div class="row">
                            <div class="col-md-4">
                                <h3><?php echo $this->translate('Saltter_IFO'); ?></h3>
                            </div>
                            <div class="col-md-4 col-md-offset-4">
                                <button type="button" class="btn btn-warning crn-btn" data-type="amount-cny">CNY</button>&nbsp;&nbsp;<button type="button" class="btn btn-default crn-btn" data-type="amount-usd">USD</button>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                <!-- 为 ECharts 准备一个具备大小（宽高）的 DOM -->
                                <div>
                                    <div id="main" class="amount-cny" style="float: left; width: 200px; height: 180px;"></div>
                                    <div id="main2" class="amount-usd" style="float:left;width: 200px;height:180px; display: none;"></div>
                                </div>
                            </div>

                            <div class="col-md-6 col-md-offset-2">
                                <div class="amount-cny">
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_CIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_CNY_F, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_DIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_CNY_D, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_FIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_CNY_B, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                </div>

                                <div class="amount-usd" style="display: none;">
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_CIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_USD_F, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_DIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_USD_D, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                    <div class="row margin-top-15">
                                        <div class="col-md-6">
                                            <?php echo $this->translate('Saltter_FIFO');?>
                                        </div>
                                        <div class="col-md-4 text-right">
                                            <b>
                                                <?php echo number_format($this->amount_USD_B, 2);?>
                                            </b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="info-paymentTradingBal">
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="panel panel-success" style="height: 105px;">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="text-center text-primary span-font-size-18">
                                                        <?php echo $this->translate('Saltter_recive').$this->translate('Saltter_able');?>
                                                    </p>
                                                </div>
                                            </div>

                                            <?php if (is_array($this->paymentTradingBalList['R']) && count($this->paymentTradingBalList['R']) > 0): ?>
                                                <?php foreach ($this->paymentTradingBalList['R'] as $k=>$trading_CNY):?>
                                                    <div class="row margin-top-10">
                                                        <div class="col-md-2 col-md-offset-1">
                                                            <i>
                                                                <?php echo $trading_CNY['crnCode'];?>
                                                            </i>
                                                        </div>
                                                        <div class="col-md-9 text-right span-font-size-16">
                                                            <?php echo number_format($trading_CNY['balAmount'], 2);?>
                                                        </div>
                                                    </div>
                                                <?php endforeach; ?>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="panel panel-danger" style="height: 105px;">
                                        <div class="panel-body">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <p class="text-center text-primary span-font-size-18">
                                                        <?php echo $this->translate('Saltter_pay').$this->translate('Saltter_able');?>
                                                    </p>
                                                </div>
                                            </div>

                                            <?php if (is_array($this->paymentTradingBalList['P']) && count($this->paymentTradingBalList['P']) > 0): ?>
                                            <?php foreach ($this->paymentTradingBalList['P'] as $k=>$trading_CNY):?>
                                            <div class="row margin-top-10"">
                                                <div class="col-md-2 col-md-offset-1">
                                                    <i>
                                                        <?php echo $trading_CNY['crnCode'];?>
                                                    </i>
                                                </div>
                                                <div class="col-md-9 text-right span-font-size-16">
                                                    <?php echo number_format($trading_CNY['balAmount'], 2);?>
                                                </div>
                                            </div>
                                            <?php endforeach; ?>
                                            <?php endif;?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-10">
                        <p class="span-font-size-18 text-primary margin-top-15"><?php echo $this->translate('Saltter_Lastlist'); ?></p>
                    </div>
                    <div class="col-md-2 text-right">
                        <a href="/user/settle/list" class="btn btn-warning"><?php echo $this->translate('Saltter_VALL');?></a>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <?php if (!empty($this->resultMsg)): ?>
                            <div class="alert alert-success alert-dismissible fade in" role="alert" id="resultMsg">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                <p><?php echo base64_decode($this->resultMsg); ?>!</p>
                            </div>
                        <?php endif; ?>

                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th><?php echo $this->translate('Saltter_Time'); ?></th>
                                <th><?php echo $this->translate('type'); ?></th>
                                <th style="width: 350px;"><?php echo $this->translate('Saltter_TradeID'); ?></th>
                                <th><?php echo $this->translate('Saltter_For'); ?></th>
                                <th class="text-center"><?php echo $this->translate('ordertotal'); ?></th>
                                <th class="text-center"><?php echo $this->translate('Saltter_Status'); ?></th>
                                <th><?php echo $this->translate('madeTT'); ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (is_array($this->list) && count($this->list) > 0): ?>
                                <?php foreach ($this->list as $paymentTrading):?>
                                    <tr>
                                        <td style="vertical-align: middle; " width="170px"><?php echo date('Y-m-d H:i:s', strtotime($paymentTrading['recordDate'])); ?></td>
                                        <td style="vertical-align: middle; ">
                                            <?php if ($paymentTrading['tradingType'] == 'D'): ?>
                                                <?php echo $this->ShowDictionaryTo("AR_AP_TYPE", $this->userLangCode, $this->dic_Setting['AR_AP_TYPE'], $paymentTrading['rptype']); ?>
                                            <?php else: ?>
                                                <?php echo $this->ShowDictionaryTo("PAYMENT_TRADING_TYPE", $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'], $paymentTrading['tradingType']); ?>
                                            <?php endif;?>
                                        </td>
                                        <td>
                                            <?php echo $paymentTrading['transNo']; ?><br>
                                            <span style="color: #ccc;">
                                            <?php echo $paymentTrading['subject']; ?><br>
                                            <?php echo $paymentTrading['remarks']; ?>
                                            </span>
                                        </td>
                                        <td style="vertical-align: middle; ">
                                            <?php echo $paymentTrading['oppCustomerName']; ?>
                                        </td>
                                        <td class="text-right" style="vertical-align: middle;">
                                            <?php if ($paymentTrading['rptype'] == 'P'):?>
                                                <p class="text-danger">
                                                    <?php echo $paymentTrading['crnCode']; ?>&nbsp;<?php echo number_format($paymentTrading['totalAmount'], 2); ?>
                                                </p>
                                            <?php else: ?>
                                                <?php echo $paymentTrading['crnCode']; ?>&nbsp;<?php echo number_format($paymentTrading['totalAmount'], 2); ?>
                                            <?php endif; ?>
                                        </td>
                                        <td style="vertical-align: middle; ">
                                            <?php if ($paymentTrading['paymentStatus'] == 0):?>
                                                <?php if ($paymentTrading['rptype'] == 'P'): ?>
                                                    待付
                                                <?php elseif ($paymentTrading['rptype'] == 'R'):?>
                                                    待收
                                                <?php elseif ($paymentTrading['rptype'] == 'O'):?>
                                                    申请中
                                                <?php endif;?>
                                            <?php else: ?>
                                                <?php echo $this->ShowDictionaryTo("PAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $paymentTrading['paymentStatus']); ?>
                                            <?php endif; ?>
                                        </td>
                                        <td style="vertical-align: middle; ">
                                            <?php if ($paymentTrading['allowPayment']): ?>
                                                <a href="/user/settle/payment?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('Saltter_payment'); ?></a>|
                                            <?php endif; ?>
                                            <?php if ($paymentTrading['allowTransfer']): ?>
                                                <a href="/user/settle/transfer?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('Saltter_transfer'); ?></a>|
                                            <?php endif; ?>
                                            <a href="/user/settle/listview?<?php echo base64_encode($paymentTrading['tradingID']); ?>"><?php echo $this->translate('Saltter_INF'); ?></a>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php else:?>
                                <tr>
                                    <td colspan="7"><?php echo $this->translate('noData');?></td>
                                </tr>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/js/echarts.simple.min.js"></script>
<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        $(".crn-btn").click(function () {

            var $cnrBtn = $(".crn-btn"),
                dataType = $(this).attr("data-type"),
                $amountCny = $(".amount-cny"),
                $amountUsd = $(".amount-usd");
            $cnrBtn.removeClass("btn-warning");
            $(this).addClass("btn-warning");

            if (dataType === 'amount-cny') {
                $amountCny.show();
                $amountUsd.hide();
            } else {
                $amountCny.hide();
                $amountUsd.show();
            }
        });
	});

    //app.title = '金额环形图';
    // 基于准备好的dom，初始化echarts实例
    var myChart = echarts.init(document.getElementById('main'));
    var zp=<?php echo empty($this->amount_CNY_F)?0:$this->amount_CNY_F;?>;  //可支配余额
    var dx=<?php echo empty($this->amount_CNY_D)?0:$this->amount_CNY_D;?>;  //定向余额
    var dj=<?php echo empty($this->amount_CNY_B)?0:$this->amount_CNY_B;?>;   //冻结余额
    // 指定图表的配置项和数据
    var option = {
        tooltip: {
            trigger: 'item',
            formatter: " {b}:<br/> {c} ({d}%)"
        },
        color:['#86c224','#EF8200','#77c2f6'],
        series: [
            {
                name:'Amount',
                type:'pie',
                radius: ['65%', '80%'],
                label: {
                    normal: {
                        show: true,
                        formatter: " {b}: {d}%",
                        position: 'center'
                    },
                    emphasis: {
                        show: true,
                        formatter: " {b}: {d}%",
                        position: 'center',
                        textStyle: {
                            fontWeight: 'bold',
                            fontSize: '12'
                        }
                    }
                },
                labelLine: {
                    normal: {
                        show: false
                    }
                },
                data:[
                    {value:zp, name:'<?php echo $this->translate('Saltter_CIFO');?>'},//可支配
                    {value:dx, name:'<?php echo $this->translate('Saltter_DIFO');?>'},//定向
                    {value:dj, name:'<?php echo $this->translate('Saltter_FIFO');?>'}  //冻结
                ]
            }
        ]
    };
    myChart.setOption(option);

    var myChart2 = echarts.init(document.getElementById('main2'));
    var zp2=<?php echo empty($this->amount_USD_F)?0:$this->amount_USD_F;?>;  //可支配余额
    var dx2=<?php echo empty($this->amount_USD_D)?0:$this->amount_USD_D;?>;  //定向余额
    var dj2=<?php echo empty($this->amount_USD_B)?0:$this->amount_USD_B;?>;   //冻结余额
    // 指定图表的配置项和数据
    var option2 = {
        tooltip: {
            trigger: 'item',
            formatter: " {b}:<br/> {c} ({d}%)"
        },
        color:['#86c224','#EF8200','#77c2f6'],
        series: [
            {
                name:'Amount',
                type:'pie',
                radius: ['65%', '80%'],
                label: {
                    normal: {
                        show: true,
                        formatter: " {b}: {d}%",
                        position: 'center'
                    },
                    emphasis: {
                        show: true,
                        formatter: " {b}: {d}%",
                        position: 'center',
                        textStyle: {
                            fontWeight: 'bold',
                            fontSize: '12'
                        }
                    }
                },
                labelLine: {
                    normal: {
                        show: false
                    }
                },
                data:[
                    {value:zp2, name:'<?php echo $this->translate('Saltter_CIFO');?>'},//可支配
                    {value:dx2, name:'<?php echo $this->translate('Saltter_DIFO');?>'},//定向
                    {value:dj2, name:'<?php echo $this->translate('Saltter_FIFO');?>'}  //冻结
                ]
            }
        ]
    };
    myChart2.setOption(option2);
</script>
</body>
</html>
