<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>快移</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <script type="text/javascript">
        function doPasswd(){
            SeedMsgBox('正在保存中，请稍候...');
            var options = {
                target:     '#SeedMsgTxt',
                url:        '<?php echo $this->baseUrl();?>/passwd',
                success: function() {
                }
            };
            $('#register_form').ajaxSubmit(options);
        }
        function checkpwd(va) {
            var pwd = document.getElementById("ecommpasswsd").value;
            if (va == "") {
                $("#e_pwd").css('color', 'red');
                $("#ecommpasswsd").css('border-color', 'red');
                document.getElementById("e_pwd").innerHTML = "<?php echo $this->translate('password') . $this->translate('de_null');?>";
                /*密码不能为空*/
                document.register_form.sub.disabled = true;
            } else {
                $("#ecommpasswsd").css('border-color', '#DF7E20');
                document.getElementById("e_pwd").innerHTML = "";

            }

            var reg = new RegExp("^(?=.{7,})(((?=.*[A-Z])(?=.*[a-z]))|((?=.*[A-Z])(?=.*[0-9]))|((?=.*[a-z])(?=.*[0-9]))).*$", "g");
            var pwdok = reg.test(pwd);
            if (!pwdok) {
                $("#e_pwd").css('color', 'red');
                $("#ecommpasswsd").css('border-color', 'red');
                document.getElementById("e_pwd").innerHTML = "<?php echo $this->translate('mat_psd');?>";
                /*密码最少8位，包含大小字母数字*/
                document.register_form.sub.disabled = true;
                return false;
            } else {
                $("#ecommpasswsd").css('border-color', '#DF7E20');
                document.getElementById("e_pwd").innerHTML = "";

            }
        }
        function checkRpwd(va) {
            var pwd = document.getElementById("ecommpasswsd").value;
            if (va == "") {
                $("#e_rpwd").css('color', 'red');
                $("#ecommpasswsd").css('border-color', 'red');
                document.getElementById("e_rpwd").innerHTML = "<?php echo $this->translate('password') . $this->translate('de_null');?>";
                /*密码不能为空*/
                document.register_form.sub.disabled = true;
                $("#e_rpwd").css('border-color', '#red');
            } else {
                $("#ecommpasswsd").css('border-color', '#DF7E20');
                document.getElementById("e_rpwd").innerHTML = "";

            }
            if (va != pwd) {
                $("#e_rpwd").css('color', 'red');
                $("#ecommrpasswsd").css('border-color', 'red');
                document.getElementById("e_rpwd").innerHTML = "<?php echo $this->translate('is_psd');?>";
                /*两次输入的密码不一致*/
                document.register_form.sub.disabled = true;
            } else {
                $("#ecommrpasswsd").css('border-color', '#DF7E20');
                document.getElementById("e_rpwd").innerHTML = "";

            }
        }
    </script>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div style="margin: 0 auto;" class="o_content w940">
        <div class="o_tab">
        </div>
        <div class="n_o_c_tit">
            <h4><!--设置支付密码--><?php echo $this->translate('Saltter_init_pwd');?></h4>
        </div>
        <div class="u_info_ed_box">
            <form action="#" method="post" id="register_form">
                <div class="infobox" style="margin-left: 20%;">
                    <dl class="infobox_pd">
                        <label class="labelbox"><!--新 密 码--><?php echo $this->translate('newPSD');?></label>
                        <input type="password" onblur="checkpwd(this.value)" id="ecommpasswsd" name="password" value=""/>
                        <span id="e_pwd" class="f12"></span>
                    </dl>
                    <dl class="infobox_pd">
                        <label class="labelbox"><!--确认密码--><?php echo $this->translate('confirmPSD');?></label>
                        <input type="password" onblur="checkRpwd(this.value)" id="ecommrpasswsd" name="password2" value=""/>
                        <span id="e_rpwd" class="f12"></span>
                    </dl>
                </div>
                <p class="tc">
                    <input class="acc_sbtn" type="submit"  value="<?php echo $this->translate('confirmed');?>"><!--确认-->
                </p>
            </form>
        </div>
    </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>