<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">

    <link href="/ky/css/settle/base.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body" style="margin-bottom: 180px;">
	<div class="container">
		<div class="row">

            <div class="page-header">
                <h3><?php echo $this->translate('Saltter_init_pwd'); ?></h3>
            </div>

            <form action="#" method="post" id="register_form" class="form-horizontal">
                <div class="form-group">
                    <label for="newPSD" class="col-sm-2 col-md-offset-2 control-label"><?php echo $this->translate('newPSD'); ?></label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" name="newPSD" id="newPSD" placeholder="">
                        <span id="e_pwd" class="f12"></span>
                    </div>
                </div>

                <div class="form-group">
                    <label for="confirmPSD" class="col-sm-2 col-md-offset-2 control-label"><?php echo $this->translate('confirmPSD'); ?></label>
                    <div class="col-sm-4">
                        <input type="password" class="form-control" name="confirmPSD" id="confirmPSD" placeholder="">
                        <span id="e_pwd" class="f12"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-4 col-sm-4">
                        <button type="submit" class="btn btn-warning btn-block"><?php echo $this->translate('confirmed'); ?></button>
                    </div>
                </div>
            </form>
		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {
        $("#register_form").validate({
            rules: {
                newPSD: {
                    isValidPassword: true,
                    minlength: 8,
                    maxlength: 30
                },
                confirmPSD: {
                    reCheckPassword: true
                }
            },
            messages: {
                newPSD : {
                    required: "<?php echo $this->translate('de_null'); ?>",
                    minlength: "<?php echo $this->translate('mat_psd');?>",
                    maxlength: "<?php echo $this->translate('is_passwd');?>"
                }
            },
            errorPlacement: function(error, element) {
                // Append error within linked label
                $(error).addClass("col-md-offset-4");
                $(element)
                    .closest( "form" )
                    .find( "label[for='" + element.attr( "id" ) + "']" )
                    .parent().addClass("has-error").removeClass("has-success")
                    .append( error );
            },
            success: function(label) {
                var forName = $(label).attr("for");
                $("label[for='" + forName + "']").parent().addClass("has-success").removeClass("has-error");
                $(label).remove();
            },
            highlight: function (element) {
                $("label[for='" + element.id + "']").parent().addClass("has-error").removeClass("has-success");
            },
            submitHandler: function (form) {
                form.submit();
            }
        });
	});

	$(function () {

	});

    // 密码规验证(8-30位  字母数字)
    jQuery.validator.addMethod("isValidPassword", function(value, element) {
        var regExp=/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,30}$/;
        return this.optional(element) || (regExp.test(value));
    }, "<?php echo $this->translate('is_passwd');?>");

    // 验证确认密码
    jQuery.validator.addMethod("reCheckPassword", function(value, element) {
        var psw = $("#newPSD").val();
        return this.optional(element) || (value === psw);
    }, "<?php echo $this->translate('is_psd');?>");
</script>
</body>
</html>
