<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/settle"><?php echo $this->translate('Saltter_IN'); ?></a></li>
            <li class="active"><?php echo $this->translate('Saltter_List'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="page-header">
                    <h3><?php echo $this->translate('Saltter_List'); ?></h3>
                </div>

                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <div class="form-group">
                        <label for="paymentStatus" class="col-sm-1 control-label"><?php echo $this->translate('Saltter_Status'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="paymentStatus" id="paymentStatus" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_STATUS'], $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->paymentStatus); ?>
                            </select>
                        </div>

                        <label for="keyword" class="col-sm-2 control-label"><?php echo $this->translate('Saltter_Forname'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="keyword" id="keyword" placeholder="" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="transNo" class="col-sm-1 control-label"><?php echo $this->translate('Saltter_TradeID'); ?></label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" name="transNo" id="transNo" placeholder="" >
                        </div>

                        <label for="tradingType" class="col-sm-2 control-label"><?php echo $this->translate('Saltter_Class'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="tradingType" id="tradingType" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_TRADING_TYPE'], $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'], $this->tradingType); ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="crnCode" class="col-sm-1 control-label"><?php echo $this->translate('ordertotal'); ?></label>
                        <div class="col-sm-2">
                            <input type="hidden" name="crnArray" value="<?php echo $this->crnString;?>">
                            <select class="selectpicker form-control" name="crnCode" id="crnCode">
                                <?php foreach ($this->crnArr as $k=>$v):?>
                                    <?php if($this->dfcrnCode==$v):?>
                                        <option selected="selected"> <?php echo $v;?></option>
                                    <?php else:?>
                                        <option > <?php echo $v;?></option>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <label for="lowerAmount" class="sr-only">lowerAmount</label>
                        <div class="col-sm-2">
                            <input type="number" class="form-control" name="lowerAmount" id="lowerAmount">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <label for="upperAmount" class="sr-only">upperAmount</label>
                        <div class="col-sm-2">
                            <input type="number" class="form-control" name="upperAmount" id="upperAmount">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('Saltter_Time'); ?></label>
                        <div class="col-sm-3">
                            <input type="date" class="form-control" name="startDate" id="startDate">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <label for="endDate" class="sr-only">endDate</label>
                        <div class="col-sm-3">
                            <input type="date" class="form-control" name="endDate" id="endDate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-4">
                            <button type="submit" class="btn btn-warning btn-block"><?php echo $this->translate('find'); ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script src="/ky/js/base64.js"></script>
<script type="text/javascript">
    var dataDict = {};

	$().ready(function() {

	});

	$(function () {
        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["PAYMENT_TRADING_TYPE", "PAYMENT_STATUS", "AR_AP_TYPE"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);

                $('#resultListTable').bootstrapTable({
                    url: '/user/settle/payment-trading-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    height: 1019,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: params.search
                        };
                    },
                    columns: [{
                        field: 'recordDate',
                        title: '<?php echo $this->translate("Saltter_Time"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return new Date(value).format("yyyy-MM-dd hh:mm:ss");
                        }
                    }, {
                        field: 'rptype',
                        title: '<?php echo $this->translate("type"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                return value = "-";
                            } else {
                                var result = '';
                                var data = $.data(dataDict, 'dataDict');
                                if (value === 0) {
                                    $.each(data, function (key, item) {
                                        if (key === 'PAYMENT_TRADING_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === value) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                } else {
                                    $.each(data, function (key, item) {
                                        if (key === 'AR_AP_TYPE') {
                                            $.each(item, function (i, dict) {
                                                if (dict.code === value) {
                                                    result = dict.name;
                                                }
                                            });
                                        }
                                    });
                                }
                                return result;
                            }
                        }
                    }, {
                        field: 'transNo',
                        title: '<?php echo $this->translate("Saltter_TradeID"); ?>',
                        width: 350,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            value += '<br>';

                            var subject = row.subject;
                            if (subject === undefined || subject === '' || subject === null) {
                                subject = "";
                            }
                            subject += '<br>';

                            var remarks = row.remarks;
                            if (remarks === undefined || remarks === '' || remarks === null) {
                                remarks = "";
                            }

                            return value + '<span style="color: #ccc;">' + subject + remarks + '</span>';
                        }
                    }, {
                        field: 'oppCustomerName',
                        title: '<?php echo $this->translate("Saltter_For"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            return value;
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("ordertotal"); ?>',
                        align: 'right',
                        halign: 'center',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '<p>' + row.crnCode + ' ' + value + '</p>';
                            if (row.rptype === 'P') {
                                result = '<p class="text-danger">' + row.crnCode + ' ' + value + '</p>';
                            }


                            return result;
                        }
                    }, {
                        field: 'paymentStatus',
                        title: '<?php echo $this->translate("Saltter_Status"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            var result = '';
                            var data = $.data(dataDict, 'dataDict');
                            $.each(data, function (key, item) {
                                if (key === 'PAYMENT_STATUS') {
                                    $.each(item, function (i, dict) {
                                        if (dict.code === value + '') {
                                            if (dict.code === '0') {
                                                if (row.rptype === 'P') {
                                                    result = '待付';
                                                } else if (row.rptype === 'R') {
                                                    result = '待收';
                                                }

                                                /*
                                                $.each(data, function (key, item) {
                                                    if (key === 'AR_AP_TYPE') {
                                                        $.each(item, function (i, dict) {
                                                            if (dict.code === row.rptype) {
                                                                result = dict.name;
                                                            }
                                                        });
                                                    }
                                                });
*/
                                            } else {
                                                result = dict.name;
                                            }
                                        }
                                    });
                                }
                            });
                            return result;
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.tradingID);
                            var result = '';
                            if (row.allowPayment) {
                                var href = "/user/settle/payment?"+resultEnCode;
                                var str = "<?php echo $this->translate('Saltter_payment');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }
                            if (row.allowTransfer) {
                                var href = "/user/settle/transfer?"+resultEnCode;
                                var str = "<?php echo $this->translate('Saltter_transfer');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }

                            var infoHref = "/user/settle/listview?"+resultEnCode;
                            var infoStr = "<?php echo $this->translate('Saltter_INF');?>";
                            result += '<a href="' + infoHref + '">' + infoStr + '</a>';

                            return result;
                        }
                    }]
                });
            }
        });
	});

    function search() {
        var listTable = $('#resultListTable');
        var options = {
            query:{
                keyword: $("#keyword").val(),
                startDate: $("#startDate").val(),
                endDate: $("#endDate").val(),
                lowerAmount: $("#lowerAmount").val(),
                upperAmount: $("#upperAmount").val(),
                tradingType: $("#tradingType").val(),
                transNo: $("#transNo").val(),
                paymentStatus: $("#paymentStatus").val()
            }
        };
        $(listTable).bootstrapTable('refresh', options);
    }
</script>
</body>
</html>
