<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/settle"><?php echo $this->translate('Saltter_IN'); ?></a></li>
            <li><a href="/user/settle/list"><?php echo $this->translate('Saltter_List'); ?></a></li>
            <li><a href="/user/settle/lslist"><?php echo $this->translate('Saltter_Run'); ?></a></li>
            <li class="active"><?php echo $this->translate('Saltter_INF'); ?></li>
        </ol>

        <div class="page-header">
            <h3><?php echo $this->translate('Saltter_Record'); ?></h3>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Saltter_TradeID'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['transNo']; ?>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Saltter_wtname'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['subject']; ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">
                            <?php echo $this->ShowDictionaryTo("", $this->userLangCode, $this->div_Setting['AR_AP_TYPE'], $this->e['rptype']) . $this->translate('ordertotal'); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['crnCode'] . ' ' . $this->ShowToPrice($this->e['totalAmount']); ?>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Saltter_Unsettle'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['crnCode'] . ' ' . $this->ShowToPrice($this->e['balanceAmount']); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('type'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php if ($this->e['tradingType'] == 'D'): ?>
                                <?php echo $this->ShowDictionaryTo("AR_AP_TYPE", $this->userLangCode, $this->dic_Setting['AR_AP_TYPE'], $this->e['rptype']); ?>
                            <?php else: ?>
                                <?php echo $this->ShowDictionaryTo("PAYMENT_TRADING_TYPE", $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'], $this->e['tradingType']); ?>
                            <?php endif;?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">
                            <?php echo $this->translate('Saltter_contartNo'); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['contractNo']; ?>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->translate('Saltter_GTime'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo empty($this->e['recordDate']) ? null : date('Y-m-d H:i:s', strtotime($this->e['recordDate'])); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">
                            <?php echo $this->ShowToRptypeTitle($this->e['rptype'], 'Saltter_Time_ING'); ?>
                        </p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo empty($this->e['expectedDate']) ? null : date('Y-m-d H:i:s', strtotime($this->e['expectedDate'])); ?>
                        </p>
                    </div>
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->ShowToRptypeTitle($this->e['rptype'], 'Saltter_Time_Now'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo empty($this->e['actualDate']) ? null : date('Y-m-d H:i:s', strtotime($this->e['actualDate'])); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999"><?php echo $this->ShowToRptypeTitle($this->e['rptype'], 'Saltter_FTO_Status'); ?></p>
                    </div>
                    <div class="col-md-4">
                        <p class="form-control-static text-666">
                            <?php echo $this->ShowDictionaryTo("PAYMENT_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->e['paymentStatus']); ?>
                        </p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">
                            <?php echo $this->translate('Saltter_DEC'); ?>
                        </p>
                    </div>
                    <div class="col-md-9">
                        <p class="form-control-static text-666">
                            <?php echo $this->e['remarks']; ?>
                        </p>
                    </div>
                </div>

                <?php if ($this->e['rptype'] == 'P' && $this->e['isOriented'] == false): ?>
                <div class="row">
                    <div class="col-md-2">
                        <p class="form-control-static text-999">文件</p>
                    </div>
                    <div class="col-md-10"></div>
                </div>
                <div class="row">
                    <div class="col-xs-12 text-primary">
                        <?php echo $this->ShowWebuploader($this->e['attachmentList'],$this->biz_Setting['PT'],$this->attach_Setting['PTDN'], "1", $this->e['tradingID']);?>
                    </div>
                </div>
                <?php endif;?>

                <div class="row">
                    <div class="col-md-12">
                        <p class="span-font-size-18 text-primary margin-top-15"><?php echo $this->translate('Saltter_paylist'); ?></p>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-striped">
                            <thead>
                            <tr>
                                <th>记录编号</th>
                                <th><?php echo $this->translate('Saltter_Time'); ?></th>
                                <th class="text-right"><?php echo $this->translate('Saltter_TradeMount'); ?></th>
                                <th class="text-center"><?php echo $this->translate('Saltter_Status'); ?></th>
                            </tr>
                            </thead>
                            <tbody>

                            <?php if (empty($this->e['paymentRequestList'])):?>
                                <tr>
                                    <td colspan="4">暂无记录</td>
                                </tr>
                            <?php else:?>
                                <?php foreach ($this->e['paymentRequestList'] as $paymentRequest):?>
                                    <tr>
                                        <td><?php echo $paymentRequest['requestNo']; ?></td>
                                        <td><?php echo date('Y-m-d H:i:s', strtotime($paymentRequest['paymentDate'])); ?></td>
                                        <td class="text-right"><?php echo $paymentRequest['crnCode'] . ' ' . number_format($paymentRequest['totalAmount'], 2); ?></td>
                                        <td class="text-center">
                                            <?php echo $this->ShowDictionaryTo("PAYMENT_REQUEST_STATUS", $this->userLangCode, $this->dic_Setting['PAYMENT_REQUEST_STATUS'], $paymentRequest['requestStatus']); ?>
                                        </td>
                                    </tr>
                                <?php endforeach;?>
                            <?php endif;?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>
<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});
</script>
</body>
</html>
