<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">

    <link href="/ky/css/settle/base.css" rel="stylesheet">
    <link href="/ky/css/settle/style.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">

            <div class="o_content_wrap w1200 m0a clearfix">
                <div class="st_tit mt20 mb2 pb10" style="border-bottom: 2px solid #ccc;">
                    <p class="f18"><!--交易记录--><?php echo $this->translate('Saltter_List');?></p>
                    <a class="a_border ml20" href="/user/settle/lslist"><!--流水账--><?php echo $this->translate('Saltter_Run');?></a>

                </div>
                <div class="st_wrap p30 mb20">
                    <form class="form-horizontal" action="" method="post">
                        <div class="form-group">
                            <label for="paymentStatus" class="col-sm-1 control-label color-title"><?php echo $this->translate('Saltter_Status'); ?></label>
                            <div class="col-sm-4">
                                <select class="selectpicker form-control" name="paymentStatus" id="paymentStatus" data-live-search="true">
                                    <option value=""><?php echo $this->translate('et_select'); ?></option>
                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_STATUS'], $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'], $this->tradingStatus); ?>
                                </select>
                            </div>

                            <label for="oppCustomerNames" class="col-sm-2 control-label color-title"><?php echo $this->translate('Saltter_Forname'); ?></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" name="oppCustomerNames" id="oppCustomerNames" placeholder="" value="<?php echo $this->oppCustomerNames;?>" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="transNo" class="col-sm-1 control-label color-title"><?php echo $this->translate('Saltter_OrderID'); ?></label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" name="transNo" id="transNo" placeholder="" value="<?php echo $this->transNo;?>" >
                            </div>

                            <label for="tradingType" class="col-sm-2 control-label color-title"><?php echo $this->translate('Saltter_Class'); ?></label>
                            <div class="col-sm-4">
                                <select class="selectpicker form-control" name="tradingType" id="tradingType" data-live-search="true">
                                    <option value=""><?php echo $this->translate('et_select'); ?></option>
                                    <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_TRADING_TYPE'], $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'], $this->tradingType); ?>
                                </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="crnCode" class="col-sm-1 control-label color-title"><?php echo $this->translate('ordertotal'); ?></label>
                            <div class="col-sm-2">
                                <select class="selectpicker form-control" name="crnCode" id="crnCode" data-live-search="true">
                                    <?php foreach ($this->crnArr as $k=>$v):?>
                                        <?php if($this->dfcrnCode==$v):?>
                                            <option selected="selected"> <?php echo $v;?></option>
                                        <?php else:?>
                                            <option > <?php echo $v;?></option>
                                        <?php endif;?>
                                    <?php endforeach;?>
                                </select>
                                <input type="hidden" name="crnArray" value="<?php echo $this->crnString;?>">
                            </div>
                            <div class="col-sm-2">
                                <input type="number" class="form-control" name="lowerAmount" id="lowerAmount" placeholder="" value="<?php echo $this->lowerAmount; ?>" min="0" >
                            </div>
                            <div class="layui-form-mid">-</div>
                            <div class="col-sm-2">
                                <input type="number" class="form-control" name="upperAmount" id="upperAmount" placeholder="" value="<?php echo $this->upperAmount; ?>" min="0" >
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="startDate" class="col-sm-1 control-label color-title"><?php echo $this->translate('Saltter_Time'); ?></label>
                            <div class="col-sm-3">
                                <input type="date" class="form-control" name="startDate" id="startDate">
                            </div>
                            <div class="layui-form-mid">-</div>
                            <label for="endDate" class="sr-only">endDate</label>
                            <div class="col-sm-3">
                                <input type="date" class="form-control" name="endDate" id="endDate">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-5 col-sm-2">
                                <button type="submit" class="btn btn-default btn-warning btn-block"><?php echo $this->translate('find'); ?></button>
                            </div>
                        </div>
                    </form>
                </div>
                <table class="st_table bt2px">
                    <thead>
                    <tr>
                        <th width="14%"><!--时间--><?php echo $this->translate('Saltter_Time');?></th>
                        <th width="10%"><!--类型--><?php echo $this->translate('type');?></th>
                        <th width="20%"><!--交易号丨订单号丨摘要--><?php echo $this->translate('Saltter_TradeID').'|'.$this->translate('Saltter_OrderID').'|'.$this->translate('Saltter_DEC');?></th>
                        <th width="20%"><!--对方--><?php echo $this->translate('Saltter_For');?></th>
                        <th width="10%"><!--金额--><?php echo $this->translate('ordertotal');?></th>
                        <th width="13%"><!--状态--><?php echo $this->translate('Saltter_Status');?></th>
                        <th width="13%"><!--操作详情--><?php echo $this->translate('Saltter_Made');?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php if(is_array($this->e) && count($this->e)>0):?>
                        <?php foreach ($this->e as $k=>$saltter):?>
                            <tr>
                                <td><?php echo date('Y-m-d H:i:s',strtotime($saltter['recordDate']));?></td>
                                <td><?php echo $saltter['rptype']=='O'?$this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'],$saltter['tradingType']):$this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['AR_AP_TYPE'],$saltter['rptype']);?></td>
                                <td><?php echo empty($saltter['subject'])?null:$saltter['subject'].'-';?>
                                    <?php echo empty($saltter['transNo'])?null:$saltter['transNo'].'-';?>
                                    <?php echo $saltter['remarks'];?></td>
                                <td><?php echo $saltter['customerName'];?></td>
                                <td><?php echo  $this->ShowToRptype($saltter['rptype']).$saltter['crnCode'].'&nbsp;&nbsp;'.$this->ShowToPrice($saltter['totalAmount']);?></td>
                                <td><?php echo $this->ShowDictionaryTo("datatest_setting", $this->userLangCode, $this->dic_Setting['PAYMENT_STATUS'],$saltter['paymentStatus']);?></td>
                                <td>
                                    <?php if($saltter['allowPayment']):?>
                                        <a style="color:#EF8200" href="/user/settle/payment?<?php echo base64_encode($saltter['tradingID']);?>">
                                            <!--支付--><?php echo $this->translate('Saltter_payment');?></a>|
                                    <?php endif;?>
                                    <?php if($saltter['allowTransfer']):?>
                                        <a style="color:#86c224" href="/user/settle/transfer?<?php echo base64_encode($saltter['tradingID']);?>">
                                            <!--转账--><?php echo $this->translate('Saltter_transfer');?></a>|
                                    <?php endif;?>
                                    <a style="color:#56859D" href="/user/settle/listview?<?php echo base64_encode($saltter['tradingID']);?>">
                                        <!--详情--><?php echo $this->translate('Saltter_INF');?></a>
                                </td>

                            </tr>
                        <?php endforeach; ?>
                    <?php else:?>
                        <tr><td colspan="7"> <?php echo $this->translate('noData');?></td></tr>
                    <?php endif;?>
                    </tbody>
                </table>
                <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
            </div>

		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {

	});
</script>
</body>
</html>
