<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">

    <link href="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.css" rel="stylesheet">
    <link href="/ky/bootstrap-select-1.12.4-dist/css/bootstrap-select.min.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/settle"><?php echo $this->translate('settle_IN'); ?></a></li>
            <li><a href="/user/settle/list"><?php echo $this->translate('settle_List'); ?></a></li>
            <li class="active"><?php echo $this->translate('settle_Run'); ?></li>
        </ol>

        <div class="panel panel-default">
            <div class="panel-body">
                <div class="page-header">
                    <h3><?php echo $this->translate('settle_Run'); ?></h3>
                </div>

                <form class="form-horizontal" action="javascript:void(0)" onsubmit="search()" id="search_form">
                    <div class="form-group title-options">
                        <label for="tradingType" class="col-sm-1 control-label"><?php echo $this->translate('settle_direction'); ?></label>
                        <div class="col-sm-9">
                            <button type="button" class="btn btn-warning" data-type="debitCredit" data-value="all"><?php echo $this->translate('settle_all');?></button>&nbsp;&nbsp;
                            <button type="button" class="btn btn-default" data-type="debitCredit" data-value="C"><?php echo $this->translate('settle_into');?></button>&nbsp;&nbsp;
                            <button type="button" class="btn btn-default" data-type="debitCredit" data-value="D"><?php echo $this->translate('settle_out');?></button>
                            <input type="hidden" name="debitCredit" id="debitCredit" value="all">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="tradingType" class="col-sm-1 control-label"><?php echo $this->translate('settle_Class'); ?></label>
                        <div class="col-sm-4">
                            <select class="selectpicker form-control" name="tradingType" id="tradingType" data-live-search="true">
                                <option value=""><?php echo $this->translate('et_select'); ?></option>
                                <?php echo $this->ShowDictionaryList($this->dic_Setting['PAYMENT_FLOW_TYPE'], $this->userLangCode, $this->dic_Setting['PAYMENT_FLOW_TYPE'], $this->tradingType); ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="crnCode" class="col-sm-1 control-label"><?php echo $this->translate('ordertotal'); ?></label>
                        <div class="col-sm-2">
                            <input type="hidden" name="crnArray" value="<?php echo $this->crnString;?>">
                            <select class="selectpicker form-control" name="crnCode" id="crnCode">
                                <?php foreach ($this->crnArr as $k=>$v):?>
                                    <?php if($this->dfcrnCode==$v):?>
                                        <option selected="selected"> <?php echo $v;?></option>
                                    <?php else:?>
                                        <option > <?php echo $v;?></option>
                                    <?php endif;?>
                                <?php endforeach;?>
                            </select>
                        </div>
                        <label for="lowerAmount" class="sr-only">lowerAmount</label>
                        <div class="col-sm-2">
                            <input type="number" class="form-control" name="lowerAmount" id="lowerAmount">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <label for="upperAmount" class="sr-only">upperAmount</label>
                        <div class="col-sm-2">
                            <input type="number" class="form-control" name="upperAmount" id="upperAmount">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="startDate" class="col-sm-1 control-label"><?php echo $this->translate('settle_Time'); ?></label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control layDateUI" name="startDate" id="startDate">
                        </div>
                        <div class="layui-form-mid">-</div>
                        <label for="endDate" class="sr-only">endDate</label>
                        <div class="col-sm-3">
                            <input type="text" class="form-control layDateUI" name="endDate" id="endDate">
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-offset-4 col-sm-4">
                            <button type="submit" class="btn btn-warning btn-block"><?php echo $this->translate('find'); ?></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-body">
                <!-- Table -->
                <table id="resultListTable" class="table-striped"></table>
            </div>
        </div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script src="/ky/bootstrap-table-1.12.1-dist/bootstrap-table.min.js"></script>
<script src="/ky/bootstrap-table-1.12.1-dist/locale/bootstrap-table-zh-CN.min.js"></script>
<script type="text/javascript" src="/ky/bootstrap-select-1.12.4-dist/js/bootstrap-select.min.js"></script>
<script src="/ky/js/base64.js"></script>
<script type="text/javascript">
    var dataDict = {};

    $().ready(function() {

    });

    $(function () {
        var dataDictQuery = '/user/common/dict-ajax';
        var dictCode = ["PAYMENT_TRADING_TYPE", "PAYMENT_STATUS", "AR_AP_TYPE"];
        $.ajax({
            type: "POST",
            url: dataDictQuery,
            data: {
                dictCode: dictCode,
                langCode: '<?php echo $this->userLangCode; ?>'
            },
            dataType: "json",
            success: function (data) {
                $.data(dataDict, 'dataDict', data);


                var $titleOptions = $(".title-options");
                $titleOptions.find("button").click(function () {
                    var dataType = $(this).attr("data-type");
                    $("button[data-type='" + dataType + "']").removeClass("btn-warning").addClass("btn-default");
                    $(this).addClass("btn-warning");

                    $("#" + dataType).val($(this).attr("data-value"));
                });


                $('#resultListTable').bootstrapTable({
                    url: '/user/settle/payment-flow-list-ajax',
                    method: 'post',
                    // showRefresh: true,
                    // search: true,
                    pagination: true,
                    classes: 'table table-no-bordered',
                    sidePagination: 'server',
                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
                    pageNumber: 1,
                    pageSize: 10,
                    queryParams: function(params) {
                        return {
                            limit: params.limit,
                            skip: params.offset,
                            keyword: $("#keyword").val(),
                            startDate: $("#startDate").val(),
                            endDate: $("#endDate").val(),
                            lowerAmount: $("#lowerAmount").val(),
                            upperAmount: $("#upperAmount").val(),
                            tradingType: $("#tradingType").val(),
                            transNo: $("#transNo").val(),
                            debitCredit: $("#debitCredit").val(),
                            paymentStatus: $("#paymentStatus").val()
                        };
                    },
                    columns: [{
                        field: 'serialNo',
                        title: '<?php echo $this->translate("settle_RunID"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            return value;
                        }
                    }, {
                        field: 'paymentTime',
                        title: '<?php echo $this->translate("settle_Time"); ?>',
                        valign: 'middle',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                return value = "-";
                            }

                            return new Date(value).format("yyyy-MM-dd hh:mm:ss");
                        }
                    }, {
                        field: 'oppCustomerDesc',
                        title: '<?php echo $this->translate("settle_Name"); ?>',
                        width: 350,
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "";
                            }
                            value += '<br>';

                            var explanation = row.explanation;
                            if (explanation === undefined || explanation === '' || explanation === null) {
                                explanation = "";
                            }

                            return value + '<span style="color: #ccc;">' + explanation + '</span>';
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("settle_into"); ?>',
                        align: 'right',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }

                            if (row.debitCredit === 'C') {
                                return formatCurrency(value, 2);
                            } else {
                                return '';
                            }
                        }
                    }, {
                        field: 'totalAmount',
                        title: '<?php echo $this->translate("settle_out"); ?>',
                        align: 'right',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = "-";
                            }
                            if (row.debitCredit === 'D') {
                                return formatCurrency(value, 2);
                            } else {
                                return '';
                            }
                        }
                    }, {
                        field: 'acctDirectBalAmount',
                        title: '<?php echo $this->translate("settle_able"); ?>',
                        align: 'right',
                        formatter: function (value, row) {
                            if (value === undefined || value === '' || value === null) {
                                value = 0;
                            }
                            var acctFreeBalAmount = row.acctFreeBalAmount;
                            if (acctFreeBalAmount === undefined || acctFreeBalAmount === '' || acctFreeBalAmount === null) {
                                acctFreeBalAmount = 0;
                            }
                            return row.crnCode + ' ' + formatCurrency(value + acctFreeBalAmount, 2);
                        }
                    }, {
                        title: '<?php echo $this->translate("madeTT"); ?>',
                        valign: 'middle',
                        formatter: function (value, row, index) {
                            var base = new Base64();
                            var resultEnCode = base.encode(row.tradingID);
                            var result = '';
                            if (row.allowPayment) {
                                var href = "/user/settle/payment?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_payment');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }
                            if (row.allowTransfer) {
                                var href = "/user/settle/transfer?"+resultEnCode;
                                var str = "<?php echo $this->translate('settle_transfer');?>";
                                result += '<a href="' + href + '">' + str + '</a>|';
                            }

                            var infoHref = "/user/settle/listview?"+resultEnCode;
                            var infoStr = "<?php echo $this->translate('settle_INF');?>";
                            result += '<a href="' + infoHref + '">' + infoStr + '</a>';

                            return result;
                        }
                    }]
                });
            }
        });

        // 初始化日期控件, 绑定多个
        var layDateLang = '<?php if ($this->userLangCode == "en_US") echo "en"; else echo "cn";?>';
        layui.use('laydate', function() {
            var laydate = layui.laydate;
            lay('.layDateUI').each(function(){
                laydate.render({
                    elem: this
                    ,trigger: 'click'
                    ,lang: layDateLang
                });
            });
        });
    });

    function search() {
        var listTable = $('#resultListTable');
        var options = {
            query:{
                skip: 0,
                keyword: $("#keyword").val(),
                startDate: $("#startDate").val(),
                endDate: $("#endDate").val(),
                lowerAmount: $("#lowerAmount").val(),
                upperAmount: $("#upperAmount").val(),
                tradingType: $("#tradingType").val(),
                transNo: $("#transNo").val(),
                debitCredit: $("#debitCredit").val(),
                paymentStatus: $("#paymentStatus").val()
            },
            pageNumber: 1
        };
        $(listTable).bootstrapTable('refresh', options);
    }
</script>
</body>
</html>
