<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>快移</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
    <style type="text/css">
        .ls_btn{width: 300px;height: 60px;float: left;margin-left: 25%;}
        .ls_btn b,.ls_btn span{display: inline-block;line-height: 30px;font-size:16px;text-align: center;padding: 0 10px;}
        .ls_btn span{color: #86c224;}
        .rs_btn{width: 300px;height: 60px;float: left;margin-left: 10%;}
        .rs_btn b,.rs_btn span{display: inline-block;line-height: 30px;font-size:16px;text-align: center;padding: 0 10px;}
        .rs_btn span{color: #e8811a;}
    </style>
</head>
<body>
<?php echo $this->render(SEED_WWW_TPL.'/header.phtml');?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div class="st_tit mt20 mb2 pb10" style="border-bottom: 2px solid #ccc;">
        <p class="f18"><!--流水账--><?php echo $this->translate('Saltter_Run');?></p>
        <a class="a_border ml20" href="/user/settle/list"><!--交易记录--><?php echo $this->translate('Saltter_List');?></a>
    </div>
    <div class="st_wrap p30 mb20">
        <form action="" method="post">
            <div class="st_box">
                <label class="st_lab"><!-- 时间 --><?php echo $this->translate('Saltter_Time');?></label>
                <script language="javascript" type="text/javascript" src="/ky/My97DatePicker/WdatePicker.js"></script>
                <input class="st_input2" type="text" name="startDate" value="<?php echo $this->startDate;?>" tabindex="1" onfocus="WdatePicker({maxDate:'%y-%M-%d'})"> -
                <input class="st_input2" type="text" name="endDate" value="<?php echo $this->endDate;?>" tabindex="1" onfocus="WdatePicker({maxDate:'%y-%M-%d'})">
            </div>
            <div class="st_box">
                <label class="st_lab"><!--流向--><?php echo $this->translate('Saltter_direction');?></label>
                <input class="ml10" type="radio" name="debitCredit" <?php if(empty($this->debitCredit)){echo 'checked="checked"';}?> id="" value=""><?php echo $this->translate('Saltter_all');?><!--全部-->
                <input class="ml10" type="radio" name="debitCredit" <?php if($this->debitCredit=='C'){echo 'checked="checked"';}?> id="" value="C"><?php echo $this->translate('Saltter_into');?><!--流入-->
                <input class="ml10" type="radio" name="debitCredit" <?php if($this->debitCredit=='D'){echo 'checked="checked"';}?> id="" value="D"><?php echo $this->translate('Saltter_out');?><!--流出-->
            </div>
            <div class="st_box">
                <label class="st_lab"><!--金额--><?php echo $this->translate('ordertotal');?></label>
                <input type="hidden" name="crnArray" value="<?php echo $this->crnString;?>">
                <select class="st_sel" name="crnCode" style="width: 80px;">
                   <?php foreach ($this->crnArr as $k=>$v):?>
                    <option <?php if($this->dfcrnCode==$v){echo 'selected="selected"';}?>> <?php echo $v;?></option>
                    <?php endforeach;?>
                </select>
                <input style="width:100px" class="st_input" type="text" name="lowerAmount" id="" value="<?php echo $this->lowerAmount;?>">&nbsp; -
                <input style="width:100px" class="st_input" type="text" name="upperAmount" id="" value="<?php echo $this->upperAmount;?>">&nbsp;
            </div>
            <div class="st_box">
                <label class="st_lab"><!--交易分类--><?php echo $this->translate('Saltter_Class');?></label>
                <select class="st_sel" name="tradingType">
                    <?php echo $this->ShowDictionaryList("datatest_setting", $this->userLangCode, $this->dic_Setting['PAYMENT_TRADING_TYPE'],$this->tradingType); ?>
                </select>
            </div>


            <div class="clearfix tc p10">
                <input class="st_btn" type="submit" value="<?php echo $this->translate('confirm');?>"><!--确定-->
            </div>
        </form>
    </div>
    <div class="st_wrap" style="height: 80px;">
        <dl class="ls_btn"><b><!--转入金额--><?php echo $this->translate('Saltter_in_amount');?></b><span><?php echo $this->dfcrnCode.'&nbsp;&nbsp;'.$this->ShowToPrice($this->debitCredit_c);?> </span></dl>
        <dl class="rs_btn"><b><!--转出金额--><?php echo $this->translate('Saltter_out_amount');?></b><span><?php echo $this->dfcrnCode.'&nbsp;&nbsp;'.$this->ShowToPrice($this->debitCredit_d);?></span></dl>
    </div>
    <table class="st_table bt2px">
        <thead>
        <tr>
            <th  width="18%"><!--流水号--><?php echo $this->translate('Saltter_RunID');?></th>
            <th  width="15%"><!--时间--><?php echo $this->translate('Saltter_Time');?></th>
            <th  width="18%"><!--名称--><?php echo $this->translate('Saltter_Name');?></th>
            <th  width="12%"><!--转入--><?php echo $this->translate('Saltter_into');?></th>
            <th  width="12%"><!--转出--><?php echo $this->translate('Saltter_out');?></th>
            <th  width="12%"><!--余额--><?php echo $this->translate('Saltter_able');?></th>
            <th  width="13%"><!--详情--><?php echo $this->translate('Saltter_INF');?></th>
        </tr>
        </thead>
        <tbody>
        <?php if(is_array($this->e) && count($this->e)>0):?>
            <?php foreach ($this->e as $k=>$saltter):?>
                <tr>
                    <td><?php echo $saltter['transNo'];?></td>
                    <td><?php echo date('Y-m-d H:i:s',strtotime($saltter['paymentTime']));?></td>

                    <td><?php echo empty($saltter['Explanation'])?$saltter['customerName']:$saltter['Explanation'];?></td>
                    <td><?php if($saltter['debitCredit']=='C'){ echo $this->ShowToPrice($saltter['totalAmount']);}?></td>
                    <td><?php if($saltter['debitCredit']=='D'){ echo $this->ShowToPrice($saltter['totalAmount']);}?></td>
                    <td><?php echo   $saltter['crnCode']."&nbsp;".$this->ShowToPrice(($saltter['acctDirectBalAmount ']+$saltter['acctFreeBalAmount']));?></td>
                    <td>
                        <?php if($saltter['allowPayment']):?>
                            <a style="color:#86c224" href="#"><!--支付--><?php echo $this->translate('Saltter_payment');?></a>|
                        <?php endif;?>
                        <?php if($saltter['allowTransfer']):?>
                            <a style="color:#86c224" href="#"><!--转账--><?php echo $this->translate('Saltter_transfer');?></a>|
                        <?php endif;?>
                        <a style="color:#56859D" href="/user/settle/listview?<?php echo base64_encode($saltter['tradingID']);?>"><!--详情--><?php echo $this->translate('Saltter_INF');?></a>
                    </td>

                </tr>
            <?php endforeach; ?>
        <?php else:?>
            <tr><td colspan="7"> <?php echo $this->translate('noData');?></td></tr>
        <?php endif;?>
        </tbody>
    </table>
    <div class="page"> <?php echo $this->showProductPage($this->page);?> </div>
</div>
<?php echo $this->render(SEED_WWW_TPL.'/footer.phtml');?>
</body>
</html>
