<div class="o_content_wrap m0a clearfix">
    <div class="st_tit mt20 mb2 pb10" style="border-bottom: 2px solid #ccc;">
        <p class="f18"><!--设置支付密码--><?php echo $this->translate('Saltter_set_pwd');?></p>
    </div>
    <div class="st_wrap p30 mb20">
        <div class="st_box"></div>
        <form action="" method="post">
        <div class="st_box">
            <label class="st_lab"><!--新 密 码--><?php echo $this->translate('newPSD');?></label>
            <input class="st_input" type="text" name="password" id="" value="">
        </div>
        <div class="st_box"></div>
        <div class="st_box">
            <label class="st_lab"><!--确认密码--><?php echo $this->translate('confirmPSD');?></label>
            <input class="st_input" type="text" name="password2" id="" value="">
        </div>
        <div class="clearfix tc">
            <input class="st_btn" type="button" value="<?php echo $this->translate('Saltter_confirmed');?>"><!--确认-->
        </div>
        </form>
    </div>

</div>
