<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title><?php echo $this->translate('etradefast'); ?></title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">
    <link href="/ky/css/img-upload.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
        <ol class="breadcrumb">
            <li><a href="/"><?php echo $this->translate('nav_index'); ?></a></li>
            <li><a href="/user/settle"><?php echo $this->translate('settle_IN'); ?></a></li>
            <li class="active"><?php echo $this->translate('settle_recharge'); ?></li>
        </ol>

        <div class="page-header">
            <h3><?php echo $this->translate('settle_recharge'); ?></h3>
        </div>

        <?php if (!empty($this->resultMsg)): ?>
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <p><?php echo $this->resultMsg; ?>!</p>
        </div>
        <?php endif; ?>

        <form class="form-horizontal" action="#" method="post">
            <input type="hidden" name="tradingID" value="<?php echo $this->payment['tradingID']; ?>">

            <div class="form-group">
                <label class="col-sm-2 control-label"><?php echo $this->translate('settle_Balance'); ?></label>
                <div class="col-sm-4">
                    <p class="form-control-static"><?php echo $this->crnCode;?>&nbsp;<?php echo number_format($this->totalAmount, 2); ?></p>
                </div>
            </div>

            <div class="panel panel-default">
                <div class="panel-heading pay-heading">
                    <p><?php echo $this->translate('settle_prompt');?></p>
                    <p><?php echo $this->translate('settle_prompt_r1');?></p>
                    <p><?php echo $this->translate('settle_prompt_r2');?></p>
                </div>
                <div class="panel-body pay-body">
                    <div class="row pay-row">
                        <div class="col-md-12">
                            <p><?php echo $this->translate('settle_prompt_r3');?></p>
                        </div>
                    </div>

                    <div class="row pay-row">
                        <div class="col-md-2">
                            <p><?php echo $this->translate('settle_bankactname');?>：</p>
                        </div>
                        <div class="col-md-10">
                            <?php echo $this->paybank['bankAcctName'];?>
                        </div>
                    </div>

                    <div class="row pay-row">
                        <div class="col-md-2">
                            <p><?php echo $this->translate('settle_bankname');?>：</p>
                        </div>
                        <div class="col-md-10">
                            <?php echo $this->paybank['bankName'];?>
                        </div>
                    </div>

                    <div class="row pay-row">
                        <div class="col-md-2">
                            <p><?php echo $this->translate('settle_bankactno');?>：</p>
                        </div>
                        <div class="col-md-10">
                            <?php echo $this->paybank['bankAcctNo'];?>
                        </div>
                    </div>

                    <div class="row pay-row">
                        <div class="col-md-2">
                            <p><?php echo $this->translate('settle_bankaddress');?>：</p>
                        </div>
                        <div class="col-md-10">
                            <?php echo $this->paybank['bankAddress'];?>
                        </div>
                    </div>

                    <div class="row pay-row">
                        <div class="col-md-2">
                            <p>SWIFT CODE：</p>
                        </div>
                        <div class="col-md-10">
                            <?php echo $this->paybank['swiftcode'];?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="paymentAmount" class="col-sm-2 control-label"><?php echo $this->translate('settle_payment_amount');?></label>
                <div class="col-sm-3">
                    <div class="input-group">
                        <div class="input-group-addon"><?php echo $this->crnCode; ?></div>
                        <input type="number" class="form-control" name="paymentAmount" id="paymentAmount" min="0" value="0" step="0.01">
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label for="" class="col-sm-2 control-label"><?php echo $this->translate('settle_bankact'); ?></label>
                <div class="col-sm-10">
                    <?php echo $this->ShowWebuploader('', 'PR', 'PRSP', '0'); ?>
                </div>
            </div>

            <div class="form-group">
                <label for="paymentPwd" class="col-sm-2 control-label"><?php echo $this->translate('settle_pay_pwd'); ?></label>
                <div class="col-sm-3">
                    <input type="password" class="form-control" name="paymentPwd" id="paymentPwd" required>
                </div>
                <div class="col-sm-3">
                    <button type="submit" class="btn btn-warning"><?php echo $this->translate('confirmed'); ?></button>&nbsp;&nbsp;<a href="javascript:void(0)"><?php echo $this->translate('forgetPSD');?></a>
                </div>
            </div>
        </form>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript" src="/ky/upload/img.js"></script>

<script type="text/javascript">
	$().ready(function() {

	});

    var $directPaymentAmount = $("#directPaymentAmount"),
        $balPaymentAmount = $("#balPaymentAmount"),
        $paymentAmount = $("#paymentAmount"),
        $totalAmount = $("#totalAmount"),
        directPaymentAmount = 0,
        balPaymentAmount = 0,
        paymentAmount = 0;

	$(function () {
        $paymentAmount.val(0);
        doAddPaymentAmount();

	    $("#directPaymentAmount, #balPaymentAmount, #paymentAmount").keyup(function () {
            doAddPaymentAmount();
        });

	    $(".bankLabel").click(function () {
            $(".paymentGroup").removeClass("hide");
            $(".bankGroup").addClass("hide");

            doAddPaymentAmount();
        });

        $(".paymentLabel").click(function () {
            $(".paymentGroup").addClass("hide");
            $(".bankGroup").removeClass("hide");

            $paymentAmount.val(0);
            doAddPaymentAmount();
        });
	});

	function doAddPaymentAmount() {
        if ($directPaymentAmount.val() !== "" && $.isNumeric($directPaymentAmount.val())) {
            directPaymentAmount = $directPaymentAmount.val();
        }
        if ($balPaymentAmount.val() !== "" && $.isNumeric($balPaymentAmount.val())) {
            balPaymentAmount = $balPaymentAmount.val();
        }
        if ($paymentAmount.val() !== "" && $.isNumeric($paymentAmount.val())) {
            paymentAmount = $paymentAmount.val();
        }

        $totalAmount.val(arithAdd(arithAdd(directPaymentAmount, balPaymentAmount), paymentAmount));
    }
</script>
</body>
</html>
