<!DOCTYPE html>
<html lang="zh-CN">
<head>
<?php echo $this->render(SEED_WWW_TPL . '/layouts/headerLink.phtml'); ?>
	<title>快移</title>
    <link href="/ky/css/layouts/base.css" rel="stylesheet">
    <link href="/ky/css/settle/settle.css" rel="stylesheet">

    <link href="/ky/css/settle/base.css" rel="stylesheet">
    <link href="/ky/css/settle/style.css" rel="stylesheet">
    <link href="/ky/css/settle/pay.css" rel="stylesheet">
</head>
<body>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/header.phtml'); ?>

<div class="container-fluid index-body">
	<div class="container">
		<div class="row">

            <div class="o_content_wrap w1200 m0a clearfix">
                <div class="st_tit mt20 mb2 pb10">
                    <p class="f18"><!--转账--><?php echo $this->translate('Saltter_Turn');?></p>
                </div>
                <form action="#" method="post">
                    <div class="settle_info">
                        <div class="pm_view clearfix">
                            <div class="col-md-12 transfer-turn">
                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_Name'); ?></b></div>
                                    <div class="col-xs-4"><?php echo $this->paymentTrading['subject'];?></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_amount'); ?></b></div>
                                    <div class="col-xs-4 color-label"><?php echo $this->paymentTrading['crnCode'] . '&nbsp;-&nbsp;'  . $this->ShowToPrice($this->paymentTrading['totalAmount']); ?></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_amount_rev'); ?></b></div>
                                    <div class="col-xs-4 color-label"><?php echo $this->paymentTrading['crnCode'] . '&nbsp;-&nbsp;'  . $this->ShowToPrice($this->paymentTrading['balanceAmount']); ?></div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_GTime'); ?></b></div>
                                    <div class="col-xs-4">
                                        <?php if ($this->paymentTrading['recordDate']) {
                                            echo date('Y/m/d', strtotime($this->paymentTrading['recordDate']));
                                        } ?>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_Time_ING'); ?></b></div>
                                    <div class="col-xs-4">
                                        <?php if ($this->paymentTrading['expectedDate']) {
                                            echo date('Y/m/d', strtotime($this->paymentTrading['expectedDate']));
                                        } ?>
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-xs-2 color-title"><b><?php echo $this->translate('Saltter_DEC'); ?></b></div>
                                    <div class="col-xs-4"><?php echo $this->paymentTrading['remarks'];?></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pay">
                        <label><!--转出定向余额--><?php echo $this->translate('Saltter_out').$this->translate('Saltter_DIFO');?></label>
                        <em><?php echo $this->payment['crnCode'];?></em>
                        <input class="pay_inpt" type="text" name="directPaymentAmount" readonly="readonly" value="<?php echo $this->ShowToPrice($this->payment['directPaymentAmount']);?>">
                        <span class="pay_transfer_sp">
            <!--剩余--><?php echo $this->translate('Saltter_Turn');?>
                            <em><?php echo $this->payment['crnCode'];?></em><?php echo $this->ShowToPrice($this->payment['directPaymentAmount']);?><!--可用-->
                            <?php echo $this->translate('Saltter_usable');?>
                        </span>
                    </div>
                    <div class="pay">
                        <label><!--转出自由余额-->
                            <?php echo $this->translate('Saltter_out').$this->translate('Saltter_FREE');?>
                        </label>
                        <em><?php echo $this->payment['crnCode'];?></em>
                        <input id="free_balpay" class="pay_inpt" type="text" name="balPaymentAmount" value="">
                        <span id="free_balyu" class="pay_transfer_sp"><!--剩余--><?php echo $this->translate('Saltter_Turn');?>
                            <em><?php echo $this->payment['crnCode'];?></em><?php echo $this->ShowToPrice($this->paybal_free);?>
                            <!--可用--><?php echo $this->translate('Saltter_usable');?>
                        </span>
                    </div>
                    <div class="pay_bank">
                        <label><!--收款银行账号--><?php echo $this->translate('Saltter_amount_bank');?></label>
                        <select name="banklist" id="banklist">

                        </select>
                        <a id="pay_bank_no" target="_blank" href="/user/bank/add">
                            <!--添加账号--><?php echo $this->translate('Saltter_bank_add');?></a>
                    </div>

                    <h2 class="w f16"><!--发票信息--><?php echo $this->translate('Saltter_bill_info');?></h2>

                    <div class="col-md-12 transfer-turn">
                        <div class="row">
                            <label for="billNo" class="col-sm-1 control-label color-title"><b><?php echo $this->translate('Saltter_bill_no'); ?></b></label>
                            <div class="col-xs-4"><input class="pay_inpt2" type="text" value="" name="billNo" id="billNo"></div>
                        </div>

                        <div class="row">
                            <label for="billDate" class="col-sm-1 control-label color-title"><b><?php echo $this->translate('Saltter_bill_date'); ?></b></label>
                            <div class="col-xs-4"><input type="date" class="form-control" name="billDate" id="billDate" placeholder="" value="<?php echo date('Y-m-d');?>" ></div>
                        </div>

                        <div class="row">
                            <div class="col-xs-1 color-title"><b><?php echo $this->translate('Saltter_tracking_up'); ?></b></div>
                            <div class="col-xs-4"><?php echo $this->ShowWebuploader('', 'PR', 'PRIV', '0'); ?></div>
                        </div>
                    </div>

                    <div class="pay">
                        <label><!--支付密码--><?php echo $this->translate('Saltter_pay_pwd');?></label>
                        <input class="pay_inp" type="password" name="paymentPwd" value="">
                        <input class="pay_btn" type="submit" value="<?php echo $this->translate('confirmed');?>">
                    </div>
                </form>
            </div>

		</div>
	</div>
</div>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footer.phtml'); ?>

<?php echo $this->render(SEED_WWW_TPL . '/layouts/footerLink.phtml'); ?>

<script type="text/javascript">
	$().ready(function() {

	});

	$(function () {
        var select="";
        $.post('/user/settle/banklist',function(json){

            for(var i=0;i<json.length;i++){
                select+="<option value="+json[i].bankAcctID+"|"+json[i].bankAcctName+"|"+json[i].bankAcctNo+ ">" +json[i].bankAcctNo+"&nbsp;&nbsp;|&nbsp;&nbsp;"+json[i].bankName+"&nbsp;&nbsp;|&nbsp;&nbsp;"+ json[i].bankAcctName+"</option>";
            }
            $('#banklist').html(select);
        },"json");
	});

    $('#free_balpay').change(function(){
        var free_balpay=parseFloat($('#free_balpay').val());
        var yuE=<?php echo $this->ShowToPrice($this->paybal_free);?>;
        if(free_balpay>yuE){
            $('#free_balpay').val('0.00');
            $('#free_balyu').after('<span id="yue_tip"><?php echo $this->translate("Saltter_tips23");?></span>')
        }else{
            $('#yue_tip').remove();
        }
    });
</script>
</body>
</html>
