<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>快移</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <link href="/ky/css/base.css" rel="stylesheet">
    <link href="/ky/css/style.css" rel="stylesheet">
    <link href="/ky/css/pay.css" rel="stylesheet">
    <script type="text/javascript" src="/ky/js/jquery.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.wallform.js"></script>
    <script type="text/javascript" src="/ky/js/www.js"></script>
    <script type="text/javascript" src="/ky/js/jquery.movebg.js"></script>
</head>

<body>
<?php echo $this->render(SEED_WWW_TPL . '/header.phtml'); ?>
<div class="o_content_wrap w1200 m0a clearfix">
    <div class="st_tit mt20 mb2 pb10">
        <p class="f18"><!--转账--><?php echo $this->translate('Saltter_Turn');?></p>
    </div>
    <form action="#" method="post">
        <div class="settle_info">
            <div class="pm_view clearfix">
                <div class="">
                    <label class="pm_lab"><!--名称--><?php echo $this->translate('Saltter_Name');?>：</label>
                    <span><?php echo $this->paymentTrading['subject']; ?></span>
                </div>
                <div class="">
                    <label class="pm_lab"><!--金额--><?php echo $this->translate('Saltter_amount');?>：</label>
                    <span style="color: #22ac38;">
                        <?php echo $this->paymentTrading['crnCode'] . '&nbsp;-&nbsp;'  . $this->ShowToPrice($this->paymentTrading['totalAmount']); ?>
                    </span>
                </div>
                <div class="">
                    <label class="pm_lab"><!--收款余额--><?php echo $this->translate('Saltter_amount_rev');?>：</label>
                    <span style="color: #22ac38;">
                        <?php echo $this->paymentTrading['crnCode'] . '&nbsp;-&nbsp;'  . $this->ShowToPrice($this->paymentTrading['balanceAmount']); ?>
                    </span>
                </div>
                <div class="">
                    <label class="pm_lab"><!--发生时间--><?php echo $this->translate('Saltter_GTime');?>：</label>
                    <span><?php if ($this->paymentTrading['recordDate']) {
                            echo date('Y/m/d', strtotime($this->paymentTrading['recordDate']));
                        } ?>
                    </span>
                </div>
                <div class="">
                    <label class="pm_lab"><!--预收付时间--><?php echo $this->translate('Saltter_Time_ING');?>：</label>
                    <span><?php if ($this->paymentTrading['expectedDate']) {
                            echo date('Y/m/d', strtotime($this->paymentTrading['expectedDate']));
                        } ?></span>
                </div>
                <div class="">
                    <label class="pm_lab"><!--摘要--><?php echo $this->translate('Saltter_DEC');?>：</label>
                    <span><?php echo $this->paymentTrading['remarks']; ?></span>
                </div>
            </div>
        </div>
    <div class="pay">
        <label><!--转出定向余额--><?php echo $this->translate('Saltter_out').$this->translate('Saltter_DIFO');?></label>
        <em><?php echo $this->payment['crnCode'];?></em>
        <input class="pay_inpt" type="text" name="directPaymentAmount" readonly="readonly" value="<?php echo $this->ShowToPrice($this->payment['directPaymentAmount']);?>">
        <span class="pay_transfer_sp">
            <!--剩余--><?php echo $this->translate('Saltter_Turn');?>
            <em><?php echo $this->payment['crnCode'];?></em><?php echo $this->ShowToPrice($this->payment['directPaymentAmount']);?><!--可用-->
            <?php echo $this->translate('Saltter_usable');?>
        </span>
    </div>
    <div class="pay">
        <label><!--转出自由余额-->
            <?php echo $this->translate('Saltter_out').$this->translate('Saltter_FREE');?>
        </label>
        <em><?php echo $this->payment['crnCode'];?></em>
        <input id="free_balpay" class="pay_inpt" type="text" name="balPaymentAmount" value="">
        <span id="free_balyu" class="pay_transfer_sp"><!--剩余--><?php echo $this->translate('Saltter_Turn');?>
            <em><?php echo $this->payment['crnCode'];?></em><?php echo $this->ShowToPrice($this->paybal_free);?>
            <!--可用--><?php echo $this->translate('Saltter_usable');?>
        </span>
    </div>
    <div class="pay_bank">
        <label><!--收款银行账号--><?php echo $this->translate('Saltter_amount_bank');?></label>
        <select name="banklist" id="banklist">

        </select>
        <a id="pay_bank_no" target="_blank" href="/user/bank/add">
            <!--添加账号--><?php echo $this->translate('Saltter_bank_add');?></a>
    </div>

    <h2 class="w f16"><!--发票信息--><?php echo $this->translate('Saltter_bill_info');?></h2>
    <div class="pay_ticket">
        <label><!--发票号码--><?php echo $this->translate('Saltter_bill_no');?></label>
        <input class="pay_inpt2" type="text" value="">
    </div>
    <div class="pay_ticket">
        <label><!--开票日期--><?php echo $this->translate('Saltter_bill_date');?></label>
        <script language="javascript" type="text/javascript" src="/ky/My97DatePicker/WdatePicker.js"></script>
        <input class="pay_inpt2" type="text" value="" onfocus="WdatePicker({minDate:'%y-%M-%d',maxDate:'2100-01-01'})">
    </div>
    <div class="pay_ticket">
       <h3 class="f16"><!--发票影像--><?php echo $this->translate('Saltter_tracking_up');?></h3>
        <div style="width: 100%;height: 150px;margin-left: -30px;">  <?php echo $this->ShowWebuploader('', 'PR', 'PRIV', '0'); ?></div>
   </div>
    <div class="pay">
        <label><!--支付密码--><?php echo $this->translate('Saltter_pay_pwd');?></label>
        <input class="pay_inp" type="password" name="paymentPwd" value="">
        <input class="pay_btn" type="submit" value="<?php echo $this->translate('confirmed');?>">
    </div>
    </form>
</div>
<?php echo $this->render(SEED_WWW_TPL . '/footer.phtml'); ?>
<script type="application/javascript">
    $(document).ready(function(){
        var select="";
        $.post('/user/settle/banklist',function(json){

            for(var i=0;i<json.length;i++){
                select+="<option value="+json[i].bankAcctID+"|"+json[i].bankAcctName+"|"+json[i].bankAcctNo+ ">" +json[i].bankAcctNo+"&nbsp;&nbsp;|&nbsp;&nbsp;"+json[i].bankName+"&nbsp;&nbsp;|&nbsp;&nbsp;"+ json[i].bankAcctName+"</option>";
            }
            $('#banklist').html(select);
        },"json");
    });
    $('#free_balpay').change(function(){
        var free_balpay=parseFloat($('#free_balpay').val());
        var yuE=<?php echo $this->ShowToPrice($this->paybal_free);?>;
        if(free_balpay>yuE){
            $('#free_balpay').val('0.00');
            $('#free_balyu').after('<span id="yue_tip"><?php echo $this->translate("Saltter_tips23");?></span>')
        }else{
            $('#yue_tip').remove();
        }
    });

</script>

</body>
</html>